<?php

/**
 * AokprojectsKurzassessmentProblemCourse
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 * ISCP-2625
 * Maria:: Migration CISPC to ISPC 22.07.2020
 * @author elena
 * cloned from
 * @package    ISPC
 * @subpackage Application (2019-01-04)
 * @author     claudiu <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AokprojectsKurzassessmentProblemCourse extends BaseAokprojectsKurzassessmentProblemCourse
{
    /**
     * translations are grouped into an array
     * @var unknown
     */
    const LANGUAGE_ARRAY    = 'assessmentproblemcourse_lang';

    /**
     * define the FORMID and FORMNAME, if you want to piggyback some triggers
     * @var unknown
     */
    const TRIGGER_FORMID    = null;
    const TRIGGER_FORMNAME  = 'frm_assessmentproblemcourse';

    /**
     * insert into patient_files will use this
     */
    const PATIENT_FILE_TABNAME  = 'AssessmentProblemCourse';
    const PATIENT_FILE_TITLE    = 'AssessmentProblemCourse PDF'; //this will be translated

    /**
     * insert into patient_course will use this
     */
    const PATIENT_COURSE_TITLE      = 'AssessmentProblemCourse was created';
    const PATIENT_COURSE_TABNAME    = 'assessmentproblemcourse';
    const PATIENT_COURSE_TYPE       = ''; // add letter





}