<?php

/**
 * ArtificialEntriesExitsList
 * #ISPC-2512PatientCharts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ISPC
 * @subpackage Application (2020-01-15) ISPC-2508
 * @author     carmen <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 * Ancuta added to Clinic ISPC (CISPC)  on 18.03.2020
 */
class ArtificialEntriesExitsList extends BaseArtificialEntriesExitsList
{
    
    
}