<?php

/**
 * AssessmentProblemStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ISPC
 * @subpackage Application (2019-01-07)
 * @author     claudiu <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AssessmentProblemStatus extends BaseAssessmentProblemStatus
{            
    /**
     * translations are grouped into an array
     * @var unknown
     */
    const LANGUAGE_ARRAY    = 'assessmentproblemstatus_lang';
            
    /**
     * define the FORMID and FORMNAME, if you want to piggyback some triggers
     * @var unknown
     */
    const TRIGGER_FORMID    = null;
    const TRIGGER_FORMNAME  = 'frm_assessmentproblemstatus';
            
    /**
     * insert into patient_files will use this
     */
    const PATIENT_FILE_TABNAME  = 'AssessmentProblemStatus';
    const PATIENT_FILE_TITLE    = 'AssessmentProblemStatus PDF'; //this will be translated
            
    /**
     * insert into patient_course will use this
     */
    const PATIENT_COURSE_TITLE      = 'AssessmentProblemStatus was created';
    const PATIENT_COURSE_TABNAME    = 'assessmentproblemstatus';
    const PATIENT_COURSE_TYPE       = ''; // add letter

    
    
    

}