<?php

/**
 * ConnectionMaster
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ISPC
 * @subpackage Application (2020-06-25)
 * @author     Ancuta <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 * * ISPC-2612 Ancuta 25.06.2020
 */
class ConnectionMaster extends BaseConnectionMaster
{            
    /**
     * translations are grouped into an array
     * @var unknown
     */
    const LANGUAGE_ARRAY    = 'connectionmaster_lang';
            
    /**
     * define the FORMID and FORMNAME, if you want to piggyback some triggers
     * @var unknown
     */
    const TRIGGER_FORMID    = null;
    const TRIGGER_FORMNAME  = 'frm_connectionmaster';
            
    /**
     * insert into patient_files will use this
     */
    const PATIENT_FILE_TABNAME  = 'ConnectionMaster';
    const PATIENT_FILE_TITLE    = 'ConnectionMaster PDF'; //this will be translated
            
    /**
     * insert into patient_course will use this
     */
    const PATIENT_COURSE_TITLE      = 'ConnectionMaster PDF was created';
    const PATIENT_COURSE_TABNAME    = 'connectionmaster';
    const PATIENT_COURSE_TYPE       = ''; // add letter

    
    
    

}