<?php

/**
 * CrisisMedication
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ISPC
 * @subpackage Application (2018-09-13)
 * @author     carmen <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CrisisMedication extends BaseCrisisMedication
{
	/**
	 * define the FORMID and FORMNAME, if you want to piggyback some triggers
	 * @var unknown
	 */
	const TRIGGER_FORMID    = null;
	const TRIGGER_FORMNAME  = '';
	
	public function get_set_crisis_medication($bid = null)
	{
		$actions_sql = Doctrine_Query::create()
		->select('*')
		->from('CrisisMedication')
		->where('bid =?', $bid);
	
		$actionsarray = $actions_sql->fetchArray();
	
		if($actionsarray)
		{
			return $actionsarray;
		}
	}
	
	public function get_crisis_medication_group_by_set()
	{
		$actions_sql = Doctrine_Query::create()
		->select('*, count(*) as entries')
		->from('CrisisMedication')
		->groupBy('bid');
	
		$actionsarray = $actions_sql->fetchArray();
	
		if($actionsarray)
		{
			return $actionsarray;
		}
	}

}