<?php

/**
 * ElviUsers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ISPC
 * @subpackage Application (2017-11-13)
 * @author     claudiu <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ElviUsers extends BaseElviUsers
{
    /** 
     * passExtenal will be sha512( $userid . time() )
     * 
     * @param unknown $value
     * @param string $load
     * @param unknown $fieldName
     * @return Ambigous <ElviUsers, Doctrine_Record>
     */
    protected function setUserpassAtVendor($value, $load = true, $fieldName)
    {   
        if ( ! empty($value) && $load === true) {            
        	$value = Zend_Crypt::hash('SHA512', $value . time());
        }        
        
        return $this->_set($fieldName, $value, $load);
    }

    /**
     * will be "ispcUser_{$user_id}"
     * 
     * @param unknown $value
     * @param string $load
     * @param unknown $fieldName
     * @return Ambigous <ElviUsers, Doctrine_Record>
     */
    protected function setUsernameAtVendor($value, $load = true, $fieldName)
    {
    	if ( ! empty($value) && $load === true) {
        	$prefix = "ispcUser_";        	
            $value =  strpos($value, $prefix) === 0 ? $value : $prefix . $value;
    	}
    	
    	return $this->_set($fieldName, $value, $load);
    }
    
}