<?php

/**
 * ElviTransactions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ISPC
 * @subpackage Application (2017-11-13)
 * @author     claudiu <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ElviTransactions extends BaseElviTransactions
{
//     private $response;
    

    protected function setProcessToken($value, $load = true, $fieldName)
    {
        if ($load === true || empty($value)) {
            $value = new Doctrine_Expression('UUID()');
        }
        
        return $this->_set($fieldName,  $value, $load);
    }
    
    
    protected function setRequest($value, $load = true, $fieldName)
    {
        
        if (APPLICATION_ENV == 'development') {
            if ( ! empty($value) && ! empty($value['action']) && empty($this->action)) {
                $this->_set('action',  $value['action'], $load);
            }
        }
        
//         Zend_Json::$useBuiltinEncoderDecoder = true;
//         return $this->_set($fieldName,  Zend_Json::encode($value), $load);
        return $this->_set($fieldName,  $value, $load);
    }
    
    
    
}