<?php

/**
 * FormBlockCustom
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ISPC
 * @subpackage Application (2019-09-16)
 * @author     carmen <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 * ISPC-2454 
 */
class FormBlockCustom extends BaseFormBlockCustom
{            
    /**
     * translations are grouped into an array
     * @var unknown
     */
    const LANGUAGE_ARRAY    = 'formblockcustom_lang';
            
    /**
     * define the FORMID and FORMNAME, if you want to piggyback some triggers
     * @var unknown
     */
    const TRIGGER_FORMID    = null;
    const TRIGGER_FORMNAME  = 'frm_formblockcustom';
            
    /**
     * insert into patient_files will use this
     */
    const PATIENT_FILE_TABNAME  = 'FormBlockCustom';
    const PATIENT_FILE_TITLE    = 'FormBlockCustom PDF'; //this will be translated
            
    /**
     * insert into patient_course will use this
     */
    const PATIENT_COURSE_TYPE       = 'K'; // add letter
    const PATIENT_COURSE_TABNAME    = 'formblockcustom';
    
    //this is just for demo, another one is used on contact_form save
    const PATIENT_COURSE_TITLE      = '';

    
    
    

}