<?php

/**
 * GoogleapisDistancematrix
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ISPC
 * @subpackage Application (2018-09-24)
 * @author     claudiu <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class GoogleapisDistancematrix extends BaseGoogleapisDistancematrix
{

}