<?php

/**
 * IntenseConnectionsClients
 * ISPC-2614 Ancuta 16.07.2020
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ISPC
 * @subpackage Application (2020-07-06)
 * @author     Ancuta <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class IntenseConnectionsClients extends BaseIntenseConnectionsClients
{            
    /**
     * translations are grouped into an array
     * @var unknown
     */
    const LANGUAGE_ARRAY    = 'intenseconnectionsclients_lang';
            
    /**
     * define the FORMID and FORMNAME, if you want to piggyback some triggers
     * @var unknown
     */
    const TRIGGER_FORMID    = null;
    const TRIGGER_FORMNAME  = 'frm_intenseconnectionsclients';
            
    /**
     * insert into patient_files will use this
     */
    const PATIENT_FILE_TABNAME  = 'IntenseConnectionsClients';
    const PATIENT_FILE_TITLE    = 'IntenseConnectionsClients PDF'; //this will be translated
            
    /**
     * insert into patient_course will use this
     */
    const PATIENT_COURSE_TITLE      = 'IntenseConnectionsClients PDF was created';
    const PATIENT_COURSE_TABNAME    = 'intenseconnectionsclients';
    const PATIENT_COURSE_TYPE       = ''; // add letter

    
    
    

}