<?php
Doctrine_Manager::getInstance()->bindComponent('InvoicePaymentsImport', 'SYSDAT');
/**
 * InvoicePaymentsImport
 *
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ISPC
 * @subpackage Application (2020-08-19) ISPC-2623
 * @author     carmen <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 *
 */
class InvoicePaymentsImport extends BaseInvoicePaymentsImport
{
    
    
}