<?php

/**
 * InvoiceSystemPayments
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ISPC
 * @subpackage Application (2018-06-19)
 * @author     Ancuta <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class InvoiceSystemPayments extends BaseInvoiceSystemPayments
{

		public function delete_invoice_payment($invoice_type = false, $payment)
		{
		    
		    if( ! $invoice_type){
		        return false;
		    }
		    
		    
			if($payment > 0)
			{
				$delInvoicePayment = Doctrine_Query::create()
					->update("InvoiceSystemPayments")
					->set('isdelete', "1")
					->where('id = ?',$payment)
					->andWhere('invoice_type = ?',$invoice_type);
				$d = $delInvoicePayment->execute();

				if($d)
				{
					return true;
				}
				else
				{
					return false;
				}
			}
			else
			{
				return false;
			}
		}

		public function getInvoicePayments($invoice_type=false,$invoice)
		{
		    if( ! $invoice_type){
		        return false;
		    }
		    
		    if( empty($invoice)){
		        return false;
		    }
		    
			$invoices = Doctrine_Query::create()
				->select("*")
				->from('InvoiceSystemPayments')
				->Where("invoice = ?", $invoice)
				->andWhere("invoice_type = ?", $invoice_type)
				->andWhere('isdelete = 0');
			$itemInvArray = $invoices->fetchArray();
			
			return $itemInvArray;
		}

		public function getInvoicesPaymentsSum($invoice_type=false,$invoiceids)
		{
		    if( ! $invoice_type){
		        return false;
		    }
		    if( empty($invoiceids)){
		        return false;
		    }
		    

			$invoices = Doctrine_Query::create()
				->select("*, SUM(amount) as paid_sum")
				->from('InvoiceSystemPayments')
				->WhereIn("invoice", $invoiceids)
				->andWhere('invoice_type = ?',$invoice_type)
				->andWhere('isdelete = 0')
				->groupBy('invoice');
			$items_array = $invoices->fetchArray();
			
			foreach($items_array as $kpay => $vpay)
			{
				$final_invoice_items[$vpay['invoice']]['paid_sum'] = $vpay['paid_sum'];
			}
			
			return $final_invoice_items;
		}

	}