<?php

/**
 * MedicationsSetsItems
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * ISPC-2247 pct.1 Lore 05.05.2020
 *
 * @package    ISPC
 * @subpackage Application (2020-05-05) ISPC-2247
 * @author     Lore <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MedicationsSetsItemsDosage extends BaseMedicationsSetsItemsDosage
{
	/**
	 * define the FORMID and FORMNAME, if you want to piggyback some triggers
	 * @var unknown
	 */
	const TRIGGER_FORMID    = null;
	const TRIGGER_FORMNAME  = '';
	
		
	public function get_dosage_by_set($bid = null)
	{
	    $actions_sql = Doctrine_Query::create()
	    ->select('*')
	    ->from('MedicationsSetsItemsDosage')
	    ->where('bid_id =?', $bid)
	    ->andWhere('isdelete = 0');
	    
	    $dosage_array = $actions_sql->fetchArray();
	    
	    if($dosage_array)
	    {
	        return $dosage_array;
	    }
	}
	
	
	public function save_form_medication_dosage_set(array $data = array())
	{
	    
	    $dsg_arr = MedicationsSetsItemsDosage::get_dosage_by_set($data['bid']);
	    
	    if(!empty($dsg_arr)){

	        foreach($dsg_arr as $keyd => $vald){
	            
	            $dsg_upd = Doctrine::getTable('MedicationsSetsItemsDosage')->find($vald['id']);
	            if($dsg_upd)
	            {
	                $dsg_upd->isdelete = '1';
	                $dsg_upd->save();
	            }
	        }
	    } 
    
        foreach($data['set'] as $keym => $valsm){
            
            if(!empty($valsm['dosage_arr']) && !empty($valsm['dosage_arr_schema'])){
               
                foreach($valsm['dosage_arr'] as $keyarr => $vals_arr){
                    
                    if($valsm['hidd_medication'] == '') {
                        $medicati_id = $data['newhidd_medication'][$keym];
                    } else {
                        $medicati_id = $valsm['hidd_medication'];
                    }
                    
                    $set_dsg = new MedicationsSetsItemsDosage();
                    $set_dsg->bid_id = $data['bid'];
                    $set_dsg->medication_id = $medicati_id;
                    $set_dsg->dosage = $vals_arr;
                    $set_dsg->dosage_time_interval = $valsm['dosage_arr_schema'][$keyarr];
                    $set_dsg->save();
                }
            }

        }

        return true;
	}
	
	public function get_set_dosage_and_schema_group_by_medi($bid = null)
	{
	    $sets_values_dosage_arr = MedicationsSetsItemsDosage::get_dosage_by_set($bid);
	    
	    if(!empty($sets_values_dosage_arr)){
	        $dosage_sets_medication = array();
	        
	        foreach($sets_values_dosage_arr as $key => $vals)
	        {
	            $dosage_sets_medication[$vals['medication_id']]['dosage_arr'][] = $vals['dosage'];
	            $dosage_sets_medication[$vals['medication_id']]['dosage_arr_schema'][] = $vals['dosage_time_interval'];
	        }
	        
	        return $dosage_sets_medication;
	    } else {
	        return false;
	    }
	}
	
	public function get_dosage_by_set_and_medication($bid = null, $medication_id = null)
	{
	    $actions_sql = Doctrine_Query::create()
	    ->select('*')
	    ->from('MedicationsSetsItemsDosage')
	    ->where('bid_id =?', $bid)
	    ->andWhere('medication_id =?', $medication_id)
	    ->andWhere('isdelete = 0');
	    
	    $dosage_array = $actions_sql->fetchArray();
	    
	    if($dosage_array)
	    {
	        return $dosage_array;
	    }
	}
	    

}


