<?php

/**
 * MenuGroups
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ISPC
 * @subpackage Application (2021-01-29)
 * @author     Ancuta <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MenuGroups extends BaseMenuGroups
{            
    /**
     * translations are grouped into an array
     * @var unknown
     */
    const LANGUAGE_ARRAY    = 'menugroups_lang';
            
    /**
     * define the FORMID and FORMNAME, if you want to piggyback some triggers
     * @var unknown
     */
    const TRIGGER_FORMID    = null;
    const TRIGGER_FORMNAME  = 'frm_menugroups';
            
    /**
     * insert into patient_files will use this
     */
    const PATIENT_FILE_TABNAME  = 'MenuGroups';
    const PATIENT_FILE_TITLE    = 'MenuGroups PDF'; //this will be translated
            
    /**
     * insert into patient_course will use this
     */
    const PATIENT_COURSE_TITLE      = 'MenuGroups PDF was created';
    const PATIENT_COURSE_TABNAME    = 'menugroups';
    const PATIENT_COURSE_TYPE       = ''; // add letter

    //ISPC-2782 CRISTI C.
    public static function getGroups($details = false)
    {
        $logininfo = new Zend_Session_Namespace('Login_Info');
        $clientid = $logininfo->clientid;
        
        $fdoc = Doctrine_Query::create()
        ->select('*')
        ->from('MenuGroups indexBy id')
        ->where('isdelete = 0 ');
        
        $grouprray = $fdoc->fetchArray(); // proper way

        if($details){
            return $grouprray;
        }
        
        $groups = array();
        $groups= array("0" => "Select Parent");
        
        foreach($grouprray as $group)
        {
            $groups[$group['id']] = $group['menu_group_name'];
        }
        return $groups;
    }
    
    

}