<?php

/**
 * MePatientQrCodes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ISPC
 * @subpackage Application (2020-01-29)
 * @author     Ancuta <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 * ISPC-2432 Ancuta 29.01.2020
 */
class MePatientQrCodes extends BaseMePatientQrCodes
{            
    /**
     * translations are grouped into an array
     * @var unknown
     */
    const LANGUAGE_ARRAY    = 'mepatientqrcodes_lang';
            
    /**
     * define the FORMID and FORMNAME, if you want to piggyback some triggers
     * @var unknown
     */
    const TRIGGER_FORMID    = null;
    const TRIGGER_FORMNAME  = 'frm_mepatientqrcodes';
            
    /**
     * insert into patient_files will use this
     */
    const PATIENT_FILE_TABNAME  = 'MePatientQrCodes';
    const PATIENT_FILE_TITLE    = 'MePatientQrCodes PDF'; //this will be translated
            
    /**
     * insert into patient_course will use this
     */
    const PATIENT_COURSE_TITLE      = 'MePatientQrCodes PDF was created';
    const PATIENT_COURSE_TABNAME    = 'mepatientqrcodes';
    const PATIENT_COURSE_TYPE       = ''; // add letter

    
    function qr_identifier_generate()
    {
        $code_nr = rand(10000000,99999999); 
        $code = $code_nr;
        
        $devices_codes = Doctrine_Query::create()
        ->select('*')
        ->from('MePatientQrCodes')
        ->where("qr_identifier =?", $code)
        ->fetchArray();
        
        if(!empty($devices_codes))
        {
            return $this->qr_identifier_generate();
        }
        else
        {
            return $code;
        }
        
    }
    

}