<?php

/**
 * MePatientRequestsNotProcessed
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ISPC
 * @subpackage Application (2020-03-12)
 * @author     Ancuta <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MePatientRequestsNotProcessed extends BaseMePatientRequestsNotProcessed
{            
    /**
     * translations are grouped into an array
     * @var unknown
     */
    const LANGUAGE_ARRAY    = 'mepatientrequestsnotprocessed_lang';
            
    /**
     * define the FORMID and FORMNAME, if you want to piggyback some triggers
     * @var unknown
     */
    const TRIGGER_FORMID    = null;
    const TRIGGER_FORMNAME  = 'frm_mepatientrequestsnotprocessed';
            
    /**
     * insert into patient_files will use this
     */
    const PATIENT_FILE_TABNAME  = 'MePatientRequestsNotProcessed';
    const PATIENT_FILE_TITLE    = 'MePatientRequestsNotProcessed PDF'; //this will be translated
            
    /**
     * insert into patient_course will use this
     */
    const PATIENT_COURSE_TITLE      = 'MePatientRequestsNotProcessed PDF was created';
    const PATIENT_COURSE_TABNAME    = 'mepatientrequestsnotprocessed';
    const PATIENT_COURSE_TYPE       = ''; // add letter

    
    
    

}