<?php

/**
 * NordrheinBilling
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ISPC
 * @subpackage Application (2018-11-28)
 * @author     Ancuta <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class NordrheinBilling extends BaseNordrheinBilling
{

    /**
     * Ancuta 07.12.2018 ISPC-2286
     * @param unknown $ipids
     * @param string $period
     * @param string $invoice_results
     * @return Ambigous <string, unknown>|boolean
     */

    
    public function saved_data($ipids, $period = false, $invoice_results = false)
    {
        if (empty($ipids)) {
            return false;
        }
        
        if ( ! is_array($ipids)) {
            $ipids = array($ipids);
        } 
        
        if ( ! empty($ipids)) {
            $query = Doctrine_Query::create()
                ->select('*')
                ->from('NordrheinBilling')
                ->where('isdelete = "0"');
            if($period){
                foreach ($ipids as $k_ipid => $v_ipid) {
                    $or_sql[] = '(ipid = "' . $v_ipid . '" AND date BETWEEN "' . date('Y-m-d', strtotime($period[$v_ipid]['start'])) . '" AND "' . date('Y-m-d', strtotime($period[$v_ipid]['end'])) . '")';
                }
                $query->andWhere(implode(' OR ', $or_sql));
            } else{
                $query->andWhereIn('ipid',$ipids);
            }
            $q_res = $query->fetchArray();
            
            if ($q_res) {
                
                $saved_data = array();
                foreach ($q_res as $k_res => $v_res) 
                {
                    $value = '0';
                    if ($invoice_results) 
                    {
                        
                        $value = $v_res['value'];
                        $saved_data[$v_res['ipid']][date('d.m.Y', strtotime($v_res['date']))][$v_res['shortcut']] = $value;
                    } 
                    else 
                    {
                        $value = $v_res['value'];
                        $saved_data[$v_res['ipid']][$v_res['shortcut']][date('d.m.Y', strtotime($v_res['date']))] = $v_res['value'];
                    }
                }
                
                return $saved_data;
            } else {
                return false;
            }
        }
    }
    
    
    /**
     * Ancuta 29.11.2018 ISPC-2286
     * @param number $clientid
     * @param unknown $ipids
     * @param string $period
     * @param string $patients_periods
     * @return multitype:
     */
    
    public function nr_billable_actions($clientid = 0, $ipids = array(), $period = false, $patients_periods = false){
        
        if( empty($ipids) || empty($clientid)){
            return array();
        }
        $patientmaster_obj = new PatientMaster();

        
        //get all shortcuts
        $InvoiceSystem_obj = new InvoiceSystem(); 
        $shortcuts_arr = $InvoiceSystem_obj->invoice_products('nr_invoice');
        
        
        if(empty($patients_periods) && empty($period)){
            return array();
        }
        
        if(empty($patients_periods) && !empty($period))
        {
            foreach($ipids as $ipid)
            {
                $patients_periods[$ipid] = $period;
                $patients_periods[$ipid]['days'] = $patientmaster_obj->getDaysInBetween($period['start'], $period['end'],false,"d.m.Y");
            }
        }
 
        
        // get User details
        $user_m = new User();
        //$all_users = $user_m->getClientsUsers(array($clientid),true);
        $all_users = $user_m->get_clients_users(array($clientid));    //TODO-2862 Lore 30.01.2020

        $user_shortcut = array();
        foreach($all_users as $k=>$udata){
            if(empty($udata['shortname'])){
               $user_shortcut[$udata['id']] = mb_substr($udata['first_name'], 0, 1, "UTF-8") . "" . mb_substr($udata['last_name'], 0, 1, "UTF-8");
            } else {
                $user_shortcut[$udata['id']] = $udata['shortname'];
            }
        }
        
        // get patient treatment days
        $conditions['periods'][0]['start'] = '2009-01-01';
        $conditions['periods'][0]['end'] = date('Y-m-d');
        $conditions['client'] = $clientid;
        $conditions['ipids'] = $ipids;
        
        //beware of date d.m.Y format here
        $patient_days = array();
        $patient_days = Pms_CommonData::patients_days($conditions);
       
        $patient_details  =array();
        
        $overall_treatment_days = array();
        $overall_hospiz_days = array();
        
        foreach($patient_days as $k_pat => $pat_details)
        {
            usort($pat_details['treatment_days'], array(new Pms_Sorter(), "_date_compare"));
            $overall_treatment_days[$k_pat] = $pat_details['treatment_days'];
            
            // hospiz days 
            //$pat_details['hospiz']['real_days_cs']
            usort($pat_details['hospiz']['real_days_cs'], array(new Pms_Sorter(), "_date_compare"));
            $overall_hospiz_days[$k_pat] = $pat_details['hospiz']['real_days_cs'];
        }
        

        $patient_days2locationtypes = array();
        $all_patient_active_days = array();
        foreach ($patient_days as $k_patient => $patient_data) {
            
            $all_patient_active_days[$k_patient] = $patient_data['real_active_days'];
            
            foreach ($patient_data['locations'] as $pat_location_row_id => $pat_location_data) {
                foreach ($pat_location_data['days'] as $kl => $lday) {
                    if (in_array($lday, $patient_data['real_active_days'])) {
                        
                        if (empty($pat_location_data['type'])) {
                            $pat_location_data['type'] = 0;
                        }
                        
                        if ($pat_location_data['discharge_location'] != 1) {
                            $patient_days2locationtypes[$k_patient][$lday][] = $pat_location_data['type'];
                        }
                    }
                }
            }
        }
        
        // locations
        $location_mapping = $InvoiceSystem_obj->invoice_locations_mapping('nr_invoice');
        
        $loc_types2loc_ident = array();
        foreach ($location_mapping as $loc_ident => $loc_details) {
            
            foreach ($loc_details['location_type'] as $k => $loc_type) {
                
                $loc_types2loc_ident[$loc_type] = $loc_ident;
            }
        }
        
        foreach ($patient_days2locationtypes as $pipid => $locdata) {
            foreach ($locdata as $loc_day => $day_loc_types) {
                $del_val = "1";
                if (! in_array($loc_day, $hospital_days_cs_dmY[$pipid]) && ($key = array_search($del_val, $day_loc_types)) !== false) {
                    unset($patient_days2locationtypes[$pipid][$loc_day][$key]);
                }
            }
        }
        
        foreach ($patient_days2locationtypes as $pipid => $locdata) {
            foreach ($locdata as $loc_day => $day_loc_types) {
                $patient_days2locationtypes[$pipid][$loc_day] = end($day_loc_types);
            }
        }
        
        
        //patient discharged dead START
        $discharge_methods = DischargeMethod::getDischargeMethod($clientid);
        
        $dead_abbr = array("tod","verstorben");
        $tod_ids = array();
        foreach($discharge_methods as $k=> $dis_data){
            if(in_array(strtolower($dis_data['abbr']),$dead_abbr  )){
                $tod_ids[] = $dis_data['id'];
            }
        }
        	
        $discharged_tod_res = array();
        if(!empty($tod_ids))
        {
            $dispat = Doctrine_Query::create()
            ->select("*")
            ->from("PatientDischarge")
            ->whereIn("ipid", $ipids )
            ->andWhereIn("discharge_method", $tod_ids)
            ->andWhere('isdelete = "0"');
            $discharged_tod_res = $dispat->fetchArray();
        }
        
        $discharge_death_date = array();
        $dead_patients = array();
        foreach($discharged_tod_res as $k=>$discharge_detah_details)
        {
            $discharge_death_date[$discharge_detah_details['ipid']] = $discharge_detah_details['discharge_date'];
            $dead_patients[] = $discharge_detah_details['ipid'];
        }
        //patient discharged dead END

        
        $dead_in_valid_48h = array();
        foreach($ipids as $ipid)
        {
            if( ! empty($overall_treatment_days[$ipid])){
                $patient_days[$ipid]['first_28_days'] = array_slice($overall_treatment_days[$ipid], 0,28);
                $patient_days[$ipid]['after_day_29'] = array_slice($overall_treatment_days[$ipid], 28);
        
                if(in_array($ipid, $dead_patients) && count($overall_treatment_days[$ipid]) <= 2){
                    $patient_days[$ipid]['valid_48h'] = $overall_treatment_days[$ipid];
                    $dead_in_valid_48h[$ipid][] = date('d.m.Y',strtotime($discharge_death_date[$ipid]));
                }
            }
        }

        $treatment_hours = array();
        if( ! empty($dead_patients)){

            $patient_falls = array();
            foreach($dead_patients as $dipid){
                $patient_falls[$dipid] = PatientReadmission::findFallsOfIpid(array($dipid));
            }
            
            $treatment_hours = array();
            foreach($patient_falls as $ipid => $readm_periods ){
                
                $treatment_hours[$ipid] = 0; 
                foreach($readm_periods as $period_ident => $pert){
                    $treatment_hours[$ipid] += (strtotime($pert['discharge']['date'])   - strtotime($pert['admission']['date'])) / (60*60);  
                }
            }
        }

        //get sapv data START
        $sapv_array = SapvVerordnung::get_patients_sapv_periods($ipids,true);
        
        $patients2highest_sapv = array();
        $patients2sapv_type = array();
        foreach($sapv_array as $sapv_ipid => $sapv_item)
        {
            foreach($sapv_item as $sapv_id => $sapv_data)
            {
                foreach($sapv_data['days'] as $ks => $s_day)
                {
                    $patients2highest_sapv[$sapv_ipid][$s_day] = $sapv_data['highest'];
                    $patient_days[$sapv_ipid]['sapv_days'][] = $s_day;
                    foreach($sapv_data['types_arr'] as $stype)
                    {
                        $patients2sapv_type[$sapv_ipid][$stype][] = $s_day;
                    }
                }
            }
        }
        //get sapv data END
        

        //get patient TELEFONAT (XT) / Beratung (U) START
        $course_array = array();
        $course_array = PatientCourse::get_multi_pat_shortcuts_course($ipids, array('XT','U'));
        
        $course_data = array();
        $course_entries = array();
        $x = 0 ;
        foreach($course_array as $key_course => $course_value)
        {
            
            $course_value_date = date('Y-m-d', strtotime($course_value['done_date']));
            $course_value_date_dmy = date('d.m.Y', strtotime($course_value['done_date']));
            if( in_array(date('d.m.Y', strtotime($course_value['done_date'])), $patient_days[$course_value['ipid']]['sapv_days']) 
                &&  in_array (date('d.m.Y', strtotime($course_value['done_date'])),$patient_days[$course_value['ipid']]['real_active_days'] )
               )
            {
                // REMOVE CONTACTS AFTER Death time
                if($course_value_date == date('Y-m-d', strtotime($discharge_death_date[$course_value['ipid']])) && strtotime(date('Y-m-d H:i:s', strtotime($course_value['done_date']))) > strtotime($discharge_death_date[$course_value['ipid']])){
                    // do not add
                }
                else{
                    $course_data[$course_value['ipid']][$course_value_date_dmy][$course_value['course_type']][] = $course_value;
                    $course_dates[$course_value['ipid']][$course_value['course_type']][] = $course_value_date;
                    
                    $done_date = (!empty($course_value['done_date'])) ? $course_value['done_date'] : $course_value['course_date'];
                    
                    
                    
                    
                    // calculate duration to find out end time and done date
                    $duration = "";
                    $coursearr = array();
                    $coursearr = explode("|", $course_value['course_title']);
        
                    
                    if(count($coursearr) == 3)
                    { //method implemented with 3 inputs
                        $duration  = intval($coursearr[0]);
                    }
                    else if(count($coursearr) != 3 && count($coursearr) < 3)
                    { //old method before anlage 10
                        $duration  = intval($coursearr[0]);
                    }
                    else if(count($coursearr) != 3 && count($coursearr) > 3)
                    { //new method (U) 3 inputs and 1 select newly added in verlauf
                        $duration  = intval($coursearr[1]);
                    }
                    if(empty($done_date)){
                        $done_date = end($coursearr);
                    }
                    
                    $done_date_dmy = date('d.m.Y',strtotime($done_date));
                    $full_done_date_dmy = date('d.m.Y H:i:s',strtotime($done_date));
                    $full_done_date_Ymd = date('Y-m-d H:i:s',strtotime($done_date));
                    
                    $course_entries[$course_value['ipid']][$done_date_dmy][$x] = $course_value;
                    $minutes = "";
                    $minutes = "+".$duration." minutes";
                    $course_entries[$course_value['ipid']][$done_date_dmy][$x]['full_done_date'] = $full_done_date_Ymd;
                    $course_entries[$course_value['ipid']][$done_date_dmy][$x]['date'] = date("Ymd",strtotime($done_date));
                    $course_entries[$course_value['ipid']][$done_date_dmy][$x]['start_date'] = date("Y-m-d H:i:s",strtotime($done_date));
                    $course_entries[$course_value['ipid']][$done_date_dmy][$x]['time_from'] = date("Hi",strtotime($done_date));
                    $course_entries[$course_value['ipid']][$done_date_dmy][$x]['time_till'] = date("Hi",strtotime($minutes, strtotime($done_date)));
                    $course_entries[$course_value['ipid']][$done_date_dmy][$x]['end_date'] = date("Y-m-d H:i:s",strtotime($minutes, strtotime($done_date)));
                    $course_entries[$course_value['ipid']][$done_date_dmy][$x]['pdf_time_from'] = date("H:i",strtotime($done_date));
                    
                    $x++;
                }
            }
        }
        
        $course_entries_sorted = array();
        foreach($course_entries as $k_pat => $pat_course_date)
        {
            foreach($pat_course_date as $dates=>$date_values)
            {
                usort($date_values, array(new Pms_Sorter('full_done_date'), "_date_compare"));
                $course_entries_sorted[$k_pat][$dates] = $date_values;
            }
        }
        
        //get patient TELEFONAT (XT) / Beratung (U)  END
        $previleges = new Modules();
        $include_other_visits = $previleges->checkModulePrivileges("181",$clientid);
 
        
        //GET ALL VISITS
        $patients_visits  = array();
        
        if($include_other_visits)
        {
            // Kvno doctor visits -START
            $doctor_visits = array();
            $doctor_visits= KvnoDoctor::get_visits_multiple($ipids);
            // remove visits after death time
            foreach($doctor_visits as $kvno_doc_id => $kvno_doc_vval)
            {
                if(is_numeric($kvno_doc_id) && !empty($discharge_death_date[$kvno_doc_vval['ipid']]))
                {
                    if(strtotime(date('Y-m-d H:i:s', strtotime($kvno_doc_vval['start_date']))) > strtotime($discharge_death_date[$kvno_doc_vval['ipid']]) && $patient_days[$kvno_doc_vval['ipid']]['details']['isdischarged'] == '1')
                    {
                        unset($doctor_visits[$kvno_doc_id]);
                    }
                }
            }
            foreach($doctor_visits as $kvdoc_id =>$kvd_data){
                $patients_visits[$kvd_data['ipid']][date("d.m.Y",strtotime($kvd_data['start_date']))][] = 'kv_doc-'.$kvd_data['id'];
            }
            // Kvno doctor visits END        
            
    
            // Kvno nurse visits -START        
            $nurse_visits = array();
            $nurse_visits= KvnoNurse::get_visits_multiple($ipids);
            // remove visits after death time
            foreach($nurse_visits as $kvno_nur_id => $kvno_nur_vval)
            {
                if(is_numeric($kvno_nur_id) && !empty($discharge_death_date[$kvno_nur_vval['ipid']]))
                {
                    if(strtotime(date('Y-m-d H:i:s', strtotime($kvno_nur_vval['start_date']))) > strtotime($discharge_death_date[$kvno_nur_vval['ipid']]) && $patient_days[$kvno_nur_vval['ipid']]['details']['isdischarged'] == '1')
                    {
                        unset($nurse_visits[$kvno_nur_id]);
                    }
                }
            }
            
            foreach($nurse_visits as $kvnur_id =>$kvn_data){
                $patients_visits[$kvn_data['ipid']][date("d.m.Y",strtotime($kvn_data['start_date']))][] = 'kv_nur-'.$kvn_data['id'];
            }
            // Kvno nurse visits END        
        }
        
        
        //Contact forms START
        $contact_forms_all = ContactForms::get_contactforms_multiple($ipids);
        // remove contacts after death time
        $contact_forms_ids = array();
        foreach($contact_forms_all as $kcf => $v_cf)
        {
            $contact_forms_ids[] = $v_cf['id'];
            
            if(is_numeric($kcf) && !empty($discharge_death_date[$v_cf['ipid']]))
            {
                if(strtotime(date('Y-m-d H:i:s', strtotime($v_cf['start_date']))) > strtotime($discharge_death_date[$v_cf['ipid']]) && $patient_days[$v_cf['ipid']]['details']['isdischarged'] == '1')
                {
                    unset($contact_forms_all[$kcf] );
                }
            }
        }
        // get Additional users
        $block_aditional_users = new FormBlockAdditionalUsers();
        $block_au_data = $block_aditional_users->getPatientFormBlockAdditionalUsers($ipids, $contact_forms_ids,false,true);
        
        $users2cf  = array();
        foreach($contact_forms_all as $k_cf=>$v_cf_data){
            $users2cf[$k_cf] = array();
            $has_creator = false;
            if(count($block_au_data[$v_cf_data['id']]) != 0)
            {
                foreach($block_au_data[$v_cf_data['id']] as $k_block_au_data => $v_block_au)
                {
                    if($v_block_au['creator'] == '1')
                    {
                        $has_creator = true;
                    }
                    $users2cf[$k_cf] [] = $user_shortcut[$v_block_au['additional_user']];
               
                }
            }

            if(count($block_au_data[$v_cf_data['id']]) == '0' || $has_creator === false)
            {
                $users2cf[$k_cf][] = $user_shortcut[$v_cf_data['create_user']];
            }
            
            $contact_forms_all[$k_cf]['user_shortcuts']  = implode(", ",$users2cf[$k_cf]);
        }
      
        $patients_visits_full = array();
        foreach($contact_forms_all as $cf_if =>$cf_data){
            $patients_visits[$cf_data['ipid']][date("d.m.Y",strtotime($cf_data['billable_date']))][] = 'cf-'.$cf_data['id'];
            $patients_visits_full[$cf_data['ipid']][date("d.m.Y",strtotime($cf_data['billable_date']))][] = $cf_data;
        }
        
        
        $patient_visits_sorted = array();
        foreach($patients_visits_full as $v_pat => $pat_vis)
        {
            foreach($pat_vis as $v_dates=>$date_v_values)
            {
                usort($date_v_values, array(new Pms_Sorter('billable_date'), "_date_compare"));
                $patient_visits_sorted[$v_pat][$v_dates] = $date_v_values;
            }
        }
        // Contact forms END
        
        
        // get assessment
        $assessment_forms = array();
        $assessment_forms = Doctrine_Query::create()
        ->select('*')
        ->from('KvnoAssessment')
        ->whereIn("ipid", $ipids )
        ->fetcharray();
        
        $all_assessments = array();
        $completed_assessments = array();
        $a = 0;
        foreach( $assessment_forms as $ass_key => $ass_value){
            if( $ass_value['iscompleted'] == "1" ){
                $ass_complete_date = "";
                $ass_complete_date = date("d.m.Y",strtotime($ass_value['completed_date']));
                $all_assessments[$ass_value['ipid']][] = $ass_complete_date ;      
                $completed_assessments[$ass_value['ipid']][$ass_complete_date][$a] =$ass_value;
                $completed_assessments[$ass_value['ipid']][$ass_complete_date][$a] ['start_date'] = (!empty($ass_value['start_date']) && $ass_value['start_date']!="0000-00-00 00:00:00") ? $ass_value['start_date']:$ass_value['completed_date'];
                $completed_assessments[$ass_value['ipid']][$ass_complete_date][$a] ['time_from'] =  date("Hi",strtotime(  $completed_assessments[$ass_value['ipid']][$a] ['start_date']));
                $completed_assessments[$ass_value['ipid']][$ass_complete_date][$a] ['pdf_time_from'] =  date("H:i",strtotime(  $completed_assessments[$ass_value['ipid']][$a] ['start_date']));
                $completed_assessments[$ass_value['ipid']][$ass_complete_date][$a] ['end_date'] =  $ass_value['completed_date'];
                $completed_assessments[$ass_value['ipid']][$ass_complete_date][$a] ['time_till'] =  date("Hi",strtotime($ass_value['completed_date']));
                
                $ass_user_shortcuts[$ass_value['ipid']][$ass_complete_date][$a] = array();
                if(!empty($ass_value['doc_id']) && $ass_value['doc_id'] != '0'){
                    $ass_user_shortcuts[$ass_value['ipid']][$ass_complete_date][$a][] =  $user_shortcut[$ass_value['doc_id']];
                }
                if(!empty($ass_value['pfl_id']) && $ass_value['pfl_id'] != '0'){
                    $ass_user_shortcuts[$ass_value['ipid']][$ass_complete_date][$a][] = $user_shortcut[$ass_value['pfl_id']];
                }
                
                $completed_assessments[$ass_value['ipid']][$ass_complete_date][$a] ['users_shortcuts'] =  implode(", ",$ass_user_shortcuts[$ass_value['ipid']][$ass_complete_date][$a]);
                
                $a++;          
            }
        }
        
        // get assessments END
        
        // price list
        $price_list_obj = new PriceList();
        
        $master_price_list = array();
        foreach($ipids as $kmp_ipid => $vmp_ipid)
        {
            $master_price_list[$vmp_ipid] = $price_list_obj->period_price_list_specific_nordrhein($patients_periods[$vmp_ipid]['start'], $patients_periods[$vmp_ipid]['end']);
        }
        
        
        // get saved data 
        $saved_values = array();
        $saved_values = self::saved_data($ipids,false);

        // needed:
        // sapv days
        // active days
        // course data - XT, U
        // Contact forms
        // Assessment
        
        $billed = array();
        $master_data = array();
        foreach($ipids as $ipid)
        {
            foreach($all_patient_active_days[$ipid] as $day)
            {
                if( in_array($day,$patient_days[$ipid]['real_active_days']) && in_array($day,$patient_days[$ipid]['sapv_days']))
                {
                        
                    //$day_location_type = $loc_types2loc_ident[$patient_days2locationtypes[$ipid][date('d.m.Y',strtotime($day))]];
                    //TODO-2668- Ancuta added a comment - if needed please activate: remove all products if NO location type 
                    $day_location_type = strlen($patient_days2locationtypes[$ipid][date('d.m.Y',strtotime($day))]) > 0 ? $loc_types2loc_ident[$patient_days2locationtypes[$ipid][date('d.m.Y',strtotime($day))]] : "";;
                    // --
                    
                    // B1 	
                    // Beratung Grundpauschale (Tag 1-28) 	
                    // can be billed one time per LIFE 	
                    // is billed for FIRST ever XT entry or "Beratung" shortcut in verlauf in the first 28 days of treatment
                    // for B1 you need at least Beratung verordnung (so BE, KO, TV, or VV)
                    
                    $shortcut = "b1";

                    if( isset($saved_values[$ipid][$shortcut][$day]))
                    {
                        $master_data['invoices'][$ipid][$day][$shortcut]['checked']         = $saved_values[$ipid][$shortcut][$day] ;
                        $master_data['invoices'][$ipid][$day][$shortcut]['qty']             = $saved_values[$ipid][$shortcut][$day];
                        $master_data['invoices'][$ipid][$day][$shortcut]['price']           = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price'];
                        $master_data['invoices'][$ipid][$day][$shortcut]['dta_price']       = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_price'];
                        $master_data['invoices'][$ipid][$day][$shortcut]['dta_id']          = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_id'];
                        $master_data['invoices'][$ipid][$day][$shortcut]['location_type']   = $day_location_type;
                        $master_data['invoices'][$ipid][$day][$shortcut]['price_list']      = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price_list'];
                        
                        if(!empty($course_entries_sorted[$ipid][$day]) && $saved_values[$ipid][$shortcut][$day] > 0){
                            $master_data['invoices'][$ipid][$day][$shortcut]['date']            = $course_entries_sorted[$ipid][$day][0]['date'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['start_date']      = $course_entries_sorted[$ipid][$day][0]['start_date'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['end_date']        = $course_entries_sorted[$ipid][$day][0]['end_date'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['time_from']       = $course_entries_sorted[$ipid][$day][0]['time_from'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['time_till']       = $course_entries_sorted[$ipid][$day][0]['time_till'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['pdf_time_from']   = $course_entries_sorted[$ipid][$day][0]['pdf_time_from'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['user_shortcut']   = $user_shortcut[$course_entries_sorted[$ipid][$day][0]['create_user']];
                        }
                        
                        
                        if($saved_values[$ipid][$shortcut][$day] == "1")
                        {
                            $billed[$ipid][$shortcut][] = $day;
                        }
                    }
                    else
                    {
                        //TODO-2845 ISPC : leistungsnachweis Nordrhein 2018 Ancuta 23.01.2020
                        // removed 23.01.2020 $saved_values[$ipid][$shortcut] from condition:
                        if(
                            empty($billed[$ipid][$shortcut])
                            && in_array($day,$patient_days[$ipid]['first_28_days'])
                            && $patients2highest_sapv[$ipid][$day] >= 1
                            && ! empty($course_data[$ipid][$day]) // it has a XT or a U on this day 
                            )
                        {
                            
                            if( ! in_array($day,$billed[$ipid][$shortcut]))
                            {
                                $billed[$ipid][$shortcut][] = $day;
                            }
                            $master_data['invoices'][$ipid][$day][$shortcut]['checked']         = 1;
                            $master_data['invoices'][$ipid][$day][$shortcut]['qty']             = 1;
                            $master_data['invoices'][$ipid][$day][$shortcut]['price']           = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['dta_price']       = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_price'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['dta_id']          = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_id'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['location_type']   = $day_location_type;
                            $master_data['invoices'][$ipid][$day][$shortcut]['price_list']      = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price_list'];
                            
                            if(!empty($course_entries_sorted[$ipid][$day])){
                                $master_data['invoices'][$ipid][$day][$shortcut]['date']            = $course_entries_sorted[$ipid][$day][0]['date'];
                                $master_data['invoices'][$ipid][$day][$shortcut]['start_date']      = $course_entries_sorted[$ipid][$day][0]['start_date'];
                                $master_data['invoices'][$ipid][$day][$shortcut]['end_date']        = $course_entries_sorted[$ipid][$day][0]['end_date'];
                                $master_data['invoices'][$ipid][$day][$shortcut]['time_from']       = $course_entries_sorted[$ipid][$day][0]['time_from'];
                                $master_data['invoices'][$ipid][$day][$shortcut]['time_till']       = $course_entries_sorted[$ipid][$day][0]['time_till'];
                                $master_data['invoices'][$ipid][$day][$shortcut]['pdf_time_from']   = $course_entries_sorted[$ipid][$day][0]['pdf_time_from'];
                                $master_data['invoices'][$ipid][$day][$shortcut]['user_shortcut']   = $user_shortcut[$course_entries_sorted[$ipid][$day][0]['create_user']];
                            }
                        }
                        else 
                        {
                            $master_data['invoices'][$ipid][$day][$shortcut]['checked']         = 0 ;
                            $master_data['invoices'][$ipid][$day][$shortcut]['qty']             = 0;
                            $master_data['invoices'][$ipid][$day][$shortcut]['price']           = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['dta_price']       = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_price'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['dta_id']          = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_id'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['location_type']   = $day_location_type;
                            $master_data['invoices'][$ipid][$day][$shortcut]['price_list']      = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price_list'];
 
                        }
                    }
                    
                    
                    
                            
                    // B2 	
                    // Beratung Folgepauschale (ab Tag 29) 	
                    // can be billed one time per LIFE 	
                    // is billed for FIRST ever XT entry or "Beratung" shortcut in verlauf from day 29 of treatment
                    // for B2 you need at least Beratung verordnung (so BE, KO, TV, or VV)
                    $shortcut = "b2";
                    if( isset($saved_values[$ipid][$shortcut][$day]))
                    {
                        $master_data['invoices'][$ipid][$day][$shortcut]['checked']         = $saved_values[$ipid][$shortcut][$day] ;
                        $master_data['invoices'][$ipid][$day][$shortcut]['qty']             = $saved_values[$ipid][$shortcut][$day];
                        $master_data['invoices'][$ipid][$day][$shortcut]['price']           = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price'];
                        $master_data['invoices'][$ipid][$day][$shortcut]['dta_price']       = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_price'];
                        $master_data['invoices'][$ipid][$day][$shortcut]['dta_id']          = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_id'];
                        $master_data['invoices'][$ipid][$day][$shortcut]['location_type']   = $day_location_type;
                        $master_data['invoices'][$ipid][$day][$shortcut]['price_list']      = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price_list'];
                        

                        if(!empty($course_entries_sorted[$ipid][$day]) && $saved_values[$ipid][$shortcut][$day] > 0){
                            $master_data['invoices'][$ipid][$day][$shortcut]['date']            = $course_entries_sorted[$ipid][$day][0]['date'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['start_date']      = $course_entries_sorted[$ipid][$day][0]['start_date'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['end_date']        = $course_entries_sorted[$ipid][$day][0]['end_date'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['time_from']       = $course_entries_sorted[$ipid][$day][0]['time_from'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['time_till']       = $course_entries_sorted[$ipid][$day][0]['time_till'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['pdf_time_from']   = $course_entries_sorted[$ipid][$day][0]['pdf_time_from'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['user_shortcut']   = $user_shortcut[$course_entries_sorted[$ipid][$day][0]['create_user']];
                        }
                        
                        if($saved_values[$ipid][$shortcut][$day] == "1")
                        {
                            $billed[$ipid][$shortcut][] = $day;
                        }
                    }
                    else
                    {
                        
                        if(
                            empty($billed[$ipid][$shortcut])
                            && in_array($day,$patient_days[$ipid]['after_day_29'])
                            && $patients2highest_sapv[$ipid][$day] >= 2
                            && ! empty($course_data[$ipid][$day]) // it has a XT or a U on this day 
                            )
                        {
                            
                            if( ! in_array($day,$billed[$ipid][$shortcut]))
                            {
                                $billed[$ipid][$shortcut][] = $day;
                            }
                            $master_data['invoices'][$ipid][$day][$shortcut]['checked']         = 1 ;
                            $master_data['invoices'][$ipid][$day][$shortcut]['qty']             = 1;
                            $master_data['invoices'][$ipid][$day][$shortcut]['price']           = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['dta_price']       = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_price'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['dta_id']          = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_id'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['location_type']   = $day_location_type;
                            $master_data['invoices'][$ipid][$day][$shortcut]['price_list']      = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price_list'];
                            

                            if(!empty($course_entries_sorted[$ipid][$day])){
                                $master_data['invoices'][$ipid][$day][$shortcut]['date']            = $course_entries_sorted[$ipid][$day][0]['date'];
                                $master_data['invoices'][$ipid][$day][$shortcut]['start_date']      = $course_entries_sorted[$ipid][$day][0]['start_date'];
                                $master_data['invoices'][$ipid][$day][$shortcut]['end_date']        = $course_entries_sorted[$ipid][$day][0]['end_date'];
                                $master_data['invoices'][$ipid][$day][$shortcut]['time_from']       = $course_entries_sorted[$ipid][$day][0]['time_from'];
                                $master_data['invoices'][$ipid][$day][$shortcut]['time_till']       = $course_entries_sorted[$ipid][$day][0]['time_till'];
                                $master_data['invoices'][$ipid][$day][$shortcut]['pdf_time_from']   = $course_entries_sorted[$ipid][$day][0]['pdf_time_from'];
                                $master_data['invoices'][$ipid][$day][$shortcut]['user_shortcut']   = $user_shortcut[$course_entries_sorted[$ipid][$day][0]['create_user']];
                            }
                        }
                        else 
                        {
                            $master_data['invoices'][$ipid][$day][$shortcut]['checked']         = 0 ;
                            $master_data['invoices'][$ipid][$day][$shortcut]['qty']             = 0;
                            $master_data['invoices'][$ipid][$day][$shortcut]['price']           = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['dta_price']       = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_price'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['dta_id']          = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_id'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['location_type']   = $day_location_type;
                            $master_data['invoices'][$ipid][$day][$shortcut]['price_list']      = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price_list'];
               
                        }
                    }

                    
                    
                    
                    // K1 	
                    // Koordination/Assessment Grundpauschale (Tag 1-28) 	
                    // for 1-n assessment forms being filled in the days 1- 28 	
                    // is billed for the ASSESMENT being filled 
                    // for K1  you need at least Koordination verordnung (so BE, KO, TV, or VV)
    
                    $shortcut = "k1";
                    if( isset($saved_values[$ipid][$shortcut][$day]))
                    {
                        $master_data['invoices'][$ipid][$day][$shortcut]['checked']         = $saved_values[$ipid][$shortcut][$day] ;
                        $master_data['invoices'][$ipid][$day][$shortcut]['qty']             = $saved_values[$ipid][$shortcut][$day];
                        $master_data['invoices'][$ipid][$day][$shortcut]['price']           = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price'];
                        $master_data['invoices'][$ipid][$day][$shortcut]['dta_price']       = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_price'];
                        $master_data['invoices'][$ipid][$day][$shortcut]['dta_id']          = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_id'];
                        $master_data['invoices'][$ipid][$day][$shortcut]['location_type']   = $day_location_type;
                        $master_data['invoices'][$ipid][$day][$shortcut]['price_list']      = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price_list'];
                        
                        if(!empty($completed_assessments[$ipid][$day]) && $saved_values[$ipid][$shortcut][$day] > 0 ){
                            $completed_assessments[$ipid][$day] = array_values($completed_assessments[$ipid][$day]);  // Ancuta  31.08.2020 - issues with 0 key
                            $master_data['invoices'][$ipid][$day][$shortcut]['date']            = $completed_assessments[$ipid][$day][0]['start_date'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['start_date']      = $completed_assessments[$ipid][$day][0]['start_date'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['end_date']        = $completed_assessments[$ipid][$day][0]['end_date'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['time_from']       = $completed_assessments[$ipid][$day][0]['time_from'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['time_till']       = $completed_assessments[$ipid][$day][0]['time_till'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['pdf_time_from']   = $completed_assessments[$ipid][$day][0]['pdf_time_from'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['user_shortcut']   = $completed_assessments[$ipid][$day][0]['users_shortcuts'];
                        }
                        
                        if($saved_values[$ipid][$shortcut][$day] == "1")
                        {
                            $billed[$ipid][$shortcut][] = $day;
                        }
                    }
                    else
                    {
                        if(
                            empty($billed[$ipid][$shortcut])
                            && in_array($day,$patient_days[$ipid]['first_28_days'])
                            && $patients2highest_sapv[$ipid][$day] >= 2
                            && in_array($day,$all_assessments[$ipid]) // it has an assessment COMPLETED on this day  
                            )
                        {
                            
                            if( ! in_array($day,$billed[$ipid][$shortcut]))
                            {
                                $billed[$ipid][$shortcut][] = $day;
                            }
                            $master_data['invoices'][$ipid][$day][$shortcut]['checked']         = 1 ;
                            $master_data['invoices'][$ipid][$day][$shortcut]['qty']             = 1;
                            $master_data['invoices'][$ipid][$day][$shortcut]['price']           = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['dta_price']       = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_price'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['dta_id']          = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_id'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['location_type']   = $day_location_type;
                            $master_data['invoices'][$ipid][$day][$shortcut]['price_list']      = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price_list'];

                            if(!empty($completed_assessments[$ipid][$day])){
                                $completed_assessments[$ipid][$day] = array_values($completed_assessments[$ipid][$day]);  // Ancuta  31.08.2020 - issues with 0 key
                                $master_data['invoices'][$ipid][$day][$shortcut]['date']            = $completed_assessments[$ipid][$day][0]['start_date'];
                                $master_data['invoices'][$ipid][$day][$shortcut]['start_date']      = $completed_assessments[$ipid][$day][0]['start_date'];
                                $master_data['invoices'][$ipid][$day][$shortcut]['end_date']        = $completed_assessments[$ipid][$day][0]['end_date'];
                                $master_data['invoices'][$ipid][$day][$shortcut]['time_from']       = $completed_assessments[$ipid][$day][0]['time_from'];
                                $master_data['invoices'][$ipid][$day][$shortcut]['time_till']       = $completed_assessments[$ipid][$day][0]['time_till'];
                                $master_data['invoices'][$ipid][$day][$shortcut]['pdf_time_from']   = $completed_assessments[$ipid][$day][0]['pdf_time_from'];
                                $master_data['invoices'][$ipid][$day][$shortcut]['user_shortcut']   =  $completed_assessments[$ipid][$day][0]['users_shortcuts'];
                            }
                            
                        }
                        else 
                        {
                            $master_data['invoices'][$ipid][$day][$shortcut]['checked']         = 0 ;
                            $master_data['invoices'][$ipid][$day][$shortcut]['qty']             = 0;
                            $master_data['invoices'][$ipid][$day][$shortcut]['price']           = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['dta_price']       = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_price'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['dta_id']          = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_id'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['location_type']   = $day_location_type;
                            $master_data['invoices'][$ipid][$day][$shortcut]['price_list']      = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price_list'];
                            
                        }
                    }

                    // K2 	
                    // Koordination/Assessment Folgepauschale (ab Tag 29) 	
                    // ONE TIME BILLED ! 	
                    // for 1-n FOLGE-assessment forms being filled from day 29 of reatment 	
                    // for K1  you need at least Koordination verordnung (so BE, KO, TV, or VV)
                    $shortcut = "k2";
                    if( isset($saved_values[$ipid][$shortcut][$day]))
                    {
                        $master_data['invoices'][$ipid][$day][$shortcut]['checked']         = $saved_values[$ipid][$shortcut][$day] ;
                        $master_data['invoices'][$ipid][$day][$shortcut]['qty']             = $saved_values[$ipid][$shortcut][$day];
                        $master_data['invoices'][$ipid][$day][$shortcut]['price']           = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price'];
                        $master_data['invoices'][$ipid][$day][$shortcut]['dta_price']       = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_price'];
                        $master_data['invoices'][$ipid][$day][$shortcut]['dta_id']          = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_id'];
                        $master_data['invoices'][$ipid][$day][$shortcut]['location_type']   = $day_location_type;
                        $master_data['invoices'][$ipid][$day][$shortcut]['price_list']      = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price_list'];
                        
                        
                        if(!empty($completed_assessments[$ipid][$day]) && $saved_values[$ipid][$shortcut][$day] > 0 ){
                            $completed_assessments[$ipid][$day] = array_values($completed_assessments[$ipid][$day]);  // Ancuta  31.08.2020 - issues with 0 key
                            $master_data['invoices'][$ipid][$day][$shortcut]['date']            = $completed_assessments[$ipid][$day][0]['start_date'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['start_date']      = $completed_assessments[$ipid][$day][0]['start_date'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['end_date']        = $completed_assessments[$ipid][$day][0]['end_date'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['time_from']       = $completed_assessments[$ipid][$day][0]['time_from'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['time_till']       = $completed_assessments[$ipid][$day][0]['time_till'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['pdf_time_from']   = $completed_assessments[$ipid][$day][0]['pdf_time_from'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['user_shortcut']   = $completed_assessments[$ipid][$day][0]['users_shortcuts'];
                        }
                        
                        
                        if($saved_values[$ipid][$shortcut][$day] == "1")
                        {
                            $billed[$ipid][$shortcut][] = $day;
                        }
                    }
                    else
                    {
                        
                        if(
                            empty($billed[$ipid][$shortcut])
                            && in_array($day,$patient_days[$ipid]['after_day_29'])
                            && $patients2highest_sapv[$ipid][$day] >= 1
                            && in_array($day,$all_assessments[$ipid]) // it has an assessment COMPLETED on this day  
                            )
                        {
                            
                            if( ! in_array($day,$billed[$ipid][$shortcut]))
                            {
                                $billed[$ipid][$shortcut][] = $day;
                            }
                            $master_data['invoices'][$ipid][$day][$shortcut]['checked']         = 1 ;
                            $master_data['invoices'][$ipid][$day][$shortcut]['qty']             = 1;
                            $master_data['invoices'][$ipid][$day][$shortcut]['price']           = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['dta_price']       = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_price'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['dta_id']          = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_id'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['location_type']   = $day_location_type;
                            $master_data['invoices'][$ipid][$day][$shortcut]['price_list']      = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price_list'];

                            if(!empty($completed_assessments[$ipid][$day])  ){
                                $completed_assessments[$ipid][$day] = array_values($completed_assessments[$ipid][$day]); // Ancuta  31.08.2020 - issues with 0 key
                                $master_data['invoices'][$ipid][$day][$shortcut]['date']            = $completed_assessments[$ipid][$day][0]['start_date'];
                                $master_data['invoices'][$ipid][$day][$shortcut]['start_date']      = $completed_assessments[$ipid][$day][0]['start_date'];
                                $master_data['invoices'][$ipid][$day][$shortcut]['end_date']        = $completed_assessments[$ipid][$day][0]['end_date'];
                                $master_data['invoices'][$ipid][$day][$shortcut]['time_from']       = $completed_assessments[$ipid][$day][0]['time_from'];
                                $master_data['invoices'][$ipid][$day][$shortcut]['time_till']       = $completed_assessments[$ipid][$day][0]['time_till'];
                                $master_data['invoices'][$ipid][$day][$shortcut]['pdf_time_from']   = $completed_assessments[$ipid][$day][0]['pdf_time_from'];
                                $master_data['invoices'][$ipid][$day][$shortcut]['user_shortcut']   = $completed_assessments[$ipid][$day][0]['users_shortcuts'];
                            }
                            
                            
                        }
                        else 
                        {
                            $master_data['invoices'][$ipid][$day][$shortcut]['checked']         = 0 ;
                            $master_data['invoices'][$ipid][$day][$shortcut]['qty']             = 0;
                            $master_data['invoices'][$ipid][$day][$shortcut]['price']           = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['dta_price']       = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_price'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['dta_id']          = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_id'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['location_type']   = $day_location_type;
                            $master_data['invoices'][$ipid][$day][$shortcut]['price_list']      = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price_list'];
                            
                        }
                    }
                    
                    
                    // TV1 	
                    // TV/VV Versorgungstag ambulant 	
                    // ONE per day max. 	
                    // billed for every day WITH A VISIT  
                    // least TV (Tv or VV) verordnung
                    $shortcut = "tv1";
                    if( isset($saved_values[$ipid][$shortcut][$day]))
                    {
                        $master_data['invoices'][$ipid][$day][$shortcut]['checked']         = $saved_values[$ipid][$shortcut][$day] ;
                        $master_data['invoices'][$ipid][$day][$shortcut]['qty']             = $saved_values[$ipid][$shortcut][$day];
                        $master_data['invoices'][$ipid][$day][$shortcut]['price']           = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price'];
                        $master_data['invoices'][$ipid][$day][$shortcut]['dta_price']       = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_price'];
                        $master_data['invoices'][$ipid][$day][$shortcut]['dta_id']          = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_id'];
                        $master_data['invoices'][$ipid][$day][$shortcut]['location_type']   = $day_location_type;
                        $master_data['invoices'][$ipid][$day][$shortcut]['price_list']      = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price_list'];

                        if(!empty($patient_visits_sorted[$ipid][$day]) && $saved_values[$ipid][$shortcut][$day]>0){
                        
                            $master_data['invoices'][$ipid][$day][$shortcut]['date']            = $patient_visits_sorted[$ipid][$day][0]['start_date'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['start_date']      = $patient_visits_sorted[$ipid][$day][0]['start_date'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['end_date']        = $patient_visits_sorted[$ipid][$day][0]['end_date'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['time_from']       = date("Hi",strtotime($patient_visits_sorted[$ipid][$day][0]['start_date']));
                            $master_data['invoices'][$ipid][$day][$shortcut]['time_till']       = date("Hi",strtotime($patient_visits_sorted[$ipid][$day][0]['end_date']));
                            $master_data['invoices'][$ipid][$day][$shortcut]['pdf_time_from']   = date("H:i",strtotime($patient_visits_sorted[$ipid][$day][0]['start_date']));
                            $master_data['invoices'][$ipid][$day][$shortcut]['user_shortcut']   = $patient_visits_sorted[$ipid][$day][0]['user_shortcuts'];
                        }
                        
                        if($saved_values[$ipid][$shortcut][$day] == "1")
                        {
                            $billed[$ipid][$shortcut][] = $day;
                        }
                    }
                    else
                    {
                        if(
                            empty($billed[$ipid][$shortcut][$day])
                            && $patients2highest_sapv[$ipid][$day] >= 3
                            && ! empty($patients_visits[$ipid][$day]) // it has VISIT on this day  
                            && ! in_array($day,$overall_hospiz_days[$ipid])  // NOT in HOSPIZ
                            )
                        {
                            
                            if( ! in_array($day,$billed[$ipid][$shortcut]))
                            {
                                $billed[$ipid][$shortcut][] = $day;
                            }
                            $master_data['invoices'][$ipid][$day][$shortcut]['checked']         = strlen($day_location_type)>0 ? "1":"0"; //TODO-2668 @ Ancuta 19.11.2019 - if there is no location for this day - do not show in form
                            $master_data['invoices'][$ipid][$day][$shortcut]['qty']             = strlen($day_location_type)>0  ? "1":"0"; //TODO-2668 @ Ancuta 19.11.2019 - if there is no location for this day - do not show in form
                            $master_data['invoices'][$ipid][$day][$shortcut]['price']           = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['dta_price']       = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_price'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['dta_id']          = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_id'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['location_type']   = $day_location_type;
                            $master_data['invoices'][$ipid][$day][$shortcut]['price_list']      = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price_list'];

                            if(!empty($patient_visits_sorted[$ipid][$day])){
                                $master_data['invoices'][$ipid][$day][$shortcut]['date']            = $patient_visits_sorted[$ipid][$day][0]['start_date'];
                                $master_data['invoices'][$ipid][$day][$shortcut]['start_date']      = $patient_visits_sorted[$ipid][$day][0]['start_date'];
                                $master_data['invoices'][$ipid][$day][$shortcut]['end_date']        = $patient_visits_sorted[$ipid][$day][0]['end_date'];
                                $master_data['invoices'][$ipid][$day][$shortcut]['time_from']       = date("Hi",strtotime($patient_visits_sorted[$ipid][$day][0]['start_date']));
                                $master_data['invoices'][$ipid][$day][$shortcut]['time_till']       = date("Hi",strtotime($patient_visits_sorted[$ipid][$day][0]['end_date']));
                                $master_data['invoices'][$ipid][$day][$shortcut]['pdf_time_from']   = date("H:i",strtotime($patient_visits_sorted[$ipid][$day][0]['start_date']));
                                $master_data['invoices'][$ipid][$day][$shortcut]['user_shortcut']   = $patient_visits_sorted[$ipid][$day][0]['user_shortcuts'];
                            }
                        }
                        else 
                        {
                            $master_data['invoices'][$ipid][$day][$shortcut]['checked']         = 0 ;
                            $master_data['invoices'][$ipid][$day][$shortcut]['qty']             = 0;
                            $master_data['invoices'][$ipid][$day][$shortcut]['price']           = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['dta_price']       = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_price'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['dta_id']          = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_id'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['location_type']   = $day_location_type;
                            $master_data['invoices'][$ipid][$day][$shortcut]['price_list']      = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price_list'];
                        }
                    }
              
                    
                    
                    
                    // TVH 	
                    // TV Versorgungstag stat. Hospiz 	
                    // ONE per day max. 	
                    // billed for every day WITH A VISIT in HOSPIZ 
                    //at least TV (Tv or VV) verordnung
                    $shortcut = "tvh";
                    if( isset($saved_values[$ipid][$shortcut][$day]))
                    {
                        $master_data['invoices'][$ipid][$day][$shortcut]['checked']         = $saved_values[$ipid][$shortcut][$day] ;
                        $master_data['invoices'][$ipid][$day][$shortcut]['qty']             = $saved_values[$ipid][$shortcut][$day];
                        $master_data['invoices'][$ipid][$day][$shortcut]['price']           = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price'];
                        $master_data['invoices'][$ipid][$day][$shortcut]['dta_price']       = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_price'];
                        $master_data['invoices'][$ipid][$day][$shortcut]['dta_id']          = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_id'];
                        $master_data['invoices'][$ipid][$day][$shortcut]['location_type']   = $day_location_type;
                        $master_data['invoices'][$ipid][$day][$shortcut]['price_list']      = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price_list'];
    
                        if(!empty($patient_visits_sorted[$ipid][$day]) && $saved_values[$ipid][$shortcut][$day]>0){
                        
                            $master_data['invoices'][$ipid][$day][$shortcut]['date']            = $patient_visits_sorted[$ipid][$day][0]['start_date'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['start_date']      = $patient_visits_sorted[$ipid][$day][0]['start_date'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['end_date']        = $patient_visits_sorted[$ipid][$day][0]['end_date'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['time_from']       = date("Hi",strtotime($patient_visits_sorted[$ipid][$day][0]['start_date']));
                            $master_data['invoices'][$ipid][$day][$shortcut]['time_till']       = date("Hi",strtotime($patient_visits_sorted[$ipid][$day][0]['end_date']));
                            $master_data['invoices'][$ipid][$day][$shortcut]['pdf_time_from']   = date("H:i",strtotime($patient_visits_sorted[$ipid][$day][0]['start_date']));
                            $master_data['invoices'][$ipid][$day][$shortcut]['user_shortcut']   = $patient_visits_sorted[$ipid][$day][0]['user_shortcuts'];
                        }
                        
                        
                        if($saved_values[$ipid][$shortcut][$day] == "1")
                        {
                            $billed[$ipid][$shortcut][] = $day;
                        }
                    }
                    else
                    {
                        
                        if(
                            empty($billed[$ipid][$shortcut][$day])
                            && $patients2highest_sapv[$ipid][$day] >= 3
                            && ! empty($patients_visits[$ipid][$day]) // it has VISIT on this day
                            && in_array($day,$overall_hospiz_days[$ipid])  // in HOSPIZ
                            )
                        {
                            
                            if( ! in_array($day,$billed[$ipid][$shortcut]))
                            {
                                $billed[$ipid][$shortcut][] = $day;
                            }
                            $master_data['invoices'][$ipid][$day][$shortcut]['checked']         = 1;
                            $master_data['invoices'][$ipid][$day][$shortcut]['qty']             = 1;
                            $master_data['invoices'][$ipid][$day][$shortcut]['price']           = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['dta_price']       = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_price'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['dta_id']          = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_id'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['location_type']   = $day_location_type;
                            $master_data['invoices'][$ipid][$day][$shortcut]['price_list']      = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price_list'];
                            
                            
                            if(!empty($patient_visits_sorted[$ipid][$day])){
                            
                                $master_data['invoices'][$ipid][$day][$shortcut]['date']            = $patient_visits_sorted[$ipid][$day][0]['start_date'];
                                $master_data['invoices'][$ipid][$day][$shortcut]['start_date']      = $patient_visits_sorted[$ipid][$day][0]['start_date'];
                                $master_data['invoices'][$ipid][$day][$shortcut]['end_date']        = $patient_visits_sorted[$ipid][$day][0]['end_date'];
                                $master_data['invoices'][$ipid][$day][$shortcut]['time_from']       = date("Hi",strtotime($patient_visits_sorted[$ipid][$day][0]['start_date']));
                                $master_data['invoices'][$ipid][$day][$shortcut]['time_till']       = date("Hi",strtotime($patient_visits_sorted[$ipid][$day][0]['end_date']));
                                $master_data['invoices'][$ipid][$day][$shortcut]['pdf_time_from']   = date("H:i",strtotime($patient_visits_sorted[$ipid][$day][0]['start_date']));
                                $master_data['invoices'][$ipid][$day][$shortcut]['user_shortcut']   = $patient_visits_sorted[$ipid][$day][0]['user_shortcuts'];
                            }
                            
                        }
                        else 
                        {
                            $master_data['invoices'][$ipid][$day][$shortcut]['checked']         = 0;
                            $master_data['invoices'][$ipid][$day][$shortcut]['qty']             = 0;
                            $master_data['invoices'][$ipid][$day][$shortcut]['price']           = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['dta_price']       = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_price'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['dta_id']          = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_id'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['location_type']   = $day_location_type;
                            $master_data['invoices'][$ipid][$day][$shortcut]['price_list']      = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price_list'];
                            
                        }
                    }
                    
                    
                    
                    // DTH 	
                    // Fallpauschale Exitus 48h 	
                    // can be billed one time per LIFE 	
                    // is billed if the DEAD happens within 48 h after admission  	
                    //at least TV (Tv or VV) verordnung
                    $shortcut = "dth";
                    if( isset($saved_values[$ipid][$shortcut][$day]))
                    {
                        $master_data['invoices'][$ipid][$day][$shortcut]['checked']         = $saved_values[$ipid][$shortcut][$day] ;
                        $master_data['invoices'][$ipid][$day][$shortcut]['qty']             = $saved_values[$ipid][$shortcut][$day];
                        $master_data['invoices'][$ipid][$day][$shortcut]['price']           = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price'];
                        $master_data['invoices'][$ipid][$day][$shortcut]['dta_price']       = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_price'];
                        $master_data['invoices'][$ipid][$day][$shortcut]['dta_id']          = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_id'];
                        $master_data['invoices'][$ipid][$day][$shortcut]['location_type']   = $day_location_type;
                        $master_data['invoices'][$ipid][$day][$shortcut]['price_list']      = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price_list'];
                        $master_data['invoices'][$ipid][$day][$shortcut]['pdf_time_from']   =  "X";
    
                        
                        if($saved_values[$ipid][$shortcut][$day] == "1")
                        {
                            $billed[$ipid][$shortcut][] = $day;
                        }
                    }
                    else
                    {
                        
                        if(
                            empty($billed[$ipid][$shortcut])
                            && $patients2highest_sapv[$ipid][$day] >= 3
                            &&  in_array($day,$dead_in_valid_48h[$ipid])
                            && $treatment_hours[$ipid] <= 48
                            )
                        {
                            
                            if( ! in_array($day,$billed[$ipid][$shortcut]))
                            {
                                $billed[$ipid][$shortcut][] = $day;
                            }
                            $master_data['invoices'][$ipid][$day][$shortcut]['checked']         = 1;
                            $master_data['invoices'][$ipid][$day][$shortcut]['qty']             = 1;
                            $master_data['invoices'][$ipid][$day][$shortcut]['price']           = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['dta_price']       = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_price'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['dta_id']          = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_id'];                            
                            $master_data['invoices'][$ipid][$day][$shortcut]['location_type']   = $day_location_type;
                            $master_data['invoices'][$ipid][$day][$shortcut]['price_list']      = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price_list'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['pdf_time_from']   = date('H:i',strtotime($discharge_death_date[$ipid]));
                            
                            
                        }
                        else 
                        {
                            $master_data['invoices'][$ipid][$day][$shortcut]['checked']         = 0 ;
                            $master_data['invoices'][$ipid][$day][$shortcut]['qty']             = 0;
                            $master_data['invoices'][$ipid][$day][$shortcut]['price']           = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['dta_price']       = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_price'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['dta_id']          = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['dta_id'];
                            $master_data['invoices'][$ipid][$day][$shortcut]['location_type']   = $day_location_type;
                            $master_data['invoices'][$ipid][$day][$shortcut]['price_list']      = $master_price_list[$ipid][date("Y-m-d",strtotime($day))][$shortcut][$day_location_type]['price_list'];
                            
                        }
                    }
                }
            }

            // return only data in period
            foreach($master_data['invoices'][$ipid] as $the_day => $day_values){
                if( ! in_array($the_day, $patients_periods[$ipid]['days'])){
                    unset($master_data['invoices'][$ipid][$the_day]);
                }
                
            }
        }
//         echo "<pre>";
//         print_r($master_data);
//         exit;
        
//         print_r($patients_periods);
//         exit;
        
        return $master_data;
    }
}