<?php

/**
 * OrganicEntriesExitsLists
 * #ISPC-2512PatientCharts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ISPC
 * @subpackage Application (2020-04-07) ISPC-2520
 * @author     Lore <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class OrganicEntriesExitsLists extends BaseOrganicEntriesExitsLists
{
    
    
}