<?php

/**
 * PatientDemstepcare
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ISPC
 * @subpackage Application (2019-09-04)
 * @author     Ancuta <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 * Demstepcare_upload - 10.09.2019 Ancuta
 */
class PatientDemstepcare extends BasePatientDemstepcare
{            
    /**
     * translations are grouped into an array
     * @var unknown
     */
    const LANGUAGE_ARRAY    = 'patientdemstepcare_lang';
            
    /**
     * define the FORMID and FORMNAME, if you want to piggyback some triggers
     * @var unknown
     */
    const TRIGGER_FORMID    = null;
    const TRIGGER_FORMNAME  = 'frm_patientdemstepcare';
            
    /**
     * insert into patient_files will use this
     */
    const PATIENT_FILE_TABNAME  = 'PatientDemstepcare';
    const PATIENT_FILE_TITLE    = 'PatientDemstepcare PDF'; //this will be translated
            
    /**
     * insert into patient_course will use this
     */
    const PATIENT_COURSE_TITLE      = 'PatientDemstepcare PDF was created';
    const PATIENT_COURSE_TABNAME    = 'patientdemstepcare';
    const PATIENT_COURSE_TYPE       = ''; // add letter

    

    public static function getDefaults( $field = null)
    {
    
        switch($field) {
            case 'dementia_diagnosis': // endstellige Demenzdiagnose nach ICD-10
                $defaults = array(
                "0"=>self::translate('—'),
                self::translate('---- Demenz bei Alzheimer-Krankheit') => array(
                '1' => self::translate('F00.0* G30.0+ - Demenz bei Alzheimer-Krankheit, mit frühem Beginn (<65 Jahre)'),
                '2' => self::translate('F00.1* G30.1+ - Demenz bei Alzheimer-Krankheit, mit spätem Beginn (<65 Jahre)'),
                '3' => self::translate('F00.2* G30.8+ - Demenz bei Alzheimer-Krankheit, atypische oder gemischte Form')
                ),
                self::translate('---- Vaskuläre Demenz') => array(
                '4' => self::translate('F01.0 - Vaskuläre Demenz mit akutem Beginn'),
                '5' => self::translate('F01.1 - Multiinfarkt-Demenz'),
                '6' => self::translate('F01.2 - Subkortikale vaskuläre Demenz'),
                '7' => self::translate('F01.3 - Gemischte kortikale und subkortikale vaskuläre Demenz'),
                '8' => self::translate('F01.8 - Sonstige vaskuläre Demenz')
                ),
                self::translate('---- Demenz bei anderenorts klassifizierten Krankheiten') => array(
                '9' => self::translate('F02.0* G31.0+ - Demenz bei Pick-Krankheit / frontotemporaler Lobärdegeneration'),
                '10' => self::translate('F02.2* G10+ - Demenz bei Chorea Huntington'),
                '11' => self::translate('F02.3* G20+ - Demenz bei primärem Parkinson-Syndrom'),
                '12' => self::translate('F02.8* G31.82+ - Demenz bei Lewy-Körper-Krankheit')
                )
                );
                break;
    
            case 'cerebral_imaging'://cerebrale Bildgebung
                $defaults = array(
                '0' => self::translate('—'),
                '1' => self::translate('erfolgt'),
                '2' => self::translate('unklar'),
                '3' => self::translate('nein')
                );
                break;
    
            case 'laboratory'://Labor
                $defaults = array(
                '0' => self::translate('—'),
                '1' => self::translate('erfolgt'),
                '2' => self::translate('unklar'),
                '3' => self::translate('nein')
                );
                break;
    
            default : $defaults = null;
        }
    
    
        return $defaults;
    }
    

}