<?php
// ISPC-2776 Lore 15.12.2020
/**
 * PatientChildrenDiseases
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ISPC-2776
 * @subpackage Application (2020-12-15)
 * @author     Lore <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class  PatientChildrenDiseases extends BasePatientChildrenDiseases
{            

    public function getPatientChildrenDiseases($ipid)
    {
        if (empty($ipid)) {
            return; //fail-safe
        }
        
        $loc = Doctrine_Query::create()
        ->select("*")
        ->from('PatientChildrenDiseases')
        ->andWhere("ipid= ? ", $ipid);
        $disarr = $loc->fetchArray();
        
        return $disarr;
        
    }
 
    public function getChildrenDiseases($ipid)
    {
        if (empty($ipid)) {
            return;
        }
        
        $pcd = new PatientChildrenDiseases();
        $pcd_stm = $pcd->getPatientChildrenDiseases($ipid);                      
        
        if(!empty($pcd_stm)){
            $rotavirus = PatientChildrenDiseases::getRotavirus();
            $diphtheria = PatientChildrenDiseases::getDiphtheria();
            $hep_a = PatientChildrenDiseases::getHepatitA();
            $hep_b = PatientChildrenDiseases::getHepatitB();
            $hib   = PatientChildrenDiseases::getHib();
            $hpv   = PatientChildrenDiseases::getHpv();
            $measles = PatientChildrenDiseases::getMeasles();
            $meningococci = PatientChildrenDiseases::getMeningococci();
            $mumps = PatientChildrenDiseases::getMumps();
            $pertussis = PatientChildrenDiseases::getPertussis();
            $pneumococci = PatientChildrenDiseases::getPneumococci();
            $polio = PatientChildrenDiseases::getPolio();
            $rubella = PatientChildrenDiseases::getRubella();
            $tetanus = PatientChildrenDiseases::getTetanus();
            $tuberculosis = PatientChildrenDiseases::getTuberculosis();
            $varicella = PatientChildrenDiseases::getVaricella();
            
            if(!empty($pcd_stm[0]['rotavirus_opt'])){
                $pcd_stm[0]['rotavirus'] = '<ul class="ChildrenDiseases_pm">';
                $rotavirus_opt_arr = explode(",", $pcd_stm[0]['rotavirus_opt']);
                foreach($rotavirus_opt_arr as $km => $vm){
                    if($km > 0 ){
                        $pcd_stm[0]['rotavirus'] .= '';
                    }
                    $pcd_stm[0]['rotavirus'] .= '<li>'.$rotavirus[$vm];
                    if($vm == 11 && !(empty($pcd_stm[0]['rotavirus_last_vaccination']) || $pcd_stm[0]['rotavirus_last_vaccination'] == "0000-00-00 00:00:00" || $pcd_stm[0]['rotavirus_last_vaccination'] == "1970-01-01 00:00:00")){
                        $pcd_stm[0]['rotavirus'] .= ' '.date('d.m.Y', strtotime($pcd_stm[0]['rotavirus_last_vaccination']));
                    }
                    if($vm == 12 && !(empty($pcd_stm[0]['rotavirus_next_vaccination']) || $pcd_stm[0]['rotavirus_next_vaccination'] == "0000-00-00 00:00:00" || $pcd_stm[0]['rotavirus_next_vaccination'] == "1970-01-01 00:00:00")){
                        $pcd_stm[0]['rotavirus'] .= ' '.date('d.m.Y', strtotime($pcd_stm[0]['rotavirus_next_vaccination']));
                    }
                    if($vm == 13 && !empty($pcd_stm[0]['rotavirus_text']) ){
                        $pcd_stm[0]['rotavirus'] .= ': '.$pcd_stm[0]['rotavirus_text'];
                    }
                    $pcd_stm[0]['rotavirus'] .= '</li>';
                }
                $pcd_stm[0]['rotavirus'] .= '</ul>';
            }
            
            if(!empty($pcd_stm[0]['varicella_opt'])){
                $pcd_stm[0]['varicella'] = '<ul class="ChildrenDiseases_pm">';
                $varicella_opt_arr = explode(",", $pcd_stm[0]['varicella_opt']);
                foreach($varicella_opt_arr as $km => $vm){
                    if($km > 0 ){
                        $pcd_stm[0]['varicella'] .= '';
                    }
                    $pcd_stm[0]['varicella'] .= '<li>'.$varicella[$vm];
                    if($vm == 9 && !(empty($pcd_stm[0]['varicella_last_vaccination']) || $pcd_stm[0]['varicella_last_vaccination'] == "0000-00-00 00:00:00" || $pcd_stm[0]['varicella_last_vaccination'] == "1970-01-01 00:00:00")){
                        $pcd_stm[0]['varicella'] .= ' '.date('d.m.Y', strtotime($pcd_stm[0]['varicella_last_vaccination']));
                    }
                    if($vm == 10 && !(empty($pcd_stm[0]['varicella_next_vaccination']) || $pcd_stm[0]['varicella_next_vaccination'] == "0000-00-00 00:00:00" || $pcd_stm[0]['varicella_next_vaccination'] == "1970-01-01 00:00:00")){
                        $pcd_stm[0]['varicella'] .= ' '.date('d.m.Y', strtotime($pcd_stm[0]['varicella_next_vaccination']));
                    }
                    if($vm == 11 && !empty($pcd_stm[0]['varicella_text']) ){
                        $pcd_stm[0]['varicella'] .= ': '.$pcd_stm[0]['varicella_text'];
                    }
                    $pcd_stm[0]['varicella'] .= '</li>';
                }
                $pcd_stm[0]['varicella'] .= '</ul>';
            }
            
            if(!empty($pcd_stm[0]['measles_opt'])){
                $pcd_stm[0]['measles'] = '<ul class="ChildrenDiseases_pm">';
                $measles_opt_arr = explode(",", $pcd_stm[0]['measles_opt']);
                foreach($measles_opt_arr as $km => $vm){
                    if($km > 0 ){
                        $pcd_stm[0]['measles'] .= '';
                    }
                    $pcd_stm[0]['measles'] .= '<li>'.$measles[$vm];
                    if($vm == 10 && !(empty($pcd_stm[0]['measles_last_vaccination']) || $pcd_stm[0]['measles_last_vaccination'] == "0000-00-00 00:00:00" || $pcd_stm[0]['measles_last_vaccination'] == "1970-01-01 00:00:00")){
                        $pcd_stm[0]['measles'] .= ' '.date('d.m.Y', strtotime($pcd_stm[0]['measles_last_vaccination']));
                    }
                    if($vm == 11 && !(empty($pcd_stm[0]['measles_next_vaccination']) || $pcd_stm[0]['measles_next_vaccination'] == "0000-00-00 00:00:00" || $pcd_stm[0]['measles_next_vaccination'] == "1970-01-01 00:00:00")){
                        $pcd_stm[0]['measles'] .= ' '.date('d.m.Y', strtotime($pcd_stm[0]['measles_next_vaccination']));
                    }
                    if($vm == 12 && !empty($pcd_stm[0]['measles_text']) ){
                        $pcd_stm[0]['measles'] .= ': '.$pcd_stm[0]['measles_text'];
                    }
                    $pcd_stm[0]['measles'] .= '</li>';
                }
                $pcd_stm[0]['measles'] .= '</ul>';
            }
            
            if(!empty($pcd_stm[0]['mumps_opt'])){
                $pcd_stm[0]['mumps'] = '<ul class="ChildrenDiseases_pm">';
                $mumps_opt_arr = explode(",", $pcd_stm[0]['mumps_opt']);
                foreach($mumps_opt_arr as $km => $vm){
                    if($km > 0 ){
                        $pcd_stm[0]['mumps'] .= '';
                    }
                    $pcd_stm[0]['mumps'] .= '<li>'.$mumps[$vm];
                    if($vm == 8 && !(empty($pcd_stm[0]['mumps_last_vaccination']) || $pcd_stm[0]['mumps_last_vaccination'] == "0000-00-00 00:00:00" || $pcd_stm[0]['mumps_last_vaccination'] == "1970-01-01 00:00:00")){
                        $pcd_stm[0]['mumps'] .= ' '.date('d.m.Y', strtotime($pcd_stm[0]['mumps_last_vaccination']));
                    }
                    if($vm == 9 && !(empty($pcd_stm[0]['mumps_next_vaccination']) || $pcd_stm[0]['mumps_next_vaccination'] == "0000-00-00 00:00:00" || $pcd_stm[0]['mumps_next_vaccination'] == "1970-01-01 00:00:00")){
                        $pcd_stm[0]['mumps'] .= ' '.date('d.m.Y', strtotime($pcd_stm[0]['mumps_next_vaccination']));
                    }
                    if($vm == 10 && !empty($pcd_stm[0]['mumps_text']) ){
                        $pcd_stm[0]['mumps'] .= ': '.$pcd_stm[0]['mumps_text'];
                    }
                    $pcd_stm[0]['mumps'] .= '</li>';
                }
                $pcd_stm[0]['mumps'] .= '</ul>';
            }
            
            if(!empty($pcd_stm[0]['rubella_opt'])){
                $pcd_stm[0]['rubella'] = '<ul class="ChildrenDiseases_pm">';
                $rubella_opt_arr = explode(",", $pcd_stm[0]['rubella_opt']);
                foreach($rubella_opt_arr as $km => $vm){
                    if($km > 0 ){
                        $pcd_stm[0]['rubella'] .= '';
                    }
                    $pcd_stm[0]['rubella'] .= '<li>'.$rubella[$vm];
                    if($vm == 9 && !(empty($pcd_stm[0]['rubella_last_vaccination']) || $pcd_stm[0]['rubella_last_vaccination'] == "0000-00-00 00:00:00" || $pcd_stm[0]['rubella_last_vaccination'] == "1970-01-01 00:00:00")){
                        $pcd_stm[0]['rubella'] .= ' '.date('d.m.Y', strtotime($pcd_stm[0]['rubella_last_vaccination']));
                    }
                    if($vm == 10 && !(empty($pcd_stm[0]['rubella_next_vaccination']) || $pcd_stm[0]['rubella_next_vaccination'] == "0000-00-00 00:00:00" || $pcd_stm[0]['rubella_next_vaccination'] == "1970-01-01 00:00:00")){
                        $pcd_stm[0]['rubella'] .= ' '.date('d.m.Y', strtotime($pcd_stm[0]['rubella_next_vaccination']));
                    }
                    if($vm == 11 && !empty($pcd_stm[0]['rubella_text']) ){
                        $pcd_stm[0]['rubella'] .= ': '.$pcd_stm[0]['rubella_text'];
                    }
                    $pcd_stm[0]['rubella'] .= '</li>';
                }
                $pcd_stm[0]['rubella'] .= '</ul>';
            }
            
            if(!empty($pcd_stm[0]['pertussis_opt'])){
                $pcd_stm[0]['pertussis'] = '<ul class="ChildrenDiseases_pm">';
                $pertussis_opt_arr = explode(",", $pcd_stm[0]['pertussis_opt']);
                foreach($pertussis_opt_arr as $km => $vm){
                    if($km > 0 ){
                        $pcd_stm[0]['pertussis'] .= '';
                    }
                    $pcd_stm[0]['pertussis'] .= '<li>'.$pertussis[$vm];
                    if($vm == 14 && !(empty($pcd_stm[0]['pertussis_last_vaccination']) || $pcd_stm[0]['pertussis_last_vaccination'] == "0000-00-00 00:00:00" || $pcd_stm[0]['pertussis_last_vaccination'] == "1970-01-01 00:00:00")){
                        $pcd_stm[0]['pertussis'] .= ' '.date('d.m.Y', strtotime($pcd_stm[0]['pertussis_last_vaccination']));
                    }
                    if($vm == 15 && !(empty($pcd_stm[0]['pertussis_next_vaccination']) || $pcd_stm[0]['pertussis_next_vaccination'] == "0000-00-00 00:00:00" || $pcd_stm[0]['pertussis_next_vaccination'] == "1970-01-01 00:00:00")){
                        $pcd_stm[0]['pertussis'] .= ' '.date('d.m.Y', strtotime($pcd_stm[0]['pertussis_next_vaccination']));
                    }
                    if($vm == 16 && !empty($pcd_stm[0]['pertussis_text']) ){
                        $pcd_stm[0]['pertussis'] .= ': '.$pcd_stm[0]['pertussis_text'];
                    }
                    $pcd_stm[0]['pertussis'] .= '</li>';
                }
                $pcd_stm[0]['pertussis'] .= '</ul>';
            }
            
            if(!empty($pcd_stm[0]['diphtheria_opt'])){
                $pcd_stm[0]['diphtheria'] = '<ul class="ChildrenDiseases_pm">';
                $diphtheria_opt_arr = explode(",", $pcd_stm[0]['diphtheria_opt']);
                foreach($diphtheria_opt_arr as $km => $vm){
                    if($km > 0 ){
                        $pcd_stm[0]['diphtheria'] .= '';
                    }
                    $pcd_stm[0]['diphtheria'] .= '<li>'.$diphtheria[$vm];
                    if($vm == 13 && !(empty($pcd_stm[0]['diphtheria_last_vaccination']) || $pcd_stm[0]['diphtheria_last_vaccination'] == "0000-00-00 00:00:00" || $pcd_stm[0]['diphtheria_last_vaccination'] == "1970-01-01 00:00:00")){
                        $pcd_stm[0]['diphtheria'] .= ' '.date('d.m.Y', strtotime($pcd_stm[0]['diphtheria_last_vaccination']));
                    }
                    if($vm == 14 && !(empty($pcd_stm[0]['diphtheria_next_vaccination']) || $pcd_stm[0]['diphtheria_next_vaccination'] == "0000-00-00 00:00:00" || $pcd_stm[0]['diphtheria_next_vaccination'] == "1970-01-01 00:00:00")){
                        $pcd_stm[0]['diphtheria'] .= ' '.date('d.m.Y', strtotime($pcd_stm[0]['diphtheria_next_vaccination']));
                    }
                    if($vm == 15 && !empty($pcd_stm[0]['diphtheria_text']) ){
                        $pcd_stm[0]['diphtheria'] .= ': '.$pcd_stm[0]['diphtheria_text'];
                    }
                    $pcd_stm[0]['diphtheria'] .= '</li>';
                }
                $pcd_stm[0]['diphtheria'] .= '</ul>';
            }
            
            if(!empty($pcd_stm[0]['tetanus_opt'])){
                $pcd_stm[0]['tetanus'] = '<ul class="ChildrenDiseases_pm">';
                $tetanus_opt_arr = explode(",", $pcd_stm[0]['tetanus_opt']);
                foreach($tetanus_opt_arr as $km => $vm){
                    if($km > 0 ){
                        $pcd_stm[0]['tetanus'] .= '';
                    }
                    $pcd_stm[0]['tetanus'] .= '<li>'.$tetanus[$vm];
                    if($vm == 14 && !(empty($pcd_stm[0]['tetanus_last_vaccination']) || $pcd_stm[0]['tetanus_last_vaccination'] == "0000-00-00 00:00:00" || $pcd_stm[0]['tetanus_last_vaccination'] == "1970-01-01 00:00:00")){
                        $pcd_stm[0]['tetanus'] .= ' '.date('d.m.Y', strtotime($pcd_stm[0]['tetanus_last_vaccination']));
                    }
                    if($vm == 15 && !(empty($pcd_stm[0]['tetanus_next_vaccination']) || $pcd_stm[0]['tetanus_next_vaccination'] == "0000-00-00 00:00:00" || $pcd_stm[0]['tetanus_next_vaccination'] == "1970-01-01 00:00:00")){
                        $pcd_stm[0]['tetanus'] .= ' '.date('d.m.Y', strtotime($pcd_stm[0]['tetanus_next_vaccination']));
                    }
                    if($vm == 16 && !empty($pcd_stm[0]['tetanus_text']) ){
                        $pcd_stm[0]['tetanus'] .= ': '.$pcd_stm[0]['tetanus_text'];
                    }
                    $pcd_stm[0]['tetanus'] .= '</li>';
                }
                $pcd_stm[0]['tetanus'] .= '</ul>';
            }
            
            if(!empty($pcd_stm[0]['hib_opt'])){
                $pcd_stm[0]['hib'] = '<ul class="ChildrenDiseases_pm">';
                $hib_opt_arr = explode(",", $pcd_stm[0]['hib_opt']);
                foreach($hib_opt_arr as $km => $vm){
                    if($km > 0 ){
                        $pcd_stm[0]['hib'] .= '';
                    }
                    $pcd_stm[0]['hib'] .= '<li>'.$hib[$vm];
                    if($vm == 11 && !(empty($pcd_stm[0]['hib_last_vaccination']) || $pcd_stm[0]['hib_last_vaccination'] == "0000-00-00 00:00:00" || $pcd_stm[0]['hib_last_vaccination'] == "1970-01-01 00:00:00")){
                        $pcd_stm[0]['hib'] .= ' '.date('d.m.Y', strtotime($pcd_stm[0]['hib_last_vaccination']));
                    }
                    if($vm == 12 && !(empty($pcd_stm[0]['hib_next_vaccination']) || $pcd_stm[0]['hib_next_vaccination'] == "0000-00-00 00:00:00" || $pcd_stm[0]['hib_next_vaccination'] == "1970-01-01 00:00:00")){
                        $pcd_stm[0]['hib'] .= ' '.date('d.m.Y', strtotime($pcd_stm[0]['hib_next_vaccination']));
                    }
                    if($vm == 13 && !empty($pcd_stm[0]['hib_text']) ){
                        $pcd_stm[0]['hib'] .= ': '.$pcd_stm[0]['hib_text'];
                    }
                    $pcd_stm[0]['hib'] .= '</li>';
                }
                $pcd_stm[0]['hib'] .= '</ul>';
            }
            
            if(!empty($pcd_stm[0]['polio_opt'])){
                $pcd_stm[0]['polio'] = '<ul class="ChildrenDiseases_pm">';
                $polio_opt_arr = explode(",", $pcd_stm[0]['polio_opt']);
                foreach($polio_opt_arr as $km => $vm){
                    if($km > 0 ){
                        $pcd_stm[0]['polio'] .= '';
                    }
                    $pcd_stm[0]['polio'] .= '<li>'.$polio[$vm];
                    if($vm == 12 && !(empty($pcd_stm[0]['polio_last_vaccination']) || $pcd_stm[0]['polio_last_vaccination'] == "0000-00-00 00:00:00" || $pcd_stm[0]['polio_last_vaccination'] == "1970-01-01 00:00:00")){
                        $pcd_stm[0]['polio'] .= ' '.date('d.m.Y', strtotime($pcd_stm[0]['polio_last_vaccination']));
                    }
                    if($vm == 13 && !(empty($pcd_stm[0]['polio_next_vaccination']) || $pcd_stm[0]['polio_next_vaccination'] == "0000-00-00 00:00:00" || $pcd_stm[0]['polio_next_vaccination'] == "1970-01-01 00:00:00")){
                        $pcd_stm[0]['polio'] .= ' '.date('d.m.Y', strtotime($pcd_stm[0]['polio_next_vaccination']));
                    }
                    if($vm == 14 && !empty($pcd_stm[0]['polio_text']) ){
                        $pcd_stm[0]['polio'] .= ': '.$pcd_stm[0]['polio_text'];
                    }
                    $pcd_stm[0]['polio'] .= '</li>';
                }
                $pcd_stm[0]['polio'] .= '</ul>';
            }
            
            if(!empty($pcd_stm[0]['pneumococci_opt'])){
                $pcd_stm[0]['pneumococci'] = '<ul class="ChildrenDiseases_pm">';
                $pneumococci_opt_arr = explode(",", $pcd_stm[0]['pneumococci_opt']);
                foreach($pneumococci_opt_arr as $km => $vm){
                    if($km > 0 ){
                        $pcd_stm[0]['pneumococci'] .= '';
                    }
                    $pcd_stm[0]['pneumococci'] .= '<li>'.$pneumococci[$vm];
                    if($vm == 10 && !(empty($pcd_stm[0]['pneumococci_last_vaccination']) || $pcd_stm[0]['pneumococci_last_vaccination'] == "0000-00-00 00:00:00" || $pcd_stm[0]['pneumococci_last_vaccination'] == "1970-01-01 00:00:00")){
                        $pcd_stm[0]['pneumococci'] .= ' '.date('d.m.Y', strtotime($pcd_stm[0]['pneumococci_last_vaccination']));
                    }
                    if($vm == 11 && !(empty($pcd_stm[0]['pneumococci_next_vaccination']) || $pcd_stm[0]['pneumococci_next_vaccination'] == "0000-00-00 00:00:00" || $pcd_stm[0]['pneumococci_next_vaccination'] == "1970-01-01 00:00:00")){
                        $pcd_stm[0]['pneumococci'] .= ' '.date('d.m.Y', strtotime($pcd_stm[0]['pneumococci_next_vaccination']));
                    }
                    if($vm == 12 && !empty($pcd_stm[0]['pneumococci_text']) ){
                        $pcd_stm[0]['pneumococci'] .= ': '.$pcd_stm[0]['pneumococci_text'];
                    }
                    $pcd_stm[0]['pneumococci'] .= '</li>';
                }
                $pcd_stm[0]['pneumococci'] .= '</ul>';
            }
            
            if(!empty($pcd_stm[0]['meningococci_opt'])){
                $pcd_stm[0]['meningococci'] = '<ul class="ChildrenDiseases_pm">';
                $meningococci_opt_arr = explode(",", $pcd_stm[0]['meningococci_opt']);
                foreach($meningococci_opt_arr as $km => $vm){
                    if($km > 0 ){
                        $pcd_stm[0]['meningococci'] .= '';
                    }
                    $pcd_stm[0]['meningococci'] .= '<li>'.$meningococci[$vm];
                    if($vm == 7 && !(empty($pcd_stm[0]['meningococci_last_vaccination']) || $pcd_stm[0]['meningococci_last_vaccination'] == "0000-00-00 00:00:00" || $pcd_stm[0]['meningococci_last_vaccination'] == "1970-01-01 00:00:00")){
                        $pcd_stm[0]['meningococci'] .= ' '.date('d.m.Y', strtotime($pcd_stm[0]['meningococci_last_vaccination']));
                    }
                    if($vm == 8 && !(empty($pcd_stm[0]['meningococci_next_vaccination']) || $pcd_stm[0]['meningococci_next_vaccination'] == "0000-00-00 00:00:00" || $pcd_stm[0]['meningococci_next_vaccination'] == "1970-01-01 00:00:00")){
                        $pcd_stm[0]['meningococci'] .= ' '.date('d.m.Y', strtotime($pcd_stm[0]['meningococci_next_vaccination']));
                    }
                    if($vm == 9 && !empty($pcd_stm[0]['meningococci_text']) ){
                        $pcd_stm[0]['meningococci'] .= ': '.$pcd_stm[0]['meningococci_text'];
                    }
                    $pcd_stm[0]['meningococci'] .= '</li>';
                }
                $pcd_stm[0]['meningococci'] .= '</ul>';
            }
            
            if(!empty($pcd_stm[0]['hepatit_a_opt'])){
                $pcd_stm[0]['hepatit_a'] = '<ul class="ChildrenDiseases_pm">';
                $hep_a_opt_arr = explode(",", $pcd_stm[0]['hepatit_a_opt']);
                foreach($hep_a_opt_arr as $km => $vm){
                    if($km > 0 ){
                        $pcd_stm[0]['hepatit_a'] .= '';
                    }
                    $pcd_stm[0]['hepatit_a'] .= '<li>'.$hep_a[$vm];
                    if($vm == 9 && !(empty($pcd_stm[0]['hepatit_a_last_vaccination']) || $pcd_stm[0]['hepatit_a_last_vaccination'] == "0000-00-00 00:00:00" || $pcd_stm[0]['hepatit_a_last_vaccination'] == "1970-01-01 00:00:00")){
                        $pcd_stm[0]['hepatit_a'] .= ' '.date('d.m.Y', strtotime($pcd_stm[0]['hepatit_a_last_vaccination']));
                    }
                    if($vm == 10 && !(empty($pcd_stm[0]['hepatit_a_next_vaccination']) || $pcd_stm[0]['hepatit_a_next_vaccination'] == "0000-00-00 00:00:00" || $pcd_stm[0]['hepatit_a_next_vaccination'] == "1970-01-01 00:00:00")){
                        $pcd_stm[0]['hepatit_a'] .= ' '.date('d.m.Y', strtotime($pcd_stm[0]['hepatit_a_next_vaccination']));
                    }
                    if($vm == 11 && !empty($pcd_stm[0]['hepatit_a_text']) ){
                        $pcd_stm[0]['hepatit_a'] .= ': '.$pcd_stm[0]['hepatit_a_text'];
                    }
                    $pcd_stm[0]['hepatit_a'] .= '</li>';
                }
                $pcd_stm[0]['hepatit_a'] .= '</ul>';
            }
            
            if(!empty($pcd_stm[0]['hepatit_b_opt'])){
                $pcd_stm[0]['hepatit_b'] = '<ul class="ChildrenDiseases_pm">';
                $hepatit_b_opt_arr = explode(",", $pcd_stm[0]['hepatit_b_opt']);
                foreach($hepatit_b_opt_arr as $km => $vm){
                    if($km > 0 ){
                        $pcd_stm[0]['hepatit_b'] .= '';
                    }
                    $pcd_stm[0]['hepatit_b'] .= '<li>'.$hep_b[$vm];
                    if($vm == 11 && !(empty($pcd_stm[0]['hepatit_b_last_vaccination']) || $pcd_stm[0]['hepatit_b_last_vaccination'] == "0000-00-00 00:00:00" || $pcd_stm[0]['hepatit_b_last_vaccination'] == "1970-01-01 00:00:00")){
                        $pcd_stm[0]['hepatit_b'] .= ' '.date('d.m.Y', strtotime($pcd_stm[0]['hepatit_b_last_vaccination']));
                    }
                    if($vm == 12 && !(empty($pcd_stm[0]['hepatit_b_next_vaccination']) || $pcd_stm[0]['hepatit_b_next_vaccination'] == "0000-00-00 00:00:00" || $pcd_stm[0]['hepatit_b_next_vaccination'] == "1970-01-01 00:00:00")){
                        $pcd_stm[0]['hepatit_b'] .= ' '.date('d.m.Y', strtotime($pcd_stm[0]['hepatit_b_next_vaccination']));
                    }
                    if($vm == 13 && !empty($pcd_stm[0]['hepatit_b_text']) ){
                        $pcd_stm[0]['hepatit_b'] .= ': '.$pcd_stm[0]['hepatit_b_text'];
                    }
                    $pcd_stm[0]['hepatit_b'] .= '</li>';
                }
                $pcd_stm[0]['hepatit_b'] .= '</ul>';
            }

            if(!empty($pcd_stm[0]['tuberculosis_opt'])){
                $pcd_stm[0]['tuberculosis'] = '<ul class="ChildrenDiseases_pm">';
                $tuberculosis_opt_arr = explode(",", $pcd_stm[0]['tuberculosis_opt']);
                foreach($tuberculosis_opt_arr as $km => $vm){
                    if($km > 0 ){
                        $pcd_stm[0]['tuberculosis'] .= '';
                    }
                    $pcd_stm[0]['tuberculosis'] .= '<li>'.$tuberculosis[$vm];
                    if($vm == 4 && !empty($pcd_stm[0]['tuberculosis_text']) ){
                        $pcd_stm[0]['tuberculosis'] .= ': '.$pcd_stm[0]['tuberculosis_text'];
                    }
                    $pcd_stm[0]['tuberculosis'] .= '</li>';
                }
                $pcd_stm[0]['tuberculosis'] .= '</ul>';
            }
            
            if(!empty($pcd_stm[0]['hpv_opt'])){
                $pcd_stm[0]['hpv'] = '<ul class="ChildrenDiseases_pm">';
                $hpv_opt_arr = explode(",", $pcd_stm[0]['hpv_opt']);
                foreach($hpv_opt_arr as $km => $vm){
                    if($km > 0 ){
                        $pcd_stm[0]['hpv'] .= '';
                    }
                    $pcd_stm[0]['hpv'] .= '<li>'.$hpv[$vm];
                    if($vm == 9 && !(empty($pcd_stm[0]['hpv_last_vaccination']) || $pcd_stm[0]['hpv_last_vaccination'] == "0000-00-00 00:00:00" || $pcd_stm[0]['hpv_last_vaccination'] == "1970-01-01 00:00:00")){
                        $pcd_stm[0]['hpv'] .= ' '.date('d.m.Y', strtotime($pcd_stm[0]['hpv_last_vaccination']));
                    }
                    if($vm == 10 && !(empty($pcd_stm[0]['hpv_next_vaccination']) || $pcd_stm[0]['hpv_next_vaccination'] == "0000-00-00 00:00:00" || $pcd_stm[0]['hpv_next_vaccination'] == "1970-01-01 00:00:00")){
                        $pcd_stm[0]['hpv'] .= ' '.date('d.m.Y', strtotime($pcd_stm[0]['hpv_next_vaccination']));
                    }
                    if($vm == 11 && !empty($pcd_stm[0]['hpv_text']) ){
                        $pcd_stm[0]['hpv'] .= ': '.$pcd_stm[0]['hpv_text'];
                    }
                    $pcd_stm[0]['hpv'] .= '</li>';
                }
                $pcd_stm[0]['hpv'] .= '</ul>';
            }
            
            if(!empty($pcd_stm[0]['other_text'])){
                $pcd_stm[0]['other'] = '<ul class="ChildrenDiseases_pm">';
                $pcd_stm[0]['other'] .= '<li>'.$pcd_stm[0]['other_text'].'</li>';
                $pcd_stm[0]['other'] .= '</ul>';
            }
 
        }
        
        return $pcd_stm;
        
    }
    
    public static function getRotavirus()
    {
        $rotavirus = array(
            '1' => 'Aktuell erkrankt',
            '2' => 'In Vergangenheit erkrankt',
            '3' => 'Nicht/noch nie erkrankt',
            '4' => 'Grundimmunisierung vollständig (3/3 Impfungen erhalten)',
            '5' => 'Grundimmunisierung unvollständig (2/3 Impfungen erhalten)',
            '6' => 'Grundimmunisierung unvollständig (1/3 Impfungen erhalten)',
            '7' => 'Grundimmunisierung unvollständig (3/4 Impfungen erhalten)',
            '8' => 'Grundimmunisieurung noch nicht begonnen',
            '9' => 'Impfung wird abgelehnt',
            '10' => 'Impfung nicht möglich',
            '11' => 'Letzte Impfung:',
            '12' => 'Nächste Impfung:',
            '13' => 'Sonstiges',
        );
        
        return $rotavirus;
    }
    
    public static function getVaricella()
    {
        $varicella = array(
            '1' => 'Aktuell erkrankt',
            '2' => 'In Vergangenheit erkrankt',
            '3' => 'Nicht/noch nie erkrankt',
            '4' => 'Grundimmunisierung vollständig (2/2 Impfungen erhalten)',
            '5' => 'Grundimmunisierung unvollständig (1/2 Impfungen erhalten)',
            '6' => 'Grundimmunisieurung noch nicht begonnen',
            '7' => 'Impfung wird abgelehnt',
            '8' => 'Impfung nicht möglich',
            '9' => 'Letzte Impfung:',
            '10' => 'Nächste Impfung:',
            '11' => 'Sonstiges',
        );
        
        return $varicella;
    }

    public static function getMeasles()
    {
        $measles = array(
            '1' => 'Aktuell erkrankt',
            '2' => 'In Vergangenheit erkrankt',
            '3' => 'Nicht/noch nie erkrankt',
            '4' => 'Grundimmunisierung vollständig (2/2 Impfungen erhalten)',
            '5' => 'Grundimmunisierung unvollständig (1/2 Impfungen erhalten)',
            '6' => 'Grundimmunisieurung noch nicht begonnen',
            '7' => 'Standardimpfung (ab 18. Lebensjahr) erhalten',
            '8' => 'Impfung wird abgelehnt',
            '9' => 'Impfung nicht möglich',
            '10' => 'Letzte Impfung:',
            '11' => 'Nächste Impfung:',
            '12' => 'Sonstiges',
        );
        
        return $measles;
    }

    
    public static function getMumps()
    {
        $mumps = array(
            '1' => 'Aktuell erkrankt',
            '2' => 'In Vergangenheit erkrankt',
            '3' => 'Nicht/noch nie erkrankt',
            '4' => 'Grundimmunisierung vollständig (2/2 Impfungen erhalten)',
            '5' => 'Grundimmunisierung unvollständig (1/2 Impfungen erhalten)',
            '6' => 'Grundimmunisieurung noch nicht begonnen',
            '7' => 'Impfung wird abgelehnt',
            '8' => 'Letzte Impfung:',
            '9' => 'Nächste Impfung:',
            '10' => 'Sonstiges',
        );
        
        return $mumps;
    }
    
    public static function getRubella()
    {
        $rubella = array(
            '1' => 'Aktuell erkrankt',
            '2' => 'In Vergangenheit erkrankt',
            '3' => 'Nicht/noch nie erkrankt',
            '4' => 'Grundimmunisierung vollständig (2/2 Impfungen erhalten)',
            '5' => 'Grundimmunisierung unvollständig (1/2 Impfungen erhalten)',
            '6' => 'Grundimmunisieurung noch nicht begonnen',
            '7' => 'Impfung wird abgelehnt',
            '8' => 'Impfung nicht möglich',
            '9' => 'Letzte Impfung:',
            '10' => 'Nächste Impfung:',
            '11' => 'Sonstiges',
        );
        
        return $rubella;
    }
    
    public static function getPertussis()
    {
        $pertussis = array(
            '1' => 'Aktuell erkrankt',
            '2' => 'In Vergangenheit erkrankt',
            '3' => 'Nicht/noch nie erkrankt',
            '4' => 'Grundimmunisierung vollständig (4/4 Impfungen erhalten)',
            '5' => 'Grundimmunisierung unvollständig (1/4 Impfungen erhalten)',
            '6' => 'Grundimmunisierung unvollständig (2/4 Impfungen erhalten)',
            '7' => 'Grundimmunisierung unvollständig (3/4 Impfungen erhalten)',
            '8' => 'Grundimmunisieurung noch nicht begonnen',
            '9' => 'Auffrischimpfung (5.-6. Lebensjahr) erhalten',
            '10' => 'Auffrischimpfung (9.-16. Lebensjahr) erhalten',
            '11' => 'Auffrischimpfung (ab 18. Lebensjahr) erhalten',
            '12' => 'Impfung wird abgelehnt',
            '13' => 'Impfung nicht möglich',
            '14' => 'Letzte Impfung:',
            '15' => 'Nächste Impfung:',
            '16' => 'Sonstiges',
        );
        
        return $pertussis;
    }
    
    public static function getDiphtheria()
    {
        $diphterie = array(
            '1' => 'Aktuell erkrankt',
            '2' => 'In Vergangenheit erkrankt*',
            '3' => 'Nicht/noch nie erkrankt',
            '4' => 'Grundimmunisierung vollständig (4/4 Impfungen erhalten)',
            '5' => 'Grundimmunisierung unvollständig (1/4 Impfungen erhalten)',
            '6' => 'Grundimmunisierung unvollständig (2/4 Impfungen erhalten)',
            '7' => 'Grundimmunisierung unvollständig (3/4 Impfungen erhalten)',
            '8' => 'Grundimmunisieurung noch nicht begonnen',
            '9' => 'Auffrischimpfung (5.-6. Lebensjahr) erhalten',
            '10' => 'Auffrischimpfung (9.-16. Lebensjahr) erhalten',
            '11' => 'Auffrischimpfung (ab 18. Lebensjahr) erhalten',
            '12' => 'Impfung nicht möglich',
            '13' => 'Letzte Impfung:',
            '14' => 'Nächste Impfung:',
            '15' => 'Sonstiges',
        );
        
        return $diphterie;
    }
    
    public static function getTetanus()
    {
        $tetanus = array(
            '1' => 'Aktuell erkrankt',
            '2' => 'In Vergangenheit erkrankt*',
            '3' => 'Nicht/noch nie erkrankt',
            '4' => 'Grundimmunisierung vollständig (4/4 Impfungen erhalten)',
            '5' => 'Grundimmunisierung unvollständig (1/4 Impfungen erhalten)',
            '6' => 'Grundimmunisierung unvollständig (2/4 Impfungen erhalten)',
            '7' => 'Grundimmunisierung unvollständig (3/4 Impfungen erhalten)',
            '8' => 'Grundimmunisieurung noch nicht begonnen',
            '9' => 'Auffrischimpfung (5.-6. Lebensjahr) erhalten',
            '10' => 'Auffrischimpfung (9.-16. Lebensjahr) erhalten',
            '11' => 'Auffrischimpfung (ab 18. Lebensjahr) erhalten',
            '12' => 'Impfung wird abgelehnt',
            '13' => 'Impfung nicht möglich',
            '14' => 'Letzte Impfung:',
            '15' => 'Nächste Impfung:',
            '16' => 'Sonstiges',
        );
        
        return $tetanus;
    }
    
    public static function getHib()
    {
        $hib = array(
            '1' => 'Aktuell erkrankt',
            '2' => 'In Vergangenheit erkrankt*',
            '3' => 'Nicht/noch nie erkrankt',
            '4' => 'Grundimmunisierung vollständig (4/4 Impfungen erhalten)',
            '5' => 'Grundimmunisierung unvollständig (1/4 Impfungen erhalten)',
            '6' => 'Grundimmunisierung unvollständig (2/4 Impfungen erhalten)',
            '7' => 'Grundimmunisierung unvollständig (3/4 Impfungen erhalten)',
            '8' => 'Grundimmunisieurung noch nicht begonnen',
            '9' => 'Impfung wird abgelehnt',
            '10' => 'Impfung nicht möglich',
            '11' => 'Letzte Impfung:',
            '12' => 'Nächste Impfung:',
            '13' => 'Sonstiges',
        );
        
        return $hib;
    }
    
    public static function getPolio()
    {
        $polio = array(
            '1' => 'Aktuell erkrankt',
            '2' => 'In Vergangenheit erkrankt*',
            '3' => 'Nicht/noch nie erkrankt',
            '4' => 'Grundimmunisierung vollständig (4/4 Impfungen erhalten)',
            '5' => 'Grundimmunisierung unvollständig (1/4 Impfungen erhalten)',
            '6' => 'Grundimmunisierung unvollständig (2/4 Impfungen erhalten)',
            '7' => 'Grundimmunisierung unvollständig (3/4 Impfungen erhalten)',
            '8' => 'Grundimmunisieurung noch nicht begonnen',
            '9' => 'Auffrischimpfung (9.-16. Lebensjahr) erhalten',
            '10' => 'Impfung wird abgelehnt',
            '11' => 'Impfung nicht möglich',
            '12' => 'Letzte Impfung:',
            '13' => 'Nächste Impfung:',
            '14' => 'Sonstiges',
        );
        
        return $polio;
    }
    
    public static function getPneumococci()
    {
        $pneumococci = array(
            '1' => 'Aktuell erkrankt',
            '2' => 'In Vergangenheit erkrankt*',
            '3' => 'Nicht/noch nie erkrankt',
            '4' => 'Grundimmunisierung vollständig (3/3 Impfungen erhalten)',
            '5' => 'Grundimmunisierung unvollständig (1/3 Impfungen erhalten)',
            '6' => 'Grundimmunisierung unvollständig (2/3 Impfungen erhalten)',
            '7' => 'Grundimmunisieurung noch nicht begonnen',
            '8' => 'Impfung wird abgelehnt',
            '9' => 'Impfung nicht möglich',
            '10' => 'Letzte Impfung:',
            '11' => 'Nächste Impfung:',
            '12' => 'Sonstiges',
        );
        
        return $pneumococci;
    }
    
    public static function getMeningococci()
    {
        $meningococci = array(
            '1' => 'Aktuell erkrankt',
            '2' => 'In Vergangenheit erkrankt*',
            '3' => 'Nicht/noch nie erkrankt',
            '4' => 'Grundimmunisierung vollständig (1/1 Impfungen erhalten)',
            '5' => 'Grundimmunisieurung noch nicht begonnen',
            '6' => 'Impfung wird abgelehnt',
            '7' => 'Letzte Impfung:',
            '8' => 'Nächste Impfung:',
            '9' => 'Sonstiges',
        );
        
        return $meningococci;
    }
    
    public static function getHepatitA ()
    {
        $hep_a = array(
            '1' => 'Aktuell erkrankt',
            '2' => 'In Vergangenheit erkrankt*',
            '3' => 'Nicht/noch nie erkrankt',
            '4' => 'Grundimmunisierung vollständig (2/2 Impfungen erhalten)',
            '5' => 'Grundimmunisierung unvollständig (1/2 Impfungen erhalten)',
            '6' => 'Grundimmunisieurung noch nicht begonnen',
            '7' => 'Impfung wird abgelehnt',
            '8' => 'Impfung nicht möglich',
            '9' => 'Letzte Impfung:',
            '10' => 'Nächste Impfung:',
            '11' => 'Sonstiges',
        );
        
        return $hep_a;
    }
    
    public static function getHepatitB ()
    {
        $hep_b = array(
            '1' => 'Aktuell erkrankt',
            '2' => 'In Vergangenheit erkrankt*',
            '3' => 'Nicht/noch nie erkrankt',
            '4' => 'Grundimmunisierung vollständig (4/4 Impfungen erhalten)',
            '5' => 'Grundimmunisierung unvollständig (1/4 Impfungen erhalten)',
            '6' => 'Grundimmunisierung unvollständig (2/4 Impfungen erhalten)',
            '7' => 'Grundimmunisierung unvollständig (3/4 Impfungen erhalten)',
            '8' => 'Grundimmunisieurung noch nicht begonnen',
            '9' => 'Impfung wird abgelehnt',
            '10' => 'Impfung nicht möglich',
            '11' => 'Letzte Impfung:',
            '12' => 'Nächste Impfung:',
            '13' => 'Sonstiges',
        );
        
        return $hep_b;
    }
    
    public static function getTuberculosis()
    {
        $tuberkulose = array(
            '1' => 'Aktuell erkrankt',
            '2' => 'In Vergangenheit erkrankt*',
            '3' => 'Nicht/noch nie erkrankt',
            '4' => 'Sonstiges',
        );
        
        return $tuberkulose;
    }
    
    public static function getHpv ()
    {
        $hpv = array(
            '1' => 'Aktuell erkrankt',
            '2' => 'In Vergangenheit erkrankt*',
            '3' => 'Nicht/noch nie erkrankt',
            '4' => 'Grundimmunisierung vollständig (2/2 Impfungen erhalten)',
            '5' => 'Grundimmunisierung unvollständig (1/2 Impfungen erhalten)',
            '6' => 'Grundimmunisieurung noch nicht begonnen',
            '7' => 'Impfung wird abgelehnt',
            '8' => 'Impfung nicht möglich',
            '9' => 'Letzte Impfung:',
            '10' => 'Nächste Impfung:',
            '11' => 'Sonstiges',
        );
        
        return $hpv;
    }
       
}

?>





