<?php

/**
 * PatientMre
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ISPC
 * @subpackage Application (2020-10-06)
 * @author     Ancuta <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 * 
 * ISPC-2654 Ancuta 06.10.2020
 */
class PatientMre extends BasePatientMre
{            
    /**
     * translations are grouped into an array
     * @var unknown
     */
    const LANGUAGE_ARRAY    = 'patientmre_lang';
            
    /**
     * define the FORMID and FORMNAME, if you want to piggyback some triggers
     * @var unknown
     */
    const TRIGGER_FORMID    = null;
    const TRIGGER_FORMNAME  = 'frm_patientmre';
            
    /**
     * insert into patient_files will use this
     */
    const PATIENT_FILE_TABNAME  = 'PatientMre';
    const PATIENT_FILE_TITLE    = 'PatientMre PDF'; //this will be translated
            
    /**
     * insert into patient_course will use this
     */
    const PATIENT_COURSE_TITLE      = 'PatientMre PDF was created';
    const PATIENT_COURSE_TABNAME    = 'patientmre';
    const PATIENT_COURSE_TYPE       = ''; // add letter

    
    
    /**
     * ISPC-2654 Ancuta 06.10.2020
     * @return string[]
     */
    public static function get_pathogen_list(){
        $retValue = [
            'MRSA',
            'ESBL-Bildner',
            '3MRGN^2',
            '4MRGN^2',
            'VRE',
            'Clostridioides difficile',
            'sonstiger Nachweis eines multiresistenten Erregers: ',
        ];
        return $retValue;
    }
    
    /**
     * ISPC-2654 Ancuta 06.10.2020
     * @return string[]
     */
    public static function get_rehabilitation(){
        $retValue = [
            '0'=>'ja',
            '1'=>'nein',
            '2'=>'nicht möglich',
        ];
        return $retValue;
    }
    
    /**
     * ISPC-2654 Ancuta 06.10.2020
     * @return string[]
     */
    public static function get_rehabilitation_status(){
        $retValue = [
            '0'=>'mit Erfolg',
            '1'=>'ohne Erfolg',
            '2'=>'wurde begonnen',
            '3'=>'konnte aber nicht abgeschlossen werden'
        ];
        return $retValue;
    }
    
    /**
     * ISPC-2654 Ancuta 06.10.2020
     * @return string[]
     */
    public static function get_localization_list(){
        $retValue = [
            '0'=>'Nase/Rachenraum',
            '1'=>'Sputum/Trachealsekret',
            '2'=>'Haut',
            '3'=>'Wunde: ________ (freetext)',// has free text
            '4'=>'Urin/Harnblase',
            '5'=>'Stuhl/Rektalabstrich',
            '6'=>'Blutkultur/Liquor',
            '7'=>'Device Art: ________ (freetext)',
            '8'=>'sonstige: ________ (freetext)',
        ];
        return $retValue;
    }
    
    /**
     * ISPC-2654 Ancuta 06.10.2020
     * @return string[]
     */
    public static function get_carrier_status_list(){
        $retValue = [
            '0'=>'Kolonisation',
            '1'=>'Infektion',
        ];
        return $retValue;
    }

}