<?php
// ISPC-2672 Lore 26.10.2020
/**
 * PatientSapvTeam
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ISPC-2672
 * @subpackage Application (2020-10-26)
 * @author     Lore <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PatientSapvTeam extends BasePatientSapvTeam
{            

    public function getPatientSapvTeam($ipid)
    {
        if (empty($ipid)) {
            return; //fail-safe
        }
        
        $pg = Doctrine_Query::create()
        ->select("*")
        ->from('PatientSapvTeam')
        ->andWhere("ipid= ? ", $ipid);
        $pgarr = $pg->fetchArray();
        
        return $pgarr;
        
    }

    
}

?>





