<?php

/**
 * PatientMovementnumber
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ISPC
 * @subpackage Application (2020-08-05)
 * @author     Ancuta <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 * ISPC-2459 Ancuta 05.08.2020
 */
class PatientMovementnumber extends BasePatientMovementnumber
{            
    /**
     * translations are grouped into an array
     * @var unknown
     */
    const LANGUAGE_ARRAY    = 'patientmovementnumber_lang';
            
    /**
     * define the FORMID and FORMNAME, if you want to piggyback some triggers
     * @var unknown
     */
    const TRIGGER_FORMID    = null;
    const TRIGGER_FORMNAME  = 'frm_patientmovementnumber';
            
    /**
     * insert into patient_files will use this
     */
    const PATIENT_FILE_TABNAME  = 'PatientMovementnumber';
    const PATIENT_FILE_TITLE    = 'PatientMovementnumber PDF'; //this will be translated
            
    /**
     * insert into patient_course will use this
     */
    const PATIENT_COURSE_TITLE      = 'PatientMovementnumber PDF was created';
    const PATIENT_COURSE_TABNAME    = 'patientmovementnumber';
    const PATIENT_COURSE_TYPE       = ''; // add letter

    
    
    

}