<?php

/**
 * PatientPsychooncological
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ISPC
 * @subpackage Application (2017-12-08)
 * @author     claudiu <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PatientPsychooncological extends BasePatientPsychooncological
{
    
    public function findOrCreateOneBy($fieldName, $value, array $data = array(), $hydrationMode = Doctrine_Core::HYDRATE_RECORD)
    {
        if ( is_null($value) || ! $entity = $this->getTable()->findOneBy($fieldName, $value, $hydrationMode)) {
            $entity = $this->getTable()->create(array( $fieldName => $value));
        }
    
        $entity->fromArray($data); //update
    
        $entity->save(); //at least one field must be dirty in order to persist
    
        return $entity;
    }
    
    

    /**
     *
     * @param string|array $ipid
     * @param int $hydrationMode
     */
    public function findByIpid( $ipid = '', $hydrationMode = Doctrine_Core::HYDRATE_ARRAY )
    {
        if (empty($ipid) || !is_string($ipid)) {
    
            return;
    
        } else {
            return $this->getTable()->findBy('ipid', $ipid, $hydrationMode);
    
        }
    }
}