<?php
/**
 * PatientTherapy
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ISPC
 * @subpackage Application (2020-12-16) ISPC-2774
 * @author     carmen <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
	class PatientTherapy extends BasePatientTherapy {

		
	}

?>