<?php
//TODO : move the saved values to DgpKern and then delete all this model PatientKarnofsky

/**
 * PatientKarnofsky
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ISPC
 * @subpackage Application (2017-12-14)
 * @author     claudiu <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PatientKarnofsky extends BasePatientKarnofsky
{

    
    public function findOrCreateOneByIpidAndWlassessmentid($ipid = '', $wlassessment_id = 0, array $data = array(), $hydrationMode = Doctrine_Core::HYDRATE_RECORD)
    {
        if ( is_null($value) || ! $entity = $this->getTable()->findOneByIpidAndWlassessmentid($ipid, $wlassessment_id)) {
            $entity = $this->getTable()->create(array( 'ipid' => $ipid, 'wlassessment_id' => $wlassessment_id));
        }
    
        unset($data[$this->getTable()->getIdentifier()]);
    
        $entity->fromArray($data); //update

        $entity->save(); //at least one field must be dirty in order to persist
    
        return $entity;
    }
    
}