<?php
// ISPC-2672 Carmen 21.10.2020
/**
 * PatientKindergarten
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ISPC-2672
 * @subpackage Application (2020-10-21)
 * @author     Carmen <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PatientKindergarten extends BasePatientKindergarten
{  
	
}

?>





