<?php

/**
 * PharmaPatientDrugplanDosage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ISPC
 * @subpackage Application (2020-02-08)
 * @author     Ancuta <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 * ISPC-2507
 */
class PharmaPatientDrugplanDosage extends BasePharmaPatientDrugplanDosage
{            
    /**
     * translations are grouped into an array
     * @var unknown
     */
    const LANGUAGE_ARRAY    = 'pharmapatientdrugplandosage_lang';
            
    /**
     * define the FORMID and FORMNAME, if you want to piggyback some triggers
     * @var unknown
     */
    const TRIGGER_FORMID    = null;
    const TRIGGER_FORMNAME  = 'frm_pharmapatientdrugplandosage';
            
    /**
     * insert into patient_files will use this
     */
    const PATIENT_FILE_TABNAME  = 'PharmaPatientDrugplanDosage';
    const PATIENT_FILE_TITLE    = 'PharmaPatientDrugplanDosage PDF'; //this will be translated
            
    /**
     * insert into patient_course will use this
     */
    const PATIENT_COURSE_TITLE      = 'PharmaPatientDrugplanDosage PDF was created';
    const PATIENT_COURSE_TABNAME    = 'pharmapatientdrugplandosage';
    const PATIENT_COURSE_TYPE       = ''; // add letter

    
    
    

}