<?php

/**
 * PriceNordrheinAnlage10
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ISPC
 * @subpackage Application (2019-12-10) ISPC-2495
 * @author     Carmen <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PriceNordrheinAnlage10 extends BasePriceNordrheinAnlage10
{

}

?>