<?php

/**
 * PrintJobsItems
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ISPC
 * @subpackage Application (2020-09-04)
 * @author     Ancuta <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 * ISPC-2609 Ancuta 07.09.2020
 */
class PrintJobsItems extends BasePrintJobsItems
{            
    /**
     * translations are grouped into an array
     * @var unknown
     */
    const LANGUAGE_ARRAY    = 'printjobsitems_lang';
            
    /**
     * define the FORMID and FORMNAME, if you want to piggyback some triggers
     * @var unknown
     */
    const TRIGGER_FORMID    = null;
    const TRIGGER_FORMNAME  = 'frm_printjobsitems';
            
    /**
     * insert into patient_files will use this
     */
    const PATIENT_FILE_TABNAME  = 'PrintJobsItems';
    const PATIENT_FILE_TITLE    = 'PrintJobsItems PDF'; //this will be translated
            
    /**
     * insert into patient_course will use this
     */
    const PATIENT_COURSE_TITLE      = 'PrintJobsItems PDF was created';
    const PATIENT_COURSE_TABNAME    = 'printjobsitems';
    const PATIENT_COURSE_TYPE       = ''; // add letter

    
    
    

}