<?php

/**
 * PrivateContactform
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ISPC [ISPC-2909]
 * @subpackage Application (2021-06-01)
 * @author     Ancuta <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PrivateContactform extends BasePrivateContactform
{            
    /**
     * translations are grouped into an array
     * @var unknown
     */
    const LANGUAGE_ARRAY    = 'privatecontactform_lang';
            
    /**
     * define the FORMID and FORMNAME, if you want to piggyback some triggers
     * @var unknown
     */
    const TRIGGER_FORMID    = null;
    const TRIGGER_FORMNAME  = 'frm_privatecontactform';
            
    /**
     * insert into patient_files will use this
     */
    const PATIENT_FILE_TABNAME  = 'PrivateContactform';
    const PATIENT_FILE_TITLE    = 'PrivateContactform PDF'; //this will be translated
            
    /**
     * insert into patient_course will use this
     */
    const PATIENT_COURSE_TITLE      = 'PrivateContactform PDF was created';
    const PATIENT_COURSE_TABNAME    = 'privatecontactform';
    const PATIENT_COURSE_TYPE       = ''; // add letter

    
    
    

}