<?php

/**
 * SisStationary
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ISPC
 * @subpackage Application (2018-08-09)
 * @author     carmen <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SisStationary extends BaseSisStationary
{
	/**
	 * define the FORMID and FORMNAME, if you want to piggyback some triggers
	 * @var unknown
	 */
	const TRIGGER_FORMID    = null;
	const TRIGGER_FORMNAME  = 'frmSisStationary_ispc2240';
	
	/**
	 * insert into patient_files will use this
	 */
	const PATIENT_FILE_TABNAME  = 'SisStationary_ispc2240';
	const PATIENT_FILE_TITLE    = 'SisStationary_PDF 2018'; //this will be translated
	
	/**
	 * insert into patient_course will use this
	 */
	const PATIENT_COURSE_TITLE_CREATE = 'SIS - stationär Formular hinzugefügt';
	const PATIENT_COURSE_TITLE_EDIT = 'SIS - stationär Formular wurde editiert';
	const PATIENT_COURSE_TABNAME_SAVE    = 'SisStationary_save';
	const PATIENT_COURSE_TYPE       = 'F';
	
	public function findOrCreateOneByIdAndIpid($id = 0 , $ipid = '', array $data = array(), $hydrationMode = Doctrine_Core::HYDRATE_RECORD)
	{
		if ( empty($id) || ! $entity = $this->getTable()->findOneByIdAndIpid($id, $ipid)) {
	
			$entity = $this->getTable()->create(array( 'ipid' => $ipid));
		}
	
		unset($data[$this->getTable()->getIdentifier()]);
	
		$entity->fromArray($data); //update
	
		$entity->save(); //at least one field must be dirty in order to persist
	
		return $entity;
	}
	
	
	
	/**
	 * @claudiu
	 * @param string $ipid
	 * @param unknown $hydrationMode
	 * @return void|Ambigous <Doctrine_Collection, multitype:>
	 */
	public function findByIpid( $ipid = '', $hydrationMode = Doctrine_Core::HYDRATE_ARRAY )
	{
		if (empty($ipid) || ! is_string($ipid)) {
	
			return;
	
		} else {
			return $this->getTable()->findBy('ipid', $ipid, $hydrationMode);
	
		}
	}
	
	public function get_patient_sis_stationary($ipid,$clientid,$form_id = false)
	{
		$actions_sql = Doctrine_Query::create()
		->select('*')
		->from('SisStationary')
		->where("ipid= ?", $ipid)
		->andWhere("clientid= ?", $clientid);
		if($form_id ){
			$actions_sql->andWhere("id = ?", $form_id);
		}
		//$actions_sql->andWhere('isdelete = 0');
	
		$actionsarray = $actions_sql->fetchArray();
	
		if($actionsarray)
		{
			return $actionsarray;
		}
	}

}