<?php

/**
 * SisStationaryThematics
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ISPC
 * @subpackage Application (2018-08-13)
 * @author     carmen <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SisStationaryThematics extends BaseSisStationaryThematics
{

	public function findOrCreateOneByIdAndIpid($id = 0 , $ipid = '', array $data = array(), $hydrationMode = Doctrine_Core::HYDRATE_RECORD)
	{
		if ( empty($id) || ! $entity = $this->getTable()->findOneByIdAndIpid($id, $ipid)) {
	
			$entity = $this->getTable()->create(array( 'ipid' => $ipid));
		}
	
		unset($data[$this->getTable()->getIdentifier()]);
	
		$entity->fromArray($data); //update
	
		$entity->save(); //at least one field must be dirty in order to persist
	
		return $entity;
	}
	
	
	
	/**
	 * @claudiu
	 * @param string $ipid
	 * @param unknown $hydrationMode
	 * @return void|Ambigous <Doctrine_Collection, multitype:>
	 */
	public function findByIpid( $ipid = '', $hydrationMode = Doctrine_Core::HYDRATE_ARRAY )
	{
		if (empty($ipid) || ! is_string($ipid)) {
	
			return;
	
		} else {
			return $this->getTable()->findBy('ipid', $ipid, $hydrationMode);
	
		}
	}
	
	public function get_patient_sis_stationary_thematics($ipid,$clientid,$form_id)
	{
		$actions_sql = Doctrine_Query::create()
		->select('*')
		->from('SisStationaryThematics')
		->where("ipid= ?", $ipid)
		->andWhere("clientid=?", $clientid)
		->andWhere("form_id = ?", $form_id);
		//->andWhere('isdelete = 0');
		$actionsarray = $actions_sql->fetchArray();
	
		if($actionsarray)
		{
			return $actionsarray;
		}
	}

}