<?php

/**
 * StandardDocumentation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ISPC-2494
 * @subpackage Application (2019-12-06)
 * @author     Ancuta <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class StandardDocumentation extends BaseStandardDocumentation
{            
    /**
     * translations are grouped into an array
     * @var unknown
     */
    const LANGUAGE_ARRAY    = 'standarddocumentation_lang';
            
    /**
     * define the FORMID and FORMNAME, if you want to piggyback some triggers
     * @var unknown
     */
    const TRIGGER_FORMID    = null;
    const TRIGGER_FORMNAME  = 'frm_standarddocumentation';
            
    /**
     * insert into patient_files will use this
     */
    const PATIENT_FILE_TABNAME  = 'StandardDocumentation';
    const PATIENT_FILE_TITLE    = 'StandardDocumentation PDF'; //this will be translated
            
    /**
     * insert into patient_course will use this
     */
    const PATIENT_COURSE_TITLE      = 'StandardDocumentation PDF was created';
    const PATIENT_COURSE_TABNAME    = 'standarddocumentation';
    const PATIENT_COURSE_TYPE       = ''; // add letter

    
    public static function findFormsOfIpids($ipids =  array() , $fillFinished = null)
    {
        if (empty($ipids) || ! is_array($ipids)) {
            return; //fail-safe
        }
        
        $q = Doctrine_Query::create()
        ->select('*')
        ->from('StandardDocumentation ')
        ->whereIn("ipid", $ipids) 
        ->andwhere('isdelete = 0');
        
        if ( ! is_null($fillFinished)) {
            $q->andWhere("id IS NOT NULL");
        }
        
        $sd_forms =  $q->fetchArray();
        
        if (empty($sd_forms)) {
            return; //you have no forms
        }
       
        return $sd_forms;
    }
    
    public function getLabelsArray()
    {
        $labels = array(
            "opt_labels_symp" => array(
                "0"=>"Gar nicht",
                "1"=>"Ein wenig",
                "2"=>"Maßig",
                "3"=>"Stark",
                "4"=>"Extrem stark",
                "5"=>"Nicht beurteilbar"
            ),
            "opt_labels_life" => array(
                "1"=>"Sehr schlecht",
                "2"=>"",
                "3"=>"",
                "4"=>"",
                "5"=>"",
                "6"=>"",
                "7"=>"Ausge-zeichnet",
                "8"=>"Nicht beurteilbar"
            ),
            "opt_labels_free" => array(
                "0"=>"Gar nicht",
                "1"=>"Selten",
                "2"=>"Manchmal",
                "3"=>"Meistens",
                "4"=>"Immer",
                "5"=>"Nicht beurteilbar"
            ),
            "opt_labels_nofree" => array(
                "0"=>"Immer",
                "1"=>"Meistens",//"1"=>"Selten",
                "2"=>"Manchmal",
                "3"=>"Selten",//"3"=>"Meistens",
                "4"=>"Gar nicht",
                "5"=>"Nicht beurteilbar"
            )
       ); 
       
       return $labels;
    }

}
