<?php

/**
 * StudypoolEmailsLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class StudypoolEmailsLog extends BaseStudypoolEmailsLog
{
	private static $mandatory_columns = array(
			'clientid',
	);
	
	public function set_new_record($params = array())
	{
	
		if (empty($params) || !is_array($params)) {
			return false;// something went wrong
		}
	
		foreach (self::$mandatory_columns as $column) {
	
			if ( empty($params[$column]) &&  empty($this->{$column}) )
			{
				return false;
			}
		}
	
		foreach ($params as $k => $v)
			if (isset($this->{$k})) {
				$this->{$k} = $v;
			}
	
		$this->save();
	
		return $this->id;
	
	}
	
	public function get_log( $clientid = 0 ) 
	{
		
		$cols = $this->getTable()->getColumnNames();
		
		$q = $this->getTable()->createQuery()
		->where("clientid = ?" , $clientid)
		->fetchArray();

		return array_merge(array($cols), $q);
	}
	
	
}