<?php

/**
 * SurveyMasterChains
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ISPC
 * @subpackage Application (2020-11-04)
 * @author     Ancuta <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 * 
 * ISPC-2695
 */
class SurveyMasterChains extends BaseSurveyMasterChains
{            
    

}