<?php

/**
 * Usershifts2patients
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ISPC
 * @subpackage Application (2018-10-11) [ISPC-2257]
 * @author     Ancuta <office@originalware.com> 
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Usershifts2patients extends BaseUsershifts2patients
{

    public function get_saved_data($clientid, $period = false, $ipids = array(), $userids = array())
    {
        if (empty($clientid)) {
            $logininfo = new Zend_Session_Namespace('Login_Info');
            $clientid = $logininfo->clientid;
        }
        
        if (! empty($ipids)) {
            
            if (! is_array($ipids)) {
                $ipids = array(
                    $ipids
                );
            }
        }
        
        if (! empty($userids)) {
            
            if (! is_array($userids)) {
                $userids = array(
                    $userids
                );
            }
        }
        
        $saved_usershifts = Doctrine_Query::create()->from('Usershifts2patients INDEXBY id')
            ->select('*')
            ->where('clientid = ?', $clientid);
        if ($period) {
            $saved_usershifts->andWhere('DATE(shift_date) BETWEEN ? AND ?', array(
                $period['start'],
                $period['end']
            ));
        }
        if (! empty($ipids)) {
            $saved_usershifts->andWhereIn('ipid', $ipids);
        }
        if (! empty($userids)) {
            $saved_usershifts->andWhereIn('userid', $userids);
        }
        
        $saved_usershifts->andWhere('isdelete = 0');
        $saved_usershifts_array = $saved_usershifts->fetchArray();
        
        if (! empty($saved_usershifts_array)) {
            return $saved_usershifts_array;
        } else {
            return array();
        }
    }
    
    
    public function get_all_data($clientid, $period = false, $ipids = array(), $userids = array())
    {
        if (empty($clientid)) {
            $logininfo = new Zend_Session_Namespace('Login_Info');
            $clientid = $logininfo->clientid;
        }
        
        $epids = array();
        if (! empty($ipids)) {
            
            if (! is_array($ipids)) {
                $ipids = array(
                    $ipids
                );
            }
            
            
            $EpidIpidMapping = new EpidIpidMapping();
            $ipids2epids = $EpidIpidMapping->getIpidsEpids($ipids);
            
            $epids2ipids = array_flip($ipids2epids);
            $epids = array_values($ipids2epids);
//             dd($epids2ipids);
            //41ea078f9f34cbca087c8735fd85183ff9309a99
            
            
            /*
             *             [0] => 00b72460851402092e5ac0ed4332677acf0953b4
            [1] => 08e72971b2299765f05a653dd3ad326a05f5b533
            [2] => 1aaa2abe6510642a97cfb745529ccb62e2cb4f21
            [3] => 3941275cb524df62ce1e228165c78fb797e83a45
            [4] => 41ea078f9f34cbca087c8735fd85183ff9309a99
            [5] => 68970bd31290ddf56c15f3634f5cf5ba0c8811a7
             * */
        }
        
        if (! empty($userids)) {
            
            if (! is_array($userids)) {
                $userids = array(
                    $userids
                );
            }
        }
        
        $saved_usershifts = Doctrine_Query::create()->from('Usershifts2patients INDEXBY id')
            ->select('*')
            ->where('clientid = ?', $clientid);
        if ($period) {
            $saved_usershifts->andWhere('DATE(shift_date) BETWEEN ? AND ?', array(
                $period['start'],
                $period['end']
            ));
        }
        if (! empty($ipids)) {
            $saved_usershifts->andWhereIn('ipid', $ipids);
        }
        if (! empty($userids)) {
            $saved_usershifts->andWhereIn('userid', $userids);
        }
        
        $saved_usershifts->andWhere('isdelete = 0');
        $saved_usershifts_array = $saved_usershifts->fetchArray();
        
        
        // check if users are nurses 
        $UserObj = new User();
        $client_users = $UserObj->get_AllByClientid($clientid,array('usercolor','groupid','isactive_date'));
        usort($client_users, array(new Pms_Sorter('last_name'), "_strcmp"));
        
        $usergroup = new Usergroup();
        $clientGroups = array();
        $clientGroups = $usergroup->getUserGroups(array('4','5'), $clientid);
        $gr_doctors = array();
        $gr_nurses  = array();
        
        $group_name = array();
        foreach($clientGroups as $k=>$grm_data){
            $group_name[$grm_data['id']] =  $grm_data['groupname'];
            if($grm_data['groupmaster'] == "4"){
                $gr_doctors[] = $grm_data['id'];
                $allowed[] = $grm_data['id'];
            }
            if($grm_data['groupmaster'] == "5"){
                $gr_nurses[] = $grm_data['id'];
                $allowed[] = $grm_data['id'];
            }
        }
        
        $doctor_users = array();
        $nurse_users = array();
        foreach($client_users as $k=>$udata){
        
            if($udata['isdelete'] == "0" 
                && in_array($udata['groupid'],$allowed) 
                && in_array($udata['id'],$userids) 
                 )
            {
                if(in_array($udata['groupid'],$gr_doctors)){
                    $doctor_users[] =  $udata['id'];
                }
                if(in_array($udata['groupid'],$gr_nurses)){
                    $nurse_users[] =  $udata['id'];
                }
            }
        }
        
        
        // get assigned to patients
        $assigned_users2patients = array();
        
        if ( ! empty($epids) && ! empty($nurse_users) ) {
      
            $fdoc = Doctrine_Query::create()
            ->select("*")
            ->from('PatientQpaLeading')
            ->whereIn("ipid", $ipids)
            ->andWhereIn("userid", $nurse_users)
            ->andWhere('clientid = ?',$clientid)
            ->andWhere('ipid != ""');
            $star_users = $fdoc->fetchArray();
        
        
            if( ! empty($star_users)){
        
                foreach( $star_users as $k => $suval){
                    $star_users2patients[$suval['ipid']][] = $suval['userid'];
                }

                
                $assigned_usr = Doctrine_Query::create()
                ->select('*')
                ->from('PatientQpaMapping')
                ->whereIn('epid', $epids);
                $assigned_users = $assigned_usr->fetchArray();
        
                if( !empty( $assigned_users ) )
                {
                    foreach( $assigned_users as $k_usr => $v_usr )
                    {
                        if(
                            in_array($v_usr['userid'], $nurse_users)
                            && in_array($v_usr['userid'], $star_users2patients[$epids2ipids[$v_usr['epid']]])
                        ){
                            $assigned_users2patients[$epids2ipids[$v_usr['epid']]] =  $v_usr['userid'];
                        }
                    }
                }
            }
        }
        
        $result = array();
        $result['saved'] =  $saved_usershifts_array;
        $result['assigned'] = $assigned_users2patients;  
        
        
        if (! empty($result)) {
            return $result;
        } else {
            return array();
        }
    }
    
    
    
    
    public function get_shift_assignment($clientid, $userids = array(), $invoice_period = false, $user_periods = false, $ipids = array()){
        
//         $logininfo = new Zend_Session_Namespace('Login_Info');
        if( empty($userids) || empty($clientid) || empty($invoice_period) ) {
            
            return false;
            
        }         

        
        // GET details of patient in period    
        $conditions['client'] = $clientid;
        if( ! empty($ipids) ){
            $conditions['ipids'] = $ipids;
        }
        $conditions['periods'][0]['start'] = $invoice_period['start'];
        $conditions['periods'][0]['end'] = $invoice_period['end'];
        
        $patient_days = Pms_CommonData::patients_days($conditions, $sql);
        $active_ipids = array_keys($patient_days);
        
        
        $epid2ipid = array();
        $patients_details = array();
        
    	foreach($patient_days as $ipid=>$pdata){

    	    $epid2ipid[$ipid] = $pdata['details']['epid'];

    	    $patients_details[$ipid]['real_active_days'] = array_values($pdata['real_active_days']);
	        foreach( $pdata['real_active_days'] as $k => $rday ){
	           $patients_details[$ipid]['active_dats_Ymd'][] = date('Y-m-d',strtotime($rday));
	        }
	    }
// 	    if($logininfo->userid == "338-test"){
// 	        print_r("active_ipids \n ");
// 	        print_r($active_ipids)   ;
// 	    }
	    if( empty($active_ipids)){
	        return false;
	    }
		    
        
       // get all shifts of selected users - saved and assigned  
       $shifts = array();
       $shifts =  $this->get_all_data($clientid, $invoice_period, $active_ipids, $userids);

//        if($logininfo->userid == "338-test"){
//            print_r("shifts \n ");
//            print_r($shifts)   ;
//        }
       
       if( empty($shifts) ) {
           return false;
       }
       
       $saved_per_month  = array();
       $saved_shifts = array();
       foreach($shifts['saved'] as $k => $s_entry){
           if( in_array($s_entry['shift_date'], $patients_details[$s_entry['ipid']]['active_dats_Ymd'] ) ){
               $saved_shifts[$s_entry['userid']][$s_entry['ipid']][$s_entry['shift_date']][] = $s_entry['shift_type'];
               $saved_per_month[$s_entry['userid']][$s_entry['ipid']][date('Y-m',strtotime($s_entry['shift_date']))][$s_entry['shift_type']][] = $s_entry['shift_type'];
           }
       }
       
       if(!empty($shifts['assigned'])){
           foreach($shifts['assigned'] as $ipid => $star_nurse){
               foreach($patients_details[$ipid]['active_dats_Ymd'] as $k=>$active_day ){
                   if(empty($saved_per_month[$star_nurse][$ipid][date('Y-m',strtotime($active_day))]['pflege'])){
                       $saved_shifts[$star_nurse][$ipid][$active_day][] = 'pflege';
                   }
               }
           }
       }
      
       
//        if($logininfo->userid == "338-test"){
//         print_r("saved_shifts \n ");
//         print_r($saved_shifts);
//        }
       
       if( empty($saved_shifts) ) {
           return false;
       }  

       $sh_ipids = array();
       foreach($saved_shifts as $uid => $patientns_data ){
           foreach($patientns_data as $patient=>$shifts){
               $sh_ipids[] = $patient;
           }
       }
       
       if(empty($sh_ipids)){
           return false;
       }
       $sh_ipids = array_unique($sh_ipids);
       // for all the patients from STEP 1  get the allowed days from SH anlage

       
       
       // STEP 2
       $patient_days_details = array();
       $fam_doc2ipid = array();
       foreach($patient_days as $ipidd => $pde){
           if(in_array($ipidd,$sh_ipids)){
               $patient_days_details[$ipidd] = $pde;
                
               $fdocs_detaisls[$ipidd] = $pde['details']['familydoc_id']; 
               $fam_doc2ipid[$pde['details']['familydoc_id']] = $ipidd; 
           }
       }

       // check module
       $Modules_obj = new Modules();
       if($Modules_obj->checkModulePrivileges("176", $clientid))
       {
           $familly_doctor_billing = true;
       }
       else
       {
           $familly_doctor_billing = false;
       }

       $shift_billing_doctors = array();
       if($familly_doctor_billing && !empty($fam_doc2ipid)){
           // get all doctors that have billing
            
           $docids = array_keys($fam_doc2ipid);
           $FamilyDoctor_obj = new FamilyDoctor();
           $doctor_details = $FamilyDoctor_obj->get_family_doctors_multiple($docids);
            
           if(!empty($doctor_details)){
               $shift_billing_doctors_arr = array_filter($doctor_details, function($item) use ($row) {
                   return $item['shift_billing'] == 1;
               });
               
               if( !empty($shift_billing_doctors_arr)){
                   $shift_billing_doctors = array_keys($shift_billing_doctors_arr);
               }
           }
           
       }
       
       // biling doctor  =  234958
       

       
       // get all sh anlage   - relevant data :: The health insurance billing
       $anlage_14_control = new Anlage14Control();
       $invoice_data = $anlage_14_control->anlage_14_invoicesactions($clientid, $patient_days_details, $invoice_period);

//        dd($invoice_data['master_data_invoices']);


//        if($logininfo->userid == "338-test"){
//            print_r("invoice_data \n ");
//            print_r($invoice_data);
//        }
        
       
       if(empty($invoice_data ['export_data'])){
           return false;
       }
       
       $patients_valid_days = array();
       $patients_valid_days = $invoice_data ['export_data'];
//     dd($patients_valid_days);
       
       // get master price list     
       $p_list = new PriceList();
       $master_price_list = $p_list->get_period_price_list($invoice_period['start'], $invoice_period['end']);
 
       $shift_type2price_group = array('day'=>'day_doctor','night'=>'night_doctor','pflege'=>'assigned_nurse','familly_doc_shift'=>'family_doctor'); 

       
       foreach($saved_shifts as $user_id=> $shift_arr)
       {
           foreach($shift_arr as $sh_ipid => $shift_date2shift_type )
           {
               foreach($shift_date2shift_type as $date => $shift_type)
               {
 
                   
                   for ($s=0;$s<=count($shift_type)-1;$s++)
                       {
                       
                       // if in valid days
                       // in flatrate days OR in visit days  && sapv_highest == 4 && NOT IN HOSPILAT
                       // ISPC-2257 - Ancuta - 23.07.2019 addd Not in hospital condition
                       $sh = 'VVD';
                       if( 
                           in_array(date('d.m.Y',strtotime($date)),$patients_valid_days[$sh_ipid]['all_valid_days'])
                           && (in_array(date('d.m.Y',strtotime($date)),$patients_valid_days[$sh_ipid]['FLATRATE_DAYS']) || in_array(date('d.m.Y',strtotime($date)),$patients_valid_days[$sh_ipid]['VISITS_ALL']))
                           && $patients_valid_days[$sh_ipid]['sapv_day2sapv_type'][date('d.m.Y',strtotime($date))] == "4"
                           && ! in_array(date('d.m.Y',strtotime($date)),$patient_days_details[$sh_ipid]['hospiz']['real_days_cs'])
                           && ! in_array(date('d.m.Y',strtotime($date)),$patient_days_details[$sh_ipid]['hospital']['real_days_cs'])
                           )
                       {
                          $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['shortcut'] = $sh;
                          $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['price'] = $master_price_list[$date][0][$sh][$shift_type2price_group[$shift_type[$s]]]['price'];
                          $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['shift_type'] = $shift_type[$s];
                          $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['price_group'] = $shift_type2price_group[$shift_type[$s]];
                          $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['list'] = $master_price_list[$date][0][$sh][$shift_type2price_group[$shift_type[$s]]]['list'];
                          $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['qty'] = 1;
                          $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['days'][$shift_type[$s]][] = date('d.m.Y',strtotime($date));
                          
                          
                          
                          if($familly_doctor_billing && in_array($fdocs_detaisls[$sh_ipid],$shift_billing_doctors) ){
                           
                              $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['shortcut'] = $sh;
                              $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['price'] = $master_price_list[$date][0][$sh][$shift_type2price_group['familly_doc_shift']]['price'];
                              $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['shift_type'] = 'familly_doc_shift';
                              $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['price_group'] = $shift_type2price_group['familly_doc_shift'];
                              $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['list'] = $master_price_list[$date][0][$sh][$shift_type2price_group['familly_doc_shift']]['list'];
                              $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['qty'] = 1;
                              $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['days']['family_doctor'][] = date('d.m.Y',strtotime($date));
                          }
                          
                       }
                       
                       // ISPC-2257 - Ancuta - 23.07.2019 addd Not in hospital condition
                       $sh = 'TVD';
                       if( 
                           in_array(date('d.m.Y',strtotime($date)),$patients_valid_days[$sh_ipid]['all_valid_days'])
                           && (in_array(date('d.m.Y',strtotime($date)),$patients_valid_days[$sh_ipid]['FLATRATE_DAYS']) || in_array(date('d.m.Y',strtotime($date)),$patients_valid_days[$sh_ipid]['VISITS_ALL']))
                           &&  $patients_valid_days[$sh_ipid]['sapv_day2sapv_type'][date('d.m.Y',strtotime($date))] == "3"
                           && ! in_array(date('d.m.Y',strtotime($date)),$patient_days_details[$sh_ipid]['hospiz']['real_days_cs'])
                           && !in_array(date('d.m.Y',strtotime($date)),$invoice_items['system_user'][$user_id][$sh_ipid]['VVD']['days'][$shift_type[$s]])
                           && ! in_array(date('d.m.Y',strtotime($date)),$patient_days_details[$sh_ipid]['hospital']['real_days_cs'])
                           )
                       {
    //                       $invoice_items['system_user'][$user_id][$sh_ipid][date('d.m.Y',strtotime($date))] = $sh."_price_for_".$shift_type[$s];
    //                       $invoice_items['system_user'][$user_id][$sh_ipid][$sh]['days'][$shift_type[$s]][] = date('d.m.Y',strtotime($date));
                          
                          $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['shortcut'] = $sh;
    //                       $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['price'] = "price_for_".$date."_shortcut: ".$sh." price_group ".$shift_type[$s];
                          $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['price'] = $master_price_list[$date][0][$sh][$shift_type2price_group[$shift_type[$s]]]['price'];
                          $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['shift_type'] = $shift_type[$s];
                          $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['price_group'] = $shift_type2price_group[$shift_type[$s]];
                          $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['list'] = $master_price_list[$date][0][$sh][$shift_type2price_group[$shift_type[$s]]]['list'];
                          $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['qty'] = 1;
                          $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['days'][$shift_type[$s]][] = date('d.m.Y',strtotime($date));
                          
                          
                          
                          if($familly_doctor_billing && in_array($fdocs_detaisls[$sh_ipid],$shift_billing_doctors) ){

                              $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['shortcut'] = $sh;
                              $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['price'] = $master_price_list[$date][0][$sh][$shift_type2price_group['familly_doc_shift']]['price'];
                              $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['shift_type'] = 'familly_doc_shift';
                              $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['price_group'] = $shift_type2price_group['familly_doc_shift'];
                              $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['list'] = $master_price_list[$date][0][$sh][$shift_type2price_group['familly_doc_shift']]['list'];
                              $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['qty'] = 1;
                              $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['days']['family_doctor'][] = date('d.m.Y',strtotime($date));
                          }
                       }
                       
                       // ISPC-2257 - Ancuta - 23.07.2019 addd Not in hospital condition
                       // TODO-2727 Ancuta -18.12.2019- Add NOT in HOSPIZ days
                       // TODO-2727 Ancuta -18.12.2019- Add NOT in visit days 
                       $sh =  "PH1"; // PH2: WHAT ? HOW? 
                       if( 
                           in_array(date('d.m.Y',strtotime($date)),$patients_valid_days[$sh_ipid]['PHONE_ALL'])
                           && !in_array(date('d.m.Y',strtotime($date)),$invoice_items['system_user'][$user_id][$sh_ipid]['items']['VVD']['days'][$shift_type[$s]])
                           && !in_array(date('d.m.Y',strtotime($date)),$invoice_items['system_user'][$user_id][$sh_ipid]['items']['TVD']['days'][$shift_type[$s]])
                           && ! in_array(date('d.m.Y',strtotime($date)),$patient_days_details[$sh_ipid]['hospital']['real_days_cs'])
                           && ! in_array(date('d.m.Y',strtotime($date)),$patient_days_details[$sh_ipid]['hospiz']['real_days_cs'])
                           && ! in_array(date('d.m.Y',strtotime($date)),$patients_valid_days[$sh_ipid]['VISITS_ALL'])
                           )
                       {
                           // Changes requested on 25.04.2019
                              /* if(count($patients_valid_days[$sh_ipid]['phone2day'][date('d.m.Y',strtotime($date))]) >=2){
                                  $phone_qty[$sh_ipid][$sh][$day_dmY] = 2;
                              } else {
                                  $phone_qty[$sh_ipid][$sh][$day_dmY] = count($patients_valid_days[$sh_ipid]['phone2day'][date('d.m.Y',strtotime($date))]);
                              } */
                              
                              $phone_qty[$sh_ipid][$sh][$day_dmY] = 1;
                              
                              $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['shortcut'] = $sh;
                              $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['price'] = $master_price_list[$date][0][$sh][$shift_type2price_group[$shift_type[$s]]]['price'];
                              $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['list'] = $master_price_list[$date][0][$sh][$shift_type2price_group[$shift_type[$s]]]['list'];
                              $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['qty'] = $phone_qty[$sh_ipid][$sh][$day_dmY];
                              $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['days'][$shift_type[$s]][] = date('d.m.Y',strtotime($date));
                              
                              if($familly_doctor_billing && in_array($fdocs_detaisls[$sh_ipid],$shift_billing_doctors) ){
                              
                                  $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['shortcut'] = $sh;
                                  $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['price'] = $master_price_list[$date][0][$sh][$shift_type2price_group['familly_doc_shift']]['price'];
                                  $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['shift_type'] = 'familly_doc_shift';
                                  $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['price_group'] = $shift_type2price_group['familly_doc_shift'];
                                  $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['list'] = $master_price_list[$date][0][$sh][$shift_type2price_group['familly_doc_shift']]['list'];
                                  $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['qty'] = $phone_qty[$sh_ipid][$sh][$day_dmY];
                                  $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['days']['family_doctor'][] = date('d.m.Y',strtotime($date));
                              }
                       }
    
                       
                       // ISPC-2257 - Ancuta - 23.07.2019 addd Not in hospital condition
                       // TODO-2727 Ancuta -18.12.2019- Add NOT in HOSPIZ days 
                       // TODO-2727 Ancuta -18.12.2019- Add NOT in visit days 
                       $sh =  "PH2"; // PH2: WHAT ? HOW? 
                       if( 
                           in_array(date('d.m.Y',strtotime($date)),$patients_valid_days[$sh_ipid]['PHONE_ALL'])
                           && !in_array(date('d.m.Y',strtotime($date)),$invoice_items['system_user'][$user_id][$sh_ipid]['items']['VVD']['days'][$shift_type[$s]])
                           && !in_array(date('d.m.Y',strtotime($date)),$invoice_items['system_user'][$user_id][$sh_ipid]['items']['TVD']['days'][$shift_type[$s]])
                           && ! in_array(date('d.m.Y',strtotime($date)),$patient_days_details[$sh_ipid]['hospital']['real_days_cs'])
                           && ! in_array(date('d.m.Y',strtotime($date)),$patient_days_details[$sh_ipid]['hospiz']['real_days_cs'])
                           && ! in_array(date('d.m.Y',strtotime($date)),$patients_valid_days[$sh_ipid]['VISITS_ALL'])
                           //&& !empty($invoice_items['system_user'][$user_id][$sh_ipid]['items']['PH1']['days'][$shift_type[$s]])
                           )
                       {
                              /* if(count($patients_valid_days[$sh_ipid]['phone2day'][date('d.m.Y',strtotime($date))]) >=2){
                                  $phone_qty[$sh_ipid][$sh][$day_dmY] = 2;
                              } else {
                                  $phone_qty[$sh_ipid][$sh][$day_dmY] = count($patients_valid_days[$sh_ipid]['phone2day'][date('d.m.Y',strtotime($date))]);
                              } */
                           
                              $phone_qty[$sh_ipid][$sh][$day_dmY] = 0;
                              
                              
                              if(count($patients_valid_days[$sh_ipid]['phone2day'][date('d.m.Y',strtotime($date))]) == 1)
                              {
                                  $phone_qty[$sh_ipid][$sh][$day_dmY] = 0; // we already have a PH1 billed
                              }
                              else if(count($patients_valid_days[$sh_ipid]['phone2day'][date('d.m.Y',strtotime($date))]) >= 2)
                              {
                                  $phone_qty[$sh_ipid][$sh][$day_dmY] = 1; // We have a PH1 billed, and only 1 more is allowed
                              } 
                              
                              if($phone_qty[$sh_ipid][$sh][$day_dmY] > 0){
                                  
                                  $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['shortcut'] = $sh;
                                  $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['price'] = $master_price_list[$date][0][$sh][$shift_type2price_group[$shift_type[$s]]]['price'];
                                  $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['list'] = $master_price_list[$date][0][$sh][$shift_type2price_group[$shift_type[$s]]]['list'];
                                  $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['qty'] = $phone_qty[$sh_ipid][$sh][$day_dmY];
                                  $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['days'][$shift_type[$s]][] = date('d.m.Y',strtotime($date));
                                  
                                  if($familly_doctor_billing && in_array($fdocs_detaisls[$sh_ipid],$shift_billing_doctors) ){
                                  
                                      $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['shortcut'] = $sh;
                                      $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['price'] = $master_price_list[$date][0][$sh][$shift_type2price_group['familly_doc_shift']]['price'];
                                      $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['shift_type'] = 'familly_doc_shift';
                                      $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['price_group'] = $shift_type2price_group['familly_doc_shift'];
                                      $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['list'] = $master_price_list[$date][0][$sh][$shift_type2price_group['familly_doc_shift']]['list'];
                                      $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['qty'] = $phone_qty[$sh_ipid][$sh][$day_dmY];
                                      $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['days']['family_doctor'][] = date('d.m.Y',strtotime($date));
                                  }
                              }
                          
                       }
                       
                       
                       // ISPC-2257 - Ancuta - 23.07.2019 addd Not in hospital condition
                       $sh = "HOD";
                       if(
                           in_array(date('d.m.Y',strtotime($date)),$patients_valid_days[$sh_ipid]['curent_period_days_sapv'])
                           && in_array(date('d.m.Y',strtotime($date)),$patient_days_details[$sh_ipid]['hospiz']['real_days_cs'])
                           && in_array(date('d.m.Y',strtotime($date)),$patients_valid_days[$sh_ipid]['VISITS_ALL'])
                           && ! in_array(date('d.m.Y',strtotime($date)),$patient_days_details[$sh_ipid]['hospital']['real_days_cs'])
                       )
                       {
    
                           $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['shortcut'] = $sh;
    //                        $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['price'] = "price_for_".$date."_shortcut: ".$sh." price_group ".$shift_type[$s];
                           $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['price'] = $master_price_list[$date][0][$sh][$shift_type2price_group[$shift_type[$s]]]['price'];
                           $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['shift_type'] = $shift_type[$s];
                           $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['price_group'] = $shift_type2price_group[$shift_type[$s]];
                           $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['list'] = $master_price_list[$date][0][$sh][$shift_type2price_group[$shift_type[$s]]]['list'];
                           $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['qty'] = 1;
                           $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['days'][$shift_type[$s]][] = date('d.m.Y',strtotime($date));
                           
                           
                           if($familly_doctor_billing && in_array($fdocs_detaisls[$sh_ipid],$shift_billing_doctors) ){
                           
                               $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['shortcut'] = $sh;
                               $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['price'] = $master_price_list[$date][0][$sh][$shift_type2price_group['familly_doc_shift']]['price'];
                               $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['shift_type'] = 'familly_doc_shift';
                               $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['price_group'] = $shift_type2price_group['familly_doc_shift'];
                               $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['list'] = $master_price_list[$date][0][$sh][$shift_type2price_group['familly_doc_shift']]['list'];
                               $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['qty'] = 1;
                               $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['days']['family_doctor'][] = date('d.m.Y',strtotime($date));
                           }
                       }
    
                       // ISPC-2257 - Ancuta - 23.07.2019 addd Not in hospital condition
                       $sh = "HOP";
                       if(
                           in_array(date('d.m.Y',strtotime($date)),$patients_valid_days[$sh_ipid]['curent_period_days_sapv'])
                           && in_array(date('d.m.Y',strtotime($date)),$patient_days_details[$sh_ipid]['hospiz']['real_days_cs'])
                           && !in_array(date('d.m.Y',strtotime($date)),$patients_valid_days[$sh_ipid]['VISITS_ALL'])
                           && in_array(date('d.m.Y',strtotime($date)),$patients_valid_days[$sh_ipid]['PHONE_ALL'])
                           && ! in_array(date('d.m.Y',strtotime($date)),$patient_days_details[$sh_ipid]['hospital']['real_days_cs'])
                       )                                                                
                       {
                           $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['shortcut'] = $sh;
                           $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['price'] = $master_price_list[$date][0][$sh][$shift_type2price_group[$shift_type[$s]]]['price'];
                           $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['shift_type'] = $shift_type[$s];
                           $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['price_group'] = $shift_type2price_group[$shift_type[$s]];
                           $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['qty'] = 1;
                           $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['days'][$shift_type[$s]][] = date('d.m.Y',strtotime($date));
                           
                           
                           
                           if($familly_doctor_billing && in_array($fdocs_detaisls[$sh_ipid],$shift_billing_doctors) ){
                           
                               $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['shortcut'] = $sh;
                               $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['price'] = $master_price_list[$date][0][$sh][$shift_type2price_group['familly_doc_shift']]['price'];
                               $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['shift_type'] = 'familly_doc_shift';
                               $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['price_group'] = $shift_type2price_group['familly_doc_shift'];
                               $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['list'] = $master_price_list[$date][0][$sh][$shift_type2price_group['familly_doc_shift']]['list'];
                               $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['entries']['family_doctor'][date('d.m.Y',strtotime($date))]['qty'] = 1;
                               $invoice_items['family_doctors'][$fdocs_detaisls[$sh_ipid]][$sh_ipid]['items'][$sh]['days']['family_doctor'][] = date('d.m.Y',strtotime($date));
                           }
                           
                       }
                       
                       
                       // first treatment day
                       //ISPC-2257     Administrator added a comment - 21/Feb/19 10:55 AM
                       // New Items added  on 04.03.2019  By Ancuta           
                       // ISPC-2257 - Ancuta - 23.07.2019 addd Not in hospital condition
                       $sh = "KO";
                       if(
                           $invoice_data['master_data_invoices'][$sh_ipid][date('d.m.Y',strtotime($date))]['sh_beko']['checked'] == "1"
                           && $invoice_data['master_data_invoices'][$sh_ipid][date('d.m.Y',strtotime($date))]['sh_beko']['qty'] == "1"
                           && $shift_type[$s] == 'pflege'
                           && ! in_array(date('d.m.Y',strtotime($date)),$patient_days_details[$sh_ipid]['hospital']['real_days_cs'])
                       )                                                                
                       {
                           $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['shortcut'] = $sh;
                           $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['price'] = $master_price_list[$date][0][$sh][$shift_type2price_group[$shift_type[$s]]]['price'];
                           $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['shift_type'] = $shift_type[$s];
                           $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['price_group'] = $shift_type2price_group[$shift_type[$s]];
                           $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['qty'] = 1;
                           $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['days'][$shift_type[$s]][] = date('d.m.Y',strtotime($date));
                           
                       }
                       
                       // ISPC-2257 - Ancuta - 23.07.2019 addd Not in hospital condition
                       $sh = "FOLGEKO";
                       if(
                           $invoice_data['master_data_invoices'][$sh_ipid][date('d.m.Y',strtotime($date))]['sh_folgeko']['checked'] == "1"
                           && $invoice_data['master_data_invoices'][$sh_ipid][date('d.m.Y',strtotime($date))]['sh_folgeko']['qty'] == "1"
                           && $shift_type[$s] == 'pflege'
                           && ! in_array(date('d.m.Y',strtotime($date)),$patient_days_details[$sh_ipid]['hospital']['real_days_cs'])
                       )                                                                 
                       {
                           $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['shortcut'] = $sh;
                           $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['price'] = $master_price_list[$date][0][$sh][$shift_type2price_group[$shift_type[$s]]]['price'];
                           $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['shift_type'] = $shift_type[$s];
                           $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['price_group'] = $shift_type2price_group[$shift_type[$s]];
                           $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['entries'][$shift_type[$s]][date('d.m.Y',strtotime($date))]['qty'] = 1;
                           $invoice_items['system_user'][$user_id][$sh_ipid]['items'][$sh]['days'][$shift_type[$s]][] = date('d.m.Y',strtotime($date));
                           
                       }
                   }
               }
           }
       }
       
 
           
       return $invoice_items;
        
    }
}