<!-- Dragos:: ISPC-2777 22.01.2021 -->
<table width="935" border="0" cellspacing="0" cellpadding="0" style="font-family:Arial, Helvetica, sans-serif; font-size:11px; background-color:  #ffe0da;">
	<tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
    			<tr>
                   <td width="935" align="left" valign="top" style="line-height: 1.5;">&nbsp;</td>
                </tr>
      			<tr>
      				<td width="10">&nbsp;</td>
        			<td width="350" align="left" valign="top">
	        			<table width="350" cellspacing="0" cellpadding="0" style="background-color: #fff;">
	        				<tr>
                               <td width="350" align="left" valign="top" style="border-top: 1px solid #ce6370; border-left: 1px solid #ce6370; border-right: 1px solid #ce6370; font-size: 6px; font-weight: bold; line-height: 0.5;">&nbsp;</td>
                           	</tr>
	          				<tr>
                               <td  width="350" align="left" valign="top" style="border-left: 1px solid #ce6370; border-right: 1px solid #ce6370; border-bottom: 1px solid #ce6370;">
	            					<table width="100%" border="0" cellspacing="0" cellpadding="0">
	            						<tr>
                							<td  width="350" align="left" valign="top" style="color: #ce6370; line-height: 1.5;">Krankenkasse bzw. Kostenträger</td>
              							</tr>
              							<tr>
                							<td  width="340" align="left" valign="top" style="line-height: 1.5; font-size:12px;"><? echo $this->kvheader_details['phealthinsurance_name'] ?></td>
              							</tr>
	          						</table>
	          					</td>
          					</tr> 
          					<tr>
          						<td align="left" valign="top"  style="border-left: 1px solid #ce6370; border-right: 1px solid #ce6370; border-bottom: 1px solid #ce6370;">
          							<table width="350" border="0" cellspacing="0" cellpadding="0">
              							<tr>
                							<td colspan="2" width="350" align="left" valign="top" style="color: #ce6370; line-height: 1;">Name, Vorname des Versicherten</td>
              							</tr>
              							<tr>
                							<td colspan="2" width="350" align="left" valign="top" style="color: #ce6370; line-height: 0.5;">&nbsp;</td>
              							</tr>
                						<tr>                							
                							<td width="225" style="font-size:12px;"><? echo nl2br($this->kvheader_details['insured_name_firstname']); ?></td>
                							<td align="left" valign="top">
                								<table width="160" border="0" cellspacing="0" cellpadding="0">
                  									<tr>
                    									<td align="left" valign="top" colspan="2" style="line-height: 2.25;">&nbsp;</td>
                  									</tr>
                  									<tr>
                    									<td width="20" height="21" align="left" valign="top">&nbsp;</td>
                    									<td height="21" align="left" valign="top" colspan="2"  style="font-size:12px;"><? echo $this->kvheader_details['born_on'] ?></td>
                  									</tr>
                   									<tr>
                    									<td height="21" colspan="2">&nbsp;</td>
                  									</tr>
                								</table>
                							</td>                							
              							</tr>
              						</table>
              					</td>
              				</tr>
              				<tr>
           						<td align="left" valign="top"  style="border-left: 1px solid #ce6370; border-right: 1px solid #ce6370; border-bottom: 1px solid #ce6370;">
           							<table width="350" border="0" cellspacing="0" cellpadding="0">
           								<tr>
                							<td colspan="5" width="350" align="left" valign="top" style="color: #ce6370; line-height: 0.25;">&nbsp;</td>
              							</tr>
              							<tr>
							                
							                <td width="110" align="left" valign="top" style="color: #ce6370; line-height: 1.25;">Kostenträgerkennung</td>
							                <td width="5" align="left" valign="top" style="color: #ce6370; line-height: 1.25;">&nbsp;</td>
							                <td width="130" align="left" valign="top" style="color: #ce6370; line-height: 1.25;">Versicherten-Nr.</td>
							                <td width="5" align="left" valign="top" style="color: #ce6370; line-height: 1.25;">&nbsp;</td>
							                <td width="100" align="left" valign="top" style="color: #ce6370; line-height: 1.25;">Status</td>
						              	</tr>
						              	<tr>
                							<td colspan="5" width="350" align="left" valign="top" style="color: #ce6370; line-height: 0.25;">&nbsp;</td>
              							</tr>
						              	<tr>
							                
							                <td width="110" align="left" valign="top" style="line-height: 1.25; border-right: 1px solid #ce6370; font-size:12px;"><? echo $this->kvheader_details['health_insurance_nr'] ?></td>
							                <td width="5" align="left" valign="top" style="color: #ce6370; line-height: 1.25;">&nbsp;</td>
							                <td width="130" align="left" valign="top" style="line-height: 1.25; border-right: 1px solid #ce6370; font-size:12px;"><? echo $this->kvheader_details['health_insurance_patient_number'] ?></td>
							                <td width="5" align="left" valign="top" style="color: #ce6370; line-height: 1.25;">&nbsp;</td>
							                <td width="100" align="left" valign="top" style="line-height: 1.25;font-size:12px;"><? echo $this->kvheader_details['health_insurance_patient_status'] ?></td>
						              	</tr>
            						</table>
            					</td>
          					</tr>
          					<tr>
            					<td align="left" valign="top"  style="border-left: 1px solid #ce6370; border-right: 1px solid #ce6370; border-bottom: 1px solid #ce6370;">
           							<table width="350" border="0" cellspacing="0" cellpadding="0">
           								<tr>
                							<td colspan="5" width="370" align="left" valign="top" style="color: #ce6370; line-height: 0.25;">&nbsp;</td>
              							</tr>
              							<tr>
							               
							                <td width="110" align="left" valign="top" style="color: #ce6370; line-height: 1.5;">Betriebsstätten-Nr.</td>
							                <td width="5" align="left" valign="top" style="color: #ce6370; line-height: 1.5;">&nbsp;</td>
							                <td width="140" align="left" valign="top" style="color: #ce6370; line-height: 1.5;">Arzt-Nr.</td>
							                <td width="5" align="left" valign="top" style="color: #ce6370; line-height: 1.5;">&nbsp;</td>
							                <td width="90" align="left" valign="top" style="color: #ce6370; line-height: 1.5;">Datum</td>
						              	</tr>
						              	<tr>
                							<td colspan="6" width="350" align="left" valign="top" style="color: #ce6370; line-height: 0.25;">&nbsp;</td>
              							</tr>
              							<tr>
							               
							                <td width="110" align="left" valign="top" style="line-height: 1.5; border-right: 1px solid #ce6370; font-size:12px;"><? echo $this->kvheader_details['stamp_user_bsnr'] ?></td>
							                <td width="5" align="left" valign="top" style="color: #ce6370; line-height: 1.5;">&nbsp;</td>
							                <td width="140" align="left" valign="top" style="line-height: 1.5; border-right: 1px solid #ce6370; font-size:12px;"><? echo $this->kvheader_details['stamp_user_lanr'] ?></td>
							                <td width="5" align="left" valign="top" style="color: #ce6370; line-height: 1.5;">&nbsp;</td>
							                <td width="90" align="left" valign="top" style="line-height: 1.5; font-size:12px;"><? echo $this->kvheader_details['formular_date'] ?></td>
						              	</tr>
           							</table>
            					</td>
          					</tr>              							   
          				</table>	
          			</td>
          			<td width="20">&nbsp;</td>
          			<td width="534" align="left" valign="top">
	        			<table width="534" cellspacing="0" cellpadding="0">
	        				<tr>
                				<td colspan="3" width="534" align="left" valign="bottom" style="line-height: 0.25;">&nbsp;</td>
              				</tr>
	        				<tr>
	        				 	<td width="5" align="left" valign="top">&nbsp;</td>
                				<td width="472" align="left" valign="top" style="color: #ce6370; font-size: 18px; font-weight: bold; line-height: 1.15;">Verordnung häuslicher Krankenpflege</td>
                				<td width="40" align="right" valign="top" style="color: #ce6370; font-size: 18px; font-weight: bold; line-height: 1.15;">12</td>
              				</tr>
	          				<tr>
           						<td width="534" colspan="2" align="left" valign="top">
           							<table width="534" border="0" cellspacing="0" cellpadding="0">
           								<tr>
                							<td colspan="7" width="534" align="left" valign="bottom" style="line-height: 0.5;">&nbsp;</td>
              							</tr>
           								<tr>
                							<td colspan="7" width="534" align="left" valign="bottom" style="color: #ce6370; line-height: 1.5;">Verordnungsrelevante Diagnose(n)<font style="font-weight: bold; font-style: italic">(ICD-10-Code)</font></td>
              							</tr>
						              	<tr>
							                <td width="122" height="23" align="left" valign="top" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;<? echo $this->topform_details['icdnumber1'] ?></td>
							                <td width="7" height="23" align="left" valign="top">&nbsp;</td>							                
							                <td width="122" height="23" align="left" valign="top" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;<? echo $this->topform_details['icdnumber2'] ?></td>
							                <td width="7" height="23" align="left" valign="top">&nbsp;</td>							                
							                <td width="122" height="23" align="left" valign="top" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;<? echo $this->topform_details['icdnumber3'] ?></td>
							                <td width="7" height="23" align="left" valign="top">&nbsp;</td>							                
							                <td width="122" height="23" align="left" valign="top" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;<? echo $this->topform_details['icdnumber4'] ?></td>
						              	</tr>
            						</table>
            					</td>
          					</tr>
          					<tr>
           						<td align="left" valign="top">
           							<table width="534" border="0" cellspacing="0" cellpadding="0">
           								<tr>
                							<td width="534" align="left" valign="bottom" style="line-height: 1;">&nbsp;</td>
              							</tr>
           								<tr>
                							<td width="534" align="left" valign="bottom" style="color: #ce6370; line-height: 1.25;">Einschränkungen, die häusliche Krankenpflege erforderlich machen</td>
              							</tr>
              							<tr>
                							<td width="534" align="left" valign="bottom" style="color: #ce6370; line-height: 1.5;"><font style="font-weight: bold; font-style: italic;">(vgl. auch Leistungsverzeichnis HKP-Rikhtlinie )</font></td>
              							</tr>
						              	<tr>
                							<td width="534" align="left" valign="bottom" style="line-height: 1;">&nbsp;</td>
              							</tr>
							                <?php
							                	if($this->topform_details['topform_textarea'] != "")
												{
							                		$textlines = explode("<br />", nl2br($this->topform_details['topform_textarea']));
													if(count($textlines) == 1)
													{ ?>
													<tr>
														<td width="512" height="23" align="left" valign="middle" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;<? echo $textlines[0]; ?></td>
													</tr>
													<?php
														for($nrl=1; $nrl<=2; $nrl++)
														{ ?>
														<tr>
															<td width="512" height="23" align="left" valign="top" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;</td>
														</tr>
								                <?php } } elseif(count($textlines) == 2) { ?>
								                	<tr>
									                	<td width="512" height="23" align="left" valign="middle" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;&nbsp;<? echo $textlines[0]; ?></td>
									                </tr>
									                <tr>
									                	<td width="512" height="23" align="left" valign="middle" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;<? echo $textlines[1]; ?></td>
													</tr>
													<tr>								                
									                	<td width="512" height="23" align="left" valign="middle" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;</td>
									                </tr>
									            <?php } else { ?>
									            	<tr>
									                	<td width="512" height="23" align="left" valign="middle" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;&nbsp;<? echo $textlines[0]; ?></td>
									                </tr>
									                <tr>
									                	<td width="512" height="23" align="left" valign="middle" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;<? echo $textlines[1]; ?></td>
													</tr>
													<tr>								                
									                	<td width="512" height="23" align="left" valign="middle" style="border-bottom:1px solid #ce6370; background-color: #fff;">&nbsp;<? echo $textlines[2]; ?></td>
									                </tr>
									           <?php } } else { ?>
									           		<tr>
									                	<td width="512" height="23" align="left" valign="middle" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;</td>
									                </tr>
									                <tr>
									                	<td width="512" height="23" align="left" valign="middle" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;</td>
													</tr>
													<tr>								                
									                	<td width="512" height="23" align="left" valign="middle" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;</td>
									                </tr>
									           <?php } ?>
            						</table>
            					</td>
          					</tr>          					
	          			</table>          				
          			</td>
				</tr>   				
			</table>
		</td>
	</tr>
	<tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
    			<tr>
					<td colspan="3" align="left" valign="top" style="line-height: 1;">&nbsp;</td>
				</tr>
    			<tr>
    				<td width="350">
    					<table border="0" cellspacing="0" cellpadding="0">
	    					<tr>
			    				<td width="10" align="left" valign="top" style="font-size: 16px; font-weight: bold; ">&nbsp;</td>
				                <td width="25" align="center" valign="top" style="font-size: 16px; font-weight: bold; border:1px solid #ce6370; background-color: #fff;"><? if($this->topform_details['reg_type_0'] == "1") { echo 'X'; } ?></td>
				                <td width="92" align="left" valign="top" style="line-height: 1.1;  color: #ce6370;">&nbsp;Erst-<br />&nbsp;verordnung</td>
				                <td width="25" align="center" valign="top" style="font-size: 16px; font-weight: bold; border:1px solid #ce6370; background-color: #fff;"><? if($this->topform_details['reg_type_1'] == "1") { echo 'X'; } ?></td>
				                <td width="123" align="left" valign="top" style="line-height: 1.1;  color: #ce6370;">&nbsp;Folge-<br />&nbsp;verordnung</td>
				                <td width="25" align="center" valign="top" style="font-size: 16px; font-weight: bold; border:1px solid #ce6370; background-color: #fff;"><? if($this->topform_details['reg_type_2'] == "1") { echo 'X'; } ?></td>
				                <td width="60" align="left" valign="top" style="line-height: 2.2;  color: #ce6370;">&nbsp;Unfall</td>
			                </tr>
			            </table>
	                </td>
	                <td width="30" align="left" valign="top" style="line-height: 1;">&nbsp;</td>
	                <td width="550">
	                	<table border="0" cellspacing="0" cellpadding="0">
		    				<tr>
		    					<td width="35" height="29" align="center" valign="top" style="line-height: 2.2; color: #ce6370;">vom</td>
			                	<td width="23" height="29" align="center" valign="top" style="font-size: 16px; line-height: 1.5; border:1px solid #ce6370; background-color: #fff;"><? echo $this->topform_details['from'][0] ?></td>
			                	<td width="23" height="29" align="center" valign="top" style="font-size: 16px; line-height: 1.5; border:1px solid #ce6370; background-color: #fff;"><? echo $this->topform_details['from'][1] ?></td>
			                	<td width="23" height="29" align="center" valign="top" style="font-size: 16px; line-height: 1.5; border:1px solid #ce6370; background-color: #fff;"><? echo $this->topform_details['from'][2] ?></td>
			                	<td width="23" height="29" align="center" valign="top" style="font-size: 16px; line-height: 1.5; border:1px solid #ce6370; background-color: #fff;"><? echo $this->topform_details['from'][3] ?></td>
			                	<td width="23" height="29" align="center" valign="top" style="font-size: 16px; line-height: 1.5; border:1px solid #ce6370; background-color: #fff;"><? echo $this->topform_details['from'][4] ?></td>
			                	<td width="23" height="29" align="center" valign="top" style="font-size: 16px; line-height: 1.5; border:1px solid #ce6370; background-color: #fff;"><? echo $this->topform_details['from'][5] ?></td>
			                	
				               	<td width="35" height="29" align="center" valign="top" style="line-height: 2.2; color: #ce6370;">bis</td>
					            <td width="23" height="29" align="center" valign="top" style="font-size: 16px; line-height: 1.5; border:1px solid #ce6370; background-color: #fff;"><? echo $this->topform_details['to'][0] ?></td>
			                	<td width="23" height="29" align="center" valign="top" style="font-size: 16px; line-height: 1.5; border:1px solid #ce6370; background-color: #fff;"><? echo $this->topform_details['to'][1] ?></td>
			                	<td width="23" height="29" align="center" valign="top" style="font-size: 16px; line-height: 1.5; border:1px solid #ce6370; background-color: #fff;"><? echo $this->topform_details['to'][2] ?></td>
			                	<td width="23" height="29" align="center" valign="top" style="font-size: 16px; line-height: 1.5; border:1px solid #ce6370; background-color: #fff;"><? echo $this->topform_details['to'][3] ?></td>
			                	<td width="23" height="29" align="center" valign="top" style="font-size: 16px; line-height: 1.5; border:1px solid #ce6370; background-color: #fff;"><? echo $this->topform_details['to'][4] ?></td>
			                	<td width="23" height="29" align="center" valign="top" style="font-size: 16px; line-height: 1.5; border:1px solid #ce6370; background-color: #fff;"><? echo $this->topform_details['to'][5] ?></td>
				           </tr>
			          	</table>
			     	</td>
              	</tr>
    		</table>
    	</td>
    </tr>
    <tr>
		<td lign="left" valign="top" style="line-height: 1;">&nbsp;</td>
	</tr>
    <tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
    			<tr>
					<td width="15" align="left" valign="top" style="font-size: 14px; font-weight: bold; ">&nbsp;</td>
					<td width="40" align="left" valign="top" style="font-size: 14px; font-weight: bold; background-color: #f38653;">&nbsp;</td>
					<td width="580" align="left" valign="top" style="font-size: 14px; font-weight: bold; background-color: #f38653; color: #ce6370; line-height: 2;">Behandlungsflege</td>
					<td width="5" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
					<td width="268" rowspan="3" style="border:1px solid #ce6370; border-bottom: none; background-color: #fff;">
						<table>
							<tr>
								<td lign="left" valign="top" style="line-height: 0.5;">&nbsp;</td>
							</tr>
							<tr>
								<td colspan="2" width="268" height="23" align="left" valign="top" style="color: #ce6370;"><font style="font-weight: bold;">&nbsp;&nbsp;Dauer nur anzugeben bei Abweichung<br />&nbsp;&nbsp;von dauer des gesamten verordnung</font></td>
							</tr>
							<tr>
								<td lign="left" valign="top" style="line-height: 1.5;">&nbsp;</td>
							</tr>
							<tr>
								<td width="138" height="23" align="left" valign="top" style="line-height: 2; border-bottom:none; border-right: 1px solid #ce6370; color: #ce6370;">&nbsp;Häufigkeit</td>
								<td width="132" height="23" align="left" valign="top" style="line-height: 2; color: #ce6370;">&nbsp;Dauer</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td lign="left" valign="top" style="line-height: 1;">&nbsp;</td>
				</tr>
				<tr>
					<td width="55" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
					<td width="215" height="23" align="left" valign="top" style="line-height: 2;  color: #ce6370;"><font style="font-weight: bold;">Medikamentengabe, </font>Präparate</td>
                	<td width="365" height="23" align="left" valign="middle" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;<? echo $this->treatcare_details['prep_med_0'] ?></td>
                	<td width="5" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>

                </tr>
				<tr>
					<td width="55" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>								                
                	<td colspan="4" height="23"  width="580"align="left" valign="middle" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;<? echo $this->treatcare_details['prep_med_1'] ?></td>
                	<td width="5" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
                	<td colspan="2" width="268" style="border:1px solid #ce6370; background-color: #fff;">
                		<table>
                			<tr>
                				<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; color: #ce6370;">&nbsp;tgl.</td>
                				<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; color: #ce6370;">&nbsp;wtl.</td>
                				<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; color: #ce6370;">&nbsp;mtl.</td>
                				<td width="68" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; color: #ce6370;">&nbsp;vom</td>
                				<td width="64" height="23" align="left" valign="top" style="line-height: 2; color: #ce6370;">&nbsp;bis</td>                				
                			</tr>               		
                		</table>
                	</td>
                </tr>
    		</table>
    	</td>
    </tr>
    <tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
    			
    			<tr>
    				<td width="55" height="21" align="left" valign="top">&nbsp;</td>
    				<td width="25" align="center" valign="top" style="font-size: 16px; font-weight: bold; border:1px solid #ce6370; background-color: #fff;"><? if($this->treatcare_details['med_box'] == "1") { echo 'X'; } ?></td>
				    <td width="555" align="left" valign="top" style="line-height: 2;  color: #ce6370;">&nbsp;Herrichten der Medikamentenbox</td>
				    <td width="5" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
	                <td colspan="2" width="268" style="border:1px solid #ce6370; background-color: #fff;">
                		<table>
                			<tr>
                				<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][0]['right_1'] ?></td>
                				<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][0]['right_2'] ?></td>
                				<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][0]['right_3'] ?></td>
                				<td width="68" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][0]['right_4'] ?></td>
                				<td width="64" height="23" align="left" valign="top" style="line-height: 2; ">&nbsp;<? echo $this->treatcare_details['frequency'][0]['right_5'] ?></td>                				
                			</tr>               		
                		</table>
                	</td>
              	</tr>
			</table>
		</td>
	</tr>
	<tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
    			
    			<tr>
    				<td width="55" height="21" align="left" valign="top">&nbsp;</td>
    				<td width="25" align="center" valign="top" style="font-size: 16px; font-weight: bold; border:1px solid #ce6370; background-color: #fff;"><? if($this->treatcare_details['prep_med_4'] == "1") { echo 'X'; } ?></td>
				    <td width="555" align="left" valign="top" style="line-height: 2;  color: #ce6370;">&nbsp;Medikamentengabe</td>
				    <td width="5" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
	                <td colspan="2" width="268" style="border:1px solid #ce6370; background-color: #fff;">
                		<table>
                			<tr>
                				<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][1]['right_1'] ?></td>
                				<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][1]['right_2'] ?></td>
                				<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][1]['right_3'] ?></td>
                				<td width="68" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][1]['right_4'] ?></td>
                				<td width="64" height="23" align="left" valign="top" style="line-height: 2; ">&nbsp;<? echo $this->treatcare_details['frequency'][1]['right_5'] ?></td>                				
                			</tr>               		
                		</table>
                	</td>
              	</tr>
			</table>
		</td>
	</tr>
	
	<tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
    			
    			<tr>
    				<td width="55" height="23" align="left" valign="top">&nbsp;</td>
    				<td width="25" height="23" align="center" valign="top" style="font-size: 16px; font-weight: bold; border:1px solid #ce6370; background-color: #fff;"><? if($this->treatcare_details['inject'] == "1") { echo 'X'; } ?></td>
    				<td width="172" height="23" align="left" valign="top" style="line-height: 2;  color: #ce6370;">&nbsp;Injektionen</td>
    				<td width="25" height="23" align="center" valign="top" style="font-size: 16px; font-weight: bold; border:1px solid #ce6370; background-color: #fff;"><? if($this->treatcare_details['made'] == "1") { echo 'X'; } ?></td>
    				<td width="119" height="23" align="left" valign="top" style="line-height: 2;  color: #ce6370;">&nbsp;herrichten</td>
    				<td width="25" height="23" align="center" valign="top" style="font-size: 16px; font-weight: bold; border:1px solid #ce6370; background-color: #fff;"><? if($this->treatcare_details['intram'] == "1") { echo 'X'; } ?></td>
    				<td width="118" height="23" align="left" valign="top" style="line-height: 2;  color: #ce6370;">&nbsp;intramuskulär</td>
	                <td width="25" height="23" align="center" valign="top" style="font-size: 16px; font-weight: bold; border:1px solid #ce6370; background-color: #fff;"><? if($this->treatcare_details['subcut'] == "1") { echo 'X'; } ?></td>
	                <td width="76" height="23" align="left" valign="top" style="line-height: 2;  color: #ce6370;">&nbsp;subkutan</td>
	                <td colspan="2" width="268" style="border:1px solid #ce6370; background-color: #fff;">
                		<table>
                			<tr>
                				<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][2]['right_1'] ?></td>
                				<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][2]['right_2'] ?></td>
                				<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][2]['right_3'] ?></td>
                				<td width="68" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][2]['right_4'] ?></td>
                				<td width="64" height="23" align="left" valign="top" style="line-height: 2; ">&nbsp;<? echo $this->treatcare_details['frequency'][2]['right_5'] ?></td>                				
                			</tr>               		
                		</table>
                	</td>
              	</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td>
			<table>
				<tr>
					<td width="60" align="left" valign="top" height="23">&nbsp;</td>
					<td width="215" align="left" valign="top" height="23" style="line-height: 2;  color: #ce6370;"><font style=" font-weight: bold;">Blutzuckermessung</font></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
    			
    			<tr>
    				<td width="55" height="21" align="left" valign="top">&nbsp;</td>
	                <td width="25" height="21" align="center" valign="top" style="font-size: 16px; font-weight: bold; border:1px solid #ce6370; background-color: #fff;"><? if($this->treatcare_details['first_new_appoint'] == "1") { echo 'X'; } ?></td>
	                <td width="289" height="23" align="left" valign="top" style="line-height: 1.1;  color: #ce6370;">&nbsp;Erst- oder Neueinstellung<br />&nbsp;max. 4 Wochen und max. 3x täglich</td>
	                <td width="25" height="21" align="center" valign="top" style="font-size: 16px; font-weight: bold; border:1px solid #ce6370; background-color: #fff;"><? if($this->treatcare_details['intens_insulint'] == "1") { echo 'X'; } ?></td>
	                <td width="247" height="23" align="left" valign="top" style="line-height: 2;  color: #ce6370;">&nbsp;bei intensivierter Insulintherapie</td>
	                <td colspan="2" width="268" style="border:1px solid #ce6370; background-color: #fff;">
                		<table>
                			<tr>
                				<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][3]['right_1'] ?></td>
                				<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][3]['right_2'] ?></td>
                				<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][3]['right_3'] ?></td>
                				<td width="68" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][3]['right_4'] ?></td>
                				<td width="64" height="23" align="left" valign="top" style="line-height: 2; ">&nbsp;<? echo $this->treatcare_details['frequency'][3]['right_5'] ?></td>                				
                			</tr>               		
                		</table>
                	</td>
              	</tr>
			</table>
		</td>
	</tr>
	<tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
    			<tr>
					<td colspan="4" align="left" valign="top" style="line-height: 1.5;">&nbsp;</td>
				</tr>
    			<tr>
    				<td width="55" height="21" align="left" valign="top">&nbsp;</td>
    				<td width="315" height="23" align="left" valign="top" style="line-height: 2;  color: #ce6370;"><font style="font-weight: bold">Kompressionsbehandlung</font></td>
	                <td width="25" height="21" align="center" valign="top" style="font-size: 16px; font-weight: bold; border:1px solid #ce6370; background-color: #fff;"><? if($this->treatcare_details['right_side'] == "1") { echo 'X'; } ?></td>
	                <td width="67" height="23" align="left" valign="top" style="line-height: 2;  color: #ce6370;">&nbsp;rechts</td>
	                <td width="25" height="21" align="center" valign="top" style="font-size: 16px; font-weight: bold; border:1px solid #ce6370; background-color: #fff;"><? if($this->treatcare_details['left_side'] == "1") { echo 'X'; } ?></td>
	               	<td width="57" height="23" align="left" valign="top" style="line-height: 2;  color: #ce6370;">&nbsp;links</td>
	                <td width="25" height="21" align="center" valign="top" style="font-size: 16px; font-weight: bold; border:1px solid #ce6370; background-color: #fff;"><? if($this->treatcare_details['both_sides'] == "1") { echo 'X'; } ?></td>
	                <td width="67" height="23" align="left" valign="top" style="line-height: 2;  color: #ce6370;">&nbsp;beid seits</td>
              	</tr>
			</table>
		</td>
	</tr>
	<tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
    			
    			<tr>
    				<td width="55" height="21" align="left" valign="top">&nbsp;</td>
	                <td width="25" height="21" align="center" valign="top" style="font-size: 16px; font-weight: bold; border:1px solid #ce6370; background-color: #fff;"><? if($this->treatcare_details['comp_attract'] == "1") { echo 'X'; } ?></td>
	                <td width="290" height="23" align="left" valign="top" style="line-height: 2;  color: #ce6370;">&nbsp;Kompressionsstrümpfe anziehen</td>
	                <td width="25" height="21" align="center" valign="top" style="font-size: 16px; font-weight: bold; border:1px solid #ce6370; background-color: #fff;"><? if($this->treatcare_details['comp_pulloff'] == "1") { echo 'X'; } ?></td>
	                <td width="247" height="23" align="left" valign="top" style="line-height: 2;  color: #ce6370;">&nbsp;Kompressionsstrümpfe ausziehen</td>
	                <td colspan="2" width="268" style="border:1px solid #ce6370; background-color: #fff;">
                		<table>
                			<tr>
                				<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][4]['right_1'] ?></td>
                				<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][4]['right_2'] ?></td>
                				<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][4]['right_3'] ?></td>
                				<td width="68" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][4]['right_4'] ?></td>
                				<td width="64" height="23" align="left" valign="top" style="line-height: 2; ">&nbsp;<? echo $this->treatcare_details['frequency'][4]['right_5'] ?></td>                				
                			</tr>               		
                		</table>
                	</td>
              	</tr>
			</table>
		</td>
	</tr>
	<tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
    			
    			<tr>
    				<td width="55" height="21" align="left" valign="top">&nbsp;</td>
	                <td width="25" height="21" align="center" valign="top" style="font-size: 16px; font-weight: bold; border:1px solid #ce6370; background-color: #fff;"><? if($this->treatcare_details['comp_incr'] == "1") { echo 'X'; } ?></td>
	                <td width="290" height="23" align="left" valign="top" style="line-height: 2;  color: #ce6370;">&nbsp;Kompressionsverbände anlegen</td>
	                <td width="25" height="21" align="center" valign="top" style="font-size: 16px; font-weight: bold; border:1px solid #ce6370; background-color: #fff;"><? if($this->treatcare_details['comp_decr'] == "1") { echo 'X'; } ?></td>
	                <td width="247" height="23" align="left" valign="top" style="line-height: 2;  color: #ce6370;">&nbsp;Kompressionsverbände abnehmen</td>
	                <td colspan="2" width="268" style="border:1px solid #ce6370; background-color: #fff;">
                		<table>
                			<tr>
                				<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][5]['right_1'] ?></td>
                				<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][5]['right_2'] ?></td>
                				<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][5]['right_3'] ?></td>
                				<td width="68" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][5]['right_4'] ?></td>
                				<td width="64" height="23" align="left" valign="top" style="line-height: 2; ">&nbsp;<? echo $this->treatcare_details['frequency'][5]['right_5'] ?></td>                				
                			</tr>               		
                		</table>
                	</td>
              	</tr>
			</table>
		</td>
	</tr>
	<tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
    			<tr>
					<td colspan="6" align="left" valign="top" height="28">&nbsp;</td>
				</tr>
    			<tr>
    				<td width="55" height="23" align="left" valign="top">&nbsp;</td>
	                <td width="25" height="23" align="center" valign="top" style="font-size: 16px; font-weight: bold; border:1px solid #ce6370; background-color: #fff;"><? if($this->treatcare_details['support'] == "1") { echo 'X'; } ?></td>
	                <td width="290" height="23" align="left" valign="top" style="line-height: 2;  color: #ce6370;">&nbsp;Stützende und stabilisierende verbände, Art</td>
	                <td width="265" height="23" align="left" valign="top" style="border-bottom: 1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;<? echo $this->treatcare_details['support_ext'] ?></td>
	                <td width="5" height="23" align="left" valign="top">&nbsp;</td>
	                <td colspan="2" width="268" style="border:1px solid #ce6370; background-color: #fff;">
                		<table>
                			<tr>
                				<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][6]['right_1'] ?></td>
                				<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][6]['right_2'] ?></td>
                				<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][6]['right_3'] ?></td>
                				<td width="68" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][6]['right_4'] ?></td>
                				<td width="64" height="23" align="left" valign="top" style="line-height: 2; ">&nbsp;<? echo $this->treatcare_details['frequency'][6]['right_5'] ?></td>                				
                			</tr>               		
                		</table>
                	</td>
              	</tr>
			</table>
		</td>
	</tr>
	<tr>
    	<td width="100%">
			<table>
				<tr>
					<td width="60" align="left" valign="top" height="23">&nbsp;</td>
					<td width="853" align="left" valign="top" height="23" style="line-height: 2;  color: #ce6370;"><font style=" font-weight: bold;">Wundversorgung und Positionswechsel zur Dekubitusbehandlung</font></td>
				</tr>
			</table>
    	</td>
    </tr>

	<tr>
		<td width="100%">
			<table border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td width="60" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
					<td width="65" height="23" align="left" valign="top" style="line-height: 2;  color: #ce6370;">Wundart</td>
					<td width="515" height="23" align="left" valign="middle" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;<? echo $this->treatcare_details['wound_care_1'] ?></td>
					<td width="5" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
					<td width="268" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
				</tr>
			</table>

		</td>
	</tr>
    <tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td colspan="3" align="left" valign="top" style="line-height: 1;">&nbsp;</td>
				</tr>
				<tr>
					<td width="50" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
					<td width="69" height="23" align="left" valign="top" style="line-height: 2;  color: #ce6370;">&nbsp;Lokalisation</td>
					<td width="120" height="23" align="left" valign="top" style="border-bottom: 1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;<? echo $this->treatcare_details['wound_care_4'] ?></td>
					<td width="5" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
                	<td width="110" height="23" align="left" valign="top" style="line-height: 1.1;  color: #ce6370;">aktuelle Größe (Länge, Breite, Tiefe)</td>
					<td width="120" height="23" align="left" valign="top" style="border-bottom: 1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;<? echo $this->treatcare_details['wound_care_5'] ?></td>
					<td width="5" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
                	<td width="60" height="23" align="left" valign="top" style="line-height: 1.1;  color: #ce6370;">aktueller Grad</td>
					<td width="95" height="23" align="left" valign="top" style="border-bottom: 1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;<? echo $this->treatcare_details['wound_care_6'] ?></td>
                	<td width="5" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
                </tr>
    		</table>
    	</td>
    </tr>
	<tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td colspan="3" align="left" valign="top" style="line-height: 1;">&nbsp;</td>
				</tr>
    			<tr>
    				<td width="55" height="23" align="left" valign="top">&nbsp;</td>
	                <td width="100" height="23" align="left" valign="top" style="line-height: 1.1;  color: #ce6370;">Präparate, Verbandmaterialien</td>
	                <td width="480" height="23" align="left" valign="top" style="border-bottom: 1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;<? echo $this->treatcare_details['wound_care_8'] ?></td>
	                <td width="5" height="23" align="left" valign="top">&nbsp;</td>
	                <td colspan="2" width="268">&nbsp;</td>
              	</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td width="100%">
			<table border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td colspan="3" align="left" valign="top" style="line-height: 1;">&nbsp;</td>
				</tr>
				<tr>
					<td width="60" height="21" align="left" valign="top">&nbsp;</td>
					<td width="25" height="21" align="center" valign="top" style="font-size: 16px; font-weight: bold; border:1px solid #ce6370; background-color: #fff;"><? if($this->treatcare_details['wound_care_10'] == "1") { echo 'X'; } ?></td>
					<td width="290" height="23" align="left" valign="top" style="line-height: 2;  color: #ce6370;">&nbsp;Wundversorgung akut</td>
					<td width="25" height="21" align="center" valign="top" style="font-size: 16px; font-weight: bold; border:1px solid #ce6370; background-color: #fff;"><? if($this->treatcare_details['wound_care_11'] == "1") { echo 'X'; } ?></td>
					<td width="247" height="23" align="left" valign="top" style="line-height: 2;  color: #ce6370;">&nbsp;Wundversorgung chronisch</td>
					<td colspan="2" width="268" style="border:1px solid #ce6370; background-color: #fff;">
						<table>
							<tr>
								<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][7]['right_1'] ?></td>
								<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][7]['right_2'] ?></td>
								<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][7]['right_3'] ?></td>
								<td width="68" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][7]['right_4'] ?></td>
								<td width="64" height="23" align="left" valign="top" style="line-height: 2; ">&nbsp;<? echo $this->treatcare_details['frequency'][7]['right_5'] ?></td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td width="100%">
			<table border="0" cellspacing="0" cellpadding="0">

				<tr>
					<td width="60" height="21" align="left" valign="top">&nbsp;</td>
					<td width="25" height="21" align="center" valign="top" style="font-size: 16px; font-weight: bold; border:1px solid #ce6370; background-color: #fff;"><? if($this->treatcare_details['wound_care_12'] == "1") { echo 'X'; } ?></td>
					<td width="290" height="23" align="left" valign="top" style="line-height: 2;  color: #ce6370;">&nbsp;Positionswechsel zur Dekubitusbehandlung</td>
					<td width="272" height="23" align="left" valign="top" style="line-height: 2;  color: #ce6370;">&nbsp;</td>
					<td colspan="2" width="268" style="border:1px solid #ce6370; background-color: #fff;">
						<table>
							<tr>
								<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][8]['right_1'] ?></td>
								<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][8]['right_2'] ?></td>
								<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][8]['right_3'] ?></td>
								<td width="68" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][8]['right_4'] ?></td>
								<td width="64" height="23" align="left" valign="top" style="line-height: 2; ">&nbsp;<? echo $this->treatcare_details['frequency'][8]['right_5'] ?></td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td>
			<table>
				<tr>
					<td width="60" align="left" valign="top" height="23">&nbsp;</td>
					<td width="580" align="left" valign="top" height="23" style="line-height: 2;  color: #ce6370;"><font style=" font-weight: bold;">Sonstige Maßnahmen der Behandlungspflege</font></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
    			
    			<tr>
    				<td width="55" height="23" align="left" valign="top">&nbsp;</td>
	                <td width="580" height="23" align="left" valign="top" style="border-bottom: 1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;<? echo $this->treatcare_details['wound_care_13'] ?></td>
	                <td width="5" height="23" align="left" valign="top">&nbsp;</td>
	                <td colspan="2" width="268" style="border:1px solid #ce6370; background-color: #fff;">
                		<table>
                			<tr>
                				<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][9]['right_1'] ?></td>
                				<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][9]['right_2'] ?></td>
                				<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][9]['right_3'] ?></td>
                				<td width="68" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][9]['right_4'] ?></td>
                				<td width="64" height="23" align="left" valign="top" style="line-height: 2; ">&nbsp;<? echo $this->treatcare_details['frequency'][9]['right_5'] ?></td>                				
                			</tr>               		
                		</table>
                	</td>
              	</tr>
			</table>
		</td>
	</tr>
    <tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
    			
    			<tr>
    				<td width="55" height="23" align="left" valign="top">&nbsp;</td>
	                <td width="580" height="23" align="left" valign="top" style="border-bottom: 1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;<? echo $this->treatcare_details['wound_care_14'] ?></td>
	                <td width="5" height="23" align="left" valign="top">&nbsp;</td>
	                <td colspan="2" width="268" style="border:1px solid #ce6370; background-color: #fff;">
                		<table>
                			<tr>
                				<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][10]['right_1'] ?></td>
                				<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][10]['right_2'] ?></td>
                				<td width="44" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][10]['right_3'] ?></td>
                				<td width="68" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->treatcare_details['frequency'][10]['right_4'] ?></td>
                				<td width="64" height="23" align="left" valign="top" style="line-height: 2; ">&nbsp;<? echo $this->treatcare_details['frequency'][10]['right_5'] ?></td>                				
                			</tr>               		
                		</table>
                	</td>
              	</tr>
			</table>
		</td>
	</tr>
    <tr>
		<td>
			<table>
				<tr>
					<td width="60" align="left" valign="top" height="23">&nbsp;</td>
					<td width="580" align="left" valign="top" height="23" style="line-height: 2;  color: #ce6370;">Anleitung zur Behandlungspflege <font style=" font-weight: bold;">für Patient/Angehörige (z.B. Injektionen, Wundbehandlung)</font></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
    			
    			<tr>
    				<td width="55" height="23" align="left" valign="top">&nbsp;</td>
	                <td width="580" height="23" align="left" valign="top" style="border-bottom: 1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;<? echo $this->treatcare_details['wound_care_15'] ?></td>
	                <td width="5" height="23" align="left" valign="top">&nbsp;</td>
	                <td width="269" height="23" align="left" valign="top" style="border-bottom: 1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;<span style="color: #ce6370;">Anzahl</span> <? echo $this->treatcare_details['care_number'] ?></td>
              	</tr>
			</table>
		</td>
	</tr>
	<tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
    			<tr>
					<td colspan="3" align="left" valign="top" style="line-height: 1;">&nbsp;</td>
				</tr>
    			<tr>
    				<td width="15" align="left" valign="top" style="font-size: 14px; font-weight: bold; ">&nbsp;</td>
    				<td width="40" align="left" valign="top" style="font-size: 14px; font-weight: bold; background-color: #f38653;">&nbsp;</td>
    				<td width="580" align="left" valign="top" style="font-size: 14px; font-weight: bold; background-color: #f38653; color: #ce6370; line-height: 2;">Grundpflege und hauswirtschaftliche Versorgung</td>
    			</tr>
    		</table>
    	</td>
    </tr>
 	<tr>
		<td align="left" valign="top" style="line-height: 1;">&nbsp;</td>
	</tr>
	<tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
    			
    			<tr>
    				<td width="55" height="23" align="left" valign="top">&nbsp;</td>
	                <td width="25" height="23" align="center" valign="top" style="font-size: 16px; font-weight: bold; border:1px solid #ce6370; background-color: #fff;"><? if($this->basiccare_details['basic_1'] == "1") { echo 'X'; } ?></td>
	                <td width="348" height="23" align="left" valign="top" style="line-height: 2;  color: #ce6370;">&nbsp;Unterstützungspflege nach § 37 (1a) SGB V</td>
	                <td width="208" style="border:1px solid #ce6370; background-color: #fff;">
                		<table>
                			<tr>
                				<td width="102" height="23" align="left" valign="top" style="line-height: 2; border-bottom:1px solid #ce6370; border-right: 1px solid #ce6370; color: #ce6370;">&nbsp;Häufigkeit</td>
                				<td width="106" height="23" align="left" valign="top" style="line-height: 2; color: #ce6370;">&nbsp;Dauer</td>
                			</tr>                		
                		</table>
                	</td>
              	</tr>
			</table>
		</td>
	</tr>
    <tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
    			
    			<tr>
    				<td width="55" height="23" align="left" valign="top">&nbsp;</td>
	                <td width="25" height="23" align="center" valign="top" style="font-size: 16px; font-weight: bold; border:1px solid #ce6370; background-color: #fff;"><? if($this->basiccare_details['basic_2'] == "1") { echo 'X'; } ?></td>
	                <td width="348" height="23" align="left" valign="top" style="line-height: 2;  color: #ce6370;">&nbsp;Krankenhausvermeidungspflege nach § 37 (1a) SGB V</td>
	                <td width="208" style="border:1px solid #ce6370; background-color: #fff;">
                		<table>
                			<tr>
                				<td width="34" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; color: #ce6370;">&nbsp;tgl.</td>
                				<td width="34" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; color: #ce6370;">&nbsp;wtl.</td>
                				<td width="34" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; color: #ce6370;">&nbsp;mtl.</td>
                				<td width="53" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; color: #ce6370;">&nbsp;vom</td>
                				<td width="53" height="23" align="left" valign="top" style="line-height: 2; color: #ce6370;">&nbsp;bis</td>                				
                			</tr>               		
                		</table>
                	</td>
               </tr>
			</table>
		</td>
	</tr>
	<tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
    			
    			<tr>
    				<td width="80" height="23" align="left" valign="top">&nbsp;</td>
	                <td width="25" height="23" align="center" valign="top" style="font-size: 16px; font-weight: bold; border:1px solid #ce6370; background-color: #fff;"><? if($this->basiccare_details['basic_3'] == "1") { echo 'X'; } ?></td>
	                <td width="323" height="23" align="left" valign="top" style="line-height: 2;  color: #ce6370;">&nbsp;Grundpflege</td>
	                <td colspan="2" width="208" style="border:1px solid #ce6370; background-color: #fff;">
                		<table>
                			<tr>
                				<td width="34" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->basiccare_details['frequency'][11]['right_1'] ?></td>
                				<td width="34" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->basiccare_details['frequency'][11]['right_2'] ?></td>
                				<td width="34" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->basiccare_details['frequency'][11]['right_3'] ?></td>
                				<td width="53" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->basiccare_details['frequency'][11]['right_4'] ?></td>
                				<td width="53" height="23" align="left" valign="top" style="line-height: 2; ">&nbsp;<? echo $this->basiccare_details['frequency'][11]['right_5'] ?></td>                				
                			</tr>               		
                		</table>
                	</td>
               </tr>
			</table>
		</td>
	</tr>
	<tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
    			
    			<tr>
    				<td width="80" height="23" align="left" valign="top">&nbsp;</td>
	                <td width="25" height="23" align="center" valign="top" style="font-size: 16px; font-weight: bold; border:1px solid #ce6370; background-color: #fff;"><? if($this->basiccare_details['basic_4'] == "1") { echo 'X'; } ?></td>
	                <td width="323" height="23" align="left" valign="top" style="line-height: 2;  color: #ce6370;">&nbsp;hauswirtschaftliche Versorgung</td>
	                <td width="208" style="border:1px solid #ce6370; background-color: #fff;">
                		<table>
                			<tr>
                				<td width="34" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->basiccare_details['frequency'][12]['right_1'] ?></td>
                				<td width="34" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->basiccare_details['frequency'][12]['right_2'] ?></td>
                				<td width="34" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->basiccare_details['frequency'][12]['right_3'] ?></td>
                				<td width="53" height="23" align="left" valign="top" style="line-height: 2; border-right:1px solid #ce6370; ">&nbsp;<? echo $this->basiccare_details['frequency'][12]['right_4'] ?></td>
                				<td width="53" height="23" align="left" valign="top" style="line-height: 2; ">&nbsp;<? echo $this->basiccare_details['frequency'][12]['right_5'] ?></td>                				
                			</tr>               		
                		</table>
                	</td>
                	<td width="5" height="23" align="left" valign="top">&nbsp;</td>
                	<td width="269" rowspan="6">
                		<table>
                			<tr>
                				<td width="269" align="left" valign="top" style="line-height: 1.5;">&nbsp;</td>
                			</tr>
                			<tr>
                				<td width="260"  style="line-height: 1; border:1px solid #ce6370;">
	                				<table>
	                					<tr>
	                						<td width="260" align="left" valign="top">&nbsp;</td>
	                					</tr>
	                					<tr>
	                						<td width="260" height="111" align="center"><?php echo $this->stamp_block; ?></td>
	                					</tr>
	                				</table>
                				</td>
                			</tr>
                		</table>
                	</td>
                	
               </tr>
               <tr>
               		<td width="55" align="left" valign="top" height="23">&nbsp;</td>
					<td colspan="4" width="580" align="left" valign="top" height="23" style="line-height: 2;  color: #ce6370;"><font style=" font-weight: bold;">&nbsp;</font></td>
			   </tr>
               <?php
               	if($this->basiccare_details['basic_textarea'] != "")
					{
						$textlines = explode("<br />", nl2br($this->basiccare_details['basic_textarea']));

						if(count($textlines) == 1)
						{ ?>
					<tr>
						<td width="55" align="left" valign="top" height="23">&nbsp;</td>
						<td colspan="4" width="100" align="left" valign="top" height="23" style="line-height: 2;  color: #ce6370;"><font style=" font-weight: bold;">Weitere Hinweise</font></td>
						<td colspan="4" width="481" height="23" align="left" valign="middle" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;<? echo $textlines[0]; ?></td>
					</tr>
					<?php
						for($nrl=1; $nrl<=3; $nrl++)
														{ ?>
						<tr>
							<td width="55" align="left" valign="top" height="23">&nbsp;</td>
							<td colspan="4" width="581" height="23" align="left" valign="top" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;</td>
						</tr>
                <?php } } elseif(count($textlines) == 2) { ?>
                	<tr>
                		<td width="55" align="left" valign="top" height="23">&nbsp;</td>
						<td colspan="4" width="100" align="left" valign="top" height="23" style="line-height: 2;  color: #ce6370;"><font style=" font-weight: bold;">Weitere Hinweise</font></td>
	                	<td colspan="4" width="481" height="23" align="left" valign="middle" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;<? echo $textlines[0]; ?></td>
	                </tr>
	                <tr>
	                	<td width="55" align="left" valign="top" height="23">&nbsp;</td>
	                	<td colspan="4" width="581" height="23" align="left" valign="middle" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;"><? echo $textlines[1]; ?></td>
					</tr>
					<tr>
						<td width="55" align="left" valign="top" height="23">&nbsp;</td>								                
	                	<td colspan="4" width="581" height="23" align="left" valign="middle" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;</td>
	                </tr>
	                <tr>
	                	<td width="55" align="left" valign="top" height="23">&nbsp;</td>								                
	                	<td colspan="4" width="581" height="23" align="left" valign="middle" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;</td>
	                </tr>
	            <?php } elseif(count($textlines) == 3) { ?>
	            	<tr>
	            		<td width="55" align="left" valign="top" height="23">&nbsp;</td>
						<td colspan="4" width="100" align="left" valign="top" height="23" style="line-height: 2;  color: #ce6370;"><font style=" font-weight: bold;">Weitere Hinweise</font></td>
	                	<td colspan="4" width="481" height="23" align="left" valign="middle" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;<? echo $textlines[0]; ?></td>
	                </tr>
	                <tr>
	                	<td width="55" align="left" valign="top" height="23">&nbsp;</td>
	                	<td colspan="4" width="581" height="23" align="left" valign="middle" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;"><? echo $textlines[1]; ?></td>
					</tr>
					<tr>
						<td width="55" align="left" valign="top" height="23">&nbsp;</td>								                
	                	<td colspan="4" width="581" height="23" align="left" valign="middle" style="border-bottom:1px solid #ce6370; background-color: #fff;"><? echo $textlines[2]; ?></td>
	                </tr>
	                <tr>
	                	<td width="55" align="left" valign="top" height="23">&nbsp;</td>								                
	                	<td colspan="4" width="581" height="23" align="left" valign="middle" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;</td>
	                </tr>
	                 <?php } elseif(count($textlines) >= 4) { ?>
	            	<tr>
	            		<td width="55" align="left" valign="top" height="23">&nbsp;</td>
						<td colspan="4" width="100" align="left" valign="top" height="23" style="line-height: 2;  color: #ce6370;"><font style=" font-weight: bold;">Weitere Hinweise</font></td>
	                	<td colspan="4" width="481" height="23" align="left" valign="middle" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;<? echo $textlines[0]; ?></td>
	                </tr>
	                <tr>
	                	<td width="55" align="left" valign="top" height="23">&nbsp;</td>
	                	<td colspan="4" width="581" height="23" align="left" valign="middle" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;"><? echo $textlines[1]; ?></td>
					</tr>
					<tr>
						<td width="55" align="left" valign="top" height="23">&nbsp;</td>								                
	                	<td colspan="4" width="581" height="23" align="left" valign="middle" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;"><? echo $textlines[2]; ?></td>
	                </tr>
	                <tr>
	                	<td width="55" align="left" valign="top" height="23">&nbsp;</td>								                
	                	<td colspan="4" width="581" height="23" align="left" valign="middle" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;"><? echo $textlines[3]; ?></td>
	                </tr>
	           <?php } } else { ?>
	           		<tr>
	           			<td width="55" align="left" valign="top" height="23">&nbsp;</td>
						<td colspan="4" width="100" align="left" valign="top" height="23" style="line-height: 2;  color: #ce6370;"><font style=" font-weight: bold;">Weitere Hinweise</font></td>
	                	<td colspan="4" width="481" height="23" align="left" valign="middle" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;</td>
	                </tr>
	                <tr>
	                	<td width="55" align="left" valign="top" height="23">&nbsp;</td>
	                	<td colspan="4" width="581" height="23" align="left" valign="middle" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;</td>
					</tr>
					<tr>
						<td width="55" align="left" valign="top" height="23">&nbsp;</td>								                
	                	<td colspan="4" width="581" height="23" align="left" valign="middle" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;</td>
	                </tr>
	                <tr>
	                	<td width="55" align="left" valign="top" height="23">&nbsp;</td>								                
	                	<td colspan="4" width="581" height="23" align="left" valign="middle" style="border-bottom:1px solid #ce6370; background-color: #fff; line-height: 2;">&nbsp;</td>
	                </tr>
	           <?php } ?>
	           <tr>
               		<td colspan="5" width="5" align="left" valign="top" style="line-height: 0.5;">&nbsp;</td>
			   </tr>
	           <tr>
               		<td width="55" align="left" valign="top" height="23">&nbsp;</td>
					<td colspan="4" width="240" align="left" valign="top" height="23" style="line-height: 2;  color: #ce6370; border: 1px solid #ce6370;"><font style=" font-weight: bold;">Ausfertigung für die Krankenkasse</font></td>
			   </tr>
			</table>
		</td>
	</tr>
	<tr>
		<td width="55" align="left" valign="top" height="55">&nbsp;</td>
	</tr>
</table>
