<!-- Dragos:: ISPC-2777 25.01.2021 -->
<table width="935" border="0" cellspacing="0" cellpadding="0" style="font-family:Arial, Helvetica, sans-serif; font-size:11px;">
	<tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
    			<tr>
                   <td width="935" align="left" valign="top" style="line-height: 1.5;">&nbsp;</td>
                </tr>
      			<tr>
      				<td width="7">&nbsp;</td>
        			<td width="360" align="left" valign="top">
	        			<table width="350" cellspacing="0" cellpadding="0" style="">
	        				<tr>
                               <td width="350" align="left" valign="top" style="font-size: 6px; font-weight: bold; line-height: 0.6;">&nbsp;</td>
                           	</tr>
	          				<tr>
                               <td  width="350" align="left" valign="top" style="">
	            					<table width="100%" border="0" cellspacing="0" cellpadding="0">
	            						<tr>
                							<td  width="350" align="left" valign="top" style="line-height: 1.5;">&nbsp;</td>
              							</tr>
              							<tr>
                							<td  width="340" align="left" valign="top" style="line-height: 2; font-size:12px;"><? echo $this->kvheader_details['phealthinsurance_name'] ?></td>
              							</tr>
	          						</table>
	          					</td>
          					</tr> 
          					<tr>
          						<td align="left" valign="top"  style="">
          							<table width="350" border="0" cellspacing="0" cellpadding="0">
              							<tr>
                							<td colspan="2" width="350" align="left" valign="top" style="line-height: 1;">&nbsp;</td>
              							</tr>
              							<tr>
                							<td colspan="2" width="350" align="left" valign="top" style="line-height: 0.5;">&nbsp;</td>
              							</tr>
                						<tr>                							
                							<td width="225" style="font-size:12px;"><? echo nl2br($this->kvheader_details['insured_name_firstname']); ?></td>
                							<td align="left" valign="top">
                								<table width="160" border="0" cellspacing="0" cellpadding="0">
                  									<tr>
                    									<td align="left" valign="top" colspan="2" style="line-height: 3;">&nbsp;</td>
                  									</tr>
                  									<tr>
                    									<td width="40" height="21" align="left" valign="top">&nbsp;</td>
                    									<td height="21" align="left" valign="top" colspan="2"  style="font-size:12px;"><? echo $this->kvheader_details['born_on'] ?></td>
                  									</tr>
                   									<tr>
                    									<td height="21" colspan="2">&nbsp;</td>
                  									</tr>
                								</table>
                							</td>                							
              							</tr>
              						</table>
              					</td>
              				</tr>
              				<tr>
           						<td align="left" valign="top"  style="">
           							<table width="350" border="0" cellspacing="0" cellpadding="0">
           								<tr>
                							<td colspan="5" width="350" align="left" valign="top" style="line-height: 0.25;">&nbsp;</td>
              							</tr>
              							<tr>
							                
							                <td width="120" align="left" valign="top" style="line-height: 1.28;">&nbsp;</td>
							                <td width="5" align="left" valign="top" style="line-height: 1.28;">&nbsp;</td>
							                <td width="145" align="left" valign="top" style="line-height: 1.28;">&nbsp;</td>
							                <td width="5" align="left" valign="top" style="line-height: 1.28;">&nbsp;</td>
							                <td width="75" align="left" valign="top" style="line-height: 1.28;">&nbsp;</td>
						              	</tr>
						              	<tr>
                							<td colspan="5" width="350" align="left" valign="top" style="line-height: 0.25;">&nbsp;</td>
              							</tr>
						              	<tr>
							                
							                <td width="120" align="left" valign="top" style="line-height: 1.25; font-size:12px;"><? echo $this->kvheader_details['health_insurance_nr'] ?></td>
							                <td width="5" align="left" valign="top" style="color: #ce6370; line-height: 1.25;">&nbsp;</td>
							                <td width="145" align="left" valign="top" style="line-height: 1.25; font-size:12px;"><? echo $this->kvheader_details['health_insurance_patient_number'] ?></td>
							                <td width="5" align="left" valign="top" style="color: #ce6370; line-height: 1.25;">&nbsp;</td>
							                <td width="75" align="left" valign="top" style="line-height: 1.25;font-size:12px;"><? echo $this->kvheader_details['health_insurance_patient_status'] ?></td>
						              	</tr>
            						</table>
            					</td>
          					</tr>
          					<tr>
            					<td align="left" valign="top"  style="">
           							<table width="350" border="0" cellspacing="0" cellpadding="0">
           								<tr>
                							<td colspan="5" width="370" align="left" valign="top" style="line-height: 0.25;">&nbsp;</td>
              							</tr>
              							<tr>
							               
							                <td width="120" align="left" valign="top" style="line-height: 1.5;">&nbsp;</td>
							                <td width="5" align="left" valign="top" style="line-height: 1.5;">&nbsp;</td>
							                <td width="125" align="left" valign="top" style="line-height: 1.5;">&nbsp;</td>
							                <td width="5" align="left" valign="top" style="line-height: 1.5;">&nbsp;</td>
							                <td width="90" align="left" valign="top" style="line-height: 1.5;">&nbsp;</td>
						              	</tr>
						              	<tr>
                							<td colspan="6" width="350" align="left" valign="top" style="line-height: 0.25;">&nbsp;</td>
              							</tr>
              							<tr>
							               
							                <td width="120" align="left" valign="top" style="line-height: 1.5; font-size:12px;"><? echo $this->kvheader_details['stamp_user_bsnr'] ?></td>
							                <td width="5" align="left" valign="top" style="color: #ce6370; line-height: 1.5;">&nbsp;</td>
							                <td width="125" align="left" valign="top" style="line-height: 1.5; font-size:12px;"><? echo $this->kvheader_details['stamp_user_lanr'] ?></td>
							                <td width="5" align="left" valign="top" style="color: #ce6370; line-height: 1.5;">&nbsp;</td>
							                <td width="90" align="left" valign="top" style="line-height: 1.5; font-size:12px;"><? echo $this->kvheader_details['formular_date'] ?></td>
						              	</tr>
           							</table>
            					</td>
          					</tr>              							   
          				</table>	
          			</td>
          			<td width="25">&nbsp;</td>
          			<td width="524" align="left" valign="top">
	        			<table width="534" cellspacing="0" cellpadding="0">
	        				<tr>
                				<td colspan="3" width="534" align="left" valign="bottom" style="line-height: 0.25;">&nbsp;</td>
              				</tr>
	        				<tr>
	        				 	<td width="5" align="left" valign="top">&nbsp;</td>
                				<td width="472" align="left" valign="top" style="font-size: 18px; font-weight: bold; line-height: 1.15;">&nbsp;</td>
                				<td width="40" align="right" valign="top" style="font-size: 18px; font-weight: bold; line-height: 1.15;">&nbsp;</td>
              				</tr>
	          				<tr>
           						<td width="534" colspan="2" align="left" valign="top">
           							<table width="534" border="0" cellspacing="0" cellpadding="0">
           								<tr>
                							<td colspan="7" width="534" align="left" valign="bottom" style="line-height: 0.8;">&nbsp;</td>
              							</tr>
           								<tr>
                							<td colspan="7" width="534" align="left" valign="bottom" style="line-height: 1.75;">&nbsp;</td>
              							</tr>
						              	<tr>
							                <td width="113" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->topform_details['icdnumber1'] ?></td>
							                <td width="8" height="23" align="left" valign="top">&nbsp;</td>
							                <td width="113" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->topform_details['icdnumber2'] ?></td>
							                <td width="8" height="23" align="left" valign="top">&nbsp;</td>
							                <td width="113" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->topform_details['icdnumber3'] ?></td>
							                <td width="8" height="23" align="left" valign="top">&nbsp;</td>
							                <td width="113" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->topform_details['icdnumber4'] ?></td>
						              	</tr>
            						</table>
            					</td>
          					</tr>
          					<tr>
           						<td align="left" valign="top">
           							<table width="534" border="0" cellspacing="0" cellpadding="0">
           								<tr>
                							<td width="534" align="left" valign="bottom" style="line-height: 1;">&nbsp;</td>
              							</tr>
           								<tr>
                							<td width="534" align="left" valign="bottom" style="line-height: 1.25;">&nbsp;</td>
              							</tr>
              							<tr>
                							<td width="534" align="left" valign="bottom" style="line-height: 1.5;">&nbsp;</td>
              							</tr>
						              	<tr>
                							<td width="534" align="left" valign="bottom" style="line-height: 1.5;">&nbsp;</td>
              							</tr>
							                <?php
							                	if($this->topform_details['topform_textarea'] != "")
												{
							                		$textlines = explode("<br />", nl2br($this->topform_details['topform_textarea']));
													if(count($textlines) == 1)
													{ ?>
													<tr>
														<td width="512" height="23" align="left" valign="middle" style="line-height: 2.5;">&nbsp;<? echo $textlines[0]; ?></td>
													</tr>
													<?php
														for($nrl=1; $nrl<=2; $nrl++)
														{ ?>
														<tr>
															<td width="512" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
														</tr>
								                <?php } } elseif(count($textlines) == 2) { ?>
								                	<tr>
									                	<td width="512" height="23" align="left" valign="middle" style="line-height: 2;">&nbsp;&nbsp;<? echo $textlines[0]; ?></td>
									                </tr>
									                <tr>
									                	<td width="512" height="23" align="left" valign="middle" style="line-height: 2.75;">&nbsp;<? echo $textlines[1]; ?></td>
													</tr>
													<tr>								                
									                	<td width="512" height="23" align="left" valign="middle" style="line-height: 2.5;">&nbsp;</td>
									                </tr>
									            <?php } else { ?>
									            	<tr>
									                	<td width="512" height="23" align="left" valign="middle" style="line-height: 2;">&nbsp;&nbsp;<? echo $textlines[0]; ?></td>
									                </tr>
									                <tr>
									                	<td width="512" height="23" align="left" valign="middle" style="line-height: 2.75;">&nbsp;<? echo $textlines[1]; ?></td>
													</tr>
													<tr>								                
									                	<td width="512" height="23" align="left" valign="middle" style="line-height: 2.5;">&nbsp;<? echo $textlines[2]; ?></td>
									                </tr>
									           <?php } } else { ?>
									           		<tr>
									                	<td width="512" height="23" align="left" valign="middle" style="line-height: 2;">&nbsp;</td>
									                </tr>
									                <tr>
									                	<td width="512" height="23" align="left" valign="middle" style="line-height: 2.75;">&nbsp;</td>
													</tr>
													<tr>								                
									                	<td width="512" height="23" align="left" valign="middle" style="line-height: 2.5;">&nbsp;</td>
									                </tr>
									           <?php } ?>
            						</table>
            					</td>
          					</tr>          					
	          			</table>          				
          			</td>
				</tr>   				
			</table>
		</td>
	</tr>
	<tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
    			<tr>
					<td colspan="3" align="left" valign="top" style="line-height: 1;">&nbsp;</td>
				</tr>
    			<tr>
    				<td width="350">
    					<table border="0" cellspacing="0" cellpadding="0">
	    					<tr>
			    				<td width="8" align="left" valign="top" style="font-size: 16px; font-weight: bold; ">&nbsp;</td>
				                <td width="25" align="center" valign="top" style="font-size: 16px; font-weight: bold;"><? if($this->topform_details['reg_type_0'] == "1") { echo 'X'; } ?></td>
				                <td width="102" align="left" valign="top" style="line-height: 1.1;  color: #ce6370;">&nbsp;</td>
				                <td width="25" align="center" valign="top" style="font-size: 16px; font-weight: bold;"><? if($this->topform_details['reg_type_1'] == "1") { echo 'X'; } ?></td>
				                <td width="112" align="left" valign="top" style="line-height: 1.1;  color: #ce6370;">&nbsp;</td>
				                <td width="25" align="center" valign="top" style="font-size: 16px; font-weight: bold;"><? if($this->topform_details['reg_type_2'] == "1") { echo 'X'; } ?></td>
				                <td width="60" align="left" valign="top" style="line-height: 2.2;  color: #ce6370;">&nbsp;</td>
			                </tr>
			            </table>
	                </td>
	                <td width="48" align="left" valign="top" style="line-height: 1;">&nbsp;</td>
	                <td width="550">
	                	<table border="0" cellspacing="0" cellpadding="0">
		    				<tr>
		    					<td width="35" height="29" align="center" valign="top" style="line-height: 2.2;">&nbsp;</td>
			                	<td width="23" height="29" align="center" valign="top" style="font-size: 16px; line-height: 1.5;"><? echo $this->topform_details['from'][0] ?></td>
			                	<td width="23" height="29" align="center" valign="top" style="font-size: 16px; line-height: 1.5;"><? echo $this->topform_details['from'][1] ?></td>
			                	<td width="23" height="29" align="center" valign="top" style="font-size: 16px; line-height: 1.5;"><? echo $this->topform_details['from'][2] ?></td>
			                	<td width="23" height="29" align="center" valign="top" style="font-size: 16px; line-height: 1.5;"><? echo $this->topform_details['from'][3] ?></td>
			                	<td width="23" height="29" align="center" valign="top" style="font-size: 16px; line-height: 1.5;"><? echo $this->topform_details['from'][4] ?></td>
			                	<td width="23" height="29" align="center" valign="top" style="font-size: 16px; line-height: 1.5;"><? echo $this->topform_details['from'][5] ?></td>
			                	
				               	<td width="47" height="29" align="center" valign="top" style="line-height: 2.2;">&nbsp;</td>
					            <td width="23" height="29" align="center" valign="top" style="font-size: 16px; line-height: 1.5;"><? echo $this->topform_details['to'][0] ?></td>
			                	<td width="23" height="29" align="center" valign="top" style="font-size: 16px; line-height: 1.5;"><? echo $this->topform_details['to'][1] ?></td>
			                	<td width="23" height="29" align="center" valign="top" style="font-size: 16px; line-height: 1.5;"><? echo $this->topform_details['to'][2] ?></td>
			                	<td width="23" height="29" align="center" valign="top" style="font-size: 16px; line-height: 1.5;"><? echo $this->topform_details['to'][3] ?></td>
			                	<td width="23" height="29" align="center" valign="top" style="font-size: 16px; line-height: 1.5;"><? echo $this->topform_details['to'][4] ?></td>
			                	<td width="23" height="29" align="center" valign="top" style="font-size: 16px; line-height: 1.5;"><? echo $this->topform_details['to'][5] ?></td>
				           </tr>
			          	</table>
			     	</td>
              	</tr>
    		</table>
    	</td>
    </tr>
    <tr>
		<td lign="left" valign="top" style="line-height: 0.5;">&nbsp;</td>
	</tr>
    <tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
    			<tr>
					<td width="15" align="left" valign="top" style="font-size: 14px; font-weight: bold;">&nbsp;</td>
					<td width="40" align="left" valign="top" style="font-size: 14px; font-weight: bold;">&nbsp;</td>
					<td width="580" align="left" valign="top" style="font-size: 14px; font-weight: bold; line-height: 2;">&nbsp;</td>
					<td width="35" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
					<td width="215" rowspan="3" style="border-bottom: none; ">
						<table>
							<tr>
								<td lign="left" valign="top" style="line-height: 0.5;">&nbsp;</td>
							</tr>
							<tr>
								<td colspan="2" width="268" height="23" align="left" valign="top" style="">&nbsp;</td>
							</tr>
							<tr>
								<td lign="left" valign="top" style="line-height: 1.5;">&nbsp;</td>
							</tr>
							<tr>
								<td width="103" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
								<td width="112" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td lign="left" valign="top" style="line-height: 1;">&nbsp;</td>
				</tr>
				<tr>
					<td width="60" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
					<td width="215" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
                	<td width="385" height="23" align="left" valign="middle" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['prep_med_0'] ?></td>
                	<td width="5" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>

                </tr>
				<tr>
					<td width="60" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
                	<td colspan="4" height="23"  width="600"align="left" valign="middle" style="line-height: 2.5;">&nbsp;<? echo $this->treatcare_details['prep_med_1'] ?></td>
                	<td width="10" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
                	<td colspan="2" width="215" style="">
                		<table>
                			<tr>
                				<td width="28" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
                				<td width="34" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
                				<td width="35" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
                				<td width="58" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
                				<td width="57" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
                			</tr>               		
                		</table>
                	</td>
                </tr>
    		</table>
    	</td>
    </tr>
    <tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
    			<tr>
					<td style="line-height: 0.5">&nbsp;</td>
				</tr>
    			<tr>
    				<td width="60" height="21" align="left" valign="top">&nbsp;</td>
    				<td width="25" align="center" valign="top" style="font-size: 16px; font-weight: bold;"><? if($this->treatcare_details['med_box'] == "1") { echo 'X'; } ?></td>
				    <td width="575" align="left" valign="top" style="line-height: 2;  color: #ce6370;">&nbsp;</td>
				    <td width="10" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
	                <td colspan="2" width="215" style="">
                		<table>
                			<tr>
                				<td width="28" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][0]['right_1'] ?></td>
                				<td width="34" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][0]['right_2'] ?></td>
                				<td width="35" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][0]['right_3'] ?></td>
                				<td width="58" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][0]['right_4'] ?></td>
                				<td width="57" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][0]['right_5'] ?></td>
                			</tr>               		
                		</table>
                	</td>
              	</tr>
			</table>
		</td>
	</tr>
	<tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td style="line-height: 0.5">&nbsp;</td>
				</tr>
    			<tr>
    				<td width="60" height="21" align="left" valign="top">&nbsp;</td>
    				<td width="25" align="center" valign="top" style="font-size: 16px; font-weight: bold;"><? if($this->treatcare_details['prep_med_4'] == "1") { echo 'X'; } ?></td>
				    <td width="575" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
				    <td width="10" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
	                <td colspan="2" width="215" style="">
                		<table>
                			<tr>
                				<td width="28" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][1]['right_1'] ?></td>
                				<td width="34" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][1]['right_2'] ?></td>
                				<td width="35" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][1]['right_3'] ?></td>
                				<td width="58" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][1]['right_4'] ?></td>
                				<td width="57" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][1]['right_5'] ?></td>
                			</tr>               		
                		</table>
                	</td>
              	</tr>
			</table>
		</td>
	</tr>
	
	<tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td style="line-height: 0.6">&nbsp;</td>
				</tr>
    			<tr>
    				<td width="60" height="23" align="left" valign="top">&nbsp;</td>
    				<td width="25" height="23" align="center" valign="top" style="font-size: 16px; font-weight: bold;"><? if($this->treatcare_details['inject'] == "1") { echo 'X'; } ?></td>
    				<td width="170" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
    				<td width="25" height="23" align="center" valign="top" style="font-size: 16px; font-weight: bold;"><? if($this->treatcare_details['made'] == "1") { echo 'X'; } ?></td>
    				<td width="115" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
    				<td width="25" height="23" align="center" valign="top" style="font-size: 16px; font-weight: bold;"><? if($this->treatcare_details['intram'] == "1") { echo 'X'; } ?></td>
    				<td width="146" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
	                <td width="25" height="23" align="center" valign="top" style="font-size: 16px; font-weight: bold;"><? if($this->treatcare_details['subcut'] == "1") { echo 'X'; } ?></td>
	                <td width="80" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
	                <td colspan="2" width="215" style="">
                		<table>
                			<tr>
                				<td width="28" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][2]['right_1'] ?></td>
                				<td width="34" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][2]['right_2'] ?></td>
                				<td width="35" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][2]['right_3'] ?></td>
                				<td width="58" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][2]['right_4'] ?></td>
                				<td width="57" height="23" align="left" valign="top" style="line-height: 2; ">&nbsp;<? echo $this->treatcare_details['frequency'][2]['right_5'] ?></td>
                			</tr>
                		</table>
                	</td>
              	</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td>
			<table>
				<tr>
					<td width="60" align="left" valign="top" height="23">&nbsp;</td>
					<td width="215" align="left" valign="top" height="23" style="line-height: 2;"><font style=" font-weight: bold;">&nbsp;</font></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td style="line-height: 0.75">&nbsp;</td>
				</tr>
    			<tr>
    				<td width="60" height="21" align="left" valign="top">&nbsp;</td>
	                <td width="25" height="21" align="center" valign="top" style="font-size: 16px; font-weight: bold;"><? if($this->treatcare_details['first_new_appoint'] == "1") { echo 'X'; } ?></td>
	                <td width="310" height="23" align="left" valign="top" style="line-height: 1.1;">&nbsp;</td>
	                <td width="25" height="21" align="center" valign="top" style="font-size: 16px; font-weight: bold;"><? if($this->treatcare_details['intens_insulint'] == "1") { echo 'X'; } ?></td>
	                <td width="250" height="23" align="left" valign="top" style="line-height: 2;  color: #ce6370;">&nbsp;</td>
	                <td colspan="2" width="215" style="">
                		<table>
                			<tr>
                				<td width="28" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][3]['right_1'] ?></td>
                				<td width="34" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][3]['right_2'] ?></td>
                				<td width="35" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][3]['right_3'] ?></td>
                				<td width="58" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][3]['right_4'] ?></td>
                				<td width="57" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][3]['right_5'] ?></td>
                			</tr>               		
                		</table>
                	</td>
              	</tr>
			</table>
		</td>
	</tr>
	<tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
    			<tr>
					<td colspan="4" align="left" valign="top" style="line-height: 1.5;">&nbsp;</td>
				</tr>
    			<tr>
    				<td width="60" height="21" align="left" valign="top">&nbsp;</td>
    				<td width="335" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
	                <td width="25" height="21" align="center" valign="top" style="font-size: 16px; font-weight: bold;"><? if($this->treatcare_details['right_side'] == "1") { echo 'X'; } ?></td>
	                <td width="67" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
	                <td width="25" height="21" align="center" valign="top" style="font-size: 16px; font-weight: bold;"><? if($this->treatcare_details['left_side'] == "1") { echo 'X'; } ?></td>
	               	<td width="57" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
	                <td width="25" height="21" align="center" valign="top" style="font-size: 16px; font-weight: bold;"><? if($this->treatcare_details['both_sides'] == "1") { echo 'X'; } ?></td>
	                <td width="67" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
              	</tr>
			</table>
		</td>
	</tr>
	<tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td colspan="4" align="left" valign="top" style="line-height: 0.6;">&nbsp;</td>
				</tr>
    			<tr>
    				<td width="60" height="21" align="left" valign="top">&nbsp;</td>
	                <td width="25" height="21" align="center" valign="top" style="font-size: 16px; font-weight: bold;"><? if($this->treatcare_details['comp_attract'] == "1") { echo 'X'; } ?></td>
	                <td width="310" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
	                <td width="25" height="21" align="center" valign="top" style="font-size: 16px; font-weight: bold;"><? if($this->treatcare_details['comp_pulloff'] == "1") { echo 'X'; } ?></td>
	                <td width="250" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
	                <td colspan="2" width="215" style="">
                		<table>
                			<tr>
                				<td width="28" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][4]['right_1'] ?></td>
                				<td width="34" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][4]['right_2'] ?></td>
                				<td width="35" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][4]['right_3'] ?></td>
                				<td width="58" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][4]['right_4'] ?></td>
                				<td width="57" height="23" align="left" valign="top" style="line-height: 2; ">&nbsp;<? echo $this->treatcare_details['frequency'][4]['right_5'] ?></td>
                			</tr>               		
                		</table>
                	</td>
              	</tr>
			</table>
		</td>
	</tr>
	<tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td colspan="4" align="left" valign="top" style="line-height: 0.6;">&nbsp;</td>
				</tr>
    			<tr>
    				<td width="60" height="21" align="left" valign="top">&nbsp;</td>
	                <td width="25" height="21" align="center" valign="top" style="font-size: 16px; font-weight: bold;"><? if($this->treatcare_details['comp_incr'] == "1") { echo 'X'; } ?></td>
	                <td width="310" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
	                <td width="25" height="21" align="center" valign="top" style="font-size: 16px; font-weight: bold;"><? if($this->treatcare_details['comp_decr'] == "1") { echo 'X'; } ?></td>
	                <td width="250" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
	                <td colspan="2" width="215" style="">
                		<table>
                			<tr>
                				<td width="28" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][5]['right_1'] ?></td>
                				<td width="34" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][5]['right_2'] ?></td>
                				<td width="35" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][5]['right_3'] ?></td>
                				<td width="58" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][5]['right_4'] ?></td>
                				<td width="57" height="23" align="left" valign="top" style="line-height: 2; ">&nbsp;<? echo $this->treatcare_details['frequency'][5]['right_5'] ?></td>
                			</tr>               		
                		</table>
                	</td>
              	</tr>
			</table>
		</td>
	</tr>
	<tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
    			<tr>
					<td colspan="6" align="left" valign="top" style="line-height: 1.5">&nbsp;</td>
				</tr>
    			<tr>
    				<td width="60" height="23" align="left" valign="top">&nbsp;</td>
	                <td width="25" height="23" align="center" valign="top" style="font-size: 16px; font-weight: bold;"><? if($this->treatcare_details['support'] == "1") { echo 'X'; } ?></td>
	                <td width="310" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
	                <td width="265" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['support_ext'] ?></td>
	                <td width="10" height="23" align="left" valign="top">&nbsp;</td>
	                <td colspan="2" width="215" style="">
                		<table>
                			<tr>
                				<td width="28" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][6]['right_1'] ?></td>
                				<td width="34" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][6]['right_2'] ?></td>
                				<td width="35" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][6]['right_3'] ?></td>
                				<td width="58" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][6]['right_4'] ?></td>
                				<td width="57" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][6]['right_5'] ?></td>
                			</tr>               		
                		</table>
                	</td>
              	</tr>
			</table>
		</td>
	</tr>
	<tr>
    	<td width="100%">
			<table>
				<tr>
					<td width="60" align="left" valign="top" height="23">&nbsp;</td>
					<td width="853" align="left" valign="top" height="23" style="line-height: 3;  color: #ce6370;">&nbsp;</td>
				</tr>
			</table>
    	</td>
    </tr>

	<tr>
		<td width="100%">
			<table border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td width="60" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
					<td width="85" height="23" align="left" valign="top" style="line-height: 2;  color: #ce6370;">&nbsp;</td>
					<td width="515" height="23" align="left" valign="middle" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['wound_care_1'] ?></td>
					<td width="5" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
					<td width="268" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
				</tr>
			</table>

		</td>
	</tr>
    <tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td colspan="3" align="left" valign="top" style="line-height: 1.5;">&nbsp;</td>
				</tr>
				<tr>
					<td width="55" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
					<td width="85" height="23" align="left" valign="top" style="line-height: 2;  color: #ce6370;">&nbsp;</td>
					<td width="125" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['wound_care_4'] ?></td>
					<td width="5" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
                	<td width="120" height="23" align="left" valign="top" style="line-height: 1.1;  color: #ce6370;">&nbsp;</td>
					<td width="125" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['wound_care_5'] ?></td>
					<td width="5" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
                	<td width="75" height="23" align="left" valign="top" style="line-height: 1.1;  color: #ce6370;">&nbsp;</td>
					<td width="65" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['wound_care_6'] ?></td>
                	<td width="5" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
                </tr>
    		</table>
    	</td>
    </tr>
	<tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td colspan="3" align="left" valign="top" style="line-height: 1.25;">&nbsp;</td>
				</tr>
    			<tr>
    				<td width="60" height="23" align="left" valign="top">&nbsp;</td>
	                <td width="135" height="23" align="left" valign="top" style="line-height: 1.1;  color: #ce6370;">&nbsp;</td>
	                <td width="465" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['wound_care_8'] ?></td>
	                <td width="5" height="23" align="left" valign="top">&nbsp;</td>
	                <td colspan="2" width="268">&nbsp;</td>
              	</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td width="100%">
			<table border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td colspan="3" align="left" valign="top" style="line-height: 1.3;">&nbsp;</td>
				</tr>
				<tr>
					<td width="65" height="21" align="left" valign="top">&nbsp;</td>
					<td width="25" height="21" align="center" valign="top" style="font-size: 16px; font-weight: bold;"><? if($this->treatcare_details['wound_care_10'] == "1") { echo 'X'; } ?></td>
					<td width="310" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
					<td width="25" height="21" align="center" valign="top" style="font-size: 16px; font-weight: bold;"><? if($this->treatcare_details['wound_care_11'] == "1") { echo 'X'; } ?></td>
					<td width="245" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
					<td width="10" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
					<td colspan="2" width="215" style="">
						<table>
							<tr>
								<td width="33" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][7]['right_1'] ?></td>
								<td width="34" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][7]['right_2'] ?></td>
								<td width="35" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][7]['right_3'] ?></td>
								<td width="58" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][7]['right_4'] ?></td>
								<td width="57" height="23" align="left" valign="top" style="line-height: 2; ">&nbsp;<? echo $this->treatcare_details['frequency'][7]['right_5'] ?></td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td width="100%">
			<table border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td colspan="3" align="left" valign="top" style="line-height: 0.75;">&nbsp;</td>
				</tr>
				<tr>
					<td width="65" height="21" align="left" valign="top">&nbsp;</td>
					<td width="25" height="21" align="center" valign="top" style="font-size: 16px; font-weight: bold;"><? if($this->treatcare_details['wound_care_12'] == "1") { echo 'X'; } ?></td>
					<td width="310" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
					<td width="270" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
					<td width="10" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
					<td colspan="2" width="215" style="">
						<table>
							<tr>
								<td width="33" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][8]['right_1'] ?></td>
								<td width="34" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][8]['right_2'] ?></td>
								<td width="35" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][8]['right_3'] ?></td>
								<td width="58" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][8]['right_4'] ?></td>
								<td width="57" height="23" align="left" valign="top" style="line-height: 2; ">&nbsp;<? echo $this->treatcare_details['frequency'][8]['right_5'] ?></td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td>
			<table>
				<tr>
					<td width="60" align="left" valign="top" height="23">&nbsp;</td>
					<td width="580" align="left" valign="top" height="23" style="line-height: 3;  color: #ce6370;">&nbsp;</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
    			
    			<tr>
    				<td width="60" height="23" align="left" valign="top">&nbsp;</td>
	                <td width="600" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['wound_care_13'] ?></td>
	                <td width="10" height="23" align="left" valign="top">&nbsp;</td>
	                <td colspan="2" width="215" style="">
                		<table>
                			<tr>
                				<td width="28" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][9]['right_1'] ?></td>
                				<td width="34" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][9]['right_2'] ?></td>
                				<td width="35" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][9]['right_3'] ?></td>
                				<td width="58" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][9]['right_4'] ?></td>
                				<td width="57" height="23" align="left" valign="top" style="line-height: 2; ">&nbsp;<? echo $this->treatcare_details['frequency'][9]['right_5'] ?></td>
                			</tr>               		
                		</table>
                	</td>
              	</tr>
			</table>
		</td>
	</tr>
    <tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td colspan="3" align="left" valign="top" style="line-height: 0.5;">&nbsp;</td>
				</tr>
    			<tr>
    				<td width="60" height="23" align="left" valign="top">&nbsp;</td>
	                <td width="600" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['wound_care_14'] ?></td>
	                <td width="10" height="23" align="left" valign="top">&nbsp;</td>
	                <td colspan="2" width="215" style="">
                		<table>
                			<tr>
                				<td width="28" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][10]['right_1'] ?></td>
                				<td width="34" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][10]['right_2'] ?></td>
                				<td width="35" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][10]['right_3'] ?></td>
                				<td width="58" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['frequency'][10]['right_4'] ?></td>
                				<td width="57" height="23" align="left" valign="top" style="line-height: 2; ">&nbsp;<? echo $this->treatcare_details['frequency'][10]['right_5'] ?></td>
                			</tr>               		
                		</table>
                	</td>
              	</tr>
			</table>
		</td>
	</tr>
    <tr>
		<td>
			<table>
				<tr>
					<td width="60" align="left" valign="top" height="23">&nbsp;</td>
					<td width="580" align="left" valign="top" height="23" style="line-height: 2.5;">&nbsp;</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
    			
    			<tr>
    				<td width="60" height="23" align="left" valign="top">&nbsp;</td>
	                <td width="600" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->treatcare_details['wound_care_15'] ?></td>
	                <td width="75" height="23" align="left" valign="top">&nbsp;</td>
	                <td width="150" height="23" align="left" valign="top" style="line-height: 2;"><? echo $this->treatcare_details['care_number'] ?></td>
              	</tr>
			</table>
		</td>
	</tr>
	<tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
    			<tr>
					<td colspan="3" align="left" valign="top" style="line-height: 1;">&nbsp;</td>
				</tr>
    			<tr>
    				<td width="15" align="left" valign="top" style="font-size: 14px; font-weight: bold; ">&nbsp;</td>
    				<td width="40" align="left" valign="top" style="font-size: 14px; font-weight: bold;">&nbsp;</td>
    				<td width="580" align="left" valign="top" style="font-size: 14px; font-weight: bold; line-height: 2;">&nbsp;</td>
    			</tr>
    		</table>
    	</td>
    </tr>
 	<tr>
		<td align="left" valign="top" style="line-height: 1.1;">&nbsp;</td>
	</tr>
	<tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
    			
    			<tr>
    				<td width="60" height="23" align="left" valign="top">&nbsp;</td>
	                <td width="25" height="23" align="center" valign="top" style="font-size: 16px; font-weight: bold;"><? if($this->basiccare_details['basic_1'] == "1") { echo 'X'; } ?></td>
	                <td width="360" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
	                <td width="208" style="">
                		<table>
                			<tr>
                				<td width="97" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
                				<td width="115" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
                			</tr>                		
                		</table>
                	</td>
              	</tr>
			</table>
		</td>
	</tr>
    <tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td align="left" valign="top" style="line-height: 0.5;">&nbsp;</td>
				</tr>
    			<tr>
    				<td width="60" height="23" align="left" valign="top">&nbsp;</td>
	                <td width="25" height="23" align="center" valign="top" style="font-size: 16px; font-weight: bold;"><? if($this->basiccare_details['basic_2'] == "1") { echo 'X'; } ?></td>
	                <td width="360" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
	                <td width="208" style="">
                		<table>
                			<tr>
                				<td width="28" height="23" align="left" valign="top" style="line-height: 2;color: #ce6370;">&nbsp;</td>
                				<td width="34" height="23" align="left" valign="top" style="line-height: 2;color: #ce6370;">&nbsp;</td>
                				<td width="35" height="23" align="left" valign="top" style="line-height: 2;color: #ce6370;">&nbsp;</td>
                				<td width="58" height="23" align="left" valign="top" style="line-height: 2;color: #ce6370;">&nbsp;</td>
                				<td width="60" height="23" align="left" valign="top" style="line-height: 2; color: #ce6370;">&nbsp;</td>
                			</tr>               		
                		</table>
                	</td>
               </tr>
			</table>
		</td>
	</tr>
	<tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td align="left" valign="top" style="line-height: 0.5;">&nbsp;</td>
				</tr>
    			<tr>
    				<td width="88" height="23" align="left" valign="top">&nbsp;</td>
	                <td width="25" height="23" align="center" valign="top" style="font-size: 16px; font-weight: bold; "><? if($this->basiccare_details['basic_3'] == "1") { echo 'X'; } ?></td>
	                <td width="333" height="23" align="left" valign="top" style="line-height: 2;  color: #ce6370;">&nbsp;</td>
	                <td colspan="2" width="208" style="">
                		<table>
                			<tr>
                				<td width="28" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->basiccare_details['frequency'][11]['right_1'] ?></td>
                				<td width="34" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->basiccare_details['frequency'][11]['right_2'] ?></td>
                				<td width="35" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->basiccare_details['frequency'][11]['right_3'] ?></td>
                				<td width="58" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->basiccare_details['frequency'][11]['right_4'] ?></td>
                				<td width="60" height="23" align="left" valign="top" style="line-height: 2; ">&nbsp;<? echo $this->basiccare_details['frequency'][11]['right_5'] ?></td>
                			</tr>               		
                		</table>
                	</td>
               </tr>
			</table>
		</td>
	</tr>
	<tr>
    	<td width="100%">
    		<table border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td align="left" valign="top" style="line-height: 0.5;">&nbsp;</td>
				</tr>
    			<tr>
    				<td width="88" height="23" align="left" valign="top">&nbsp;</td>
	                <td width="25" height="23" align="center" valign="top" style="font-size: 16px; font-weight: bold; "><? if($this->basiccare_details['basic_4'] == "1") { echo 'X'; } ?></td>
	                <td width="333" height="23" align="left" valign="top" style="line-height: 2;  color: #ce6370;">&nbsp;</td>
	                <td width="208" style="">
                		<table>
                			<tr>
                				<td width="28" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->basiccare_details['frequency'][12]['right_1'] ?></td>
                				<td width="34" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->basiccare_details['frequency'][12]['right_2'] ?></td>
                				<td width="35" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->basiccare_details['frequency'][12]['right_3'] ?></td>
                				<td width="58" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;<? echo $this->basiccare_details['frequency'][12]['right_4'] ?></td>
                				<td width="60" height="23" align="left" valign="top" style="line-height: 2; ">&nbsp;<? echo $this->basiccare_details['frequency'][12]['right_5'] ?></td>
                			</tr>               		
                		</table>
                	</td>
                	<td width="10" height="23" align="left" valign="top">&nbsp;</td>
                	<td width="215" rowspan="11">
                		<table>
                			<tr>
                				<td width="215" align="left" valign="top" style="line-height: 1.5;">&nbsp;</td>
                			</tr>
                			<tr>
                				<td width="215"  style="line-height: 1;">
	                				<table>
	                					<tr>
	                						<td width="215" align="left" valign="top">&nbsp;</td>
	                					</tr>
	                					<tr>
	                						<td width="215" height="" align="center"><?php echo $this->stamp_block; ?></td>
	                					</tr>
	                				</table>
                				</td>
                			</tr>
                		</table>
                	</td>
                	
               </tr>
               <tr>
               		<td width="55" align="left" valign="top" style="line-height: 1.5">&nbsp;</td>

			   </tr>
               <?php
               	if($this->basiccare_details['basic_textarea'] != "")
					{
						$textlines = explode("<br />", nl2br($this->basiccare_details['basic_textarea']));

						if(count($textlines) == 1)
						{ ?>
					<tr>
						<td width="60" align="left" valign="top" height="23">&nbsp;</td>
						<td width="130" align="left" valign="top" height="23" style="line-height: 2;">&nbsp;</td>
						<td colspan="3" width="460" height="23" align="left" valign="middle" style="line-height: 2;">&nbsp;<? echo $textlines[0]; ?></td>
					</tr>
					<?php
						for($nrl=1; $nrl<=3; $nrl++)
					{ ?>
						<tr>
							<td style="line-height: 0.5">&nbsp;</td>
						</tr>
						<tr>
							<td width="60" align="left" valign="top" height="23">&nbsp;</td>
							<td colspan="4" width="590" height="23" align="left" valign="top" style="line-height: 2;">&nbsp;</td>
						</tr>
                <?php } } elseif(count($textlines) == 2) { ?>
                	<tr>
						<td width="60" align="left" valign="top" height="23">&nbsp;</td>
						<td width="130" align="left" valign="top" height="23" style="line-height: 2;">&nbsp;</td>
						<td colspan="3" width="460" height="23" align="left" valign="middle" style="line-height: 2;">&nbsp;<? echo $textlines[0]; ?></td>
	                </tr>
					<tr>
						<td style="line-height: 0.5">&nbsp;</td>
					</tr>
	                <tr>
	                	<td width="60" align="left" valign="top" height="23">&nbsp;</td>
	                	<td colspan="4" width="590" height="23" align="left" valign="middle" style="line-height: 2;"><? echo $textlines[1]; ?></td>
					</tr>
					<tr>
						<td style="line-height: 0.5">&nbsp;</td>
					</tr>
					<tr>
						<td width="60" align="left" valign="top" height="23">&nbsp;</td>
	                	<td colspan="4" width="590" height="23" align="left" valign="middle" style="line-height: 2;">&nbsp;</td>
	                </tr>
					<tr>
						<td style="line-height: 0.5">&nbsp;</td>
					</tr>
	                <tr>
	                	<td width="60" align="left" valign="top" height="23">&nbsp;</td>
	                	<td colspan="4" width="590" height="23" align="left" valign="middle" style="line-height: 2;">&nbsp;</td>
	                </tr>
	            <?php } elseif(count($textlines) == 3) { ?>
					<tr>
						<td width="60" align="left" valign="top" height="23">&nbsp;</td>
						<td width="130" align="left" valign="top" height="23" style="line-height: 2;">&nbsp;</td>
						<td colspan="3" width="460" height="23" align="left" valign="middle" style="line-height: 2;">&nbsp;<? echo $textlines[0]; ?></td>
					</tr>
					<tr>
						<td style="line-height: 0.5">&nbsp;</td>
					</tr>
	                <tr>
	                	<td width="60" align="left" valign="top" height="23">&nbsp;</td>
	                	<td colspan="4" width="590" height="23" align="left" valign="middle" style="line-height: 2;"><? echo $textlines[1]; ?></td>
					</tr>
					<tr>
						<td style="line-height: 0.5">&nbsp;</td>
					</tr>
					<tr>
						<td width="60" align="left" valign="top" height="23">&nbsp;</td>
	                	<td colspan="4" width="590" height="23" align="left" valign="middle" style=""><? echo $textlines[2]; ?></td>
	                </tr>
					<tr>
						<td style="line-height: 0.5">&nbsp;</td>
					</tr>
	                <tr>
	                	<td width="60" align="left" valign="top" height="23">&nbsp;</td>
	                	<td colspan="4" width="590" height="23" align="left" valign="middle" style="line-height: 2;">&nbsp;</td>
	                </tr>
	                 <?php } elseif(count($textlines) >= 4) { ?>
	            	<tr>
						<td width="60" align="left" valign="top" height="23">&nbsp;</td>
						<td width="130" align="left" valign="top" height="23" style="line-height: 2;  color: #ce6370;">&nbsp;</td>
	                	<td colspan="3" width="460" height="23" align="left" valign="middle" style="line-height: 2;">&nbsp;<? echo $textlines[0]; ?></td>
	                </tr>
					<tr>
						<td style="line-height: 0.5">&nbsp;</td>
					</tr>
	                <tr>
	                	<td width="60" align="left" valign="top" height="23">&nbsp;</td>
	                	<td colspan="4" width="590" height="23" align="left" valign="middle" style="line-height: 2;"><? echo $textlines[1]; ?></td>
					</tr>
					<tr>
						<td style="line-height: 0.5">&nbsp;</td>
					</tr>
					<tr>
						<td width="60" align="left" valign="top" height="23">&nbsp;</td>
	                	<td colspan="4" width="590" height="23" align="left" valign="middle" style="line-height: 2;"><? echo $textlines[2]; ?></td>
	                </tr>
					<tr>
						<td style="line-height: 0.5">&nbsp;</td>
					</tr>
	                <tr>
	                	<td width="60" align="left" valign="top" height="23">&nbsp;</td>
	                	<td colspan="4" width="590" height="23" align="left" valign="middle" style="line-height: 2;"><? echo $textlines[3]; ?></td>
	                </tr>
	           <?php } } else { ?>
	           		<tr>
	           			<td width="60" align="left" valign="top" height="23">&nbsp;</td>
	                	<td colspan="4" width="590" height="23" align="left" valign="middle" style="line-height: 2;">&nbsp;</td>
	                </tr>
					<tr>
						<td style="line-height: 0.5">&nbsp;</td>
					</tr>
	                <tr>
	                	<td width="60" align="left" valign="top" height="23">&nbsp;</td>
	                	<td colspan="4" width="590" height="23" align="left" valign="middle" style="line-height: 2;">&nbsp;</td>
					</tr>
					<tr>
						<td style="line-height: 0.5">&nbsp;</td>
					</tr>
					<tr>
						<td width="60" align="left" valign="top" height="23">&nbsp;</td>
	                	<td colspan="4" width="590" height="23" align="left" valign="middle" style="line-height: 2;">&nbsp;</td>
	                </tr>
					<tr>
						<td style="line-height: 0.5">&nbsp;</td>
					</tr>
	                <tr>
	                	<td width="60" align="left" valign="top" height="23">&nbsp;</td>
	                	<td colspan="4" width="590" height="23" align="left" valign="middle" style="line-height: 2;">&nbsp;</td>
	                </tr>
	           <?php } ?>
	           <tr>
               		<td colspan="5" width="5" align="left" valign="top" style="line-height: 0.5;">&nbsp;</td>
			   </tr>
	           <tr>
               		<td width="55" align="left" valign="top" height="23">&nbsp;</td>
					<td colspan="4" width="590" align="left" valign="top" height="23" style="line-height: 2;">&nbsp;</td>
			   </tr>
			</table>
		</td>
	</tr>
</table>
