<!-- Maria:: Migration ISPC to CISPC 08.08.2020 -->
<?php
$order_data = $this->order_data;
$patient_enc_id = $this->patient_enc_id;
$lang = $this->translate('order_details');
$client_materials = $this->client_materials;
?>

<h1><?php echo $lang ['[Delivery For]'] ?> <b><?php echo $order_data['PatientsOrdersDetails']['patient_name']?></b></h1>
<hr/>
<br/>

<h3>1) <?php echo $lang ['[Dates]']; ?></h3>
<table>
	<tr>
		<td width="20%"><?php echo $lang ['[Order date]']; ?> </td>
		<td width="20%"> <u><?php echo $order_data['PatientsOrdersDetails']['order_date']?></u></td>
		<td class="button_td"></td>
		<td  width="20%"><?php echo $lang ['[Delivery date]']; ?> </td>
		<td width="20%"><u><?php echo $order_data['PatientsOrdersDeliveryDates']['delivery_date']?></u></td>
	</tr>
	<?php if(!empty($order_data['PatientsOrdersDeliveryDates']['order_deliveries'])):?>
	<tr>
		<td colspan="3"></td>
		<td><?php echo $lang ['[previous delivery]']; ?></td>
		<td>
			<table>
				<?php foreach($order_data['PatientsOrdersDeliveryDates']['order_deliveries'] as $k=>$del_Date):?>
				<tr>
					<td><?php echo $del_Date;?></td>
				</tr>
				<?php endforeach; ?>
			</table>
		</td>
	</tr>
	<?php endif;?>
	<tr>
	    <td colspan="5" align="right"><?php echo $this->translate('delivery_date_info'); ?></td>
	</tr>
</table>

	
<br/>&nbsp;<br/>

<h3>2) <?php echo $lang ['[Order intervall]']; ?></h3>
<table border="0" cellpadding="10" style="width: 100%">
	<tr>
		<td>
		<?php $intervals =  array(
					'once' => $lang['[Once]'],
					'every_x_days' => $lang['[Every x days]'],
					'selected_days_of_the_week' => $lang['[every week on the following work days]'],
				);?>
			<?php 
				echo $this->formRadio("data[PatientsOrdersDetails][order_interval]", $order_data['PatientsOrdersDetails']['order_interval'], array() , $intervals , " ");
				?>
         </td>
    </tr>
    <tr>
        <td border="1">
				<?php 
				if($order_data['PatientsOrdersDetails']['order_interval'] == "every_x_days"){
				    echo $order_data['PatientsOrdersDetails']['order_interval_options'];
				} elseif($order_data['PatientsOrdersDetails']['order_interval'] == "selected_days_of_the_week"){
				    echo $this->formMultiCheckbox("data[PatientsOrdersDetails][order_interval_options]", explode(',',$order_data['PatientsOrdersDetails']['order_interval_options']), array("class"=>"ioptions selected_days_of_the_week" ), $this->days_of_week_arr , "<br />\n");
				}
				?>
		</td>
	</tr>
</table>
	

<br/>&nbsp;<br/>


<h3>3) <?php echo $lang ['[Order Medication]']; ?></h3>
<table border="1" cellpadding="10" cellspacing="0"  style="width: 100%">
<?php if(!empty($order_data['PatientsOrdersMedication'])): ?>
    <tr>
        <th style="background: #fefefe;" ><?php echo $lang ['[medication]']; ?></th>
        <th style="background: #fefefe;" ><?php echo $lang ['[dosage]']; ?></th>
        <th style="background: #fefefe;" ><?php echo $lang ['[packaging]']; ?></th>
        <th style="background: #fefefe;" ><?php echo $lang ['[volume]']; ?></th>
        <th style="background: #fefefe;" ><?php echo $lang ['[kcal]']; ?></th>
    </tr>	    
	<?php foreach($order_data['PatientsOrdersMedication'] as $dr_id=>$med): ?>
	    <tr>
	       <td><?php echo $med['medication_name'];?></td>
	       <td><?php echo $med['dosage'];?></td>
	       <td><?php echo $med['packaging'];?></td>
	       <td><?php echo $med['volume'];?></td>
	       <td><?php echo $med['kcal'];?></td>
	    </tr>
	    
	<?php endforeach;?>
	<?php else:?>
      <tr>
          <td colspan="6"><?php echo $lang ['[no medication]']; ?></td>
      </tr>
	<?php endif;?>
</table>    


<br/>&nbsp;<br/>	
	
<h3>4) <?php echo $lang ['[Order Additional lists]']; ?></h3>
<?php if(empty($this->client_materials)):?>
	<?php echo  $lang ['[no aditional items]'] ?>
<?php else: ?>
<table border="1" cellpadding="10"  style="width: 100%; text-align: left;">
<?php $c=1; foreach($this->client_materials as $category => $items): ?>
<tr>
<th><h4 class="<?php echo $category ?>"><?php echo $c.'. '. $lang ['[Category_'.$category.']']; ?></h4></th>
</tr>
<?php if(!empty($order_data['PatientsOrdersMaterials'][$category])): ?>
        <tr><td>
        	<!-- ISPC-2639 pct.3 Lore 24.07.2020 -->
    	      <table>
    	      <!--                 <tr>
                  <th style="  border: 1px solid black;  border-collapse: collapse;" > Name</th>
                  <th style="  border: 1px solid black;  border-collapse: collapse;" > Quantity ordered</th>
                </tr> -->

                  <?php foreach($order_data['PatientsOrdersMaterials'][$category] as $k=>$id): ?>
                    <?php if($id > 0):?>
                    <tr >
                      <td > <?php echo $client_materials[$category][$k];?></td>
                      <td > <?php echo $id;?></td>
                    </tr>
                   <?php endif; ?>
                  <?php endforeach; ?>
              </table>
			<!-- //. -->
                                    	<!--         	<?php for($i=0; $i < $id; $i++): ?>
                                    		<?php echo   $client_materials[$category][$k].'; ';?>
                                    	<?php endfor;?>  -->
        </td>
        </tr>
	<?php else: ?>
    <?php   echo '<tr><td>-- </td> </tr>';?> 
	<?php endif; ?>

<?php $c++; endforeach; ?>
</table>	
<?php endif; ?>

<br/>&nbsp;<br/>

	
<h3>5) <?php echo $lang ['[Pharmacy]']; ?></h3>
<?php 
$listef = array();
foreach ($order_data['PatientsOrdersRecipients'] as $k=>$rid){
    if(!in_array($rid,$listef)){
        echo $order_data['recipients'][$rid].'; '; 
        $listef[] = $rid; 
    }
}
?>


<br/>&nbsp;<br/>

<h3>6) <?php echo $lang ['[Comment order]']; ?></h3>
<table border="1" cellpadding="10"  style="width: 100%; page-break-inside: avoid;">
<tr>
<td>
<?php echo  $order_data['PatientsOrdersDetails']['order_comment'] ?>
</td>
</tr>
</table>
	
	

<br/>&nbsp;<br/>
<br/>&nbsp;<br/>
<table border="0" cellpadding="10"  style="width: 100%; page-break-inside: avoid;">
<tr>
<td>
<?php echo $lang ['[Order verified by user:]']; ?> <b><?php echo  $order_data['current_user_name'] ?></b> - <?php echo  date('d.m.Y') ?>  
</td>
</tr>
</table>