<head>
       <!--  <link href="<?php echo APP_BASE; ?>/css/page-css/wlassessment_pdf.css" rel="stylesheet" type="text/css" /> -->
        <link href="<?php echo APP_BASE; ?>/css/page-css/patientdiagnosis.css" rel="stylesheet" type="text/css" />   
                        
    </head>
<?php 
//ISPC-2775 Carmen 06.01.2021
?>
 <table border="0">
 <tr><td height="25px"></td> </tr>
 <tr>
 	<th bgcolor="#D8D8D8" height="25px"><b>Diagnosen</b></th>
 </tr>
 <tr><td height="25px"></td> </tr>
 </table>
<!-- FILTER  -->

<table>
<tr>
	<?php foreach($this->diagnosis_categories as $cat_id=>$cat) : ?>
	
		<?php if(in_array($cat_id,$this->used_categories)):?>
		
    		<td bgcolor="<?php echo $cat['color']?>">
    		<?php echo $cat['shortcut'];?> - <?php echo $cat['name']?>
    		</td>
		
		<?php endif;?>
	<?php endforeach;?>
	</tr>
	 <tr><td height="25px"></td> </tr>
	</table>


<!-- ACTIVE  -->

<table id="table_icd" style="width: 100%;">
<tr>
	<td><b><?php echo $this->translate('icd_category'); ?></b></td>
	<td><b><?php echo $this->translate('icd_code'); ?></font></td>
	<td><b><?php echo $this->translate('icd_description'); ?></font></td>
	<td><b><?php echo $this->translate('relevant2admission'); ?></font></td>
	<td><b><?php echo $this->translate('icd_start_date'); ?></font></td>
	<td><b><?php echo $this->translate('icd_end_date'); ?></font></td>
	<td><b><?php echo $this->translate('icd_comment'); ?></font></td>
</tr>
<?php foreach($this->icd_data as $kicd => $vicd) { 
	if($vicd['order_value'] != 'p') {
	?>
	<tr>
		<td><table><tr><?php echo $vicd['icd_category']; ?></tr></table></td>
		<td><?php echo $vicd['icd_code']; ?></td>
		<td><?php echo $vicd['icd_description']; ?></td>
		<td align="center"><?php echo $vicd['relevant2admission']; ?></td>
		<td><?php echo $vicd['icd_start_date']; ?></td>
		<td><?php echo $vicd['icd_end_date']; ?></td>
		<td><?php echo $vicd['icd_comment']; ?></td>
	</tr>
<?php } } ?>
</table>



<!-- ENDED -->

<h2>beendet, aber aus aktuellem Fall</h2>
<table id="ended_table_icd" style="width: 100%;">
<tr>
	<td><b><?php echo $this->translate('icd_category'); ?></font></td>
	<td><b><?php echo $this->translate('icd_code'); ?></font></td>
	<td><b><?php echo $this->translate('icd_description'); ?></font></td>
	<td><b><?php echo $this->translate('relevant2admission'); ?></font></td>
	<td><b><?php echo $this->translate('icd_start_date'); ?></font></td>
	<td><b><?php echo $this->translate('icd_end_date'); ?></font></td>
	<td><b><?php echo $this->translate('icd_comment'); ?></font></td>
</tr>
<?php foreach($this->icd_data_ended as $kicd => $vicd) { ?>
	<tr>
		<td><table><tr><?php echo $vicd['icd_category']; ?></tr></table></td>
		<td><?php echo $vicd['icd_code']; ?></td>
		<td><?php echo $vicd['icd_description']; ?></td>
		<td align="center"><?php echo $vicd['relevant2admission']; ?></td>
		<td><?php echo $vicd['icd_start_date']; ?></td>
		<td><?php echo $vicd['icd_end_date']; ?></td>
		<td><?php echo $vicd['icd_comment']; ?></td>
	</tr>
<?php } ?>
</table>


<!-- ARCHIVED -->

<h1>Archiv der Diagnosen &amp; Symptome</h1>
<table id="archived_table_icd" style="width: 100%;">
<tr>
	<td><b><?php echo $this->translate('icd_category'); ?></font></td>
	<td><b><?php echo $this->translate('icd_code'); ?></font></td>
	<td><b><?php echo $this->translate('icd_description'); ?></font></td>
	<td><b><?php echo $this->translate('relevant2admission'); ?></font></td>
	<td><b><?php echo $this->translate('icd_start_date'); ?></font></td>
	<td><b><?php echo $this->translate('icd_end_date'); ?></font></td>
	<td><b><?php echo $this->translate('icd_comment'); ?></font></td>
</tr>
<?php foreach($this->icd_data_archived as $kicd => $vicd) { ?>
	<tr>
		<td><table><tr><?php echo $vicd['icd_category']; ?></tr></table></td>
		<td><?php echo $vicd['icd_code']; ?></td>
		<td><?php echo $vicd['icd_description']; ?></td>
		<td align="center"><?php echo $vicd['relevant2admission']; ?></td>
		<td><?php echo $vicd['icd_start_date']; ?></td>
		<td><?php echo $vicd['icd_end_date']; ?></td>
		<td><?php echo $vicd['icd_comment']; ?></td>
	</tr>
<?php } ?></table>

