<!-- Maria:: Migration ISPC to CISPC 08.08.2020 -->
<html>
    <head>
    <meta http-equiv="Content-Type" content="charset=utf-8" />
 
        <link href="<?php echo PUBLIC_PATH; ?>/css/page-css/rubinforms_pdf.css" rel="stylesheet" type="text/css" />   
        <style>
            @page { margin: 40px 60px 40px 70px; }
        </style>               
    </head>
    
    <body class='rubin_form_class <?=$this->form_ident?>'>
       
        <div id="content">
        
        <?=$this->form_pdf;?>

        </div>                                
    </body>
</html>
 