<html>
    <head>
    <meta http-equiv="Content-Type" content="charset=utf-8" />
 
        <link href="<?php echo PUBLIC_PATH; ?>/css/page-css/rubin_mna_pdf.css" rel="stylesheet" type="text/css" />
        <style>
            @page { margin: 40px 60px 40px 70px; }
        </style>               
    </head>
    
    <body class='rubin_form_class'>
       
        <div id="content">
        
        <?=$this->form_pdf;?>

        </div>                                
    </body>
</html>
