<html><head>
        <link href="<?=$this->app_path?>/../public/css/page-css/wlassessment_pdf.css" rel="stylesheet" type="text/css" />  
        <style>
            @page { margin: 20px 20px 60px 40px; }
        </style>                
    </head><body class='wlassessment_form_class'>
       
        <div id="content">
        
        <?=$this->wlassessment_form;?>    

        </div>                                
    </body></html>