<?php

$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/data_tables/jquery.dataTables.js?'.date('Ymd'));
$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/data_tables/dataTables.jqueryui.js?'.date('Ymd'));
//$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/views/dischargelocation/listlocation.js?'.date('Ymd'));
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/data_tables/dataTables.jqueryui.css?' . date('Ymd'));
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/page-css/listscommon.css?' . date('Ymd'));
?>

<br/>
<div id="addfamilydoctor_Msgerror" class="err"><? echo $this->error_message; ?></div>
<div class="add_link">
	<a href="<?php echo $this->url(array('controller'=>'diagnosis' , 'action' => 'addclientdiagnosis' )); ?>"><? echo $this->translate('addarticle'); ?></a>
</div>

 <h1><? echo $this->translate('listclientdiagnosis') ?></h1>
<br/>
<!-- <div style="clear:both;"></div> -->
<div id="addfamilydoctor_Msgerror" class="err"><? echo urldecode($_GET['mes']); ?></div>	
<table id="table" class="table table-striped table-bordered table-hover table-condensed dataTable no-footer  left_menu_datatable">
</table>	

 <!-- <div class="diagno_assigned"> <span>!</span> ) <?php echo $this->translate('The diagnoses marked have patients assigned.'); ?></div> -->
 