<?php 
/**
 * TODO: on production use leaflet.js
 * TODO: on production use leaflet-routing-machine.min.js
 */

$this->headLink()
    //->appendStylesheet(APP_BASE . "https://unpkg.com/leaflet@1.2.0/dist/leaflet.css")
    //->appendStylesheet("https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.css")
    ->appendStylesheet(APP_BASE . "javascript/openstreetmap/jquery-switchButton-1.0/jquery.switchButton.css")
    ->appendStylesheet(APP_BASE . "javascript/openstreetmap/leaflet-1.4.0/leaflet.css")    
    ->appendStylesheet(APP_BASE . "javascript/openstreetmap/leaflet-routing-machine-3.2.12/dist/leaflet-routing-machine.css")
    ->appendStylesheet(APP_BASE . "javascript/openstreetmap/leaflet-list-markers-0.1.0/dist/leaflet-list-markers.src.css")
    ->appendStylesheet(APP_BASE . "javascript/openstreetmap/leaflet-extramarkers-1.1.0/dist/css/leaflet.extra-markers.min.css")
    ->appendStylesheet(APP_BASE . "javascript/openstreetmap/leaflet-easybutton-2.4.0/src/easy-button.css")
    ->appendStylesheet(APP_BASE . "javascript/openstreetmap/leaflet-search-2.9.8/dist/leaflet-search.src.css")
    ->appendStylesheet(APP_BASE . "javascript/openstreetmap/leaflet-markercluster-0.7/dist/MarkerCluster.css")
    ->appendStylesheet(APP_BASE . "javascript/openstreetmap/leaflet-markercluster-0.7/dist/MarkerCluster.Default.css")
    
    
    ->appendStylesheet(APP_BASE . "css/page-css/openstreetmap.css")
    
    
;
    
//<script src="http://cdn.leafletjs.com/leaflet-0.7/leaflet.js"></script>

$this->headScript()
    
    ->appendFile(APP_BASE . "javascript/openstreetmap/jquery-switchButton-1.0/jquery.switchButton.js")
    
    //->appendFile("https://unpkg.com/leaflet@1.2.0/dist/leaflet.js")
    //->appendFile("https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.js")
//     ->appendFile("http://cdn.leafletjs.com/leaflet-0.7/leaflet.js")
//      ->appendFile("https://unpkg.com/leaflet.markercluster@1.4.0/dist/leaflet.markercluster.js")
//      ->appendFile("https://unpkg.com/leaflet.featuregroup.subgroup@1.0.2/dist/leaflet.featuregroup.subgroup.js")
    

    ->appendFile(APP_BASE . "javascript/openstreetmap/leaflet-1.4.0/leaflet-src.js")    
    ->appendFile(APP_BASE . "javascript/openstreetmap/leaflet-routing-machine-3.2.12/dist/leaflet-routing-machine.js")   
    ->appendFile(APP_BASE . "javascript/openstreetmap/leaflet-list-markers-0.1.0/dist/leaflet-list-markers.src.js")   
    ->appendFile(APP_BASE . "javascript/openstreetmap/leaflet-extramarkers-1.1.0/dist/js/leaflet.extra-markers.js")   
    ->appendFile(APP_BASE . "javascript/openstreetmap/leaflet-easybutton-2.4.0/src/easy-button.js")   
    ->appendFile(APP_BASE . "javascript/openstreetmap/leaflet-search-2.9.8/dist/leaflet-search.src.js")
    ->appendFile(APP_BASE . "javascript/openstreetmap/leaflet-markercluster-1.4.0/dist/leaflet.markercluster.js")    
    ->appendFile(APP_BASE . "javascript/openstreetmap/leaflet-featuregroup-subgroup-1.0.2/dist/leaflet.featuregroup.subgroup.js")    
    
    ->appendFile(APP_BASE . "javascript/views/routeplanning/Control.Geocoder.js")   
    //->appendFile(APP_BASE . "javascript/leaflet-routing-machine-3.2.12/examples/config.js")   
;

?>

<style>
/*make page 100%*/
.outer,
#Wrapper {
    width:100%!important;
    overflow: hidden;
}

#MainContent{
    width:calc(100% - 230px); 
    /*230 is from the .LeftDiv.left width:192px + #Wrapper margin-left:20px + MainContent margin-left:10px=> 222px + 8px from me*/
}

.map {

    position: relative;
    
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    
    width:100%;
    height:100%;
    min-height:800px;
    display:block;
}
    
.results {
    background-color: white;
    opacity: 0.8;
    position: absolute;
    top: 12px;
    right: 12px;
    width: 320px;
    height: 480px;
    overflow-y: scroll;
}
</style>



<div id="map" class="map"></div>


<div id="wrongaddresses" class="wrongaddresses list-markers leaflet-control" style="display:none">
    <h2><?=$this->translate("Sorry, we cannot locate the addresses of this patients , please fix them and reload this page")?></h2>
    <br/>
    <ul class="list-markers-ul"></ul>
</div>


