<?php
// ISPC-2654 Ancuta 07.10.2020
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/page-css/patientdiagnosis.css');

?>

<style>
	#livesearch_opscode {

        max-height: 300px;
        overflow-x: hidden;
        overflow-y: scroll;
        width: 680px !important;
        background-color: #fff;
        border: 2px solid #000;
        display:block;
       /* z-index:2147483647; /* !! MAX */
    }
    #pathogen_error {
	display: none;
	color: #e32;
}
</style>

<div style="display: none;"><img id="calImg" src="<? echo RES_FILE_PATH;  ?>/images/calendar.png" alt="Popup" class="trigger"></div>
<div id="diagnosis_tabs">
	<ul>
		<li><a href="#tabs-1">ICD</a></li>
		<?php if(!$this->onlyicd) { //ISPC-2775 Carmen 05.01.2020 ?> 
			<li><a id="nonmedical_tab_ops" href="#tabs-2">OPS</a></li>
			<li><a id="nonmedical_tab" href="#tabs-3">MRE</a></li>
		<?php } //ISPC-2775 Carmen 05.01.2020 ?>
	</ul>
	<div id="tabs-1">
    	
    	<?php
    $block = $this->icd;
    echo $block['__formHTML'];
    ?>
    	
    </div>
    <?php if(!$this->onlyicd) { //ISPC-2775 Carmen 05.01.2020 ?> 
	<div id="tabs-2">

	<?php
    $block = $this->ops;
    echo $block['__formHTML'];
    ?>
</div>
	<div id="tabs-3">
    	<?php
    $block = $this->mre;
    echo $block['__formHTML'];
    ?>
    </div>
    <?php } //ISPC-2775 Carmen 05.01.2020 ?>
</div>