<!-- Maria:: Migration ISPC to CISPC 08.08.2020 -->
<?
// $this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/data_tables/datatables.min.css');
// $this->headScript()->appendFile(RES_FILE_PATH.'/javascript/data_tables/jquery.dataTables.js');
// $this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/data_tables/fixedColumns.dataTables.min.css');
// $this->headScript()->appendFile(RES_FILE_PATH.'/javascript/data_tables/dataTables.fixedColumns.min.js');
// $this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/medicationnew.css');
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/page-css/patientmedication/style.mobile.css');
$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/dateUtil.js');

$is_ie = 0;
$ua = htmlentities($_SERVER['HTTP_USER_AGENT'], ENT_QUOTES, 'UTF-8');
if (preg_match('~MSIE|Internet Explorer~i', $ua) || (strpos($ua, 'Trident/7.0') !== false && strpos($ua, 'rv:11.0') !== false)) {
    // do stuff for IE
    $is_ie = 1;
}

// ISPC-2346 Added by Ancuta  18.06.2019 START:
if($this->ModulePrivileges[189] == true && $is_ie == 0 ){
    $this->headScript()->appendFile(RES_FILE_PATH.'/javascript/dynamsoft-javascript-barcode/dist/dbr-6.5.2.min.js');
    $this->headScript()->appendFile(RES_FILE_PATH.'/javascript/pms/datamatriximportReader.js');
}else{
    $this->headScript()->appendFile(RES_FILE_PATH.'/javascript/pms/datamatriximport.js');
}
// --


// allowed medication types
$allowed_medication_types = $this->medication_blocks;
$timed_scheduled_medications = $this->timed_scheduled_medications; 
$allow_normal_scheduled = $this->allow_normal_scheduled; 

// for ISPC-2247 changes were made to this page (Ancuta 06.11.2018)
$sort_order = $this->sort_order;

// ISPC-2524 pct.1)  Lore 14.01.2020
$contact_form_files = $this->form_files;
$users_data = $this->users_data;
?>

<script type="text/javascript">
var is_ie = "<?php echo $is_ie?>";

var allow_reader = 0;
<?php if($this->ModulePrivileges[189] == true):?> 
var allow_reader = 1;
<?php endif;?>

var med_sort = "";
var saved_sorting_ls = '<?php echo $this->js_saved_order; ?>';
var saved_sorting = jQuery.parseJSON (saved_sorting_ls) || {};
// console.log(saved_sorting);
var pat = "<?php echo $_REQUEST['id']; ?>";
var Barcodereader_LicenseKey = "<?php echo $this->barcodereaderKey; ?>";
var datamatrixurl = "patientnew/datamatriximport";

var dosage_intervals_json = <?php if ( ! empty($this->dosage_intervals) && is_array($this->dosage_intervals)) { echo json_encode($this->dosage_intervals);} else echo'{}' ?>;

 
 var reset_comment = "";
 var current_date = "<?php echo date("d.m.Y",time()); ?>";

 
$(document).ready(function() { /*------ Start $(document).ready --------------------*/

	getmedicationdeleted();

	//     ISPC-2127 deleted medis :: show hide 21.02.2018
	$('.deleted_meds_state').live('click',function(){
		
		$('#deleted_med_table').toggle();
		if ($(this).hasClass('hidden')){
			$(this).removeClass('hidden')
			$(this).addClass('shown')
		} else if ($(this).hasClass('shown')){
			$(this).removeClass('shown')
			$(this).addClass('hidden')
		}
	});

	// ISPC-2524 pct.1) Lore 15.01.2020
	$('.dateien_verlauf_state').live('click',function(){
		
		$('#dateien_verlauf_med_table').toggle();
		if ($(this).hasClass('hidden')){
			$(this).removeClass('hidden')
			$(this).addClass('shown')
		} else if ($(this).hasClass('shown')){
			$(this).removeClass('shown')
			$(this).addClass('hidden')
		}
	});
	//.
	
	$("#print_button").prop('disabled', true);

	
	$('#select_pdf').live('change',function(){
		if($(this).val() != 0 ) {
			$('#print_button').removeAttr('disabled','disabled');
		} else {
			$("#print_button").prop('disabled', true);
		}
		
	});
	
	$('#print_button').live('click',function(e){
		e.preventDefault();
		if($('#select_pdf').val() !=0){
			$("#print_medications").submit();	
		}
		
	});
	
	//ISPC - 2305 - reset scheduled medication comment
	$(document).on('change', '#reset_comment', function(){
		reset_comment = $('#reset_comment').val();
	});
	
	// scheduled medication interval start / restart 
	$(".interval_start").live('click',function(){
	 	var patient_id = '<?php echo $_REQUEST['id']; ?>';
	 	var current_date = '<?php echo date("d.m.Y",time()); ?>';
	 	
		var drug_id = $(this).data("drug_id");
		var medication_type = $(this).data("medication_type");
		//ISPC - 2305 - scheduled medication reset comment
		var medi_comment = $('#'+drug_id+'_medi_comment').html();
		
		if(medication_type != 'scheduled')
		{
			reset_comment_dialog = '<?php echo $this->translate("confirm_give_medication"); ?>';
		}
		else
		{
			reset_comment_dialog = '<span style="width: 100%;display: block;"><?php echo $this->translate("confirm_give_medication"); ?></span><label style="display: block; width: 100%; padding-top: 10px;"><?php echo $this->translate("medication_comments");?>:</label>';				
			reset_comment_dialog += '<textarea name="reset_comment"  id="reset_comment" rows="" cols=""></textarea>';	
		}
		
		jConfirm(reset_comment_dialog, '<?php echo $this->translate('confirm_give_medication_title'); ?>', function(r) {
		    if(r) {
				
				$.ajax({
					type: 'POST',
					url: 'ajax/givescheduledmed',
					data: {
						id: patient_id,
						drug_id: drug_id,
						reset_comment: reset_comment
					},
					success:function(response){
						

						$('#'+medication_type+'_'+drug_id+'_interval_start').remove(); // remove button
						$('#'+drug_id+'_administration_date').html(current_date);// change date
						$('#'+drug_id+'_medi_comment').html(medi_comment+'<br/>'+reset_comment);// change comment
						
						setTimeout(function () {
							$('#sch_'+drug_id).remove();
						}, 800);
						//console.log(response);
						var response_obj = jQuery.parseJSON(response);
						if (response_obj['remove_icon'] == '1') {
							$('#sys_icon-52').remove();
							$('#content_sys_icon-52').remove();
						}
					}
				});
		    }  
		});
	});
	
	$(".interval_restart").live('click',function(){
	 	var patient_id = '<?php echo $_REQUEST['id']; ?>';
	 	var current_date = '<?php echo date("d.m.Y",time()); ?>';
		var drug_id = $(this).data("drug_id");
		var medication_type = $(this).data("medication_type");
		//ISPC - 2305 - scheduled medication reset comment
		var medi_comment = $('#'+drug_id+'_medi_comment').html();
		//console.log("dddd");
		if(medication_type != 'scheduled')
		{
			reset_comment_dialog = '<?php echo $this->translate("confirm_give_medication"); ?>';
		}
		else
		{
			reset_comment_dialog = '<span style="width: 100%;display: block;"><?php echo $this->translate("confirm_give_medication"); ?></span><label style="display: block; width: 100%; padding-top: 10px;"><?php echo $this->translate("medication_comments");?>:</label>';				
			reset_comment_dialog += '<textarea name="reset_comment"  id="reset_comment" rows="" cols=""></textarea>';	
		}
		
		jConfirm(reset_comment_dialog, '<?php echo $this->translate('confirm_give_medication_title'); ?>', function(r) {
			
		    if(r) {
// 				ajaxCallserver({url: appbase + 'ajax/givescheduledmed', method:'POST', data: {id: patient_id, drug_id: drug_id}, callLoading: readmisionCallback});
// 				$('#'+medication_type+'_'+drug_id+'_interval_restart').remove(); //  remove button
// 				$('#'+drug_id+'_administration_date').html(current_date);// change date
// 				window.location.reload(true);
			
				$.ajax({
					type: 'POST',
					url: 'ajax/givescheduledmed',
					data: {
						id: patient_id,
						drug_id: drug_id,
						reset_comment: reset_comment
					},
					success:function(response){
						

						$('#'+medication_type+'_'+drug_id+'_interval_restart').remove(); // remove button
						$('#'+drug_id+'_administration_date').html(current_date);// change date
						$('#'+drug_id+'_medi_comment').html(medi_comment+'<br/>'+reset_comment);// change comment
						
						setTimeout(function () {
							$('#sch_'+drug_id).remove();
						}, 800);
						
						//console.log(response);
						var response_obj = jQuery.parseJSON(response);
						if (response_obj['remove_icon'] == '1') {
							$('#sys_icon-52').remove();
							$('#content_sys_icon-52').remove();
						}
					}
				});
		    }  
		});
	});
	
	
	
	
	$('.med_approve_rights').removeAttr('disabled','disabled');
	$('.med_approve_rights').live('click',function(e){
		e.preventDefault();
		
		var action = $(this).data('action');
		var recordid = $(this).data('recordid');
		var alt_id = $(this).data('alt_id');
		$('.med_approve_rights').attr('disabled','disabled');
		
		if(action && recordid){
			$.ajax({
				type: 'POST',
				url: 'ajax/applymedicationchanges?id=<?php echo $_REQUEST['id']; ?>',
				data: {
					action: action,
					recordid: recordid,
					alt_id: alt_id
				},
				success:function(data){
					location.href = "<?php echo APP_BASE ?>patientmedication/overview?flg=suc&id=<?php echo $_REQUEST['id']; ?>";
				},
				error:function(){
					ajax_done = 1;
					// failed request; give feedback to user
				}
			});
		}
	});
	
	
	$('.pump_med_approve_rights').removeAttr('disabled','disabled');
	$('.pump_med_approve_rights').live('click',function(e){
		e.preventDefault();
		
		var action = $(this).data('action');
		var recordid = $(this).data('recordid');
		var alt_id = $(this).data('alt_id');
		$('.pump_med_approve_rights').attr('disabled','disabled');
		
		if(action && recordid){
			$.ajax({
				type: 'POST',
				url: 'ajax/applypumpmedicationchanges?id=<?php echo $_REQUEST['id']; ?>',
				data: {
					action: action,
					recordid: recordid,
					alt_id: alt_id
				},
				success:function(data){
					location.href = "<?php echo APP_BASE ?>patientmedication/overview?flg=suc&id=<?php echo $_REQUEST['id']; ?>";
				},
				error:function(){
					ajax_done = 1;
					// failed request; give feedback to user
				}
			});
		}
	});

	
	/* ######################## MEDICATION DELETED ######################## */
		$(document).off('click',".renew_ajx").on('click',".renew_ajx", function(){
			var trid = $(this).closest('tr').attr('id');
			var drug_id = $(this).attr('rel');
			var pid = "<?php echo $_GET['id']; ?>";
			renew_medication(drug_id,pid,trid);
		});
		
		function renew_medication(mid,pid,trid)
		{
			var allow_changes = "<?php echo $this->allow_changes;?>"
			var approval_rights = "<?php echo $this->approval_rights;?>"
			var acknowledge = "<?php echo $this->acknowledge;?>"
					
			if(mid>0){
				$.ajax({
					url:'patient/patientmedicationchange?mid='+mid+'&id='+pid+'&act=rnw&noredir=1',
					async: false						
				});
			}
			
			location.href = "<?php echo APP_BASE ?>patientmedication/overview?flg=suc&id=<?php echo $_REQUEST['id']; ?>";
		}
	/* ######################## MEDICATION SHARED DATA ######################## */
		$('#shared_meds').live('click', function(e){
		e.preventDefault();
		  var drugplan_id = $(this).data("drugplan_id");
		  var medication_type = $(this).data("medication_type");
		  
		$('.medication_shared_meds').load('<?php  echo APP_BASE."patientmedication/shared?id=".$_REQUEST['id'].""; ?>', function() {
			$('.medication_shared_meds').dialog('open');
		});
	});
	
	
	$('#shared_meds_cron').live('click', function(e){
		e.preventDefault();
		var url = '<?php echo APP_BASE; ?>cron/runsharemedications';
		xhr = $.ajax({
			url : url,
			success : function(response) {
				//console.log("cron");
				alert("Completed!")
			}
		});

	});


	$( ".medication_shared_meds" ).dialog({
		autoOpen: false,
		resizable: false,
		title: "<?php echo $this->translate('medication_shared_meds')?>",
		height: 550,
		width: 900,
		modal: true,
		open: function() {
			$(this).dialog( "option", "buttons", 
					[ 
						{
							text: "<?php echo $this->translate('save')?>", 
							"class": 'cancelButtonClass',
							click: function() {
// 								$( this ).dialog( "close" );
								$('#share_medications').submit();
								//console.log("save changes");
							}
						},
						{
							text: "<?php echo $this->translate('cancel')?>", 
							"class": 'cancelButtonClass',
							click: function() {
								$( this ).dialog( "close" );
							}
						}
				]
			);
		},
		close: function() {
			
		}

	});
	
	/* ######################## MEDICATION HISTORY ######################## */
		$('.show_medication_info').live('click', function(e){
		e.preventDefault();
		  var drugplan_id = $(this).data("drugplan_id");
		  var medication_type = $(this).data("medication_type");
		  
		$('.medication_history').load('<?php  echo APP_BASE."patientmedication/history?id=".$_REQUEST['id']."&drugplan_id='+drugplan_id+'"; ?>', function() {
			$('.medication_history').dialog('open');
		});
//		$('.medication_history').load('<?php  echo APP_BASE."patientnew/medicationhistory?id=".$_REQUEST['id']."&drugplan_id='+drugplan_id+'"; ?>', function() {
// 			$('.medication_history').dialog('open');
// 		});
	});


	$( ".medication_history" ).dialog({
		autoOpen: false,
		resizable: false,
		title: "<?php echo $this->translate('medication history')?>",
		height: 600,
		width: 850,
		modal: true,
		open: function() {
			$(this).dialog( "option", "buttons", 
					[ 
						{
							text: "<?php echo $this->translate('cancel')?>", 
							"class": 'cancelButtonClass',
							click: function() {
								$( this ).dialog( "close" );
							}
						},
				]
			);
		},
		close: function() {
			
		}

	});
	/* ######################## MEDICATION SETS  ######################## */
	$('.MedicSetButton').live('click', function(e){
		e.preventDefault();
		
		var pat = "<?php echo $_REQUEST['id'];?>";
		var set_type = $(this).data("med_block");
		var url = appbase+'patientmedication/sets?id='+pat+'&set_type='+set_type;
		xhr = $.ajax({
			url : url,
			success : function(response) {
				$('.medication_sets').html(response);
				$('.medication_sets').dialog('open');
			}
		});
	});
	
	
	
	$( ".medication_sets" ).dialog({
		autoOpen: false,
		resizable: false,
		title: "<?php echo $this->translate('2247 - Medication sets ')?>",
		height: 550,
		width: 900,
		modal: true,
		open: function() {
			//		<!-- ISPC-2329 pct.l) Lore 23.08.2019  -->
			if($('#nosets').val() == "1"){
				$(this).dialog( "option", "buttons", 
						[ 
						 
							{
								text: "<?php echo $this->translate('cancel')?>", 
								"class": 'cancelButtonClass',
								click: function() {
									$( this ).dialog( "close" );
								}
							}
					]
				);	
			} else{
			$(this).dialog( "option", "buttons", 
					[ 
						{   
							text: "<?php echo $this->translate('save')?>", 
							"class": 'cancelButtonClass disabledButtonClass',
							click: function() {
    // 								$( this ).dialog( "close" );
    								$('#add_set_medication').submit();
    								//console.log("save changes");
							}
						},
						{
							text: "<?php echo $this->translate('cancel')?>", 
							"class": 'cancelButtonClass',
							click: function() {
								$( this ).dialog( "close" );
							}
						}
				]
			);
		}
		},
		close: function() {
			
		}

	});
 
	
	$('.all_print_medication').each(function(){
		if($(this).is(':checked')){
			$('#select_all').attr('checked', true)
		}
	});
	
	$('#select_all').live('click', function(){
		
		if($(this).is(':checked')){
			$('.all_print_medication').each(function(){
				$(this).attr('checked', true)
			});
		} else {
			$('.all_print_medication').each(function(){
				$(this).attr('checked', false)
			});
		}
	});

	//ISPC-2664 Carmen 28.09.2020
	var no_change = false;
	var input_element_old_value_weight = '';
	var input_element_old_value_height = '';
	$('input', '.vital_signs').on('change', function (){
		
		if($(this).val().indexOf(".") > 0)
		{
			if($(this).attr('id') == "last_weight")
			{
				if(input_element_old_value_weight == '')
				{
					input_element_old_value_weight = this.defaultValue;
				}
				
				$(this).val(parseFloat($(this).val()).toFixed(3));
			}
			else
			{
				if(input_element_old_value_height == '')
				{
					input_element_old_value_height = this.defaultValue;
				}
				
				$(this).val(parseFloat($(this).val()).toFixed(2));
			}
		}
		else if($(this).val().indexOf(",") > 0)
		{
			if($(this).attr('id') == "last_weight")
			{
				if(input_element_old_value_weight == '')
				{
					input_element_old_value_weight = this.defaultValue;
				}
				
				$(this).val(parseFloat($(this).val().replace(/,/g, '.')).toFixed(3));
			}
			else
			{
				if(input_element_old_value_height == '')
				{
					input_element_old_value_height = this.defaultValue;
				}
				
				$(this).val(parseFloat($(this).val().replace(/,/g, '.')).toFixed(2));
			}
		}
		
		if($(this).val() == 0.000) {$(this).val(""); no_change = true; alert(translate('The input cant be empty'))};
	});

	$('input', '.vital_signs').on('keydown', function (e) {
		// Allow: backspace, delete, tab, escape, enter and .
		if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190, 188]) !== -1 ||
			// Allow: home, end, left, right
			(e.keyCode >= 35 && e.keyCode <= 39)) 
		{
			// let it happen, don't do anything
			return;
		}

		
		// Ensure that it is a number and stop the keypress
		if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
			e.preventDefault();
		}
	});
	
	$(document).on('click', '.weight, .height', function() {
		var vital_signs_element = $(this).attr('class');
		var vital_signs_element_value = $(this).closest("tr").find("input").val();
		var confirm_message = translate('do you want to change current item?');
		confirm_message = confirm_message.replace(/\%item/g, translate(vital_signs_element));
		if(!no_change)
		{
		jConfirm(confirm_message, translate('confirm_change_title'), function(r) {
		  	if(r) {
				if(vital_signs_element_value != '') {
					if(vital_signs_element_value.indexOf(",") > 0)
					{
						vital_signs_element_value = vital_signs_element_value.replace(/,/g, '.'); 
					}
					else
					{
						$(this).closest("tr").find("input").val(vital_signs_element_value.replace(/\./g, ','));
					}
					
					$.ajax({
						url : 'ajax/setvitalsignselement',
						type : 'POST',
						data : {
							element: vital_signs_element,
							element_value: vital_signs_element_value,
							ipid: idpd,
						},
						success : function(response) {
								if(vital_signs_element == "weight")
								{
									$(".gewicht").find('span:first').next().text(vital_signs_element_value+' kg');
									$(".weight_date").text(response);
									if($("#last_weight").val() != "" && $("#last_height").val() != "")
									{
										var last_weight = parseFloat($("#last_weight").val());
										var last_height = parseFloat($("#last_height").val());
										var last_body_surface = 0.007184*Math.pow(last_height,0.725)*Math.pow(last_weight, 0.425);
										$("#last_body_surface").val(last_body_surface.toFixed(3));
										input_element_old_value_weight = parseFloat($("#last_weight").val());
									}
								}
								else if(vital_signs_element == "height")
								{
									$(".grobe").find('span:first').next().text(vital_signs_element_value+' cm');
									$(".height_date").text(response);
									if($("#last_weight").val() != "" && $("#last_height").val() != "")
									{
										var last_weight = parseFloat($("#last_weight").val());
										var last_height = parseFloat($("#last_height").val());
										var last_body_surface = 0.007184*Math.pow(last_height,0.725)*Math.pow(last_weight, 0.425);
										$("#last_body_surface").val(last_body_surface.toFixed(3));
										input_element_old_value_height = parseFloat($("#last_height").val());
									}
								}
							}
					});
				}
			}
		});
		}
		else
		{
			if(vital_signs_element == "weight")
			{
				$(this).closest("tr").find("input").val(input_element_old_value_weight);
			}
			else
			{
				$(this).closest("tr").find("input").val(input_element_old_value_height);
			}
			no_change = false;
		}
	});
	//--
	
	 
});/*-- END  $(document).ready ----------- --*/
	
 
</script>
<?php //if($this->force_full_width=="1"):?>
<?php if(1):?>
<style>
 .outer{ 
 	width: 100%!important; 
 } 

 #Wrapper { 
     width: 98%!important; 
 } 

 #MainContent { 
     width: 75%!important; 
}
</style>
<?php endif; ?>
<?php //echo $this->patientinfo ?>
<?php //echo $this->tabmenus ?>
<?php $medication_array = $this->medication?>

<!-- ####################################### Take over buttons  ################################################# -->
<?php if( $this->show_take_over == "1"):?>
<div class="patient_time_scheme">
	<button id="shared_meds"><?php echo $this->translate('take over button')?></button>
	<!--  
	
	<button id="shared_meds_cron"><?php echo $this->translate('DEV ONLY - get shared meds for modal -')?></button>
	 
	 -->
</div>
<?php endif;?>
 
<!-- ####################################### Vital Signs - ISPC-2664 Carmen  ################################################# -->
<?php if($this->ModulePrivileges[239] == true):?>
<div>
	<table class="vital_signs" style="width:22%;" border="0">
		<tr>
			<td style="width: 25%; padding: 3px; border-top: 1px solid rgba(159,159,159,0.25); border-left: 1px solid rgba(159,159,159,0.25); border-right: 1px solid rgba(159,159,159,0.25);">Gewicht</td><td style="width: 75%; border-top: 1px solid rgba(159,159,159,0.25); border-left: 1px solid rgba(159,159,159,0.25); border-right: 1px solid rgba(159,159,159,0.25);"><input id="last_weight" style="width: 30%; margin-left: 3px" value="<?php echo $this->vital_signs['weight']; ?>" />&nbsp;kg&nbsp;vom&nbsp;<span class="weight_date"><?php echo $this->vital_signs['weight_signs_date']?></span><span class="weight" style="display: block; float:right;" title="<?php echo $this->translate("change weight"); ?>" ><img src="<?php echo RES_FILE_PATH; ?>/images/ok.png" style="margin-right: 5px;"/></span></td>
		</tr>
		<tr>
			<td style="width: 25%; padding: 3px; border-top: 1px solid rgba(159,159,159,0.25); border-left: 1px solid rgba(159,159,159,0.25); border-right: 1px solid rgba(159,159,159,0.25);">Größe</td><td style="width: 75%; border-top: 1px solid rgba(159,159,159,0.25); border-left: 1px solid rgba(159,159,159,0.25); border-right: 1px solid rgba(159,159,159,0.25);"><input id="last_height" style="width: 30%; margin-left: 3px;" value="<?php echo $this->vital_signs['height']; ?>" />&nbsp;cm&nbsp;vom&nbsp;<span class="height_date"><?php echo $this->vital_signs['height_signs_date']?></span><span class="height" style="display: block; float:right;" title="<?php echo $this->translate("change height"); ?>" ><img src="<?php echo RES_FILE_PATH; ?>/images/ok.png" style="margin-right: 5px;"/></span></td>
		</tr>
		<tr>
			<td style="width: 25%; padding: 3px; border-top: 1px solid rgba(159,159,159,0.25); border-left: 1px solid rgba(159,159,159,0.25); border-right: 1px solid rgba(159,159,159,0.25);">KOF</td><td style="width: 75%; border-top: 1px solid rgba(159,159,159,0.25); border-left: 1px solid rgba(159,159,159,0.25); border-right: 1px solid rgba(159,159,159,0.25);"><input id="last_body_surface" class="KOF" disabled="disabled" style="width: 30%; color: #333; margin-left: 3px; border:0px; background: white;" value="<?php echo $this->vital_signs['body_surface'] ?>" />&nbsp;m&sup2;</span>&nbsp;</td>
		</tr>
		<tr>
			<td style="width: 25%; padding: 3px; border-top: 1px solid rgba(159,159,159,0.25); border-left: 1px solid rgba(159,159,159,0.25); border-right: 1px solid rgba(159,159,159,0.25); border-bottom: 1px solid rgba(159,159,159,0.25);">Alter</td><td style="width: 75%; border-top: 1px solid rgba(159,159,159,0.25); border-left: 1px solid rgba(159,159,159,0.25); border-right: 1px solid rgba(159,159,159,0.25); border-bottom: 1px solid rgba(159,159,159,0.25);"><input class="age" disabled="disabled" style="width: 80%; color: #333; margin-left: 3px; border:0px; background: white;" value="<?php echo $this->age; ?>" /></td>
		</tr>
	</table>
</div>
<?php endif; ?>
	
<!-- ####################################### Alergies  ################################################# -->
	<div class="mk-container comment" >
		<h2><?php echo $this->translate('allergies_comment')?>:</h2>
		<div id="" class="comment">
			<span class="editText" id="allergies_pat"><?php if(!empty($this->allergies_comment)):?><?php echo $this->allergies_comment?><?php else: ?><?php echo $this->translate('no alergies'); ?><?php endif;  ?></span>
		</div>
	</div>

<!-- ####################################### Select all  ################################################# 
	<div class="pdf_options" style="padding-bottom:5px;">
		<label>
			<input type="checkbox" id="select_all" class="all_print_medication"/>
			<?php echo $this->translate('Select all for printing')?>
		</label>
	</div>

-->
	
	<div class="cb-container">
	<input type="checkbox" id="select_all" class="all_print_medication" >
	<label for="select_all"><?php echo $this->translate('Select all for printing')?></label>
    </div>
	
	
<!-- ################################################################################################### -->
<!-- ####################################### MEDICATION BLOCKS ######################################### -->
<!-- ################################################################################################### -->

<form action="<?php  echo APP_BASE.'patientmedication/print?id='.$_REQUEST['id'].''; ?>" method="post" name="print_medications" id="print_medications" >

<?php foreach($allowed_medication_types as $k=>$medication_type):?>
	<?php if(in_array($medication_type,$timed_scheduled_medications)):?>

	<div class="mk-container">
	<!-- top -->
	<div class="mk-top">
		<h2><?php echo $this->translate($medication_type." medication title")?> </h2>
		<div class="cb-container print_opt_line">
			<input type="checkbox" value="1" name="print[<?php echo $medication_type;?>][allow]" checked="checked" id="print<?php echo $medication_type;?>" class="all_print_medication" />
			<label for="print<?php echo $medication_type;?>"><?php echo $this->translate('show in pdf');?></label>
		</div>
		
		<div class="right-nav">
			<div class="sorting" onClick="med_Sort(this)" data-sort_type="<?php echo $medication_type;?>">
				<span class="sortby" ><?php  echo $this->translate('Sort by');?> <?php echo  $this->translate('medication_'.$sort_order[$medication_type]['col']);?></span>
				<div class="buttons">
					<input type="button" name="sortup" class="btnSort sortup  <?php if($sort_order[$medication_type]['ord']=='asc'):?> active <?php endif;?>"  onclick="save_sort_option('<?php echo $medication_type;?>','<?php echo $sort_order[$medication_type]['col']?>','asc')" />
					<input type="button" name="sortdown" class="btnSort sortdown <?php if($sort_order[$medication_type]['ord']=='desc'):?> active <?php endif;?> " onclick="save_sort_option('<?php echo $medication_type;?>','<?php echo $sort_order[$medication_type]['col']?>','desc')">
				</div>
			</div>
			
			<div class="sorting-dd" id="sort_<?php echo $medication_type;?>" >
					<div class="sortby">
					<?php  echo $this->translate('SORT BY');?>:
					</div>
					 <?php $sorting_options = array('importance','medication','drug','indication','change_date');?>  
					
					<ul>
					   <?php foreach($sorting_options as $sort_col):?>
						<li <?php if($sort_order[$medication_type]['col']== $sort_col):?> class="active" <?php endif;?> 
						 onclick="save_sort_option('<?php echo $medication_type;?>','<?php echo $sort_col;?>','<?php echo $sort_order[$medication_type]['ord']; ?>')"
						 
						><?php echo $this->translate('medication_'.$sort_col)?></li>
					   <?php endforeach;?>
					</ul>
					
				</div>
			<a href="<?php  echo APP_BASE.'patientmedication/edit?id='.$_REQUEST['id'].'&#'.$medication_type; ?>" class="btnBlue btnEdit"> </a>	
		</div>
		
		<?php if($medication_type == "isbedarfs" && ( count($this->bedarfsdrop) > 0 || count($this->new_medication_sets[$medication_type]) > 0)):?>
		<div class="bedarf_sets">
				<label>Medikamenten Set hinzufügen</label>
				<?php if( count($this->bedarfsdrop) > '1') :?>					
					<?php echo $this->formSelect('bid', $this->bid, array('onChange'=>'togglebutton(this.value)'), $this->bedarfsdrop) ?>
					<input name="insert_bedarf" type="submit" id="MedicButton" value="<?php echo $this->translate('add'); ?>" disabled="disabled" />
				<?php endif;?>
				
			<!-- ISPC - 2247 -->
			<?php if( count($this->new_medication_sets[$medication_type]) > '0') :?>					
				<input name="insert_set" type="button" class="MedicSetButton" value="<?php echo $this->translate('add_set'); ?>"  data-med_block="<?php echo $medication_type; ?> " />			
			<?php endif;?>
		</div>
		<?php endif;?>
		
		<!-- ISPC-2329 pct.k) Lore 23.08.2019  -->
		<?php if($medication_type == "actual" && ( count($this->bedarfsdrop) > 0 || count($this->new_medication_sets[$medication_type]) > 0)):?>
		<div class="bedarf_sets">
			<?php if( count($this->new_medication_sets[$medication_type]) > '0') :?>					
				<input name="insert_set" type="button" class="MedicSetButton" value="<?php echo $this->translate('add_set'); ?>"  data-med_block="<?php echo $medication_type; ?> " />			
			<?php endif;?>
		</div>
		<?php endif;?>

		<!-- ISPC-2329 pct.l) Lore 23.08.2019  -->
		<?php if(($medication_type == "actual" || $medication_type == "isbedarfs" || $medication_type == "iscrisis") && count($this->new_medication_sets[$medication_type]) == 0):?>
		<div class="bedarf_sets">
				<input name="insert_set" type="button" class="MedicSetButton" value="<?php echo $this->translate('add_set'); ?>"  data-med_block="<?php echo $medication_type; ?> " />			
		</div>
		<?php endif;?>	
				
	</div>
	<!-- // top -->
	
	    <?php $colspan_diagno = count($this->dosage_intervals[$medication_type]); ?>
	    <?php 
	       if($medication_type == "actual" || $medication_type == "isivmed"){
    	       $colspan_table = $colspan_diagno + 5; // change colspan according to blocks
	       } else{
    	       $colspan_table = $colspan_diagno + 5; 
	       }
		?>
		<table class="medikation" cellspacing="0" cellpadding="0" border="0">
		<thead>
			<tr>
				<th rowspan="2" colspan="2" class="name">NAME / <span>WIRKSTOFF</span></th>
				<th colspan="<?php echo count($this->dosage_intervals[$medication_type])?>" class="dosierung">DOSIERUNG</th>
				<th rowspan="2">INDIKATION / KOMMENTAR</th>
				<th rowspan="2" colspan="2">LETZTE ÄNDERUNG</th>
			</tr>
			<tr class="time">
				<!--  DOSAGE TABLE HEADER KIDS-->
	 			<?php foreach($this->dosage_intervals[$medication_type] as $k => $di):?>
		 			<th><?php echo $di;?></th>
	 			<?php endforeach;?>
			</tr>
		</thead>
		<tbody>
		<?php 
		foreach($medication_array[$medication_type] as $k =>$med):?>
		
		    <?php
		    $has_ack_class="";

		    if(($this->acknowledge  == "1" && !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :
    		    $has_ack_class = "has_ack";
            endif; 
            ?>
		    <?php 
		    $data_medid= "";  
			if(($this->acknowledge  == "1" && !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :
                $data_medid ='data-medid="'. $med['id'].'"' ;  
			endif; 
            ?> 
            
            
            
            <!--  Check if the medication line - needs multiple rows  -->
            <?php $row_type = "double";?>
            <?php $row_span = ' rowspan="2"';?>
            
        		<?php
        		 $dosage_concentration_line = array();
        		 foreach($this->dosage_intervals[$medication_type] as $k => $dosage_time):?>
				    <?php if (isset($med['dosage'][$dosage_time]) && strlen(trim($med['dosage'][$dosage_time])) > 0 && !empty($med['dosage_concentration'][$dosage_time]) ):?>
					   <?php  $dosage_concentration_line[] =  $med['dosage_concentration'][$dosage_time];?>
					<?php endif;?>
				<?php endforeach;?>
            
            <?php if(empty($med['drug']) && empty($dosage_concentration_line)):?>
                <?php $row_type = " single";?>
                <?php $row_span = '';?>    
            <?php endif;?>
            <!-- end check -->
            
            
            
            
            <tr  class="<?php echo $row_type; ?> <?php if($row_type =="double"): ?>first <?php endif;?> medication_row_<?php echo $med['id']?> <?php echo $has_ack_class;?>" <?php echo $data_medid?>>
                <!--TD: Sort/Importance  -->			
				<td class="sortnum" <?php echo $row_span?> ><span> <?php echo $med['importance']; ?></span></td>
				
                <!--TD: Name  -->
				<td class="name"><?php echo $med['medication'];?></td>
				
                <!--TD: Time dosage  -->				
				<?php foreach($this->dosage_intervals[$medication_type] as $k => $dosage_time):?>
				<td class="dosierung"><?php echo $med['dosage'][$dosage_time];?> <?php if (strlen($med['dosage'][$dosage_time]) > 0):?><?php echo $med['unit'];?><?php endif;?></td>
				<?php endforeach;?>
				
                <!--TD: Indication + Comment  -->								
				<td class="ind-comm" <?php echo $row_span?> >
    				<?php if(!empty($med['indication'])):?>
        				<?php if(strlen($med['indication_color']) > 0 ):?>
        					<div class="indikation" style="color:#<?php echo $med['indication_color'];?>"><span class="circle" style="background:#<?php echo $med['indication_color'];?>"></span><?php echo $med['indication'];?></div>
        					<?php else:?>
           					<div class="indikation" style="color:#000000"><span class="circle" style="background:#000000"></span><?php echo $med['indication'];?></div>
        				<?php endif;?>
    				<?php endif;?>
					<div class="comment extra_padding_left"  id="<?php echo $med['id'];?>_medi_comment" > <?php echo $med['comments'];?> </div>
				</td>
				
                <!--TD: Date+ History  -->				
				<td class="date" <?php echo $row_span?>>
					<input type="button" name="history" class="btnHistory show_medication_info"   data-medication_type="<?php echo $medication_type; ?>" data-drugplan_id="<?php echo $med['id']; ?>">
					<div class="date-cont"><?php echo date('d.m.Y',strtotime($med['medication_change']));?></div>
				</td>
				
                <!--TD: Details-->	
                <!-- 				<td class="details expand_details" <?php echo $row_span?> data-expand_details_id="<?php echo $med['id']?>"></td>
                 ISPC-2329 Lore 16.06.2020 -->			
				<td class="details expand_details" <?php echo $row_span?> data-expand_details_id="<?php echo $med['id']?>"><button class="expand_details_float" name="btn123" ></td>
			</tr>
			
			
			<?php if($row_type =="double"): ?>
			<tr class="<?php echo $row_type; ?> last  last_med_row_<?php echo $med['id']?>  <?php if(($this->acknowledge  == "1" && !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :?> has_ack <?php endif; ?>">
			    
			    <!--TD: Drug-->
				<td class="name wirkstoff"><?php echo $med['drug'];?></td>
				
				
				<?php foreach($this->dosage_intervals[$medication_type] as $k => $dosage_time):?>
			    <!--TD: Dosage interval <?php echo $dosage_time;?>-->
				<td class="dosierung">
				    <?php if (strlen($med['dosage'][$dosage_time]) > 0):?>
					   <?php echo $med['dosage_concentration'][$dosage_time];?>
					<?php endif;?>
				</td>
				<?php endforeach;?>
				
			</tr>
			<?php endif;?>
			
			
			<tr class="medication_details_row_<?php echo $med['id']?> hide_details expandedItem <?php if(($this->acknowledge  == "1" && !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :?> has_ack <?php endif; ?>"  >
			
				<td colspan="<?php echo $colspan_table; ?>">
			
					<h3>APPLIKATIONSWEG, DARREICHUNGSFORM, EINHEIT, ETC</h3>
			
					<div class="ei-content">
			
						<ul class="item">
							<li><span>Konzentration: </span><?php echo $med['concentration_full'];?></li>
							<li><span>Einheit: </span><?php echo $med['unit'];?></li>
						</ul>
						
						<ul class="item">
							<li><span>Darreichungsform: </span><?php echo $med['dosage_form'];?></li>
							<li><span>Applikationsweg: </span><?php echo $med['type'];?></li>
						</ul>
						
						<?php if(($medication_type=="actual" || $medication_type=="isivmed" ) && $allow_normal_scheduled == "1"):?>
    						<?php if($med['has_interval'] == "1"):?>
    						<ul class="item">
    							<li><span>Interval(Tage): </span><?php echo $med['days_interval'];?></li>
    							<?php  if( $med['administration_date'] != "0000-00-00 00:00:00"):?>
        							<li><span>Intervall zuletzt gestartet: </span>
        							<?php echo date("d.m.Y",strtotime($med['administration_date']));?>
        							</li>
        							<?php if($med['allow_restart'] == "1"):?>
        							 <li><button type="button" class="btnBlue interval_restart interval_settings" data-drug_id="<?php echo $med['id'];?>"  data-medication_type = "<?php echo $medication_type;?>" id="<?php echo $medication_type;?>_<?php echo $med['id'];?>_interval_restart" ><?php echo $this->translate("give medication- Restart start interval")?></button></li>
        							<?php endif; ?>
        						<?php else: ?>
        						  <li> 
        						    <button type="button" class="btnBlue interval_start interval_settings"  data-drug_id="<?php echo $med['id'];?>"  data-medication_type = "<?php echo $medication_type;?>"  id="<?php echo $medication_type;?>_<?php echo $med['id'];?>_interval_start" ><?php echo $this->translate("give medication- start interval")?></button>
       						    </li>
       							<?php endif; ?>
    						</ul>
    						<?php endif;?>
						<?php endif;?>
						
						<?php if($medication_type=="isintubated" ):?>
    						<ul class="item">
    							<li><span>Kcal: </span><?php echo $med['kcal'];?></li>
    							<li><span>Volumen: </span><?php echo $med['volume'];?></li>
    							<li><span>Kammerbeutel Info: </span><?php echo $med['packaging_name'];?></li>
    						</ul>
						<?php endif;?>
						
						<?php if(!empty($med['prescribed_by'])):?>
    						<ul class="item">
    							<li>
                                    <span><?php echo $this->translate('medication_prescribed_by');?></span> <?php echo $med['prescribed_by'];?>
    							</li> 
    						</ul>
						<?php endif;?>
						
					</div>
				</td>
			</tr>
			
 <!--  ##############- Online -########################## -->			
		<?php if( $this->acknowledge  == "1" && ! empty($med['on_hold_changes'][$med['id']] )) : ?>
			<?php
			    $online_on_hold_changes = array();
			    $online_on_hold_changes = $med['on_hold_changes'][$med['id']];
				$ack_referance_txt = array();
                $ack_referance_del = array();
                $ack_referance_txt[$med['id']]="";
				$ack_referance_del[$med['id']] = "";

				  if($med['on_hold_changes'][$med['id']]['status'] == "delete")
				  {
					 $ack_referance_txt[$med['id']] = '<span class="blue_text">'.$this->translate("Unapproved changes: ").'</span>';
					 $ack_referance_del[$med['id']] = '<span class="red_text">'.$this->translate("Delete medication: ").'</span>'; 
				  } 
				  else if($med['on_hold_changes'][$med['id']]['status'] == "new")
				  {
					 $ack_referance_txt[$med['id']] = '<span class="green_text">'.$this->translate("Unapproved newly added medication: ").'</span>'; 
					 $ack_referance_del[$med['id']] = ''; 
				  } 
				  else
				  {
					 $ack_referance_txt[$med['id']] = '<span class="blue_text">'.$this->translate("Unapproved changes: ").'</span>'; 
					 $ack_referance_del[$med['id']] = ''; 
				  }
               
 		 
				if($this->approval_rights == "1")
				{
					$app_rights = '<button class="med_approve_rights approvem" data-action="approve" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Approve").'</button><button class="med_approve_rights denym"   data-action="decline" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Decline").'</button>';
					$approve = '<button class="med_approve_rights approvem" data-action="approve" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Approve").'</button>';
					$deny = '<button class="med_approve_rights denym"   data-action="decline" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Decline").'</button>';
	 			} 
				else
				{
					$app_rights = '';
					$approve = '';
					$deny = '';
				}
 		?>

		  <tr class="double extedned_ack  ack_medication_row_<?php echo $med['id']?> " >
		  
                <!-- TD: Sort -->		  
				<td class="sortnum" rowspan="2"> </td>
				
		  
                <!-- TD: Name +  Ack Referance -->		  
				<td class="name">
				    <?php echo $ack_referance_txt[$med['id']];?><br/><br/>
				    <?php echo $online_on_hold_changes['name'];?>
				</td>
				
		  
				<?php foreach($this->dosage_intervals[$medication_type] as $k => $dosage_time):?>
                <!-- TD: Dosage- timeintervals -->		  
				<td class="dosierung"><?php echo $online_on_hold_changes['dosage'][$dosage_time];?> 
				<?php if ($this->show_new_fileds == "1" && strlen($online_on_hold_changes['dosage'][$dosage_time]) > 0):?><?php echo $online_on_hold_changes['unit'];?><?php endif;?></td>
				<?php endforeach;?>
				
		  
                <!-- TD: Indication and Comment -->		  
				<td class="ind-comm" rowspan="2">
    				<?php if(!empty($online_on_hold_changes['indication'])):?>
        				<?php if(strlen( $online_on_hold_changes['indication_color']) > 0):?>
        					<div class="indikation" style="color:#<?php echo $online_on_hold_changes['indication_color'];?>"><span class="circle" style="background:#<?php echo $online_on_hold_changes['indication_color'];?>"></span><?php echo $online_on_hold_changes['indication'];?> </div>
        					<?php else:?>
        					<div class="indikation" style="color:#000000"><span class="circle" style="background:#000000"></span><?php echo  $online_on_hold_changes['indication'];?></div>
        				<?php endif;?>
    				<?php endif;?>
					<div class="comment extra_padding_left"  id="<?php echo $med['id'];?>_medi_comment">
					   <?php echo $online_on_hold_changes['comments'];?>
					</div>
				</td>
				
		  
                <!-- TD: Date -->		  
				<td class="date" rowspan="2">
					<div class="date-cont"><?php echo date('d.m.Y',strtotime($online_on_hold_changes['medication_change_date']));?></div>
				</td>
		  
                <!-- TD: Details -->		  
				<td class="details ack_expand_details" rowspan="2" data-expand_details_id="<?php echo $med['id']?>"></td>
			</tr>
			
			<tr class="double last extedned_ack">
			
                <!-- TD: Drug-->			
				<td class="name wirkstoff"><?php echo $online_on_hold_changes['drug'];?></td>
				
				<?php foreach($this->dosage_intervals[$medication_type] as $k => $dosage_time):?>
                <!-- TD: Doseiges value per interval: -->			
				<td class="dosierung">
				    <?php if ($this->show_new_fileds == "1" && strlen($online_on_hold_changes['dosage'][$dosage_time]) > 0):?>
					   <?php echo $online_on_hold_changes['dosage_concentration'][$dosage_time];?>
					<?php endif;?>
				</td>
				<?php endforeach;?>
			</tr>

			
			<tr class="ack_medication_details_row_<?php echo $med['id']?> hide_details expandedItem extedned_ack" >
			
				<td colspan="10">
			
					<h3>APPLIKATIONSWEG, DARREICHUNGSFORM, EINHEIT, ETC</h3>
			
					<div class="ei-content">
			
						<ul class="item">
							<li><span>Konzentration: </span><?php echo $online_on_hold_changes['concentration'];?></li>
							<li><span>Einheit: </span><?php echo $online_on_hold_changes['unit'];?></li>
						</ul>
						
						<ul class="item">
							<li><span>Darreichungsform: </span><?php echo $online_on_hold_changes['dosage_form'];?></li>
							<li><span>Applikationsweg: </span><?php echo $online_on_hold_changes['type'];?></li>
						</ul>
						
						<?php if( ($medication_type=="actual" || $medication_type=="isivmed") && $allow_normal_scheduled == "1"):?>
    						<?php if($online_on_hold_changes['has_interval'] == "1"):?>
    						<ul class="item">
    							<li><span>Interval(Tage): </span><?php echo $online_on_hold_changes['days_interval'];?></li>
    							<?php  if( $online_on_hold_changes['administration_date'] != "0000-00-00 00:00:00"):?>
        							<li><span>Intervall zuletzt gestartet: </span>
                                        <?php echo date("d.m.Y",strtotime($online_on_hold_changes['administration_date']));?>
        							</li>
       							<?php endif; ?>
    						</ul>
    						<?php endif;?>
						<?php endif;?>
						
						<?php if($medication_type=="isintubated" ):?>
    						<ul class="item">
    							<li><span>Kcal: </span><?php echo $online_on_hold_changes['kcal'];?></li>
    							<li><span>Volumen: </span><?php echo $online_on_hold_changes['volume'];?></li>
    							<li><span>Kammerbeutel Info: </span><?php echo $online_on_hold_changes['packaging_name'];?></li>
    						</ul>
						<?php endif;?>
					
					
						<?php if( !empty($online_on_hold_changes['prescribed_by'])):?>
    						<ul class="item">
    							<li><span><?php echo $this->translate('medication_prescribed_by');?>: </span><?php echo $online_on_hold_changes['prescribed_by'];?></li>
    						</ul>
						<?php endif;?>
					
					
						
						<ul class="item">
                            <li><?php echo $approve; ?></li>
							<li><?php echo $deny; ?></li>
						</ul>
						
					</div>
					
				</td>
				
			</tr>
			
<?php  endif;?>
 <!--  ##############- Online END-########################## -->		
            
            
<!--  ##############- Offline-########################## --> 
    <?php if($this->ModulePrivileges[155] == true && ! empty($med['on_hold_changes_offline'][$med['id']])) : ?>
                    <!-- offline changes moderate -->               
                    <?php         
                    foreach ($med['on_hold_changes_offline'][$med['id']] as $on_hold_changes ) : 
                   
                        $ack_referance_txt = "";
                        $ack_referance_del = "";
                        switch($on_hold_changes['status']) {
                            case 'delete' :
                                $ack_referance_txt = '<span class="blue_text">'.$this->translate("Offline Unapproved changes: ").'</span>';
                                $ack_referance_del = '<span class="red_text">'.$this->translate("Offline Delete medication: ").'</span>';
                            break;

                            case 'new' :
                                $ack_referance_txt = '<span class="green_text">'.$this->translate("Offline Unapproved newly added medication: ").'</span>';
                                $ack_referance_del = '';
                            break;

                            case 'edit' :
                                $ack_referance_txt = '<span class="blue_text">'.$this->translate("Offline Unapproved Edit changes: ").'</span>';
                                $ack_referance_del = '';
                            break;

                            default :
                                $ack_referance_txt = '<span class="blue_text">'.$this->translate("Offline Unapproved changes: ").'</span>';
                                $ack_referance_del = '';
                            break;
                        }


                 
                        if($this->approval_rights == "1")
                        {
                            $app_rights = '<button class="med_approve_rights approvem" data-action="approve" data-recordid="'.$med['id'].'" data-alt_id="'.$on_hold_changes['alt_id'].'">'.$this->translate("Offline Approve").'</button><button class="med_approve_rights denym"   data-action="decline" data-recordid="'.$med['id'].'" data-alt_id="'.$on_hold_changes['alt_id'].'">'.$this->translate("Offline Decline").'</button>';
                            $approve = '<button class="med_approve_rights approvem" data-action="approve" data-recordid="'.$med['id'].'" data-alt_id="'.$on_hold_changes['alt_id'].'">'.$this->translate("Offline Approve").'</button>';
                            $deny = '<button class="med_approve_rights denym"   data-action="decline" data-recordid="'.$med['id'].'" data-alt_id="'.$on_hold_changes['alt_id'].'">'.$this->translate("Offline Decline").'</button>';
                        } 
                        else
                        {
                            $app_rights = '';
                            $approve = '';
                            $deny = '';
                        }
                ?>
               
            <tr class="double extedned_ack  offline_ack_medication_row_<?php echo $med['id']?> " >

                <!-- TD: Sort  --> 
				<td class="sortnum" rowspan="2"> </td>

                <!-- TD: Name  --> 
				<td class="name">
				    <?php echo $ack_referance_txt;?><br/><br/>
				    <?php echo $on_hold_changes['name'];?>
				</td>
				
				<?php foreach($this->dosage_intervals[$medication_type] as $k => $dosage_time):?>
                <!-- TD:Dosage per intervals  --> 
				<td class="dosierung"><?php echo $on_hold_changes['dosage'][$dosage_time];?> 
				<?php if ($this->show_new_fileds == "1" && strlen($on_hold_changes['dosage'][$dosage_time]) > 0):?><?php echo $on_hold_changes['unit'];?><?php endif;?></td>
				<?php endforeach;?>
				

                <!-- TD:Indication comment  --> 
				<td class="ind-comm" rowspan="2">
    				<?php if(!empty($on_hold_changes['indication'])):?>
        				<?php if(strlen( $on_hold_changes['indication_color']) > 0):?>
        					<div class="indikation" style="color:#<?php echo $on_hold_changes['indication_color'];?>"><span class="circle" style="background:#<?php echo $on_hold_changes['indication_color'];?>"></span><?php echo $on_hold_changes['indication'];?> </div>
        					<?php else:?>
        					<div class="indikation" style="color:#000000"><span class="circle" style="background:#000000"></span><?php echo  $on_hold_changes['indication'];?></div>
        				<?php endif;?>
    				<?php endif;?>
					<div class="comment extra_padding_left"  id="<?php echo $med['id'];?>_medi_comment">
					   <?php echo $on_hold_changes['comments'];?>
					</div>
				</td>
				

                <!-- TD: Date  --> 
				<td class="date" rowspan="2">
					<div class="date-cont"><?php echo date('d.m.Y',strtotime($on_hold_changes['medication_change_date']));?></div>
				</td>

                <!-- TD: Details--> 
				<td class="details offline_ack_expand_details" rowspan="2" data-expand_details_id="<?php echo $med['id']?>"></td>
			</tr>
			
			<tr class="double last extedned_ack">

                <!-- TD: Drug--> 
				<td class="name wirkstoff"><?php echo $on_hold_changes['drug'];?></td>

				
				<?php foreach($this->dosage_intervals[$medication_type] as $k => $dosage_time):?>

                <!-- TD: Dosage--> 
				<td class="dosierung">
				    <?php if ($this->show_new_fileds == "1" && strlen($on_hold_changes['dosage'][$dosage_time]) > 0):?>
					   <?php echo $on_hold_changes['dosage_concentration'][$dosage_time];?>
					<?php endif;?>
				</td>
				<?php endforeach;?>
			</tr>
			
			<tr class="offline_ack_medication_details_row_<?php echo $med['id']?> hide_details expandedItem extedned_ack" >
			
				<td colspan="10">
			
					<h3>APPLIKATIONSWEG, DARREICHUNGSFORM, EINHEIT, ETC</h3>
			
					<div class="ei-content">
			
						<ul class="item">
							<li><span>Konzentration: </span><?php echo $on_hold_changes['concentration'];?></li>
							<li><span>Einheit: </span><?php echo $on_hold_changes['unit'];?></li>
						</ul>
						
						<ul class="item">
							<li><span>Darreichungsform: </span><?php echo $on_hold_changes['dosage_form'];?></li>
							<li><span>Applikationsweg: </span><?php echo $on_hold_changes['type'];?></li>
						</ul>
						
						<?php if( ($medication_type=="actual" || $medication_type=="isivmed") && $allow_normal_scheduled == "1"):?>
    						<?php if($on_hold_changes['has_interval'] == "1"):?>
    						<ul class="item">
    							<li><span>Interval(Tage): </span><?php echo $on_hold_changes['days_interval'];?></li>
    							<?php  if( $on_hold_changes['administration_date'] != "0000-00-00 00:00:00"):?>
        							<li><span>Intervall zuletzt gestartet: </span>
        							<?php echo date("d.m.Y",strtotime($on_hold_changes['administration_date']));?>
        							</li>
        							<?php if($med['allow_restart'] == "1"):?>
        							 <li><button type="button" class="btnBlue interval_restart interval_settings" data-drug_id="<?php echo $med['id'];?>"  data-medication_type = "<?php echo $medication_type;?>" id="<?php echo $medication_type;?>_<?php echo $med['id'];?>_interval_restart" ><?php echo $this->translate("give medication- Restart start interval")?></button></li>
        							<?php endif; ?>
        						<?php else: ?>
        						  <li> 
        						    <button type="button" class="btnBlue interval_start interval_settings"  data-drug_id="<?php echo $med['id'];?>"  data-medication_type = "<?php echo $medication_type;?>"  id="<?php echo $medication_type;?>_<?php echo $med['id'];?>_interval_start" ><?php echo $this->translate("give medication- start interval")?></button>
       						    </li>
       							<?php endif; ?>
    						</ul>
    						<?php endif;?>
						<?php endif;?>
						
												
						<?php if($medication_type=="isintubated" ):?>
    						<ul class="item">
    							<li><span>Kcal: </span><?php echo $on_hold_changes['kcal'];?></li>
    							<li><span>Volumen: </span><?php echo $on_hold_changes['volume'];?></li>
    							<li><span>Kammerbeutel Info: </span><?php echo $on_hold_changes['packaging_name'];?></li>
    						</ul>
						<?php endif;?>
						
						<ul class="item">
							<li><?php echo $approve; ?></li>
							<li><?php echo $deny; ?></li>
						</ul>
			
					</div>
					
				</td>
				
			</tr>
			
            <?php endforeach; ?>
        <?php endif;?>
<!--  ##############- Offline END -########################## -->              
			
		  <tr class="separator">
				<td colspan="<?php echo $colspan_table?>"> </td>
			</tr>
		<?php endforeach;?>
		
		</tbody>
	</table>
	
</div>	
	
	<!-- NO TIME PERIOD  -->
	
	<?php elseif(!in_array($medication_type,$timed_scheduled_medications) && !in_array($medication_type,array('isschmerzpumpe','treatment_care','scheduled'))): ?>
	
	<div class="mk-container">
	
	<!-- top -->
	<div class="mk-top">
		<h2><?php echo $this->translate($medication_type." medication title")?> </h2>
		<div class="cb-container print_opt_line">
			<input type="checkbox" value="1" name="print[<?php echo $medication_type;?>][allow]" checked="checked" id="print<?php echo $medication_type;?>" class="all_print_medication" />
			<label for="print<?php echo $medication_type;?>"><?php echo $this->translate('show in pdf');?></label>
		</div>
		
				<div class="right-nav">
			<div class="sorting" onClick="med_Sort(this)" data-sort_type="<?php echo $medication_type;?>">
				<span class="sortby" ><?php  echo $this->translate('Sort by');?> <?php echo  $this->translate('medication_'.$sort_order[$medication_type]['col']);?></span>
				<div class="buttons">
					<input type="button" name="sortup" class="btnSort sortup  <?php if($sort_order[$medication_type]['ord']=='asc'):?> active <?php endif;?>"  onclick="save_sort_option('<?php echo $medication_type;?>','<?php echo $sort_order[$medication_type]['col']?>','asc')" />
					<input type="button" name="sortdown" class="btnSort sortdown <?php if($sort_order[$medication_type]['ord']=='desc'):?> active <?php endif;?> " onclick="save_sort_option('<?php echo $medication_type;?>','<?php echo $sort_order[$medication_type]['col']?>','desc')">
				</div>
			</div>
			
			<div class="sorting-dd" id="sort_<?php echo $medication_type;?>" >
					<div class="sortby">
					<?php  echo $this->translate('SORT BY');?>:
					</div>
					 <?php $sorting_options = array('importance','medication','drug','indication','change_date','escalation');?>  
					
					<ul>
					   <?php foreach($sorting_options as $sort_col):?>
						<li <?php if($sort_order[$medication_type]['col']== $sort_col):?> class="active" <?php endif;?> 
						 onclick="save_sort_option('<?php echo $medication_type;?>','<?php echo $sort_col;?>','<?php echo $sort_order[$medication_type]['ord']; ?>')"
						 
						><?php echo $this->translate('medication_'.$sort_col)?></li>
					   <?php endforeach;?>
					</ul>
					
				</div>
			<a href="<?php  echo APP_BASE.'patientmedication/edit?id='.$_REQUEST['id'].'&#'.$medication_type; ?>" class="btnBlue btnEdit"> </a>	
		</div>
		
		
		<?php if($medication_type == "isbedarfs" && ( count($this->bedarfsdrop) > 0 || count($this->new_medication_sets[$medication_type]) > 0)):?>
		<div class="bedarf_sets">
				<label>Medikamenten Set hinzufügen</label>
				<?php if( count($this->bedarfsdrop) > '1') :?>					
					<?php echo $this->formSelect('bid', $this->bid, array('onChange'=>'togglebutton(this.value)'), $this->bedarfsdrop) ?>
					<input name="insert_bedarf" type="submit" id="MedicButton" value="<?php echo $this->translate('add'); ?>" disabled="disabled" />
				<?php endif;?>
				
			<!-- ISPC - 2247 -->
			<?php if( count($this->new_medication_sets[$medication_type]) > '0') :?>					
				<input name="insert_set" type="button" class="MedicSetButton" value="<?php echo $this->translate('add_set'); ?>"  data-med_block="<?php echo $medication_type; ?> " />			
			<?php endif;?>
		</div>
		<?php endif;?>
				
		<?php if( $medication_type == "iscrisis"  && ( count($this->new_medication_sets[$medication_type]) > 0)):?>
		<div class="bedarf_sets cb-container">
			<!-- ISPC - 2247 -->
			<label>Medikamenten Set hinzufügen</label>
			<input name="insert_set" type="button" class="MedicSetButton  btnBlue" value="<?php echo $this->translate('add_set'); ?>"  data-med_block="<?php echo $medication_type; ?> " />			
		</div>
		<?php endif;?>		
	</div>
	<!-- // top -->
	
		<table class="medikation" cellspacing="0" cellpadding="0" border="0">
		<?php if($medication_type == "iscrisis"  || $medication_type == "isbedarfs" ):?>
	    <?php 
	       $colspan_table = 7; // change colspan according to blocks
		?>
		<thead>
			<tr>
				<th rowspan="2" colspan="2" class="name">NAME / <span>WIRKSTOFF</span></th>
				<th colspan="" class="dosierung">DOSIERUNG / <span>INTERVALL</span></th>
				<th rowspan="2">INDIKATION / KOMMENTAR</th>
				<th rowspan="2" >ESKALATION</span></th>
				<th rowspan="2" >LETZTE ÄNDERUNG</th>
			</tr>
		</thead>
		<?php else:?>
	    <?php 
	       $colspan_table = 6; // change colspan according to blocks
		?>
		<thead>
			<tr>
				<th rowspan="2" colspan="2" class="name">NAME / <span>WIRKSTOFF</span></th>
				<th colspan="" class="dosierung">DOSIERUNG</th>
				<th rowspan="2">INDIKATION / KOMMENTAR</th>
				<th rowspan="2" colspan="2">LETZTE ÄNDERUNG</th>
			</tr>
		</thead>
		<?php endif;?>
		<tbody>
		<?php foreach($medication_array[$medication_type] as $k =>$med):?>
		
		    <?php
		    $has_ack_class="";

		    if(($this->acknowledge  == "1" && !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :
    		    $has_ack_class = "has_ack";
            endif; 
            ?>
		    <?php 
		    $data_medid= "";  
			if(($this->acknowledge  == "1" && !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :
                $data_medid ='data-medid="'. $med['id'].'"' ;  
			endif; 
            ?> 
            
            <!--  Check if the medication line - needs multiple rows  -->
            <?php $row_type_nt = "double";?>
            <?php $row_span_nt = ' rowspan="2"';?>
            
            <?php if(empty($med['drug']) && empty($med['dosage_interval'])):?>
                <?php $row_type_nt = " single";?>
                <?php $row_span_nt = '';?>    
            <?php endif;?>
            <!-- end check -->
            
            

            <tr  class="<?php echo $row_type_nt?> <?php if($row_type_nt == 'double'):?>first <?php endif;?> medication_row_<?php echo $med['id']?> <?php echo $has_ack_class;?>" <?php echo $data_medid?>>

                <!--TD: Sort  -->
				<td class="sortnum" <?php echo $row_span_nt?> ><span> <?php echo $med['importance']; ?></span></td>

                <!--TD: Name  -->
				<td class="name"><?php echo $med['medication'];?></td>
				
                <!--TD: Dosage  -->
				<?php if($medication_type == "iscrisis" || $medication_type == "isbedarfs"):?>
				<td class="dosierung" >
				    <?php echo $med['dosage'];?> 
				    <?php echo $med['unit'];?>
				 </td>
				<?php else:?>
				<td class="dosierung" <?php echo $row_span_nt; ?>>
				    <?php echo $med['dosage'];?> 
				    <?php echo $med['unit'];?> 
				 </td>
				<?php endif;?>
				

                <!--TD: Indication Comment  -->
				<td class="ind-comm" <?php echo $row_span_nt; ?>>
				<?php if(!empty( $med['indication'])):?>
    				<?php if(strlen($med['indication_color']) > 0):?>
    					<div class="indikation" style="color:#<?php echo $med['indication_color'];?>"><span class="circle" style="background:#<?php echo $med['indication_color'];?>"></span><?php echo $med['indication'];?></div>
    					<?php else:?>
    					<div class="indikation" style="color:#000000"><span class="circle" style="background:#000000"></span><?php echo $med['indication'];?></div>
    				<?php endif;?>
				<?php endif;?>
					<div class="comment extra_padding_left"  id="<?php echo $med['id'];?>_medi_comment"><?php echo $med['comments'];?></div>
				</td>


				<?php if($medication_type == "iscrisis" || $medication_type == "isbedarfs"):?>
                <!--TD: Escalation  -->
				<td class="escalation" <?php echo $row_span_nt; ?>>
					<div><?php echo $med['escalation']; ?></div>
				</td>
				<?php endif;?>

                <!--TD: Date  -->
				<td class="date" <?php echo $row_span_nt; ?>>
					<input type="button" name="history" class="btnHistory show_medication_info"   data-medication_type="<?php echo $medication_type; ?>" data-drugplan_id="<?php echo $med['id']; ?>">
					<div class="date-cont"><?php echo date('d.m.Y',strtotime($med['medication_change']));?></div>
				</td>

                <!--TD: Details  -->
                <!-- 				<td class="details expand_details" <?php echo $row_span_nt; ?> data-expand_details_id="<?php echo $med['id']?>"></td>
                ISPC-2329 Lore 16.06.2020 -->
				<td class="details expand_details" <?php echo $row_span_nt; ?> data-expand_details_id="<?php echo $med['id']?>"><button class="expand_details_float" name="btn123" ></td>
			</tr>
			
			<?php if( $row_type_nt == 'double'):?>
			<tr class="<?php echo $row_type_nt?> last last_med_row_<?php echo $med['id']?>  <?php if(($this->acknowledge  == "1" && !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :?> has_ack <?php endif; ?>">
			
                <!--TD: Drug  -->
				<td class="name wirkstoff"><?php echo $med['drug'];?> </td>
				
				<?php if($medication_type == "iscrisis" || $medication_type == "isbedarfs"):?>
                <!--TD: Dosage Interval -->
				<td class="dosierung"><?php echo $med['dosage_interval'];?> </td>
				<?php endif;?>
			</tr>
			<?php endif;?>
			
			<tr class="medication_details_row_<?php echo $med['id']?> hide_details expandedItem <?php if(($this->acknowledge  == "1" && !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :?> has_ack <?php endif; ?>"  >

                <td colspan="<?php echo $colspan_table;?>">
			
					<h3>APPLIKATIONSWEG, DARREICHUNGSFORM, EINHEIT, ETC</h3>
				
					<div class="ei-content">
						
						<ul class="item">
							<li><span>Konzentration: </span><?php echo $med['concentration_full'];?></li>
							<li><span>Einheit: </span><?php echo $med['unit'];?></li>
						</ul>
						
						<ul class="item">
							<li><span>Darreichungsform: </span><?php echo $med['dosage_form'];?></li>
							<li><span>Applikationsweg: </span><?php echo $med['type'];?></li>
						</ul>
						
						<?php if( ($medication_type=="actual" || $medication_type=="isivmed") && $allow_normal_scheduled == "1"):?>
    						<?php if($med['has_interval'] == "1"):?>
    						<ul class="item">
    							<li><span>Interval(Tage): </span><?php echo $med['days_interval'];?></li>
    							<?php  if( $med['administration_date'] != "0000-00-00 00:00:00"):?>
        							<li><span>Intervall zuletzt gestartet: </span>
        							<?php echo date("d.m.Y",strtotime($med['administration_date']));?>
        							</li>
        							<?php if($med['allow_restart'] == "1"):?>
        							 <li><button type="button" class="btnBlue interval_restart interval_settings" data-drug_id="<?php echo $med['id'];?>"  data-medication_type = "<?php echo $medication_type;?>" id="<?php echo $medication_type;?>_<?php echo $med['id'];?>_interval_restart" ><?php echo $this->translate("give medication- Restart start interval")?></button></li>
        							<?php endif; ?>
        						<?php else: ?>
        						  <li> 
        						    <button type="button" class="btnBlue interval_start interval_settings"  data-drug_id="<?php echo $med['id'];?>"  data-medication_type = "<?php echo $medication_type;?>"  id="<?php echo $medication_type;?>_<?php echo $med['id'];?>_interval_start" ><?php echo $this->translate("give medication- start interval")?></button>
       						    </li>
       							<?php endif; ?>
    						</ul>
    						<?php endif;?>
						<?php endif;?>
						
					</div>
				</td>
			</tr>
			
<!--  ##############- ONLINE -########################## --> 			
		<?php if( $this->acknowledge  == "1" && ! empty($med['on_hold_changes'][$med['id']] )) : ?>
			<?php 
			
			    $online_on_hold_changes = array();
			    $online_on_hold_changes = $med['on_hold_changes'][$med['id']]; 
				$ack_referance_txt = array();
                $ack_referance_del = array();
                $ack_referance_txt[$med['id']]="";
				$ack_referance_del[$med['id']] = "";

				  if($med['on_hold_changes'][$med['id']]['status'] == "delete")
				  {
					 $ack_referance_txt[$med['id']] = '<span class="blue_text">'.$this->translate("Unapproved changes: ").'</span>';
					 $ack_referance_del[$med['id']] = '<span class="red_text">'.$this->translate("Delete medication: ").'</span>'; 
				  } 
				  else if($med['on_hold_changes'][$med['id']]['status'] == "new")
				  {
					 $ack_referance_txt[$med['id']] = '<span class="green_text">'.$this->translate("Unapproved newly added medication: ").'</span>'; 
					 $ack_referance_del[$med['id']] = ''; 
				  } 
				  else
				  {
					 $ack_referance_txt[$med['id']] = '<span class="blue_text">'.$this->translate("Unapproved changes: ").'</span>'; 
					 $ack_referance_del[$med['id']] = ''; 
				  }
               
 		 
				if($this->approval_rights == "1")
				{
					$app_rights = '<button class="med_approve_rights approvem" data-action="approve" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Approve").'</button><button class="med_approve_rights denym"   data-action="decline" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Decline").'</button>';
					$approve = '<button class="med_approve_rights approvem" data-action="approve" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Approve").'</button>';
					$deny = '<button class="med_approve_rights denym"   data-action="decline" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Decline").'</button>';
	 			} 
				else
				{
					$app_rights = '';
					$approve = '';
					$deny = '';
				}
 		?>
 
		  <tr class="double extedned_ack  ack_medication_row_<?php echo $med['id']?> " >
		  
		        <!-- TD:Sort -->  
				<td class="sortnum" rowspan="2"> </td>
				
				<!-- TD: Name -->
				<td class="name">
				    <?php echo $ack_referance_txt[$med['id']];?><br/><br/>
				    <?php echo $online_on_hold_changes['name'];?>
				</td>
				<!-- TD: Dosage -->
				<td class="dosierung" rowspan="2">
				    <?php echo $online_on_hold_changes['dosage'];?> 
				    <?php if ($this->show_new_fileds == "1" && strlen($online_on_hold_changes['dosage']) > 0):?><?php echo $online_on_hold_changes['unit'];?><?php endif;?>
				</td>
				
				<!-- TD: Indication -->
				<td class="ind-comm" rowspan="2">
    				<?php if(!empty($online_on_hold_changes['indication'])):?>
        				<?php if(strlen($online_on_hold_changes['indication_color']) > 0):?>
        					<div class="indikation" style="color:#<?php echo $online_on_hold_changes['indication_color'];?>"><span class="circle" style="background:#<?php echo $online_on_hold_changes['indication_color'];?>"></span><?php echo $online_on_hold_changes['indication'];?> </div>
        					<?php else:?>
        					<div class="indikation" style="color:#000000"><span class="circle" style="background:#000000"></span><?php echo $online_on_hold_changes['indication'];?></div>
        				<?php endif;?>
    				<?php endif;?>
					<div class="comment extra_padding_left"  id="<?php echo $med['id'];?>_medi_comment"><?php echo $online_on_hold_changes['comments'];?></div>
				</td>
				
				<!-- TD: Escalation -->
				<?php if($medication_type == "iscrisis" || $medication_type == "isbedarfs"):?>
				<td class="escalation" rowspan="2">
					<div class="escalation"><?php echo $online_on_hold_changes['escalation'];?></div>
				</td>
				<?php endif;?>
				
				<!-- TD: Date -->
				<td class="date" rowspan="2">
					<div class="date-cont"><?php echo date('d.m.Y',strtotime($online_on_hold_changes['medication_change_date']));?></div>
				</td>
				
				<!-- TD: Details -->
				<td class="details ack_expand_details" rowspan="2" data-expand_details_id="<?php echo $med['id']?>"></td>
			</tr>
			
			<tr class="double last extedned_ack">
			    <!-- TD: Drug -->
				<td class="name wirkstoff"><?php echo $online_on_hold_changes['drug'];?></td>
			</tr>
			
			
			<tr class="ack_medication_details_row_<?php echo $med['id']?> hide_details expandedItem extedned_ack" >
			
				<td colspan="<?php echo $colspan_table; ?>">
					
					<h3>APPLIKATIONSWEG, DARREICHUNGSFORM, EINHEIT, ETC</h3>
					
					<div class="ei-content">
					
						<ul class="item">
							<li><span>Konzentration: </span><?php echo $online_on_hold_changes['concentration'];?></li>
							<li><span>Einheit: </span><?php echo $online_on_hold_changes['unit'];?></li>
						</ul>
						
						<ul class="item">
							<li><span>Darreichungsform: </span><?php echo $online_on_hold_changes['dosage_form'];?></li>
							<li><span>Applikationsweg: </span><?php echo $online_on_hold_changes['type'];?></li>
						</ul>
						
						<?php if( ($medication_type=="actual" || $medication_type=="isivmed") && $allow_normal_scheduled == "1"):?>
    						<?php if($online_on_hold_changes['has_interval'] == "1"):?>
    						<ul class="item">
    							<li><span>Interval(Tage): </span><?php echo $online_on_hold_changes['days_interval'];?></li>
    							<?php  if( $online_on_hold_changes['administration_date'] != "0000-00-00 00:00:00"):?>
        							<li><span>Intervall zuletzt gestartet: </span>
        							 <?php echo date("d.m.Y",strtotime($online_on_hold_changes['administration_date']));?>
        							</li>
       							<?php endif; ?>
    						</ul>
    						<?php endif;?>
						<?php endif;?>
						
						<ul class="item">
		 				    <li><?php echo $approve; ?></li>
                            <li><?php echo $deny; ?></li>
						</ul>
					</div>
					
				</td>
				
			</tr>
            <?php  endif;?>
<!--  ##############- ONLINE END -########################## -->
            			
<!--  ##############- OFFLINE -########################## -->			
    <?php if($this->ModulePrivileges[155] == true && ! empty($med['on_hold_changes_offline'][$med['id']])) : ?>
    <!-- offline changes moderate -->               
                    <?php   
                    $on_hold_changes = array();
                    foreach ($med['on_hold_changes_offline'][$med['id']] as $on_hold_changes ) : 
                   
                        $ack_referance_txt = "";
                        $ack_referance_del = "";
                        switch($on_hold_changes['status']) {
                            case 'delete' :
                                $ack_referance_txt = '<span class="blue_text">'.$this->translate("Offline Unapproved changes: ").'</span>';
                                $ack_referance_del = '<span class="red_text">'.$this->translate("Offline Delete medication: ").'</span>';
                            break;

                            case 'new' :
                                $ack_referance_txt = '<span class="green_text">'.$this->translate("Offline Unapproved newly added medication: ").'</span>';
                                $ack_referance_del = '';
                            break;

                            case 'edit' :
                                $ack_referance_txt = '<span class="blue_text">'.$this->translate("Offline Unapproved Edit changes: ").'</span>';
                                $ack_referance_del = '';
                            break;

                            default :
                                $ack_referance_txt = '<span class="blue_text">'.$this->translate("Offline Unapproved changes: ").'</span>';
                                $ack_referance_del = '';
                            break;
                        }


                 
                        if($this->approval_rights == "1")
                        {
                            $app_rights = '<button class="med_approve_rights approvem" data-action="approve" data-recordid="'.$med['id'].'" data-alt_id="'.$on_hold_changes['alt_id'].'">'.$this->translate("Offline Approve").'</button><button class="med_approve_rights denym"   data-action="decline" data-recordid="'.$med['id'].'" data-alt_id="'.$on_hold_changes['alt_id'].'">'.$this->translate("Offline Decline").'</button>';
                            $approve = '<button class="med_approve_rights approvem" data-action="approve" data-recordid="'.$med['id'].'" data-alt_id="'.$on_hold_changes['alt_id'].'">'.$this->translate("Offline Approve").'</button>';
                            $deny = '<button class="med_approve_rights denym"   data-action="decline" data-recordid="'.$med['id'].'" data-alt_id="'.$on_hold_changes['alt_id'].'">'.$this->translate("Offline Decline").'</button>';
                        } 
                        else
                        {
                            $app_rights = '';
                            $approve = '';
                            $deny = '';
                        }

                ?>
                
                
                
		  <tr class="double extedned_ack  offline_ack_medication_row_<?php echo $med['id']?> " >

		        <!-- TD: SORT  -->
				<td class="sortnum" rowspan="2"> </td>

		        <!-- TD: Name  -->
				<td class="name">
				    <?php echo $ack_referance_txt;?><br/><br/>
				    <?php echo $on_hold_changes['name'];?>
				</td>
				
		        <!-- TD: Dosage  -->
				<td class="dosierung" rowspan="2">
				    <?php echo $on_hold_changes['dosage'];?> 
				    <?php if ($this->show_new_fileds == "1" && strlen($on_hold_changes['dosage']) > 0):?><?php echo $on_hold_changes['unit'];?><?php endif;?>
				</td>
				
		        <!-- TD: Indication +Comment  -->
				<td class="ind-comm" rowspan="2">
				<?php if(!empty($on_hold_changes['indication'])):?>
    				<?php if(strlen($on_hold_changes['indication_color']) > 0):?>
    					<div class="indikation" style="color:#<?php echo $on_hold_changes['indication_color'];?>"><span class="circle" style="background:#<?php echo $on_hold_changes['indication_color'];?>"></span><?php echo $on_hold_changes['indication'];?> </div>
    					<?php else:?>
    					<div class="indikation" style="color:#000000"><span class="circle" style="background:#000000"></span><?php echo $on_hold_changes['indication'];?></div>
    				<?php endif;?>
				<?php endif;?>
					<div class="comment extra_padding_left"  id="<?php echo $med['id'];?>_medi_comment"><?php echo $on_hold_changes['comments'];?></div>
				</td>
				
				<?php if($medication_type == "iscrisis" || $medication_type == "isbedarfs"):?>
		        <!-- TD: Escalation -->
				<td class="escalation" rowspan="2">
					<div class="escalation"><?php echo $on_hold_changes['escalation'];?></div>
				</td>
				<?php endif;?>
				
				
		        <!-- TD: Date -->
				<td class="date" rowspan="2">
					<input type="button" name="history" class="btnHistory show_medication_info"   data-medication_type="<?php echo $medication_type; ?>" data-drugplan_id="<?php echo $med['id']; ?>">
					<div class="date-cont"><?php echo date('d.m.Y',strtotime($on_hold_changes['medication_change_date']));?></div>
				</td>
				
		        <!-- TD: Details -->
				<td class="details offline_ack_expand_details" rowspan="2" data-expand_details_id="<?php echo $med['id']?>"></td>
			</tr>
			
			<tr class="double last extedned_ack">
		        <!-- TD: Drug -->
				<td class="name wirkstoff"><?php echo $on_hold_changes['drug'];?></td>
			</tr>
			
			<tr class="offline_ack_medication_details_row_<?php echo $med['id']?> hide_details expandedItem extedned_ack" >
				
				<td colspan="<?php echo $colspan_table; ?>">
					
					<h3>APPLIKATIONSWEG, DARREICHUNGSFORM, EINHEIT, ETC</h3>
					
					<div class="ei-content">
					
						<ul class="item">
							<li><span>Konzentration: </span><?php echo $on_hold_changes['concentration'];?></li>
							<li><span>Einheit: </span><?php echo $on_hold_changes['unit'];?></li>
						</ul>
						
						<ul class="item">
							<li><span>Darreichungsform: </span><?php echo $on_hold_changes['dosage_form'];?></li>
							<li><span>Applikationsweg: </span><?php echo $on_hold_changes['type'];?></li>
						</ul>
						
						<?php if( ($medication_type=="actual" || $medication_type=="isivmed") && $allow_normal_scheduled == "1"):?>
    						<?php if($on_hold_changes['has_interval'] == "1"):?>
    						<ul class="item">
    							<li><span>Interval(Tage): </span><?php echo $on_hold_changes['days_interval'];?></li>
    							<?php  if( $on_hold_changes['administration_date'] != "0000-00-00 00:00:00"):?>
        							<li><span>Intervall zuletzt gestartet: </span>
        							<?php echo date("d.m.Y",strtotime($on_hold_changes['administration_date']));?>
        							</li>
        						<?php else: ?>
        		 
       							<?php endif; ?>
    						</ul>
    						<?php endif;?>
						<?php endif;?>
						
						<ul class="item ack_buttons">
							<li><?php echo $approve; ?></li>
							<li><?php echo $deny; ?></li>
						</ul>
					</div>
				</td>
			</tr>
                    <?php endforeach; endif;?>
	<!--  ##############- OFFLINE END-########################## -->		
			
		  <tr class="separator">
				<td colspan="<?php echo $colspan_table?>"> </td>
			</tr>
		<?php endforeach;?>
		
		</tbody>
	</table>
	</div>
	
	<!-- TREATMENT CARE / Behandlungspflege-->
	<?php elseif(!in_array($medication_type,$timed_scheduled_medications) && $medication_type == 'treatment_care'): ?>
	<div class="mk-container">
    	<!-- top -->
    	<div class="mk-top">
    		<h2><?php echo $this->translate($medication_type." medication title")?> </h2>
    		<div class="cb-container print_opt_line">
    			<input type="checkbox" value="1" name="print[<?php echo $medication_type;?>][allow]" checked="checked" id="print<?php echo $medication_type;?>" class="all_print_medication" />
    			<label for="print<?php echo $medication_type;?>"><?php echo $this->translate('show in pdf');?></label>
    		</div>
    		
		<div class="right-nav">
			<div class="sorting" onClick="med_Sort(this)" data-sort_type="<?php echo $medication_type;?>">
				<span class="sortby" ><?php  echo $this->translate('Sort by');?> <?php echo  $this->translate('medication_'.$sort_order[$medication_type]['col']);?></span>
				<div class="buttons">
					<input type="button" name="sortup" class="btnSort sortup  <?php if($sort_order[$medication_type]['ord']=='asc'):?> active <?php endif;?>"  onclick="save_sort_option('<?php echo $medication_type;?>','<?php echo $sort_order[$medication_type]['col']?>','asc')" />
					<input type="button" name="sortdown" class="btnSort sortdown <?php if($sort_order[$medication_type]['ord']=='desc'):?> active <?php endif;?> " onclick="save_sort_option('<?php echo $medication_type;?>','<?php echo $sort_order[$medication_type]['col']?>','desc')">
				</div>
			</div>
			
			<div class="sorting-dd" id="sort_<?php echo $medication_type;?>" >
					<div class="sortby">
					<?php  echo $this->translate('SORT BY');?>:
					</div>
					 <?php $sorting_options = array('importance','medication','comments');?>
					
					<ul>
					   <?php foreach($sorting_options as $sort_col):?>
						<li <?php if($sort_order[$medication_type]['col']== $sort_col):?> class="active" <?php endif;?> 
						 onclick="save_sort_option('<?php echo $medication_type;?>','<?php echo $sort_col;?>','<?php echo $sort_order[$medication_type]['ord']; ?>')"
						 
						><?php echo $this->translate('medication_'.$sort_col)?></li>
					   <?php endforeach;?>
					</ul>
					
				</div>
			<a href="<?php  echo APP_BASE.'patientmedication/edit?id='.$_REQUEST['id'].'&#'.$medication_type; ?>" class="btnBlue btnEdit"> </a>	
		</div>
    	</div>
    	<!-- // top -->
    	
    		<table class="medikation" cellspacing="0" cellpadding="0" border="0">
    	    <?php 
    	       $colspan_table = 7; // change colspan according to blocks
    		?>
    		<thead>
    			<tr>
    				<th colspan="2" class="name">NAME </th>
    				<th >KOMMENTAR</th>
    				<th rowspan="2" >LETZTE ÄNDERUNG</th>
    			</tr>
    		</thead>
 

    		<tbody>
    		<?php foreach($medication_array[$medication_type] as $k =>$med):?>
    		
    		    <?php
    		    $has_ack_class="";
    
    		    if(($this->acknowledge  == "1" && !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :
        		    $has_ack_class = "has_ack";
                endif; 
                ?>
    		    <?php 
    		    $data_medid= "";  
    			if(($this->acknowledge  == "1" && !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :
                    $data_medid ='data-medid="'. $med['id'].'"' ;  
    			endif; 
                ?> 
                
                <?php $row_type_nt = "single";?>
                <?php $row_span_nt = ' ';?>
    
                <tr  class="<?php echo $row_type_nt?> <?php if($row_type_nt == 'double'):?>first <?php endif;?> medication_row_<?php echo $med['id']?> <?php echo $has_ack_class;?>" <?php echo $data_medid?>>
    			
                    <!--TD: Sort -->    			
    				<td class="sortnum" <?php echo $row_span_nt?> ><span> <?php echo $med['importance']; ?></span></td>
    				
                    <!--TD: Name -->    			
    				<td class="name"><?php echo $med['medication'];?></td>
    				
    				
                    <!--TD: Indication Comment -->    			
    				<td class="ind-comm" <?php echo $row_span_nt; ?>>
    					<div class="comment extra_padding_left"  id="<?php echo $med['id'];?>_medi_comment"><?php echo $med['comments'];?></div>
    				</td>
    
    				<?php if($medication_type == "iscrisis" || $medication_type == "isbedarfs"):?>
    				
                    <!--TD: escalation -->    			
    				<td class="escalation" <?php echo $row_span_nt; ?>>
    					<div><?php echo $med['escalation']; ?></div>
    				</td>
    				<?php endif;?>
    				
    				
                    <!--TD: date -->    			
    				<td class="date" <?php echo $row_span_nt; ?>>
    					<div class="date-cont"><?php echo date('d.m.Y',strtotime($med['medication_change']));?></div>
    				</td>
    			</tr>
    			

    		<?php if( $this->acknowledge  == "1" && ! empty($med['on_hold_changes'][$med['id']] )) : ?>
    			<?php 
    				$ack_referance_txt = array();
                    $ack_referance_del = array();
                    $ack_referance_txt[$med['id']]="";
    				$ack_referance_del[$med['id']] = "";
    
    				  if($med['on_hold_changes'][$med['id']]['status'] == "delete")
    				  {
    					 $ack_referance_txt[$med['id']] = '<span class="blue_text">'.$this->translate("Unapproved changes: ").'</span>';
    					 $ack_referance_del[$med['id']] = '<span class="red_text">'.$this->translate("Delete medication: ").'</span>'; 
    				  } 
    				  else if($med['on_hold_changes'][$med['id']]['status'] == "new")
    				  {
    					 $ack_referance_txt[$med['id']] = '<span class="green_text">'.$this->translate("Unapproved newly added medication: ").'</span>'; 
    					 $ack_referance_del[$med['id']] = ''; 
    				  } 
    				  else
    				  {
    					 $ack_referance_txt[$med['id']] = '<span class="blue_text">'.$this->translate("Unapproved changes: ").'</span>'; 
    					 $ack_referance_del[$med['id']] = ''; 
    				  }
                   
     		 
    				if($this->approval_rights == "1")
    				{
    					$app_rights = '<button class="med_approve_rights approvem" data-action="approve" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Approve").'</button><button class="med_approve_rights denym"   data-action="decline" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Decline").'</button>';
    					$approve = '<button class="med_approve_rights approvem" data-action="approve" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Approve").'</button>';
    					$deny = '<button class="med_approve_rights denym"   data-action="decline" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Decline").'</button>';
    	 			} 
    				else
    				{
    					$app_rights = '';
    					$approve = '';
    					$deny = '';
    				}
     		?>
     
    		  <tr class="double extedned_ack  ack_medication_row_<?php echo $med['id']?> " >
    		  
                    <!-- TD: Sort -->            		  
    				<td class="sortnum"><?php echo $med['on_hold_changes'][$med['id']]['importance'];?></td>
    				
                    <!-- TD: Name -->            		  
    				<td class="name">
    				    <?php echo $ack_referance_txt[$med['id']];?><br/><br/>
    				    <?php echo $med['on_hold_changes'][$med['id']]['name'];?>
    				</td>
    				
                    <!-- TD: Indication and Comment + Buttons-->            		  
    				<td class="ind-comm" >
    					<div class="comment extra_padding_left"  id="<?php echo $med['id'];?>_medi_comment"><?php echo $med['on_hold_changes'][$med['id']]['comments'];?></div>
    					<br/>
    					<br/>
    					<?php echo $approve; ?> <?php echo $deny; ?>
    				</td>
    				
     
                    <!-- TD: date -->            		  
    				<td class="date" >
    					<div class="date-cont"><?php echo date('d.m.Y',strtotime($med['on_hold_changes'][$med['id']]['medication_change_date']));?></div>
    				</td>
    				
    			</tr>
                <?php  endif;?>
    			
    			
    			    
                    <?php if($this->ModulePrivileges[155] == true && ! empty($med['on_hold_changes_offline'][$med['id']])) : ?>
                    <!-- offline changes moderate -->               
                    <?php         
                    foreach ($med['on_hold_changes_offline'][$med['id']] as $on_hold_changes ) : 
                   
                        $ack_referance_txt = "";
                        $ack_referance_del = "";
                        switch($on_hold_changes['status']) {
                            case 'delete' :
                                $ack_referance_txt = '<span class="blue_text">'.$this->translate("Offline Unapproved changes: ").'</span>';
                                $ack_referance_del = '<span class="red_text">'.$this->translate("Offline Delete medication: ").'</span>';
                            break;

                            case 'new' :
                                $ack_referance_txt = '<span class="green_text">'.$this->translate("Offline Unapproved newly added medication: ").'</span>';
                                $ack_referance_del = '';
                            break;

                            case 'edit' :
                                $ack_referance_txt = '<span class="blue_text">'.$this->translate("Offline Unapproved Edit changes: ").'</span>';
                                $ack_referance_del = '';
                            break;

                            default :
                                $ack_referance_txt = '<span class="blue_text">'.$this->translate("Offline Unapproved changes: ").'</span>';
                                $ack_referance_del = '';
                            break;
                        }


                 
                        if($this->approval_rights == "1")
                        {
                            $app_rights = '<button class="med_approve_rights approvem" data-action="approve" data-recordid="'.$med['id'].'" data-alt_id="'.$on_hold_changes['alt_id'].'">'.$this->translate("Offline Approve").'</button><button class="med_approve_rights denym"   data-action="decline" data-recordid="'.$med['id'].'" data-alt_id="'.$on_hold_changes['alt_id'].'">'.$this->translate("Offline Decline").'</button>';
                            $approve = '<button class="med_approve_rights approvem" data-action="approve" data-recordid="'.$med['id'].'" data-alt_id="'.$on_hold_changes['alt_id'].'">'.$this->translate("Offline Approve").'</button>';
                            $deny = '<button class="med_approve_rights denym"   data-action="decline" data-recordid="'.$med['id'].'" data-alt_id="'.$on_hold_changes['alt_id'].'">'.$this->translate("Offline Decline").'</button>';
                        } 
                        else
                        {
                            $app_rights = '';
                            $approve = '';
                            $deny = '';
                        }

                ?>
                <tr class="double extedned_ack  offline_ack_medication_row_<?php echo $med['id']?> " >
    		  
                    <!-- TD: Sort -->            		  
    				<td class="sortnum"><?php echo $med['on_hold_changes'][$med['id']]['importance'];?></td>

    				<!-- TD: Name -->            		  
    				<td class="name">
    				    <?php echo $ack_referance_txt;?><br/><br/>
    				    <?php echo $on_hold_changes['name'];?>
    				</td>
    				

    				<!-- TD: Indication Comment -->            		  
    				<td class="ind-comm" >
    					<div class="comment extra_padding_left"  id="<?php echo $med['id'];?>_medi_comment"><?php echo $on_hold_changes['comments'];?></div>
    					<br/>
    					<br/>
    					<?php echo $approve; ?> <?php echo $deny; ?>
    				</td>
    				
    				<!-- TD: Date -->            		  
    				<td class="date" >
    					<div class="date-cont"><?php echo date('d.m.Y',strtotime($on_hold_changes['medication_change_date']));?></div>
    				</td>
    			</tr>
            <?php endforeach; endif;?>
                    
    			
    			
    			
    		  <tr class="separator">
    				<td colspan="<?php echo $colspan_table?>"> </td>
    			</tr>
    		<?php endforeach;?>
    		
    		</tbody>
    	</table>
	
	</div>
	<!--scheduled  Intervall Medis -->
	<?php elseif(!in_array($medication_type,$timed_scheduled_medications) && $medication_type == 'scheduled'): ?>
	<div class="mk-container">
	<!-- top -->
	<div class="mk-top">
		<h2><?php echo $this->translate($medication_type." medication title")?> </h2>
		<div class="cb-container print_opt_line">
			<input type="checkbox" value="1" name="print[<?php echo $medication_type;?>][allow]" checked="checked" id="print<?php echo $medication_type;?>" class="all_print_medication" />
			<label for="print<?php echo $medication_type;?>"><?php echo $this->translate('show in pdf');?></label>
		</div>
		
		<div class="right-nav">
			<div class="sorting" onClick="med_Sort(this)" data-sort_type="<?php echo $medication_type;?>">
				<span class="sortby" ><?php  echo $this->translate('Sort by');?> <?php echo  $this->translate('medication_'.$sort_order[$medication_type]['col']);?></span>
				<div class="buttons">
					<input type="button" name="sortup" class="btnSort sortup  <?php if($sort_order[$medication_type]['ord']=='asc'):?> active <?php endif;?>"  onclick="save_sort_option('<?php echo $medication_type;?>','<?php echo $sort_order[$medication_type]['col']?>','asc')" />
					<input type="button" name="sortdown" class="btnSort sortdown <?php if($sort_order[$medication_type]['ord']=='desc'):?> active <?php endif;?> " onclick="save_sort_option('<?php echo $medication_type;?>','<?php echo $sort_order[$medication_type]['col']?>','desc')">
				</div>
			</div>
			
			<div class="sorting-dd" id="sort_<?php echo $medication_type;?>" >
					<div class="sortby">
					<?php  echo $this->translate('SORT BY');?>:
					</div>
					 <?php $sorting_options = array('importance','medication','drug','indication','change_date');?>
					
					<ul>
					   <?php foreach($sorting_options as $sort_col):?>
						<li <?php if($sort_order[$medication_type]['col']== $sort_col):?> class="active" <?php endif;?> 
						 onclick="save_sort_option('<?php echo $medication_type;?>','<?php echo $sort_col;?>','<?php echo $sort_order[$medication_type]['ord']; ?>')"
						 
						><?php echo $this->translate('medication_'.$sort_col)?></li>
					   <?php endforeach;?>
					</ul>
					
				</div>
			<a href="<?php  echo APP_BASE.'patientmedication/edit?id='.$_REQUEST['id'].'&#'.$medication_type; ?>" class="btnBlue btnEdit"> </a>	
		</div>
	</div>
	<!-- // top -->
	
	    <?php 
	       $colspan_table = 8; // change colspan according to blocks
		?>
		<table class="medikation" cellspacing="0" cellpadding="0" border="0">
		<thead>
			<tr>
				<th colspan="2" class="name">NAME / <span>WIRKSTOFF</span></th>
				<th class="dosierung">DOSIERUNG</th>
				<th rowspan="2">INDIKATION / KOMMENTAR</th>
				<th >INTERVALL(Tage)</th>
				<th >INTERVALL ZULETZT GESTARTET</th>
				<th rowspan="2" colspan="2">LETZTE ÄNDERUNG</th>
			</tr>
		</thead>
		
		<tbody>
		<?php foreach($medication_array[$medication_type] as $k =>$med):?>
		
		    <?php
		    $has_ack_class="";

		    if(($this->acknowledge  == "1" && !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :
    		    $has_ack_class = "has_ack";
            endif; 
            ?>
		    <?php 
		    $data_medid= "";  
			if(($this->acknowledge  == "1" && !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :
                $data_medid ='data-medid="'. $med['id'].'"' ;  
			endif; 
            ?> 
                        
            
            <!--  Check if the medication line - needs multiple rows  -->
            <?php $row_type_nt = "double";?>
            <?php $row_span_nt = ' rowspan="2"';?>
            
            <?php if(empty($med['drug']) && empty($med['dosage_interval'])):?>
                <?php $row_type_nt = " single";?>
                <?php $row_span_nt = '';?>    
            <?php endif;?>
            <!-- end check -->
            

            <tr  class="<?php echo $row_type_nt?> <?php if($row_type_nt == 'double'):?>first <?php endif;?> medication_row_<?php echo $med['id']?> <?php echo $has_ack_class;?>" <?php echo $data_medid?>>
                
                 <!--  TD: Sort  -->
				<td class="sortnum" <?php echo $row_span_nt?> ><span> <?php echo $med['importance']; ?></span></td>
				
                 <!--  TD: Name  -->
				<td class="name"><?php echo $med['medication'];?></td>
				
				
                 <!--  TD: Dosage and Unit  -->
				<td class="dosierung">
				    <?php echo $med['dosage'];?> 
				    <?php echo $med['unit'];?> 
				 </td>
				
				
                 <!--  TD: indikation+commetn  -->
				<td class="ind-comm" <?php echo $row_span_nt; ?>>
				<?php if(!empty( $med['indication'])):?>
    				<?php if(strlen($med['indication_color']) > 0):?>
    					<div class="indikation" style="color:#<?php echo $med['indication_color'];?>"><span class="circle" style="background:#<?php echo $med['indication_color'];?>"></span><?php echo $med['indication'];?></div>
    					<?php else:?>
    					<div class="indikation" style="color:#000000"><span class="circle" style="background:#000000"></span><?php echo $med['indication'];?></div>
    				<?php endif;?>
				<?php endif;?>
					<div class="comment extra_padding_left"  id="<?php echo $med['id'];?>_medi_comment"><?php echo $med['comments'];?></div>
				</td>
				
                 <!--  TD: Interval days  -->
				<td class="days_interval"  >
					<div><?php echo $med['days_interval']; ?></div>
				</td>
				
                 <!--  TD: Administration date  -->
				<td>
					<?php  if( $med['administration_date'] != "0000-00-00 00:00:00"):?>
					  <div class="date-cont">  <?php echo date("d.m.Y",strtotime($med['administration_date']));?></div> 
					<?php endif;?>
				</td>

				
                 <!--  TD: Date+ History  -->
				<td class="date" <?php echo $row_span_nt; ?>>
				    <input type="button" name="history" class="btnHistory show_medication_info"   data-medication_type="<?php echo $medication_type; ?>" data-drugplan_id="<?php echo $med['id']; ?>">
					<div class="date-cont"><?php echo date('d.m.Y',strtotime($med['medication_change']));?></div>
				</td>
				
                 <!--  TD: Details  -->
                 <!-- 				<td class="details expand_details" <?php echo $row_span_nt; ?> data-expand_details_id="<?php echo $med['id']?>"></td>
                 ISPC-2329 Lore 16.06.2020 -->
				<td class="details expand_details" <?php echo $row_span_nt; ?> data-expand_details_id="<?php echo $med['id']?>"><button class="expand_details_float" name="btn123" ></td>
			</tr>
			
			<?php if( $row_type_nt == 'double'):?>
			<tr class="<?php echo $row_type_nt?> last last_med_row_<?php echo $med['id']?>  <?php if(($this->acknowledge  == "1" && !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :?> has_ack <?php endif; ?>">
                
                <!--  TD: Drug  -->
				<td class="name wirkstoff"><?php echo $med['drug'];?> </td>
				
                
                <!--  TD: Extra  -->
				<td class="dosierung">
                    <?php if ($this->ModulePrivileges[182]): ?>
                        <?=$this->translate("Dosage according to the product information")?>
                        <?=($med['dosage_product'] == 'yes' ? ': Ja' : ($med['dosage_product'] == 'no' ? ': Nein' : '-'))?>
                    <?php endif; ?>
				</td>
				
				
                <!--  TD: Extra  -->
				<td class="dosierung">
                    <?php if ($this->ModulePrivileges[182]): ?>
                        <?=$this->translate("Interval according to technical information")?>
                        <?=($med['days_interval_technical'] == 'yes' ? ': Ja' : ($med['days_interval_technical'] == 'no' ? ': Nein' : '-'))?>
                    <?php endif; ?>
				</td>
				
                <!--  TD: Administration button  -->
				<td class="dosierung">
				<?php  if( $med['administration_date'] != "0000-00-00 00:00:00"):?>
					<?php if($med['allow_restart'] == "1"):?>
						<button type="button" class="  interval_restart btnBlue" data-drug_id="<?php echo $med['id'];?>"  data-medication_type = "<?php echo $medication_type;?>" id="<?php echo $medication_type;?>_<?php echo $med['id'];?>_interval_restart" ><?php echo $this->translate("give medication- Restart start interval")?></button>
					<?php endif; ?>
				<?php else: ?>
					<button type="button" class="  interval_start btnBlue"  data-drug_id="<?php echo $med['id'];?>"  data-medication_type = "<?php echo $medication_type;?>"  id="<?php echo $medication_type;?>_<?php echo $med['id'];?>_interval_start" ><?php echo $this->translate("give medication- start interval")?></button>
				<?php endif; ?>
				</td>
			</tr>
			<?php endif;?>
			
			<tr class="medication_details_row_<?php echo $med['id']?> hide_details expandedItem <?php if(($this->acknowledge  == "1" && !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :?> has_ack <?php endif; ?>"  >
				
				<td colspan="<?php echo $colspan_table;?>">
					
					<h3>APPLIKATIONSWEG, DARREICHUNGSFORM, EINHEIT, ETC</h3>
					
					<div class="ei-content">
						
						<ul class="item">
							<li><span>Konzentration: </span><?php echo $med['concentration_full'];?></li>
							<li><span>Einheit: </span><?php echo $med['unit'];?></li>
						</ul>
						
						<ul class="item">
							<li><span>Darreichungsform: </span><?php echo $med['dosage_form'];?></li>
							<li><span>Applikationsweg: </span><?php echo $med['type'];?></li>
						</ul>
						
						<?php if( ($medication_type=="actual" || $medication_type=="isivmed") && $allow_normal_scheduled == "1"):?>
    						<?php if($med['has_interval'] == "1"):?>
    						<ul class="item">
    							<li><span>Interval(Tage): </span><?php echo $med['days_interval'];?></li>
    							<?php  if( $med['administration_date'] != "0000-00-00 00:00:00"):?>
        							<li><span>Intervall zuletzt gestartet: </span>
        							<?php echo date("d.m.Y",strtotime($med['administration_date']));?>
        							</li>
        							<?php if($med['allow_restart'] == "1"):?>
        							 <li><button type="button" class="btnBlue interval_restart interval_settings" data-drug_id="<?php echo $med['id'];?>"  data-medication_type = "<?php echo $medication_type;?>" id="<?php echo $medication_type;?>_<?php echo $med['id'];?>_interval_restart" ><?php echo $this->translate("give medication- Restart start interval")?></button></li>
        							<?php endif; ?>
        						<?php else: ?>
        						  <li> 
        						    <button type="button" class="btnBlue interval_start interval_settings"  data-drug_id="<?php echo $med['id'];?>"  data-medication_type = "<?php echo $medication_type;?>"  id="<?php echo $medication_type;?>_<?php echo $med['id'];?>_interval_start" ><?php echo $this->translate("give medication- start interval")?></button>
       						    </li>
       							<?php endif; ?>
    						</ul>
    						<?php endif;?>
						<?php endif;?>
						
					</div>
				</td>
			</tr>
			
			
		<?php if( $this->acknowledge  == "1" && ! empty($med['on_hold_changes'][$med['id']] )) : ?>
			<?php 
				$ack_referance_txt = array();
                $ack_referance_del = array();
                $ack_referance_txt[$med['id']]="";
				$ack_referance_del[$med['id']] = "";

				  if($med['on_hold_changes'][$med['id']]['status'] == "delete")
				  {
					 $ack_referance_txt[$med['id']] = '<span class="blue_text">'.$this->translate("Unapproved changes: ").'</span>';
					 $ack_referance_del[$med['id']] = '<span class="red_text">'.$this->translate("Delete medication: ").'</span>'; 
				  } 
				  else if($med['on_hold_changes'][$med['id']]['status'] == "new")
				  {
					 $ack_referance_txt[$med['id']] = '<span class="green_text">'.$this->translate("Unapproved newly added medication: ").'</span>'; 
					 $ack_referance_del[$med['id']] = ''; 
				  } 
				  else
				  {
					 $ack_referance_txt[$med['id']] = '<span class="blue_text">'.$this->translate("Unapproved changes: ").'</span>'; 
					 $ack_referance_del[$med['id']] = ''; 
				  }
               
 		 
				if($this->approval_rights == "1")
				{
					$app_rights = '<button class="med_approve_rights approvem" data-action="approve" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Approve").'</button><button class="med_approve_rights denym"   data-action="decline" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Decline").'</button>';
					$approve = '<button class="med_approve_rights approvem" data-action="approve" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Approve").'</button>';
					$deny = '<button class="med_approve_rights denym"   data-action="decline" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Decline").'</button>';
	 			} 
				else
				{
					$app_rights = '';
					$approve = '';
					$deny = '';
				}
 		?>
 
		  <tr class="double extedned_ack  ack_medication_row_<?php echo $med['id']?> " >
		        
		        <!-- TD: Sort -->
				<td class="sortnum" rowspan="2"> </td>

				<!-- TD: Name -->
				<td class="name">
				    <?php echo $ack_referance_txt[$med['id']];?><br/><br/>
				    <?php echo $med['on_hold_changes'][$med['id']]['name'];?>
				</td>
				
				<!-- TD: Dosage -->
				<td class="dosierung" rowspan="2">
				    <?php echo $med['on_hold_changes'][$med['id']]['dosage'];?> 
				    <?php if ($this->show_new_fileds == "1" && strlen($med['on_hold_changes'][$med['id']]['dosage']) > 0):?><?php echo $med['on_hold_changes'][$med['id']]['unit'];?><?php endif;?>
				</td>
				
				<!-- TD: Indication and Comment -->
				<td class="ind-comm" rowspan="2">
				<?php if(!empty($med['on_hold_changes'][$med['id']]['indication'])):?>
    				<?php if(strlen($med['indication_color']) > 0):?>
    					<div class="indikation" style="color:#<?php echo $med['on_hold_changes'][$med['id']]['indication_color'];?>"><span class="circle" style="background:#<?php echo $med['on_hold_changes'][$med['id']]['indication_color'];?>"></span><?php echo $med['on_hold_changes'][$med['id']]['indication'];?> </div>
    					<?php else:?>
    					<div class="indikation" style="color:#000000"><span class="circle" style="background:#000000"></span><?php echo $med['on_hold_changes'][$med['id']]['indication'];?></div>
    				<?php endif;?>
				<?php endif;?>
					<div class="comment extra_padding_left"  id="<?php echo $med['id'];?>_medi_comment"><?php echo $med['on_hold_changes'][$med['id']]['comments'];?></div>
				</td>
				
				<!-- TD: Days Interval -->
				<td class="days_interval"  >
					<div class="days_interval"><?php echo $med['on_hold_changes'][$med['id']]['days_interval'];?></div>
				</td>
				
				
				<!-- TD: Adminsitration date -->
				<td>
					<?php  if( $med['on_hold_changes'][$med['id']]['administration_date'] != "0000-00-00 00:00:00"):?>
					<div class="date-cont"><?php echo $med['on_hold_changes'][$med['id']]['administration_date'];?></div>
					<?php endif;?>
				</td>
				
				<!-- TD: Date -->
				<td class="date">
					<div class="date-cont"><?php echo date('d.m.Y',strtotime($med['on_hold_changes'][$med['id']]['medication_change_date']));?></div>
				</td>
				
				<!-- TD: Details -->
				<td class="details ack_expand_details" rowspan="2" data-expand_details_id="<?php echo $med['id']?>"></td>
			</tr>
			
			<tr class="double last extedned_ack">
			
				<!-- TD: Drug -->
				<td class="name wirkstoff"><?php echo $med['on_hold_changes'][$med['id']]['drug'];?></td>
				
				
				<!-- TD: Dosage Extra-->
				<td class="dosierung"> 
                    <?php if ($this->ModulePrivileges[182]): ?>
                        <?=$this->translate("Dosage according to the product information")?>
                        <?=($med['on_hold_changes'][$med['id']]['dosage_product'] == 'yes' ? ': Ja' : ($med['on_hold_changes'][$med['id']]['dosage_product'] == 'no' ? ': Nein' : '-'))?>
                    <?php endif; ?>
				</td>
				
				<!-- TD: Interval Extra-->
				<td class="dosierung">
                    <?php if ($this->ModulePrivileges[182]): ?>
                        <?=$this->translate("Interval according to technical information")?>
                        <?=($med['on_hold_changes'][$med['id']]['days_interval_technical'] == 'yes' ? ': Ja' : ($med['on_hold_changes'][$med['id']]['days_interval_technical'] == 'no' ? ': Nein' : '-'))?>
                    <?php endif; ?>
				</td>
				
				<td>
				</td>
				
				
			</tr>
			
			<tr class="ack_medication_details_row_<?php echo $med['id']?> hide_details expandedItem extedned_ack" >
				
				<td colspan="<?php echo $colspan_table; ?>">
					
					<h3>APPLIKATIONSWEG, DARREICHUNGSFORM, EINHEIT, ETC</h3>
					
					<div class="ei-content">
						
						<ul class="item">
							<li><span>Konzentration: </span><?php echo $med['on_hold_changes'][$med['id']]['concentration'];?></li>
							<li><span>Einheit: </span><?php echo $med['on_hold_changes'][$med['id']]['unit'];?></li>
						</ul>
						
						<ul class="item">
							<li><span>Darreichungsform: </span><?php echo $med['on_hold_changes'][$med['id']]['dosage_form'];?></li>
							<li><span>Applikationsweg: </span><?php echo $med['on_hold_changes'][$med['id']]['type'];?></li>
						</ul>
						
						<?php if( ($medication_type=="actual" || $medication_type=="isivmed") && $allow_normal_scheduled == "1"):?>
    						<?php if($med['has_interval'] == "1"):?>
    						<ul class="item">
    							<li><span>Interval(Tage): </span><?php echo $med['days_interval'];?></li>
    							<?php  if( $med['administration_date'] != "0000-00-00 00:00:00"):?>
        							<li><span>Intervall zuletzt gestartet: </span>
        							<?php echo date("d.m.Y",strtotime($med['administration_date']));?>
        							</li>
        							<?php if($med['allow_restart'] == "1"):?>
        							 <li><button type="button" class="btnBlue interval_restart interval_settings" data-drug_id="<?php echo $med['id'];?>"  data-medication_type = "<?php echo $medication_type;?>" id="<?php echo $medication_type;?>_<?php echo $med['id'];?>_interval_restart" ><?php echo $this->translate("give medication- Restart start interval")?></button></li>
        							<?php endif; ?>
        						<?php else: ?>
        						  <li> 
        						    <button type="button" class="btnBlue interval_start interval_settings"  data-drug_id="<?php echo $med['id'];?>"  data-medication_type = "<?php echo $medication_type;?>"  id="<?php echo $medication_type;?>_<?php echo $med['id'];?>_interval_start" ><?php echo $this->translate("give medication- start interval")?></button>
       						    </li>
       							<?php endif; ?>
    						</ul>
    						<?php endif;?>
						<?php endif;?>
						
                        <ul class="item">
							<li><?php echo $approve; ?></li>
							<li><?php echo $deny; ?></li>
						</ul>
					</div>
				</td>
			</tr>
            <?php  endif;?>
			    
                    <?php if($this->ModulePrivileges[155] == true && ! empty($med['on_hold_changes_offline'][$med['id']])) : ?>
                    <!-- offline changes moderate -->               
                    <?php         
                    foreach ($med['on_hold_changes_offline'][$med['id']] as $on_hold_changes ) : 
                   
                        $ack_referance_txt = "";
                        $ack_referance_del = "";
                        switch($on_hold_changes['status']) {
                            case 'delete' :
                                $ack_referance_txt = '<span class="blue_text">'.$this->translate("Offline Unapproved changes: ").'</span>';
                                $ack_referance_del = '<span class="red_text">'.$this->translate("Offline Delete medication: ").'</span>';
                            break;

                            case 'new' :
                                $ack_referance_txt = '<span class="green_text">'.$this->translate("Offline Unapproved newly added medication: ").'</span>';
                                $ack_referance_del = '';
                            break;

                            case 'edit' :
                                $ack_referance_txt = '<span class="blue_text">'.$this->translate("Offline Unapproved Edit changes: ").'</span>';
                                $ack_referance_del = '';
                            break;

                            default :
                                $ack_referance_txt = '<span class="blue_text">'.$this->translate("Offline Unapproved changes: ").'</span>';
                                $ack_referance_del = '';
                            break;
                        }


                 
                        if($this->approval_rights == "1")
                        {
                            $app_rights = '<button class="med_approve_rights approvem" data-action="approve" data-recordid="'.$med['id'].'" data-alt_id="'.$on_hold_changes['alt_id'].'">'.$this->translate("Offline Approve").'</button><button class="med_approve_rights denym"   data-action="decline" data-recordid="'.$med['id'].'" data-alt_id="'.$on_hold_changes['alt_id'].'">'.$this->translate("Offline Decline").'</button>';
                            $approve = '<button class="med_approve_rights approvem" data-action="approve" data-recordid="'.$med['id'].'" data-alt_id="'.$on_hold_changes['alt_id'].'">'.$this->translate("Offline Approve").'</button>';
                            $deny = '<button class="med_approve_rights denym"   data-action="decline" data-recordid="'.$med['id'].'" data-alt_id="'.$on_hold_changes['alt_id'].'">'.$this->translate("Offline Decline").'</button>';
                        } 
                        else
                        {
                            $app_rights = '';
                            $approve = '';
                            $deny = '';
                        }

                ?>
                
            <tr class="double extedned_ack  offline_ack_medication_row_<?php echo $med['id']?> " >
		  
		        <!--TD: Sort -->  
				<td class="sortnum" rowspan="2"> </td>
		  
		        <!--TD: Name -->  
				<td class="name">
				    <?php echo $ack_referance_txt[$med['id']];?><br/><br/>
				    <?php echo $on_hold_changes['name'];?>
				</td>
				
		        <!--TD: Dosage -->  
				<td class="dosierung" rowspan="2">
				    <?php echo $on_hold_changes['dosage'];?> 
				    <?php if ($this->show_new_fileds == "1" && strlen($on_hold_changes['dosage']) > 0):?><?php echo $on_hold_changes['unit'];?><?php endif;?>
				</td>
				
		        <!--TD: indication Comment -->  
				<td class="ind-comm" rowspan="2">
				<?php if(!empty($on_hold_changes['indication'])):?>
    				<?php if(strlen($med['indication_color']) > 0):?>
    					<div class="indikation" style="color:#<?php echo $on_hold_changes['indication_color'];?>"><span class="circle" style="background:#<?php echo $on_hold_changes['indication_color'];?>"></span><?php echo $on_hold_changes['indication'];?> </div>
    					<?php else:?>
    					<div class="indikation" style="color:#000000"><span class="circle" style="background:#000000"></span><?php echo $on_hold_changes['indication'];?></div>
    				<?php endif;?>
				<?php endif;?>
					<div class="comment extra_padding_left"  id="<?php echo $med['id'];?>_medi_comment"><?php echo $on_hold_changes['comments'];?></div>
				</td>

				<!--TD: days interval -->
				<td class="days_interval"  >
					<div class="days_interval"><?php echo $on_hold_changes['days_interval'];?></div>
				</td>
				
				<!--TD: administration date -->
				<td>
					<?php  if( $on_hold_changes['administration_date'] != "0000-00-00 00:00:00"):?>
					<div class="date-cont"><?php echo $on_hold_changes['administration_date'];?></div>
					<?php endif;?>
				</td>
				
				<!--TD: Date-->
				<td class="date">
				    <?php echo $on_hold_changes['prescribed_by'];?> 
					<div class="date-cont"><?php echo date('d.m.Y',strtotime($on_hold_changes['medication_change_date']));?></div>
				</td>
				
				<!--TD: Details-->
				<td class="details offline_ack_expand_details" rowspan="2" data-expand_details_id="<?php echo $med['id']?>"></td>
			</tr>
			
			<tr class="double last extedned_ack">
			
				<!--TD: Drug-->
				<td class="name wirkstoff"><?php echo $on_hold_changes['drug'];?></td>
				
				
				<!--TD: Dosage Extra-->
				<td class="dosierung">
                    <?php if ($this->ModulePrivileges[182]): ?>
                        <?=$this->translate("Dosage according to the product information")?>
                        <?=($on_hold_changes['dosage_product'] == 'yes' ? ': Ja' : ($on_hold_changes['dosage_product'] == 'no' ? ': Nein' : '-'))?>
                    <?php endif; ?>
				</td>
				
				
				<!--TD: Interval Extra-->
				<td class="dosierung">
                    <?php if ($this->ModulePrivileges[182]): ?>
                        <?=$this->translate("Interval according to technical information")?>
                        <?=($on_hold_changes['days_interval_technical'] == 'yes' ? ': Ja' : ($on_hold_changes['days_interval_technical'] == 'no' ? ': Nein' : '-'))?>
                    <?php endif; ?>
				</td>
				
				<td>
				</td>
			</tr>
			
			<tr class="offline_ack_medication_details_row_<?php echo $med['id']?> hide_details expandedItem extedned_ack" >

                <td colspan="<?php echo $colspan_table; ?>">
			
					<h3>APPLIKATIONSWEG, DARREICHUNGSFORM, EINHEIT, ETC</h3>
				
					<div class="ei-content">
				
						<ul class="item">
							<li><span>Konzentration: </span><?php echo $on_hold_changes['concentration'];?></li>
							<li><span>Einheit: </span><?php echo $on_hold_changes['unit'];?></li>
						</ul>
						
						<ul class="item">
							<li><span>Darreichungsform: </span><?php echo $on_hold_changes['dosage_form'];?></li>
							<li><span>Applikationsweg: </span><?php echo $on_hold_changes['type'];?></li>
						</ul>
						
						<?php if( ($medication_type=="actual" || $medication_type=="isivmed") && $allow_normal_scheduled == "1"):?>
    						<?php if($on_hold_changes['has_interval'] == "1"):?>
    						<ul class="item">
    							<li><span>Interval(Tage): </span><?php echo $med['days_interval'];?></li>
    							<?php  if( $on_hold_changes['administration_date'] != "0000-00-00 00:00:00"):?>
        							<li><span>Intervall zuletzt gestartet: </span>
        							<?php echo date("d.m.Y",strtotime($on_hold_changes['administration_date']));?>
        							</li>
        							<?php if($on_hold_changes['allow_restart'] == "1"):?>
        							 <li><button type="button" class="btnBlue interval_restart interval_settings" data-drug_id="<?php echo $med['id'];?>"  data-medication_type = "<?php echo $medication_type;?>" id="<?php echo $medication_type;?>_<?php echo $med['id'];?>_interval_restart" ><?php echo $this->translate("give medication- Restart start interval")?></button></li>
        							<?php endif; ?>
        						<?php else: ?>
        						  <li> 
        						    <button type="button" class="btnBlue interval_start interval_settings"  data-drug_id="<?php echo $med['id'];?>"  data-medication_type = "<?php echo $medication_type;?>"  id="<?php echo $medication_type;?>_<?php echo $med['id'];?>_interval_start" ><?php echo $this->translate("give medication- start interval")?></button>
       						    </li>
       							<?php endif; ?>
    						</ul>
    						<?php endif;?>
						<?php endif;?>
						
						<ul class="item">
							<li><?php echo $approve; ?></li>
							<li><?php echo $deny; ?></li>
						</ul>
					</div>
				</td>
			</tr>
    <?php endforeach; endif;?>
			
		  <tr class="separator">
				<td colspan="<?php echo $colspan_table?>"> </td>
			</tr>
		<?php endforeach;?>
		
		</tbody>
	</table>
    </div> 
     
     	<!-- Pump -->
    <?php elseif($medication_type == "isschmerzpumpe" ):?>
        <div class="mk-container">
        <?php if(empty($medication_array[$medication_type])):?>
            	
          	<!-- top -->
        	<div class="mk-top">
        		<h2><?php echo $this->translate($medication_type." medication title")?> </h2>
        		<div class="cb-container print_opt_line">
        			<input type="checkbox" value="1" name="print[<?php echo $medication_type;?>][allow]" checked="checked" id="print<?php echo $medication_type;?>" class="all_print_medication" />
        			<label for="print<?php echo $medication_type;?>"><?php echo $this->translate('show in pdf');?></label>
        		</div>
        		
         		<div class="right-nav">
        			<div class="sorting" onClick="med_Sort(this)" data-sort_type="<?php echo $medication_type;?>">
        				<span class="sortby" ><?php  echo $this->translate('Sort by');?> <?php echo  $this->translate('medication_'.$sort_order[$medication_type]['col']);?></span>
        				<div class="buttons">
        					<input type="button" name="sortup" class="btnSort sortup  <?php if($sort_order[$medication_type]['ord']=='asc'):?> active <?php endif;?>"  onclick="save_sort_option('<?php echo $medication_type;?>','<?php echo $sort_order[$medication_type]['col']?>','asc')" />
        					<input type="button" name="sortdown" class="btnSort sortdown <?php if($sort_order[$medication_type]['ord']=='desc'):?> active <?php endif;?> " onclick="save_sort_option('<?php echo $medication_type;?>','<?php echo $sort_order[$medication_type]['col']?>','desc')">
        				</div>
        			</div>
        			
        			<div class="sorting-dd" id="sort_<?php echo $medication_type;?>" >
        					<div class="sortby">
        					<?php  echo $this->translate('SORT BY');?>:
        					</div>
        					 <?php $sorting_options = array('importance','medication','drug','indication','change_date');?>
        					
        					<ul>
        					   <?php foreach($sorting_options as $sort_col):?>
        						<li <?php if($sort_order[$medication_type]['col']== $sort_col):?> class="active" <?php endif;?> 
        						 onclick="save_sort_option('<?php echo $medication_type;?>','<?php echo $sort_col;?>','<?php echo $sort_order[$medication_type]['ord']; ?>')"
        						 
        						><?php echo $this->translate('medication_'.$sort_col)?></li>
        					   <?php endforeach;?>
        					</ul>
        					
        				</div>
        			<a href="<?php  echo APP_BASE.'patientmedication/edit?id='.$_REQUEST['id'].'&#'.$medication_type; ?>" class="btnBlue btnEdit"> </a>	
        		</div>
        	   </div>
	           <!-- // top -->
            		
            	<?php if(1==2):?>	
        		<div class="med_block_header">
        			<h1><?php echo $this->translate($medication_type." medication title ".$cocktail_details['pumpe_type'])?></h1>
        			<a href="<?php  echo APP_BASE.'patientmedication/edit?id='.$_REQUEST['id'].'&#'.$medication_type; ?>"  class="medication_edit_button"> <?php echo $this->translate($medication_type." medication edit")?> </a>
        						
        			<div class="pdf_options">
        				<label>
        					<input type="checkbox" value="1" name="print[<?php echo $medication_type;?>][<?php echo $pumpe_id?>][allow]" checked="checked"  id="print<?php echo $medication_type;?><?php echo $pumpe_id?>" class="all_print_medication"/>
        					<?php echo $this->translate('show in pdf');?>
        				</label>
        			</div>
        			<input type="hidden" value="<?php echo $this->saved_order[$medication_type]['col'];?>" id="<?php echo $medication_type;?>_<?php echo $pumpe_id?>_sort_by" name="print[<?php echo $medication_type;?>][<?php echo $pumpe_id?>][sortby]" /> 	
        			<input type="hidden" value="<?php echo $this->saved_order[$medication_type]['ord'];?>" id="<?php echo $medication_type;?>_<?php echo $pumpe_id?>_sort_dir" name="print[<?php echo $medication_type;?>][<?php echo $pumpe_id?>][sortdir]" />
        		</div>
        		<table class="sch_empty_medication_table datatable" style="width:100%">
        			<thead>
        					<tr>
        			 			<th rowspan="1" data-sortname="medication"><b><?php echo $this->translate('medication_name');?></b></th><!--  1 -->
        			 			<th rowspan="1" data-sortname="unit"><b><?php echo $this->translate('medication_unit'); ?></b></th><!--  3 -->
        			 			<th rowspan="1" data-sortname="dosage"><b><?php echo $this->translate('medication_dosage_h'); ?></b></th> <!--  5 -->
        			 			<th rowspan="3" data-sortname="indication"><b><?php echo $this->translate('medication_indication'); ?></b></th><!--  0 -->
        			 			<th rowspan="3" data-sortname="medication_change"><b><?php echo $this->translate('medication_last_update'); ?></b></th><!--  0 -->
        			 			<th rowspan="3" data-sortname="importance"><b><?php echo $this->translate('medication_importance'); ?></b></th><!--  0 -->
        			 		</tr>
        			 		<tr>
        			 			<th rowspan="2" class="sorting" data-sortname="drug"><b><?php echo $this->translate('medication_drug'); ?></b></th><!--  2 -->
        			  
        			 			<th rowspan="2" class="sorting" data-sortname="concentration"><b><?php echo $this->translate('medication_concentration'); ?></b></th><!--  4 -->
        			 			 
        			 			
        			 			<th rowspan="2" class="sorting" data-sortname="dosage_24h"><b><?php echo $this->translate('medication_dosage_24h'); ?></b></th><!--  2 -->
        			 		</tr>
        		 	</thead>
        		 	<tbody>
        		 		 <tr>
        		 		 	<td colspan="6">&nbsp;</td>
        		 		 </tr>
        		 	</tbody>
        		 </table>
                <?php endif;?>
        		 
            <?php endif;?>
	
	<?php $pumpe_cnt = 1;?>
	<?php foreach($medication_array[$medication_type] as $pumpe_id =>$med_pumpe):?>
		<?php 
			$cocktail_details=""; 

			//$schmerz[$pumpe_id] = end($medication_array[$medication_type][$pumpe_id]);
			foreach($medication_array[$medication_type][$pumpe_id] as $mident=>$mdetails){
			    if(is_array($mdetails['smpdescription']) && !empty($mdetails['smpdescription'])){
			        $schmerz[$pumpe_id] = $medication_array[$medication_type][$pumpe_id][$mident];
			    }
			}
			
			$cocktail_details = $schmerz[$pumpe_id]['smpdescription'];  
			$cocktail_details_alt = $schmerz[$pumpe_id]['smpdescription_alt'];  
			$cocktail_details_alt_offline = $schmerz[$pumpe_id]['smpdescription_alt_offline']; // this is multi
		?>
      		<!-- top -->
        	<div class="mk-top">
        		<h2><?php echo $this->translate($medication_type." medication title")?> </h2>
        		<div class="cb-container print_opt_line">
        			<input type="checkbox" value="1" name="print[<?php echo $medication_type;?>][<?php echo $pumpe_id?>][allow]" checked="checked" id="print<?php echo $medication_type;?>" class="all_print_medication" />
        			<label for="print<?php echo $medication_type;?>"><?php echo $this->translate('show in pdf');?></label>
        		</div>
        		
        		<div class="right-nav">
			<div class="sorting" onClick="med_Sort(this)" data-sort_type="<?php echo $medication_type;?><?php echo $pumpe_id;?>">
				<span class="sortby" ><?php  echo $this->translate('Sort by');?> <?php echo  $this->translate('medication_'.$sort_order[$medication_type]['col']);?></span>
        				<div class="buttons">
					<input type="button" name="sortup" class="btnSort sortup  <?php if($sort_order[$medication_type]['ord']=='asc'):?> active <?php endif;?>"  onclick="save_sort_option('<?php echo $medication_type;?>','<?php echo $sort_order[$medication_type]['col']?>','asc')" />
					<input type="button" name="sortdown" class="btnSort sortdown <?php if($sort_order[$medication_type]['ord']=='desc'):?> active <?php endif;?> " onclick="save_sort_option('<?php echo $medication_type;?>','<?php echo $sort_order[$medication_type]['col']?>','desc')">
        				</div>
        				
        				
        			</div>
			<div class="sorting-dd" id="sort_<?php echo $medication_type;?><?php echo $pumpe_id;?>"  >
        					<div class="sortby">
					<?php  echo $this->translate('SORT BY');?>:
        					</div>
					 <?php $sorting_options = array('importance','medication','drug','indication','change_date');?>  
        					
        					<ul>
					   <?php foreach($sorting_options as $sort_col):?>
						<li <?php if($sort_order[$medication_type]['col']== $sort_col):?> class="active" <?php endif;?> 
						 onclick="save_sort_option('<?php echo $medication_type;?>','<?php echo $sort_col;?>','<?php echo $sort_order[$medication_type]['ord']; ?>')"
						 
						><?php echo $this->translate('medication_'.$sort_col)?></li>
					   <?php endforeach;?>
        					</ul>
        				</div>
        			<a href="<?php  echo APP_BASE.'patientmedication/edit?id='.$_REQUEST['id'].'&#'.$medication_type; ?>" class="btnBlue btnEdit"> </a>	
        		</div>
        	</div>
        	<!-- // top -->		
		
		<?php $colspan_table = 7;?>
		<table id="<?php echo $medication_type; ?><?php echo $pumpe_cnt;?>" data-sch_id = "<?php echo $pumpe_cnt;?>" class="medication_table_<?php echo $medication_type; ?> medikation">
			<thead>
					<tr>
			 			<th  colspan="2" class="name">NAME / <span>WIRKSTOFF</span></th>
			 			<th rowspan="2" class="name">Einheit / <span>Konzentration</span></th>
			 			<th rowspan="2" class="name">Dosierung/h / <span>Dosierung in 24h</span></th>
			 			<th rowspan="2">INDIKATION</th>
				        <th rowspan="2" colspan="2">LETZTE ÄNDERUNG</th>
			 		</tr>
		 	</thead>
	
			<!--  LIST MEDICATION -->
		 	<tbody>
		 		<?php foreach($med_pumpe as $k =>$med):?>
		 		
		 		<?php
        		    $has_ack_class="";
        
        		    if(($this->acknowledge  == "1" && !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :
            		    $has_ack_class = "has_ack";
                    endif; 
                    ?>
        		    <?php 
        		    $data_medid= "";  
        			if(($this->acknowledge  == "1" && !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :
                        $data_medid ='data-medid="'. $med['id'].'"' ;  
        			endif; 
                ?> 
		 		    <?php $row_type = "double";?>
                    <?php $row_span = ' rowspan="2"';?>
		 		
		 		
                   <tr class="double first medication_row_<?php echo $med['id']?> <?php echo $has_ack_class;?>"  <?php echo $data_medid?>>
						<td class="sortnum" rowspan="2" >
						
						<span  class="show_medication_info"><?php echo $med['importance'];?></span></td>
				        <td class="name"><?php echo $med['medication'];?></td>
				        
				        <td ><?php echo $med['unit'];?></td>
				        
				        <!-- ISPC-2684 Lore 02.10.2020 -->
    					<?php if($this->ModulePrivileges[240] == true) :?> 
       				        <td class="dosierung">
        				        <?php echo $med['dosage']."ml/h"; echo '<br/>'.$med['unit_dosage'].$med['unit']."/h" ; ?></td>
            			<?php else:?> 
				        	<td class="dosierung"><?php echo $med['dosage'].$med['unit']."/h"; echo $med['dosage_mg_h_kg'] ; ?></td>
						<?php endif;?>  
				
						<td class="ind-comm" rowspan="2">
            				<?php if(!empty($med['indication'])):?>
                				<?php if(strlen($med['indication_color']) > 0 ):?>
                					<div class="indikation" style="color:#<?php echo $med['indication_color'];?>"><span class="circle" style="background:#<?php echo $med['indication_color'];?>"></span><?php echo $med['indication'];?></div>
                					<?php else:?>
                   					<div class="indikation" style="color:#000000"><span class="circle" style="background:#000000"></span><?php echo $med['indication'];?></div>
                				<?php endif;?>
            				<?php endif;?>
				        </td>
				        <td class="date" rowspan="2">
					       <input type="button" name="history" class="btnHistory show_medication_info"   data-medication_type="<?php echo $medication_type; ?>" data-drugplan_id="<?php echo $med['id']; ?>">
					       <div class="date-cont"><?php echo date('d.m.Y',strtotime($med['medication_change']));?></div>
				        </td>
					</tr>
					
					<tr class="double last  last_med_row_<?php echo $med['id']?>  <?php if(($this->acknowledge  == "1" && !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :?> has_ack <?php endif; ?>">
        				<td class="name wirkstoff"><?php echo $med['drug'];?></td>
        				<td class="dosierung"><?php echo $med['concentration_full'];?></td>
           				<!-- TODO-2503 ISPC Lore 19.08.2019 -->
        				<!--<td class="dosierung"><?php echo $med['dosage_24h'];?><?php if ($this->show_new_fileds == "1" && strlen($med['dosage_24h']) > 0 && strlen($med['dosage_24h_concentration']) > 0 ):?><?php echo $med['unit'];?>/24h (<?php echo $med['dosage_24h_concentration'];?>ml)<?php endif;?></td>--> 
        				<!-- ISPC-2684 Lore 02.10.2020 -->
    					<?php if($this->ModulePrivileges[240] == true) :?> 
        					<td class="dosierung"> <?php echo $med['dosage_24h']."ml/24h"; echo '<br/>'.$med['unit_dosage_24h'].$med['unit']."/24h" ;?></td>
            			<?php else:?> 
        					<td class="dosierung"> <?php echo $med['dosage_24h'];?><?php echo $med['unit'];?>/24h <?php if(strlen($med['dosage_24h_concentration']) > 0):?>(<?php echo $med['dosage_24h_concentration'];?>ml)<?php endif;?></td>
           				<?php endif;?>
        			</tr>

			     <?php if($this->acknowledge  == "1" && !empty($med['on_hold_changes'][$med['id']])) : ?>
					<?php 
						$ack_referance_txt = array();
                        $ack_referance_del = array();
                        $ack_referance_txt[$med['id']]="";
						$ack_referance_del[$med['id']] = "";

						if($med['on_hold_changes'][$med['id']]['status'] == "delete")
						{
							$ack_referance_txt[$med['id']] = '<span class="blue_text">'.$this->translate("Unapproved changes: ").'</span>';
							$ack_referance_del[$med['id']] = '<span class="red_text">'.$this->translate("Delete medication: ").'</span>'; 
						} 
						else if($med['on_hold_changes'][$med['id']]['status'] == "new")
						{
							$ack_referance_txt[$med['id']] = '<span class="green_text">'.$this->translate("Unapproved newly added medication: ").'</span>'; 
							$ack_referance_del[$med['id']] = ''; 
						} 
						else
						{
							$ack_referance_txt[$med['id']] = '<span class="blue_text">'.$this->translate("Unapproved changes: ").'</span>'; 
							$ack_referance_del[$med['id']] = ''; 
						}
		 		 
						if($this->approval_rights == "1")
						{
							$app_rights = '<button class="med_approve_rights approvem" data-action="approve" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Approve").'</button><button class="med_approve_rights denym"   data-action="decline" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Decline").'</button>';
							$approve = '<button class="med_approve_rights approvem" data-action="approve" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Approve").'</button>';
							$deny = '<button class="med_approve_rights denym"   data-action="decline" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Decline").'</button>';
			 			} 
						else
						{
							$app_rights = '';
							$approve = '';
							$deny = '';
						}
		 		?>
			         
			         
			         
			         <tr class="double first extedned_ack has_ack  ack_medication_row_<?php echo $med['id']?> " >
			            <td class="sortnum" rowspan="2"> </td>
			            
        				<td class="name">
        				    <?php echo $ack_referance_txt[$med['id']];?><br/><br/>
        				    <?php echo $med['on_hold_changes'][$med['id']]['name'];?>
        				</td>
        				
        				
				        <td>
				        <?php echo $med['on_hold_changes'][$med['id']]['unit'];?></td>
				        
				        <td class="dosierung"> 
				        <?php echo $med['on_hold_changes'][$med['id']]['dosage'];?></td>
			            
			            
			            <td class="ind-comm" rowspan="2">
            				<?php if(!empty($med['on_hold_changes'][$med['id']]['indication'])):?>
                				<?php if(strlen($med['on_hold_changes'][$med['id']]['indication_color']) > 0 ):?>
                					<div class="indikation" style="color:#<?php echo $med['on_hold_changes'][$med['id']]['indication_color'];?>"><span class="circle" style="background:#<?php echo $med['on_hold_changes'][$med['id']]['indication_color'];?>"></span><?php echo $med['on_hold_changes'][$med['id']]['indication'];?></div>
                					<?php else:?>
                   					<div class="indikation" style="color:#000000"><span class="circle" style="background:#000000"></span><?php echo $med['on_hold_changes'][$med['id']]['indication'];?></div>
                				<?php endif;?>
            				<?php endif;?>
				        </td>
                        
                        
                        <td class="date" rowspan="2">
                            <?php if (!empty($med['on_hold_changes'][$med['id']]['medication_change_date'])):?>
                            <input type="button" name="history" class="btnHistory show_medication_info"   data-medication_type="<?php echo $medication_type; ?>" data-drugplan_id="<?php echo $med['id']; ?>">
					       <div class="date-cont"> <?php echo $med['on_hold_changes'][$med['id']]['medication_change_date'];?></div>
					       <?php endif;?>
					       	<div class=" ack_buttons">
					 			<?php echo $approve; ?>
								<?php echo $deny; ?>
					 		</div>
				        </td>
				 	</tr>
				 	
				 	<tr class="double last  has_ack">

				 	<td class="name wirkstoff">
        				<?php echo $med['on_hold_changes'][$med['id']]['drug'];?> </td>
        				
        				<td class="dosierung">
        				<?php if(strlen($med['on_hold_changes'][$med['id']]['dosage_concentration']) > 0 ):?>(<?php echo $med['on_hold_changes'][$med['id']]['dosage_concentration'];?>)<?php endif;?> </td>
        				
        				<td class="dosierung">
        				<!-- TODO-2503 ISPC Lore 19.08.2019 -->       				
        				<?php echo $med['on_hold_changes'][$med['id']]['dosage_24h'];?> <?php if (strlen($med['on_hold_changes'][$med['id']]['dosage']) > 0):?> <?php echo $med['on_hold_changes'][$med['id']]['unit'];?><?php endif;?>/24h
        				<?php if ( strlen($med['on_hold_changes'][$med['id']]['dosage_24h_concentration']) > 0 ):?> (<?php echo $med['on_hold_changes'][$med['id']]['dosage_24h_concentration'];?> ml)<?php endif;?> 
        				
        				</td>
        			</tr>
        		<?php endif; ?>	
        		
        		
                    <?php if($this->ModulePrivileges[155] == true && ! empty($med['on_hold_changes_offline'][$med['id']])) : ?>
                    <!-- offline changes moderate isschmerzpumpe-->               
                    <?php           
                    foreach ($med['on_hold_changes_offline'][$med['id']] as $on_hold_changes ) : 
                   
                        $ack_referance_txt = "";
                        $ack_referance_del = "";
                        switch($on_hold_changes['status']) {
                            case 'delete' :
                                $ack_referance_txt = '<span class="blue_text">'.$this->translate("Offline Unapproved changes: ").'</span>';
                                $ack_referance_del = '<span class="red_text">'.$this->translate("Offline Delete medication: ").'</span>';
                            break;

                            case 'new' :
                                $ack_referance_txt = '<span class="green_text">'.$this->translate("Offline Unapproved newly added medication: ").'</span>';
                                $ack_referance_del = '';
                            break;

                            case 'edit' :
                                $ack_referance_txt = '<span class="blue_text">'.$this->translate("Offline Unapproved Edit changes: ").'</span>';
                                $ack_referance_del = '';
                            break;

                            default :
                                $ack_referance_txt = '<span class="blue_text">'.$this->translate("Offline Unapproved changes: ").'</span>';
                                $ack_referance_del = '';
                            break;
                        }
                        if($this->approval_rights == "1")
                        {
                            $app_rights = '<button class="med_approve_rights approvem" data-action="approve" data-recordid="'.$med['id'].'" data-alt_id="'.$on_hold_changes['alt_id'].'">'.$this->translate("Offline Approve").'</button><button class="med_approve_rights denym"   data-action="decline" data-recordid="'.$med['id'].'" data-alt_id="'.$on_hold_changes['alt_id'].'">'.$this->translate("Offline Decline").'</button>';
                            $approve = '<button class="med_approve_rights approvem" data-action="approve" data-recordid="'.$med['id'].'" data-alt_id="'.$on_hold_changes['alt_id'].'">'.$this->translate("Offline Approve").'</button>';
                            $deny = '<button class="med_approve_rights denym"   data-action="decline" data-recordid="'.$med['id'].'" data-alt_id="'.$on_hold_changes['alt_id'].'">'.$this->translate("Offline Decline").'</button>';
                        } 
                        else
                        {
                            $app_rights = '';
                            $approve = '';
                            $deny = '';
                        }

                    ?>
                <tr class="double first extedned_ack has_ack  offline_ack_medication_row_<?php echo $med['id']?> " >
			            <td class="sortnum" rowspan="2"> </td>
			            
        				<td class="name">
        				    <?php echo $ack_referance_txt[$med['id']];?><br/><br/>
        				    <?php echo $on_hold_changes['name'];?>
        				</td>
        				
        				
				        <td>
				        <?php echo $on_hold_changes['unit'];?></td>
				        
				        <td class="dosierung"> 
				        <?php echo $on_hold_changes['dosage'];?></td>
			            
			            
			            <td class="ind-comm" rowspan="2">
            				<?php if(!empty($on_hold_changes['indication'])):?>
                				<?php if(strlen($on_hold_changes['indication_color']) > 0 ):?>
                					<div class="indikation" style="color:#<?php echo $on_hold_changes['indication_color'];?>"><span class="circle" style="background:#<?php echo $on_hold_changes['indication_color'];?>"></span><?php echo $on_hold_changes['indication'];?></div>
                					<?php else:?>
                   					<div class="indikation" style="color:#000000"><span class="circle" style="background:#000000"></span><?php echo $on_hold_changes['indication'];?></div>
                				<?php endif;?>
            				<?php endif;?>
				        </td>
                        
                        
                        <td class="date" rowspan="2">
                            <?php if (!empty($on_hold_changes['medication_change_date'])):?>
					       <div class="date-cont"> <?php echo $on_hold_changes['medication_change_date'];?></div>
					       <?php endif;?>
					       	<div class=" ack_buttons">
					 			<?php echo $approve; ?>
								<?php echo $deny; ?>
					 		</div>
				        </td>
				 	</tr>
				 	
				 	<tr class="double last  has_ack">

    				 	<td class="name wirkstoff">
            				<?php echo $on_hold_changes['drug'];?> </td>
            				
            				<td class="dosierung">
            				<?php if(strlen($on_hold_changes['dosage_concentration']) > 0 ):?>(<?php echo $on_hold_changes['dosage_concentration'];?>)<?php endif;?> </td>
            				
            				<td class="dosierung">
        				<!-- TODO-2503 ISPC Lore 19.08.2019 -->            				
            				<?php echo $on_hold_changes['dosage_24h'];?> <?php if (strlen($on_hold_changes['dosage']) > 0):?> <?php echo $on_hold_changes['unit'];?><?php endif;?>/24h
            				<?php if ( strlen($on_hold_changes['dosage_24h_concentration']) > 0 ):?> (<?php echo $on_hold_changes['dosage_24h_concentration'];?> ml)<?php endif;?> 
            				
            			</td>
        			</tr>                    
                    
                    
                    <div class="ack_div ack_information_offline_<?php echo $med['id'];?>" style="display: none">
                        <div class="ack_inner_div">
                            <?php echo $ack_referance_txt;?>
                            <div class=" ack_buttons">
                                <?php echo $approve; ?>
                                <?php echo $deny; ?>
                            </div>
                        </div>
                        <div class="ack_inner_div">
                            <?php echo $ack_referance_del;?> 
                            <b><?php echo $this->translate('medication_change_date');?></b>: <?php echo $on_hold_changes['medication_change_date'];?>  | 
                            <b><?php echo $this->translate('medication_name');?></b>: <?php echo $on_hold_changes['name'];?>  |
                            <? if( strlen($on_hold_changes['drug'])  > 0) :?> 
                                <b><?php echo $this->translate('medication_drug');?></b>: <?php echo $on_hold_changes['drug'];?>  | 
                            <?php endif;?>
                        
                            <?php if ($this->show_new_fileds == "1") : ?>
                                <?php if( strlen($on_hold_changes['unit'])  > 0) :?> 
                                    <b><?php echo $this->translate('medication_unit');?></b>: <?php echo $on_hold_changes['unit'];?> | 
                                <?php endif;?>
                             
                                <?php if( strlen($on_hold_changes['type'])  > 0) :?> 
                                    <b><?php echo $this->translate('medication_type');?></b>: <?php echo $on_hold_changes['type'];?> | 
                                <?php endif;?>
                             
                                <?php if( strlen($on_hold_changes['dosage_form'])  > 0) :?> 
                                    <b><?php echo $this->translate('medication_dosage_form');?></b>: <?php echo $on_hold_changes['dosage_form'];?> | 
                                <?php endif;?>
                             
                                <?php if( strlen($on_hold_changes['concentration'])  > 0) :?> 
                                    <b><?php echo $this->translate('medication_concentration');?></b>: <?php echo $on_hold_changes['concentration'];?> | 
                                <?php endif;?>
                            <?php endif;?>
                    
                            <!--  MEDICATION DOSAGE INPUTS-->
                            
                            
                            <b><?php echo $this->translate('medication_dosage_h');?></b>: <?php echo $on_hold_changes['dosage'];?>
                            <?php if(strlen($on_hold_changes['dosage_concentration']) > 0 ):?>(<?php echo $on_hold_changes['dosage_concentration'];?>)<?php endif;?>
                            <?php if ($this->show_new_fileds == "1" && strlen($on_hold_changes['dosage']) > 0):?> <?php echo $on_hold_changes['unit'];?><?php endif;?>
                            <b><?php echo $this->translate('medication_dosage_24h');?></b>: <?php echo $on_hold_changes['dosage_24h'];?>
                            <?php if(strlen($on_hold_changes['dosage_24h_concentration']) > 0 ):?>(<?php echo $on_hold_changes['dosage_24h_concentration'];?>)<?php endif;?>
                            <?php if ($this->show_new_fileds == "1" && strlen($on_hold_changes['dosage']) > 0):?> <?php echo $on_hold_changes['unit'];?><?php endif;?>
                            
                            <b><?php echo $this->translate('medication_indication');?></b>: <?php echo $on_hold_changes['indication'];?>   |
                              
                            <b><?php echo $this->translate('medication_prescribed_by');?></b> <?php echo $on_hold_changes['prescribed_by'];?>   | 
                            <b><?php echo $this->translate('medication_created_by');?></b>  <?php echo $on_hold_changes['created_by'];?>   
                        </div>
                    </div>
                    
                    <?php endforeach;?>
                    <!-- end offline changes moderate isschmerzpumpe-->   
                    <?php endif; ?>
        		
        			<tr class="separator">
				        <td colspan="<?php echo $colspan_table?>"> </td>
			         </tr>
			         
        		
		 		<?php endforeach;?>
		 	</tbody>
		 </table>
         
         
         
         <table class="medikation datatable_sch <?php if(($this->acknowledge  == "1" && !empty($cocktail_details_alt)) || ($this->ModulePrivileges[155] == true && ! empty($cocktail_details_alt_offline)) ) echo 'ack_back';?>" >
            <tr class="single">
                <td width="20%"><label><?php echo $this->translate("Kommentar")?>:</label></td>
                <td width="80%"><?php echo $cocktail_details['description']?></td>
            </tr>
            <tr class="single ">
                <td><label><?php echo $this->translate("medication_type")?>:</label></td>
                <td><?php echo $cocktail_details['pumpe_medication_type']?></td>
            </tr>
            <tr class="single ">
                <td><label><?php echo $this->translate("Flussrate")?>:</label></td>
                <td><?php echo $cocktail_details['flussrate']?></td>
            </tr>
            <tr class="single ">
                <td><label><?php echo $this->translate("medication_carrier_solution")?>:</label></td>
                <td><?php echo $cocktail_details['carrier_solution']?></td>
            </tr>        
            <tr class="single ">
                <td><label><?php echo $this->translate("Bolus")?>:</label></td>
                <td><?php echo $cocktail_details['bolus']?></td>
            </tr>
            <tr class="single ">
               <td><label><?php echo $this->translate("Max Bolus")?>:</label></td>
               <td><?php echo $cocktail_details['max_bolus']?></td>
            </tr>        
            <tr class="single ">
               <td><label><?php echo $this->translate("Sperrzeit")?>:</label></td>
               <td><?php echo $cocktail_details['sperrzeit']?></td>
            </tr> 
        </table>
         
                                    		<?php if($this->acknowledge  == "1" && !empty($cocktail_details_alt)):?>
                                    		<?php 
                                                            $prefix_lang_ack = '';
                                                            $ack_referance_txt = array();
                                                            $ack_referance_del = array();
                                    						$ack_referance_txt[$med['id']]="";
                                    						$ack_referance_del[$med['id']] = "";
                                    
                                    						if($cocktail_details_alt['status'] == "delete")
                                    						{
                                    							$ack_referance_txt[$cocktail_details_alt['id']] = '<span class="blue_text">'.$this->translate($prefix_lang_ack . "Unapproved changes: ").'</span>';
                                    							$ack_referance_del[$cocktail_details_alt['id']] = '<span class="red_text">'.$this->translate($prefix_lang_ack . "Delete medication: ").'</span>'; 
                                    						} 
                                    						else if($cocktail_details_alt['status'] == "new")
                                    						{
                                    							$ack_referance_txt[$cocktail_details_alt['id']] = '<span class="green_text">'.$this->translate($prefix_lang_ack . "Unapproved newly added medication: ").'</span>'; 
                                    							$ack_referance_del[$cocktail_details_alt['id']] = ''; 
                                    						} 
                                    						else
                                    						{
                                    							$ack_referance_txt[$cocktail_details_alt['id']] = '<span class="blue_text">'.$this->translate($prefix_lang_ack . "Unapproved changes: ").'</span>'; 
                                    							$ack_referance_del[$cocktail_details_alt['id']] = ''; 
                                    						}
                                    		 		 
                                    						if($this->approval_rights == "1")
                                    						{
                                    							$approve = '<button class="pump_med_approve_rights approvem" data-action="approve" data-recordid="'.$cocktail_details_alt['drugplan_cocktailid'].'" data-alt_id="'.$cocktail_details_alt['id'].'">'.$this->translate($prefix_lang_ack . "Approve").'</button>';
                                    							$deny = '<button class="pump_med_approve_rights denym"   data-action="decline" data-recordid="'.$cocktail_details_alt['drugplan_cocktailid'].'" data-alt_id="'.$cocktail_details_alt['id'].'">'.$this->translate($prefix_lang_ack . "Decline").'</button>';
                                    			 			} 
                                    						else
                                    						{
                                    							$app_rights = '';
                                    							$approve = '';
                                    							$deny = '';
                                    						}
                                    		 ?>
                                    		 <?php
                                                $rowspan = 8;
                                             ?>
                                    		 <table class="medikation datatable_sch ack_back">
                                    		 	<tr>
                                    		 		<td colspan="2" >
                                    		 			<?php echo  $ack_referance_txt[$cocktail_details_alt['id']]; ?>
                                  						<div style="text-align: right;"><?php echo  $approve; ?> <?php echo  $deny; ?></div>
                                    		 		</td>
                                    		 		
                                    		 	</tr>
                                    			<tr>
                                    				<td width="20%"><label><?php echo $this->translate("Kommentar")?>:</label></td>
                                    				<td width="40%"><?php echo $cocktail_details_alt['description']?></td>
                                    			</tr>		 
                                    			<tr>
                                    				<td><label><?php echo $this->translate("medication_type")?>:</label></td>
                                    				<td><?php echo $cocktail_details_alt['pumpe_medication_type']?></td>
                                    			</tr>		 
                                    			<tr>
                                    				<td><label><?php echo $this->translate("Flussrate")?>:</label></td>
                                    				<td><?php echo $cocktail_details_alt['flussrate']?></td>
                                    			</tr>
                                    			<tr>
                                    				<td><label><?php echo $this->translate("medication_carrier_solution")?>:</label></td>
                                    				<td><?php echo $cocktail_details_alt['carrier_solution']?></td>
                                    			</tr>				 
                                    			<tr>
                                    				<td><label><?php echo $this->translate("Bolus")?>:</label></td>
                                    				<td><?php echo $cocktail_details_alt['bolus']?></td>
                                    			</tr>		
                                    			<tr>
                                    				<td><label><?php echo $this->translate("Max Bolus")?>:</label></td>
                                    				<td><?php echo $cocktail_details_alt['max_bolus']?></td>
                                    			</tr> 
                                    			<tr>
                                    				<td><label><?php echo $this->translate("Sperrzeit")?>:</label></td>
                                    				<td><?php echo $cocktail_details_alt['sperrzeit']?></td>
                                    			</tr>	
                                    	 	</table>
                                    		<?php endif; ?>
        
                                
                                            <?php if($this->ModulePrivileges[155] == true && ! empty($cocktail_details_alt_offline) ) :?> 
                                            <!-- start offline changes isschmerzpumpe details -->
                                                <?php foreach($cocktail_details_alt_offline as $on_hold_changes_offline) : ?>
                                                <?php 
                                                    $prefix_lang_ack = 'Offline ';
                                                    $ack_referance_txt = "";
                                                    $ack_referance_del = "";
                                                
                                                    if($cocktail_details_alt['status'] == "delete")
                                                    {
                                                        $ack_referance_txt = '<span class="blue_text">'.$this->translate($prefix_lang_ack . "Unapproved changes: ").'</span>';
                                                        $ack_referance_del = '<span class="red_text">'.$this->translate($prefix_lang_ack . "Delete medication: ").'</span>'; 
                                                    } 
                                                    else if($cocktail_details_alt['status'] == "new")
                                                    {
                                                        $ack_referance_txt = '<span class="green_text">'.$this->translate($prefix_lang_ack . "Unapproved newly added medication: ").'</span>'; 
                                                        $ack_referance_del = ''; 
                                                    } 
                                                    else
                                                    {
                                                        $ack_referance_txt = '<span class="blue_text">'.$this->translate($prefix_lang_ack . "Unapproved changes: ").'</span>'; 
                                                        $ack_referance_del = ''; 
                                                    }
                                                
                                                    if($this->approval_rights == "1")
                                                    {
                                                        $approve = '<button class="pump_med_approve_rights approvem" data-action="approve" data-recordid="'.$on_hold_changes_offline['drugplan_cocktailid'].'" data-alt_id="'.$on_hold_changes_offline['id'].'">'.$this->translate($prefix_lang_ack . "Approve").'</button>';
                                                        $deny = '<button class="pump_med_approve_rights denym"   data-action="decline" data-recordid="'.$on_hold_changes_offline['drugplan_cocktailid'].'" data-alt_id="'.$on_hold_changes_offline['id'].'">'.$this->translate($prefix_lang_ack . "Decline").'</button>';
                                                    } 
                                                    else
                                                    {
                                                        $app_rights = '';
                                                        $approve = '';
                                                        $deny = '';
                                                    }
                                                
                                                    $rowspan = 8;
                                                ?>
                                                
                                                    <table class="medikation datatable_sch ack_back">
                                        		 	<tr>
                                        		 		<td colspan="2" >
                                        		 			<?php echo  $ack_referance_txt; ?>
                                      						<div style="text-align: right;"><?php echo  $approve; ?> <?php echo  $deny; ?></div>
                                        		 		</td>
                                        		 		
                                        		 	</tr>
                                        			<tr class="single">
                                        				<td width="20%"><label><?php echo $this->translate("Kommentar")?>:</label></td>
                                        				<td width="40%"><?php echo $on_hold_changes_offline['description']?></td>
                                        			</tr>		 
                                        			<tr class="single">
                                        				<td><label><?php echo $this->translate("medication_type")?>:</label></td>
                                        				<td><?php echo $on_hold_changes_offline['pumpe_medication_type']?></td>
                                        			</tr>		 
                                        			<tr class="single">
                                        				<td><label><?php echo $this->translate("Flussrate")?>:</label></td>
                                        				<td><?php echo $on_hold_changes_offline['flussrate']?></td>
                                        			</tr>
                                        			<tr class="single">
                                        				<td><label><?php echo $this->translate("medication_carrier_solution")?>:</label></td>
                                        				<td><?php echo $on_hold_changes_offline['carrier_solution']?></td>
                                        			</tr>				 
                                        			<tr class="single">
                                        				<td><label><?php echo $this->translate("Bolus")?>:</label></td>
                                        				<td><?php echo $on_hold_changes_offline['bolus']?></td>
                                        			</tr>		
                                        			<tr class="single">
                                        				<td><label><?php echo $this->translate("Max Bolus")?>:</label></td>
                                        				<td><?php echo $on_hold_changes_offline['max_bolus']?></td>
                                        			</tr> 
                                        			<tr class="single">
                                        				<td><label><?php echo $this->translate("Sperrzeit")?>:</label></td>
                                        				<td><?php echo $on_hold_changes_offline['sperrzeit']?></td>
                                        			</tr>	
                                        	 	</table>
                                                
                                                         <table class="datatable_sch ack_back" style="display: none" >
                                                            <tr>
                                                                <td colspan="2" width="60%">
                                                                    <?php echo  $ack_referance_txt; ?>
                                                                </td>
                                                                <td rowspan="<?php echo $rowspan;?>" width="40%" style='text-align:right'>
                                                                    <?php echo  $approve; ?>
                                                                    <?php echo  $deny; ?>
                                                                </td>
                                                                
                                                            </tr>
                                                            <tr>
                                                                <td width="20%"><label><?php echo $this->translate("Kommentar")?>:</label></td>
                                                                <td width="40%"><?php echo $on_hold_changes_offline['description']?></td>
                                                            </tr>        
                                                            <tr>
                                                                <td><label><?php echo $this->translate("medication_type")?>:</label></td>
                                                                <td><?php echo $on_hold_changes_offline['pumpe_medication_type']?></td>
                                                            </tr>        
                                                            <tr>
                                                                <td><label><?php echo $this->translate("Flussrate")?>:</label></td>
                                                                <td><?php echo $on_hold_changes_offline['flussrate']?></td>
                                                            </tr>
                                                            <tr>
                                                                <td><label><?php echo $this->translate("medication_carrier_solution")?>:</label></td>
                                                                <td><?php echo $on_hold_changes_offline['carrier_solution']?></td>
                                                            </tr>                
                                                            <tr>
                                                                <td><label><?php echo $this->translate("Bolus")?>:</label></td>
                                                                <td><?php echo $on_hold_changes_offline['bolus']?></td>
                                                            </tr>       
                                                            <tr>
                                                                <td><label><?php echo $this->translate("Max Bolus")?>:</label></td>
                                                                <td><?php echo $on_hold_changes_offline['max_bolus']?></td>
                                                            </tr> 
                                                            <tr>
                                                                <td><label><?php echo $this->translate("Sperrzeit")?>:</label></td>
                                                                <td><?php echo $on_hold_changes_offline['sperrzeit']?></td>
                                                            </tr>   
                                                        </table>
                                                
                                                <?php endforeach; ?>
                                         <!-- end offline changes isschmerzpumpe details -->     
                        	           <?php endif;?>
        <?php endforeach;?>
        </div>	
	<?php endif;?>
	
<?php endforeach;?>	
	
	
	
<div class="mk-container">

<div id="deleted_medication_list">

</div>

</div>


<!-- ISPC-2524 pct.1)  Lore 14.01.2020 -->
<?php if(count($contact_form_files)>0):  ?>
<div class="mk-container">
	<div class="med_block_header dateien_verlauf_header mk-top mk-edit-title">
		<h1 id="section_dateien_verlauf"><?php echo $this->translate('file_history');?></h1>
		<input type="button" class="dateien_verlauf_state hidden" title="<?php echo $this->translate('Show_dateien_verlauf')?>" />
	</div>
	<table id="dateien_verlauf_med_table" class="medication_edit_table medikation dateien_verlauf_edit_table">
		<thead>
	 		<tr>
	 			<th>Nr. </th>
 				<th><?php echo $this->translate('title'); ?></th>
	 			<th><?php echo $this->translate('filetype'); ?></th>
	 			<th><?php echo $this->translate('user'); ?></th>
	 			<th><?php echo $this->translate('date'); ?></th>
	 		</tr>
	 	</thead>
 		<tbody>
			<?php $i = 1;
			foreach ($contact_form_files as $k_contact_file => $v_contact_file): ?>
				<?php if( $i % 2 == 0):  ?>
			    	<tr>
				<?php else : ?>
					<tr style="background: #F3F3F3!important;">
				<?php endif;  ?>
					<td><a href="<?php echo APP_BASE . 'stats/patientfileupload?doc_id='.$v_contact_file['id'].'&id='.$_REQUEST['id'];?>"><?php echo $i; ?></a></td>
					<td><a href="<?php echo APP_BASE . 'stats/patientfileupload?doc_id='.$v_contact_file['id'].'&id='.$_REQUEST['id'];?>"><?php echo $v_contact_file['title']; ?></a></td>
					<td><a href="<?php echo APP_BASE . 'stats/patientfileupload?doc_id='.$v_contact_file['id'].'&id='.$_REQUEST['id'];?>"><?php echo $v_contact_file['file_type']; ?></a></td>
					<td><a href="<?php echo APP_BASE . 'stats/patientfileupload?doc_id='.$v_contact_file['id'].'&id='.$_REQUEST['id'];?>"><?php echo $users_data[$v_contact_file['create_user']]['first_name'].', '.$users_data[$v_contact_file['create_user']]['last_name']; ?></a></td>
					<td><a href="<?php echo APP_BASE . 'stats/patientfileupload?doc_id='.$v_contact_file['id'].'&id='.$_REQUEST['id'];?>"><?php echo date('d.m.Y', strtotime($v_contact_file['create_date'])); ?></a></td>
				</tr>
			<?php $i++; endforeach; ?>		 		
 		</tbody>
	</table>
</div>
<?php endif;  ?>
<!-- .. -->




<div class="medication_history">
	
	<div class="history_content" >
	
	</div>
</div>






<div class="medication_shared_meds">
	
	<div class="shared_meds_content" >
	
	</div>
</div>




<div class="print_block">
<label>
<?php echo $this->translate("print_medication_plan:"); ?>
</label>
<select name="pdf_layout" id="select_pdf">
	<option value="0"></option>
	<option value="medicationplan"><?php echo $this->translate("pdf_medicationplan")?></option>
	<option value="medicationplanpatient"><?php echo $this->translate("pdf_patient_medicationplan")?></option>
	<option value="medicationplanpatient_active_substance"><?php echo $this->translate("pdf_patient_medicationplan") ." ". $this->translate("medication_drug") ?></option>
	<option value="medicationplanpatient_bedarfsmedication"><?php echo $this->translate("pdf_patient_bedarfsmedication") ?></option>
	<option value="medicationplanpatient_applikation"><?php echo $this->translate("pdf_patient_applikation") ?></option>
	<option value="medicationplanpatient_datamatrix"><?php echo $this->translate("pdf_patient_datamatrix") ?></option>
</select>
 <input  type="submit" id="print_button"  name="print_action" value="<?php echo $this->translate('print')?>"  class="btnsubmit_usersessions"/>
 <br/>
 <?php  if($this->pharmacyorder) : ?>
	<input type="button" class="button" value="Apotheken Bestellung" onclick="location.href='<?php echo APP_BASE; ?>patient/pharmacyorder?id=<?php echo $_REQUEST["id"]; ?>'" />
 <?php  endif; ?>
 	
 <br/>	
	<?php 
		//recipe request button
		if ($this->reciperequest_privileges) {
			echo $this->formButton('reciperequest', $this->translate('reciperequest_button'), array("type"=>"button" ,"class"=>"button", "onclick"=>"window.location.href=String(window.appbase + 'patientnew/reciperequest?id=' + window.idpd)"));
		} 

		//import medication from datamatrix xml
		echo $this->formButton('reciperequest', $this->translate('datamatrix_import_button'), array("type"=>"button" ,"class"=>"button", "onclick"=>"$.fn.datamatrixImport()"));
	?>
	
<!-- TODO-2508 ISPC: Lore 19.08.2019 -->
<?php if($this->pharmacyprivileges) : ?>
	<input type="button" class="button" value="BTM Buch" name="btmbuch" id="btmbuch" onclick="location.href='<?php echo APP_BASE; ?>patient/btmbuch?id=<?php echo $_REQUEST['id']; ?>'" />
<?php endif; ?>

<!-- 
 <button name="print_action"  type="submit" class="medication_edit_button"><?php echo $this->translate("generatepdf")?></button>
 -->
 </div>
</form>

<!-- datamatrix import dialog -->
<?php
	$datamatrix_lang = $this->translate('datamatrix_lang');
?>
<div class="modal" id="datamatix_dialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display:none">
		<?php if($this->ModulePrivileges[189] == true):?>
    <!-- ISPC-2346 Added by Ancuta  18.06.2019 START: -->
       <div id="noCam" style="display: none">
            <div class="s-info"><?php echo $this->translate('No camera available'); ?></div>
        </div>
        <div id="div-video-container">
            <video class="dbrScanner-video" playsinline="true" ></video>
        </div>
    <!-- End-->
    <?php endif;?>    
	<div class="row inprogresss" data-step="inprogress" data-title="<?php echo $this->escape($datamatrix_lang['step_in_progress_title']);?>">
		<?php echo $this->escape($datamatrix_lang['step_in_progress_infotext']);?>
	</div>
	<div class="row errors" data-step="errors" data-title="<?php echo $this->escape($datamatrix_lang['step_errors_title']);?>">
		<?php echo $this->escape($datamatrix_lang['step_errors_infotext']);?>
	</div>
	
	<div class="row hide first_step" data-step="1" data-title="<?php echo $this->escape($datamatrix_lang['step1_title']);?>">
    
    		
		
		<div class="datamatrix_xml_div">
		<label>
			<?php echo $this->escape($datamatrix_lang['step1_label']);?>
			<textarea class='datamatrix_xml' style="width:99%; height: 300px;"></textarea>
		</label> 
		
		<div class='infotext'>
			<?php echo $this->escape($datamatrix_lang['step1_infotext']);?>
		</div>
	   </div>
		
	</div>
	
	<div class="row hide second" data-step="2" data-title="<?php echo $this->escape($datamatrix_lang['step2_title']);?>"  >
		 
		<form id="datamatrixSelected" name="datamatrixSelected" method="post" >
			<div class="medication_html_grid"></div>
		</form>
		
		<div class='infotext'>
			<?php echo $this->escape($datamatrix_lang['step2_infotext']);?>
		</div>
	</div>
	
	<div class="row hide" data-step="3" data-title="<?php echo $this->escape($datamatrix_lang['step3_title']);?>">		
		<div class='infotext'>
			<?php echo $this->escape($datamatrix_lang['step3_infotext']);?>
		</div>
	</div>
	
</div>
<!-- eo datamatrix import dialog -->

<div id="MedicSet">
	<div class="sets_content" >
	
	</div>

</div>

<div class="medication_sets">
	
	<div class="medication_sets_content" >
	
	</div>
</div>