<!-- Maria:: Migration ISPC to CISPC 08.08.2020 -->
<?
$set_type = $this->set_type;
$patient_time_scheme = $this->intervals;

$escalation = array("1"=>"I","2"=>"II","3"=>"III");
// for ISPC-2247 changes were made to this page (Ancuta 06.11.2018) 
?>

<script type="text/javascript">
$('.all_sets_medication').each(function(){
	if($(this).is(':checked')){
		$('#select_all_cb_medication').attr('checked', true)
	}
});

$('#select_all_cb_medication').live('click', function(){
	
	if($(this).is(':checked')){
		$('.all_sets_medication').each(function(){
			$(this).attr('checked', true)
		});
	} else {
		$('.all_sets_medication').each(function(){
			$(this).attr('checked', false)
		});
	}
});
</script>

<style>
	.modal_drop{
		width: 100%;
	}
	.modal_textinput{
		width: 95%;
	}
</style>

<input type="hidden"  name="set_type"  value="<? echo $set_type;?>" class="modal_textinput"/>
<table class="datatable">
	<tr>
		<!-- <th> # </th> -->  
		<!-- ISPC-2247 pct.2 Lore 30.04.2020 -->  
		<th> <input type="checkbox" id="select_all_cb_medication" class="all_sets_medication" /> </th>
		
		<th> <?php echo $this->translate('2247 - label_eskalation')?></th>
		<th> <?php echo $this->translate('2247 - medication_drug')?></th>
		<th> <?php echo $this->translate('2247 - medication_dosage')?></th>
		<th> <?php echo $this->translate('2247 - medication_frequency')?></th>
		<th> <?php echo $this->translate('2247 - medication_dosage_form')?></th>
		<th> <?php echo $this->translate('2247 - medication_type')?></th>
		<!--<th> <?php echo $this->translate('2247 - medication_indication')?></th> -->
		<th> <?php echo $this->translate('2247 - comment')?></th>
	</tr>
<?php $nrmed = 1;  foreach($this->set_items as $k => $item):?>
<tr>
	<td>
		<input type="checkbox" name="item[<?php echo $nrmed?>][add_medication]" value="1" class="all_sets_medication" />
	</td>
	
	<td>
		<?php echo $this->formSelect('item['.$nrmed.'][escalation]', '', array("class"=>"modal_drop"), $escalation) ?>
	</td>
	
	<td>
		<input type="text" readonly="readonly" name="item[<?php echo $nrmed?>][drug]"  value="<? echo $item['drug'];?>" class="modal_textinput"/>
		<input type="text" readonly="readonly" name="item[<?php echo $nrmed?>][medication]"  value="<? echo $item['medication'];?>"  class="modal_textinput" />
		<input type="hidden" readonly="readonly" name="item[<?php echo $nrmed?>][source]"  value="<? echo $item['source'] ;?>" class="modal_textinput"/>
		<!-- ISPC-2554 pct.1 Carmen 08.04.2020 -->	
		<input type="hidden" readonly="readonly" name="item[<?php echo $nrmed?>][atc]"  value="<? echo $item['atc'] ;?>" class="modal_textinput"/>
		<input type="hidden" readonly="readonly" name="item[<?php echo $nrmed?>][unit]"  value="<? echo $item['unit'] ;?>" class="modal_textinput"/>
		<!-- //-- -->
	</td>
	
	
	<!-- ISPC-2247 pct.1 Lore 06.05.2020 --> 
	<?php $schema_different = 0; ?>	
	<td>
		<? if (!empty($item['dosage_array']) ): ?>
				<? if (!empty($item['dosage_array_schema']) ): ?>
				
					<?php foreach($item['dosage_array_schema'] as $ks => $schema):?>
					<table>
    					<tr>
    					 	<? if ($schema  ==  $patient_time_scheme[$ks]): ?>    					 	
    					 		<th style="width : 40px;"><? echo $schema ;?></th> 
    					 		
    					 		<td style="width : 50px;"><? echo $item['dosage_array'][$ks];?></td> 
                			 	<input type="hidden" readonly="readonly" name="item[<?php echo $nrmed?>][dosage_<?php echo $ks?>]"  value="<? echo $item['dosage_array'][$ks] ;?>" class="modal_textinput"/>	
    					 		<input type="hidden" readonly="readonly" name="item[<?php echo $nrmed?>][schema_<?php echo $ks?>]"  value="<? echo $schema ;?>" class="modal_textinput"/>	
    					 		
    					   	<?php else :?>
								<?php $schema_different = 1; ?>	
    							<th style="width : 40px; color: red;"><? echo $schema ;?></th> 
    							<td style="width : 50px;"><? echo $item['dosage_array'][$ks];?></td> 
    							
            				<?php endif;?>
                		</tr>
            		</table>
					<?php endforeach;?>

        		<?php else :?>
            			<?php if( count($item['dosage_array']) <= 1):?>
            				<input type="hidden" readonly="readonly" name="item[<?php echo $nrmed?>][dosage]"  value="<? echo $item['dosage'][0] ;?>" class="modal_textinput"/>	
            				<? echo reset($item['dosage_array']) ?>
            			<?php else :?>
            				<?php echo $this->formSelect('item['.$nrmed.'][dosage]', '', array("class"=>"modal_drop"), $item['dosage_array']) ?>
            			<?php endif;?>

        		<?php endif;?>
        <?php else :?>
        	- 
		<?php endif;?>
	</td> 
	<!-- //. -->
	
	<!-- <td>
		//<? if (!empty($item['dosage_array']) ): ?>
    		//	<?php if( count($item['dosage_array']) <= 1):?>
    		//		<input type="hidden" readonly="readonly" name="item[<?php echo $nrmed?>][dosage]"  value="<? echo $item['dosage'][0] ;?>" class="modal_textinput"/>	
    		//		<? echo reset($item['dosage_array']) ?>
    		//	<?php else :?>
    		//		<?php echo $this->formSelect('item['.$nrmed.'][dosage]', '', array("class"=>"modal_drop"), $item['dosage_array']) ?>
    		//	<?php endif;?>
		//<?php else :?>
		//     - 
		//<?php endif;?>
	</td>  -->
	
	<td>
		<? if (!empty($item['frequency_array']) ): ?>
			<?php if( count($item['frequency_array']) == 1):?>
				<input type="hidden" readonly="readonly" name="item[<?php echo $nrmed?>][dosage_interval]"  value="<? echo reset($item['frequency_array']);?>" class="modal_textinput"/>	
				<? echo reset($item['frequency_array']) ?>
			<?php else :?>
				<?php echo $this->formSelect('item['.$nrmed.'][dosage_interval]', '', array("class"=>"modal_drop"), $item['frequency_array']) ?>
			<?php endif;?>
		<?php else :?>
		 - 			
		<?php endif;?>
		
		
	</td>
	
	<td>
		
		<? if (!empty($item['med_dosage_form_array']) ): ?>
			<?php if( count($item['med_dosage_form_array']) == 1):?>
				<input type="hidden" readonly="readonly" name="item[<?php echo $nrmed?>][dosage_form]"  value="<? echo $item['med_dosage_form'][0];?>" class="modal_textinput"/>	
				<? echo reset($item['med_dosage_form_array']) ?>
			<?php else :?>
				<?php echo $this->formSelect('item['.$nrmed.'][dosage_form]', '', array("class"=>"modal_drop"), $item['med_dosage_form_array']) ?>
			<?php endif;?>
		<?php else :?>
		 - 
		<?php endif;?>
		
		
	</td>
	
	<td>
	
		<? if (!empty($item['type']) ): ?>
			<?php if( count($item['medication_type_array']) == 1):?>
				<input type="hidden" readonly="readonly" name="item[<?php echo $nrmed?>][type]"  value="<? echo $item['type'][0];?>" class="modal_textinput"/>	
				<? echo reset($item['medication_type_array']) ?>
			<?php else :?>
				<?php echo $this->formSelect('item['.$nrmed.'][type]', '', array("class"=>"modal_drop"), $item['medication_type_array']) ?>
			<?php endif;?>
		<?php else :?>
		 - 			
		<?php endif;?>
	</td>
	<!--	
	<td>
		<input type="hidden" readonly="readonly" name="item[<?php echo $nrmed?>][indication]"  value="<? echo $item['indication']['id'];?>" class="modal_textinput"/>
		<span  style="width: 100%; display:block; text-align: center; margin: auto;<?php if(!empty($item['indication']['color'])) : ?>background:#<?=$item['indication']['color'].';' ?><?php endif;?>">
		<? echo $item['indication']['name'];?>
		</span>
	</td>
	-->
	<td>
		<input type="hidden" readonly="readonly" name="item[<?php echo $nrmed?>][indication]"  value="<? echo $item['indication']['id'];?>" class="modal_textinput"/>
		<textarea readonly="readonly" rows="5" cols="20" name="item[<?php echo $nrmed?>][comments]" ><?php echo $item['comments']; ?></textarea>
	</td>
	
</tr>

	<? if ($schema_different == 1): ?>
		<tr><td style="color: red;" colspan=8;> <?php echo $this->translate('ATTENTION  - the set time scheme  does not correspond with the patient time scheme - and the dosages will not be transferred ')?>	</td></tr>
	<?php endif;?>
	
<?php $nrmed++; endforeach;?>

 
</table>