<!-- Maria:: Migration ISPC to CISPC 08.08.2020 -->

<?php 
$patients_details = $this->patients_details;
$medications_array = $this->medications_array;
$medication_blocks = $this->medication_blocks;;


$sets  = $this->sets;

// for ISPC-2247 changes were made to this page (Ancuta 06.11.2018) 
?>

<script type="text/javascript">
$(document).ready(function() { /*------ Start $(document).ready --------------------*/

 

});	/*------ END $(document).ready --------------------*/

function _getSetMedications(set_id){
	var pat = "<?php echo $_REQUEST['id'];?>";
	var set_type = "<?php echo $this->set_type;?>";
	
// 	var url = '<?php echo APP_BASE; ?>patientnew/medicationdeleted?id=<?php echo $_REQUEST["id"]; ?>';
	var url = appbase+'patientmedication/setitems?id='+pat+'&set_id='+set_id+'&set_type='+set_type;
	xhr = $.ajax({
		url : url,
		success : function(response) {
			$('.med_set_container').html(response);
		}
	});
}

</script>

<!-- ISPC-2329 pct.l) Lore 23.08.2019 -->
 
<form action="<?php echo  APP_BASE.'patientmedication/sets?id='.$_REQUEST['id'] ;?>" name="add_set_medication" id="add_set_medication" method="post" >

<div class="form_row">

<?php if( empty($sets)):?>
	<?php echo '<br>Diese "Sets"- Funktion erlaubt Ihnen komfortabel die Möglichkeit hinterlegte Medikamente in einem Patienten hinzuzufügen.
            <br>Diese Sets können Sie selber verwalten und zusammenstellen.<br>Gehen Sie dazu in die Mandanten Einstellungen zum Punkt "Liste -> Krisen-Sets" ' ?>
		<input id= 'nosets' value='1' type='hidden'/>
<?php endif;?>

<?php if( !empty($sets)):?>
	<input id= 'nosets' value='0' type='hidden'/>
	<label><?php echo $this->translate('2247 - select sets '.$this->set_type)?></label>
	<?php echo $this->formSelect('', $this->bid, array('onChange'=>'_getSetMedications(this.value)'), $sets['set_drop']) ?>
<?php endif;?>

</div>
<div class="med_set_container">

</div>
</form>