<?php 
$this->headTitle()->set('ISPC Login Schritt 2');

$this->headMeta("width=device-width, initial-scale=1.0", "viewport");

$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/login-mobile.css');
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/auth.css');


?>
<script type="text/javascript">
window.onload = function() {
    document.getElementById("user").focus();
}
</script>
<div class="row row-logo">
    <div class="col-md-4 col-md-offset-4 col-lg-4 col-lg-offset-4">
        <div class="logo">&nbsp;</div>
    </div>
</div>

<div class="row">
    <div class="col-md-4 col-md-offset-4 col-lg-4 col-lg-offset-4">
        <div class="hjdt">
            <form class="form-horizontal" method="POST">
                <fieldset>
                    <legend>Schritt 2</legend>
                    
                    <?php if ( ! empty($this->error_message)) :?>
                    <div class="alert alert-warning">
                        <?=$this->error_message?>
                    </div>
                    <?php endif; ?>
                    
                    
                    <div class="control-group">
                        <label class="control-label" for="user">Benutzername :</label>
                        <div class="controls">
                            <input id="user" name="username" type="text" class="form-control focus-start">
                        </div>
                        <label class="control-label" for="pass">Kennwort :</label>
                        <div class="controls">
                            <input id="pass" name="password" type="password" class="form-control">
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="singlebutton"></label>
                        <div class="controls">
                            <input type="submit" name="s" class="btn btn-primary" value="Anmelden">
                        </div>
                    </div>
                </fieldset>

                <input type="hidden" name="referer" value="/">
                <?php 
                    //fake nounce csfr... this must be done with send_form to work...
                    $csrf = new Zend_Form_Element_Hash('csrf');
                    $csrf->initCsrfToken();
                    echo $this->formHidden('nonce', $csrf->getValue(), array('salt' => 'unique'));
                ?>
                 
            </form>
            
            <!-- this next block is only for entrust  login -->
            <!-- 
            <span> 
                Hier können Sie Ihr Kennwort ändern oder ein defektes Token melden 
                <a href="https://www.ispc-login.de/IdentityGuardSelfService/"> &gt;&gt;&gt; </a>
            </span>
            <hr>
             -->
            <span class="black"> 
                <a href="http://www.smart-q.de/support/impressum">Impressum</a> 
                | 
                <a href="http://www.smart-q.de/support/datenschutz">Datenschutz</a> 
                <br>© <a href="http://www.smart-q.de/">Smart-Q Softwaresysteme GmbH</a>
            </span>
            
            
        </div>
    </div>
</div>