<?php

/**
 * Anlage14ControlTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @method createIfNotExistsOneBy($fieldName, $value = null, array $data = array())
 * @method findOrCreateOneBy($fieldName, $value = null, array $data = array())
 * 
 * @package    ISPC
 * @subpackage Application (2019-11-06) - ISPC-2426
 * @author     carmen <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Anlage14ControlTable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return Anlage14ControlTable (object)
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Anlage14Control');
    }
    
    /**
     *
     * @param array $ipids
     * @param mixed $hydrationMode
     * @return void|Doctrine_Collection
     */
    public static function findAllAnlage14Controlsaved($ipids = null, $month_select_array_filled = null, $hydrationMode = Doctrine_Core::HYDRATE_ARRAY)
    {
    
    	if (empty($ipids) || empty($month_select_array_filled)) {
    		return; //fail-safe
    	}
    	
    	$month_interval = $month_select_array_filled;
    	array_walk($month_interval, function(&$value) {
    		$value = substr($value, -2);
    	});
    	$month_array_filled = array_values($month_interval);
    	
    	$month_interval = $month_select_array_filled;
    	array_walk($month_interval, function(&$value) {
    		$value = substr($value, 0, 4);
    	});
    	$year_array_filled = array_values($month_interval);
    	
    	return self::getInstance()->createQuery('sh14contr')
    	->select("sh14contr.*")
    	->whereIn('sh14contr.ipid', $ipids)
    	->andWhereIn('MONTH(sh14contr.date)', $month_array_filled)
    	->andWhereIn('YEAR(sh14contr.date)', $year_array_filled)
    	->andWhere('sh14contr.isdelete = "0"')
    	->execute(null, $hydrationMode);
    }
}