<?php

/**
 * AssessmentProblemCourseTable
 * ISPC-2625, AOK Kurzassessment, 04.07.2020, elena
 *
 * cloned from MamboAssessmentProblemCourseTable
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @method createIfNotExistsOneBy($fieldName, $value = null, array $data = array())
 * @method findOrCreateOneBy($fieldName, $value = null, array $data = array())
 *
 * @package    ISPC
 * @subpackage Application (2019-01-04)
 * @author     claudiu <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AokprojectsKurzassessmentProblemCourseTable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return AokprojectsKurzassessmentProblemCourseTable (object)
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AokprojectsKurzassessmentProblemCourse');
    }
/*
    public static function findByAssessmentIdAndAssessmentName($assessment_id, $assessment_name, $hydrateMode){
        if (empty($assessment_id) || !is_string($assessment_name)) {
            return;
        }

        return self::getInstance()->createQuery()
            ->select('*')
            ->where('assessment_id = :assessment_id')
            ->andWhere('assessment_name= :assessment_name')
            ->fetchArray(array('assessment_id' => $assessment_id, 'assessment_name' => $assessment_name), $hydrateMode)
            ;
    }*/
}