<?php
//ISPC-2806 Dragos 28.01.2021
/**
 * ClientComplaintSettingsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @method createIfNotExistsOneBy($fieldName, $value = null, array $data = array())
 * @method findOrCreateOneBy($fieldName, $value = null, array $data = array())
 * 
 * @package    ISPC
 * @subpackage Application (2021-01-27)
 * @author     Ancuta <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ClientComplaintSettingsTable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ClientComplaintSettingsTable (object)
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClientComplaintSettings');
    }
}
