<?php

/**
 * ClientUserTextBoxTable
 * ISPC-2827 Lore 30.03.2021
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClientUserTextBoxTable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClientUserTextBoxTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClientUserTextBox');
    }
    
}