<?php

/**
 * ConnectionMasterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @method createIfNotExistsOneBy($fieldName, $value = null, array $data = array())
 * @method findOrCreateOneBy($fieldName, $value = null, array $data = array())
 * 
 * @package    ISPC
 * @subpackage Application (2020-06-25)
 * @author     Ancuta <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 * * ISPC-2612 Ancuta 25.06.2020
 */
class ConnectionMasterTable extends Pms_Doctrine_Table
{

    /**
     * Returns an instance of this class.
     *
     * @return ConnectionMasterTable (object)
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConnectionMaster');
    }

    public static function _find_connection_details($type, $connection_id = null,$category = false)
    {
        if (empty($type)) {
            return;
        }

        $cm = self::getInstance()->createQuery('cm INDEXBY id')
            ->select('cm.*,cm.id as connection_id,cm.clientid as master_client ,cf.*')
            ->where('list_type =?', $type);
        if ($connection_id) {
            $cm->andWhere('id =?', $connection_id);
        }
        if ($category) {
            $cm->andWhere('list_category =?', $category);
        }
        $cm->leftJoin('cm.ConnectionFollowers as cf');
        $result = $cm->fetchArray();

        return $result;
    }

    public static function _check_client_connection_follower($type, $followers = array())
    {
        if (empty($type)) {
            return;
        }
        
        if($followers && !is_array($followers)){
            $followers = array($followers);
        }

        $cm = self::getInstance()->createQuery('cm INDEXBY id')
            ->select('cm.*,cm.id as connection_id,cm.clientid as master_client ,cf.*')
            ->where('list_type =?', $type);
        $cm->leftJoin('cm.ConnectionFollowers as cf');
        if ($followers) {
            $cm->andWhereIn('cf.clientid', $followers);
        }
        $cm->andWhere('cf.isdelete =?', 0);
        $result = $cm->fetchArray();

        if (empty($result)) {
            return false;
        } else {
            return true;
        }
    }
    
    
    public static function _check_client_connection_follower2category($type, $followers = array(),$category = false)
    {
        if (empty($type)) {
            return;
        }
        
        if($followers && !is_array($followers)){
            $followers = array($followers);
        }

        $cm = self::getInstance()->createQuery('cm INDEXBY id')
            ->select('cm.*,cm.id as connection_id,cm.clientid as master_client ,cf.*')
            ->where('list_type =?', $type);
        $cm->leftJoin('cm.ConnectionFollowers as cf');
        if ($followers) {
            $cm->andWhereIn('cf.clientid', $followers);
        }
        if ($category) {
            $cm->andWhere('list_category =?', $category);
        }
        $cm->andWhere('cf.isdelete =?', 0);
        $result = $cm->fetchArray();

        if (empty($result)) {
            return false;
        } else {
            return true;
        }
    }
    
    
    public static function _find_parent_connection_details($type, $parentid = null, $connection_id = null)
    {
        if (empty($type)) {
            return;
        }
        
        $cm = self::getInstance()->createQuery('cm')
        ->select('cm.*,cm.id as connection_id,cm.clientid as master_client ,cf.*')
        ->where('list_type =?', $type);
        if ($parentid) {
            $cm->andWhere('clientid =?', $parentid);
        }
        if ($connection_id) {
            $cm->andWhere('id =?', $connection_id);
        }
        $cm->leftJoin('cm.ConnectionFollowers as cf');
        $result = $cm->fetchArray();
        
        return $result;
    }
    
    public static function _find_parent_connection_details2category($type, $parentid = null, $connection_id = null, $category = null)
    {
        if (empty($type)) {
            return;
        }
        
        $cm = self::getInstance()->createQuery('cm')
        ->select('cm.*,cm.id as connection_id,cm.clientid as master_client ,cf.*')
        ->where('list_type =?', $type);
        if ($parentid) {
            $cm->andWhere('clientid =?', $parentid);
        }
        if ($connection_id) {
            $cm->andWhere('id =?', $connection_id);
        }
        if ($category) {
            $cm->andWhere('list_category =?', $category);
        }
        $cm->leftJoin('cm.ConnectionFollowers as cf');
        $result = $cm->fetchArray();
        
        return $result;
    }
    
    
    public static  function  _find_parent_followers2connectionType($type,$parentid,$return_s = 'all' ){
        
        if (empty($type)) {
            return;
        }
        if (empty($parentid)) {
            return;
        }
        
        $cm = self::getInstance()->createQuery('cm')
        ->select('cm.*,cm.id as connection_id,cm.clientid as master_client ,cf.*')
        ->where('list_type =?', $type);
        $cm->andWhere('clientid =?', $parentid);
        $cm->leftJoin('cm.ConnectionFollowers as cf');
        $result = $cm->fetchArray();
        
        if($return_s == 'all'){
            return $result;
        }
        elseif($return_s == 'ids'){
            $all_followers_ids = array();
            foreach($result as $k=>$cn){
                foreach($cn['ConnectionFollowers'] as $k=>$cf){
                    $all_followers_ids[] = $cf['clientid'];
                }
            }
            return $all_followers_ids;
            
        }
        
    }
    /**
     * ISPC-2614
     * @return array
     */
    public static function _find_all_lists_connections() {
        
        $cm = self::getInstance()->createQuery('cm')
        ->select('cm.*,cm.id as connection_id,cm.clientid as master_client ,cf.*')
        ->leftJoin('cm.ConnectionFollowers as cf');
        $result = $cm->fetchArray();
        
        
        $list_connection = array();
        foreach($result as $k => $list_info)
        {
            
            $list_connection[$list_info['list_type'] ]['parent2connection'][$list_info['clientid']] =  $list_info['id'];
            
            foreach($list_info['ConnectionFollowers'] as $cf=>$cfdata){
            
                if($cfdata['connection_id'] == $list_info['id']) {
                    $list_connection[$list_info['list_type'] ]['follower2connection'][$cfdata['clientid']] =  $cfdata['connection_id'];
                    $list_connection[$list_info['list_type'] ]['parent2child'] [ $list_info['clientid'] ][] = $cfdata['clientid'];
                    $list_connection[$list_info['list_type'] ]['child2parent'] [ $cfdata['clientid'] ] =   $list_info['clientid'];
                    $list_connection[$list_info['list_type'] ]['childern'] [  ] =   $list_info['clientid'];

                    
                    $list_connection[$list_info['list_type'] ]['parentChild_connection'] [ $list_info['clientid'].'-'.$cfdata['clientid'] ] =   $list_info['id'];
                    $list_connection[$list_info['list_type'] ]['ChildParent_connection'] [ $cfdata['clientid'].'-'.$list_info['clientid'] ] =   $list_info['id'];
                    
                }
            }
        }

        return $list_connection;
        
    }
    
}