<?php

/**
 * CourseshortcutsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @method createIfNotExistsOneBy($fieldName, $value = null, array $data = array())
 * @method findOrCreateOneBy($fieldName = '', $value = null, array $data = array())
 * 
 * @package    ISPC
 * @subpackage Application (2019-05-09)
 * @author     carmen <office@originalware.com>
 */
class CourseshortcutsTable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CourseshortcutsTable
     */
	
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Courseshortcuts');
    }
    
    /**
     *
     * @param mixed $hydrationMode
     * @return void|Doctrine_Collection
     */
    public static function findCourseShortcutDetailsbyshortcut($shortcut, $hydrationMode = Doctrine_Core::HYDRATE_ARRAY)
    {
    	return self::getInstance()->createQuery('sht')
    	->select("sht.*")
    	->where('sht.shortcut = ? ', $shortcut)
    	->andWhere('sht.isdelete = "0"')
    	->execute(null, $hydrationMode);
    }
   
}