<?php

/**
 * ElviGroupsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ElviGroupsTable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ElviGroupsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ElviGroups');
    }
}