<?php

/**
 * ElviOrganizationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ElviOrganizationsTable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ElviOrganizationsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ElviOrganizations');
    }
}