<?php

/**
 * ElviUsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ElviUsersTable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ElviUsersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ElviUsers');
    }
    
}