<?php

/**
 * ElviTransactionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ElviTransactionsTable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ElviTransactionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ElviTransactions');
    }
}