<?php

/**
 * EmergencyPlanSapvIITable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @method createIfNotExistsOneBy($fieldName, $value = null, array $data = array())
 * @method findOrCreateOneBy($fieldName, $value = null, array $data = array())
 * 
 * @package    ISPC-2736 Lore 12.11.2020
 * @subpackage Application (2020-11-12)
 * @author     Loredana <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class EmergencyPlanSapvIITable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return EmergencyPlanSapvIITable (object)
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmergencyPlanSapvII');
    }
}