<?php

/**
 * ExtraFormsClientTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExtraFormsClientTable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExtraFormsClientTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExtraFormsClient');
    }
    
}