<?php

/**
 * FormBlockCustomSettings
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @method createIfNotExistsOneBy($fieldName, $value = null, array $data = array())
 * @method findOrCreateOneBy($fieldName, $value = null, array $data = array())
 * 
 * @package    ISPC
 * @subpackage Application (2019-09-13)
 * @author     carmen <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 * ISPC-2454 
 */
class FormBlockCustomSettingsTable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return FormBlockCustomSettingsTable (object)
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FormBlockCustomSettings');
    }
    
    /**
     *
     * @param mixed $hydrationMode
     * @return void|Doctrine_Collection
     */
    public static function findByClientid($clientid, $hydrationMode = Doctrine_Core::HYDRATE_ARRAY)
    {
    	return self::getInstance()->createQuery('fbs')
    	->select("fbs.*")
    	->where('fbs.clientid = ? ', $clientid)
    	->execute(null, $hydrationMode);
    }

}