<?php

/**
 * FormBlockKeyValueTable
 * //Maria:: Migration CISPC to ISPC 22.07.2020
 * This class has NOT auto-generated by the Doctrine ORM Framework
 *
 * TODO: Nico want to speek with Alex to find out the correct use of this new models
 * TODO: and how to generate this
 */
class FormBlockTimedocumentationClinicTable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return FormBlockTimedocumentationClinicTable (object)
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FormBlockTimedocumentationClinic');
    }
}