<?php

/**
 * FormBlockArtificialEntriesExitsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @method createIfNotExistsOneBy($fieldName, $value = null, array $data = array())
 * @method findOrCreateOneBy($fieldName = '', $value = null, array $data = array())
 * ISPC-2508 Carmen 23.01.2020
 *  Ancuta added to Clinic ISPC (CISPC)  on 18.03.2020
 */
class FormBlockArtificialEntriesExitsTable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FormBlockArtificialEntriesExitsTable
     */
	
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FormBlockArtificialEntriesExits');
    }
   
}