<?php

/**
 * FormBlockProblemsSituationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @method createIfNotExistsOneBy($fieldName, $value = null, array $data = array())
 * @method findOrCreateOneBy($fieldName, $value = null, array $data = array())
 * 
 * @package    ISPC [ISPC-2864]
 * @subpackage Application (2021-04-13)
 * @author     Ancuta <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class FormBlockProblemsSituationsTable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return FormBlockProblemsSituationsTable (object)
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FormBlockProblemsSituations');
    }
}