<?php

/**
 * GroupCourseDefaultPermissionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @method createIfNotExistsOneBy($fieldName, $value = null, array $data = array())
 * @method findOrCreateOneBy($fieldName = '', $value = null, array $data = array())
 * 
 * @package    ISPC
 * @subpackage Application (2019-05-09)
 * @author     carmen <office@originalware.com>
 */
class GroupCourseDefaultPermissionsTable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GroupCourseDefaultPermissionsTable
     */
	
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GroupCourseDefaultPermissions');
    }
    
    /**
     *
     * @param mixed $hydrationMode
     * @return void|Doctrine_Collection
     */
    public static function findCourseShortcutPermissionsbyshortcutid($shortcutid, $hydrationMode = Doctrine_Core::HYDRATE_ARRAY)
    {
    	return self::getInstance()->createQuery('shtp')
    	->select("shtp.*")
    	->where('shtp.shortcutid = ? ', $shortcutid)
    	->execute(null, $hydrationMode);
    }
   
}