<?php

/**
 * Hl7MessagesSentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @method createIfNotExistsOneBy($fieldName, $value = null, array $data = array())
 * @method findOrCreateOneBy($fieldName, $value = null, array $data = array())
 * 
 * @package    ISPC
 * @subpackage Application (2019-02-05)
 * @author     claudiu <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Hl7MessagesSentTable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return Hl7MessagesSentTable (object)
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Hl7MessagesSent');
    }
    
    
    public function findTransmitedInvoices($parent_table = '', $invoice_ids = []) 
    {
        
        if (empty($invoice_ids) || empty($parent_table)) {
            return;//fail-safe
        }
        
        
        if ( ! is_array($invoice_ids)) 
            $invoice_ids = [$invoice_ids];
        
        
        return self::getInstance()->createQuery('fnd')
        ->select('*')
        ->where('parent_table = ?', $parent_table)
        ->andWhereIn('parent_table_id', $invoice_ids)
        ->andWhere('message_type = ?', 'DFT^P03')
        ->fetchArray();
                
    }
    
}