<?php

/**
 * IntenseConnectionsTable
 * Ancuta ISPC-2614
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @method createIfNotExistsOneBy($fieldName, $value = null, array $data = array())
 * @method findOrCreateOneBy($fieldName, $value = null, array $data = array())
 * 
 * @package    ISPC
 * @subpackage Application (2020-07-06)
 * @author     Ancuta <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class IntenseConnectionsTable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return IntenseConnectionsTable (object)
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IntenseConnections');
    }
    
    public static function _find_connection_By_id($conn_id = 0){
        
        if(empty($conn_id)){
            return;
        }
        
        $cm = self::getInstance()->createQuery('cm')->select('cm.*,cf.*,co.*');
        $cm->where('cm.id =?',$conn_id);
        $cm->leftJoin('cm.IntenseConnectionsClients as cf');
        $cm->leftJoin('cm.IntenseConnectionsOptions as co');
        $result = $cm->fetchArray();
        
        return $result ;
    }
    public static function _get_intense_connections(){
        
        $cm = self::getInstance()->createQuery('cm')->select('cm.*,cf.*');
        $cm->leftJoin('cm.IntenseConnectionsClients as cf');
        $result = $cm->fetchArray();
        
        return $result ;
    }
    public static function _find_intense_connectionBetweenClients($client1,$client2,$conn_id = null,$return_options = false,$specific_option = false){
        if (empty($client1) && empty($client2)) {
            return;
        }
        $clients = array($client1,$client2);
 
        $cm = self::getInstance()->createQuery('cm')->select('cm.*,cf.*,co.*');
        if($conn_id){
            $cm->where('cm.id != ?',$conn_id );
        }
        $cm->leftJoin('cm.IntenseConnectionsClients as cf');
        if($return_options){
            $cm->leftJoin('cm.IntenseConnectionsOptions as co');
            if($specific_option){
                $cm->andWhere('co.option_name = ?',$specific_option );
            }
        }
        $cm->andWhereIn('cf.clientid',$clients );
        $result = $cm->fetchArray();

        $connection_clients = array();
        $connection_data = array();
        foreach($result as $key => $ic){
            $connection_data[$ic['id']] = $ic;
            foreach($ic['IntenseConnectionsClients'] as $k=>$d){
                $connection_clients[$d['intense_connection_id']][] = $d['clientid'];
            }
        }
        
        $existing_connections = array();
        foreach($connection_clients as $con_id =>$cls){
            if(in_array($client1,$cls) && in_array($client2,$cls) ){
                if($return_options){
                    $existing_connections[$con_id] = $connection_data[$con_id];
                } else{
                    $existing_connections[] = $con_id;
                }
            }
        }
        
        if (empty($existing_connections)) {
            return false;
        } else {
            return $existing_connections;
        }
    }
    
    
}