<?php

/**
 * MePatientNotificationsHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @method createIfNotExistsOneBy($fieldName, $value = null, array $data = array())
 * @method findOrCreateOneBy($fieldName, $value = null, array $data = array())
 * 
 * @package    ISPC
 * @subpackage Application (2020-01-22)
 * @author     Ancuta <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MePatientNotificationsHistoryTable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return MePatientNotificationsHistoryTable (object)
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MePatientNotificationsHistory');
    }
    
    
    
    /**
     * @ ANCUTA
     * ISPC-2432
     * 12.02.2020
     * @param array $patients
     * @return void|array|Doctrine_Collection
     */
    public static function findNotificationSentToday( $patients = array() )
    {
        if(empty($patients)){
            return;
        }
        
        return self::getInstance()->createQuery('nh')
        ->select("nh.*")
        ->whereIn('nh.ipid ', $patients)
        ->andWhere('date(create_date) = ? ', date('Y-m-d'))
        ->andWhere('notification_type = ? ', 'scheduled')
        ->fetchArray();
    }
}