<?php

/**
 * MePatientDevicesNotificationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @method createIfNotExistsOneBy($fieldName, $value = null, array $data = array())
 * @method findOrCreateOneBy($fieldName, $value = null, array $data = array())
 * 
 * @package    ISPC
 * @subpackage Application (2020-01-22)
 * @author     Ancuta <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 * ISPC-2432
 */
class MePatientDevicesNotificationsTable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return MePatientDevicesNotificationsTable (object)
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MePatientDevicesNotifications');
    }
    
    public static function findByIpid($ipid, $hydrationMode = Doctrine_Core::HYDRATE_ARRAY)
    {
        return self::getInstance()->createQuery('ipes')
        ->select("ipes.*")
        ->where('ipes.ipid = ? ', $ipid)
        ->orderBy('id DESC')
        ->limit(1)
        ->execute(null, $hydrationMode);
    }
}