<?php

/**
 * MePatientQrCodesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @method createIfNotExistsOneBy($fieldName, $value = null, array $data = array())
 * @method findOrCreateOneBy($fieldName, $value = null, array $data = array())
 * 
 * @package    ISPC
 * @subpackage Application (2020-01-29)
 * @author     Ancuta <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 * ISPC-2432 Ancuta 29.01.2020
 */
class MePatientQrCodesTable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return MePatientQrCodesTable (object)
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MePatientQrCodes');
    }
}