<?php

/**
 * MePatientSurveysTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @method createIfNotExistsOneBy($fieldName, $value = null, array $data = array())
 * @method findOrCreateOneBy($fieldName, $value = null, array $data = array())
 * 
 * @package    ISPC
 * @subpackage Application (2020-01-10)
 * @author     Ancuta <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 * ISPC-2432 Ancuta 13.01.2020
 */
class MePatientSurveysTable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return MePatientSurveysTable (object)
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MePatientSurveys');
    }

    
    public static function find_survey_Byid($survey_id = 0)
    {
        if(empty($survey_id)){
            return;
        }
        
        $poa = self::getInstance()->createQuery('s INDEXBY id')
        ->select('s.*,sc.*')
        ->where('s.id =?', $survey_id);
        $poa->leftJoin('s.MePatientSurveysClients as sc')
        ->orderBy('s.survey_name ASC');
        $result = $poa->fetchArray();
        
        return $result;
        
        
    }
    
    public static function find_multiple_survey_Byids($survey_ids = array())
    {
        if(empty($survey_ids)){
            return;
        }
        
        $poa = self::getInstance()->createQuery('s INDEXBY id')
        ->select('s.*,sc.*')
        ->whereIn('s.id', $survey_ids);
        $poa->leftJoin('s.MePatientSurveysClients as sc')
        ->orderBy('s.survey_name ASC');
        $result = $poa->fetchArray();
        
        return $result;
        
        
    }

    
    public static function find_survey_ByClientid($clientid = 0)
    {
        if(empty($clientid)){
            return;
        }
        
        $poa = self::getInstance()->createQuery('s INDEXBY id')
        ->select('s.*,sc.*');
        $poa->leftJoin('s.MePatientSurveysClients as sc')
        ->andWhere('sc.clientid=?',$clientid)
        ->orderBy('s.survey_name ASC');
        $result = $poa->fetchArray();
        
        return $result;
        
        
    }
}