<?php

/**
 * PatientArtificialEntriesExitsTable
 * #ISPC-2512PatientCharts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @method createIfNotExistsOneBy($fieldName, $value = null, array $data = array())
 * @method findOrCreateOneBy($fieldName, $value = null, array $data = array())
 * 
 * @package    ISPC
 * @subpackage Application (2020-01-17) ISPC-2508
 * @author     carmen <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 * Ancuta added to Clinic ISPC (CISPC)  on 18.03.2020
 */
class PatientArtificialEntriesExitsTable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PatientArtificialEntriesExitsTable (object)
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PatientArtificialEntriesExits');
    }
    
    /**
     *
     * @param mixed $hydrationMode
     * @return void|Doctrine_Collection
     */
    public static function findAllByClientArtIds($artids,  $hydrationMode = Doctrine_Core::HYDRATE_ARRAY)
    {
    	if(empty($artids))
    	{
    		return;
    	}
    	
    	return self::getInstance()->createQuery('part')
    	->select("part.*")
    	->whereIn('part.option_id', $artids)
    	->andWhere('isremove = "0"')
    	->execute(null, $hydrationMode);
    }
    
}