<?php

/**
 * PatientsOrdersDetailsLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @method createIfNotExistsOneBy($fieldName, $value = null, array $data = array())
 * @method findOrCreateOneBy($fieldName, $value = null, array $data = array())
 * 
 * @package    ISPC
 * @subpackage Application (2019-01-15)
 * @author     Ancuta <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PatientsOrdersDetailsLogTable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PatientsOrdersDetailsLogTable (object)
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PatientsOrdersDetailsLog');
    }
    
    

    /**
     * Ancuta
     * 15.01.2019
     * @param number $order_id
     * @return void|mixed
     */
    public static function find_log_by_order( $order_id = 0)
    {
        if (empty($order_id)) {
            return;
        }
        return self::getInstance()->createQuery()
        ->select('*')
        ->where('order_id = ? ', $order_id)
        ->orderBy('create_date ASC')
        ->fetchArray();
    }
    
}