<?php

/**
 * PatientsOrdersPeriodsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @method createIfNotExistsOneBy($fieldName, $value = null, array $data = array())
 * @method findOrCreateOneBy($fieldName, $value = null, array $data = array())
 * 
 * @package    ISPC
 * @subpackage Application (2019-01-10)
 * @author     Ancuta <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PatientsOrdersPeriodsTable extends Pms_Doctrine_Table
{

    /**
     * Returns an instance of this class.
     *
     * @return PatientsOrdersPeriodsTable (object)
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PatientsOrdersPeriods');
    }

    public static function find_all_patients_periods($ipids = array(), $status = false, $only_opened = false)
    {
        if (empty($ipids)) {
            return;
        }
        
        $x = self::getInstance()->createQuery('poa')
            ->select('poa.*')
            ->whereIn('ipid', $ipids);
        if (! empty($status)) {
            $x->andWhere('action_status = ? ', $status);
        }
        
        if ($only_opened) {
            $x->andWhere('end_date is NULL');
        }
        $result = $x->fetchArray();
        
        return $result;
    }
}