<?php

/**
 * PatientDiagnoOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @method createIfNotExistsOneBy($fieldName, $value = null, array $data = array())
 * @method findOrCreateOneBy($fieldName, $value = null, array $data = array())
 * 
 * @package    ISPC
 * @subpackage Application (2019-04-11)
 * @author     carmen <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PatientDiagnoOrderTable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PatientDiagnoOrderTable (object)
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PatientDiagnoOrder');
    }
    
    public static function findDiagnoOrder($ipids = null, $hydrationMode = Doctrine_Core::HYDRATE_ARRAY)
    {
    	if(!is_array($ipids))
    	{
    		$ipids = array($ipids);
    	}
    
    	if (empty($ipids)) {
    		return; //fail-safe
    	}
    	
    	return self::getInstance()->createQuery('dord')
    	->select("*")
    	->whereIn('ipid', $ipids)
    	->execute(null, $hydrationMode);
    }
}