<?php

/**
 * PatientDrugplanTransitionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @method createIfNotExistsOneBy($fieldName, $value = null, array $data = array())
 * @method findOrCreateOneBy($fieldName, $value = null, array $data = array())
 * 
 * @package    ISPC-2524 pct.2)  Lore 15.01.2020
 * @subpackage Application (2020-01-15)
 * @author     Ancuta <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PatientDrugplanTransitionTable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PatientDrugplanTransitionTable (object)
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PatientDrugplanTransition');
    }
}
