<?php

/**
 * PatientDiagnosisTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @method createIfNotExistsOneBy($fieldName, $value = null, array $data = array())
 * @method findOrCreateOneBy($fieldName, $value = null, array $data = array())
 * 
 * @package    ISPC
 * @subpackage Application (2019-11-21)
 * @author     carmen <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PatientDiagnosisTable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PatientDiagnosisTable (object)
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PatientDiagnosis');
    }
    
    public static function findPatientDiagnoByDiagnoid($diagids = null, $hydrationMode = Doctrine_Core::HYDRATE_ARRAY)
    {
    	if(!is_array($diagids))
    	{
    		$diagids = array($diagids);
    	}
    
    	if (empty($diagids)) {
    		return; //fail-safe
    	}
    	
    	return self::getInstance()->createQuery('pdiag')
    	->select("pdiag.icd_id")
    	->whereIn('icd_id', $diagids)
    	->execute(null, $hydrationMode);
    }
    
    
    
    /**
     * ISPC-2654 Ancuta 07.10.2020
     * @param unknown $ipid
     * @param unknown $hydrationMode
     * @return void|Doctrine_Collection
     */
    public static function find_by_ipid($ipid = null, $hydrationMode = Doctrine_Core::HYDRATE_ARRAY)
    {
        if(empty($ipid)){
    		return; //fail-safe
        }
    	return self::getInstance()->createQuery('pdiag')
    	->select("pdiag.*")
    	->leftJoin('pdiag.PatientDiagnosisClinical')
    	->where('pdiag.ipid =?', $ipid)
    	->execute(null, $hydrationMode);
    }
}