<?php

/**
 * PatientsOrdersAllowedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @method createIfNotExistsOneBy($fieldName, $value = null, array $data = array())
 * @method findOrCreateOneBy($fieldName, $value = null, array $data = array())
 * 
 * @package    ISPC
 * @subpackage Application (2018-12-21)
 * @author     Ancuta <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PatientsOrdersAllowedTable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PatientsOrdersAllowedTable (object)
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PatientsOrdersAllowed');
    }
    
    /**
     * @Ancuta
     * 21.12.2018
     * @param string $period
     * @param number $clientid
     *  ISPC-2281
     */
    public static function find_patients_inPeriod($period = false, $ipids = array())
    {
        if (empty($period)) {
            return ;
        }
    
        $x = self::getInstance()->createQuery('poa')
        ->select('poa.*,pod.id,pod.ipid')
        ->where('(start_date BETWEEN ? AND ?) or (start_date <= ?) ',array($period['start'],$period['end'],$period['start']))
        ->leftJoin('poa.PatientsOrdersDetails as pod')
        ->fetchArray()
//             dd($x->getSqlQuery());
        ;
        
        return $x;
    }
    
    
    
    
    
}