<?php

/**
 * PatientSurveySettingsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @method createIfNotExistsOneBy($fieldName, $value = null, array $data = array())
 * @method findOrCreateOneBy($fieldName, $value = null, array $data = array())
 * 
 * @package    ISPC
 * @subpackage Application (2019-08-22)
 * @author     carmen <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PatientSurveySettingsTable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PatientSurveySettingsTable (object)
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PatientSurveySettings');
    }
    
    /**
     *
     * @param mixed $hydrationMode
     * @return void|Doctrine_Collection
     */
    public static function findByIpid($ipid, $hydrationMode = Doctrine_Core::HYDRATE_ARRAY)
    {
    	return self::getInstance()->createQuery('ipes')
    	->select("ipes.*")
    	->where('ipes.ipid = ? ', $ipid)
    	->orderBy('id DESC')
    	->limit(1)
    	->execute(null, $hydrationMode);
    }

}