<?php

/**
 * PharmaPatientDrugplanTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @method createIfNotExistsOneBy($fieldName, $value = null, array $data = array())
 * @method findOrCreateOneBy($fieldName, $value = null, array $data = array())
 * 
 * @package    ISPC
 * @subpackage Application (2020-02-08)
 * @author     Ancuta <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 * ISPC-2507
 */
class PharmaPatientDrugplanTable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PharmaPatientDrugplanTable (object)
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PharmaPatientDrugplan');
    }
    
    
    public static function find_by_request_ids($request_ids = array()) {
        
        if(empty($request_ids )  ){
            return array();
        }
   
        
        
          $ppdr = self::getInstance()->createQuery('ppd')
         ->select('ppdr.*,ppd.*,ppdd.*,ppde.*')
         ->whereIn('ppd.pharma_request_id', $request_ids);
         $ppdr->leftJoin('ppd.PharmaPatientDrugplanDosage as ppdd')
         ->leftJoin('ppd.PharmaPatientDrugplanExtra as ppde')
         ;
         //         dd($ppdr->getSqlquery());
         $result = $ppdr->fetchArray();
         
         return $result;
         
        
        
    }
}