<?php

/**
 * PlansMediPrintSettingsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @method createIfNotExistsOneBy($fieldName, $value = null, array $data = array())
 * @method findOrCreateOneBy($fieldName, $value = null, array $data = array())
 * 
 * @package    ISPC
 * @subpackage Application (2019-05-28) ISPC-2162
 * @author     carmen <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PlansMediPrintSettingsTable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PlansMediPrintSettingsTable (object)
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlansMediPrintSettings');
    }
    
    /**
     *
     * @param mixed $hydrationMode
     * @return void|Doctrine_Collection
     */
    public static function findAllClientPlansMediPrintSettings($clientid, $hydrationMode = Doctrine_Core::HYDRATE_ARRAY)
    {    
    	return self::getInstance()->createQuery('plm')
    	->select("plm.*")
    	->where('plm.clientid = ? ', $clientid)
    	->execute(null, $hydrationMode);
    }
    
}