<?php

/**
 * RlpProductsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @method createIfNotExistsOneBy($fieldName, $value = null, array $data = array())
 * @method findOrCreateOneBy($fieldName, $value = null, array $data = array())
 * 
 * @package    ISPC
 * @subpackage Application (2019-01-30)
 * @author     Ancuta <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 * TODO-2058 
 */
class RlpProductsTable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return RlpProductsTable (object)
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RlpProducts');
    }

    /**
     * 
     * @param unknown $list
     * @param unknown $clientid
     * @param unknown $shortcuts
     * @return unknown|multitype:string
     */
 
    
    public function find_client_products($client)
    {
        if(empty($client)){
            return false;
        }
        
        $rlp_invoice = new RlpInvoices();
        $default_products = $rlp_invoice->rlp_products_ident();
        
 
        $res = self::getInstance()->createQuery('rlp')
        ->select('*')
        ->where('client =?', $client)
        ->fetchArray();
        ;
        
        if($res)
        {
            foreach($res as $k_res => $v_res)
            {
                $res_prices[$v_res['shortcut']] = $v_res['identification'];
            }
    
            return $res_prices;
        }
        else
        {
            
            //in case of finding nothing
            return $default_products;
        }
    }
    
}