<?php

/**
 * SurveyResultScoresTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @method createIfNotExistsOneBy($fieldName, $value = null, array $data = array())
 * @method findOrCreateOneBy($fieldName, $value = null, array $data = array())
 * 
 * @package    ISPC
 * @subpackage Application (2019-09-11)
 * @author     Ancuta <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 * ISPC-2411
 */
class SurveyResultScoresTable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return SurveyResultScoresTable (object)
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SurveyResultScores');
    }
    
    
    public static function findByPatient2chain( $patient2chain = 0, $hydrationMode = Doctrine_Core::HYDRATE_ARRAY)
    {
        if(empty($patient2chain)){
            return;
        }
        
        return self::getInstance()->createQuery('srs')
        ->select("srs.*")
        ->where('srs.survey_took = ? ', $patient2chain)
        ->execute(null, $hydrationMode);
    }
}