<?php

/**
 * SurveyEmailsLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @method createIfNotExistsOneBy($fieldName, $value = null, array $data = array())
 * @method findOrCreateOneBy($fieldName, $value = null, array $data = array())
 * 
 * @package    ISPC
 * @subpackage Application (2019-08-21)
 * @author     carmen <office@originalware.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 * ISPC-2411
 */
class SurveyEmailsLogTable extends Pms_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return SurveyEmailsLogTable (object)
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SurveyEmailsLog');
    }
    
    /**
     *
     * @param mixed $hydrationMode
     * @return void|Doctrine_Collection
     */
    public static function findAllByClientid($clientid, $hydrationMode = Doctrine_Core::HYDRATE_ARRAY)
    {
    	$cols = self::getInstance()->getColumnNames();
    	
    	return array_merge(array($cols), self::getInstance()->createQuery('iel')
    	->select("iel.*")
    	->where('iel.clientid = ? ', $clientid)
    	->execute(null, $hydrationMode));
    }

}