<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>ISPC</title>
</head>
<body>

    <h1 id="errorOccur_heading"><? echo $this->translate('an_error_occured'); ?></h1>
    <h2 id="errorMsg_heading">&nbsp;</h2>

    <?=(APPLICATION_ENV == 'production') ? "<!--" :  "";?>
    
    <p><?php echo $this->message ?></p>

    <?php if (isset($this->exception)): ?>
        <h3 id="ExcepInfo_heading">Exception information:</h3>
        <p id="excepGetMsg_p">
            <b>Message:</b> <?php echo $this->exception->getMessage() ?>
        </p>
        
        <h3 id="stackTrace_Heading">Stack trace:</h3>
        <pre>
            <?php echo $this->exception->getTraceAsString() ?>
        </pre>
    <?php endif; ?>

  <h5 id="RequePar_heading">Request Parameters:</h5>
  <pre><?php echo var_export($this->request->getParams(), true) ?>
  </pre>

  <?=(APPLICATION_ENV == 'production') ? "-->" :  "";?>
  
</body>
</html>
