<div id="layout_result_messages">
    <?php if (count($this->SuccessMessages)) : ?>
    <!--  SuccessMessages -->
        <ul id="messages" class="success">
        <?php foreach ($this->SuccessMessages as $message) : ?>
            <li><?php echo $this->escape($message); ?></li>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>
    <?php if (count($this->ErrorMessages)) : ?>
    <!--  ErrorMessages -->
        <ul id="messages" class="err">
        <?php foreach ($this->ErrorMessages as $message) : ?>
            <li><?php echo $this->escape($message); ?></li>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>
</div>

<?php
$this->headLink()->appendStylesheet(RES_FILE_PATH.'/css/pagination_style.css');
$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/data_tables/jquery.dataTables.js');
$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/data_tables/dataTables.jqueryui.js');
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/data_tables/dataTables.jqueryui.css');

$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/page-css/projects.css');

?>

<script type="text/javascript">

    var btm_special_user = false;
    <?php if ( $this->btm_special_user ) : ?>
    btm_special_user =  true;
    <?php endif; ?>
        
    var DEBUGMODE = <?=APPLICATION_ENV == 'development' ? 'true' : 'false' ?>;
    
</script>

<div class="tab_container" >
    <div>
        <div id="tabs_projects">
        
            <ul>
                <li><a href="#tabs-1"><?=$this->translate('[Projects Open]');?></a></li>
                <li><a href="#tabs-2"><?=$this->translate('[Projects Prepare]');?></a></li>
                <li><a href="#tabs-3"><?=$this->translate('[Projects Closed]');?></a></li>
            </ul>

            <div id="tabs-1">
                <div id="open-projects">
                    <?=$this->translate('[Projects Open legend]')?>
                    <?=$this->formButton('btn_add_new_project', $this->translate('[Add New Project]') , array('style'=>'float:right', 'onClick' => 'return newProjectDialog();'))?>                
                </div>
            </div>
            
            <div id="tabs-2">
                <div id="prepare-projects">
                    <?=$this->translate('[Projects Prepare legend]')?>
                    <?=$this->formButton('btn_add_new_project', $this->translate('[Add New Project]') , array('style'=>'float:right', 'onClick' => 'return newProjectDialog();'))?>
                </div>
            </div>
            
            <div id="tabs-3">
                <div id="closed-projects">
                    <?=$this->translate('[Projects Closed legend]')?>
                    <?=$this->formButton('btn_add_new_project', $this->translate('[Add New Project]') , array('style'=>'float:right', 'onClick' => 'return newProjectDialog();'))?>                    
                </div>
            </div>
            
            <table id="projects_dtable" class="selector_table_projects datatable" style="width:100%;">
                <tr>
                    <td colspan="6"><?php echo $this->translate('loadingpleasewait');?></td>
                </tr>
            </table>    
                
        </div>
        
    </div>

    
</div>



<!-- datapicker image -->
<div id="calImgs" style="display: none;">
    <img id="calImg" src="<?php echo RES_FILE_PATH; ?>/images/calendar.png" alt="Popup" class="trigger">
</div>


<!-- Add a new project DIALOG, also edit a project -->
<div id="new_project_dialog" style="overflow-y: none; display:none">

    <?= $this->formHidden("project_ID" , ""); ?>
    
    <span>
        <label class="w100 required" style="display: inline-block"><?= $this->translate('[Project name]'); ?></label>
        <?= $this->formText("name" , "", array('class'=>'w400')); ?>
    </span>
    <br/>
    
    <span style="padding-right:20px;">
        <label class="w100 required" style="display: inline-block"><?= $this->translate('[Project OPEN from]'); ?></label>
        <?= $this->formText("open_from", "", array('class'=>'w100 date')); ?>
    </span>
    <span>
        <label class="w50 required" style="display: inline-block"><?= $this->translate('[Project OPEN till]'); ?></label>
        <?= $this->formText("open_till", "", array('class'=>'w100 date')); ?>
    </span>
    <br/>
    <!-- 
    <span style="padding-right:20px;">
        <label class="w100 required" style="display: inline-block"><?= $this->translate('[Project prepare from]'); ?></label>
        <?= $this->formText("prepare_from", "", array('class'=>'w100 date')); ?>
    </span>
    <span>
        <label class="w50 required" style="display: inline-block"><?= $this->translate('[Project prepare till]'); ?></label>
        <?= $this->formText("prepare_till", "", array('class'=>'w100 date')); ?>
    </span>
    <br/>
     -->
     
    <br/>
    <span>
        <label style="display: inline-block"><?= $this->translate('[Project small description]'); ?></label>
        <?= $this->formTextarea("description", "", array('class' => 'elstic', 'rows'=> '4', cols=>'70')); ?>
    </span>
    <br/>
    
    <span id="error_messages" style="color: red; font-weight: bold"></span>
    
</div>









