<?php
$this->headScript()
//->appendFile(RES_FILE_PATH.'/javascript/data_tables/jquery.dataTables.js')
//->appendFile(RES_FILE_PATH.'/javascript/data_tables/dataTables.jqueryui.js')
->appendFile(RES_FILE_PATH . '/javascript/inputmask/dist/jquery.inputmask.bundle.js')
->appendFile(RES_FILE_PATH . '/javascript/jquery.datetimepicker/dist/jquery-ui-timepicker-addon.min.js')
->appendFile(RES_FILE_PATH . '/javascript/jquery.datetimepicker/dist/i18n/jquery-ui-timepicker-de.js');



$this->headLink()
//->appendStylesheet(RES_FILE_PATH.'/css/pagination_style.css')
//->appendStylesheet(RES_FILE_PATH . '/css/data_tables/dataTables.jqueryui.css')
->appendStylesheet(RES_FILE_PATH . '/css/page-css/assessmentbenefitplan.css')
->appendStylesheet(RES_FILE_PATH . '/javascript/jquery.datetimepicker/dist/jquery-ui-timepicker-addon.min.css');

?>

<div style="clear:both"></div>

<!-- datapicker image -->
<div id="calImgs" style="display: none;">
    <img id="calImg" src="<?php echo RES_FILE_PATH; ?>/images/calendar.png" alt="Popup" class="trigger">
</div>


<div id="layout_result_messages">
    <?php if (count($this->SuccessMessages)) : ?>
    <!--  SuccessMessages -->
        <ul id="messages" class="success">
        <?php foreach ($this->SuccessMessages as $message) : ?>
            <li><?php echo $this->escape($message); ?></li>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>
    <div style="display:none">
    <?php if (count($this->ErrorMessages)) : ?>
    <!--  ErrorMessages -->
        <ul id="messages" class="err">
        <?php foreach ($this->ErrorMessages as $message) : ?>
            <li><?php echo $this->escape($message); ?></li>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>
    </div>
</div>

<!-- inline script -->
<script type="text/javascript">
$(document).ready(function() {
    //add vars
});
</script>

<?php
    //echo the form

    $this->form
    ->setAction($this->url() . "?id=" . $this->enc_id)
    ->setMethod(Zend_Form::METHOD_POST)
    ->setAttrib('novalidate', true) // this form is not html5 friendly.. it has closed accordions
    ->setAttrib('autocomplete', false) // this form is not html5 friendly.. it has closed accordions
    ->setAttrib("id", "wlassessment_form")
    ->setAttrib("class", "wlassessment_form_class livesearchFormEvents assessmentproblems_form_class")
    ->setAttrib("onsubmit", "return form_submit_validate();");
        


    echo $this->form;
?>
