<?php
// ISPC-2432 Ancuta 13.01.2020
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/page-css/mepatient/style.css');
?>

<style>
.outer{
	width:100%!important;
}
#Wrapper{
	width:100%!important;
}

#MainContent{
	width:calc(100% - 220px)!important;
}

.users-select-dd{
    width:100%;
    min-width: 1010px!important;
	max-width:calc(100% - 220px)!important;
}

.nv-container .form-element input[type="text"], .nv-container .form-element select, .nv-container .form-element textarea{
	max-width:1074px!important;
}

.nv-container .form-element .users-select{
	max-width:1340px!important;
}
.users-select-dd .scrollable-container{
    padding:2px!important;
}

.users-select-dd ul.checkbox-container li{
    width: 19%;
}
.users-select-dd ul.checkbox-container li label{
   word-wrap: break-word!important;
}

</style>




<br/>
<a href="<?php echo $this->url(array('controller'=>'mepatient' , 'action' => 'surveys')) ;?>"><?php echo $this->translate("back")?></a>
<br/>


<div class="nv-container">
	<h1><? echo $this->translate('mePateint-ad survey title') ?></h1>
<form action="" method="post" name="save_survey" id="save_survey">
    
    	
    <div class="form-element">
		<label style="width:16%"><? echo $this->translate('mePateint-survey_name') ?></label>
		<input type="text"  tabindex="1" name="survey_name"  value="<? echo $this->survey_name ?>">
    	<div class="err"><? echo $this->error_survey_name;?></div>
	</div>	
    	
    <div class="form-element">
		<label style="width:16%"><? echo $this->translate('mePateint-survey_url') ?></label>
		<input type="text"  tabindex="1" name="survey_url"  value="<? echo $this->survey_url ?>">
    	<div  class="err"> <? echo $this->error_survey_url ?> </div>
	</div>	
    <div class="form-element">
		<label style="width:16%"><? echo $this->translate('mePateint-survey_painpool_id') ?></label>
		<input type="text"  tabindex="1" name="painpool_survey_id"  value="<? echo $this->painpool_survey_id ?>">
    	<div  class="err"><? echo $this->error_survey_painpool_survey_id ?></div>
	</div>	
    	
	<div class="form-element">	
		<label><? echo $this->translate('mePateint-clients') ?></label>
		<ul class="users-select">
			<li class="btnSelect"><input type="button" class="btnExpand hidden"></li>
		</ul>
		<div class="users-select-dd" style="display: none">
			<div class="close_scc"></div>
			<div class="scrollable-container">
				<div class=" ">
					<ul class="checkbox-container users">
						<?php  foreach($this->clientsarray as $k=>$client):?>
						<?php if($client['isactive'] == 0):?>
							<li class="cb-green"> 
							<input type="checkbox" name="clients[]"  
							id="client_user_<?=$client['id']?>" 
							value="<?=$client['id']?>" 
							data-user_id="<?=$client['id']?>" 
							data-user_name="<?=$client['client_name']?>" 
							data-user_type="user" class="recipients" 
							<?php if(in_array($client['id'],$this->clients)):?>  checked="checked"<? endif;?>
							/>
							<label for="client_user_<?=$client['id'];?>"><?=$client["client_name"];?></label></li>
							
							<?php endif;?>
							
						<?php  endforeach; ?>
					</ul>
				</div>
				
			</div>
		</div>
		 
	</div>
  	<div class="err"><? echo $this->error_survey_clients ?></div>
			
	<input type="submit" name="btnsubmit" id="btnsubmit" class="btnNSsubmit"  tabindex="3" value="<? echo $this->translate('mePateint-add survey') ?>">
	
	</form>
</div>



