<?php
// ISPC-2432 Ancuta 13.01.2020
$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/data_tables/jquery.dataTables.js?'.date('Ymd'));
$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/data_tables/dataTables.jqueryui.js?'.date('Ymd'));
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/data_tables/dataTables.jqueryui.css?' . date('Ymd'));
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/page-css/listscommon.css?' . date('Ymd'));

?>
<div class="add_link">
	<a href="<?php echo $this->url(array('controller'=>'mepatient' , 'action' => 'addsurvey')); ?>"><? echo $this->translate('mep_add_survey'); ?></a>
</div>
<h1><? echo $this->translate('mep_surveylist'); ?></h1>
<br/>
<div style="clear:both;"></div>
	
<table id="table" class="table table-striped table-bordered table-hover table-condensed dataTable no-footer  left_menu_datatable survey_datatable">
</table>	
