<?php 
//ISPC-2892 Ancuta 27.04.2021
?>
<div id="layout_result_messages">
    <?php if (count($this->SuccessMessages)) : ?>
    <!--  SuccessMessages -->
        <ul id="messages" class="success">
        <?php foreach ($this->SuccessMessages as $message) : ?>
            <li><?php echo $this->escape($message); ?></li>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>
    <?php if (count($this->ErrorMessages)) : ?>
    <!--  ErrorMessages -->
        <ul id="messages" class="err">
        <?php foreach ($this->ErrorMessages as $message) : ?>
            <li><?php echo $this->escape($message); ?></li>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>
</div>

<?php
$this->headLink()->appendStylesheet(RES_FILE_PATH.'/css/efa/aidsuppliers.css');

//patientfileupload

$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/qtip/jquery.qtip.min.css?' . date('Ymd'));
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/qtip/jquery.qtip.min.css?' . date('Ymd'));
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/tags_editor/jquery.tag-editor.css?' . date('Ymd'));
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/patientfile.css?' . date('Ymd'));
$this->headScript()->appendFile(RES_FILE_PATH . '/javascript/qtip/jquery.qtip.min.js?' . date('Ymd'));
$this->headScript()->appendFile(RES_FILE_PATH . '/javascript/tags_editor/jquery.tag-editor.js?' . date('Ymd'));
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/page-css/patientfileupload/upload-files.css');
//add file uploader
$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/fine-uploader/fine-uploader.min.js');
$this->headLink()->appendStylesheet(RES_FILE_PATH.'/javascript/fine-uploader/fine-uploader.css');
//rendered-add the fine-uploader file-uploader template
$qqtemplate = Pms_Template::createTemplate(array(), 'templates/qq_fileupload_template_multiple_2018_09.html');
$this->headScript()->setAllowArbitraryAttributes(true)->appendScript($qqtemplate, 'text/template', array("id" => "qq-template", "noescape" => true));






$selected_period = $this->selected_period;
$national_holidays = $this->national_holidays;
$order_grid_patients = $this->order_grid_patients;

if(empty($_REQUEST['tab'])){
    $selected_tab = 'show_aids';
}else{
    $selected_tab = $_REQUEST['tab'];
}
?>

<script type="text/javascript">
var selected_tab= '<?php echo $selected_tab;?>';
    var DEBUGMODE = <?=APPLICATION_ENV == 'development' ? 'true' : 'false' ?>;
    
var isdischarged = <?php echo $this->isdischarged; ?>;
</script>
 <style>
    .fb_versorger_tab_wrap{
        width: 100%;
    }
    
    .fb_versorger_empty{
        height:8px;
    }
    .fb_versorger_tab{
        width:98%;
    }
    .fb_versorger_tab  .fb_versorger_col_head{
        font-weight:bold;
        color: #000;
        line-height: 26px;
        background: #f3f3f3;
        border: 1px solid #c7c7c7;
/*         border-radius: 5px; */
        padding: 10px;
    }
    .fb_versorger_tab  .fb_versorger_col_left{
        padding: 10px;
        width:120px;
    }

    #patversorgereditor .tab_container{
        width: 810px;
    }
</style>
<h1>
<?php echo $this->translate('versorger_title_vv'); ?>
</h1>
<br/>
<div style="width: 100%;">
    <div style="width: 100%;">
        <div id="tabs_files_suppliers" style="width: 100%;">
        
            <ul>
                <li><a href="#tabs-1" id="show_aids" data-tab="show_aids"><?=$this->translate('show aids');?></a></li>
                <li><a href="#tabs-2" id="nursing_files" data-tab="nursing_files"><?=$this->translate('nursing files');?></a></li>
                <li><a href="#tabs-3" id="show_suppliers" data-tab="show_suppliers"><?=$this->translate('show suppliers');?></a></li>
                <li><a href="#tabs-4" id="form_files" data-tab="form_files"><?=$this->translate('formular files');?></a></li>
            </ul>


            <div id="tabs-1" class="show_aids">
             
             
            </div>
            
            <div id="tabs-2" class="nursing_files">
            
            
             <form enctype="multipart/form-data"  action="<?php echo APP_BASE.'/efa/aidsuppliers?id='.$_REQUEST['id'].'&step=save_nursing_files' ?>" method="post" name="frmusernf" id="frmusernf" autocomplete="off" >
          
                	    <div class=" ">
                	    	<div class="ff_file_list">
                    			<?php $i = 1;
                    			foreach ($this->nursing_files as $k_contact_file => $v_contact_file): ?>
                        			<a class="ff_file_link" href="<?php echo APP_BASE . 'stats/patientfileupload?doc_id='.$v_contact_file['id'].'&id='.$_REQUEST['id'];?>" style="width: 100%;display : block; float: left; ">
                        				<span class="ff_date"><?php echo date('d.m.Y', strtotime($v_contact_file['create_date'])); ?></span>
                        				<span class="ff_name"><?php echo $v_contact_file['title']; ?></span>
                        				<span class="ff_user"><?php echo $this->users_data[$v_contact_file['create_user']]['first_name'].', '.$this->users_data[$v_contact_file['create_user']]['last_name']; ?></span>
                        			</a>
                    			<?php $i++; endforeach; ?>		 		
                 			</div>
                			<table width="100%" border="0" cellspacing="0" cellpadding="0">
                				
                				<tr>
                					<td width="23" align="left" valign="top"><strong><?php echo $this->translate('uploadnewfile'); ?></strong></td>
                				</tr>
                				<tr>
                					<td width="23" align="left" valign="top">&nbsp;</td>
                				</tr>
                				<tr>
                					<td align="left" valign="top" class="pf_edit_cont">
                						<div id="TableContentOuter" style="display:<?php echo $this->styleadd ?>">
                							<input type="hidden" name="fileuploads" value="1" /> 
                							<table width="35%" border="0" cellspacing="0" cellpadding="0">
                
                								<tr>
                									<!-- <td width="20% align="left" class="file_upload"><?php echo $this->translate('uploadfile_user_new') ?>*</td>
                									 -->
                									<td align="left" style="padding-bottom: 5px">
                										<!-- ISPC-2642 Ancuta 10-11.08.2020 -->
                										<?php if(isset($_REQUEST['file_id']) && !empty($_REQUEST['file_id']) && !empty($this->current_file_data)):?>
                											<?php $current_file = $this->current_file_data; ?>
                											<div class="qq_file_uploader_placeholder_nf">
                											<div class="  qq-uploader bigupload">
                											    <ul class="qq-upload-list-selector qq-upload-list qq-upload-list-visible" aria-live="polite" aria-relevant="additions removals">
                											    <li class="qq-file-id-0 qq-upload-success" qq-file-id="0">
                											            <div class="qq-file-info">
                											                <span class="infolabel">Dokument benennen:</span>
                											                <div class="qq-file-name">
                											                    <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-progress-bar-selector qq-progress-bar qq-hide"></div>
                											                    <input type="text" class="qquuid_file_title qq-edit-filename-selector" id="edif_file_name" name="title" value="<?php echo $current_file['title'];?>" tabindex="0">
                											                    <input type="hidden" name="post_action" value="update_file_data">
                											                    <input type="hidden" name="file_id" value="<?php echo $current_file['id'];?>" tabindex="0">
                											                    <input type="hidden" name="fileuploads" value="0" /> 
                											                </div>
                											            </div>
                											        </li></ul>
                
                											</div>		
                											</div>		
                                                        <? else: ?>
                                                        <div id="qq_file_uploader_placeholder_nf" class='qq_file_uploader_placeholder qq_file_uploader_multiple' data-parent='fieldset' data-action_name="upload_patient_files" data-tabname="0">
                                                            <noscript>
                                                                Please enable JavaScript to use file uploader.
                                                            </noscript>
                                                        </div>
                                                        <? endif; ?>
                                                        
                                                   </td>
                								</tr>
                								
                							</table>
                
                							<div style="width: 100%;">
                								<input type="hidden" name="active_version" id="active_version" value="0"/> <!-- ISPC - 2129 -->
                								<input type="button" name="btnsubmit" id="btnsubmit-save_nf" value="<?php echo $this->translate('submit') ?>" class="button btnSubmit2018" onclick="checkdischargednew('frmusernf')">
                							</div>
                						</div>
                					</td>
                				</tr>
                			</table>
                 	   </div>	
                </form>
             
             
             
            </div>
            
            
            <div id="tabs-3"  class="show_suppliers">
            
            </div>
            
            
            <div id="tabs-4" class="form_files" >

                <form enctype="multipart/form-data"  action="<?php echo APP_BASE.'/efa/aidsuppliers?id='.$_REQUEST['id'].'&step=save_forms_files' ?>" method="post" name="frmuserff" id="frmuserff" autocomplete="off" >
                	    <div class=" ">
                	    	<div class="ff_file_list">
                    			<?php $i = 1;
                    			foreach ($this->form_files as $k_contact_file => $v_contact_file): ?>
                        			<a class="ff_file_link" href="<?php echo APP_BASE . 'stats/patientfileupload?doc_id='.$v_contact_file['id'].'&id='.$_REQUEST['id'];?>" style="width: 100%;display : block; float: left; ">
                        				<span class="ff_date"><?php echo date('d.m.Y', strtotime($v_contact_file['create_date'])); ?></span>
                        				<span class="ff_name"><?php echo $v_contact_file['title']; ?></span>
                        				<span class="ff_user"><?php echo $this->users_data[$v_contact_file['create_user']]['first_name'].', '.$this->users_data[$v_contact_file['create_user']]['last_name']; ?></span>
                        			</a>
                    			<?php $i++; endforeach; ?>		 		
                 			</div>
                			<table width="100%" border="0" cellspacing="0" cellpadding="0">
                				
                				<tr>
                					<td width="23" align="left" valign="top"><strong><?php echo $this->translate('uploadnewfile'); ?></strong></td>
                				</tr>
                				<tr>
                					<td width="23" align="left" valign="top">&nbsp;</td>
                				</tr>
                				<tr>
                					<td align="left" valign="top" class="pf_edit_cont">
                						<div id="TableContentOuter" style="display:<?php echo $this->styleadd ?>">
                							<input type="hidden" name="fileuploads" value="1" /> 
                							<table width="35%" border="0" cellspacing="0" cellpadding="0">
                
                								<tr>
                									<!-- <td width="20% align="left" class="file_upload"><?php echo $this->translate('uploadfile_user_new') ?>*</td>
                									 -->
                									<td align="left" style="padding-bottom: 5px">
                										<!-- ISPC-2642 Ancuta 10-11.08.2020 -->
                										<?php if(isset($_REQUEST['file_id']) && !empty($_REQUEST['file_id']) && !empty($this->current_file_data)):?>
                											<?php $current_file = $this->current_file_data; ?>
                											<div class="qq_file_uploader_placeholder_ff">
                											<div class="  qq-uploader bigupload">
                											    <ul class="qq-upload-list-selector qq-upload-list qq-upload-list-visible" aria-live="polite" aria-relevant="additions removals">
                											    <li class="qq-file-id-0 qq-upload-success" qq-file-id="0">
                											            <div class="qq-file-info">
                											                <span class="infolabel">Dokument benennen:</span>
                											                <div class="qq-file-name">
                											                    <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-progress-bar-selector qq-progress-bar qq-hide"></div>
                											                    <input type="text" class="qquuid_file_title qq-edit-filename-selector" id="edif_file_name" name="title" value="<?php echo $current_file['title'];?>" tabindex="0">
                											                    <input type="hidden" name="post_action" value="update_file_data">
                											                    <input type="hidden" name="file_id" value="<?php echo $current_file['id'];?>" tabindex="0">
                											                    <input type="hidden" name="fileuploads" value="0" /> 
                											                </div>
                											            </div>
                											        </li></ul>
                
                											</div>		
                											</div>		
                                                        <? else: ?>
                                                        <div id="qq_file_uploader_placeholder_ff" class='qq_file_uploader_placeholder qq_file_uploader_multiple' data-parent='fieldset' data-action_name="upload_patient_files" data-tabname="0">
                                                            <noscript>
                                                                Please enable JavaScript to use file uploader.
                                                            </noscript>
                                                        </div>
                                                        <? endif; ?>
                                                        
                                                   </td>
                								</tr>
                								
                							</table>
                
                							<div style="width: 100%;">
                								<input type="hidden" name="active_version" id="active_version" value="0"/> <!-- ISPC - 2129 -->
                								<input type="button" name="btnsubmit" id="btnsubmit-save_ff" value="<?php echo $this->translate('submit') ?>" class="button btnSubmit2018" onclick="checkdischargednew('frmuserff')">
                							</div>
                						</div>
                					</td>
                				</tr>
                			</table>
                 	   </div>	
                </form>
            
            </div>
   
        </div>
        
    </div>

    
</div>



<!-- datapicker image -->
<div id="calImgs" style="display: none;">
    <img id="calImg" src="<?php echo RES_FILE_PATH; ?>/images/calendar.png" alt="Popup" class="trigger">
</div>

 