<?php //ISPC-2831 Dragos 15.03.2021 ?>
<?php

$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/page-css/efadiagnosis.css');

?>

<style>

</style>

<div style="display: none;"><img id="calImg" src="<? echo RES_FILE_PATH;  ?>/images/calendar.png" alt="Popup" class="trigger"></div>
<div id="diagnosis_and_findings_tabs" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
        <li class="ui-state-default ui-corner-top ui-tabs-selected ui-state-active"><a href="<?=APP_BASE?>efa/diagnosis?id=<?=$_REQUEST['id']?>">Diagnosen</a></li>
        <li class="ui-state-default ui-corner-top"><a href="<?=APP_BASE?>patient/patientfileupload?id=<?=$_REQUEST['id']?>&efa=1">Befunde</a></li>
        <li class="ui-state-default ui-corner-top"><a href="<?=APP_BASE?>efa/interventions?id=<?=$_REQUEST['id']?>">Interventionen</a></li>
        <li class="ui-state-default ui-corner-top"><a href="<?=APP_BASE?>efa/reactions?id=<?=$_REQUEST['id']?>">Reaktionen</a></li>
        <li class="ui-state-default ui-corner-top"><a href="<?=APP_BASE?>efa/vaccinations?id=<?=$_REQUEST['id']?>">Impfstatus</a></li>
        <li class="ui-state-default ui-corner-top"><a href="<?=APP_BASE?>efa/history?id=<?=$_REQUEST['id']?>">bisherige Krankengeschichte</a></li>
    </ul>
    <div id="tabs-1">

        <?php
        $block = $this->icd;
        echo $block['__formHTML'];
        ?>

    </div>
    <div id="tabs-2">
    </div>
    <div id="tabs-3">
    </div>
</div>
<script>
    var pid = '<?php echo $_REQUEST['id']; ?>';
</script>
