<?php 
//ISPC-2864 Ancuta 13.04.2021
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/efa/patientproblems.css');
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/qtip/jquery.qtip.min.css?' . date('Ymd'));
$this->headScript()->appendFile(RES_FILE_PATH . '/javascript/qtip/jquery.qtip.min.js?' . date('Ymd'));

$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/efa/modal-efa.css');

$problems = $this->patient_problems;
$inner_block_width = count($problems) > 0 ?    count($problems) * 280 : 350;  

$situation_array = array('current_situation','hypothesis','measures');

?>
<script type="text/javascript">
$(document).ready(function() {
	
});
</script>
<?php if($this->efa_extension == 'sapv'):?>
<div class="upper_block">
	<div class="ub_left">
		<div class="up_line" id="sapv_block">
			<form method="post" action="" id="sapv_description_save">
				<label class="big">SAPV Auftrag</label>
				<textarea id="sapv_text" name="sapv_description" rows="" cols=""><?php echo $this->patient_sapv_description;?></textarea>
				<button type="submit" class="save_sapv" style="display: block; float:left; margin:5px;" title="SAPV Auftrag aktualisieren"></button>
			</form>
			
		</div>
	</div>
	<div class="ub_right">
		<div class="up_line">
			<label>Letzter Kontakt:</label>
			<span class="up_text_field  up_phone"><?php echo $this->last_phone_date; ?></span>
			<span class="up_text_field  up_contact"><?php echo $this->last_contact_date; ?></span>
		</div>
		<div class="up_line">
			<label>Nächster Kontakt:</label>
			<span class="up_text_field  up_custom_event"><?php echo $this->next_custom_event;?></span>
		</div>
	</div>
</div>
<?php elseif($this->efa_extension == 'bpss'):?>

<div class="upper_block">
	<div class="bpss_modal" id="bpss_modal"></div>
	<h2>Biopschosoziales Modell</h2>
	<div class="ub_left">
		<div class="up_line">
			<?php $bpss_type = "bio"; ?>
			<label class="big"><?php echo $this->translate($bpss_type.'_title'); ?></label>
			<button class="add_bpss" data-bpss_type="<?php echo $bpss_type; ?>">+</button>
			<div class="bpss_container cnt_<?php echo $bpss_type; ?>" data-bpss_type="<?php echo $bpss_type; ?>"  data-recid="1">
			<?php foreach($this->bpss_data[$bpss_type] as $k=>$bpsp):?>
			    <div class="bpss_text_container" data-bpss_type="<?php echo $bpss_type; ?>"  data-recid="<?php echo $bpsp['id']?>"  title="<?php echo $bpsp['qtip']; ?>">
                    <span class="bbps_text"><?php echo $bpsp['bpss_description']?></span> 
                </div>
			<?php endforeach; ?>
			</div>
		</div>
		
		<div class="up_line">
			<?php $bpss_type = "social"; ?>
			<label class="big"><?php echo $this->translate($bpss_type.'_title'); ?></label>
			<button class="add_bpss" data-bpss_type="<?php echo $bpss_type; ?>">+</button>
			<div class="bpss_container cnt_<?php echo $bpss_type; ?>" data-bpss_type="<?php echo $bpss_type; ?>"  data-recid="1">
			<?php foreach($this->bpss_data[$bpss_type] as $k=>$bpsp):?>
			    <div class="bpss_text_container" data-bpss_type="<?php echo $bpss_type; ?>"  data-recid="<?php echo $bpsp['id']?>"  title="<?php echo $bpsp['qtip']; ?>">
                    <span class="bbps_text"><?php echo $bpsp['bpss_description']?></span> 
                </div>
			<?php endforeach; ?>
			</div>
		</div>
		
	</div>
 
	<div class="ub_left">
		<div class="up_line">
			<?php $bpss_type = "psycho"; ?>
			<label class="big"><?php echo $this->translate($bpss_type.'_title'); ?></label>
			<button class="add_bpss" data-bpss_type="<?php echo $bpss_type; ?>">+</button>
			<div class="bpss_container cnt_<?php echo $bpss_type; ?>" data-bpss_type="<?php echo $bpss_type; ?>"  data-recid="1">
			<?php foreach($this->bpss_data[$bpss_type] as $k=>$bpsp):?>
			    <div class="bpss_text_container" data-bpss_type="<?php echo $bpss_type; ?>"  data-recid="<?php echo $bpsp['id']?>"  title="<?php echo $bpsp['qtip']; ?>">
                    <span class="bbps_text"><?php echo $bpsp['bpss_description']?></span> 
                </div>
			<?php endforeach; ?>
			</div>
		</div>
		<div class="up_line">
			<?php $bpss_type = "spiritual"; ?>
			<label class="big"><?php echo $this->translate($bpss_type.'_title'); ?></label>
			<button class="add_bpss" data-bpss_type="<?php echo $bpss_type; ?>">+</button>
			<div class="bpss_container cnt_<?php echo $bpss_type; ?>" data-bpss_type="<?php echo $bpss_type; ?>"   >
			<?php foreach($this->bpss_data[$bpss_type] as $k=>$bpsp):?>
			    <div class="bpss_text_container" data-bpss_type="<?php echo $bpss_type; ?>"  data-recid="<?php echo $bpsp['id']?>"  title="<?php echo $bpsp['qtip']; ?>">
                    <span class="bbps_text"><?php echo $bpsp['bpss_description']?></span> 
                </div>
			<?php endforeach; ?>
			</div>
		</div>
 
	</div>
 
</div>
<?php endif;?>

<div class="full_width">
	<button class="add_btn add_problem"><?php echo $this->translate('add p_problem');?></button>
</div>
<div class="outer_problems_div">
<div class="inner_problems_div" style="min-width:<?echo $inner_block_width + 380;?>px;  width:<?echo $inner_block_width;?>px;  ">
<?php $col_nr = 1; ?>
<?php foreach($problems as $pr_id => $pr_info):?>
	<div  class="problem_container" id="<?php echo $pr_id; ?>">
		<div class="problem_header">
			<button class="edit_btn edit_problem" data-problem_id="<?php echo  $pr_id;?>" ></button>
			<span class="pp_name"><i><?php echo $this->translate('Problem:')?></i> <b><?php echo $pr_info['problem_name']?></b></span>
			<span class="pp_name"><i><?php echo $this->translate('Datum:')?></i> <b><?php echo $pr_info['problem_date']?></b></span>
			
		</div>
		<div class="down_arrow toggle_down_arrow"  data-block_type="current"  data-block_problem="<?php echo  $pr_id;?>" ></div>
   		<div class="problem_current_situations current_<?php echo  $pr_id;?> " >
		<?php foreach($situation_array as $situation_type):?>
		
    		<?php if(!empty($pr_info['problem_situations']['current'][$situation_type])):?>
    			<?php $sit = $pr_info['problem_situations']['current'][$situation_type]; ?>
    			<div class="situation_block type_<?php echo $situation_type?>">
        			<div class="sb_header  show_content" data-problem_id="<?php echo  $pr_id;?>" data-sit_type="<?php echo $situation_type;?>" data-sit_status="latest">
        			  <?php if(strlen($sit['situation_description']) > 0 ):?>
        				<span class="has_content_bubble"></span>
        			<?php endif;?>
        				<h2><?php echo  $this->translate($situation_type.'title');?><br/><span>(Datum: <?php echo date('d.m.Y H:i',strtotime($sit['situation_date'])); ?>)</span></h2>
    				</div>
        			<div class="sb_text content_<?php echo  $pr_id;?>_<?php echo $situation_type;?>_latest">
        				<span id="stl-<?php echo  $pr_id;?>-<?php echo  $sit['id'];?>-<?php echo $situation_type;?>" class="editText" data-problem_situation="1" rel="situation" ><?php echo $sit['situation_description']; ?></span>
        			</div>
        		</div>
    		<?php else: ?>
    			<?php $sit = array(); ?>
    			<div class="situation_block type_<?php echo $situation_type?>">
        			<div class="sb_header  show_content" data-problem_id="<?php echo  $pr_id;?>" data-sit_type="<?php echo $situation_type;?>" data-sit_status="latest">
        				<h2><?php echo  $this->translate($situation_type.'title');?><br/>(Datum: -)</h2>
    				</div>
        			<div class="sb_text content_<?php echo  $pr_id;?>_<?php echo $situation_type;?>_latest" >
        				<span id="stl-<?php echo  $pr_id;?>-<?php echo  "new";?>-<?php echo $situation_type;?>" class="editText" data-problem_situation="1" rel="situation" >Dies ist ein Empty Feld, klicken Sie hier um etwas einzutragen.</span>
        			</div>
        		</div>
    		<?php endif;?>
		<?php endforeach; ?>
   		</div>
   		<?php if(!empty($pr_info['problem_situations']['old'])):?>
		<div class="down_arrow toggle_down_arrow" data-block_type="old"  data-block_problem="<?php echo  $pr_id;?>" ></div>
		<?php endif; ?>
		
		<div class="problem_old_situations  old_<?php echo  $pr_id;?>">
		<?php 
		krsort($pr_info['problem_situations']['old']);
		$kd=1;
		foreach($pr_info['problem_situations']['old'] as $version => $sit_arrs):
		?>
			<div style="display: block;   background: #f3f3f3;" >
			<?php foreach($situation_array as $situation_type):?>
				<?php if(strlen($sit_arrs[$situation_type]['situation_description']) > 0 ):?>
			 	<div class="old_problem_type_block sb_header_old type_<?php echo $situation_type?>">
        			<?php if(strlen($sit_arrs[$situation_type]['situation_description']) > 0 ):?>
        				<span class="has_content_bubble"></span>
        			<?php endif;?>
        			<h2 class="show_content" data-problem_id="<?php echo  $pr_id.$version;?>" data-sit_type="<?php echo $situation_type;?>"  data-sit_status="old"><?php echo  $this->translate($situation_type.' title old values');?>
        				<br>
        				<b style="text-align: center;">(Datum: <?php echo date('d.m.Y H:i',strtotime($sit_arrs[$situation_type]['situation_date'])); ?>)</b>
        			</h2>
            		<div class="old_situation_block_outer content_<?php echo  $pr_id.$version;?>_<?php echo $situation_type;?>_old"  >
            			<div class="sb_text_old" style="margin: 5px;">
            				<?php echo $sit_arrs[$situation_type]['situation_description']; ?> 
            			</div>
            		</div>
        		</div>
    			<?php endif;?>
			<?php endforeach; ?>
			</div>
			<?php $kd++; ?>
			<?php if(count($pr_info['problem_situations']['old']) >= $kd):?>
<!--     			<div class="down_arrow"></div> -->
			<?php endif;?>
		<?php endforeach; ?>
		
		
		
 
		</div>
		
		

	</div>

<?php $col_nr++;?>
<?php endforeach;?>
</div>
</div>
