<?php 
//users2patient.phtml
//ISPC-2894 Ancuta 19.05.2021

$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/efa/users2patient.css');
?>


<?php if (!empty($this->users2patient)):?>
<?php
foreach($this->users2patient as $line => $info):?>
<div class="o_block">
	<div class="o_block_title show_content" data-line="<?php echo $line; ?>" data-userinfo="<?php echo $info['userid'];?>" ><?php echo $info['user_name']; ?> <?php echo $info['assign_date']; ?></div>
	
	<div class="o_block_content content_<?php echo $line; ?>_<?php echo $info['userid'];?>">
	<table class="datatable">
		<tr>
			<th><?php echo $this->translate('street'); ?></th>
			<td><?php echo $info['user_data']['street1']; ?></td>
		</tr>
		<tr>
			<th><?php echo $this->translate('zip'); ?></th>
			<td><?php echo $info['user_data']['zip']; ?></td>
		</tr>
		<tr>
			<th><?php echo $this->translate('city'); ?></th>
			<td><?php echo $info['user_data']['city']; ?></td>
		</tr>
		<tr>
			<th><?php echo $this->translate('phone'); ?></th>
			<td><?php echo $info['user_data']['phone']; ?></td>
		</tr>
		<tr>
			<th><?php echo $this->translate('fax') ?></th>
			<td><?php echo $info['user_data']['fax']; ?></td>
		</tr>
		<tr>
			<th><?php echo $this->translate('email'); ?></th>
			<td><?php echo $info['user_data']['emailid']; ?></td>
		</tr>
		
	</table>
	</div>
</div>
<?php endforeach;?>
<?php else: ?>
	<span><?php echo $this->translate('No assigned users ')?></span>
<?php endif;?>