<?php
// ISPC-2517 Ancuta 14.04.2020 
//#ISPC-2512PatientCharts
$management = $this->management;
?>
<h1><?php echo $this->translate('Fieberkurve - CLient permissions to  events:'); ?></h1>
<form action="" method="post" name="frmcourse" id="frmcourse" >
	<div class="grid">
		<table   id="sort_blocks"  class="datatable" border="0">
		<thead>
			<tr>
				<th><b><?php echo $this->translate('events_names'); ?></b></th>
				<th><b><?php echo $this->translate('available in + button'); ?></b></th>
				<!-- ISPC-2841 Lore 22.03.2021 -->
				<th><b><?php echo $this->translate('show in chart'); ?></b></th>
			</tr>
		</thead>	
			<tbody>
			<?php foreach ($management['events'] as $ke=>$event):?>
			<tr>
				<td><?php echo $this->translate($event.'_label');?></td>
				<td>
					<input name="canaccess[<?php echo $event; ?>]" type="checkbox" class="has_access" value="1" <?php if(in_array($event,$management['canaccess'])): ?>checked="checked"<?php endif; ?> />
				</td>
				<!-- ISPC-2841 Lore 22.03.2021 -->
				<td>
					<input name="show_in_chart[<?php echo $event; ?>]" type="checkbox" class="is_show" value="1" <?php if(in_array($event,$management['show_in_chart'])): ?>checked="checked"<?php endif; ?> />
				</td>
			</tr>
 
			<?php endforeach; ?>
 
			<tr>
				<td colspan="8" valign="top" align="left">
					<input name="submit" id="submit" type="submit" class="button" value="<? echo $this->translate('submit') ?>" />
				</td>
			</tr>
			</tbody>
		</table>
	</div>
</form>