<?php
// Maria:: Migration ISPC to CISPC 08.08.2020
// ISPC-2517 Ancuta 14.04.2020 
//#ISPC-2512PatientCharts
$management = $this->management;
?>

<script>
    $('body').on('click', '#sort_blocks tr td:first-child', function(){
        if($(this).parents('tr').find('.has_access').prop('checked')) {
            $(this).parents('tr').find('.has_access').prop('checked', 0);
        } else{
            $(this).parents('tr').find('.has_access').prop('checked',1);
            }

    });

    $('body').on('click', '#sort_blocks tr:first-child th', function(){

        var col = $(this).parent().children().index($(this))+1;
        var col_tds=$('#sort_blocks tr td:nth-child('+col+')').find('.has_access');
        if($(col_tds).prop('checked')) {
            $(col_tds).prop('checked', 0);
        } else{
            $(col_tds).prop('checked',1);
        }

    });

</script>

<h1><?php echo $this->translate('Fieberkurve - Groups events management'); ?></h1>
<form action="" method="post" name="frmcourse" id="frmcourse" >
	<div class="grid">
		<?php if(!empty($management['final_events'])):?>
		<table   id="sort_blocks"  class="datatable" border="0">
		<thead>
			<tr>
				<th><b><?php echo $this->translate('events_names'); ?></b></th>
				<?php foreach($management['master_groups'] as $gr_id => $gr_name): ?>
					<th><?php echo $gr_name?></th>
				<?php endforeach; ?>
				<th></th>
			</tr>
		</thead>	
			<tbody>
			<?php foreach ($management['final_events'] as $ke=>$event):?>
			<?php if($event['event_name'] != "contact_form_items"):?>
    			<tr class="sort" id="<? echo $event['event_name']?>">
    				<td>
    					<?php echo $this->translate($event['event_name'].'_label');?>
    					<input type="hidden" name="events[order][<?php echo $event['event_name']; ?>]" id="group_order<? echo $event['event_name']?>"  value="<? echo $event['order']?>"/>
    				</td>
    				<?php foreach($management['master_groups'] as $gr_id => $gr_name): ?>
    					<td>
    					<input name="events[has_access][<?php echo $event['event_name']; ?>][<?php echo  $gr_id; ?>]" type="checkbox" class="has_access" value="1" <?php if( in_array($gr_id, $event['permissions2groups'] )): ?>checked="checked"<?php endif; ?> />
    					</td>
    				<?php endforeach; ?>				
    				<td><span class="ui-icon ui-icon-arrowthick-2-n-s" style="display:inline-block; float: right;"></span></td>
    			</tr>
			<?php else: ?>
			
			<tr class="sort" id="<? echo $event['event_name'].'-'.$event['form_type']?>">
				<td>
					Kontaktformular - <?php echo $event['form_type_name'];?>
					<input type="hidden" name="events[order][<?php echo $event['event_name']; ?>][<?php echo $event['form_type']?>]" id="group_order<? echo $event['event_name'].'-'.$event['form_type']?>"  value="<? echo $event['order']?>"/>
				</td>
				<?php foreach($management['master_groups'] as $gr_id => $gr_name): ?>
					<td>
					<input name="events[has_access][<?php echo $event['event_name']; ?>][<?php echo $event['form_type']; ?>][<?php echo  $gr_id; ?>]" type="checkbox" class="has_access" value="1" <?php if( in_array($gr_id, $event['permissions2groups'] )): ?>checked="checked"<?php endif; ?> />
					</td>
				<?php endforeach; ?>				
				<td><span class="ui-icon ui-icon-arrowthick-2-n-s" style="display:inline-block; float: right;"></span></td>
			</tr>
			<?php endif; ?>
			<?php endforeach; ?>
 
			<tr>
				<td colspan="8" valign="top" align="left">
					<input name="submit" id="submit" type="submit" class="button" value="<? echo $this->translate('submit') ?>" />
				</td>
			</tr>
			</tbody>
		
		
		</table>
		<?php else: ?>
		<div class="err">
	 		<?php echo $this->translate('For this client there are no events available! ')?>
	 		</div>
		<?php endif; ?>	
	</div>
</form>