<?php
// ISPC-2517 Ancuta 15.04.2020 
#ISPC-2512PatientCharts
$management = $this->management;
?>
<script type="text/javascript">
	var pid = '<?php echo $_REQUEST['id']; ?>';
</script>
<style>
.groupHeader{
display: none!important;

}
.contactform_dragvbox .contactform_dragvbox_content.besuch.collapsed{
display: block!important;
}
.ui-datepicker-trigger{
float: none!important;
}
.option_date{
width: 100px;
}
.option_time{
width: 80px;
}

</style>
<div class="modal_success_msg"><?php echo $this->translate('recordinsertedsuccessfully')?></div>
<?php foreach ($management['final_events'] as $k=>$event):?>
	<?php if($event['event_name'] != "contact_form_items"):?>			
    		<button type="button" class="open_event_modal <?php echo $event['event_name'];?>" data-event_name="<?php echo $event['event_name'];?>" title=" "><?php echo $this->translate($event['event_name'].'_modal_button');?></button>
	<?php else: ?>
  		<button type="button" class="open_event_modal <?php echo $event['event_name'];?>"  data-event_name="<?php echo $event['event_name'];?>" data-event_type="<?php echo $event['form_type'];?>"  title=" "> Kontaktformular - <?php echo $event['form_type_name'];?></button>
	<?php endif; ?>
<?php endforeach;?>
 