<?php 

//css append
$this->headLink()->appendStylesheet(RES_FILE_PATH.'/css/page-css/rubinforms.css');


    //add file uploader
//     $this->headScript()->appendFile(RES_FILE_PATH.'/javascript/fine-uploader/fine-uploader.min.js');
//     $this->headLink()->appendStylesheet(RES_FILE_PATH.'/javascript/fine-uploader/fine-uploader.css');

    //rendered-add the fine-uploader file-uploader template
    //$qqtemplate = $this->render("templates/qq_fileupload_template_small_2017_09.html");

//     $qqtemplate = Pms_Template::createTemplate(array(), 'templates/qq_fileupload_template_multiple_2018_09.html');
//     $this->headScript()->setAllowArbitraryAttributes(true)->appendScript($qqtemplate, 'text/template', array("id" => "qq-template", "noescape" => true));



?>

<!-- inline script -->
<script type="text/javascript" >
var total = 0;

$(document).ready(function() {

// 	uploader_create('acp_file_healthcare_proxy', ['pdf','docx','doc']);


	$(".pfileremove").live('click', function() {
		$.confirmdeletepid = $(this).data('pid');
		$.confirmdeleteid = $(this).data('id');
			jConfirm('<? echo $this->translate('confirmdeleterecord'); ?>', '<? echo $this->translate('confirmdeletetitle'); ?>', function(r) {
			if(r)
			{	
				location.href = "<? echo APP_BASE ?>patient/patientfileremove?id="+ $.confirmdeletepid+"&did="+$.confirmdeleteid;
			}
		});
	});
});

//extensions = array[];


</script>

<div style="display: none"> <img id="calImg" src="<?php echo RES_FILE_PATH;  ?>/images/calendar.png" alt="Popup" class="trigger"> </div>
 
<?php
    //echo the form

    $this->form
    ->setAction($this->url() . "?id=" . $this->enc_id."&form=".$this->form_ident)
    ->setMethod(Zend_Form::METHOD_POST)
    ->setAttrib('novalidate', true) // this form is not html5 friendly.. it has closed accordions
    ->setAttrib('autocomplete', false) // this form is not html5 friendly.. it has closed accordions
    ->setAttrib("id", "rubin_form_".$this->form_ident)
    ->setAttrib("class", "rubin_form_class")
    ->setAttrib("onsubmit", "return form_submit_validate();");
        


    echo $this->form;
    
?>



