<form method="post">
<table class="datatable">
<tr> 
    <td>form_id</td>
    <td>
    <select name="form_id">
    <option value="mna">mna</option>
    <option value="cmai">cmai</option>   
    <option value="iadl">iadl</option>
    <option value="mmst">mmst</option>
    <option value="tug">tug</option>
    <option value="dem_tect">dem_tect</option>
    <option value="whoqol">whoqol</option>
    <option value="badl">badl</option>			<!-- ISPC-2455 Lore -->
    <option value="cmscale">cmscale</option>    <!-- ISPC-2456 Lore -->
    </select>
    </td>
</tr>
<tr>
    <td>Question_id</td>
    <td><input type="text" value="" name="question_id"></td>
</tr>

<tr>
    <td>Question_text</td>
    <td>
        <textarea name="question_text" colls="30" rows="5" style="height: 30px; width: 100%;"></textarea>
    </td>
</tr>

<tr>
    <td>Question_type</td>
    <td><select name="question_type">
    <option value="radio">radio</option>
    <option value="checkbox">checkbox</option>
    <option value="text">text</option>
    <option value="textarea">textarea</option>
    <option value="html">html</option>
    </select>
    </td>
</tr>

<tr>
    <th>Question_options</th>
    
    <td >
    
    <table class="datatable">
        <tr>
            <th>option_name</th>
            <th>option_value</th>
        </tr>
        <?php for($i=1;$i<=10;$i++):?>
            <tr>
                <td> <textarea name="option[<?php echo $i ?>][name]" colls="" rows="" style="height: 50px; width: 90%; display: block; float:left;"></textarea></td>
                <td><input type="text" value="" name="option[<?php echo $i ?>][value]"></td>
            </tr>
        <?php endfor;?>

         
    </table>
</tr>
<tr>
<td colspan="2">
 <input type="submit">
</td>
</tr>
</table>
</form>