<?php 
	$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/jquery.tablesorter.js');

	$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/pharmaindex/medi_pharmaindex.js?'.date('YmdHis'));
	$this->headLink()->appendStylesheet(RES_FILE_PATH.'/css/pharmaindex/medi_pharmaindex.css?'.date('Ymd'));
// 	$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/medicationnew_edit.css?' . date('Ymd'));
	$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/autogrow/jquery.elastic.source_new.js');
	$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/jquery.viewport.js');

	$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/views/patientmedication/editblocks.js?'.date('Ymd'));
	$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/page-css/patientmedication/style.css');

//Changes for ISPC-1848 F

	//ISPC-2589 Ancuta 28.05.2020 [migration from clinic CISPC]
	if($this->show_amts_button == "1"){
	    $this->headScript()->appendFile(RES_FILE_PATH . '/javascript/ontodrug/ontodrug.js?' . date('Ymd'));
	    $this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/page-css/ontodrugstyle.css');
	}
	//-- 
?>
<script type="text/javascript">

$(document).ready(function(){
	var idpd = "<?php echo $_REQUEST['id'];?>";
	$('#medisync_drop').load('<?php echo APP_BASE;?>ajax/medisyncwidget?id='+idpd );
	
});
// add extra js here, js variables that are php echo 

</script>
<style type="text/css">
span.submit-floating {
	width: 785px;
	background-color: #BDE5F8;
	border: 2px solid #000;
    z-index:999;
    position: fixed;
    top:90%;
    left: 222px;
    padding: 5px 10px;
    cursor: pointer;
    font-weight: bold;
    text-align: center;
}
</style>
	
	
<?php if(1== 1): $width_options = " width_options"; ?>
<style>
 
.medication_block {
    width: 100% !important;
}
 .outer{ 
 	width: 100%!important; 
 } 

 #Wrapper { 
     width: 98%!important; 
     min-width: 1010px !important; 
 } 

 #MainContent { 
     /*TODO-2762 Ancuta 19.12.2019*/  
     width: calc(100% - 250px)!important;/*      width: 75%!important; */
}

span.submit-floating {
    /*TODO-2762 Ancuta 19.12.2019*/  
     width: calc(97% - 250px)!important;/* 	width: 78%; */  
}
</style>

<? else: $width_options = "";
endif;
?>
	

<div class="<?php echo $width_options; ?>">

<!--  LIST ERRORS -->
		<?php foreach ($this->errors as $key => $val):?>
			<div id="error_master_div_<?php echo $key; ?>" class="clearer err error_master_div">
			<?php foreach ($val as  $value) :?>
				<span class="error"><?php echo $value ?></span>
			<?php endforeach?>
			</div>
		<?php endforeach?>
		
<form action="" method="post" id="form_medicationedit">
	<!-- ISPC-2524 pct.3)  Lore 14.01.2020-->
	<div id="selector_manual_forms_editmode"></div>	
    <!-- //. -->

	<div id="medication_blocks">
	
	</div>
 	<span class="submit-floating">
		<input  type="submit" value="<?php echo $this->translate('save')?>" name="save" class="btnsubmit" />
	 	<input  type="submit" value="<?php echo $this->translate('save_and_continue')?>" name="save_and_continue" class="btnsubmit"/>
	 	<!-- <input  type="button" value="<?php echo $this->translate('toggle_all_extra_info')?>" onclick="toggle_all_extra_info(this); return false;"/>-->
<!-- 	 	ISPC-2589 Ancuta 28.05.2020 [migration from clinic CISPC](start) -->
	 	<?php if($this->show_amts_button == "1"):?>
            <input  type="button" value="AMTS-Check" name="ontodrug" id="ontodrug" class="btn"/>
        <?php endif;?>
<!-- 	 	ISPC-2589 Ancuta 28.05.2020 [migration from clinic CISPC](end) -->
	</span>
</form>
</div>
<div id="medisync_drop" ></div>