<!-- ISPC-2829 Lore 08.03.2021 -->
<?
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/data_tables/datatables.min.css');
$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/data_tables/jquery.dataTables.js');
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/data_tables/fixedColumns.dataTables.min.css');
$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/data_tables/dataTables.fixedColumns.min.js');
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/data_tables/mediscreen.css?' . date('Ymd'));

// $this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/medicationnew.css');
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/page-css/patientmedication/style.css');
//ISPC-2797 Ancuta 17.02.2021
$this->elsa_planned_medis = 0 ;
if($this->elsa_planned_medis == 1){
}
    $this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/page-css/patientmedication/planned_style.css');
//--

    $this->headScript()->appendFile(RES_FILE_PATH.'/javascript/autogrow/jquery.elastic.source_new.js');
    $this->headScript()->appendFile(RES_FILE_PATH.'/javascript/views/patientmedication/editblocks.js?'.date('Ymd'));
$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/dateUtil.js');
$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/pharmaindex/medi_pharmaindex.js?'.date('YmdHis'));
$this->headLink()->appendStylesheet(RES_FILE_PATH.'/css/pharmaindex/medi_pharmaindex.css?'.date('Ymd'));
//patientfileupload
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/qtip/jquery.qtip.min.css?' . date('Ymd'));
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/tags_editor/jquery.tag-editor.css?' . date('Ymd'));
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/patientfile.css?' . date('Ymd'));
$this->headScript()->appendFile(RES_FILE_PATH . '/javascript/qtip/jquery.qtip.min.js?' . date('Ymd'));
$this->headScript()->appendFile(RES_FILE_PATH . '/javascript/tags_editor/jquery.tag-editor.js?' . date('Ymd'));
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/page-css/patientfileupload/upload-files.css');
//add file uploader
$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/fine-uploader/fine-uploader.min.js');
$this->headLink()->appendStylesheet(RES_FILE_PATH.'/javascript/fine-uploader/fine-uploader.css');
//rendered-add the fine-uploader file-uploader template
$qqtemplate = Pms_Template::createTemplate(array(), 'templates/qq_fileupload_template_multiple_2018_09.html');
$this->headScript()->setAllowArbitraryAttributes(true)->appendScript($qqtemplate, 'text/template', array("id" => "qq-template", "noescape" => true));

//.

$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/page-css/efadiagnosis.css');

$is_ie = 0;
$ua = htmlentities($_SERVER['HTTP_USER_AGENT'], ENT_QUOTES, 'UTF-8');
if (preg_match('~MSIE|Internet Explorer~i', $ua) || (strpos($ua, 'Trident/7.0') !== false && strpos($ua, 'rv:11.0') !== false)) {
    // do stuff for IE
    $is_ie = 1;
}

// ISPC-2346 Added by Ancuta  18.06.2019 START:
if($this->ModulePrivileges[189] == true && $is_ie == 0 ){
    //$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/dynamsoft-javascript-barcode/dist/dbr-6.5.2.min.js');
    //$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/pms/datamatriximportReader.js');
    
    $this->headScript()->setAllowArbitraryAttributes(true)->appendFile(RES_FILE_PATH.'/javascript/dynamsoft-javascript-barcode7.3/dist/dbr.js','text/javascript',array('data-productKeys'=> $this->barcodereaderKey));
    $this->headScript()->appendFile(RES_FILE_PATH.'/javascript/pms/datamatriximportReader7.js');
}else{
    $this->headScript()->appendFile(RES_FILE_PATH.'/javascript/pms/datamatriximport.js');
}
// --

// allowed medication types
$allowed_medication_types = $this->medication_blocks;
$timed_scheduled_medications = $this->timed_scheduled_medications; 
$allow_normal_scheduled = $this->allow_normal_scheduled; 

// for ISPC-2247 changes were made to this page (Ancuta 06.11.2018)
$sort_order = $this->sort_order;

// ISPC-2524 pct.1)  Lore 14.01.2020 
$contact_form_files = $this->form_files;
$users_data = $this->users_data;
?>

<script type="text/javascript">
var is_ie = "<?php echo $is_ie?>";

var allow_reader = 0;
<?php if($this->ModulePrivileges[189] == true):?> 
var allow_reader = 1;
<?php endif;?>

var med_sort = "";
var saved_sorting_ls = '<?php echo $this->js_saved_order; ?>';
var saved_sorting = jQuery.parseJSON (saved_sorting_ls) || {};
// console.log(saved_sorting);
var pat = "<?php echo $_REQUEST['id']; ?>";
var Barcodereader_LicenseKey = "<?php echo $this->barcodereaderKey; ?>";
var datamatrixurl = "patientnew/datamatriximport";

var dosage_intervals_json = <?php if ( ! empty($this->dosage_intervals) && is_array($this->dosage_intervals)) { echo json_encode($this->dosage_intervals);} else echo'{}' ?>;

 
 var reset_comment = "";
 var current_date = "<?php echo date("d.m.Y",time()); ?>";

var isdischarged = <?php echo $this->isdischarged; ?>;
	 
 
 // Define all needed variables
	// ISPC-2329 pct.b
	var current_doctor = <?php echo $this->verordnetvon ?>;
	var jsusers = <?php echo $this->jsusers ?>;
	var js_unit = <?php echo $this->js_med_unit ?>;
	var js_dosage_form = <?php echo $this->js_med_dosage_form ?>;
	var js_dosage_form_custom = <?php echo $this->js_med_dosage_form_custom ?>;
	var js_type = <?php echo $this->js_med_type ?>;
	var js_type_custom = <?php echo $this->js_med_type_custom ?>;
	var js_indication = <?php echo $this->js_med_indication ?>;
	var js_dosage_intervals = <?php echo $this->js_dosage_intervals ?>;
	var healthinsuranceik = "<?php echo $this->kassen_no; ?>";
	var client = '<?php echo $this->clientid ?>';	
	var new_fields = '<?php echo $this->show_new_fileds ?>';	
	var max_pumpe = 5;	
	var number_of_pumps_def = "<?php echo count($this->cocktail_array);?>";
	var number_of_pumps = number_of_pumps_def;
		
	//ISPC-2833 Ancuta 01.03.2021		
	var max_ispumpe_pumpe = 5;	
	var number_of_ispumpe_pumps_def = "<?php echo count($this->perfusor_pumpe_data_array);?>";
	var number_of_ispumpe_pumps = number_of_ispumpe_pumps_def;
	//-- 
	
		
	var timed_bocks = '<?php echo $this->js_timed_scheduled_medications; ?>';	

	var allow_normal_scheduled =  "<?php echo $this->allow_normal_scheduled; ?>";
	

	var individual_medication_time = "<?php echo $this->individual_medication_time; ?>";
	var show_mmi = "<?php echo $this->show_mmi; ?>";
	
	var elsa_planned_medis = "<?php echo $this->elsa_planned_medis; ?>";//ISPC-2797 Ancuta 18.02.2021
	
	var allow_changes = "<?php echo $this->allow_changes;?>";
	var approval_rights = "<?php echo $this->approval_rights;?>";
	var acknowledge = "<?php echo $this->acknowledge;?>";
	
	var client_pumpe_autocalculus = <?=($this->ModulePrivileges[163] == true) ? 1 : 0;?>;//module 163

	var show_dosage_unit = <?=($this->ModulePrivileges[240] == true) ? 1 : 0;?>;  //module 240	ISPC-2684 Lore 05.10.2020
	
	var js_packaging_array = <?php echo $this->js_packaging_array ?>;
	
	
	var js_escalation = <?php echo $this->js_med_escalation ?>;
	
    var module_lysocare = <?=($this->ModulePrivileges[182] == true) ? 1 : 0;?>;//module 182

    var pat = "<?php echo $_REQUEST['id'];?>";
    
	//ISPC-2554 pct.1 Carmen 03.04.2020
    var js_dosageform_mmi = <?php echo $this->js_med_dosageform_mmi ?>;
    var js_clientdosageform = <?php echo $this->js_clientdosageform ?>;
    var js_clientunit = <?php echo $this->js_clientunit ?>;
	//Carmen 17.06.2020
    var module_takinghint = <?=($this->ModulePrivileges[230] == true) ? 1 : 0;?>;//module 230
    //--

    var allow_medication_comunication_ii = "<?php echo $this->allow_medication_comunication_ii;?>"; //added by Carmen 06.05.2020 for ISPC-2507
	//TODO-3365 Carmen 21.08.2020
    var js_pharmaindex_settings = <?php echo $this->js_pharmaindex_settings ?>;
    //console.log(js_pharmaindex_settings);
    //--
    //ISPC-2664 carmen 30.09.2020
    var module_pediatric_medication = <?=($this->ModulePrivileges[239] == true) ? 1 : 0;?>;//module 239
    var patientweight = "<?php echo $this->patientweight;?>";  
    //--
      
 
 $(document).ready(function () {
     $("#medilisttabs").tabs();

     $('.efa_expand_details').live('click',function(e){
    		e.preventDefault();
    		var med_id = $(this).data('efa_expand_details_id');
    		//console.log(med_id );
    		 
    		if( $('.medication_row_'+med_id).hasClass('expanded')){
    			$('.medication_row_'+med_id).removeClass('expanded')
    			$('.medication_details_row_'+med_id).hide();
    		} else{
    			$('.medication_row_'+med_id).addClass('expanded')
    			$('.medication_details_row_'+med_id).show();
    			
    		}
    	});
     $('.ack_efa_expand_details').live('click',function(){
    		var med_id = $(this).data('efa_expand_details_id');
    		console.log(med_id );
    		
    		if( $('.ack_medication_row_'+med_id).hasClass('expanded')){
    			$('.ack_medication_row_'+med_id).removeClass('expanded')
    			$('.ack_medication_details_row_'+med_id).hide();
    		} else{
    			$('.ack_medication_row_'+med_id).addClass('expanded')
    			$('.ack_medication_details_row_'+med_id).show();
    			
    		}
    	});


    	$('.offline_ack_efa_expand_details').live('click',function(){
    		var med_id = $(this).data('efa_expand_details_id');
    		console.log(med_id );
    		
    		if( $('.offline_ack_medication_row_'+med_id).hasClass('expanded')){
    			$('.offline_ack_medication_row_'+med_id).removeClass('expanded')
    			$('.offline_ack_medication_details_row_'+med_id).hide();
    		} else{
    			$('.offline_ack_medication_row_'+med_id).addClass('expanded')
    			$('.offline_ack_medication_details_row_'+med_id).show();
    			
    		}
    	});
  	
 	/* ######################## MEDICATION HISTORY ######################## */
		$('.show_medication_info').live('click', function(e){
		e.preventDefault();
		  var drugplan_id = $(this).data("drugplan_id");
		  var medication_type = $(this).data("medication_type");
		  
		$('.medication_history').load('<?php  echo APP_BASE."patientmedication/history?id=".$_REQUEST['id']."&drugplan_id='+drugplan_id+'"; ?>', function() {
			$('.medication_history').dialog('open');
		});

	});


	$( ".medication_history" ).dialog({
		autoOpen: false,
		resizable: false,
		title: "<?php echo $this->translate('medication history')?>",
		height: 600,
		width: 850,
		modal: true,
		open: function() {
			$(this).dialog( "option", "buttons", 
					[ 
						{
							text: "<?php echo $this->translate('cancel')?>", 
							"class": 'cancelButtonClass',
							click: function() {
								$( this ).dialog( "close" );
							}
						},
				]
			);
		},
		close: function() {
			
		}

	});
	
 	/* ######################## MEDICATION SETS  ######################## */
 	$('.MedicSetButton').live('click', function(e){
 		e.preventDefault();
 		
 		var pat = "<?php echo $_REQUEST['id'];?>";
 		var set_type = $(this).data("med_block");
 		var url = appbase+'patientmedication/sets?id='+pat+'&set_type='+set_type;
 		xhr = $.ajax({
 			url : url,
 			success : function(response) {
 				$('.medication_sets').html(response);
 				$('.medication_sets').dialog('open');
 			}
 		});
 	});

 	
 	$( ".medication_sets" ).dialog({
 		autoOpen: false,
 		resizable: false,
 		title: "<?php echo $this->translate('2247 - Medication sets ')?>",
 		height: 550,
 		width: 900,
 		modal: true,
 		open: function() {
 			//		<!-- ISPC-2329 pct.l) Lore 23.08.2019  -->
 			if($('#nosets').val() == "1"){
 				$(this).dialog( "option", "buttons", 
 						[ 
 						 
 							{
 								text: "<?php echo $this->translate('cancel')?>", 
 								"class": 'cancelButtonClass',
 								click: function() {
 									$( this ).dialog( "close" );
 								}
 							}
 					]
 				);	
 			} else{
 			$(this).dialog( "option", "buttons", 
 					[ 
 						{   
 							text: "<?php echo $this->translate('save')?>", 
 							"class": 'cancelButtonClass disabledButtonClass',
 							click: function() {
     // 								$( this ).dialog( "close" );
     								$('#add_set_medication').submit();
     								//console.log("save changes");
 							}
 						},
 						{
 							text: "<?php echo $this->translate('cancel')?>", 
 							"class": 'cancelButtonClass',
 							click: function() {
 								$( this ).dialog( "close" );
 							}
 						}
 				]
 			);
 		}
 		},
 		close: function() {
 			
 		}

 	});
  });
	/*#########################################################################*/

	function hide_sort(_this){
		
		$(_this).hide();
	}
	function show_sort(_this){
		
		$(_this).hide();
	}
		
  function med_Sort(that){
		
		var mtype = $(that).data('sort_type');
		
		  $( '#sort_'+mtype).toggle();
		
	}

  function save_sort_option(medication_type, column , order){

		 $.ajax({
			type: 'POST',
			url: 'user/savemedicationsorting',
			data: {
				source:'new_medi_page',
				page: 'patientmedication-'+medication_type,
				patient: pat,
				order: order,
				column: column,
				save_sorting: "yes"
			},
			success:function(response){

				//TODO-3450 Ancuta 22.09.2020
				//var url=appbase +'patientmedication/overview?id='+pat;
				var url=appbase +'patientmedication/etamedication?id='+pat+'&sort_b='+medication_type+'&sort_c='+column+'&sort_d='+order;
				window.location.href = url;
		 
			}
		});
			
	} 

	//ISPC-2642 Ancuta 10-11.08.2020
	$('.pf_edit_cont').removeClass('blink_edit_cont');
	<?php if(!empty($_GET['file_id']) ):?>
	$(window).load(function() {
	
	 	$('html, body').animate({
          scrollTop: $("#edif_file_name").offset().top
      }, 100, function() {
          $("#edif_file_name").focus();
      });
		});
	
	
		$('.pf_edit_cont').addClass('blink_edit_cont');
		
		setTimeout(function() {
			$('.pf_edit_cont').removeClass('blink_edit_cont');
		}, 4500);
	<? endif;?>
	
	//-- 

			

	// Delete file with confirmation
	$("#pfileremove").live('click', function() {
		$.confirmdeletepid = $(this).attr('rel_pid');
		$.confirmdeleteid = $(this).attr('rel_id');
			jConfirm('<? echo $this->translate('confirmsingledeleterecord'); ?>', '<? echo $this->translate('confirmdeletetitle'); ?>', function(r) {
			if(r)
			{	
				location.href = "<? echo APP_BASE ?>patient/patientfileremove?id="+ $.confirmdeletepid+"&did="+$.confirmdeleteid;
			}
		});
	});


	
	function EditOneMedi(_obj){
		//alert('med_id: '+medication_id+'; medi_type: '+medication_type);
  		console.log(_obj.id,_obj.medication_block_type);
		
		
		var medication_type = _obj.medication_block_type;
		var drugplan_id = _obj.id;
		
		var arr_values = Object.values(_obj);
		//console.log(arr_values);
		var modal = $(document.getElementById("edit_etamedication-dialog"));

		modal.dialog({
	        //autoOpen: true,
	        height: 600,
	        width:1300,
	        modal: true,
	        title : translate("Änderung der Medikation eintragen"),
	        open: function(event, ui) {
				$.getmedicationblocks(_obj);
	        	var med_id   = arr_values[0]; 
	        	var med_name = arr_values[3]; 
	        	var med_dosage_arr = Object.values(arr_values[4]); 
	        	
				$('#med_id').val(med_id);
				$('#med_name').val(med_name);
				
				for (var i = 0; i < med_dosage_arr.length; i++) {
					$('#med_dosage_'+i).val(med_dosage_arr[i]); 
		        	var count_dosage = i;
				}
	        	
	        },
			buttons: {
				"<?php echo $this->translate('submit'); ?>": function() {
					$('#med_single_edit').submit();
				},
				"<?php echo $this->translate('cancel'); ?>": function() {
					$(this).dialog("close");
				}
			}
	           
		});
	}
		
</script>
<?php //if($this->force_full_width=="1"):?>
<style>
 
.btnHistory{
    display: none!important;
}


/* ISPC-2831 Dragos 15.03.2021 */

#medilisttabs .ui-widget-header, .ui-widget-content {
	background: none !important;
	border-color: darkgrey !important;
}

#medilisttabs .ui-state-default.ui-state-active, .ui-widget-content .ui-state-active, .ui-widget-header .ui-state-active {
	border-color: darkgrey !important;
	background-color: darkgray !important;
}

#medilisttabs .ui-state-default, .ui-widget-content .ui-state-default, .ui-widget-header .ui-state-default {
	background: none;
	border-color: #DDDDDD;
	background-color: white;

}

#medilisttabs .ui-state-default.ui-state-active:hover {
	background-color: darkgray !important;
}

#medilisttabs .ui-state-default:hover {
	background-color: #DDDDDD !important;
}
#medilisttabs .ui-state-active a, .ui-state-active a:link {
	color: white !important;
}

#medilisttabs .ui-state-default a, .ui-state-default a:link {
	color: black;
}

 
ul{
	list-style-type:none;
}
.separator{
	height: 2px;
	width:100%;
}

 

 
 
   
 
form.create_form_diagnosis_clinical {
	font: normal 12px Arial, Helvetica, sans-serif;
	margin: 0;
	padding: 0;
	width: 100%;
}

form.create_form_diagnosis_clinical fieldset {
	border: solid 1px #ffffff;
	padding: 15px;
	margin: 0;
	margin-top: 10px;
	background: #ffffff;
}

form.create_form_diagnosis_clinical fieldset legend {
	font-size: 1.3em;
	font-weight: bold;
	color: #2d3a67;
}

form.create_form_diagnosis_clinical label {
	display: block;
	float: left;
	width: 160px;
	padding: 0;
	margin: 5px 0 0;
	text-align: left;
}

form.create_form_diagnosis_clinical input,form textarea,form select {
	width: auto;
	margin: 7px 0 0 10px;
}

form.create_form_diagnosis_clinical input#reset {
	margin-left: 0px;
}

form.create_form_diagnosis_clinical textarea {
	overflow: auto;
}

form.create_form_diagnosis_clinical small {
	display: block;
	margin: 0 0 5px 168px;
	padding: 1px 3px;
	font-size: 11px;
}

form.create_form_diagnosis_clinical .help {
	display: block;
	margin: 0 0 5px 380px;
	width: 27px;
	height: 27px;
	background: green;
}

form.create_form_diagnosis_clinical .required {
	font-weight: bold;
}

form.create_form_diagnosis_clinical br {
	clear: left;
}

form.create_form_diagnosis_clinical .button {
	width: auto;
	height: 27px;
	background: #FFFFFF;
	border: solid 1px #088fd5;
	font-family: Arial, Helvetica, sans-serif;
	font-size: 11px;
	font-weight: bold;
	text-decoration: none;
	text-align: center;
	color: #2257a1;
}
tr.lightGrayClass td{
	background: #babdb6;
}
tr.ArclightGrayClass td{
	background: #dddddd;
}
tr.GrayClass td{
	background: #888a85;
}

form .button1 {
	width: auto;
	height: 27px;
	background: #FFFFFF;
	border: solid 1px #088fd5;
	font-family: Arial, Helvetica, sans-serif;
	font-size: 11px;
	font-weight: bold;
	text-decoration: none;
	text-align: center;
	color: #2257a1;
}

form .checkbox {
	width: 100%;
	padding-top: 5px;
}

form .checkbox {
	width: 200px;
}
 
 
.ClrBth {
	clear: both;
}
  
.f_highlight{
	display: none;
	 float: left;
	width:98%;
	margin: 10px 0 10px 0; 
	padding: 3px 0 3px 0;
	height: 20%;
	text-align: center;
	font-size: 14px;
	font-weight: 800;
	background: #f8f8f8;
}

ul.tabs{
	margin: 0px;
	padding: 0px;
	list-style: none;
	width:100%!important;
}
	
ul.tabs li{
	background: none;
	color: #222;
	display: inline-block;
	padding: 0px 10px 0px 10px!important;
	cursor: pointer;
	height: 32px;
}

ul.tabs li.current{
}

.tab_block{
	display: none;
}

.tab_block.current{
	display: inherit;
}
       


.diagno_category_filter_cnt{
	line-height:14px;
	height: 20px;
	float: left;
	display: block;
	border:0px;
	margin:2px;
	border-radius: 5px;
	color: #ffffff;
	padding: 2px;
/* 	mix-blend-mode: difference; */
}
.diagno_category_filter_cnt input,
.diagno_category_filter_cnt label{
	float: left;
}
.diagno_category_filter_cnt label{
	line-height: 20px;
	margin-left: 5px;
	margin-right: 5px;
}

.new_entry_button{
	background: transparent;
	border:0;
}
.new_entry_button span{
	line-height: 25px;
}


.cat_sh{
	display: block;
	float: left;
	width: 20px;
	height: 20px;
	line-height: 20px;
	font-weight: 900;
	text-align: center;
	border-radius: 5px;
	color: #ffffff;
	margin-right:2px;
}


.icd_block table th{
	border: 1px solid #f5efef;
}
.icd_block table td{
	border: 1px solid #f5efef;
}



.ended_block{
	width: 100%;
	margin-top:10px;
	margin-bottom: 20px;
}

.ended_block table th{
	border: 1px solid #f5efef;
}
.ended_block table td{
	border: 1px solid #f5efef;
}

.ended_block h2{
	font-size: 12px!important;;
/* 	font-weight:normal; */
	color:#000!important;;
	margin-bottom:3px;
}




.archived_block{
	width: 100%;
	margin-top:100px;
}

.archived_block h1{
	font-size: 14px;
	margin-bottom:10px;
}
.archived_block table th{
	border: 1px solid #f5efef;
}
.archived_block table td{
	border: 1px solid #f5efef;
}


.side_labels input{
	margin-right: 5px;
}



/*ISPC-2775 Carmen 05.01.2021  */
#patnewdiagnosiseditor #table_icd{
    table-layout: fixed;
}

#patnewdiagnosiseditor #table_icd td, #patnewdiagnosiseditor #table_icd th{
    word-wrap:break-word
}

#patnewdiagnosiseditor #ended_table_icd{
    table-layout: fixed;
}

#patnewdiagnosiseditor #ended_table_icd td, #patnewdiagnosiseditor #ended_table_icd th{
    word-wrap:break-word
}

#patnewdiagnosiseditor #archived_table_icd {
    table-layout: fixed;
}

#patnewdiagnosiseditor #archived_table_icd  td, #patnewdiagnosiseditor #archived_table_icd  th{
    word-wrap:break-word
}

#patnewdiagnosiseditor .diagno_category_filter_cnt label {
	line-height: 14px;
}

#patnewdiagnosiseditor .diagno_category_filter_cnt input {
	margin: 2px 0 0 10px;
}


/*ISPC-2721 CRISTI C. 28.01.2021*/
@media (max-width: 1980px) {
		#tabs-1 #table_icd tr td:nth-child(2) {
		min-width:141px;
	}
	
	#tabs-1 #table_icd tr td:nth-child(3) {
		min-width:120px;
	}
	
	#tabs-1 #ended_table_icd tr td:nth-child(1) {
		min-width:199px;
	}
	
	
	#tabs-1 #ended_table_icd tr td:nth-child(2) {
		min-width:120px;
	}
	
	#tabs-1 #archived_table_icd tr td:nth-child(1) {
		min-width:199px;
	}
	
	
	#tabs-1 #archived_table_icd tr td:nth-child(2) {
		min-width:120px;
	}	
	
	
	
}

@media (max-width: 1250px) { 
	#tabs-1 #ended_table_icd tr td:nth-child(1) {
		min-width:199px;
	}
	
	#tabs-1 #archived_table_icd tr td:nth-child(1) {
		min-width:199px;
	}
	
	
}


@media (max-width: 1865px) { 
	#tabs-1 #table_icd tr td:nth-child(2) {
		min-width:143px;
	}
	
	
}

@media (max-width: 1722px) { 
	#tabs-1 #table_icd tr td:nth-child(2) {
		min-width:146px;
	}	
	
}

@media(max-width:1610px) {
	#tabs-1 #table_icd tr td:nth-child(4) {
    min-width: 250px;
	}
	
	#tabs-1 #ended_table_icd tr td:nth-child(3) {
    min-width: 250px;
	}
	
	#tabs-1 #archived_table_icd tr td:nth-child(3) {
    min-width: 250px;
	}
}

@media (max-width: 1566px) { 
	#tabs-1 #table_icd tr td:nth-child(2) {
		min-width:152px;
	}
	
	
}

@media (max-width: 1458px) { 
	#tabs-1 #table_icd tr td:nth-child(2) {
		min-width:159px;
	}
	
	#tabs-1 #table_icd tr td:nth-child(4) {
    min-width: 150px;
	}
	
	#tabs-1 #ended_table_icd tr td:nth-child(3) {
    min-width: 150px;
	}
	
	#tabs-1 #archived_table_icd tr td:nth-child(3) {
    min-width: 150px;
	}
	
	
}

@media (max-width: 1240px) { 
	#tabs-1 #table_icd tr td:nth-child(2) {
		min-width:70px;
	}
	
	#tabs-1 #ended_table_icd tr td:nth-child(1) {
		min-width:108px;
	}
	
	#tabs-1 #archived_table_icd tr td:nth-child(1) {
		min-width:108px;
	}
	
}
/* //- */


.red_File_bar{
    background: #dd7f7f; 
     color: #fff; 
    font-weight: 800;
    padding: 2px; 
    line-height: 26px;
    font-size: 14px;
}
</style>
 
<?php //echo $this->patientinfo ?>
<?php //echo $this->tabmenus ?>
<?php $medication_array = $this->medication?>

<?php if($this->show_file_red_bar == '1'):?>
<div class="red_File_bar">
<span > <?php echo $this->translate('aktuellere Fassung als PDF vorhanden !! ('.$this->last_file_date.')');?></span>
</div>
<?php endif;?>
<br/>
 <?php 
// if( empty($medication_array) || (!empty($_REQUEST['msg']) && $_REQUEST['msg'] =="KeineMedikation")  ):
 if( (!empty($_REQUEST['msg']) && $_REQUEST['msg'] =="KeineMedikation")  ):
 ?>
 <div class="err"><?php echo $this->translate('Keine Medikation');?></div>
<?php endif;?>


<div id="medilisttabs" class="medilisttabs">
	<ul>
       <li><a href="#tab-actual"><?php echo $this->translate("actual"." medication title")?></a></li>
       <li><a href="#tab-isbedarfs"><?php echo $this->translate("isbedarfs"." medication title")?></a></li>
       <li><a href="#tab-iscrisis"><?php echo $this->translate("iscrisis"." medication title")?></a></li>
       <li><a href="#tab-medipdf"><?php echo $this->translate("Medikations- Pläne (PDF)")?></a></li>
    </ul>
    
    <!--  ##################################################### -->
    <!--  #################- actual -########################## -->		
    <!--  ##################################################### -->
    <div id="tab-actual">
        <?php foreach($allowed_medication_types as $k=>$medication_type):?>
        	<?php if($medication_type == 'actual'):?>
			<?php if(in_array($medication_type,$timed_scheduled_medications)):?>
        	
        	<div class="mk-container">
            	<!-- top -->
            	<div class="mk-top">
            		<h2><?php echo $this->translate($medication_type." medication title")?> </h2>

            	    <?php $colspan_diagno = count($this->dosage_intervals[$medication_type]); ?>
            	    <?php 
            	       	   $colspan_table = $colspan_diagno + 6;
            		?>            		
            		<table class="medikation" cellspacing="0" cellpadding="0" border="0">
                		<thead>
                			<tr>
                				<th rowspan="2" colspan="2" class="name">NAME / <span>WIRKSTOFF</span></th>
                				<th colspan="<?php echo count($this->dosage_intervals[$medication_type])?>" class="dosierung">DOSIERUNG</th>
                				<th rowspan="2">INDIKATION / KOMMENTAR</th>
                				<th rowspan="2">ESKALATION</th>
                				<th rowspan="2" colspan="2">LETZTE ÄNDERUNG</th>
                			</tr>
                			<tr class="time">
                				<!--  DOSAGE TABLE HEADER KIDS-->
                	 			<?php foreach($this->dosage_intervals[$medication_type] as $k => $di):?>
                		 			<th><?php echo $di;?></th>
                	 			<?php endforeach;?>
                			</tr>
                		</thead>   
                		<tbody>
                    		<?php 
                    		foreach($medication_array[$medication_type] as $k =>$med):?>
                    		
                    		    <?php
                    		    $has_ack_class="";
                    
                    		    if((  !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :
                        		    $has_ack_class = "has_ack";
                                endif; 
                                ?>
                    		    <?php 
                    		    $data_medid= "";  
                    			if(( !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :
                                    $data_medid ='data-medid="'. $med['id'].'"' ;  
                    			endif; 
                                ?> 
                                
                                
                                
                                <!--  Check if the medication line - needs multiple rows  -->
                                <?php $row_type = "double";?>
                                <?php $row_span = ' rowspan="2"';?>
                                
                            		<?php
                            		 $dosage_concentration_line = array();
                            		 foreach($this->dosage_intervals[$medication_type] as $k => $dosage_time):?>
                                        <!-- TODO-3624 Ancuta 23.11.2020 --> 
                    				    <?php if (isset($med['dosage'][$dosage_time]) && strlen(trim($med['dosage'][$dosage_time])) > 0 && !empty($med['dosage_concentration'][$dosage_time]) ):?>
                    					   <?php  $dosage_concentration_line[] =  $med['dosage_concentration'][$dosage_time];?>
                    					<?php endif;?>
                    				<?php endforeach;?>
                                
                                <?php if(empty($med['drug']) && empty($dosage_concentration_line)):?>
                                    <?php $row_type = " single";?>
                                    <?php $row_span = '';?>    
                                <?php endif;?>
                                <!-- end check -->
                                
                                
                                
                                <tr  class="<?php echo $row_type; ?> <?php if($row_type =="double"): ?>first <?php endif;?> medication_row_<?php echo $med['id']?>  " <?php echo $data_medid?>>
                                    <!--TD: Sort/Importance  -->			
                    				<td class="sortnum" <?php echo $row_span?> ><span> <?php echo $med['importance']; ?></span></td>
                    				
                                    <!--TD: Name  -->
                    				<td class="name"><?php echo $med['medication'];?></td>
                    				
                                    <!--TD: Time dosage  -->				
                    				<?php foreach($this->dosage_intervals[$medication_type] as $k => $dosage_time):?>
                    				<td class="dosierung"><?php echo $med['dosage'][$dosage_time];?> <?php if (strlen($med['dosage'][$dosage_time]) > 0):?><?php echo $med['unit'];?><?php endif;?></td>
                    				<?php endforeach;?>
                    				
                                    <!--TD: Indication + Comment  -->								
                    				<td class="ind-comm" <?php echo $row_span?> >
                        				<?php if(!empty($med['indication'])):?>
                            				<?php if(strlen($med['indication_color']) > 0 ):?>
                            					<div class="indikation" style="color:#<?php echo $med['indication_color'];?>"><span class="circle" style="background:#<?php echo $med['indication_color'];?>"></span><?php echo $med['indication'];?></div>
                            					<?php else:?>
                               					<div class="indikation" style="color:#000000"><span class="circle" style="background:#000000"></span><?php echo $med['indication'];?></div>
                            				<?php endif;?>
                        				<?php endif;?>
                    					<div class="comment extra_padding_left"  id="<?php echo $med['id'];?>_medi_comment" > <?php echo $med['comments'];?> </div>
                    				</td>
                    				
                    				 <!--TD: Escalation  -->
                    				<td class="escalation" <?php echo $row_span; ?>>
                    					<div><?php echo $med['escalation']; ?></div>
                    				</td>
                    				
                                    <!--TD: Date+ History  -->				
                    				<td class="date" <?php echo $row_span?>>
                    					<input type="button" name="history" class="btnHistory show_medication_info"   data-medication_type="<?php echo $medication_type; ?>" data-drugplan_id="<?php echo $med['id']; ?>">
                    					<div class="date-cont"><?php echo date('d.m.Y',strtotime($med['medication_change']));?></div>
                    				</td>
                    				
                                    <!--TD: Details-->
                                    <!-- 				<td class="details efa_expand_details" <?php echo $row_span?> data-efa_expand_details_id="<?php echo $med['id']?>"></td>
                                    ISPC-2329 Lore 16.06.2020    -->				
                    				<td class="details efa_expand_details" <?php echo $row_span?> data-efa_expand_details_id="<?php echo $med['id']?>" ><button class="efa_expand_details_float" name="btn123" ></button></td>
                    			
                    				<td <?php echo $row_span; ?>>																					<!-- ISPC-2829 Lore 02.04.2021 -->
                    					<img src="<?php echo RES_FILE_PATH?>/images/edit.png" alt="Bearbeiten" onclick='EditOneMedi(<?=json_encode($med, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP | JSON_UNESCAPED_UNICODE); ?>)'  />
                    				</td>                     			
                    			</tr>
                    			
                    			
                    			<?php if($row_type =="double"): ?>
                    			<tr class="<?php echo $row_type; ?> last  last_med_row_<?php echo $med['id']?>  ">
                    			    
                    			    <!--TD: Drug-->
                    				<td class="name wirkstoff"><?php echo $med['drug'];?></td>
                    				
                    				
                    				<?php foreach($this->dosage_intervals[$medication_type] as $k => $dosage_time):?>
                    			    <!--TD: Dosage interval <?php echo $dosage_time;?>-->
                    				<td class="dosierung">
                    				    <!-- TODO-3624 Ancuta 23.11.2020 -->
                    				    <?php if (strlen($med['dosage'][$dosage_time]) > 0):?>
                    					   <?php echo $med['dosage_concentration'][$dosage_time];?>
                    					<?php endif;?>
                    				</td>
                    				<?php endforeach;?>
                    				
                    			</tr>
                    			<?php endif;?>
                    			
                    			
                    			<tr class="medication_details_row_<?php echo $med['id']?> hide_details expandedItem "  >
                    			
                    				<td colspan="<?php echo $colspan_table; ?>">
                    			
                    					<h3>APPLIKATIONSWEG, DARREICHUNGSFORM, EINHEIT, ETC</h3>
                    			
                    					<div class="ei-content">
                    			
                    						<ul class="item">
                    							<li><span>Konzentration: </span><?php echo $med['concentration_full'];?></li>
                    							<li><span>Einheit: </span><?php echo $med['unit'];?></li>
                    						</ul>
                    						
                    						<ul class="item">
                    							<li><span>Darreichungsform: </span><?php echo $med['dosage_form'];?></li>
                    							<li><span>Applikationsweg: </span><?php echo $med['type'];?></li>
                    						</ul>
                    						
                    						<?php if(  $allow_normal_scheduled == "1" && $med['has_interval'] == "1"):?>
                        						<ul class="item">
                        							<li><span>Interval(Tage): </span><?php echo $med['days_interval'];?></li>
                        							<?php  if( $med['administration_date'] != "0000-00-00 00:00:00"):?>
                            							<li><span>Intervall zuletzt gestartet: </span>
                            							<?php echo date("d.m.Y",strtotime($med['administration_date']));?>
                            							</li>
                            							<?php if($med['allow_restart'] == "1"):?>
                            							 <li><button type="button" class="btnBlue interval_restart interval_settings" data-drug_id="<?php echo $med['id'];?>"  data-medication_type = "<?php echo $medication_type;?>" id="<?php echo $medication_type;?>_<?php echo $med['id'];?>_interval_restart" ><?php echo $this->translate("give medication- Restart start interval")?></button></li>
                            							<?php endif; ?>
                            						<?php else: ?>
                            						  <li> 
                            						    <button type="button" class="btnBlue interval_start interval_settings"  data-drug_id="<?php echo $med['id'];?>"  data-medication_type = "<?php echo $medication_type;?>"  id="<?php echo $medication_type;?>_<?php echo $med['id'];?>_interval_start" ><?php echo $this->translate("give medication- start interval")?></button>
                           						    </li>
                           							<?php endif; ?>
                        						</ul>
                    						<?php endif;?>
 
                    						<?php if(!empty($med['prescribed_by'])):?>
                        						<ul class="item">
                        							<li>
                                                        <span><?php echo $this->translate('medication_prescribed_by');?></span> <?php echo $med['prescribed_by'];?>
                        							</li> 
                        						</ul>
                    						<?php endif;?>
                    						
                    					</div>
                    				</td>
                    			</tr>
 
                    		  <tr class="separator">
                    				<td colspan="<?php echo $colspan_table?>"> </td>
                    			</tr>
                    		<?php endforeach;?>
                    		
                    		</tbody>
                    	</table>
	      		
            	</div>
        	</div>
        	
        	<!-- NO TIME PERIOD  -->
        	
        <?php elseif(!in_array($medication_type,$timed_scheduled_medications) && !in_array($medication_type,array('isschmerzpumpe','treatment_care','scheduled','ispumpe'))): ?>
        	
        	<div class="mk-container">
        	
        	<!-- top -->
        	<div class="mk-top">
        		<h2><?php echo $this->translate($medication_type." medication title")?> </h2>      		
        	</div>
        	<!-- // top -->
        	
        		<table class="medikation" cellspacing="0" cellpadding="0" border="0">
        	    <?php 
        	       $colspan_table = 7; // change colspan according to blocks
        		?>
        		<thead>
        			<tr>
        				<th rowspan="2" colspan="2" class="name">NAME / <span>WIRKSTOFF</span></th>
        				<th colspan="" class="dosierung">DOSIERUNG / <span>INTERVALL</span></th>
        				<th rowspan="2">INDIKATION / KOMMENTAR</th>
        				<th rowspan="2" >ESKALATION</span></th>
        				<th rowspan="2" >LETZTE ÄNDERUNG</th>
        			</tr>
        		</thead>
 
        		<tbody>
        		<?php foreach($medication_array[$medication_type] as $k =>$med):?>
                    <!--  Check if the medication line - needs multiple rows  -->
                    <?php $row_type_nt = "double";?>
                    <?php $row_span_nt = ' rowspan="2"';?>
                    
                    <?php if(empty($med['drug']) && empty($med['dosage_interval'])):?>
                        <?php $row_type_nt = " single";?>
                        <?php $row_span_nt = '';?>    
                    <?php endif;?>
                    <!-- end check -->
                    
                    
        
                    <tr  class="<?php echo $row_type_nt?> <?php if($row_type_nt == 'double'):?>first <?php endif;?> medication_row_<?php echo $med['id']?> " <?php echo $data_medid?>>
        
                        <!--TD: Sort  -->
        				<td class="sortnum" <?php echo $row_span_nt?> ><span> <?php echo $med['importance']; ?></span></td>
        
                        <!--TD: Name  -->
        				<td class="name"><?php echo $med['medication'];?></td>
        				
                        <!--TD: Dosage  -->
        				<td class="dosierung" <?php echo $row_span_nt; ?>>
        				    <?php echo $med['dosage'];?> 
        				    <?php echo $med['unit'];?> 
        				 </td>
        
                        <!--TD: Indication Comment  -->
        				<td class="ind-comm" <?php echo $row_span_nt; ?>>
        				<?php if(!empty( $med['indication'])):?>
            				<?php if(strlen($med['indication_color']) > 0):?>
            					<div class="indikation" style="color:#<?php echo $med['indication_color'];?>"><span class="circle" style="background:#<?php echo $med['indication_color'];?>"></span><?php echo $med['indication'];?></div>
            					<?php else:?>
            					<div class="indikation" style="color:#000000"><span class="circle" style="background:#000000"></span><?php echo $med['indication'];?></div>
            				<?php endif;?>
        				<?php endif;?>
        					<div class="comment extra_padding_left"  id="<?php echo $med['id'];?>_medi_comment"><?php echo $med['comments'];?></div>
        				</td>
        
                        <!--TD: Escalation  -->
        				<td class="escalation" <?php echo $row_span_nt; ?>>
        					<div><?php echo $med['escalation']; ?></div>
        				</td>
        
                        <!--TD: Date  -->
        				<td class="date" <?php echo $row_span_nt; ?>>
        					<input type="button" name="history" class="btnHistory show_medication_info"   data-medication_type="<?php echo $medication_type; ?>" data-drugplan_id="<?php echo $med['id']; ?>">
        					<div class="date-cont"><?php echo date('d.m.Y',strtotime($med['medication_change']));?></div>
        				</td>
        
                        <!--TD: Details  -->
                        <!-- 				<td class="details efa_expand_details" <?php echo $row_span_nt; ?> data-efa_expand_details_id="<?php echo $med['id']?>"></td>
                         ISPC-2329 Lore 16.06.2020    -->
        				<td class="details efa_expand_details" <?php echo $row_span_nt; ?> data-efa_expand_details_id="<?php echo $med['id']?>" ><button class="efa_expand_details_float" name="btn123" ></button></td>
        			
         				<td  <?php echo $row_span_nt; ?> >
                    		<img src="<?php echo RES_FILE_PATH?>/images/edit.png" alt="Bearbeiten" onclick='EditOneMedi(<?=json_encode($med, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP | JSON_UNESCAPED_UNICODE); ?>)'  />
        				</td>        			
        			</tr>
        			
        			<?php if( $row_type_nt == 'double'):?>
        			<tr class="<?php echo $row_type_nt?> last last_med_row_<?php echo $med['id']?>  <?php if(($this->acknowledge  == "1" && !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :?> has_ack <?php endif; ?>">
        			
                        <!--TD: Drug  -->
        				<td class="name wirkstoff"><?php echo $med['drug'];?> </td>
        				
        				<?php if($medication_type == "iscrisis" || $medication_type == "isbedarfs"):?>
                        <!--TD: Dosage Interval -->
        				<td class="dosierung"><?php echo $med['dosage_interval'];?> </td>
        				<?php endif;?>
        			</tr>
        			<?php endif;?>
        			
        			<tr class="medication_details_row_<?php echo $med['id']?> hide_details expandedItem"  >
        
                        <td colspan="<?php echo $colspan_table;?>">
        			
        					<h3>APPLIKATIONSWEG, DARREICHUNGSFORM, EINHEIT, ETC</h3>
        				
        					<div class="ei-content">
        						
        						<ul class="item">
        							<li><span>Konzentration: </span><?php echo $med['concentration_full'];?></li>
        							<li><span>Einheit: </span><?php echo $med['unit'];?></li>
        						</ul>
        						
        						<ul class="item">
        							<li><span>Darreichungsform: </span><?php echo $med['dosage_form'];?></li>
        							<li><span>Applikationsweg: </span><?php echo $med['type'];?></li>
        						</ul>
        						
        						<?php if( $allow_normal_scheduled == "1" && $med['has_interval'] == "1"):?>
            						<ul class="item">
            							<li><span>Interval(Tage): </span><?php echo $med['days_interval'];?></li>
            							<?php  if( $med['administration_date'] != "0000-00-00 00:00:00"):?>
                							<li><span>Intervall zuletzt gestartet: </span>
                							<?php echo date("d.m.Y",strtotime($med['administration_date']));?>
                							</li>
                							<?php if($med['allow_restart'] == "1"):?>
                							 <li><button type="button" class="btnBlue interval_restart interval_settings" data-drug_id="<?php echo $med['id'];?>"  data-medication_type = "<?php echo $medication_type;?>" id="<?php echo $medication_type;?>_<?php echo $med['id'];?>_interval_restart" ><?php echo $this->translate("give medication- Restart start interval")?></button></li>
                							<?php endif; ?>
                						<?php else: ?>
                						  <li> 
                						    <button type="button" class="btnBlue interval_start interval_settings"  data-drug_id="<?php echo $med['id'];?>"  data-medication_type = "<?php echo $medication_type;?>"  id="<?php echo $medication_type;?>_<?php echo $med['id'];?>_interval_start" ><?php echo $this->translate("give medication- start interval")?></button>
               						    </li>
               							<?php endif; ?>
            						</ul>
        						<?php endif;?>
        						
        					</div>
        				</td>
        			</tr>
  
        		  <tr class="separator">
        				<td colspan="<?php echo $colspan_table?>"> </td>
        			</tr>
        		<?php endforeach;?>
        		
        		</tbody>
        	</table>

        	</div>      
  
        <?php endif;?>        	
		 <?php $new_line = array('efaoption'=>'1','medication_block_type'=>$medication_type,'id'=>'x')?>
         <a href="javascript:void(0)" rel="actual" class="add_button_link medication_add_link"  onclick='EditOneMedi(<?=json_encode($new_line, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP | JSON_UNESCAPED_UNICODE); ?>)'>Neues Medikament hinzufügen</a>
         <br/>&nbsp;
         <br/>&nbsp;
         <br/>&nbsp;
        	        
           
		<!-- ####  Acknolege  #### -->
    	<?php if(count($contact_form_files)>0 && 1==2):  ?>
    	    <p style="color:red;"><?php echo $this->translate('noch nicht eingepflegte Änderungen');?></p>	
    	
    	    <div class="mk-container">

			<?php $i = 1;
			foreach ($contact_form_files as $k_contact_file => $v_contact_file): ?>
			 <table id="dateien_verlauf_state" class="medication_edit_table medikation dateien_verlauf_edit_table">

 				<tbody>
				<?php if( $i % 2 == 0):  ?>
			    	<tr>
				<?php else : ?>
					<tr style="background: #F3F3F3!important;">
				<?php endif;  ?>
					<td style="width:30%"><a href="<?php echo APP_BASE . 'stats/patientfileupload?doc_id='.$v_contact_file['id'].'&id='.$_REQUEST['id'];?>"><?php echo $users_data[$v_contact_file['create_user']]['first_name'].', '.$users_data[$v_contact_file['create_user']]['last_name']; ?><br/><?php echo date('d.m.Y', strtotime($v_contact_file['create_date'])); ?></a></td>
					<td style="width:40%"><a href="<?php echo APP_BASE . 'stats/patientfileupload?doc_id='.$v_contact_file['id'].'&id='.$_REQUEST['id'];?>"><?php echo $v_contact_file['title']; ?></a></td>
					<td style="width:30%"><a href="<?php echo APP_BASE . 'stats/patientfileupload?doc_id='.$v_contact_file['id'].'&id='.$_REQUEST['id'];?>"><?php echo $v_contact_file['file_type']; ?></a></td>
					</tr>
        		</tbody>
        	</table>
        	<?php $i++; endforeach; ?>		 		
     	   </div>		
         <?php endif;  ?>
        <?php endif;?>
    	<?php endforeach;?>
    	
 
    	 <?php foreach($allowed_medication_types as $k=>$medication_type):?>
        	<?php if($medication_type == 'actual'):?>
			<?php if(in_array($medication_type,$timed_scheduled_medications)):?>
        	
        	<div class="mk-container">
            	<!-- top -->
            	<div class="mk-top">
            		<h2><?php echo $this->translate('noch nicht eingepflegte Änderungen');?> </h2>
            	    <?php 
                        $colspan_diagno = count($this->dosage_intervals[$medication_type]); 
                        $colspan_table = $colspan_diagno + 6;
            		?>            		
            		<table class="medikation" cellspacing="0" cellpadding="0" border="0">
                		<thead>
	                		<tr>
                				<th rowspan="2" colspan="2" class="name">NAME / <span>WIRKSTOFF</span></th>
                				<th colspan="<?php echo count($this->dosage_intervals[$medication_type])?>" class="dosierung">DOSIERUNG</th>
                				<th rowspan="2">INDIKATION / KOMMENTAR</th>
                				<th rowspan="2">ESKALATION</th>
                				<th rowspan="2" colspan="2">LETZTE ÄNDERUNG</th>
                			</tr>
 
                			<tr class="time">
                				<!--  DOSAGE TABLE HEADER KIDS-->
                	 			<?php foreach($this->dosage_intervals[$medication_type] as $k => $di):?>
                		 			<th><?php echo $di;?></th>
                	 			<?php endforeach;?>
                			</tr>
                		</thead>   
                		<tbody>
                    		<?php 
                    		foreach($medication_array[$medication_type] as $k =>$med):?>
                    		
                    		    <?php
                    		    $has_ack_class="";
                    
                    		    if((  !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :
                        		    $has_ack_class = "has_ack";
                                endif; 
                                ?>
                    		    <?php 
                    		    $data_medid= "";  
                    			if((  !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :
                                    $data_medid ='data-medid="'. $med['id'].'"' ;  
                    			endif; 
                                ?> 
                                
                                <!--  Check if the medication line - needs multiple rows  -->
                                <?php $row_type = "double";?>
                                <?php $row_span = ' rowspan="2"';?>
                                
                            		<?php
                            		 $dosage_concentration_line = array();
                            		 foreach($this->dosage_intervals[$medication_type] as $k => $dosage_time):?>
                                        <!-- TODO-3624 Ancuta 23.11.2020 --> 
                    				    <?php if (isset($med['dosage'][$dosage_time]) && strlen(trim($med['dosage'][$dosage_time])) > 0 && !empty($med['dosage_concentration'][$dosage_time]) ):?>
                    					   <?php  $dosage_concentration_line[] =  $med['dosage_concentration'][$dosage_time];?>
                    					<?php endif;?>
                    				<?php endforeach;?>
                                
                                <?php if(empty($med['drug']) && empty($dosage_concentration_line)):?>
                                    <?php $row_type = " single";?>
                                    <?php $row_span = '';?>    
                                <?php endif;?>
                                <!-- end check -->
 
                     <!--  ##############- Online -########################## -->			
                    		<?php if(! empty($med['on_hold_changes'][$med['id']] )) : ?>
                    			<?php
                    			    $online_on_hold_changes = array();
                    			    $online_on_hold_changes = $med['on_hold_changes'][$med['id']];
                    				$ack_referance_txt = array();
                                    $ack_referance_del = array();
                                    $ack_referance_txt[$med['id']]="";
                    				$ack_referance_del[$med['id']] = "";
                    
                    				  if($med['on_hold_changes'][$med['id']]['status'] == "delete")
                    				  {
                    					 $ack_referance_txt[$med['id']] = '<span class="blue_text">'.$this->translate("Unapproved changes: ").'</span>';
                    					 $ack_referance_del[$med['id']] = '<span class="red_text">'.$this->translate("Delete medication: ").'</span>'; 
                    				  } 
                    				  else if($med['on_hold_changes'][$med['id']]['status'] == "new")
                    				  {
                    					 $ack_referance_txt[$med['id']] = '<span class="green_text">'.$this->translate("Unapproved newly added medication: ").'</span>'; 
                    					 $ack_referance_del[$med['id']] = ''; 
                    				  } 
                    				  else
                    				  {
                    					 $ack_referance_txt[$med['id']] = '<span class="blue_text">'.$this->translate("Unapproved changes: ").'</span>'; 
                    					 $ack_referance_del[$med['id']] = ''; 
                    				  }
                                   
                     		 
                    				if($this->approval_rights == "1")
                    				{
                    					$app_rights = '<button class="med_approve_rights approvem" data-action="approve" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Approve").'</button><button class="med_approve_rights denym"   data-action="decline" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Decline").'</button>';
                    					$approve = '<button class="med_approve_rights approvem" data-action="approve" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Approve").'</button>';
                    					$deny = '<button class="med_approve_rights denym"   data-action="decline" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Decline").'</button>';
                    	 			} 
                    				else
                    				{
                    					$app_rights = '';
                    					$approve = '';
                    					$deny = '';
                    				}
                     		?>
                    
                    		  <tr class="double extedned_ack  ack_medication_row_<?php echo $med['id']?> " >
                    		  
                                    <!-- TD: Sort -->		  
                    				<td class="sortnum" rowspan="2"> </td>
                    				
                    		  
                                    <!-- TD: Name +  Ack Referance -->		  
                    				<td class="name">
                    				    <?php echo $ack_referance_txt[$med['id']];?><br/><br/>
                    				    <?php echo $online_on_hold_changes['name'];?>
                    				</td>
                    				
                    		  
                    				<?php foreach($this->dosage_intervals[$medication_type] as $k => $dosage_time):?>
                                    <!-- TD: Dosage- timeintervals -->		  
                    				<td class="dosierung"><?php echo $online_on_hold_changes['dosage'][$dosage_time];?> 
                    				<?php if ($this->show_new_fileds == "1" && strlen($online_on_hold_changes['dosage'][$dosage_time]) > 0):?><?php echo $online_on_hold_changes['unit'];?><?php endif;?></td>
                    				<?php endforeach;?>
                    				
                    		  
                                    <!-- TD: Indication and Comment -->		  
                    				<td class="ind-comm" rowspan="2">
                        				<?php if(!empty($online_on_hold_changes['indication'])):?>
                            				<?php if(strlen( $online_on_hold_changes['indication_color']) > 0):?>
                            					<div class="indikation" style="color:#<?php echo $online_on_hold_changes['indication_color'];?>"><span class="circle" style="background:#<?php echo $online_on_hold_changes['indication_color'];?>"></span><?php echo $online_on_hold_changes['indication'];?> </div>
                            					<?php else:?>
                            					<div class="indikation" style="color:#000000"><span class="circle" style="background:#000000"></span><?php echo  $online_on_hold_changes['indication'];?></div>
                            				<?php endif;?>
                        				<?php endif;?>
                    					<div class="comment extra_padding_left"  id="<?php echo $med['id'];?>_medi_comment">
                    					   <?php echo $online_on_hold_changes['comments'];?>
                    					</div>
                    				</td>
                    				
                    		 		<!--TD: Escalation  -->
                    				<td class="escalation" rowspan="2">
                    					<div><?php echo $online_on_hold_changes['escalation']; ?></div>
                    				</td>
                    				
                                    <!-- TD: Date -->		  
                    				<td class="date" rowspan="2">
                    					<div class="date-cont"><?php echo date('d.m.Y',strtotime($online_on_hold_changes['medication_change_date']));?></div>
                    				</td>
                    		  
                                    <!-- TD: Details -->		  
                    				<td class="details ack_efa_expand_details" rowspan="2" data-efa_expand_details_id="<?php echo $med['id']?>"></td>
                    			</tr>
                    			
                    			<tr class="double last extedned_ack">
                    			
                                    <!-- TD: Drug-->			
                    				<td class="name wirkstoff"><?php echo $online_on_hold_changes['drug'];?></td>
                    				
                    				<?php foreach($this->dosage_intervals[$medication_type] as $k => $dosage_time):?>
                                    <!-- TD: Doseiges value per interval: -->			
                    				<td class="dosierung">
                    				    <!-- TODO-3624 Ancuta 23.11.2020 -->
                    				    <?php if ($this->show_new_fileds == "1" && strlen($online_on_hold_changes['dosage'][$dosage_time]) > 0):?>
                    					   <?php echo $online_on_hold_changes['dosage_concentration'][$dosage_time];?>
                    					<?php endif;?>
                    				</td>
                    				<?php endforeach;?>
                    			</tr>
                    			
                    			<tr class="ack_medication_details_row_<?php echo $med['id']?> hide_details expandedItem extedned_ack" >
                    			
                    				<td colspan="11"><!-- TODO 3247 Carmen 03.07.2020 -->
                    			
                    					<h3>APPLIKATIONSWEG, DARREICHUNGSFORM, EINHEIT, ETC</h3>
                    			
                    					<div class="ei-content">
                    			
                    						<ul class="item">
                    							<li><span>Konzentration: </span><?php echo $online_on_hold_changes['concentration'];?></li>
                    							<li><span>Einheit: </span><?php echo $online_on_hold_changes['unit'];?></li>
                    						</ul>
                    						
                    						<ul class="item">
                    							<li><span>Darreichungsform: </span><?php echo $online_on_hold_changes['dosage_form'];?></li>
                    							<li><span>Applikationsweg: </span><?php echo $online_on_hold_changes['type'];?></li>
                    						</ul>
                    						
                    						<?php if( ($medication_type=="actual") && $allow_normal_scheduled == "1"):?>
                        						<?php if($online_on_hold_changes['has_interval'] == "1"):?>
                        						<ul class="item">
                        							<li><span>Interval(Tage): </span><?php echo $online_on_hold_changes['days_interval'];?></li>
                        							<?php  if( $online_on_hold_changes['administration_date'] != "0000-00-00 00:00:00"):?>
                            							<li><span>Intervall zuletzt gestartet: </span>
                                                            <?php echo date("d.m.Y",strtotime($online_on_hold_changes['administration_date']));?>
                            							</li>
                           							<?php endif; ?>
                        						</ul>
                        						<?php endif;?>
                    						<?php endif;?>
                    						
                    						<?php if( !empty($online_on_hold_changes['prescribed_by'])):?>
                        						<ul class="item">
                        							<li><span><?php echo $this->translate('medication_prescribed_by');?>: </span><?php echo $online_on_hold_changes['prescribed_by'];?></li>
                        						</ul>
                    						<?php endif;?>
                    					</div>
                    				</td>
                    			</tr>
                    			
                    <?php  endif;?>
                     <!--  ##############- Online END-########################## -->		
                    		  <tr class="separator">
                    				<td colspan="<?php echo $colspan_table?>"> </td>
                    			</tr>
                    		<?php endforeach;?>
                    		
                    		</tbody>
                    	</table>
	      		
            	</div>
        	</div>
        	
        	<!-- NO TIME PERIOD  -->
        <?php elseif(!in_array($medication_type,$timed_scheduled_medications) && !in_array($medication_type,array('isschmerzpumpe','treatment_care','scheduled','ispumpe'))): ?>
        	
        	<div class="mk-container">
        	
        	<!-- top -->
        	<div class="mk-top">
        		<h2><?php echo $this->translate('noch nicht eingepflegte Änderungen');?></h2>      		
        	</div>
        	<!-- // top -->
        	
        		<table class="medikation" cellspacing="0" cellpadding="0" border="0">
        	    <?php 
        	       $colspan_table = 7; // change colspan according to blocks
        		?>
        		<thead>
        			<tr>
        				<th rowspan="2" colspan="2" class="name">NAME / <span>WIRKSTOFF</span></th>
        				<th colspan="" class="dosierung">DOSIERUNG / <span>INTERVALL</span></th>
        				<th rowspan="2">INDIKATION / KOMMENTAR</th>
        				<th rowspan="2" >ESKALATION</span></th>
        				<th rowspan="2" >LETZTE ÄNDERUNG</th>
        			</tr>
        		</thead>
 
        		<tbody>
        		<?php foreach($medication_array[$medication_type] as $k =>$med):?>
        		
        		    <?php
        		    $has_ack_class="";
        
        		    if(($this->acknowledge  == "1" && !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :
            		    $has_ack_class = "has_ack";
                    endif; 
                    ?>
        		    <?php 
        		    $data_medid= "";  
        			if(($this->acknowledge  == "1" && !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :
                        $data_medid ='data-medid="'. $med['id'].'"' ;  
        			endif; 
                    ?> 
                    
                    <!--  Check if the medication line - needs multiple rows  -->
                    <?php $row_type_nt = "double";?>
                    <?php $row_span_nt = ' rowspan="2"';?>
                    
                    <?php if(empty($med['drug']) && empty($med['dosage_interval'])):?>
                        <?php $row_type_nt = " single";?>
                        <?php $row_span_nt = '';?>    
                    <?php endif;?>
                    <!-- end check -->
                    
                    
    
 
 
        <!--  ##############- ONLINE -########################## --> 			
        		<?php if(   ! empty($med['on_hold_changes'][$med['id']] )) : ?>
        			<?php 
        			
        			    $online_on_hold_changes = array();
        			    $online_on_hold_changes = $med['on_hold_changes'][$med['id']]; 
        				$ack_referance_txt = array();
                        $ack_referance_del = array();
                        $ack_referance_txt[$med['id']]="";
        				$ack_referance_del[$med['id']] = "";
        
        				  if($med['on_hold_changes'][$med['id']]['status'] == "delete")
        				  {
        					 $ack_referance_txt[$med['id']] = '<span class="blue_text">'.$this->translate("Unapproved changes: ").'</span>';
        					 $ack_referance_del[$med['id']] = '<span class="red_text">'.$this->translate("Delete medication: ").'</span>'; 
        				  } 
        				  else if($med['on_hold_changes'][$med['id']]['status'] == "new")
        				  {
        					 $ack_referance_txt[$med['id']] = '<span class="green_text">'.$this->translate("Unapproved newly added medication: ").'</span>'; 
        					 $ack_referance_del[$med['id']] = ''; 
        				  } 
        				  else
        				  {
        					 $ack_referance_txt[$med['id']] = '<span class="blue_text">'.$this->translate("Unapproved changes: ").'</span>'; 
        					 $ack_referance_del[$med['id']] = ''; 
        				  }
        		 
        					$app_rights = '';
        					$approve = '';
        					$deny = '';
        			 
         		?>
         
        		  <tr class="double extedned_ack  ack_medication_row_<?php echo $med['id']?> " >
        		  
        		        <!-- TD:Sort -->  
        				<td class="sortnum" rowspan="2"> </td>
        				
        				<!-- TD: Name -->
        				<td class="name">
        				    <?php echo $ack_referance_txt[$med['id']];?><br/><br/>
        				    <?php echo $online_on_hold_changes['name'];?>
        				</td>
        				<!-- TD: Dosage -->
        				<td class="dosierung" rowspan="2">
        				<?php 
        				if(is_array($online_on_hold_changes['dosage'])){
        				    $online_on_hold_changes['dosage'] = implode('-',$online_on_hold_changes['dosage']);
        				}
        				?>
        				    <?php echo $online_on_hold_changes['dosage'];?> 
        				    <?php if ($this->show_new_fileds == "1" && strlen($online_on_hold_changes['dosage']) > 0):?><?php echo $online_on_hold_changes['unit'];?><?php endif;?>
        				</td>
        				
        				<!-- TD: Indication -->
        				<td class="ind-comm" rowspan="2">
            				<?php if(!empty($online_on_hold_changes['indication'])):?>
                				<?php if(strlen($online_on_hold_changes['indication_color']) > 0):?>
                					<div class="indikation" style="color:#<?php echo $online_on_hold_changes['indication_color'];?>"><span class="circle" style="background:#<?php echo $online_on_hold_changes['indication_color'];?>"></span><?php echo $online_on_hold_changes['indication'];?> </div>
                					<?php else:?>
                					<div class="indikation" style="color:#000000"><span class="circle" style="background:#000000"></span><?php echo $online_on_hold_changes['indication'];?></div>
                				<?php endif;?>
            				<?php endif;?>
        					<div class="comment extra_padding_left"  id="<?php echo $med['id'];?>_medi_comment"><?php echo $online_on_hold_changes['comments'];?></div>
        				</td>
        				
        				<!-- TD: Escalation -->
        				<?php if($medication_type == "iscrisis" || $medication_type == "isbedarfs" || $medication_type == 'actual'):?><!-- TODO-3247 Carmen 03.07.2020 -->
        				<td class="escalation" rowspan="2">
        					<div class="escalation"><?php echo $online_on_hold_changes['escalation'];?></div>
        				</td>
        				<?php endif;?>
        				
        				<!-- TD: Date -->
        				<td class="date" rowspan="2">
        					<div class="date-cont"><?php echo date('d.m.Y',strtotime($online_on_hold_changes['medication_change_date']));?></div>
        				</td>
        				
        				<!-- TD: Details -->
        				<td class="details ack_efa_expand_details" rowspan="2" data-efa_expand_details_id="<?php echo $med['id']?>"></td>
        			</tr>
        			
        			<tr class="double last extedned_ack">
        			    <!-- TD: Drug -->
        				<td class="name wirkstoff"><?php echo $online_on_hold_changes['drug'];?></td>
        			</tr>
        			
        			
        			<tr class="ack_medication_details_row_<?php echo $med['id']?> hide_details expandedItem extedned_ack" >
        			
        				<td colspan="<?php echo $colspan_table; ?>">
        					
        					<h3>APPLIKATIONSWEG, DARREICHUNGSFORM, EINHEIT, ETC</h3>
        					
        					<div class="ei-content">
        					
        						<ul class="item">
        							<li><span>Konzentration: </span><?php echo $online_on_hold_changes['concentration'];?></li>
        							<li><span>Einheit: </span><?php echo $online_on_hold_changes['unit'];?></li>
        						</ul>
        						
        						<ul class="item">
        							<li><span>Darreichungsform: </span><?php echo $online_on_hold_changes['dosage_form'];?></li>
        							<li><span>Applikationsweg: </span><?php echo $online_on_hold_changes['type'];?></li>
        						</ul>
        						
        						<?php if( ($medication_type=="actual" || $medication_type == "isivmed") && $allow_normal_scheduled == "1"):?>
            						<?php if($online_on_hold_changes['has_interval'] == "1"):?>
            						<ul class="item">
            							<li><span>Interval(Tage): </span><?php echo $online_on_hold_changes['days_interval'];?></li>
            							<?php  if( $online_on_hold_changes['administration_date'] != "0000-00-00 00:00:00"):?>
                							<li><span>Intervall zuletzt gestartet: </span>
                							 <?php echo date("d.m.Y",strtotime($online_on_hold_changes['administration_date']));?>
                							</li>
               							<?php endif; ?>
            						</ul>
            						<?php endif;?>
        						<?php endif;?>
        					</div>
        				</td>
        			</tr>
                    <?php  endif;?>
        <!--  ##############- ONLINE END -########################## -->
                    			
        		  <tr class="separator">
        				<td colspan="<?php echo $colspan_table?>"> </td>
        			</tr>
        		<?php endforeach;?>
        		
        		</tbody>
        	</table>

        	</div>      
  
        <?php endif;?>        	
 
        	        
           
		<!-- ####  Acknolege  #### -->
    	<?php if(count($contact_form_files)>0 && 1==2):  ?>
    	    <p style="color:red;"><?php echo $this->translate('noch nicht eingepflegte Änderungen');?></p>	
    	
    	    <div class="mk-container">

			<?php $i = 1;
			foreach ($contact_form_files as $k_contact_file => $v_contact_file): ?>
			 <table id="dateien_verlauf_state" class="medication_edit_table medikation dateien_verlauf_edit_table">

 				<tbody>
				<?php if( $i % 2 == 0):  ?>
			    	<tr>
				<?php else : ?>
					<tr style="background: #F3F3F3!important;">
				<?php endif;  ?>
					<td style="width:30%"><a href="<?php echo APP_BASE . 'stats/patientfileupload?doc_id='.$v_contact_file['id'].'&id='.$_REQUEST['id'];?>"><?php echo $users_data[$v_contact_file['create_user']]['first_name'].', '.$users_data[$v_contact_file['create_user']]['last_name']; ?><br/><?php echo date('d.m.Y', strtotime($v_contact_file['create_date'])); ?></a></td>
					<td style="width:40%"><a href="<?php echo APP_BASE . 'stats/patientfileupload?doc_id='.$v_contact_file['id'].'&id='.$_REQUEST['id'];?>"><?php echo $v_contact_file['title']; ?></a></td>
					<td style="width:30%"><a href="<?php echo APP_BASE . 'stats/patientfileupload?doc_id='.$v_contact_file['id'].'&id='.$_REQUEST['id'];?>"><?php echo $v_contact_file['file_type']; ?></a></td>
					</tr>
        		</tbody>
        	</table>
        	<?php $i++; endforeach; ?>		 		
    
     	   </div>		
         <?php endif;  ?>
        	
        <?php endif;?>
        
    	<?php endforeach;?>
    	
    </div>
    
    
    
    
    
    
    
    <!--  ##################################################### -->
    <!--  ##############- isbedarfs -########################## -->		
    <!--  ##################################################### -->
    <div id="tab-isbedarfs">
        <?php foreach($allowed_medication_types as $k=>$medication_type):?>
		<?php if($medication_type == "isbedarfs"):?>
		
		<?php if(in_array($medication_type,$timed_scheduled_medications)):?>
		
        	<div class="mk-container">
            	<!-- top -->
            	<div class="mk-top">
            		<h2><?php echo $this->translate($medication_type." medication title")?> </h2>

            	    <?php $colspan_diagno = count($this->dosage_intervals[$medication_type]); ?>
            	    <?php 
        	       	   $colspan_table = $colspan_diagno + 6;
            		?>       
            		    			
        		    <table class="medikation" cellspacing="0" cellpadding="0" border="0">
                		<thead>
                			<tr>
                				<th rowspan="2" colspan="2" class="name">NAME / <span>WIRKSTOFF</span></th>
                				<th colspan="<?php echo count($this->dosage_intervals[$medication_type])?>" class="dosierung">DOSIERUNG</th>
                				<th rowspan="2">INDIKATION / KOMMENTAR</th>
                				<th rowspan="2">ESKALATION</th>
                				<th rowspan="2" colspan="2">LETZTE ÄNDERUNG</th>
                			</tr>
    
                			<tr class="time">
                				<!--  DOSAGE TABLE HEADER KIDS-->
                	 			<?php foreach($this->dosage_intervals[$medication_type] as $k => $di):?>
                		 			<th><?php echo $di;?></th>
                	 			<?php endforeach;?>
                			</tr>
                		</thead>      
                    		<?php 
                    		foreach($medication_array[$medication_type] as $k =>$med):?>
                    		
                    		    <?php
                    		    $has_ack_class="";
                    
                    		    if(( !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :
                        		    $has_ack_class = "has_ack";
                                endif; 
                                ?>
                    		    <?php 
                    		    $data_medid= "";  
                    			if((  !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :
                                    $data_medid ='data-medid="'. $med['id'].'"' ;  
                    			endif; 
                                ?> 
                                
                                
                                
                                <!--  Check if the medication line - needs multiple rows  -->
                                <?php $row_type = "double";?>
                                <?php $row_span = ' rowspan="2"';?>
                                
                            		<?php
                            		 $dosage_concentration_line = array();
                            		 foreach($this->dosage_intervals[$medication_type] as $k => $dosage_time):?>
                                        <!-- TODO-3624 Ancuta 23.11.2020 --> 
                    				    <?php if (isset($med['dosage'][$dosage_time]) && strlen(trim($med['dosage'][$dosage_time])) > 0 && !empty($med['dosage_concentration'][$dosage_time]) ):?>
                    					   <?php  $dosage_concentration_line[] =  $med['dosage_concentration'][$dosage_time];?>
                    					<?php endif;?>
                    				<?php endforeach;?>
                                
                                <?php if(empty($med['drug']) && empty($dosage_concentration_line)):?>
                                    <?php $row_type = " single";?>
                                    <?php $row_span = '';?>    
                                <?php endif;?>
                                <!-- end check -->
                                
                                
                                
                                
                                <tr  class="<?php echo $row_type; ?> <?php if($row_type =="double"): ?>first <?php endif;?> medication_row_<?php echo $med['id']?> " <?php echo $data_medid?>>
                                    <!--TD: Sort/Importance  -->			
                    				<td class="sortnum" <?php echo $row_span?> ><span> <?php echo $med['importance']; ?></span></td>
                    				
                                    <!--TD: Name  -->
                    				<td class="name"><?php echo $med['medication'];?></td>
                    				
                                    <!--TD: Time dosage  -->				
                    				<?php foreach($this->dosage_intervals[$medication_type] as $k => $dosage_time):?>
                    				<td class="dosierung"><?php echo $med['dosage'][$dosage_time];?> <?php if (strlen($med['dosage'][$dosage_time]) > 0):?><?php echo $med['unit'];?><?php endif;?></td>
                    				<?php endforeach;?>
                    				
                                    <!--TD: Indication + Comment  -->								
                    				<td class="ind-comm" <?php echo $row_span?> >
                        				<?php if(!empty($med['indication'])):?>
                            				<?php if(strlen($med['indication_color']) > 0 ):?>
                            					<div class="indikation" style="color:#<?php echo $med['indication_color'];?>"><span class="circle" style="background:#<?php echo $med['indication_color'];?>"></span><?php echo $med['indication'];?></div>
                            					<?php else:?>
                               					<div class="indikation" style="color:#000000"><span class="circle" style="background:#000000"></span><?php echo $med['indication'];?></div>
                            				<?php endif;?>
                        				<?php endif;?>
                    					<div class="comment extra_padding_left"  id="<?php echo $med['id'];?>_medi_comment" > <?php echo $med['comments'];?> </div>
                    				</td>
                    				
                    				 <!--TD: Escalation  -->
                    				<?php if($medication_type == "isbedarfs" || $medication_type == "actual"):?><!-- TODO-3247 Carmen 03.07.2020 -->
                    				<td class="escalation" <?php echo $row_span; ?>>
                    					<div><?php echo $med['escalation']; ?></div>
                    				</td>
                    				<?php endif;?>
                    				
                                    <!--TD: Date+ History  -->				
                    				<td class="date" <?php echo $row_span?>>
                    					<input type="button" name="history" class="btnHistory show_medication_info"   data-medication_type="<?php echo $medication_type; ?>" data-drugplan_id="<?php echo $med['id']; ?>">
                    					<div class="date-cont"><?php echo date('d.m.Y',strtotime($med['medication_change']));?></div>
                    				</td>
                    				
                                    <!--TD: Details-->
                                    <!-- 				<td class="details efa_expand_details" <?php echo $row_span?> data-efa_expand_details_id="<?php echo $med['id']?>"></td>
                                    ISPC-2329 Lore 16.06.2020    -->				
                    				<td class="details efa_expand_details" <?php echo $row_span?> data-efa_expand_details_id="<?php echo $med['id']?>" ><button class="efa_expand_details_float" name="btn123" ></button></td>
                    			
                    				<td <?php echo $row_span?>>
                    					<img src="<?php echo RES_FILE_PATH?>/images/edit.png" alt="Bearbeiten" onclick='EditOneMedi(<?=json_encode($med, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP | JSON_UNESCAPED_UNICODE); ?>)'  />
                    				</td>                     			
                    			</tr>
                    			
                    			
                    			<?php if($row_type =="double"): ?>
                    			<tr class="<?php echo $row_type; ?> last  last_med_row_<?php echo $med['id']?> ">
                    			    
                    			    <!--TD: Drug-->
                    				<td class="name wirkstoff"><?php echo $med['drug'];?></td>
                    				
                    				
                    				<?php foreach($this->dosage_intervals[$medication_type] as $k => $dosage_time):?>
                    			    <!--TD: Dosage interval <?php echo $dosage_time;?>-->
                    				<td class="dosierung">
                    				    <!-- TODO-3624 Ancuta 23.11.2020 -->
                    				    <?php if (strlen($med['dosage'][$dosage_time]) > 0):?>
                    					   <?php echo $med['dosage_concentration'][$dosage_time];?>
                    					<?php endif;?>
                    				</td>
                    				<?php endforeach;?>
                    				
                    			</tr>
                    			<?php endif;?>
                    			
                    			
                    			<tr class="medication_details_row_<?php echo $med['id']?> hide_details expandedItem  "  >
                    			
                    				<td colspan="<?php echo $colspan_table; ?>">
                    			
                    					<h3>APPLIKATIONSWEG, DARREICHUNGSFORM, EINHEIT, ETC</h3>
                    			
                    					<div class="ei-content">
                    			
                    						<ul class="item">
                    							<li><span>Konzentration: </span><?php echo $med['concentration_full'];?></li>
                    							<li><span>Einheit: </span><?php echo $med['unit'];?></li>
                    						</ul>
                    						
                    						<ul class="item">
                    							<li><span>Darreichungsform: </span><?php echo $med['dosage_form'];?></li>
                    							<li><span>Applikationsweg: </span><?php echo $med['type'];?></li>
                    						</ul>
                    						
                    						<?php if(!empty($med['prescribed_by'])):?>
                        						<ul class="item">
                        							<li>
                                                        <span><?php echo $this->translate('medication_prescribed_by');?></span> <?php echo $med['prescribed_by'];?>
                        							</li> 
                        						</ul>
                    						<?php endif;?>
                    						
                    					</div>
                    				</td>
                    			</tr>

                    		  <tr class="separator">
                    				<td colspan="<?php echo $colspan_table?>"> </td>
                    			</tr>
                    		<?php endforeach;?>
                    		
                    		</tbody>
                    	</table>
        		
            	</div>
        	</div>	
        	  	
        	<!-- NO TIME PERIOD  -->
        	
        <?php elseif(!in_array($medication_type,$timed_scheduled_medications) && !in_array($medication_type,array('isschmerzpumpe','treatment_care','scheduled','ispumpe'))): ?>
        	
        	<div class="mk-container">
        	
        	<!-- top -->
        	<div class="mk-top">
        		<h2><?php echo $this->translate($medication_type." medication title")?> </h2>
        	</div>
        	<!-- // top -->
        	
        		<table class="medikation" cellspacing="0" cellpadding="0" border="0">
        	    <?php 
        	       $colspan_table = 7; // change colspan according to blocks
        		?>
        		<thead>
        			<tr>
        				<th rowspan="2" colspan="2" class="name">NAME / <span>WIRKSTOFF</span></th>
        				<th colspan="" class="dosierung">DOSIERUNG / <span>INTERVALL</span></th>
        				<th rowspan="2">INDIKATION / KOMMENTAR</th>
        				<th rowspan="2" >ESKALATION</span></th>
        				<th rowspan="2" >LETZTE ÄNDERUNG</th>
        			</tr>
        		</thead>
 
        		<tbody>
        		<?php foreach($medication_array[$medication_type] as $k =>$med):?>
        		
        		    <?php
        		    $has_ack_class="";
        
        		    if(( !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :
            		    $has_ack_class = "has_ack";
                    endif; 
                    ?>
        		    <?php 
        		    $data_medid= "";  
        			if((  !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :
                        $data_medid ='data-medid="'. $med['id'].'"' ;  
        			endif; 
                    ?> 
                    
                    <!--  Check if the medication line - needs multiple rows  -->
                    <?php $row_type_nt = "double";?>
                    <?php $row_span_nt = ' rowspan="2"';?>
                    
                    <?php if(empty($med['drug']) && empty($med['dosage_interval'])):?>
                        <?php $row_type_nt = " single";?>
                        <?php $row_span_nt = '';?>    
                    <?php endif;?>
                    <!-- end check -->
                    
                    
        
                    <tr  class="<?php echo $row_type_nt?> <?php if($row_type_nt == 'double'):?>first <?php endif;?> medication_row_<?php echo $med['id']?>  " <?php echo $data_medid?>>
        
                        <!--TD: Sort  -->
        				<td class="sortnum" <?php echo $row_span_nt?> ><span> <?php echo $med['importance']; ?></span></td>
        
                        <!--TD: Name  -->
        				<td class="name"><?php echo $med['medication'];?></td>
        				
                        <!--TD: Dosage  -->
        				<?php if($medication_type == "iscrisis" || $medication_type == "isbedarfs"):?>
        				<td class="dosierung" >
        				    <?php echo $med['dosage'];?> 
        				    <?php echo $med['unit'];?>
        				 </td>
        				<?php else:?>
        				<td class="dosierung" <?php echo $row_span_nt; ?>>
        				    <?php echo $med['dosage'];?> 
        				    <?php echo $med['unit'];?> 
        				 </td>
        				<?php endif;?>
        				
        
                        <!--TD: Indication Comment  -->
        				<td class="ind-comm" <?php echo $row_span_nt; ?>>
        				<?php if(!empty( $med['indication'])):?>
            				<?php if(strlen($med['indication_color']) > 0):?>
            					<div class="indikation" style="color:#<?php echo $med['indication_color'];?>"><span class="circle" style="background:#<?php echo $med['indication_color'];?>"></span><?php echo $med['indication'];?></div>
            					<?php else:?>
            					<div class="indikation" style="color:#000000"><span class="circle" style="background:#000000"></span><?php echo $med['indication'];?></div>
            				<?php endif;?>
        				<?php endif;?>
        					<div class="comment extra_padding_left"  id="<?php echo $med['id'];?>_medi_comment"><?php echo $med['comments'];?></div>
        				</td>
        
        
        				<?php if($medication_type == "iscrisis" || $medication_type == "isbedarfs" || $medication_type == 'actual'):?><!-- TODO-3247 Carmen 03.07.2020 -->
                        <!--TD: Escalation  -->
        				<td class="escalation" <?php echo $row_span_nt; ?>>
        					<div><?php echo $med['escalation']; ?></div>
        				</td>
        				<?php endif;?>
        
                        <!--TD: Date  -->
        				<td class="date" <?php echo $row_span_nt; ?>>
        					<input type="button" name="history" class="btnHistory show_medication_info"   data-medication_type="<?php echo $medication_type; ?>" data-drugplan_id="<?php echo $med['id']; ?>">
        					<div class="date-cont"><?php echo date('d.m.Y',strtotime($med['medication_change']));?></div>
        				</td>
        
                        <!--TD: Details  -->
                        <!-- 				<td class="details efa_expand_details" <?php echo $row_span_nt; ?> data-efa_expand_details_id="<?php echo $med['id']?>"></td>
                         ISPC-2329 Lore 16.06.2020    -->
        				<td class="details efa_expand_details" <?php echo $row_span_nt; ?> data-efa_expand_details_id="<?php echo $med['id']?>" ><button class="efa_expand_details_float" name="btn123" ></button></td>
        			
        				<td <?php echo $row_span_nt; ?> >
                    		<img src="<?php echo RES_FILE_PATH?>/images/edit.png" alt="Bearbeiten" onclick='EditOneMedi(<?=json_encode($med, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP | JSON_UNESCAPED_UNICODE); ?>)'  />
        				</td>         			
        			</tr>
        			
        			<?php if( $row_type_nt == 'double'):?>
        			<tr class="<?php echo $row_type_nt?> last last_med_row_<?php echo $med['id']?>  <?php if(($this->acknowledge  == "1" && !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :?> has_ack <?php endif; ?>">
        			
                        <!--TD: Drug  -->
        				<td class="name wirkstoff"><?php echo $med['drug'];?> </td>
        				
        				<?php if($medication_type == "iscrisis" || $medication_type == "isbedarfs"):?>
                        <!--TD: Dosage Interval -->
        				<td class="dosierung"><?php echo $med['dosage_interval'];?> </td>
        				<?php endif;?>
        			</tr>
        			<?php endif;?>
        			
        			<tr class="medication_details_row_<?php echo $med['id']?> hide_details expandedItem <?php if(($this->acknowledge  == "1" && !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :?> has_ack <?php endif; ?>"  >
        
                        <td colspan="<?php echo $colspan_table;?>">
        			
        					<h3>APPLIKATIONSWEG, DARREICHUNGSFORM, EINHEIT, ETC</h3>
        				
        					<div class="ei-content">
        						
        						<ul class="item">
        							<li><span>Konzentration: </span><?php echo $med['concentration_full'];?></li>
        							<li><span>Einheit: </span><?php echo $med['unit'];?></li>
        						</ul>
        						
        						<ul class="item">
        							<li><span>Darreichungsform: </span><?php echo $med['dosage_form'];?></li>
        							<li><span>Applikationsweg: </span><?php echo $med['type'];?></li>
        						</ul>
        					</div>
        				</td>
        			</tr>
        			
        		  <tr class="separator">
        				<td colspan="<?php echo $colspan_table?>"> </td>
        			</tr>
        		<?php endforeach;?>
        		
        		</tbody>
        	</table>
        	</div>              
        <?php endif;?>
        		 <?php $new_line = array('efaoption'=>'1','medication_block_type'=>$medication_type,'id'=>'x')?>
         <a href="javascript:void(0)" rel="actual" class="add_button_link medication_add_link"  onclick='EditOneMedi(<?=json_encode($new_line); ?>)'>Neues Medikament hinzufügen</a>
         <br/>&nbsp;
         <br/>&nbsp;
         <br/>&nbsp;
        	
		<!-- ####  Acknolege  #### -->
    	<?php if(count($contact_form_files)>0 && 1==2):  ?>
	        <p style="color:red;"><?php echo $this->translate('noch nicht eingepflegte Änderungen');?></p>	
    	    <div class="mk-container">

			<?php $i = 1;
			foreach ($contact_form_files as $k_contact_file => $v_contact_file): ?>
			 <table id="dateien_verlauf_state" class="medication_edit_table medikation dateien_verlauf_edit_table">

 				<tbody>
				<?php if( $i % 2 == 0):  ?>
			    	<tr>
				<?php else : ?>
					<tr style="background: #F3F3F3!important;">
				<?php endif;  ?>
					<td style="width:30%"><a href="<?php echo APP_BASE . 'stats/patientfileupload?doc_id='.$v_contact_file['id'].'&id='.$_REQUEST['id'];?>"><?php echo $users_data[$v_contact_file['create_user']]['first_name'].', '.$users_data[$v_contact_file['create_user']]['last_name']; ?><br/><?php echo date('d.m.Y', strtotime($v_contact_file['create_date'])); ?></a></td>
					<td style="width:40%"><a href="<?php echo APP_BASE . 'stats/patientfileupload?doc_id='.$v_contact_file['id'].'&id='.$_REQUEST['id'];?>"><?php echo $v_contact_file['title']; ?></a></td>
					<td style="width:30%"><a href="<?php echo APP_BASE . 'stats/patientfileupload?doc_id='.$v_contact_file['id'].'&id='.$_REQUEST['id'];?>"><?php echo $v_contact_file['file_type']; ?></a></td>
					</tr>
        		</tbody>
        	</table>
        	<?php $i++; endforeach; ?>		 		
    
     	   </div>		
         <?php endif;  ?>
                 	
		<?php endif;?>
        	
    	<?php endforeach;?>
    	
    	
    	
    	 <?php foreach($allowed_medication_types as $k=>$medication_type):?>
		<?php if($medication_type == "isbedarfs"):?>
		
		<?php if(in_array($medication_type,$timed_scheduled_medications)):?>
		
        	<div class="mk-container">
            	<!-- top -->
            	<div class="mk-top">
            		<h2><?php echo $this->translate('noch nicht eingepflegte Änderungen');?> </h2>

            	    <?php $colspan_diagno = count($this->dosage_intervals[$medication_type]); ?>
            	    <?php 
            	       	   $colspan_table = $colspan_diagno + 6;
            		?>       
            		    			
        		    <table class="medikation" cellspacing="0" cellpadding="0" border="0">
                		<thead>
                			<tr>
                				<th rowspan="2" colspan="2" class="name">NAME / <span>WIRKSTOFF</span></th>
                				<th colspan="<?php echo count($this->dosage_intervals[$medication_type])?>" class="dosierung">DOSIERUNG</th>
                				<th rowspan="2">INDIKATION / KOMMENTAR</th>
                				<th rowspan="2">ESKALATION</th>
                				<th rowspan="2" colspan="2">LETZTE ÄNDERUNG</th>
                			</tr>
 
                			<tr class="time">
                				<!--  DOSAGE TABLE HEADER KIDS-->
                	 			<?php foreach($this->dosage_intervals[$medication_type] as $k => $di):?>
                		 			<th><?php echo $di;?></th>
                	 			<?php endforeach;?>
                			</tr>
                		</thead>      
                    		<?php 
                    		foreach($medication_array[$medication_type] as $k =>$med):?>
                    		
                    		    <?php
                    		    $has_ack_class="";
                    
                    		    if(($this->acknowledge  == "1" && !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :
                        		    $has_ack_class = "has_ack";
                                endif; 
                                ?>
                    		    <?php 
                    		    $data_medid= "";  
                    			if(($this->acknowledge  == "1" && !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :
                                    $data_medid ='data-medid="'. $med['id'].'"' ;  
                    			endif; 
                                ?> 
                                
                                
                                
                                <!--  Check if the medication line - needs multiple rows  -->
                                <?php $row_type = "double";?>
                                <?php $row_span = ' rowspan="2"';?>
                                
                            		<?php
                            		 $dosage_concentration_line = array();
                            		 foreach($this->dosage_intervals[$medication_type] as $k => $dosage_time):?>
                                        <!-- TODO-3624 Ancuta 23.11.2020 --> 
                    				    <?php if (isset($med['dosage'][$dosage_time]) && strlen(trim($med['dosage'][$dosage_time])) > 0 && !empty($med['dosage_concentration'][$dosage_time]) ):?>
                    					   <?php  $dosage_concentration_line[] =  $med['dosage_concentration'][$dosage_time];?>
                    					<?php endif;?>
                    				<?php endforeach;?>
                                
                                <?php if(empty($med['drug']) && empty($dosage_concentration_line)):?>
                                    <?php $row_type = " single";?>
                                    <?php $row_span = '';?>    
                                <?php endif;?>
                                <!-- end check -->
                                 
                     <!--  ##############- Online -########################## -->			
                    		<?php if(   ! empty($med['on_hold_changes'][$med['id']] )) : ?>
                    			<?php
                    			    $online_on_hold_changes = array();
                    			    $online_on_hold_changes = $med['on_hold_changes'][$med['id']];
                    				$ack_referance_txt = array();
                                    $ack_referance_del = array();
                                    $ack_referance_txt[$med['id']]="";
                    				$ack_referance_del[$med['id']] = "";
                    
                    				  if($med['on_hold_changes'][$med['id']]['status'] == "delete")
                    				  {
                    					 $ack_referance_txt[$med['id']] = '<span class="blue_text">'.$this->translate("Unapproved changes: ").'</span>';
                    					 $ack_referance_del[$med['id']] = '<span class="red_text">'.$this->translate("Delete medication: ").'</span>'; 
                    				  } 
                    				  else if($med['on_hold_changes'][$med['id']]['status'] == "new")
                    				  {
                    					 $ack_referance_txt[$med['id']] = '<span class="green_text">'.$this->translate("Unapproved newly added medication: ").'</span>'; 
                    					 $ack_referance_del[$med['id']] = ''; 
                    				  } 
                    				  else
                    				  {
                    					 $ack_referance_txt[$med['id']] = '<span class="blue_text">'.$this->translate("Unapproved changes: ").'</span>'; 
                    					 $ack_referance_del[$med['id']] = ''; 
                    				  }
                                   
                     		 
                    				if($this->approval_rights == "1")
                    				{
                    					$app_rights = '<button class="med_approve_rights approvem" data-action="approve" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Approve").'</button><button class="med_approve_rights denym"   data-action="decline" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Decline").'</button>';
                    					$approve = '<button class="med_approve_rights approvem" data-action="approve" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Approve").'</button>';
                    					$deny = '<button class="med_approve_rights denym"   data-action="decline" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Decline").'</button>';
                    	 			} 
                    				else
                    				{
                    					$app_rights = '';
                    					$approve = '';
                    					$deny = '';
                    				}
                     		?>
                    
                    		  <tr class="double extedned_ack  ack_medication_row_<?php echo $med['id']?> " >
                    		  
                                    <!-- TD: Sort -->		  
                    				<td class="sortnum" rowspan="2"> </td>
                    				
                    		  
                                    <!-- TD: Name +  Ack Referance -->		  
                    				<td class="name">
                    				    <?php echo $ack_referance_txt[$med['id']];?><br/><br/>
                    				    <?php echo $online_on_hold_changes['name'];?>
                    				</td>
                    				
                    		  
                    				<?php foreach($this->dosage_intervals[$medication_type] as $k => $dosage_time):?>
                                    <!-- TD: Dosage- timeintervals -->		  
                    				<td class="dosierung"><?php echo $online_on_hold_changes['dosage'][$dosage_time];?> 
                    				<?php if ($this->show_new_fileds == "1" && strlen($online_on_hold_changes['dosage'][$dosage_time]) > 0):?><?php echo $online_on_hold_changes['unit'];?><?php endif;?></td>
                    				<?php endforeach;?>
                    				
                    		  
                                    <!-- TD: Indication and Comment -->		  
                    				<td class="ind-comm" rowspan="2">
                        				<?php if(!empty($online_on_hold_changes['indication'])):?>
                            				<?php if(strlen( $online_on_hold_changes['indication_color']) > 0):?>
                            					<div class="indikation" style="color:#<?php echo $online_on_hold_changes['indication_color'];?>"><span class="circle" style="background:#<?php echo $online_on_hold_changes['indication_color'];?>"></span><?php echo $online_on_hold_changes['indication'];?> </div>
                            					<?php else:?>
                            					<div class="indikation" style="color:#000000"><span class="circle" style="background:#000000"></span><?php echo  $online_on_hold_changes['indication'];?></div>
                            				<?php endif;?>
                        				<?php endif;?>
                    					<div class="comment extra_padding_left"  id="<?php echo $med['id'];?>_medi_comment">
                    					   <?php echo $online_on_hold_changes['comments'];?>
                    					</div>
                    				</td>
                    				
                    		 		<!--TD: Escalation  -->
                    				<?php if($medication_type == "isbedarfs" || $medication_type == "actual"):?><!-- TODO-3247 Carmen 03.07.2020 -->
                    				<td class="escalation" rowspan="2">
                    					<div><?php echo $online_on_hold_changes['escalation']; ?></div>
                    				</td>
                    				<?php endif;?>
                    				
                                    <!-- TD: Date -->		  
                    				<td class="date" rowspan="2">
                    					<div class="date-cont"><?php echo date('d.m.Y',strtotime($online_on_hold_changes['medication_change_date']));?></div>
                    				</td>
                    		  
                                    <!-- TD: Details -->		  
                    				<td class="details ack_efa_expand_details" rowspan="2" data-efa_expand_details_id="<?php echo $med['id']?>"></td>
                    			</tr>
                    			
                    			<tr class="double last extedned_ack">
                    			
                                    <!-- TD: Drug-->			
                    				<td class="name wirkstoff"><?php echo $online_on_hold_changes['drug'];?></td>
                    				
                    				<?php foreach($this->dosage_intervals[$medication_type] as $k => $dosage_time):?>
                                    <!-- TD: Doseiges value per interval: -->			
                    				<td class="dosierung">
                    				    <!-- TODO-3624 Ancuta 23.11.2020 -->
                    				    <?php if ($this->show_new_fileds == "1" && strlen($online_on_hold_changes['dosage'][$dosage_time]) > 0):?>
                    					   <?php echo $online_on_hold_changes['dosage_concentration'][$dosage_time];?>
                    					<?php endif;?>
                    				</td>
                    				<?php endforeach;?>
                    			</tr>
                    
                    			
                    			<tr class="ack_medication_details_row_<?php echo $med['id']?> hide_details expandedItem extedned_ack" >
                    			
                    				<td colspan="11"><!-- TODO 3247 Carmen 03.07.2020 -->
                    			
                    					<h3>APPLIKATIONSWEG, DARREICHUNGSFORM, EINHEIT, ETC</h3>
                    			
                    					<div class="ei-content">
                    			
                    						<ul class="item">
                    							<li><span>Konzentration: </span><?php echo $online_on_hold_changes['concentration'];?></li>
                    							<li><span>Einheit: </span><?php echo $online_on_hold_changes['unit'];?></li>
                    						</ul>
                    						
                    						<ul class="item">
                    							<li><span>Darreichungsform: </span><?php echo $online_on_hold_changes['dosage_form'];?></li>
                    							<li><span>Applikationsweg: </span><?php echo $online_on_hold_changes['type'];?></li>
                    						</ul>
                    						
                    						<?php if( ($medication_type=="actual" || $medication_type=="isivmed") && $allow_normal_scheduled == "1"):?>
                        						<?php if($online_on_hold_changes['has_interval'] == "1"):?>
                        						<ul class="item">
                        							<li><span>Interval(Tage): </span><?php echo $online_on_hold_changes['days_interval'];?></li>
                        							<?php  if( $online_on_hold_changes['administration_date'] != "0000-00-00 00:00:00"):?>
                            							<li><span>Intervall zuletzt gestartet: </span>
                                                            <?php echo date("d.m.Y",strtotime($online_on_hold_changes['administration_date']));?>
                            							</li>
                           							<?php endif; ?>
                        						</ul>
                        						<?php endif;?>
                    						<?php endif;?>
                    						
                    						<?php if($medication_type=="isintubated" ):?>
                        						<ul class="item">
                        							<li><span>Kcal: </span><?php echo $online_on_hold_changes['kcal'];?></li>
                        							<li><span>Volumen: </span><?php echo $online_on_hold_changes['volume'];?></li>
                        							<li><span>Kammerbeutel Info: </span><?php echo $online_on_hold_changes['packaging_name'];?></li>
                        						</ul>
                    						<?php endif;?>
                    					
                    					
                    						<?php if( !empty($online_on_hold_changes['prescribed_by'])):?>
                        						<ul class="item">
                        							<li><span><?php echo $this->translate('medication_prescribed_by');?>: </span><?php echo $online_on_hold_changes['prescribed_by'];?></li>
                        						</ul>
                    						<?php endif;?>
                    					
                    					
                    						
                    						<ul class="item">
                                                <li><?php echo $approve; ?></li>
                    							<li><?php echo $deny; ?></li>
                    						</ul>
                    						
                    					</div>
                    					
                    				</td>
                    				
                    			</tr>
                    			
                    <?php  endif;?>
                     <!--  ##############- Online END-########################## -->		
                                
                    		  <tr class="separator">
                    				<td colspan="<?php echo $colspan_table?>"> </td>
                    			</tr>
                    		<?php endforeach;?>
                    		
                    		</tbody>
                    	</table>
        		
            	</div>
        	</div>	
        	  	
        	<!-- NO TIME PERIOD  -->
        	
        <?php elseif(!in_array($medication_type,$timed_scheduled_medications) && !in_array($medication_type,array('isschmerzpumpe','treatment_care','scheduled','ispumpe'))): ?>
        	
        	<div class="mk-container">
        	
        	<!-- top -->
        	<div class="mk-top">
        		<h2><?php echo $this->translate('noch nicht eingepflegte Änderungen');?> </h2>
        	</div>
        	<!-- // top -->
        	
        		<table class="medikation" cellspacing="0" cellpadding="0" border="0">
        		<?php if($medication_type == "iscrisis"  || $medication_type == "isbedarfs" || $medication_type == "actual"):?><!-- TODO-3247 Carmen 03.07.2020 -->
        	    <?php 
        	       $colspan_table = 7; // change colspan according to blocks
        		?>
        		<thead>
        			<tr>
        				<th rowspan="2" colspan="2" class="name">NAME / <span>WIRKSTOFF</span></th>
        				<th colspan="" class="dosierung">DOSIERUNG / <span>INTERVALL</span></th>
        				<th rowspan="2">INDIKATION / KOMMENTAR</th>
        				<th rowspan="2" >ESKALATION</span></th>
        				<th rowspan="2" >LETZTE ÄNDERUNG</th>
        			</tr>
        		</thead>
        		<?php else:?>
        	    <?php 
        	       $colspan_table = 6; // change colspan according to blocks
        		?>
        		<thead>
        			<tr>
        				<th rowspan="2" colspan="2" class="name">NAME / <span>WIRKSTOFF</span></th>
        				<th colspan="" class="dosierung">DOSIERUNG</th>
        				<th rowspan="2">INDIKATION / KOMMENTAR</th>
        				<th rowspan="2" colspan="2">LETZTE ÄNDERUNG</th>
        			</tr>
        		</thead>
        		<?php endif;?>
        		<tbody>
        		<?php foreach($medication_array[$medication_type] as $k =>$med):?>
        		
        		    <?php
        		    $has_ack_class="";
        
        		    if(($this->acknowledge  == "1" && !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :
            		    $has_ack_class = "has_ack";
                    endif; 
                    ?>
        		    <?php 
        		    $data_medid= "";  
        			if(($this->acknowledge  == "1" && !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :
                        $data_medid ='data-medid="'. $med['id'].'"' ;  
        			endif; 
                    ?> 
                    
                    <!--  Check if the medication line - needs multiple rows  -->
                    <?php $row_type_nt = "double";?>
                    <?php $row_span_nt = ' rowspan="2"';?>
                    
                    <?php if(empty($med['drug']) && empty($med['dosage_interval'])):?>
                        <?php $row_type_nt = " single";?>
                        <?php $row_span_nt = '';?>    
                    <?php endif;?>
                    <!-- end check -->
                    
                      
        			
        <!--  ##############- ONLINE -########################## --> 			
        		<?php if(  ! empty($med['on_hold_changes'][$med['id']] )) : ?>
        			<?php 
        			
        			    $online_on_hold_changes = array();
        			    $online_on_hold_changes = $med['on_hold_changes'][$med['id']]; 
        				$ack_referance_txt = array();
                        $ack_referance_del = array();
                        $ack_referance_txt[$med['id']]="";
        				$ack_referance_del[$med['id']] = "";
        
        				  if($med['on_hold_changes'][$med['id']]['status'] == "delete")
        				  {
        					 $ack_referance_txt[$med['id']] = '<span class="blue_text">'.$this->translate("Unapproved changes: ").'</span>';
        					 $ack_referance_del[$med['id']] = '<span class="red_text">'.$this->translate("Delete medication: ").'</span>'; 
        				  } 
        				  else if($med['on_hold_changes'][$med['id']]['status'] == "new")
        				  {
        					 $ack_referance_txt[$med['id']] = '<span class="green_text">'.$this->translate("Unapproved newly added medication: ").'</span>'; 
        					 $ack_referance_del[$med['id']] = ''; 
        				  } 
        				  else
        				  {
        					 $ack_referance_txt[$med['id']] = '<span class="blue_text">'.$this->translate("Unapproved changes: ").'</span>'; 
        					 $ack_referance_del[$med['id']] = ''; 
        				  }
                       
         		 
        				if($this->approval_rights == "1")
        				{
        					$app_rights = '<button class="med_approve_rights approvem" data-action="approve" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Approve").'</button><button class="med_approve_rights denym"   data-action="decline" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Decline").'</button>';
        					$approve = '<button class="med_approve_rights approvem" data-action="approve" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Approve").'</button>';
        					$deny = '<button class="med_approve_rights denym"   data-action="decline" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Decline").'</button>';
        	 			} 
        				else
        				{
        					$app_rights = '';
        					$approve = '';
        					$deny = '';
        				}
         		?>
         
        		  <tr class="double extedned_ack  ack_medication_row_<?php echo $med['id']?> " >
        		  
        		        <!-- TD:Sort -->  
        				<td class="sortnum" rowspan="2"> </td>
        				
        				<!-- TD: Name -->
        				<td class="name">
        				    <?php echo $ack_referance_txt[$med['id']];?><br/><br/>
        				    <?php echo $online_on_hold_changes['name'];?>
        				</td>
        				<!-- TD: Dosage -->
        				<td class="dosierung" rowspan="2">
        				    <?php echo $online_on_hold_changes['dosage'];?> 
        				    <?php if ($this->show_new_fileds == "1" && strlen($online_on_hold_changes['dosage']) > 0):?><?php echo $online_on_hold_changes['unit'];?><?php endif;?>
        				</td>
        				
        				<!-- TD: Indication -->
        				<td class="ind-comm" rowspan="2">
            				<?php if(!empty($online_on_hold_changes['indication'])):?>
                				<?php if(strlen($online_on_hold_changes['indication_color']) > 0):?>
                					<div class="indikation" style="color:#<?php echo $online_on_hold_changes['indication_color'];?>"><span class="circle" style="background:#<?php echo $online_on_hold_changes['indication_color'];?>"></span><?php echo $online_on_hold_changes['indication'];?> </div>
                					<?php else:?>
                					<div class="indikation" style="color:#000000"><span class="circle" style="background:#000000"></span><?php echo $online_on_hold_changes['indication'];?></div>
                				<?php endif;?>
            				<?php endif;?>
        					<div class="comment extra_padding_left"  id="<?php echo $med['id'];?>_medi_comment"><?php echo $online_on_hold_changes['comments'];?></div>
        				</td>
        				
        				<!-- TD: Escalation -->
        				<?php if($medication_type == "iscrisis" || $medication_type == "isbedarfs" || $medication_type == 'actual'):?><!-- TODO-3247 Carmen 03.07.2020 -->
        				<td class="escalation" rowspan="2">
        					<div class="escalation"><?php echo $online_on_hold_changes['escalation'];?></div>
        				</td>
        				<?php endif;?>
        				
        				<!-- TD: Date -->
        				<td class="date" rowspan="2">
        					<div class="date-cont"><?php echo date('d.m.Y',strtotime($online_on_hold_changes['medication_change_date']));?></div>
        				</td>
        				
        				<!-- TD: Details -->
        				<td class="details ack_efa_expand_details" rowspan="2" data-efa_expand_details_id="<?php echo $med['id']?>"></td>
        			</tr>
        			
        			<tr class="double last extedned_ack">
        			    <!-- TD: Drug -->
        				<td class="name wirkstoff"><?php echo $online_on_hold_changes['drug'];?></td>
        			</tr>
        			
        			
        			<tr class="ack_medication_details_row_<?php echo $med['id']?> hide_details expandedItem extedned_ack" >
        			
        				<td colspan="<?php echo $colspan_table; ?>">
        					
        					<h3>APPLIKATIONSWEG, DARREICHUNGSFORM, EINHEIT, ETC</h3>
        					
        					<div class="ei-content">
        					
        						<ul class="item">
        							<li><span>Konzentration: </span><?php echo $online_on_hold_changes['concentration'];?></li>
        							<li><span>Einheit: </span><?php echo $online_on_hold_changes['unit'];?></li>
        						</ul>
        						
        						<ul class="item">
        							<li><span>Darreichungsform: </span><?php echo $online_on_hold_changes['dosage_form'];?></li>
        							<li><span>Applikationsweg: </span><?php echo $online_on_hold_changes['type'];?></li>
        						</ul>
        						
        						<?php if( ($medication_type=="actual" || $medication_type=="isivmed") && $allow_normal_scheduled == "1"):?>
            						<?php if($online_on_hold_changes['has_interval'] == "1"):?>
            						<ul class="item">
            							<li><span>Interval(Tage): </span><?php echo $online_on_hold_changes['days_interval'];?></li>
            							<?php  if( $online_on_hold_changes['administration_date'] != "0000-00-00 00:00:00"):?>
                							<li><span>Intervall zuletzt gestartet: </span>
                							 <?php echo date("d.m.Y",strtotime($online_on_hold_changes['administration_date']));?>
                							</li>
               							<?php endif; ?>
            						</ul>
            						<?php endif;?>
        						<?php endif;?>
        						
        						<ul class="item">
        		 				    <li><?php echo $approve; ?></li>
                                    <li><?php echo $deny; ?></li>
        						</ul>
        					</div>
        					
        				</td>
        				
        			</tr>
                    <?php  endif;?>
        <!--  ##############- ONLINE END -########################## -->
        		  <tr class="separator">
        				<td colspan="<?php echo $colspan_table?>"> </td>
        			</tr>
        		<?php endforeach;?>
        		</tbody>
        	</table>
        	</div>              
        <?php endif;?>
		<?php endif;?>
    	<?php endforeach;?>
    	
    	
    	
    	
    	
    	
    	
    	
    	
    </div>
    
    <!--  ##################################################### -->
    <!--  #################- iscrisis -######################## -->		
    <!--  ##################################################### -->
    <div id="tab-iscrisis">
        <?php foreach($allowed_medication_types as $k=>$medication_type):?>
        	<?php if($medication_type == 'iscrisis'):?>
        	<?php if(in_array($medication_type,$timed_scheduled_medications)):?>
        	
        	<!-- NO TIME PERIOD  -->
        	
        <?php elseif(!in_array($medication_type,$timed_scheduled_medications) && !in_array($medication_type,array('isschmerzpumpe','treatment_care','scheduled','ispumpe'))): ?>
        	
        	<div class="mk-container">
        	
        	<!-- top -->
        	<div class="mk-top">
        		<h2><?php echo $this->translate($medication_type." medication title")?> </h2>
        	</div>
        	<!-- // top -->
        	
        		<table class="medikation" cellspacing="0" cellpadding="0" border="0">
        		<?php if($medication_type == "iscrisis"  || $medication_type == "isbedarfs" || $medication_type == "actual"):?><!-- TODO-3247 Carmen 03.07.2020 -->
        	    <?php 
        	       $colspan_table = 7; // change colspan according to blocks
        		?>
        		<thead>
        			<tr>
        				<th rowspan="2" colspan="2" class="name">NAME / <span>WIRKSTOFF</span></th>
        				<th colspan="" class="dosierung">DOSIERUNG / <span>INTERVALL</span></th>
        				<th rowspan="2">INDIKATION / KOMMENTAR</th>
        				<th rowspan="2" >ESKALATION</span></th>
        				<th rowspan="2" >LETZTE ÄNDERUNG</th>
        			</tr>
        		</thead>
        		<?php else:?>
        	    <?php 
        	       $colspan_table = 6; // change colspan according to blocks
        		?>
        		<thead>
        			<tr>
        				<th rowspan="2" colspan="2" class="name">NAME / <span>WIRKSTOFF</span></th>
        				<th colspan="" class="dosierung">DOSIERUNG</th>
        				<th rowspan="2">INDIKATION / KOMMENTAR</th>
        				<th rowspan="2" colspan="2">LETZTE ÄNDERUNG</th>
        			</tr>
        		</thead>
        		<?php endif;?>
        		<tbody>
        		<?php 
        		foreach($medication_array[$medication_type] as $k =>$med):?>
        		
        		    <?php
        		    $has_ack_class="";
        
        		    if(($this->acknowledge  == "1" && !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :
            		    $has_ack_class = "has_ack";
                    endif; 
                    ?>
        		    <?php 
        		    $data_medid= "";  
        			if(($this->acknowledge  == "1" && !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :
                        $data_medid ='data-medid="'. $med['id'].'"' ;  
        			endif; 
                    ?> 
                    
                    <!--  Check if the medication line - needs multiple rows  -->
                    <?php $row_type_nt = "double";?>
                    <?php $row_span_nt = ' rowspan="2"';?>
                    
                    <?php if(empty($med['drug']) && empty($med['dosage_interval'])):?>
                        <?php $row_type_nt = " single";?>
                        <?php $row_span_nt = '';?>    
                    <?php endif;?>
                    <!-- end check -->
                    
                    
        
                    <tr  class="<?php echo $row_type_nt?> <?php if($row_type_nt == 'double'):?>first <?php endif;?> medication_row_<?php echo $med['id']?> <?php echo $has_ack_class;?>" <?php echo $data_medid?>>
        
                        <!--TD: Sort  -->
        				<td class="sortnum" <?php echo $row_span_nt?> ><span> <?php echo $med['importance']; ?></span></td>
        
                        <!--TD: Name  -->
        				<td class="name"><?php echo $med['medication'];?></td>
        				
                        <!--TD: Dosage  -->
        				<?php if($medication_type == "iscrisis" || $medication_type == "isbedarfs"):?>
        				<td class="dosierung" >
        				    <?php echo $med['dosage'];?> 
        				    <?php echo $med['unit'];?>
        				 </td>
        				<?php else:?>
        				<td class="dosierung" <?php echo $row_span_nt; ?>>
        				    <?php echo $med['dosage'];?> 
        				    <?php echo $med['unit'];?> 
        				 </td>
        				<?php endif;?>
        				
        
                        <!--TD: Indication Comment  -->
        				<td class="ind-comm" <?php echo $row_span_nt; ?>>
        				<?php if(!empty( $med['indication'])):?>
            				<?php if(strlen($med['indication_color']) > 0):?>
            					<div class="indikation" style="color:#<?php echo $med['indication_color'];?>"><span class="circle" style="background:#<?php echo $med['indication_color'];?>"></span><?php echo $med['indication'];?></div>
            					<?php else:?>
            					<div class="indikation" style="color:#000000"><span class="circle" style="background:#000000"></span><?php echo $med['indication'];?></div>
            				<?php endif;?>
        				<?php endif;?>
        					<div class="comment extra_padding_left"  id="<?php echo $med['id'];?>_medi_comment"><?php echo $med['comments'];?></div>
        				</td>
        
        
        				<?php if($medication_type == "iscrisis" || $medication_type == "isbedarfs" || $medication_type == 'actual'):?><!-- TODO-3247 Carmen 03.07.2020 -->
                        <!--TD: Escalation  -->
        				<td class="escalation" <?php echo $row_span_nt; ?>>
        					<div><?php echo $med['escalation']; ?></div>
        				</td>
        				<?php endif;?>
        
                        <!--TD: Date  -->
        				<td class="date" <?php echo $row_span_nt; ?>>
        					<input type="button" name="history" class="btnHistory show_medication_info"   data-medication_type="<?php echo $medication_type; ?>" data-drugplan_id="<?php echo $med['id']; ?>">
        					<div class="date-cont"><?php echo date('d.m.Y',strtotime($med['medication_change']));?></div>
        				</td>
        
                        <!--TD: Details  -->
                        <!-- 				<td class="details efa_expand_details" <?php echo $row_span_nt; ?> data-efa_expand_details_id="<?php echo $med['id']?>"></td>
                         ISPC-2329 Lore 16.06.2020    -->
        				<td class="details efa_expand_details" <?php echo $row_span_nt; ?> data-efa_expand_details_id="<?php echo $med['id']?>" ><button class="efa_expand_details_float" name="btn123" ></button></td>
        			
        				<td <?php echo $row_span_nt; ?>>
                    		<img src="<?php echo RES_FILE_PATH?>/images/edit.png" alt="Bearbeiten" onclick='EditOneMedi(<?=json_encode($med, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP | JSON_UNESCAPED_UNICODE); ?>)'  />
        				</td>         			
        			</tr>
        			
        			<?php if( $row_type_nt == 'double'):?>
        			<tr class="<?php echo $row_type_nt?> last last_med_row_<?php echo $med['id']?>  <?php if(($this->acknowledge  == "1" && !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :?> has_ack <?php endif; ?>">
        			
                        <!--TD: Drug  -->
        				<td class="name wirkstoff"><?php echo $med['drug'];?> </td>
        				
        				<?php if($medication_type == "iscrisis" || $medication_type == "isbedarfs"):?>
                        <!--TD: Dosage Interval -->
        				<td class="dosierung"><?php echo $med['dosage_interval'];?> </td>
        				<?php endif;?>
        			</tr>
        			<?php endif;?>
        			
        			<tr class="medication_details_row_<?php echo $med['id']?> hide_details expandedItem <?php if(($this->acknowledge  == "1" && !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :?> has_ack <?php endif; ?>"  >
        
                        <td colspan="<?php echo $colspan_table;?>">
        			
        					<h3>APPLIKATIONSWEG, DARREICHUNGSFORM, EINHEIT, ETC</h3>
        				
        					<div class="ei-content">
        						
        						<ul class="item">
        							<li><span>Konzentration: </span><?php echo $med['concentration_full'];?></li>
        							<li><span>Einheit: </span><?php echo $med['unit'];?></li>
        						</ul>
        						
        						<ul class="item">
        							<li><span>Darreichungsform: </span><?php echo $med['dosage_form'];?></li>
        							<li><span>Applikationsweg: </span><?php echo $med['type'];?></li>
        						</ul>
        						
 
        						
        					</div>
        				</td>
        			</tr>
 
        
                    			
       
        			
        		  <tr class="separator">
        				<td colspan="<?php echo $colspan_table?>"> </td>
        			</tr>
        		<?php endforeach;?>
        		
        		</tbody>
        	</table>
        	</div>              
        <?php endif;?>

		 <?php $new_line = array('efaoption'=>'1','medication_block_type'=>$medication_type,'id'=>'x')?>
         <a href="javascript:void(0)" rel="actual" class="add_button_link medication_add_link"  onclick='EditOneMedi(<?=json_encode($new_line); ?>)'>Neues Medikament hinzufügen</a>
         <br/>&nbsp;
         <br/>&nbsp;
         <br/>&nbsp;
        	        


		<!-- ####  Acknolege  #### -->
    	<?php if(count($contact_form_files)>0 && 1==2):  ?>
    	    <p style="color:red;"><?php echo $this->translate('noch nicht eingepflegte Änderungen');?></p>	
    	    <div class="mk-container">
    			<?php $i = 1;
    			foreach ($contact_form_files as $k_contact_file => $v_contact_file): ?>
        			 <table id="dateien_verlauf_state" class="medication_edit_table medikation dateien_verlauf_edit_table">
        
         				<tbody>
        				<?php if( $i % 2 == 0):  ?>
        			    	<tr>
        				<?php else : ?>
        					<tr style="background: #F3F3F3!important;">
        				<?php endif;  ?>
        					<td style="width:30%"><a href="<?php echo APP_BASE . 'stats/patientfileupload?doc_id='.$v_contact_file['id'].'&id='.$_REQUEST['id'];?>"><?php echo $users_data[$v_contact_file['create_user']]['first_name'].', '.$users_data[$v_contact_file['create_user']]['last_name']; ?><br/><?php echo date('d.m.Y', strtotime($v_contact_file['create_date'])); ?></a></td>
        					<td style="width:40%"><a href="<?php echo APP_BASE . 'stats/patientfileupload?doc_id='.$v_contact_file['id'].'&id='.$_REQUEST['id'];?>"><?php echo $v_contact_file['title']; ?></a></td>
        					<td style="width:30%"><a href="<?php echo APP_BASE . 'stats/patientfileupload?doc_id='.$v_contact_file['id'].'&id='.$_REQUEST['id'];?>"><?php echo $v_contact_file['file_type']; ?></a></td>
        					</tr>
                		</tbody>
                	</table>
            	<?php $i++; endforeach; ?>		 		
     	   </div>		
         <?php endif;?>
                 	
		<?php endif;?>

    	<?php endforeach;?>
    	
    	
    	
    	
    	
    		
    	 <?php foreach($allowed_medication_types as $k=>$medication_type):?>
		<?php if($medication_type == "iscrisis"):?>
		
		<?php if(in_array($medication_type,$timed_scheduled_medications)):?>
        	<!-- NO TIME PERIOD  -->
        <?php elseif(!in_array($medication_type,$timed_scheduled_medications) && !in_array($medication_type,array('isschmerzpumpe','treatment_care','scheduled','ispumpe'))): ?>
        	
        	<div class="mk-container">
        	
        	<!-- top -->
        	<div class="mk-top">
        		<h2><?php echo $this->translate('noch nicht eingepflegte Änderungen');?> </h2>
        	</div>
        	<!-- // top -->
        	
        		<table class="medikation" cellspacing="0" cellpadding="0" border="0">
        		<?php if($medication_type == "iscrisis"  || $medication_type == "isbedarfs" || $medication_type == "actual"):?><!-- TODO-3247 Carmen 03.07.2020 -->
        	    <?php 
        	       $colspan_table = 7; // change colspan according to blocks
        		?>
        		<thead>
        			<tr>
        				<th rowspan="2" colspan="2" class="name">NAME / <span>WIRKSTOFF</span></th>
        				<th colspan="" class="dosierung">DOSIERUNG / <span>INTERVALL</span></th>
        				<th rowspan="2">INDIKATION / KOMMENTAR</th>
        				<th rowspan="2" >ESKALATION</span></th>
        				<th rowspan="2" >LETZTE ÄNDERUNG</th>
        			</tr>
        		</thead>
        		<?php else:?>
        	    <?php 
        	       $colspan_table = 6; // change colspan according to blocks
        		?>
        		<thead>
        			<tr>
        				<th rowspan="2" colspan="2" class="name">NAME / <span>WIRKSTOFF</span></th>
        				<th colspan="" class="dosierung">DOSIERUNG</th>
        				<th rowspan="2">INDIKATION / KOMMENTAR</th>
        				<th rowspan="2" colspan="2">LETZTE ÄNDERUNG</th>
        			</tr>
        		</thead>
        		<?php endif;?>
        		<tbody>
        		<?php foreach($medication_array[$medication_type] as $k =>$med):?>
        		
        		    <?php
        		    $has_ack_class="";
        
        		    if(($this->acknowledge  == "1" && !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :
            		    $has_ack_class = "has_ack";
                    endif; 
                    ?>
        		    <?php 
        		    $data_medid= "";  
        			if(($this->acknowledge  == "1" && !empty($med['on_hold_changes'][$med['id']])) || ($this->ModulePrivileges[155] == true && !empty($med['on_hold_changes_offline'][$med['id']]))) :
                        $data_medid ='data-medid="'. $med['id'].'"' ;  
        			endif; 
                    ?> 
                    
                    <!--  Check if the medication line - needs multiple rows  -->
                    <?php $row_type_nt = "double";?>
                    <?php $row_span_nt = ' rowspan="2"';?>
                    
                    <?php if(empty($med['drug']) && empty($med['dosage_interval'])):?>
                        <?php $row_type_nt = " single";?>
                        <?php $row_span_nt = '';?>    
                    <?php endif;?>
                    <!-- end check -->
                    
                      
        			
        <!--  ##############- ONLINE -########################## --> 			
        		<?php if(  ! empty($med['on_hold_changes'][$med['id']] )) : ?>
        			<?php 
        			
        			    $online_on_hold_changes = array();
        			    $online_on_hold_changes = $med['on_hold_changes'][$med['id']]; 
        				$ack_referance_txt = array();
                        $ack_referance_del = array();
                        $ack_referance_txt[$med['id']]="";
        				$ack_referance_del[$med['id']] = "";
        
        				  if($med['on_hold_changes'][$med['id']]['status'] == "delete")
        				  {
        					 $ack_referance_txt[$med['id']] = '<span class="blue_text">'.$this->translate("Unapproved changes: ").'</span>';
        					 $ack_referance_del[$med['id']] = '<span class="red_text">'.$this->translate("Delete medication: ").'</span>'; 
        				  } 
        				  else if($med['on_hold_changes'][$med['id']]['status'] == "new")
        				  {
        					 $ack_referance_txt[$med['id']] = '<span class="green_text">'.$this->translate("Unapproved newly added medication: ").'</span>'; 
        					 $ack_referance_del[$med['id']] = ''; 
        				  } 
        				  else
        				  {
        					 $ack_referance_txt[$med['id']] = '<span class="blue_text">'.$this->translate("Unapproved changes: ").'</span>'; 
        					 $ack_referance_del[$med['id']] = ''; 
        				  }
                       
         		 
        				if($this->approval_rights == "1")
        				{
        					$app_rights = '<button class="med_approve_rights approvem" data-action="approve" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Approve").'</button><button class="med_approve_rights denym"   data-action="decline" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Decline").'</button>';
        					$approve = '<button class="med_approve_rights approvem" data-action="approve" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Approve").'</button>';
        					$deny = '<button class="med_approve_rights denym"   data-action="decline" data-recordid="'.$med['id'].'" data-alt_id="'.$med['on_hold_changes'][$med['id']]['alt_id'].'">'.$this->translate("Decline").'</button>';
        	 			} 
        				else
        				{
        					$app_rights = '';
        					$approve = '';
        					$deny = '';
        				}
         		?>
         
        		  <tr class="double extedned_ack  ack_medication_row_<?php echo $med['id']?> " >
        		  
        		        <!-- TD:Sort -->  
        				<td class="sortnum" rowspan="2"> </td>
        				
        				<!-- TD: Name -->
        				<td class="name">
        				    <?php echo $ack_referance_txt[$med['id']];?><br/><br/>
        				    <?php echo $online_on_hold_changes['name'];?>
        				</td>
        				<!-- TD: Dosage -->
        				<td class="dosierung" rowspan="2">
        				    <?php echo $online_on_hold_changes['dosage'];?> 
        				    <?php if ($this->show_new_fileds == "1" && strlen($online_on_hold_changes['dosage']) > 0):?><?php echo $online_on_hold_changes['unit'];?><?php endif;?>
        				</td>
        				
        				<!-- TD: Indication -->
        				<td class="ind-comm" rowspan="2">
            				<?php if(!empty($online_on_hold_changes['indication'])):?>
                				<?php if(strlen($online_on_hold_changes['indication_color']) > 0):?>
                					<div class="indikation" style="color:#<?php echo $online_on_hold_changes['indication_color'];?>"><span class="circle" style="background:#<?php echo $online_on_hold_changes['indication_color'];?>"></span><?php echo $online_on_hold_changes['indication'];?> </div>
                					<?php else:?>
                					<div class="indikation" style="color:#000000"><span class="circle" style="background:#000000"></span><?php echo $online_on_hold_changes['indication'];?></div>
                				<?php endif;?>
            				<?php endif;?>
        					<div class="comment extra_padding_left"  id="<?php echo $med['id'];?>_medi_comment"><?php echo $online_on_hold_changes['comments'];?></div>
        				</td>
        				
        				<!-- TD: Escalation -->
        				<?php if($medication_type == "iscrisis" || $medication_type == "isbedarfs" || $medication_type == 'actual'):?><!-- TODO-3247 Carmen 03.07.2020 -->
        				<td class="escalation" rowspan="2">
        					<div class="escalation"><?php echo $online_on_hold_changes['escalation'];?></div>
        				</td>
        				<?php endif;?>
        				
        				<!-- TD: Date -->
        				<td class="date" rowspan="2">
        					<div class="date-cont"><?php echo date('d.m.Y',strtotime($online_on_hold_changes['medication_change_date']));?></div>
        				</td>
        				
        				<!-- TD: Details -->
        				<td class="details ack_efa_expand_details" rowspan="2" data-efa_expand_details_id="<?php echo $med['id']?>"></td>
        			</tr>
        			
        			<tr class="double last extedned_ack">
        			    <!-- TD: Drug -->
        				<td class="name wirkstoff"><?php echo $online_on_hold_changes['drug'];?></td>
        			</tr>
        			
        			
        			<tr class="ack_medication_details_row_<?php echo $med['id']?> hide_details expandedItem extedned_ack" >
        			
        				<td colspan="<?php echo $colspan_table; ?>">
        					
        					<h3>APPLIKATIONSWEG, DARREICHUNGSFORM, EINHEIT, ETC</h3>
        					
        					<div class="ei-content">
        					
        						<ul class="item">
        							<li><span>Konzentration: </span><?php echo $online_on_hold_changes['concentration'];?></li>
        							<li><span>Einheit: </span><?php echo $online_on_hold_changes['unit'];?></li>
        						</ul>
        						
        						<ul class="item">
        							<li><span>Darreichungsform: </span><?php echo $online_on_hold_changes['dosage_form'];?></li>
        							<li><span>Applikationsweg: </span><?php echo $online_on_hold_changes['type'];?></li>
        						</ul>
        						
        						<?php if( ($medication_type=="actual" || $medication_type=="isivmed") && $allow_normal_scheduled == "1"):?>
            						<?php if($online_on_hold_changes['has_interval'] == "1"):?>
            						<ul class="item">
            							<li><span>Interval(Tage): </span><?php echo $online_on_hold_changes['days_interval'];?></li>
            							<?php  if( $online_on_hold_changes['administration_date'] != "0000-00-00 00:00:00"):?>
                							<li><span>Intervall zuletzt gestartet: </span>
                							 <?php echo date("d.m.Y",strtotime($online_on_hold_changes['administration_date']));?>
                							</li>
               							<?php endif; ?>
            						</ul>
            						<?php endif;?>
        						<?php endif;?>
        						
        						<ul class="item">
        		 				    <li><?php echo $approve; ?></li>
                                    <li><?php echo $deny; ?></li>
        						</ul>
        					</div>
        					
        				</td>
        				
        			</tr>
                    <?php  endif;?>
        <!--  ##############- ONLINE END -########################## -->
        		  <tr class="separator">
        				<td colspan="<?php echo $colspan_table?>"> </td>
        			</tr>
        		<?php endforeach;?>
        		</tbody>
        	</table>
        	</div>              
        <?php endif;?>
		<?php endif;?>
    	<?php endforeach;?>
    	
    	
    	
    	
    	
    	
    	
    	
    </div>

    
    <!--  ##################################################### -->
    <!--  #################- medipdf -######################### -->		
    <!--  ##################################################### -->
    <div id="tab-medipdf">
 	
	<form enctype="multipart/form-data"  action="<?php echo $this->act ?>" method="post" name="frmuser" id="frmuser" autocomplete="off" >
    	<div style="display: none;">
    		<img id="calImg" src="<?php echo RES_FILE_PATH; ?>/images/calendar.png" alt="Popup" class="trigger">
    	</div>
	    <div class="mk-container">
        	<div class="med_block_header dateien_verlauf_header mk-top mk-edit-title">
        		<h1 id="section_dateien_verlauf"><?php echo $this->translate('Medikations- Pläne (PDF)');?></h1>
        	</div>
        	<table id="dateien_verlauf_state" class="medication_edit_table medikation dateien_verlauf_edit_table">
        		<thead>
        	 		<tr>
        	 			<th>Nr. </th>
         				<th><?php echo $this->translate('title'); ?></th>
        	 			<th><?php echo $this->translate('filetype'); ?></th>
        	 			<th><?php echo $this->translate('user'); ?></th>
        	 			<th><?php echo $this->translate('date'); ?></th>
        	 		</tr>
        	 	</thead>
         		<tbody>
        			<?php $i = 1;
        			foreach ($contact_form_files as $k_contact_file => $v_contact_file): ?>
        				<?php if( $i % 2 == 0):  ?>
        			    	<tr>
        				<?php else : ?>
        					<tr style="background: #F3F3F3!important;">
        				<?php endif;  ?>
        					<td><a href="<?php echo APP_BASE . 'stats/patientfileupload?doc_id='.$v_contact_file['id'].'&id='.$_REQUEST['id'];?>"><?php echo $i; ?></a></td>
        					<td><a href="<?php echo APP_BASE . 'stats/patientfileupload?doc_id='.$v_contact_file['id'].'&id='.$_REQUEST['id'];?>"><?php echo $v_contact_file['title']; ?></a></td>
        					<td><a href="<?php echo APP_BASE . 'stats/patientfileupload?doc_id='.$v_contact_file['id'].'&id='.$_REQUEST['id'];?>"><?php echo $v_contact_file['file_type']; ?></a></td>
        					<td><a href="<?php echo APP_BASE . 'stats/patientfileupload?doc_id='.$v_contact_file['id'].'&id='.$_REQUEST['id'];?>"><?php echo $users_data[$v_contact_file['create_user']]['first_name'].', '.$users_data[$v_contact_file['create_user']]['last_name']; ?></a></td>
        					<td><a href="<?php echo APP_BASE . 'stats/patientfileupload?doc_id='.$v_contact_file['id'].'&id='.$_REQUEST['id'];?>"><?php echo date('d.m.Y', strtotime($v_contact_file['create_date'])); ?></a></td>
        				</tr>
        			<?php $i++; endforeach; ?>		 		
         		</tbody>
        	</table>

			<table width="100%" border="0" cellspacing="0" cellpadding="0">
				
				<tr>
					<td width="23" align="left" valign="top"><strong><?php echo $this->translate('uploadnewfile'); ?></strong></td>
				</tr>
				<tr>
					<td width="23" align="left" valign="top">&nbsp;</td>
				</tr>
				<tr>
					<td align="left" valign="top" class="pf_edit_cont">
						<div id="TableContentOuter" style="display:<?php echo $this->styleadd ?>">
							<input type="hidden" name="fileuploads" value="1" /> 
							<table width="35%" border="0" cellspacing="0" cellpadding="0">

								<tr>
									<!-- <td width="20% align="left" class="file_upload"><?php echo $this->translate('uploadfile_user_new') ?>*</td>
									 -->
									<td align="left" style="padding-bottom: 5px">
										<!-- ISPC-2642 Ancuta 10-11.08.2020 -->
										<?php if(isset($_REQUEST['file_id']) && !empty($_REQUEST['file_id']) && !empty($this->current_file_data)):?>
											<?php $current_file = $this->current_file_data; ?>
											<div class="qq_file_uploader_placeholder">
											<div class="  qq-uploader bigupload">
											    <ul class="qq-upload-list-selector qq-upload-list qq-upload-list-visible" aria-live="polite" aria-relevant="additions removals">
											    <li class="qq-file-id-0 qq-upload-success" qq-file-id="0">
											            <div class="qq-file-info">
											                <span class="infolabel">Dokument benennen:</span>
											                <div class="qq-file-name">
											                    <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-progress-bar-selector qq-progress-bar qq-hide"></div>
											                    <input type="text" class="qquuid_file_title qq-edit-filename-selector" id="edif_file_name" name="title" value="<?php echo $current_file['title'];?>" tabindex="0">
											                    <input type="hidden" name="post_action" value="update_file_data">
											                    <input type="hidden" name="file_id" value="<?php echo $current_file['id'];?>" tabindex="0">
											                    <input type="hidden" name="fileuploads" value="0" /> 
											                </div>
											            </div>
											        </li></ul>

											</div>		
											</div>		
                                        <? else: ?>
                                        <div id="qq_file_uploader_placeholder" class='qq_file_uploader_placeholder qq_file_uploader_multiple' data-parent='fieldset' data-action_name="upload_patient_files" data-tabname="0">
                                            <noscript>
                                                Please enable JavaScript to use file uploader.
                                            </noscript>
                                        </div>
                                        <? endif; ?>
                                        
                                   </td>
								</tr>
								
							</table>

							<div style="width: 100%;">
								<input type="hidden" name="active_version" id="active_version" value="0"/> <!-- ISPC - 2129 -->
								<input type="button" name="btnsubmit" id="btnsubmit-save" value="<?php echo $this->translate('submit') ?>" class="button btnSubmit2018" onclick="checkdischargednew('frmuser')">
							</div>
						</div>
					</td>
				</tr>
			</table>
 	   </div>	


</form>
</div>

	
<div id="edit_etamedication-dialog" style="width:450px; height: 300px; display:none;" title="">
	<form action="patientmedication/edit?id=<?php echo $_REQUEST['id']; ?>" name="med_edit" id="med_single_edit" method="post" >
		<input type="hidden"  name="efaoption" value="1" /> 
			<div id="medication_blocks">
	
	</div>
		
	</form>
</div>


<div class="medication_history">
	
	<div class="history_content" >
	
	</div>
</div>

<div id="MedicSet">
	<div class="sets_content" >
	
	</div>

</div>

<div class="medication_sets">
	
	<div class="medication_sets_content" >
	
	</div>
</div>
