<?php 
$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/views/overview/overview.box.21.js');

$box21 = $this->box21;

$head_script = <<<EOT
    var box_21_userid = {$this->logininfo['userid']};
EOT;

$this->headScript()->appendScript($head_script, $type = 'text/javascript', $attrs = array());


?>
<div style="overflow:hidden; width:100%">
    <table id="box_21_table" class="datatable wall_news" style="width:100%">
    
        <tbody>
        
    <?php foreach ($box21['wallnews'] as $row) :?>
    
            <tr>
                <td><?=$row['id']?></td>
                <td><?=$row['userid']?></td>
                <td><?=$row['user_nice_name']?></td>
                <td><?=$row['news_date']?></td>
                <td><?=$row['patient_nice_name']?></td>
                <td><?=$row['patient_id']?></td>
                <td><?=$row['news_content']?></td>      
            </tr>
    <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php 
echo $this->formButton('wallNews[button_add]', $this->translate('add_new_wallnews'), ['onClick' => 'add_new_wallnews();', 'class'=>'btnSubmit2018', 'style' => 'min-width:160px']);
?>
<!-- dialog to add new wallNews -->
<div id="box_21_dialog" style="display:none" class="dialog_wallnews">
    <form>
<?php
    echo $this->formHidden("wallNews[id]", null, ['id'=>null]);
    echo $this->translate('patient'). ": ";
    echo $this->formSelect("wallNews[patient]", null, ['id'=>null, 'class' => 'wallnews_patient_select'], $box21['users_patients']);
    echo $this->formTextarea("wallNews[content]", null, ['id'=>null , 'class'=>'elastic wallnews_content', 'rows' => 5]);
?>
    </form>
</div>
