<?php
// ISPC-2432 Ancuta 13.01.2020
// Maria:: Migration ISPC to CISPC 08.08.2020
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/page-css/connections/style.css');
$connection = $this->current_connection;
?>
<style>
 
.secondary_con_opt:hover {
	background: #f9f6ee;;
}
</style>




<br/>
<a href="<?php echo $this->url(array('controller'=>'connections' , 'action' => 'intenseconnectionslists')) ;?>"><?php echo $this->translate("back")?></a>
<br/>


<div class="nv-container">
	<h1><? echo $this->translate('Intense connection') ?></h1>
<form action="" method="post" name="save_survey" id="save_survey">
   <input type="hidden" name="connection_id" value="<?php echo $connection['connection_id']?>">
   <div class="err"><? echo $this->error_connected_clients ?></div>
	<div class="form-element">	
		<label><? echo $this->translate('Intense connection  client#1') ?></label>
		<?php 
				echo $this->formSelect(
					"parent", 
					$connection['parent'], 
					array(
						"class" => "todo_selectbox clientsarray",
					    "style"=>'width:100%;',
						"multiple" => false,
						"size" => 1,
						"disable" => array("0")
					),
					$this->clientsarray
				);
            ?>	
	</div>
  	<div class="err"><? echo $this->error_parent ?></div>
  	
    	
	<div class="form-element">	
		<label><? echo $this->translate('Intense connection  client#2') ?></label>
		<?php 
				echo $this->formSelect(
					"child", 
					$connection['child'], 
					array(
						"class" => "todo_selectbox clientsarray",
					    "style"=>'width:100%;',
						"multiple" => false,
						"size" => 1,
						"disable" => array("0")
					),
					$this->clientsarray
				);
            ?>	
	</div>
  	<div class="err"><? echo $this->error_child ?></div>
			
  	
    	
			
			
	<div class="form-element">	
		<label><? echo $this->translate('Intense connection  options') ?></label>
		<div class="err"><? echo $this->error_connection_options_err ?></div>
		<ul class="conn_options">
		<?php foreach($this->intense_options as $opt_id=>$opt_value):?>
		
    			<li class="main_con_opt">
        			<label><b><?php echo $this->translate($opt_id)?></b></label>
    			</li>
       			<li>
           			<ul class="con_option_sub">
        			<?php foreach($opt_value as $sub_option_id=>$bdata):?>
        			<?php 
        			$ckec = "";
        			if(in_array($sub_option_id,$connection['connection_options'][$opt_id])){
            			$ckec = 'checked="checked"';
        			    
        			}
        			?>
            			<li class="secondary_con_opt">
                			<input type="checkbox" name="connection_options[<?php echo $opt_id?>][]" value="<?php echo $sub_option_id;?>"  <?php echo $ckec;?>/>
                			<label><?php echo $bdata['form_name'].$bdata['option_name'];?></label>
           					<div class="err"><? echo $this->error_connection_options[$opt_id][$sub_option_id] ?></div>
            			</li>
            		<?php endforeach; ?>
           			</ul>
      			</li>
		
    		  
    		
		<?php endforeach; ?>
		</ul>
	</div>
  	<div class="err"><? echo $this->error_survey_clients ?></div>
				
			
			
			
	<input type="submit" name="btnsubmit" id="btnsubmit" class="btnNSsubmit"  tabindex="3" value="<? echo $this->translate('in_conn_save') ?>">
	
	</form>
</div>



