<!-- ISPC-2612 Ancuta 25.06.2020 -->
<?php
// Maria:: Migration ISPC to CISPC 08.08.2020
$connection_data = $this->connection_data;


$current_connection = $this->current_connection;

$clients = $this->clients;
?>
<?php if($current_connection['list_category']): ?>
<a href="<?php  echo APP_BASE ?>connections/listconnections?type=<?php echo  $current_connection['list_type'];?>&category=<?php echo  $current_connection['list_category'];?>"><?php echo $this->translate("back")?></a>
<?php else: ?>
<a href="<?php  echo APP_BASE ?>connections/listconnections?type=<?php echo  $current_connection['list_type'];?>"><?php echo $this->translate("back")?></a>
<?php endif;?>
<style>
.cl_rows:hover {
	background: #f7de13;
}
</style>

<form action="" method="post" name="frmuser" id="connection_settings" >
<table class="datatable">
	<tr>
		<th style="width: 30%"><?php echo $this->translate('connection_type')?></th>
		<td>
			<b><?php echo $current_connection['menu_name'];?></b>
			<input type="hidden" name="list_type" value="<?php echo $current_connection['list_type'];?>" />
			<input type="hidden" name="list_category" value="<?php echo $current_connection['list_category'];?>" />
			<input type="hidden" name="connection_id" value="<?php echo $current_connection['id'];?>" />
		</td>
	</tr>
	<tr>
		<th><?php echo $this->translate('connection_leading_client')?></th>
		<td>
			<?php echo $current_connection['parent_name'];?>
		</td>
	</tr>
	<tr>
		<th><?php echo $this->translate('connection_followers')?></th>
		<td>
			<?php echo $current_connection['kids_name'];?>
		</td>
	</tr>
		
</table>

<table class="datatable">
	<tr>
		<th><?php echo $this->translate('nr');?></th>	
		<th><?php echo $this->translate('client_name');?></th>	
		<th><?php echo $this->translate('connection_leading_client')?>
		<div class="error_S" style="color: red"> <? echo $this->error_clientid ?></div>
		</th>	
		<th><?php echo $this->translate('connection_followers')?>
		<div class="error_S" style="color: red"> <? echo $this->error_ConnectionFollowersClients ?></div>
		<div class="error_S" style="color: red"> <? echo $this->error_ConnectionFollowersClientsParent ?></div>
		</th>	
	</tr>
	<?php foreach($clients as $cl_id =>$client_data):?>
		<tr class="cl_rows">
			<td></td>
			<td><?php echo $client_data['client_name']?></td>
			<td>
    			<?php
    			if(isset($current_connection['clientid']) && $current_connection['clientid'] == $client_data['id'])
        			{
        			    $parent_selected = 'checked="checked"';
        			}
        			else
        			{
        			    $parent_selected = '';
        			}
    			?>
    			<input type="radio" name="clientid"   value="<?php echo $client_data['id']; ?>" class="parent_clients" <?php echo $parent_selected; ?>/>
			</td>
			
			<td>
			<?php 
			if(!empty($current_connection['ConnectionFollowersClients']) &&  in_array($client_data['id'],$current_connection['ConnectionFollowersClients']) )
			{
			    $conntected_selected = 'checked="checked"';
			}
			else
			{
			    $conntected_selected = '';
			}
			?>
			<input type="checkbox" name="ConnectionFollowersClients[]"  value="<?php echo $client_data['id']; ?>" <?php echo $conntected_selected; ?>/>
			</td>
		</tr>
	<?php endforeach;?>
	<tr>
		<td  colspan="4"><input type="submit" name="add_btn" id="add_btn" class="button" style="float:right; margin: 0 0 0 10px;" value="<?php echo $this->translate('save'); ?>"></td>
	</tr>
</table>

</form>