<!-- Maria:: Migration ISPC to CISPC 08.08.2020 -->
<!-- ISPC-2612 Ancuta 25.06.2020 -->
<?php
$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/data_tables/jquery.dataTables.js?'.date('Ymd'));
$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/data_tables/dataTables.jqueryui.js?'.date('Ymd'));
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/data_tables/dataTables.jqueryui.css?' . date('Ymd'));
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/page-css/listscommon.css?' . date('Ymd'));
?>
<style>
.even:hover {
	background: #f7de13;
}
.odd:hover {
	background: #f7de13;
}
</style>
<h1><? echo $this->translate('List Intense connections clients') ?></h1>
<br/>
<div style="clear:both;"></div>


<div class="add_link">
	<a href="<?php  echo APP_BASE ?>connections/addintenseconnection"><? echo $this->translate('addarticle'); ?></a>
</div>


<table id="table_conn_lists" >
 	<thead>
 		<tr>
 			<th><?php echo $this->translate('intense_connection_nr');?></th>
 			<th><?php echo $this->translate('intense_connection_date'); ?></th>
 			<th><?php echo $this->translate('intense_connection_parent'); ?></th>
 			<th><?php echo $this->translate('intense_connection_child'); ?></th>
 			<th><?php echo $this->translate('intense_connection_edit'); ?></th>
 		</tr>
 	</thead>
 		<?php $nr=1;?>
 		<?php foreach($this->lists as $k => $list):?>
     		<tr>
     			<td><?php echo $this->translate('ConnectionGroup#').$list['id'];?></td>
     			<td><?php echo $list['date'];?></td>
     			<td><?php echo $list['parent'];?></td>
     			<td><?php echo $list['child'];?></td>
     			<td>
         			<a href="<?php  echo APP_BASE ?>connections/addintenseconnection?connection_id=<?php echo  $list[id]?>"><img border="0" src="<?php  echo RES_FILE_PATH;?>/images/edit.png" /> </a>
     			</td>
     		</tr>
 		
 		<?php $nr++;?>
 		<?php endforeach;?>
 </table>	
 
 
 