<!-- ISPC-2612 Ancuta 25.06.2020 -->
<!-- Maria:: Migration ISPC to CISPC 08.08.2020 -->
<?php
$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/data_tables/jquery.dataTables.js?'.date('Ymd'));
$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/data_tables/dataTables.jqueryui.js?'.date('Ymd'));
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/data_tables/dataTables.jqueryui.css?' . date('Ymd'));
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/page-css/listscommon.css?' . date('Ymd'));
?>
<style>
.even:hover {
	background: #f7de13;
}
.odd:hover {
	background: #f7de13;
}
</style>
<h1><? echo $this->translate('Connections lists') ?></h1>
<br/>
<div style="clear:both;"></div>
<table id="table_conn_lists" >
 	<thead>
 		<tr>
 			<th><?php echo $this->translate('menu_name');?></th>
 			<th><?php echo $this->translate('actions'); ?></th>
<!--  			
 			<th><?php echo $this->translate('model_name');?></th>
 			<th><?php echo $this->translate('indrop');?></th>
 			<th><?php echo $this->translate('has_connection_id');?></th>
 			<th><?php echo $this->translate('menu_link');?></th>
 -->
 		</tr>
 	</thead>
 		<?php $nr=1;?>
 		<?php foreach($this->lists as $list_model => $list):?>
     		<tr>
     			<td><?php echo !empty($list['menu_name']) ? $list['menu_name'] : 'NO MENUU '.$list_model;?></td>
     			<td>
         			<?php if($list_model == "Voluntaryworkers"): ?>
         			<a href="<?php  echo APP_BASE ?>client/assignvwclients"><img border="0" src="<?php  echo RES_FILE_PATH;?>/images/edit.png" /> </a>
         			<?php else: ?>
         			<a href="<?php  echo APP_BASE ?>connections/listconnections?type=<?php echo  $list_model?>"><img border="0" src="<?php  echo RES_FILE_PATH;?>/images/edit.png" /> </a>
         			<?php endif;?>
     			</td>
<!--      			
     			<td><?php echo $list_model; ?></td>
     			<td><?php echo  $list['list_ident_column'] ?></td>
     			<td><?php echo in_array('connection_id',$list['columns']) ? "has_connection_id" : "NO" ?></td>
     			<td><a href="<?php  echo APP_BASE ?><?php echo  $list['link']?>"><?php echo  $list['link']?> </a></td>
 -->
     		</tr>
 		
 		<?php $nr++;?>
 		<?php endforeach;?>
 </table>	
 
 
 