<!-- ISPC-2612 Ancuta 25.06.2020 -->
<?php
$connection_info = $this->connection_info;
$connection_data = $this->connection_data;
?>

<a href="<?php echo $this->url(array('controller'=>'connections' , 'action' => 'lists' )); ?>"><?php echo $this->translate("back")?></a>

<br/>
<br/>

<h1><?php echo $connection_info['menu_name']?></h1>
<br/>


<div class="add_link">
<?php if ( isset($connection_info['category']) ): ?>
	<a href="<?php  echo APP_BASE ?>connections/addlistconnection?type=<?php echo  $connection_info['type']?>&category=<?php echo  $connection_info['category']?>"><? echo $this->translate('addarticle'); ?></a>
<?php else: ?>
	<a href="<?php  echo APP_BASE ?>connections/addlistconnection?type=<?php echo  $connection_info['type']?>"><? echo $this->translate('addarticle'); ?></a>
<?php endif;?>	
</div>


<table class="datatable">
	<tr>
		<th>#</th>
		<th><?php  echo $this->translate('connection_list_parent')?></th>
		<th><?php  echo $this->translate('connection_list_kids')?></th>
		<th><?php  echo $this->translate('actions')?></th>
	</tr>
	<?php if(!empty($connection_data)):?>
	<?php $nr =1;?>
	<?php foreach ($connection_data as $con_id=>$con_data):?>
    	<tr>
    		<td><?php echo $nr?></td>
    		<td><?php  echo $con_data['parent'] ?></td>
    		<td><?php  echo $con_data['kids'] ?></td>
    		<td> 
    		<?php if ( isset($connection_info['category']) ): ?>
    		<a href="<?php  echo APP_BASE ?>connections/addlistconnection?type=<?php echo  $connection_info['type']?>&category=<?php echo  $connection_info['category']?>&connection_id=<?php echo $con_id;?>"><? echo $this->translate('edit connection'); ?></a>
    		<?php else: ?>
    		<a href="<?php  echo APP_BASE ?>connections/addlistconnection?type=<?php echo  $connection_info['type']?>&connection_id=<?php echo $con_id;?>"><? echo $this->translate('edit connection'); ?></a>
    		<?php endif;?>	
    		</td>
    	</tr>
	
	<?php $nr++;?>
	<?php endforeach;?>
	<?php else: ?>
	    	<tr>
    		<td colspan="4"><?php echo $this->translate('Keine data '.$connection_info['menu_name'])?></td>
    	</tr>
    <?php endif;?>
</table>


