<?php

$thisIconNumber = $k_sys_det = 1;

$thisIconNiceName = "Ehrenamtliche";

$patientMasterData = $this->{'patientMasterData'};

$system_icon_data = $patientMasterData['system_icon_data'];
$system_icon_details = $patientMasterData['system_icon_details'];
$patient_sys_icons = $patientMasterData['patient_sys_icons'];
$patient_icons_details = $patientMasterData['patient_icons_details'];
$custom_icon_details = $patientMasterData['custom_icon_details'];
$btm_perm = $patientMasterData['btm_perm'];
$has_btm_permission = $patientMasterData['has_btm_permission'];
$diagno_act_module = $patientMasterData['diagno_act_module'];
$death_date = $patientMasterData['death_date'];
$nr = $patientMasterData['nr'];
$show_debtor_number = $patientMasterData['show_debtor_number'];

$this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureStart();

// $this->headScript()->appendFile(RES_FILE_PATH . "/javascript/views/templates/iconsexpanded/{$thisIconNumber}.js");
?>
<!-- start placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<div class="tab-content iconexpandbar collapsed" id="content_sys_icon-<?php echo $k_sys_det; ?>">
<?php 
$workers = $system_icon_data[$k_sys_det]['master_workers_data'][$this->ipid];
$p_workers = $system_icon_data[$k_sys_det]['patient_workers_data'][$this->ipid];

foreach ($workers as $k => $workers_type) :  
?>
    <h1 class="blueHD"><?=($k == "active") ? $this->translate("active voluntaryworkers") : ($k == "old" ? $this->translate("inactive voluntaryworkers") : '')?></h1>
    
    <?php foreach($workers_type as $k_worker => $worker): ?>
    
        <ul class="defaultContainer">
    
            <li class="header">
            	<h3><?=$this->translate('Ehrenamtliche'); ?></h3>
            	<h4><?=($p_workers[$worker['id']]['start_date'] != '0000-00-00 00:00:00' ? date('d.m.Y', strtotime($p_workers[$worker['id']]['start_date'])) : date('d.m.Y', strtotime($p_workers[$worker['id']]['create_date'])));?> - <?=($p_workers[$worker['id']]['end_date'] != '0000-00-00 00:00:00' ? date('d.m.Y', strtotime($p_workers[$worker['id']]['end_date'])) : '');?></h4>
            </li>
            
            <?php if ( ! empty($worker['first_name'])) : ?>
            <li class="elmnt">
            	<div class="fname"><?=$this->translate('firstname')?></div>
            	<div class="fval"><?=$this->escape($worker['first_name']); ?></div>
            </li>   
            <?php endif;?>
            <?php if ( ! empty($worker['last_name'])) : ?>
            <li class="elmnt">
            	<div class="fname"><?=$this->translate('lastname')?></div>
            	<div class="fval"><?=$this->escape($worker['last_name']); ?></div>
            </li>   
            <?php endif;?>
            <?php if ( ! empty($worker['salutation'])) : ?>
            <li class="elmnt">
            	<div class="fname"><?=$this->translate('salutation')?></div>
            	<div class="fval"><?=$this->escape($worker['salutation']); ?></div>
            </li>   
            <?php endif;?>
            <?php if ( ! empty($worker['street'])) : ?>
            <li class="elmnt">
            	<div class="fname"><?=$this->translate('address')?></div>
            	<div class="fval"><?=$this->escape($worker['street']); ?></div>
            </li>   
            <?php endif;?>
            <?php if ( ! empty($worker['zip'])) : ?>
            <li class="elmnt">
            	<div class="fname"><?=$this->translate('zip')?></div>
            	<div class="fval"><?=$this->escape($worker['zip']); ?></div>
            </li>   
            <?php endif;?>
            <?php if ( ! empty($worker['city'])) : ?>
            <li class="elmnt">
            	<div class="fname"><?=$this->translate('city')?></div>
            	<div class="fval"><?=$this->escape($worker['city']); ?></div>
            </li>   
            <?php endif;?>
            <?php if ( ! empty($worker['phone'])) : ?>
            <li class="elmnt">
            	<div class="fname"><?=$this->translate('phone1')?></div>
            	<div class="fval"><?=$this->escape($worker['phone']); ?></div>
            </li>   
            <?php endif;?>
            <?php if ( ! empty($worker['mobile'])) : ?>
            <li class="elmnt">
            	<div class="fname"><?=$this->translate('mobile')?></div>
            	<div class="fval"><?=$this->escape($worker['mobile']); ?></div>
            </li>   
            <?php endif;?>
            <?php if ( ! empty($worker['email'])) : ?>
            <li class="elmnt">
            	<div class="fname"><?=$this->translate('email')?></div>
            	<div class="fval"><?=$this->escape($worker['email']); ?></div>
            </li>   
            <?php endif;?>
            <?php if ( ! empty($worker['pvw_comment'])) : ?>
            <li class="elmnt">
            	<div class="fname"><?=$this->translate('comment')?></div>
            	<div class="fval"><?=$this->escape($worker['pvw_comment']); ?></div>
            </li>   
            <?php endif;?>
            
        </ul>
        
        <?php endforeach; ?>
<?php endforeach; ?>
</div><!-- end placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<?php $this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureEnd() ?>