<?php

$thisIconNumber = $k_sys_det = 25;
$thisIconNiceName = "Family doctor icon";

$patientMasterData = $this->{'patientMasterData'};

$system_icon_data = $patientMasterData['system_icon_data'];
$system_icon_details = $patientMasterData['system_icon_details'];
$patient_sys_icons = $patientMasterData['patient_sys_icons'];
$patient_icons_details = $patientMasterData['patient_icons_details'];
$custom_icon_details = $patientMasterData['custom_icon_details'];
$btm_perm = $patientMasterData['btm_perm'];
$has_btm_permission = $patientMasterData['has_btm_permission'];
$diagno_act_module = $patientMasterData['diagno_act_module'];
$death_date = $patientMasterData['death_date'];
$nr = $patientMasterData['nr'];
$show_debtor_number = $patientMasterData['show_debtor_number'];

$this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureStart();

// $this->headScript()->appendFile(RES_FILE_PATH . "/javascript/views/templates/iconsexpanded/{$thisIconNumber}.js");
?>
<!-- start placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<div class="tab-content iconexpandbar collapsed" id="content_sys_icon-<?php echo $k_sys_det; ?>">
<?php 

$family_doc = $system_icon_data[$k_sys_det]['family_doc_data'][$this->ipid];

if( ! empty($family_doc['title'])) {
    $family_doc_name = $family_doc['title'] . ' ' . $family_doc['last_name'].', '.$family_doc['first_name'];
} else {
    $family_doc_name = $family_doc['last_name'].', '.$family_doc['first_name'];
} 
?>
    <ul class="defaultContainer">
    
        <li class="header">
        	<h3><?=$this->translate('familydoc'); ?></h3>
        	<h4><?=$this->escape($family_doc_name); ?></h4>
        </li>
        
        <?php if ( ! empty($family_doc['first_name'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('firstname')?></div>
        	<div class="fval"><?=$this->escape($family_doc['first_name']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($family_doc['last_name'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('lastname')?></div>
        	<div class="fval"><?=$this->escape($family_doc['last_name']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($family_doc['salutation'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('salutation')?></div>
        	<div class="fval"><?=$this->escape($family_doc['salutation']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($family_doc['street1'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('address')?></div>
        	<div class="fval"><?=$this->escape($family_doc['street1']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($family_doc['zip'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('zip')?></div>
        	<div class="fval"><?=$this->escape($family_doc['zip']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($family_doc['city'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('city')?></div>
        	<div class="fval"><?=$this->escape($family_doc['city']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($family_doc['phone_practice'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('phone1')?></div>
        	<div class="fval"><?=$this->escape($family_doc['phone_practice']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($family_doc['phone_private'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('Handy Nummer')?></div>
        	<div class="fval"><?=$this->escape($family_doc['phone_private']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($family_doc['fax'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('fax')?></div>
        	<div class="fval"><?=$this->escape($family_doc['fax']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($family_doc['email'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('email')?></div>
        	<div class="fval"><?=$this->escape($family_doc['email']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($family_doc['doctornumber'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('LANR')?></div>
        	<div class="fval"><?=$this->escape($family_doc['doctornumber']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($family_doc['doctor_bsnr'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('bsnr')?></div>
        	<div class="fval"><?=$this->escape($family_doc['doctor_bsnr']); ?></div>
        </li>   
        <?php endif;?>
        
        <?php if ( ! empty($family_doc['practice'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('practice')?></div>
        	<div class="fval"><?=$this->escape($family_doc['practice']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($family_doc['comments'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('comment')?></div>
        	<div class="fval"><?=$this->escape($family_doc['comments']); ?></div>
        </li>   
        <?php endif;?>
        
    </ul>
    

</div><!-- end placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<?php $this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureEnd() ?>