<?php

$thisIconNumber = $k_sys_det = 29;
$thisIconNiceName = "Specialists";

$patientMasterData = $this->{'patientMasterData'};

$system_icon_data = $patientMasterData['system_icon_data'];
$system_icon_details = $patientMasterData['system_icon_details'];
$patient_sys_icons = $patientMasterData['patient_sys_icons'];
$patient_icons_details = $patientMasterData['patient_icons_details'];
$custom_icon_details = $patientMasterData['custom_icon_details'];
$btm_perm = $patientMasterData['btm_perm'];
$has_btm_permission = $patientMasterData['has_btm_permission'];
$diagno_act_module = $patientMasterData['diagno_act_module'];
$death_date = $patientMasterData['death_date'];
$nr = $patientMasterData['nr'];
$show_debtor_number = $patientMasterData['show_debtor_number'];

$this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureStart();

// $this->headScript()->appendFile(RES_FILE_PATH . "/javascript/views/templates/iconsexpanded/{$thisIconNumber}.js");
?>
<!-- start placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<div class="tab-content iconexpandbar collapsed" id="content_sys_icon-<?php echo $k_sys_det; ?>">
<?php
    
$specialists = $system_icon_data[$k_sys_det]['master_specialists_data'][$this->ipid];
$p_specialists = $system_icon_data[$k_sys_det]['patient_specialists_data'][$this->ipid];

foreach($specialists as $k_specialists => $v_specialists): 

?>
    <ul class="defaultContainer">
    
        <li class="header">
        	<h3><?=$this->translate('specialist'); ?></h3>
        	<h4><?=$this->escape($v_specialists['practice']); ?></h4>
        </li>
        
        <?php if ( ! empty($v_specialists['medical_speciality_text'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('specialist_type')?></div>
        	<div class="fval"><?=$this->escape($v_specialists['medical_speciality_text']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($v_specialists['first_name'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('firstname')?></div>
        	<div class="fval"><?=$this->escape($v_specialists['first_name']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($v_specialists['last_name'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('lastname')?></div>
        	<div class="fval"><?=$this->escape($v_specialists['last_name']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($v_specialists['salutation'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('salutation')?></div>
        	<div class="fval"><?=$this->escape($v_specialists['salutation']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($v_specialists['street1'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('address')?></div>
        	<div class="fval"><?=$this->escape($v_specialists['street1']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($v_specialists['zip'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('zip')?></div>
        	<div class="fval"><?=$this->escape($v_specialists['zip']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($v_specialists['city'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('city')?></div>
        	<div class="fval"><?=$this->escape($v_specialists['city']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($v_specialists['phone_practice'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('phone1')?></div>
        	<div class="fval"><?=$this->escape($v_specialists['phone_practice']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($v_specialists['phone_private'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('Telefon privat')?></div>
        	<div class="fval"><?=$this->escape($v_specialists['phone_private']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($v_specialists['phone_cell'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('mobile')?></div>
        	<div class="fval"><?=$this->escape($v_specialists['phone_cell']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($v_specialists['fax'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('fax')?></div>
        	<div class="fval"><?=$this->escape($v_specialists['fax']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($v_specialists['email'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('email')?></div>
        	<div class="fval"><?=$this->escape($v_specialists['email']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($p_specialists[$k_specialists]['comment'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('comment')?></div>
        	<div class="fval"><?=$this->escape($p_specialists[$k_specialists]['comment']); ?></div>
        </li>   
        <?php endif;?>
        
    </ul>
            
            
<?php endforeach; ?>
</div><!-- end placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<?php $this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureEnd() ?>