<?php

$thisIconNumber = $k_sys_det = 31;
$thisIconNiceName = "Diagnosis icon";

$patientMasterData = $this->{'patientMasterData'};

$system_icon_data = $patientMasterData['system_icon_data'];
$system_icon_details = $patientMasterData['system_icon_details'];
$patient_sys_icons = $patientMasterData['patient_sys_icons'];
$patient_icons_details = $patientMasterData['patient_icons_details'];
$custom_icon_details = $patientMasterData['custom_icon_details'];
$btm_perm = $patientMasterData['btm_perm'];
$has_btm_permission = $patientMasterData['has_btm_permission'];
$diagno_act_module = $patientMasterData['diagno_act_module'];
$death_date = $patientMasterData['death_date'];
$nr = $patientMasterData['nr'];
$show_debtor_number = $patientMasterData['show_debtor_number'];

$this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureStart();

// $this->headScript()->appendFile(RES_FILE_PATH . "/javascript/views/templates/iconsexpanded/{$thisIconNumber}.js");
?>
<!-- start placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<div class="tab-content iconexpandbar collapsed" id="content_sys_icon-<?php echo $k_sys_det; ?>">
<?php

    $diagnosis_data = $system_icon_data[$k_sys_det]['diagnosis_data'][$this->ipid];
    ksort($diagnosis_data);
    
?>
    <ul class="defaultContainer">
    
        <li class="header whitebg">
        	<h2><?=$this->translate('Diagnosen'); ?></h2>
        </li>
        
    <?php 
    foreach ($diagnosis_data as $diagnosis_type => $diagnosis_details) : 
    ?>
        <li class="header">
        	<h2><?=$this->escape($diagnosis_type); ?></h2>
        </li>   
        
            <?php 
            foreach ($diagnosis_details as $k => $description): 
            ?>
            <li class="elmnt">
            	<div class="fval"><?=$this->escape($description); ?></div>
            </li>
            <?php endforeach; ?>
            
    <?php endforeach; ?>
    </ul>
</div><!-- end placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<?php $this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureEnd() ?>