<?php

$thisIconNumber = $k_sys_det = 34;
$thisIconNiceName = "Aphoteke";

$patientMasterData = $this->{'patientMasterData'};

$system_icon_data = $patientMasterData['system_icon_data'];
$system_icon_details = $patientMasterData['system_icon_details'];
$patient_sys_icons = $patientMasterData['patient_sys_icons'];
$patient_icons_details = $patientMasterData['patient_icons_details'];
$custom_icon_details = $patientMasterData['custom_icon_details'];
$btm_perm = $patientMasterData['btm_perm'];
$has_btm_permission = $patientMasterData['has_btm_permission'];
$diagno_act_module = $patientMasterData['diagno_act_module'];
$death_date = $patientMasterData['death_date'];
$nr = $patientMasterData['nr'];
$show_debtor_number = $patientMasterData['show_debtor_number'];

$this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureStart();

// $this->headScript()->appendFile(RES_FILE_PATH . "/javascript/views/templates/iconsexpanded/{$thisIconNumber}.js");
?>
<!-- start placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<div class="tab-content iconexpandbar collapsed" id="content_sys_icon-<?php echo $k_sys_det; ?>">
<?php

$aphoteke_data = $system_icon_data[$k_sys_det]['patient_pharmacy_data'][$this->ipid];

foreach($aphoteke_data as $k_pharmacy => $pharmacy): 

?>


    <ul class="defaultContainer">
    
        <li class="header">
        	<h3><?=$this->translate('pharmacy_icon'); ?></h3>
        	<h4><?=$this->escape($pharmacy['pharmacy']); ?></h4>
        </li>
        
        <?php if ( ! empty($pharmacy['first_name'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('firstname')?></div>
        	<div class="fval"><?=$this->escape($pharmacy['first_name']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($pharmacy['last_name'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('lastname')?></div>
        	<div class="fval"><?=$this->escape($pharmacy['last_name']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($pharmacy['salutation'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('salutation')?></div>
        	<div class="fval"><?=$this->escape($pharmacy['salutation']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($pharmacy['street1'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('address')?></div>
        	<div class="fval"><?=$this->escape($pharmacy['street1']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($pharmacy['zip'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('zip')?></div>
        	<div class="fval"><?=$this->escape($pharmacy['zip']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($pharmacy['city'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('city')?></div>
        	<div class="fval"><?=$this->escape($pharmacy['city']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($pharmacy['phone'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('phone1')?></div>
        	<div class="fval"><?=$this->escape($pharmacy['phone']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($pharmacy['fax'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('fax')?></div>
        	<div class="fval"><?=$this->escape($pharmacy['fax']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($pharmacy['email'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('email')?></div>
        	<div class="fval"><?=$this->escape($pharmacy['email']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($pharmacy['pharmacy_comment'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('comment')?></div>
        	<div class="fval"><?=$this->escape($pharmacy['pharmacy_comment']); ?></div>
        </li>   
        <?php endif;?>
        
    </ul>
    
<?php endforeach; ?>
</div>
<!-- end placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<?php $this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureEnd() ?>