<?php

$thisIconNumber = $k_sys_det = 35;
$thisIconNiceName = "Krankenkasse";

$patientMasterData = $this->{'patientMasterData'};

$system_icon_data = $patientMasterData['system_icon_data'];
$system_icon_details = $patientMasterData['system_icon_details'];
$patient_sys_icons = $patientMasterData['patient_sys_icons'];
$patient_icons_details = $patientMasterData['patient_icons_details'];
$custom_icon_details = $patientMasterData['custom_icon_details'];
$btm_perm = $patientMasterData['btm_perm'];
$has_btm_permission = $patientMasterData['has_btm_permission'];
$diagno_act_module = $patientMasterData['diagno_act_module'];
$death_date = $patientMasterData['death_date'];
$nr = $patientMasterData['nr'];
$show_debtor_number = $patientMasterData['show_debtor_number'];

$this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureStart();

// $this->headScript()->appendFile(RES_FILE_PATH . "/javascript/views/templates/iconsexpanded/{$thisIconNumber}.js");
?>
<!-- start placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<div class="tab-content iconexpandbar collapsed" id="content_sys_icon-<?php echo $k_sys_det; ?>">
<?php 

$hi_data = $system_icon_data[$k_sys_det]['patient_hi_data'][$this->ipid];

foreach ($hi_data as $k_hi => $healthinsurance): 

?>

    <ul class="defaultContainer">
    
        <li class="header">
        	<h3><?=$this->translate('healthinsurance_icon'); ?></h3>
        	<h4><?=$this->escape($healthinsurance['company_name']) . ($healthinsurance['privatepatient'] ==1 ? '<span style="color:#ff0000;">&nbsp;(Privat)</span>' : ''); ?></h4>
        </li>
                        
        <?php if ( ! empty($healthinsurance['ins_insurance_provider']) || ! empty($healthinsurance['company']['insurance_provider'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('insurance_provider_icon')?></div>
        	<div class="fval"><?=$this->escape(! empty($healthinsurance['ins_insurance_provider']) ? $healthinsurance['ins_insurance_provider'] : $healthinsurance['company']['insurance_provider']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($healthinsurance['ins_contactperson'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('contactperson')?></div>
        	<div class="fval"><?=$this->escape($healthinsurance['ins_contactperson']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($healthinsurance['ins_street']) || ! empty($healthinsurance['company']['street1'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('street')?></div>
        	<div class="fval"><?=$this->escape(! empty($healthinsurance['ins_street']) ? $healthinsurance['ins_street'] : $healthinsurance['company']['street1']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($healthinsurance['ins_zip']) || ! empty($healthinsurance['company']['zip'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('zip')?></div>
        	<div class="fval"><?=$this->escape(! empty($healthinsurance['ins_zip']) ? $healthinsurance['ins_zip'] : $healthinsurance['company']['zip']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($healthinsurance['ins_city']) || ! empty($healthinsurance['company']['city'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('city')?></div>
        	<div class="fval"><?=$this->escape(! empty($healthinsurance['ins_city']) ? $healthinsurance['ins_city'] : $healthinsurance['company']['city']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($healthinsurance['ins_phone']) || ! empty($healthinsurance['company']['phone'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('phone1')?></div>
        	<div class="fval"><?=$this->escape(! empty($healthinsurance['ins_phone']) ? $healthinsurance['ins_phone'] : $healthinsurance['company']['phone']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($healthinsurance['ins_phone2']) || ! empty($healthinsurance['company']['phone2'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('phone2')?></div>
        	<div class="fval"><?=$this->escape(! empty($healthinsurance['ins_phone2']) ? $healthinsurance['ins_phone2'] : $healthinsurance['company']['phone2']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($healthinsurance['ins_phonefax']) || ! empty($healthinsurance['company']['phonefax'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('phonefax')?></div>
        	<div class="fval"><?=$this->escape(! empty($healthinsurance['ins_phonefax']) ? $healthinsurance['ins_phonefax'] : $healthinsurance['company']['phonefax']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($healthinsurance['ins_email']) || ! empty($healthinsurance['company']['email'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('email')?></div>
        	<div class="fval"><?=$this->escape(! empty($healthinsurance['ins_email']) ? $healthinsurance['ins_email'] : $healthinsurance['company']['email']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($healthinsurance['kvk_no']) || ! empty($healthinsurance['company']['kvnumber'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('kassenno')?></div>
        	<div class="fval"><?=$this->escape(! empty($healthinsurance['kvk_no']) ? $healthinsurance['kvk_no'] : $healthinsurance['company']['kvnumber']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($healthinsurance['institutskennzeichen']) || ! empty($healthinsurance['company']['iknumber'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('Institutskennzeichen (IK) ')?></div>
        	<div class="fval"><?=$this->escape(! empty($healthinsurance['institutskennzeichen']) ? $healthinsurance['institutskennzeichen'] : $healthinsurance['company']['iknumber']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($healthinsurance['insurance_no'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('insuranceno')?></div>
        	<div class="fval"><?=$this->escape($healthinsurance['insurance_no']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($healthinsurance['insurance_status'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('insurancestatus')?></div>
        	<div class="fval"><?=$this->escape($healthinsurance['insurance_status']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ($healthinsurance['rezeptgebuhrenbefreiung'] == '1') : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('gebuhrenbefreit')?></div>
        	<div class="fval"><?=$this->escape($this->translate('yes_radio'). ($healthinsurance['exemption_till_date'] != "" ? "(bis: ".$healthinsurance['exemption_till_date'].")" : "")); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( $healthinsurance['rezeptgebuhrenbefreiung'] == '2' ) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('gebuhrenpflichtig')?></div>
        	<div class="fval"><?=$this->translate('yes_radio')?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($healthinsurance['private_contribution'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('validcontribution')?></div>
        	<div class="fval"><?=$this->escape($healthinsurance['private_contribution'])?></div>
        </li>   
        <?php endif;?>
        
        <?php 
        if ($show_debtor_number == 1 
            && ( ! empty($healthinsurance['ins_debtor_number']) 
                || ! empty($healthinsurance['company']['debtor_number']))
            ) :
        ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('debtor_number')?></div>
        	<div class="fval"><?=$this->escape(! empty($healthinsurance['ins_debtor_number']) ? $healthinsurance['ins_debtor_number'] : $healthinsurance['company']['debtor_number']); ?></div>
        </li>   
        <?php endif;?>
        
        <?php if ( ! empty($healthinsurance['comment']) || ! empty($healthinsurance['company']['comments'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('comment')?></div>
        	<div class="fval"><?=$this->escape(! empty($healthinsurance['comment']) ? $healthinsurance['comment'] : $healthinsurance['company']['comments']); ?></div>
        </li>   
        <?php endif;?>
        
    </ul>


<?php endforeach; ?>

</div><!-- end placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<?php $this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureEnd() ?>