<?php

$thisIconNumber = $k_sys_det = 36;
$thisIconNiceName = "Versorger";

$patientMasterData = $this->{'patientMasterData'};

$system_icon_data = $patientMasterData['system_icon_data'];
$system_icon_details = $patientMasterData['system_icon_details'];
$patient_sys_icons = $patientMasterData['patient_sys_icons'];
$patient_icons_details = $patientMasterData['patient_icons_details'];
$custom_icon_details = $patientMasterData['custom_icon_details'];
$btm_perm = $patientMasterData['btm_perm'];
$has_btm_permission = $patientMasterData['has_btm_permission'];
$diagno_act_module = $patientMasterData['diagno_act_module'];
$death_date = $patientMasterData['death_date'];
$nr = $patientMasterData['nr'];
$show_debtor_number = $patientMasterData['show_debtor_number'];

$this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureStart();

// $this->headScript()->appendFile(RES_FILE_PATH . "/javascript/views/templates/iconsexpanded/{$thisIconNumber}.js");
?>
<!-- start placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<div class="tab-content iconexpandbar collapsed" id="content_sys_icon-<?php echo $k_sys_det; ?>">
<?php 

$suppliers = $system_icon_data[$k_sys_det]['patient_supplyer_data'][$this->ipid];

foreach ($suppliers as $k_suppliers => $v_suppliers) : 

?>
    <ul class="defaultContainer">
    
        <li class="header">
        	<h3><?=$this->translate('suppliers'); ?></h3>
        	<h4><?=$this->escape($v_suppliers['supplier']); ?></h4>
        </li>        
        
        <?php if ( ! empty($v_suppliers['type'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('supplier_type')?></div>
        	<div class="fval"><?=$this->escape($v_suppliers['type']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($v_suppliers['first_name'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('firstname')?></div>
        	<div class="fval"><?=$this->escape($v_suppliers['first_name']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($v_suppliers['last_name'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('lastname')?></div>
        	<div class="fval"><?=$this->escape($v_suppliers['last_name']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($v_suppliers['salutation'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('salutation')?></div>
        	<div class="fval"><?=$this->escape($v_suppliers['salutation']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($v_suppliers['street1'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('address')?></div>
        	<div class="fval"><?=$this->escape($v_suppliers['street1']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($v_suppliers['zip'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('zip')?></div>
        	<div class="fval"><?=$this->escape($v_suppliers['zip']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($v_suppliers['city'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('city')?></div>
        	<div class="fval"><?=$this->escape($v_suppliers['city']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($v_suppliers['phone'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('phone1')?></div>
        	<div class="fval"><?=$this->escape($v_suppliers['phone']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($v_suppliers['fax'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('fax')?></div>
        	<div class="fval"><?=$this->escape($v_suppliers['fax']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($v_suppliers['email'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('email')?></div>
        	<div class="fval"><?=$this->escape($v_suppliers['email']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($v_suppliers['supplier_comment'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('comment')?></div>
        	<div class="fval"><?=$this->escape($v_suppliers['supplier_comment']); ?></div>
        </li>   
        <?php endif;?>
        
    </ul>
    
<?php endforeach; ?>

</div><!-- end placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<?php $this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureEnd() ?>