<?php

$thisIconNumber = $k_sys_det = 38;
$thisIconNiceName = "Physiotherapist";

$patientMasterData = $this->{'patientMasterData'};

$system_icon_data = $patientMasterData['system_icon_data'];
$system_icon_details = $patientMasterData['system_icon_details'];
$patient_sys_icons = $patientMasterData['patient_sys_icons'];
$patient_icons_details = $patientMasterData['patient_icons_details'];
$custom_icon_details = $patientMasterData['custom_icon_details'];
$btm_perm = $patientMasterData['btm_perm'];
$has_btm_permission = $patientMasterData['has_btm_permission'];
$diagno_act_module = $patientMasterData['diagno_act_module'];
$death_date = $patientMasterData['death_date'];
$nr = $patientMasterData['nr'];
$show_debtor_number = $patientMasterData['show_debtor_number'];

$this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureStart();

// $this->headScript()->appendFile(RES_FILE_PATH . "/javascript/views/templates/iconsexpanded/{$thisIconNumber}.js");
?>
<!-- start placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<div class="tab-content iconexpandbar collapsed" id="content_sys_icon-<?php echo $k_sys_det; ?>">
<?php

$physiotherapist = $system_icon_data[$k_sys_det]['master_physio'][$this->ipid];
$p_physiotherapist = $system_icon_data[$k_sys_det]['patient_physio'][$this->ipid];
    
foreach ($physiotherapist as $k_physio => $physiotherapist) : 

?>

    <ul class="defaultContainer">
    
        <li class="header">
        	<h3><?=$this->translate('physio_icon'); ?></h3>
        	<h4><?=$this->escape($physiotherapist['physiotherapist']); ?></h4>
        </li>        
        
        <?php if ( ! empty($physiotherapist['type'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('supplier_type')?></div>
        	<div class="fval"><?=$this->escape($physiotherapist['type']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($physiotherapist['first_name'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('firstname')?></div>
        	<div class="fval"><?=$this->escape($physiotherapist['first_name']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($physiotherapist['last_name'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('lastname')?></div>
        	<div class="fval"><?=$this->escape($physiotherapist['last_name']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($physiotherapist['salutation'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('salutation')?></div>
        	<div class="fval"><?=$this->escape($physiotherapist['salutation']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($physiotherapist['street1'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('address')?></div>
        	<div class="fval"><?=$this->escape($physiotherapist['street1']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($physiotherapist['zip'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('zip')?></div>
        	<div class="fval"><?=$this->escape($physiotherapist['zip']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($physiotherapist['city'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('city')?></div>
        	<div class="fval"><?=$this->escape($physiotherapist['city']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($physiotherapist['phone_practice'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('phone1')?></div>
        	<div class="fval"><?=$this->escape($physiotherapist['phone_practice']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($physiotherapist['phone_emergency'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('emergency_phone')?></div>
        	<div class="fval"><?=$this->escape($physiotherapist['phone_emergency']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($physiotherapist['fax'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('fax')?></div>
        	<div class="fval"><?=$this->escape($physiotherapist['fax']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($physiotherapist['email'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('email')?></div>
        	<div class="fval"><?=$this->escape($physiotherapist['email']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($p_physiotherapist[$physiotherapist['id']]['physio_comment'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('comment')?></div>
        	<div class="fval"><?=$this->escape($p_physiotherapist[$physiotherapist['id']]['physio_comment']); ?></div>
        </li>   
        <?php endif;?>
        
    </ul>
    
<?php endforeach; ?>

</div><!-- end placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<?php $this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureEnd() ?>