<?php

$thisIconNumber = $k_sys_det = 39;
$thisIconNiceName = "Homecare";

$patientMasterData = $this->{'patientMasterData'};

$system_icon_data = $patientMasterData['system_icon_data'];
$system_icon_details = $patientMasterData['system_icon_details'];
$patient_sys_icons = $patientMasterData['patient_sys_icons'];
$patient_icons_details = $patientMasterData['patient_icons_details'];
$custom_icon_details = $patientMasterData['custom_icon_details'];
$btm_perm = $patientMasterData['btm_perm'];
$has_btm_permission = $patientMasterData['has_btm_permission'];
$diagno_act_module = $patientMasterData['diagno_act_module'];
$death_date = $patientMasterData['death_date'];
$nr = $patientMasterData['nr'];
$show_debtor_number = $patientMasterData['show_debtor_number'];

$this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureStart();

// $this->headScript()->appendFile(RES_FILE_PATH . "/javascript/views/templates/iconsexpanded/{$thisIconNumber}.js");
?>
<!-- start placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<div class="tab-content iconexpandbar collapsed" id="content_sys_icon-<?php echo $k_sys_det; ?>">
<?php
 
$homecare = $system_icon_data[$k_sys_det]['master_homes'][$this->ipid];
$p_homecare = $system_icon_data[$k_sys_det]['patient_homes'][$this->ipid];

foreach ($homecare as $k_home => $homecare) : 

?>

    <ul class="defaultContainer">
    
        <li class="header">
        	<h3><?=$this->translate('home_icon'); ?></h3>
        	<h4><?=$this->escape($homecare['homecare']); ?></h4>
        </li>        
        
        <?php if ( ! empty($homecare['type'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('supplier_type')?></div>
        	<div class="fval"><?=$this->escape($homecare['type']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($homecare['first_name'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('firstname')?></div>
        	<div class="fval"><?=$this->escape($homecare['first_name']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($homecare['last_name'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('lastname')?></div>
        	<div class="fval"><?=$this->escape($homecare['last_name']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($homecare['salutation'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('salutation')?></div>
        	<div class="fval"><?=$this->escape($homecare['salutation']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($homecare['street1'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('address')?></div>
        	<div class="fval"><?=$this->escape($homecare['street1']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($homecare['zip'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('zip')?></div>
        	<div class="fval"><?=$this->escape($homecare['zip']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($homecare['city'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('city')?></div>
        	<div class="fval"><?=$this->escape($homecare['city']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($homecare['phone_practice'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('phone1')?></div>
        	<div class="fval"><?=$this->escape($homecare['phone_practice']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($homecare['phone_emergency'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('emergency_phone')?></div>
        	<div class="fval"><?=$this->escape($homecare['phone_emergency']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($homecare['fax'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('fax')?></div>
        	<div class="fval"><?=$this->escape($homecare['fax']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($homecare['email'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('email')?></div>
        	<div class="fval"><?=$this->escape($homecare['email']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($p_homecare[$homecare['id']]['home_comment'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('comment')?></div>
        	<div class="fval"><?=$this->escape($p_homecare[$homecare['id']]['home_comment']); ?></div>
        </li>   
        <?php endif;?>
        
    </ul>            
            
<?php endforeach; ?>

</div><!-- end placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<?php $this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureEnd() ?>