<?php

$thisIconNumber = $k_sys_det = 4;
$thisIconNiceName = "Pflegedienst";

$patientMasterData = $this->{'patientMasterData'};

$system_icon_data = $patientMasterData['system_icon_data'];
$system_icon_details = $patientMasterData['system_icon_details'];
$patient_sys_icons = $patientMasterData['patient_sys_icons'];
$patient_icons_details = $patientMasterData['patient_icons_details'];
$custom_icon_details = $patientMasterData['custom_icon_details'];
$btm_perm = $patientMasterData['btm_perm'];
$has_btm_permission = $patientMasterData['has_btm_permission'];
$diagno_act_module = $patientMasterData['diagno_act_module'];
$death_date = $patientMasterData['death_date'];
$nr = $patientMasterData['nr'];
$show_debtor_number = $patientMasterData['show_debtor_number'];

$this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureStart();

// $this->headScript()->appendFile(RES_FILE_PATH . "/javascript/views/templates/iconsexpanded/{$thisIconNumber}.js");
?>
<!-- start placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<div class="tab-content iconexpandbar collapsed" id="content_sys_icon-<?php echo $k_sys_det; ?>">
<?php

$pflegedienstes = $system_icon_data[$k_sys_det]['master_pflege'][$this->ipid];
$p_pflegedienstes = $system_icon_data[$k_sys_det]['patient_pflege'][$this->ipid];

foreach($pflegedienstes as $k_pfleges => $pflegedienst) :

?>
    <ul class="defaultContainer">
        
        <li class="header">
        	<h3><?=$this->translate('nursing_icon'); ?></h3>
        	<h4><?=$this->escape($pflegedienst['nursing']); ?></h4>
        </li>
        
        <?php if (! empty($pflegedienst['first_name'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('firstname'); ?></div>
        	<div class="fval"><?=$this->escape($pflegedienst['first_name']); ?></div>
        </li>   
        <?php endif;?>
        <?php if (! empty($pflegedienst['last_name'])) : ?>     
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('lastname'); ?></div>
        	<div class="fval"><?=$this->escape($pflegedienst['last_name']); ?></div>
        </li>
        <?php endif;?>
        <?php if (! empty($pflegedienst['salutation'])) : ?>    
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('salutation'); ?></div>
        	<div class="fval"><?=$this->escape($pflegedienst['salutation']); ?></div>
        </li>
        <?php endif;?>
        <?php if (! empty($pflegedienst['street1'])) : ?>    
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('address'); ?></div>
        	<div class="fval"><?=$this->escape($pflegedienst['street1']); ?></div>
        </li>
        <?php endif;?>
        <?php if (! empty($pflegedienst['zip'])) : ?>    
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('zip'); ?></div>
        	<div class="fval"><?=$this->escape($pflegedienst['zip']); ?></div>
        </li>
        <?php endif;?>
        <?php if (! empty($pflegedienst['city'])) : ?>    
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('city'); ?></div>
        	<div class="fval"><?=$this->escape($pflegedienst['city']); ?></div>
        </li>
        <?php endif;?>
        <?php if (! empty($pflegedienst['phone_practice'])) : ?>    
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('phone1'); ?></div>
        	<div class="fval"><?=$this->escape($pflegedienst['phone_practice']); ?></div>
        </li>
        <?php endif;?>
        <?php if (! empty($pflegedienst['phone_emergency'])) : ?>    
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('emergency_phone'); ?></div>
        	<div class="fval"><?=$this->escape($pflegedienst['phone_emergency']); ?></div>
        </li>
        <?php endif;?>
        <?php if (! empty($pflegedienst['fax'])) : ?>    
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('fax'); ?></div>
        	<div class="fval"><?=$this->escape( $pflegedienst['fax']); ?></div>
        </li>
        <?php endif;?>
        <?php if (! empty($pflegedienst['email'])) : ?>    
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('email'); ?></div>
        	<div class="fval"><?=$this->escape( $pflegedienst['email']); ?></div>
        </li>
        <?php endif;?>
        <?php if (! empty($p_pflegedienstes[$pflegedienst['id']]['pflege_comment'])) : ?>                        
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('comment'); ?></div>
        	<div class="fval"><?=$this->escape( $p_pflegedienstes[$pflegedienst['id']]['pflege_comment']); ?></div>
        </li>
        <?php endif;?>
        
    </ul>
            
<?php endforeach; ?>
</div><!-- end placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<?php $this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureEnd() ?>