<?php

$thisIconNumber = $k_sys_det = 40;
$thisIconNiceName = "patient_location_users";

$patientMasterData = $this->{'patientMasterData'};

$system_icon_data = $patientMasterData['system_icon_data'];
$system_icon_details = $patientMasterData['system_icon_details'];
$patient_sys_icons = $patientMasterData['patient_sys_icons'];
$patient_icons_details = $patientMasterData['patient_icons_details'];
$custom_icon_details = $patientMasterData['custom_icon_details'];
$btm_perm = $patientMasterData['btm_perm'];
$has_btm_permission = $patientMasterData['has_btm_permission'];
$diagno_act_module = $patientMasterData['diagno_act_module'];
$death_date = $patientMasterData['death_date'];
$nr = $patientMasterData['nr'];
$show_debtor_number = $patientMasterData['show_debtor_number'];

$this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureStart();

// $this->headScript()->appendFile(RES_FILE_PATH . "/javascript/views/templates/iconsexpanded/{$thisIconNumber}.js");
?>
<!-- start placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<div class="tab-content iconexpandbar collapsed" id="content_sys_icon-<?php echo $k_sys_det; ?>">
<?php 

$location_users = $system_icon_data[$k_sys_det]['patient_location_users'][$this->ipid];

?>

    <ul class="defaultContainer">
        <li class="header">
        	<h3><?=$this->translate('location_users_icon'); ?></h3>
    	</li>
        	
    	<?php 
    	foreach ($location_users as $k_user => $users_data) : 
    	?>
            <li class="elmnt">
                <div class="fname"><?=( ! empty($users_data['user_title']) ? $this->escape($users_data['user_title']) : "")?> <?=( ! empty($users_data['last_name']) ? $this->escape($users_data['last_name']) : "")?> <?=( ! empty($users_data['first_name']) ? $this->escape($users_data['first_name']) : "")?></div>
                <?php if ( ! empty($users_data['phone'])) :?>
                <div class="fval"><?=$this->translate('phone1');?> <?=$this->escape($users_data['phone']); ?></div>
                <?php endif; ?>
                <?php if ( ! empty($users_data['mobile'])) :?>
                <div class="fval"><?=$this->translate('phone2');?> <?=$this->escape($users_data['mobile']); ?></div>
                <?php endif; ?>
            </li>
    	<?php endforeach; ?>
	</ul>

</div><!-- end placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<?php $this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureEnd() ?>