<?php

$thisIconNumber = $k_sys_det = 48;
$thisIconNiceName = "Medication_treatment_care_BP";

$patientMasterData = $this->{'patientMasterData'};

$system_icon_data = $patientMasterData['system_icon_data'];
$system_icon_details = $patientMasterData['system_icon_details'];
$patient_sys_icons = $patientMasterData['patient_sys_icons'];
$patient_icons_details = $patientMasterData['patient_icons_details'];
$custom_icon_details = $patientMasterData['custom_icon_details'];
$btm_perm = $patientMasterData['btm_perm'];
$has_btm_permission = $patientMasterData['has_btm_permission'];
$diagno_act_module = $patientMasterData['diagno_act_module'];
$death_date = $patientMasterData['death_date'];
$nr = $patientMasterData['nr'];
$show_debtor_number = $patientMasterData['show_debtor_number'];

$this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureStart();

// $this->headScript()->appendFile(RES_FILE_PATH . "/javascript/views/templates/iconsexpanded/{$thisIconNumber}.js");
?>
<!-- start placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<div class="tab-content iconexpandbar collapsed" id="content_sys_icon-<?php echo $k_sys_det; ?>">
<?php

$medication_data = $system_icon_data[$k_sys_det]['medication_data'][$this->ipid];

foreach ($medication_data as $medication_type => $medication_details) :

?>
    <ul class="defaultContainer">
        
        <li class="header">
        	<h3><?=$this->translate('medication_type_' . $medication_type);?> </h3>
        	<h4></h4>
        </li>        

        <?php 
        foreach($medication_details['medications'] as $k => $description) :
        ?>
            <li class="elmnt">
            
                <?php if ( ! empty($description)) : ?>
            	<div class="fval"><?=$this->escape($description); ?></div>
                <?php endif; ?>

                <?php if ( ! empty($medication_details['indications'][$k])) : ?>
                <div class="findikation" style="color:#<?=( ! empty($medication_details['indications'][$k]['color']) ? $medication_details['indications'][$k]['color'] : '3f3f3f')?>">
                    <span class="circle" style="background:#f72354"></span><?=$this->escape($medication_details['indications'][$k]['name']); ?>
                </div>
                <?php endif; ?>
                
            </li>
        <?php 
        endforeach; 
        ?>
        
    </ul>
    
<?php
endforeach;
?>

</div>
<!-- end placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<?php $this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureEnd() ?>