<?php

$thisIconNumber = $k_sys_det = 50;
$thisIconNiceName = "TourplanSettings";

$patientMasterData = $this->{'patientMasterData'};

$system_icon_data = $patientMasterData['system_icon_data'];
$system_icon_details = $patientMasterData['system_icon_details'];
$patient_sys_icons = $patientMasterData['patient_sys_icons'];
$patient_icons_details = $patientMasterData['patient_icons_details'];
$custom_icon_details = $patientMasterData['custom_icon_details'];
$btm_perm = $patientMasterData['btm_perm'];
$has_btm_permission = $patientMasterData['has_btm_permission'];
$diagno_act_module = $patientMasterData['diagno_act_module'];
$death_date = $patientMasterData['death_date'];
$nr = $patientMasterData['nr'];
$show_debtor_number = $patientMasterData['show_debtor_number'];

$this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureStart();

// $this->headScript()->appendFile(RES_FILE_PATH . "/javascript/views/templates/iconsexpanded/{$thisIconNumber}.js");
?>
<!-- start placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<div class="tab-content iconexpandbar collapsed" id="content_sys_icon-<?php echo $k_sys_det; ?>">
<?php

if (count($system_icon_data[$k_sys_det]['tourplan_settings'][$this->ipid]) > 0 ) :

    foreach( $system_icon_data[$k_sys_det]['tourplan_settings'][$this->ipid] as $id => $types ) :
        //there is a FATAL flaw in logix... is_disabled must be added after user...
        reset($types);
        $type = key($types);

        if (empty($system_icon_data[$k_sys_det]['tourplan_settings_users'][$type][$id])) continue;

?>

    <ul class="defaultContainer <?=(isset($types['is_disabled']) && $types['is_disabled']==1  ? "deleted_visit" : "" )?>" >
        
        <li class="header">
        	<h3><?=$type =='pseudogrups' ? $this->translate('userpseudo') : $this->translate('users');?> </h3>
        	<h4>
        	   <?=$this->escape($system_icon_data[$k_sys_det]['tourplan_settings_users'][$type][$id]); ?>
        	   <?php 
        	       if (isset($types['is_disabled']) && $types['is_disabled'] == 1) {
        	           echo "<br/>" . $this->translate("user_cantvisit_or_inactive_label");
        	       }
        	   ?>
        	</h4>
        </li>        
        
        <?php if ( ! empty($types[$type][1])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('Monday')?> : <?=$this->escape($types[$type][1]); ?></div>
        </li>
        <?php endif; ?>
        
        <?php if ( ! empty($types[$type][2])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('Tuesday')?> : <?=$this->escape($types[$type][2]); ?></div>
        </li>
        <?php endif; ?>
        
        <?php if ( ! empty($types[$type][3])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('Wednesday')?> : <?=$this->escape($types[$type][3]); ?></div>
        </li>
        <?php endif; ?>
        
        <?php if ( ! empty($types[$type][4])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('Thursday')?> : <?=$this->escape($types[$type][4]); ?></div>
        </li>
        <?php endif; ?>
        
        <?php if ( ! empty($types[$type][5])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('Friday')?> : <?=$this->escape($types[$type][5]); ?></div>
        </li>
        <?php endif; ?>
        
        <?php if ( ! empty($types[$type][6])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('Saturday')?> : <?=$this->escape($types[$type][6]); ?></div>
        </li>
        <?php endif; ?>
        
        <?php if ( ! empty($types[$type][7])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('Sunday')?> : <?=$this->escape($types[$type][7]); ?></div>
        </li>
        <?php endif; ?>
        
        
    </ul>
    
    
    
           
<?php 
    endforeach;
endif; 
?>
</div><!-- end placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<?php $this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureEnd() ?>