<?php

$thisIconNumber = $k_sys_det = 51;
$thisIconNiceName = "todo_data";

$patientMasterData = $this->{'patientMasterData'};

$system_icon_data = $patientMasterData['system_icon_data'];
$system_icon_details = $patientMasterData['system_icon_details'];
$patient_sys_icons = $patientMasterData['patient_sys_icons'];
$patient_icons_details = $patientMasterData['patient_icons_details'];
$custom_icon_details = $patientMasterData['custom_icon_details'];
$btm_perm = $patientMasterData['btm_perm'];
$has_btm_permission = $patientMasterData['has_btm_permission'];
$diagno_act_module = $patientMasterData['diagno_act_module'];
$death_date = $patientMasterData['death_date'];
$nr = $patientMasterData['nr'];
$show_debtor_number = $patientMasterData['show_debtor_number'];

$this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureStart();

$this->headScript()->appendFile(RES_FILE_PATH . "/javascript/views/templates/iconsexpanded/{$thisIconNumber}.js");
?>
<!-- start placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<div class="tab-content iconexpandbar collapsed" id="content_sys_icon-<?php echo $k_sys_det; ?>">
<?php

$todos = $system_icon_data[$k_sys_det]['todo_data'][$this->ipid];

foreach ($todos as $k_todo => $todo_data) :

?>

    <ul class="defaultContainer <?=($todo_data['iscompleted'] == 1 ? 'tcomplete' : 'tnotcomplete')?>"">
        <li class="header">
        	<h3><?=$this->translate('todos'); ?></h3>
        	<h4><?=$todo_data['todo']; ?></h4>
        </li>        
        
        <?php if ( ! empty($todo_data['user_name'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('assigneduser')?></div>
        	<div class="fval"><?=$this->escape($homecare['user_name']); ?></div>
        </li>
        <?php endif; ?>
        <?php if ( ! empty($todo_data['group_name'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('assignedgroup')?></div>
        	<div class="fval"><?=$this->escape($todo_data['group_name']); ?></div>
        </li>
        <?php endif; ?>
        <?php if ( ! empty($todo_data['until_date'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('untildate')?></div>
        	<div class="fval"><?=$this->escape($todo_data['until_date']); ?></div>
        </li>
        <?php endif; ?>
        <?php if ( ! empty($todo_data['complete_user'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('completeuser')?></div>
        	<div class="fval"><?=$this->escape($todo_data['complete_user']); ?></div>
        </li>
        <?php endif; ?>
        <?php if ( ! empty($todo_data['complete_date'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('completedate')?></div>
        	<div class="fval"><?=$this->escape($todo_data['complete_date']); ?></div>
        </li>
        <?php endif; ?>
        
        
        <?php if($todo_data['iscompleted'] != 1 && strpos($todo_data['triggered_by'], 'medacknowledge') === false) : ?>        
        <li class="elmnt marktodoasCompleted">
        	<div class="fval">
        	   <input type="checkbox" name="select_done" value="1" class="done_event" data-todo_nr="<?php echo  $todo_data['row_id']; ?>" id="done_event_<?php echo $todo_data['row_id']; ?>" rel="<?php echo $todo_data['row_id']; ?>" />
        	   <input type="hidden" name="todoids" value="<?php echo implode(',',$todo_data['ids']); ?>" id="todoids_<?php echo   $todo_data['row_id'];?>" />
        	   
        	   <label for="done_event_<?php echo $todo_data['row_id']; ?>"><?=$this->translate('Mark TODO as completed');?></label>
            </div>
        </li>
        <?php endif; ?>
        
        
    </ul>
           
<?php endforeach; ?>
</div><!-- end placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<?php $this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureEnd() ?>