<?php

$thisIconNumber = $k_sys_det = 52;
$thisIconNiceName = "scheduled_medication_data";

$patientMasterData = $this->{'patientMasterData'};

$system_icon_data = $patientMasterData['system_icon_data'];
$system_icon_details = $patientMasterData['system_icon_details'];
$patient_sys_icons = $patientMasterData['patient_sys_icons'];
$patient_icons_details = $patientMasterData['patient_icons_details'];
$custom_icon_details = $patientMasterData['custom_icon_details'];
$btm_perm = $patientMasterData['btm_perm'];
$has_btm_permission = $patientMasterData['has_btm_permission'];
$diagno_act_module = $patientMasterData['diagno_act_module'];
$death_date = $patientMasterData['death_date'];
$nr = $patientMasterData['nr'];
$show_debtor_number = $patientMasterData['show_debtor_number'];

$this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureStart();

$this->headScript()->appendFile(RES_FILE_PATH . "/javascript/views/templates/iconsexpanded/{$thisIconNumber}.js");
?>
<!-- start placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<div class="tab-content iconexpandbar collapsed" id="content_sys_icon-<?php echo $k_sys_det; ?>">
<?php

if (count($system_icon_data[$k_sys_det]['scheduled_medication_data'][$this->ipid] >0)) :
    
    foreach ($system_icon_data[$k_sys_det]['scheduled_medication_data'][$this->ipid] as $mid => $medication_details ) :
?>

    <ul class="defaultContainer" id="sch_<?=$mid;?>">

        <li class="elmnt">
        	
        	<div class="fname"><?=$this->escape($medication_details['medication_name']); ?></div>
        	
        	<?php if ( ! empty($medication_details['indications']['name'])) : ?>
            <div class="findikation" style="color:#<?=( ! empty($medication_details['indications']['color']) ? $medication_details['indications']['color'] : '3f3f3f')?>">
                <span class="circle" style="background:#<?=( ! empty($medication_details['indications']['color']) ? $medication_details['indications']['color'] : '3f3f3f')?>"></span>
                <?=$this->escape($medication_details['indications']['name'])?>
            </div>
            <?php endif; ?>
        </li>
        
        <?php if ( ! empty($medication_details['dosage'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('medication_dosage')?></div>
        	<div class="fval"><?=$this->escape($medication_details['dosage']); ?></div>
        </li>   
        <?php endif;?>
        
        <?php if ( ! empty($medication_details['comments'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('comments')?></div>
        	<div class="fval"><?=$this->escape($medication_details['comments']); ?></div>
        </li>   
        <?php endif;?>
        
        <?php if ( ! empty($medication_details['days_interval'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('medication_days_interval')?></div>
        	<div class="fval"><?=$this->escape($medication_details['days_interval']); ?></div>
        </li>   
        <?php endif;?>
        
        <?php if ( ! empty($medication_details['due_date'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('due_date')?></div>
        	<div class="fval" id="due_date_<?=$mid;?>"><?=date('d.m.Y', strtotime($medication_details['due_date'])); ?></div>
        </li>   
        <?php endif;?>
        
        
        <li class="elmnt">
        	
        	<div class="fname"><?=$this->translate('action')?></div>
        	
        	<div class="fval">
        	   
        	   <span id="due_date_<?php echo $mid;?>"></span>
        	   
        	   <button class="give_scheduled_medication interval_settings" id="interval_set_button_<?=$mid;?>" data-drug_id="<?=$mid;?>">
        	       <?php echo $this->translate("GIVE");?>
        	   </button>
        	</div>
        	
        </li>
        
    </ul>
    
<?php 
    endforeach;
endif; 
?>
</div><!-- end placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<?php $this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureEnd() ?>