<?php

$thisIconNumber = $k_sys_det = 55;
$thisIconNiceName = "form_block_ventilation";

$patientMasterData = $this->{'patientMasterData'};

$system_icon_data = $patientMasterData['system_icon_data'];
$system_icon_details = $patientMasterData['system_icon_details'];
$patient_sys_icons = $patientMasterData['patient_sys_icons'];
$patient_icons_details = $patientMasterData['patient_icons_details'];
$custom_icon_details = $patientMasterData['custom_icon_details'];
$btm_perm = $patientMasterData['btm_perm'];
$has_btm_permission = $patientMasterData['has_btm_permission'];
$diagno_act_module = $patientMasterData['diagno_act_module'];
$death_date = $patientMasterData['death_date'];
$nr = $patientMasterData['nr'];
$show_debtor_number = $patientMasterData['show_debtor_number'];

$this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureStart();

// $this->headScript()->appendFile(RES_FILE_PATH . "/javascript/views/templates/iconsexpanded/{$thisIconNumber}.js");
?>
<!-- start placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<div class="tab-content iconexpandbar collapsed" id="content_sys_icon-<?php echo $k_sys_det; ?>">
<?php 

$lang_block_ventilation = $this->translate('lang_block_ventilation'); 

$block_ventilation = $system_icon_data[$k_sys_det]['form_block_ventilation'][$this->ipid];

?>

    <ul class="defaultContainer">
        <li class="header">
        	<h3><?=$this->translate('patient_form_block_ventilation'); ?></h3>
        </li>        
        
        <li class="elmnt">
        	<div class="fname"><?=$lang_block_ventilation['Modus']?></div>
        	<div class="fval"><?=$this->escape($block_ventilation['modus']); ?></div>
        </li>
        <li class="elmnt">
        	<div class="fname"><?=$lang_block_ventilation['F_tot']?></div>
        	<div class="fval"><?=$this->escape($block_ventilation['f_tot']); ?></div>
        </li>
        <li class="elmnt">
        	<div class="fname"><?=$lang_block_ventilation['Vt']?></div>
        	<div class="fval"><?=$this->escape($block_ventilation['vt']); ?></div>
        </li>
        <li class="elmnt">
        	<div class="fname"><?=$lang_block_ventilation['MV']?></div>
        	<div class="fval"><?=$this->escape($block_ventilation['mv']); ?></div>
        </li>
        <li class="elmnt">
        	<div class="fname"><?=$lang_block_ventilation['PEEP']?></div>
        	<div class="fval"><?=$this->escape($block_ventilation['peep']); ?></div>
        </li>
        <li class="elmnt">
        	<div class="fname"><?=$lang_block_ventilation['PIP']?></div>
        	<div class="fval"><?=$this->escape($block_ventilation['pip']); ?></div>
        </li>
        <li class="elmnt">
        	<div class="fname"><?=$lang_block_ventilation['O2_l_min']?></div>
        	<div class="fval"><?=$this->escape($block_ventilation['o2_l_min']); ?></div>
        </li>
        <li class="elmnt">
        	<div class="fname"><?=$lang_block_ventilation['I_E']?></div>
        	<div class="fval"><?=$this->escape($block_ventilation['i_e']); ?></div>
        </li>
        <li class="elmnt">
        	<div class="fname"><?=$lang_block_ventilation['freetext']?></div>
        	<div class="fval"><?=nl2br($this->escape($block_ventilation['freetext'])); ?></div>
        </li>
        
        
    </ul>

</div><!-- end placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<?php $this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureEnd() ?>