<?php

$thisIconNumber = $k_sys_det = 56;
$thisIconNiceName = "current_maintenancestage";

$patientMasterData = $this->{'patientMasterData'};

$system_icon_data = $patientMasterData['system_icon_data'];
$system_icon_details = $patientMasterData['system_icon_details'];
$patient_sys_icons = $patientMasterData['patient_sys_icons'];
$patient_icons_details = $patientMasterData['patient_icons_details'];
$custom_icon_details = $patientMasterData['custom_icon_details'];
$btm_perm = $patientMasterData['btm_perm'];
$has_btm_permission = $patientMasterData['has_btm_permission'];
$diagno_act_module = $patientMasterData['diagno_act_module'];
$death_date = $patientMasterData['death_date'];
$nr = $patientMasterData['nr'];
$show_debtor_number = $patientMasterData['show_debtor_number'];

$this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureStart();

// $this->headScript()->appendFile(RES_FILE_PATH . "/javascript/views/templates/iconsexpanded/{$thisIconNumber}.js");
?>
<!-- start placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<div class="tab-content iconexpandbar collapsed" id="content_sys_icon-<?php echo $k_sys_det; ?>">
<?php 

$current_maintenancestage = $system_icon_data[$k_sys_det]['details_current_maintenancestage'][$this->ipid]['stage'];

?>

    <ul class="defaultContainer">
        <li class="header">
        	<h3><?=$this->translate('pflegegrade')?> : <b><?=$this->escape($current_maintenancestage['stage'])?></b></h3>
        </li>        
        <?php if ($current_maintenancestage['erstantrag'] == "1") : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('Erstantrag')?></div>
        </li>
        <?php endif; ?>
        <?php if ($current_maintenancestage['horherstufung'] == "1") : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('Höherstufung beantragt')?></div>
        </li>
        <?php endif; ?>
    </ul>

</div><!-- end placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<?php $this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureEnd() ?>