<?php

$thisIconNumber = $k_sys_det = 6;
$thisIconNiceName = "Dead";

$patientMasterData = $this->{'patientMasterData'};

$system_icon_data = $patientMasterData['system_icon_data'];
$system_icon_details = $patientMasterData['system_icon_details'];
$patient_sys_icons = $patientMasterData['patient_sys_icons'];
$patient_icons_details = $patientMasterData['patient_icons_details'];
$custom_icon_details = $patientMasterData['custom_icon_details'];
$btm_perm = $patientMasterData['btm_perm'];
$has_btm_permission = $patientMasterData['has_btm_permission'];
$diagno_act_module = $patientMasterData['diagno_act_module'];
$death_date = $patientMasterData['death_date'];
$nr = $patientMasterData['nr'];
$show_debtor_number = $patientMasterData['show_debtor_number'];

$this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureStart();

// $this->headScript()->appendFile(RES_FILE_PATH . "/javascript/views/templates/iconsexpanded/{$thisIconNumber}.js");
?>
<!-- start placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<div class="tab-content iconexpandbar collapsed" id="content_sys_icon-<?php echo $k_sys_det; ?>">
<?php 

if (in_array($system_icon_data[$k_sys_det][$this->ipid]['show']['id'], array("8", "7", "10"))) :

?>
    <ul class="defaultContainer">
    
            <?php 
            if ($system_icon_data[$k_sys_det][$this->ipid]['show']['id'] == "8") :
            ?>
            <li class="header">
            	<h3><?=$this->translate('Discharge death date'); ?></h3>
            	<h4><?=$this->escape($death_date);?></h4>
            </li>
            
            
            <?php
            elseif($system_icon_data[$k_sys_det][$this->ipid]['show']['id'] == "10") :
            ?>
            <li class="header">
            	<h3><?=$this->translate('hospital_admission'); ?></h3>
            	<h4><?=$this->escape(date('d.m.Y', strtotime($system_icon_data[$k_sys_det][$this->ipid]['last_location']['valid_from'])));?></h4>
            </li>
            
            
            <?php
            elseif($system_icon_data[$k_sys_det][$this->ipid]['show']['id'] == "7") : ?>
            <li class="header">
            	<h3><?=$this->translate('discharged_date'); ?></h3>
            	<h4><?=$this->escape(date('d.m.Y', strtotime($system_icon_data[$k_sys_det][$this->ipid]['discharge_details']['discharge_date'])));?></h4>
            </li>
            
            
            <?php endif;?>
    </ul> 
            
<?php endif; ?>

</div><!-- end placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<?php $this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureEnd() ?>