<?php

$thisIconNumber = $k_sys_det = 63;
$thisIconNiceName = "patient_contact_persons_custodians";

$patientMasterData = $this->{'patientMasterData'};

$system_icon_data = $patientMasterData['system_icon_data'];
$system_icon_details = $patientMasterData['system_icon_details'];
$patient_sys_icons = $patientMasterData['patient_sys_icons'];
$patient_icons_details = $patientMasterData['patient_icons_details'];
$custom_icon_details = $patientMasterData['custom_icon_details'];
$btm_perm = $patientMasterData['btm_perm'];
$has_btm_permission = $patientMasterData['has_btm_permission'];
$diagno_act_module = $patientMasterData['diagno_act_module'];
$death_date = $patientMasterData['death_date'];
$nr = $patientMasterData['nr'];
$show_debtor_number = $patientMasterData['show_debtor_number'];

$this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureStart();

// $this->headScript()->appendFile(RES_FILE_PATH . "/javascript/views/templates/iconsexpanded/{$thisIconNumber}.js");
?>
<!-- start placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<div class="tab-content iconexpandbar collapsed" id="content_sys_icon-<?php echo $k_sys_det; ?>">
<?php 

foreach ($system_icon_data[$k_sys_det]['patient_contact_persons_custodians'][$this->ipid] as $row) :

?>

    <ul class="defaultContainer">
    
        <li class="header">
        	<h3><?=$row['cnt_custody_val'] == 1 ? $this->translate('custodians') : $this->translate('other persons'); ?></h3>
        	<h4><?=$this->escape($row['nice_name']); ?></h4>
        </li>        
        
        <li class="elmnt ywbg">
        	<div class="fname"><?=$this->translate('cnt_custody_val')?> : <?=$row['cnt_custody_val'] == 1 ? $this->translate('yes_radio') : $this->translate('no_radio') ; ?></div>
        	<?php if ( ! empty($row['cnt_custody'])) : ?>
        	<div class="fval"><?=nl2br($this->escape($row['cnt_custody'])); ?></div>
        	<?php endif; ?>
        </li>
        
        <?php if ( ! empty($row['cnt_first_name'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('firstname')?></div>
        	<div class="fval"><?=$this->escape($row['cnt_first_name']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($row['cnt_last_name'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('lastname')?></div>
        	<div class="fval"><?=$this->escape($row['cnt_last_name']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($row['cnt_street1'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('address')?></div>
        	<div class="fval"><?=$this->escape($row['cnt_street1']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($row['cnt_zip'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('zip')?></div>
        	<div class="fval"><?=$this->escape($row['cnt_zip']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($row['cnt_city'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('city')?></div>
        	<div class="fval"><?=$this->escape($row['cnt_city']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($row['cnt_phone'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('phone')?></div>
        	<div class="fval"><?=$this->escape($row['cnt_phone']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($row['cnt_mobile'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('mobile')?></div>
        	<div class="fval"><?=$this->escape($row['cnt_mobile']); ?></div>
        </li>   
        <?php endif;?>
        <?php if ( ! empty($row['cnt_email'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('email')?></div>
        	<div class="fval"><?=$this->escape($row['cnt_email']); ?></div>
        </li>   
        <?php endif;?>

        <li class="elmnt">
        	<div class="fname"><?=$this->translate('hatversorgungsvollmacht')?></div>
        	<div class="fval"><?=$row['cnt_hatversorgungsvollmacht'] == 1 ? $this->translate('yes_radio') : $this->translate('no_radio') ; ?></div>
        </li>   
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('Legal guardian')?></div>
        	<div class="fval"><?=$row['cnt_legalguardian'] == 1 ? $this->translate('yes_radio') : $this->translate('no_radio') ; ?></div>
        </li>   
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('notify_funeral')?></div>
        	<div class="fval"><?=$row['notify_funeral'] == '1' ? $this->translate('yes_radio') : ($row['notify_funeral'] == '0' ? $this->translate('no_radio') : '–'); ?></div>
        </li>   
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('quality_control')?></div>
        	<div class="fval"><?=$row['quality_control'] == 1 ? $this->translate('yes_radio') : $this->translate('no_radio') ; ?></div>
        </li>   

        <?php if ( ! empty($row['cnt_familydegree_id'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('patientrelationship')?></div>
        	<div class="fval"><?=$this->escape($patientMasterData['FamilyDegree'][$row['cnt_familydegree_id']]); ?></div>
        </li>   
        <?php endif; ?>
        
        <?php if ( ! empty($row['cnt_comment'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?=$this->translate('comment')?></div>
        	<div class="fval"><?=$this->escape($row['cnt_comment']); ?></div>
        </li>   
        <?php endif;?>
        
    </ul>   
            
            
            
<?php endforeach; ?>
</div><!-- end placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<?php $this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureEnd() ?>