<!-- TODO-3707 Lore 06.01.2021  -->
<?php

$thisIconNumber = $k_sys_det = 79;
$thisIconNiceName = "ventilation";

$patientMasterData = $this->{'patientMasterData'};

$system_icon_data = $patientMasterData['system_icon_data'];
$system_icon_details = $patientMasterData['system_icon_details'];
$patient_sys_icons = $patientMasterData['patient_sys_icons'];
$patient_icons_details = $patientMasterData['patient_icons_details'];
$custom_icon_details = $patientMasterData['custom_icon_details'];
$btm_perm = $patientMasterData['btm_perm'];
$has_btm_permission = $patientMasterData['has_btm_permission'];
$diagno_act_module = $patientMasterData['diagno_act_module'];
$death_date = $patientMasterData['death_date'];
$nr = $patientMasterData['nr'];
$show_debtor_number = $patientMasterData['show_debtor_number'];

$this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureStart();

$this->headScript()->appendFile(RES_FILE_PATH . "/javascript/views/templates/iconsexpanded/{$thisIconNumber}.js");
?>
<!-- start placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<div class="tab-content iconexpandbar collapsed" id="content_sys_icon-<?php echo $k_sys_det; ?>">

    <ul class="defaultContainer">
        <li class="header">
        	<h4><?=$this->translate('ventilation')?></h4>
        </li>
        <li class="elmnt">    	
        	<div class="fval">
        	   <span class="current_problem_text">
        	   <?=$this->formNote(
        	       'ventilation_note',
        	       ! empty($system_icon_data[$k_sys_det]['ventilation'][$this->ipid]['problem']) ? nl2br($this->escape(str_replace("<br />", "", $system_icon_data[$k_sys_det]['ventilation'][$this->ipid]['problem']))) : ''
        	       
    	       );?>
    	       </span>
        	   <?=$this->formTextarea(
        	       'ventilation', 
        	       ! empty($system_icon_data[$k_sys_det]['ventilation'][$this->ipid]['problem']) ? $this->escape(str_replace("<br />", "", $system_icon_data[$k_sys_det]['ventilation'][$this->ipid]['problem'])) : '', 
        	       [
        	           'rows' => 3,
        	           'placeholder' => $this->translate('No data, click to add'),
        	           'class' => 'current_problem_text'
        	       ]
    	       );?>
    	   </div>
        	
        </li>
    </ul>
    
</div><!-- end placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<?php $this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureEnd() ?>