<?php

$thisIconNumber = $k_sys_det = 99999; //this is the id(pk) of you icon
$thisIconNiceName = "WRITE HERE A NICE NAME IN ENGLISH!!!!"; //this is used as comment in html only

/*
 * VARIABLES AT YOUR DISPOSAL
 * + $this->{'patientMasterData'}
 * + $this->ipid
 * + $this->end_id
 * + $this->logininfo
 * ... plus other, just make the efort and read Pms_Controller_Action for properties and methods
 */
$patientMasterData = $this->{'patientMasterData'};

$system_icon_data = $patientMasterData['system_icon_data'];
$system_icon_details = $patientMasterData['system_icon_details'];
$patient_sys_icons = $patientMasterData['patient_sys_icons'];
$patient_icons_details = $patientMasterData['patient_icons_details'];
$custom_icon_details = $patientMasterData['custom_icon_details'];
$btm_perm = $patientMasterData['btm_perm'];
$has_btm_permission = $patientMasterData['has_btm_permission'];
$diagno_act_module = $patientMasterData['diagno_act_module'];
$death_date = $patientMasterData['death_date'];
$nr = $patientMasterData['nr'];
$show_debtor_number = $patientMasterData['show_debtor_number'];

$this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureStart();

/*
 * create and add custom js file that applies only to this placeholder
 */
//$this->headScript()->appendFile(RES_FILE_PATH . "/javascript/views/templates/iconsexpanded/{$thisIconNumber}.js");
?>
<!-- start placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<div class="tab-content iconexpandbar collapsed" id="content_sys_icon-<?php echo $k_sys_det; ?>">


    <ul class="defaultContainer">
        
        <li class="header">
        	<h3><?php echo $this->translate('XXXXXX'); ?></h3>
        	<h4><?php echo $sssssss['YYYYY']; ?></h4>
        </li>
        
        <?php if (! empty($sssssss['YYYYY'])) : ?>
        <li class="elmnt">
        	<div class="fname"><?php echo $this->translate('XXXXXX'); ?></div>
        	<div class="fval"><?php echo $sssssss['YYYYY']; ?></div>
        </li>   
        <?php endif;?>
        
    </ul>

</div><!-- end placeholder.patient.icons.expanded.<?=$thisIconNumber?>  =  <?=$thisIconNiceName?> -->
<?php $this->placeholder("patient.icons.new.expanded.{$thisIconNumber}")->captureEnd() ?>