<table class="datatable">
    <tr>
        <th><?php echo $this->translate('rform_name')?></th>
        <th><?php echo $this->translate('actions')?></th>
    </tr>
    <?php foreach($this->forms as $form_ident):?>
        <tr>
            <td><?php echo $form_ident?></td>
            <td>
                <a href="rubin/formquestionlist?form_ident=<?php echo $form_ident;?>">Question order</a>
                <a href="rubin/formquestionoptionslist?form_ident=<?php echo $form_ident;?>">Question options</a>
            </td>
        </tr>
    <?php endforeach;?>
</table>