<table width="100%">
	<tr>
		<td colspan="6" valign="top">&nbsp;</td>

	</tr>
	<tr>
		<td valign="top">&nbsp;</td>
		<td valign="top"><b><?php echo $this->translate($this->form_ident); ?> :</b></td>
		<td valign="top">&nbsp;</td>
	</tr>
	<tr>
		<td colspan="3" valign="top">&nbsp;</td>

	</tr>
</table>
<form action="" method="post" name="frmcourse" id="frmcourse" >
	<div class="grid">
		<table id=" " class="datatable" border="0">
			<thead>
			<tr>
				<th style="width: 50px;">#</th>
				<th><?php echo $this->translate('question_text'); ?></th>
				<th><?php echo $this->translate('question_id'); ?></th>
				<th><?php echo $this->translate('question_type'); ?></th>
				<th><?php echo $this->translate('question_order'); ?></th>
			</tr>
			</thead>
			<tbody>
			<?php if($this->form_questions):  ?>
			<?php $i = '1'; foreach($this->form_questions as $k => $v_q):  ?>
			

			<tr id="<?php echo $v_q['id']; ?>" class="sort">
				<td>
					<?php echo $i;  ?>
				</td>
				<td><?php echo $v_q['question_text'];  ?></td>
				<td><?php echo $v_q['question_id'];  ?></td>
				<td><?php echo $v_q['question_type'];  ?></td>
				<td>
				
				<input type="text" name="order[<?php echo $v_q['id']; ?>]" value="<?php echo $v_q['question_order']; ?>" />
				</td>
 
				
			</tr>
			<?php $i++; endforeach;  ?>
			<?php else:  ?>

			<tr>
				<td colspan="3">
					<?php echo $this->translate('no_blocks_found');  ?>
				</td>
			</tr>
			<?php endif  ?>
			<tr class="disabled">
				<td colspan="8" valign="top" align="left">
					<a class="button"  href="<?php echo APP_BASE . 'rubin/formlist'; ?>" style="padding: 0;"><?php echo $this->translate('backtolist') ?></a>
					<input name="submit" id="submit" type="submit" class="button" value="<?php echo $this->translate('submit') ?>" />
				</td>
			</tr>
			</tbody>
		</table>
	</div>
</form>