<?php 

//css append
$this->headLink()->appendStylesheet(RES_FILE_PATH.'/css/page-css/rubin/rubin.css');

?>

<!-- inline script -->
<script type="text/javascript" >
var scores_arr = {};
scores_arr['before_anamnesis_total'] = 0;
scores_arr['anamnesis_total'] = 0;
var total = 0;
</script>



<?php
    //echo the form

    $this->form
    ->setAction($this->url() . "?id=" . $this->enc_id)
    ->setMethod(Zend_Form::METHOD_POST)
    ->setAttrib('novalidate', true) // this form is not html5 friendly.. it has closed accordions
    ->setAttrib('autocomplete', false) // this form is not html5 friendly.. it has closed accordions
    ->setAttrib("id", "rubin_form")
    ->setAttrib("class", "form_class")
    ->setAttrib("onsubmit", "return form_submit_validate();");
        


    echo $this->form;
?>


