<?php 
#ISPC-2512PatientCharts
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/page-css/overview_charts.css?' . date('Ymd'));
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/page-css/overview_charts_viewmode.css?' . date('Ymd'));// css for view selector

$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/page-css/expanding-buttons.css');

$blocks = $this->chart_blocks;



$pid = $_REQUEST['id'];

//set default for overview
// $chart_interval = 'week';
$chart_interval = $this->chart_interval;

$default_period = $this->period;
$start_date = $default_period['start_date'];
$end_date = $default_period['end_date'];

$start_date_ts = $default_period['start_date_ts'];
$end_date_ts = $default_period['end_date_ts'];

?>

<script type="text/javascript">
	var pid = '<?php echo $pid; ?>';
	// Get data for the first load 
	var start = '<?php echo $start_date; ?>';
	var end = '<?php echo $end_date; ?>';
	
	var start_ts = '<?php echo $start_date_ts; ?>';
	var end_ts  = '<?php echo $end_date_ts; ?>';
	
	var chart_type = '<?php echo $chart_interval; ?>';
	var chart_view_type = '<?php echo $chart_interval; ?>';

	var blocks = <?php echo json_encode($this->chart_blocks) ?>;			//ISPC-2841 Lore 29.03.2021
	
	// console.log(start,end,start_ts,end_ts);
	
	// Function to load navigation
	load_navigation(pid,chart_view_type,start_ts,end_ts);
	 
	// Function to load al charts
	//load_charts(pid,start_ts,end_ts);
	load_charts(pid,start_ts,end_ts, blocks);		//ISPC-2841 Lore 29.03.2021

	

	</script>
<style>
 .outer{ 
 	width: 100%!important; 
 } 

 #Wrapper { 
     width: 100%-14!important;          /*ISPC-2512 Lore 15.06.2020*/
    /* min-width: 1010px !important; 
 } 

/* #MainContent { 
     /* width: 80%!important;  */       /*ISPC-2512 Lore 15.06.2020*/
}
/* .highcharts-title{ */
/*     top: 0 !important; */
/*     left: 0 !important; */
/*     width: 240px; */
/*     padding: 10px 5px 10px 5px; */
/*     border-right: 1px solid #DBDEE6; */
/* } */
/*.time_chart_block{
    display: none;
    position: relative !important;
} */

div.sticky {
  	position: -webkit-sticky;
  	position: sticky;
	width: 100%;
	display: inline-table;
	background: #ffffff;
	margin: 2px 0 2px 0;
  	z-index:1000;
  	top: 50px;
  }
/* 

.time_chart_block .fixed  {

}



#portamento_container{
	background: transparent;
	z-index: 2;
}
#portamento_container #time_chart_container {
	visibility: hidden;
}
 

.time_chart_block {
	display: none;
} */

/* #portamento_container #time_chart_container.fixed
	{
	visibility: visible;
	position: fixed;
	width: 88%;                 /*ISPC-2512 Lore 15.06.2020*/
}

/*#portamento_container #time_chart_container.fixed .time_chart_block {
	display: block;
}

#portamento_container #time_chart_container.fixed {
} */


</style>
<div class="mca">
<div style="display: none;"><img id="calImg" src="<?php echo RES_FILE_PATH; ?>/images/calendar.png" alt="Popup" class="trigger"></div>
<form action="" method="post" id="chart_filter">
<input type="hidden" readonly disabled id="selected_chart_type" value="<?php echo $chart_interval;?>" />
<input type="hidden" readonly disabled id="interval_start_date" value="<?php echo $start_date_ts;?>" />
<input type="hidden" readonly disabled id="interval_end_date"  value="<?php echo $end_date_ts;?>"  />
</form>


<div id="chart_navigation">
    <!-- navigation -->
</div>

<div id="charts_display">

    <div class="sticky" style="display: none;">
        <div class="chart_blocks" id="time_chart" style="background: transparent!important; width: 100%;">	<!-- ISPC-2512 Lore 15.06.2020 width: 100%; -->
        <!-- time chart -->
        </div>
    </div>
    <?php foreach($blocks  as $block):?>
    <div class="chart_blocks" id="ch_<?php echo $block;?>_chart">
    	<div class="chart_grafic_block" id="<?php echo $block;?>_chart" style="width: 100%;">	<!-- ISPC-2512 Lore 15.06.2020 style="width: 100%; -->
        <!--chart -->
    	</div>
    </div>
    <?php endforeach;?>
     
     
    </div>
</div>
 



<div class="modal_overlay" style="display: none"></div>
<div id="cfinfo_modal"></div>

