<?php
/**
 * add here variables you need in /javascript/views/(controller)/(action)(.mobile.js && .js)
 * prefix your specific vars with `controller_action_`, so we don't have colisions
 */

?>

<div class="patientoveralllistNavigation">
    <a onClick="changePatientlistTab(this); return false;" rel="active" class="active" ><?php echo $this->translate('activepatients')?></a>
	<a onClick="changePatientlistTab(this); return false;" rel="discharged" ><?php echo $this->translate('dischargedpatients')?></a>
	<a onClick="changePatientlistTab(this); return false;" rel="standby" class="tabs" id="tab-2" ><?php echo $this->translate('standby')?></a>
</div>
    
<!-- datatable placeholder -->
<table class="selector_allpatientlist_table patientlist" border="0" cellspacing="0" cellpadding="0" >
</table>

