<?php
//ISPC-2895 Ancuta 20.05.2021
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/data_tables/datatables.min.css?' . date('Ymd'));
$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/data_tables/jquery.dataTables.js?'.date('Ymd'));
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/data_tables/fixedColumns.dataTables.min.css?' . date('Ymd'));
$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/data_tables/dataTables.fixedColumns.min.js?'.date('Ymd'));

$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/vstn_export.css?' . date('Ymd'));
$page_lang = $this->translate("vstn_export");
?>
 
<script type="text/javascript">
$(document).ready(function(){
 
 

 
    $( "#from" ).datepicker({
        changeMonth: true,
        changeYear: true,
		showOn: "both",
		buttonImage: $('#calImg').attr('src'),
		buttonImageOnly: true,
        onClose: function( selectedDate ) {
          $( "#to" ).datepicker( "option", "minDate", selectedDate );
        } 
      });
      $( "#to" ).datepicker({
		showOn: "both",
		buttonImage: $('#calImg').attr('src'),
		buttonImageOnly: true,
        changeMonth: true,
        changeYear: true,
        onClose: function( selectedDate ) {
          $( "#from" ).datepicker( "option", "maxDate", selectedDate );
        } 
      });
	
      
      $( "#from" ).mask("99.99.9999");
      $( "#to" ).mask("99.99.9999");
      
      $( "#from" ).on('change',function() {
    	  if( $(this).val().length > 0 ){
    	  }
      });
      $( "#to" ).on('change',function() {
    	  if( $(this).val().length > 0 ){
    	  }
      });
      
      
  	
  	
  	var datatable_files =	$('.vstn_files').DataTable({
		// ADD language
		 "language": {
                "url": "<?php echo RES_FILE_PATH.'/javascript/data_tables/de_language.json?'.date('Ymd')?>"
         },
 		sDom: 
			'tr',
 
		processing: true,
		
		info: false,
		filter: true,
		paginate: true,

		serverSide: true,
		"autoWidth": false,
		"stateSave": false,
		"scrollX": false,
		"scrollCollapse": true,
		"ordering": false,
		

		columns: [
		          { data: "export_date", className: ""},//0
// 		          { data: "download_link", className: ""},//1
		          { data: "delete", className: ""},//2
			],
			
		 columnDefs: [ 
				       	{ "targets": 0, "searchable": false, "orderable": false, "name":"export_date" }, // export_date
// 				       	{ "targets": 1, "searchable": false, "orderable": false, "name":"download_link" }, // first_name
				       	{ "targets": 1, "searchable": false, "orderable": false, "name":"delete" } // last_name
				],				
 		 ajax: {
			url:'vstn/getvstnfiles',
			type: 'POST'
		}
	});
  	
	$(".delete_file").live('click', function() {
		$.confirmdeleteid = $(this).attr('rel');
			jConfirm('<? echo $this->translate('confirmdeleterecord'); ?>', '<? echo $this->translate('confirmdeletetitle'); ?>', function(r) {
			if(r)
			{	
				
// 				$.ajax({
// 					  method: "POST",
// 					  url : 'vstnnew/deletefile?id='+ $.confirmdeleteid,
					  
// 					  success: function(data)
// 					  {  
// 						  $(this).closest('tr').remove();
// 					  }
// 					}) 
				
				location.href = "<? echo APP_BASE ?>vstn/deletefile?id="+ $.confirmdeleteid;
			}
		});
	});
	
});
</script>
<style>
.dataTables_processing{
	top:10px!important;      
	height: 100%!important;      
	border: 1px solid #333;
}

label.checkboxes {
  display: block;
  float: left;
  padding-right: 10px;
  white-space: nowrap;
}
label.checkboxes input {
  vertical-align: middle;
}
label.checkboxes span {
  vertical-align: middle;
}
</style>
<div style="display: none"> <img id="calImg" src="<?php echo RES_FILE_PATH;  ?>/images/calendar.png" alt="Popup" class="trigger"> </div>


<div class="page_title">
	<h1>	<?php echo $this->translate('Rubin export');?>
	</h1>
</div>	
<div class="clear"></div>
<form action="" method="post" id="export">
<input type="hidden" name="tp" value="<?php echo $_REQUEST['tp']?>" />

<table border="1" cellspacing="3" cellpadding="2" class="export_settings">
	<tr>
		<td class="tdheader">
		<?php echo $this->translate('Period selection');?>
		</td>
		<td class="tdoptions">
			<input type="text" name="period[start]"  id="from" value="<?php echo $this->period_start;?>" /> 
			<input type="text" name="period[end]"    id="to" value="<?php echo $this->period_end;?>" /> 
		</td>
	</tr>
	<tr>
		<td colspan="2" width="100%">
			<br style="clear: both"/>
 
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<input type="submit" name="generate" value="Export" />
		</td>
	</tr>
	<tr>
		<td colspan="2" align="left" >
		</td>
	</tr>
</table>

</form>