<!-- Ajax loaded ul  -->
<ul class="cbrdList LOAD"  >
<?php foreach($this->goaii_actions as $kgii=>$value_goaii):?>
	<?php if($value_goaii['available'] == '1'):?>
			<li>
				<?php if($value_goaii['source'] == "xbdt"):?>
					<input type="checkbox" name="egblock[goaii][<?php echo $value_goaii['id'];?>][value]"  value="1" <?php if($this->patient_xbdt_goaii_values[$value_goaii['id']]['value'] == '1'):?> checked="checked"<?php endif;?>   id="<?php  echo !empty($value_goaii['form_item_id']) ? $value_goaii['form_item_id'] : 'goaii'.$value_goaii['id'] ?>"   />
            <label for="<?php  echo !empty($value_goaii['form_item_id']) ? $value_goaii['form_item_id'] : 'goaii'.$value_goaii['id'] ?>"><?php echo $value_goaii['option_id'];?>  -  <?php echo $value_goaii['option_name'];?></label>
					<input type="hidden"  name="egblock[goaii][<?php echo $value_goaii['id'];?>][patient_xbdt_action_id]" value="<?php echo $this->patient_xbdt_goaii_values[$value_goaii['id']]['patient_xbdt_action_id']?>" />
				<?php else:?>
					<input type="checkbox" name="egblock[goaii][<?php echo $value_goaii['id'];?>][value]"  value="1" <?php if($this->patient_goaii_values[$value_goaii['id']]['value'] == '1'):?> checked="checked"<?php endif;?>   id="<?php  echo !empty($value_goaii['form_item_id']) ? $value_goaii['form_item_id'] : 'goaii'.$value_goaii['id'] ?>"  />
            <label for="<?php  echo !empty($value_goaii['form_item_id']) ? $value_goaii['form_item_id'] : 'goaii'.$value_goaii['id'] ?>"><?php echo $value_goaii['option_id'];?>  -  <?php echo $value_goaii['option_name'];?></label>
				<?php endif;?>
				<input type="hidden"  name="egblock[goaii][<?php echo $value_goaii['id'];?>][source]" value="<?php echo $value_goaii['source'];?>" />
		</li>
	<?php endif;?>
<?php endforeach; ?>
</ul>