<?php if (empty($this->droparray)) : ?>

    <p><?php echo $this->translate('noresultfound');  ?></p>
    <input type="hidden" value="1" id="livesearch_global_patient_no_records" />

<?php else : ?>

<?php $curent_status = ''; $rowcounter = 0;?>
<table border="0" align="left" cellpadding="0" cellspacing="0" class="patientlist" width="100%">
	
    <thead>
		<tr>
            <td><?=$this->translate('firstname')?></td>
            <td><?=$this->translate('lastname')?> </td>
            <!-- 
            <td><?=$this->translate('dateofbirth')?></td>
            <td><?=$this->translate('recordingdate')?></td>
             -->
        </tr>
	</thead>
    
	<tbody>
		<?php foreach($this->droparray as $k_patient=>$v_patient):  ?>
            <?php $rowcounter++; ?>
			<?php if($v_patient['status'] != $curent_status):  ?>
				<tr class="group_row">
					<td colspan="2">
						<div class="searchledgend">
							<div class="activerow"><?php echo $this->translate('top_search_patient_status'.$v_patient['status']); ?></div>
						</div>
					</td>
				</tr>
			<?php $curent_status = $v_patient['status']; $rowcounter = 0; endif;  ?>
			
            <?php if($_REQUEST['op'] == 'assigned_patients'):  ?>
			<tr class="row <?=$rowcounter%2 ? 'even' : 'odd' ?>" onclick="selectPatAssigned('<?php echo $v_patient['epid_id']; ?>')">
				<td><?php echo $v_patient['first_name']; ?></td>
				<td><?php echo $v_patient['last_name']; ?></td>
                <!-- 
				<td><?php echo $v_patient['birthd']; ?></td>
				<td><?php echo $v_patient['admission_date']; ?></td>
                 -->
			</tr>
			
            <?php else: ?>
            
			<tr class="row <?=$rowcounter%2 ? 'even' : 'odd' ?>" onclick="selectPat('<?php echo $v_patient['id']; ?>')">
				<td><?php echo $v_patient['first_name']; ?></td>
				<td><?php echo $v_patient['last_name']; ?></td>
                <!-- 
				<td><?php echo $v_patient['birthd']; ?></td>
				<td><?php echo $v_patient['admission_date']; ?></td>
                 -->
			</tr>
			<?php endif;  ?>

		<?php endforeach;  ?>
	</tbody>
</table>

<?php endif;  ?>