<?php if ($this->droparray): ?>
<table border="0" align="left" cellpadding="0" cellspacing="0" class="overviewdatatable" id="topsearchtable" width="100%">
	<!--  <thead> ISPC-2561 if module 221 activate show patients for all clients the user can connect
		<tr class="BlueBg"><td class="first" width="233"><?php echo $this->translate('firstname');  ?></td><td width="200"><?php echo $this->translate('lastname');  ?> </td><td><?php echo $this->translate('dateofbirth');  ?></td><td width="350"><?php echo $this->translate('recordingdate');  ?> </td></tr>
	</thead> -->
	<tbody>
		<!-- ISPC-2561 Lore 28.05.2020 -->
		<tr class="BlueBg"><td class="first" width="233"><?php echo $this->translate('firstname');  ?></td><td width="200"><?php echo $this->translate('lastname');  ?> </td><td><?php echo $this->translate('dateofbirth');  ?></td><td width="350"><?php echo $this->translate('recordingdate');  ?> </td></tr>
		<?php for($i = 0; $i <= 3; $i++) {  ?>	<!-- $v_patient['status']) can be 0,1,2 or 3 -->
			<?php $brow_tr_head = 0;  ?>
			
        	<?php foreach($this->droparray as $k_cl=>$v_cl):  ?>
            	<!-- <tr class="BlueBg"><td  colspan="4"><?php echo $this->client_data[$k_cl]['client_name'];  ?></td></tr> -->
            	<!-- <tr class="BlueBg"><td class="first" width="233"><?php echo $this->translate('firstname');  ?></td><td width="200"><?php echo $this->translate('lastname');  ?> </td><td><?php echo $this->translate('dateofbirth');  ?></td><td width="350"><?php echo $this->translate('recordingdate');  ?> </td></tr> -->
            	<?php if($k_cl == $this->clientid):  ?>
            		<?php foreach($v_cl as $k_patient=>$v_patient):  ?>
            
            				<?php if($v_patient['status'] == $i ):  ?>
							
								<?php $brow_tr_head = 1;  ?>
							
                    			<?php if($v_patient['status'] != $curent_status || ($v_patient['status'] == $curent_status && $k_cl != $curent_client)):  ?>
                    				<tr>
                    					<td colspan="4">
                    						<div class="searchledgend">
									  		   <!--  <div class="activerow"><?php echo $this->translate('top_search_patient_status'.$v_patient['status']); ?></div> -->
												 <!-- ISPC-2561 Lore 28.05.2020 -->
												<div class="activerow"><?php echo $this->translate('top_search_patient_status'.$v_patient['status']).' ('. $this->client_data[$k_cl]['client_name'] .')'; ?></div>
                    						</div>
                    					</td>
                    				</tr>
                    			<?php $curent_status = $v_patient['status']; $curent_client = $k_cl; endif;  ?>
                    			<?php if($_REQUEST['op'] == 'assigned_patients'):  ?>
                    			<tr class="row" onclick="selectPatAssigned('<?php echo $v_patient['epid_id']; ?>')">
                    				<td class="first" width="233"><?php echo $v_patient['first_name']; ?></td>
                    				<td width="200"><?php echo $v_patient['last_name']; ?></td>
                    				<td width="200"><?php echo $v_patient['birthd']; ?></td>
                    				<td width="350"><?php echo $v_patient['admission_date']; ?></td>
                    			</tr>
                    			<?php else:  ?>
                    			<tr class="row" onclick="selectPat('<?php echo $v_patient['id']; ?>')">
                    				<td class="first" width="233"><?php echo $v_patient['first_name']; ?></td>
                    				<td width="200"><?php echo $v_patient['last_name']; ?></td>
                    				<td width="200"><?php echo $v_patient['birthd']; ?></td>
                    				<td width="350"><?php echo $v_patient['admission_date']; ?></td>
                    			</tr>
                    			<?php endif;  ?>
                    		<?php endif;  ?>
                    			
            
            		<?php endforeach;  ?>
        		<?php else: ?>
            		<?php foreach($v_cl as $k_patient=>$v_patient):  ?>
						<?php if($v_patient['status'] == $i ):  ?>
							<?php $brow_tr_head = 1;  ?>
							            				
            				<?php if($v_patient['status'] != $curent_status || ($v_patient['status'] == $curent_status && $k_cl != $curent_client)):  ?>
            					<tr>
            						<td colspan="4">
            							<div class="searchledgend">
											<!--  <div class="activerow"><?php echo $this->translate('top_search_patient_status'.$v_patient['status']); ?></div> -->
											<!-- ISPC-2561 Lore 28.05.2020 -->
											<div class="activerow"><?php echo $this->translate('top_search_patient_status'.$v_patient['status']).' ('. $this->client_data[$k_cl]['client_name'] .')'; ?></div>										</div>
            							</div>
            						</td>
            					</tr>
            				<?php $curent_status = $v_patient['status']; $curent_client = $k_cl; endif;  ?>
            				
            				<tr class="row noclick">
            					<td class="first" width="233"><?php echo $v_patient['first_name']; ?></td>
            					<td width="200"><?php echo $v_patient['last_name']; ?></td>
            					<td width="200"><?php echo $v_patient['birthd']; ?></td>
            					<td width="350"><?php echo $v_patient['admission_date']; ?></td>
            				</tr>
            				
            			<?php endif;  ?>
            	
            		<?php endforeach;  ?>
        		<?php endif;  ?>
        	<?php endforeach;  ?>
        	
        	<?php if($brow_tr_head == 1):  ?>
					<tr class="BlueBg"><td class="first" width="233"><?php echo $this->translate('firstname');  ?></td><td width="200"><?php echo $this->translate('lastname');  ?> </td><td><?php echo $this->translate('dateofbirth');  ?></td><td width="350"><?php echo $this->translate('recordingdate');  ?> </td></tr>
			<?php endif;  ?>		
		
		<?php } ?>
		
	</tbody>
</table>
<?php else: ?>

	<p><?php echo $this->translate('noresultfound');  ?></p>
	<input type="hidden" value="1" id="livesearch_global_patient_no_records" />
<?php endif;  ?>