<?php
/*
 * this `layout_result_messages` needs to be moved into layout
 */
?>
<!--  //ISPC-2474 Ancuta 23.10.2020 -->
<style>
#projects_dtable tr td span, 
.alarm_info span 
{
	color: red;
	font-size:16px;
	font-weight:800;
}
 
.alarm_info {
	margin-top:5px;
	width:99%;
	border: 1px solid #000000;
	padding:5px;
}
</style>
<!-- //TODO-3337 Ancuta 18-19..08.2020:: Check treatment days of patient -->
<div id="layout_result_messages">
    <?php if (count($this->SuccessMessages)) : ?>
    <!--  SuccessMessages -->
        <ul id="messages" class="success">
        <?php foreach ($this->SuccessMessages as $message) : ?>
            <li><?php echo $this->escape($message); ?></li>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>
    <?php if (count($this->ErrorMessages)) : ?>
    <!--  ErrorMessages -->
        <ul id="messages" class="err">
        <?php foreach ($this->ErrorMessages as $message) : ?>
            <li><?php echo $this->escape($message); ?></li>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>
</div>

<script type="text/javascript">
var DEBUGMODE = false;
</script>

<?php
$this->headLink()->appendStylesheet(RES_FILE_PATH.'/css/pagination_style.css');
$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/data_tables/jquery.dataTables.js');
$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/data_tables/dataTables.jqueryui.js');
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/data_tables/dataTables.jqueryui.css');

$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/page-css/projects.css');

?>

<script type="text/javascript">        
    var DEBUGMODE = <?=APPLICATION_ENV == 'development' ? 'true' : 'false' ?>;
</script>

<div class="tab_container" >
    <div>
        <div id="tabs_projects">
        
            <ul>
                <li><a href="#tabs-1"><?=$this->translate('Patient discharged 10 years ago');?></a></li>
            </ul>

            <div id="tabs-1">
                <div id="submited">
                </div>
            </div>
            
 
            
            <table id="projects_dtable" class="selector_table_projects datatable" style="width:100%;">
                <tr>
                    <td colspan="6"><?php echo $this->translate('loadingpleasewait');?></td>
                </tr>
            </table>    
                
        </div>
        
    </div>
</div>


<div id="user_pass_validation">
<label><?php echo $this->translate('Please enter user deletion password');?></label>
<input  type="password"  id="user_password" name="user_password" value=""/>
</div>
