<?php 
/**
 * @author @cla
 * @since 01.11.2018
 * 
 * this layout is used just for user login, from /index/indexAction
 * or when special case server undermaintainance app.ini serverMove.redirectUser = 1
 */
?>
<?php echo $this->doctype() ?>
<!-- This Line will output the doctype we set inside the bootstrap file -->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<base href="<?php echo APP_BASE?>" />

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<?php echo $this->headTitle(); ?>

<?php
$this->headLink()->prependStylesheet(RES_FILE_PATH . '/bootstrap/3.3.5/css/bootstrap.min.css');
echo $this->headLink();
?>

<!-- layout metas  -->
<?php echo $this->headMeta() ?>

</head>
<body>
    <!-- isMaintenanceMode banner -->
    <?php echo $this->render('mobile/layout_new.undermaintenance.phtml') ?>

    <?php echo $this->layout()->content  ?>
    
</body>
</html>
