<?php

$appInfo = Zend_Registry::isRegistered('appInfo') ? Zend_Registry::get('appInfo') : [];

/* Banner for upload on maintenance mode*/
$show_upload_banner = isset($appInfo['isMaintenanceMode']) && $appInfo['isMaintenanceMode'] == 1 ? true : false;

if ($show_upload_banner == true) :

    $this->placeholder('website.under.maintenance')->captureStart();

?>
		<div class="alert alert-info" style="display: block;">
		<!--Wartungsarbeiten verschoben.<br />-->
		<!--Die Wartungsarbeiten werden am Montag gegen 21 Uhr durchgeführt. Das System wird dann ca. 1 Stunde nicht erreichbar sein.-->
		<!--</div>-->
			<!--Wir werden ab 17 Uhr die letzten Server-Anpassungen durchführen. Sie werden sich dann wieder mit Ihrem Token einloggen müssen. Dieses Token werden Sie vorher syncronisieren müssen. Klicken Sie dazu auf den "Kennwort ändern & Token syncronisieren Link in der Anmeldemaske. Die Server werden kurzfristig nicht erreichbar sein!-->
			<strong>ACHTUNG:</strong><br/>
			In den nächsten 15 Minuten werden Wartungsarbeiten durchgeführt. <br/>Wir erwarten keine bzw. minimale Einschränkungen für die Benutzung des Systems.<br/> 
			<!--  TODO-1029 15.06.2017-->
<!-- 			Wir führen aktuell Wartungsarbeiten durch. Während dieser Zeit kann es leider vereinzelt zu Einschränkungen im ISPC kommen.<br/> -->
<!-- 			Vielen Dank für Ihr Verständnis. Ihr smart-Q Team<br/> -->
			
			<!-- SERVER MAINTENANCE -->
			<!-- Wir werden am Dienstag 05.11. zwischen 19.00 und 21.00 uhr Wartungsarbeiten durchführen. Wir erhoffen uns einen großen Performance Gewinn durch diese Wartungsarbeiten. Wir erbitten die enstehenden Unannehmlichkeiten zu entschuldigen<br/> -->


            <!--SICK DAYS dec 2020-->
			Aufgrund eines erhöhten Krankenstands bei unseren Mitarbeitern, bitten wir Sie wenn möglich Ihre Anfragen per E-Mail an info@smart-q.de zu formulieren. Wir bitten Sie die verlängerten Reaktionszeiten zu entschuldigen.

			<!-- SERVER MAINTENANCE END -->


			<!--	Wir bitten um Ihr Verständnis.-->
			<!--Wir haben heute wichtige Aktualisierungen eingespielt. Bei Problemen auf den ISPC Seiten AKTUALISIEREN Sie bitte die Seite (F5 - Reload).-->
			<!--Es treten zur Zeit leichte Probleme in unserem Rechenzentrum auf. Wir arbeiten an der Lösung und sind zurverichtlich diese in kurzer Zeit behoben zu haben.-->
		</div>
		
<?php 
    $this->placeholder('website.under.maintenance')->captureEnd(); 
    
    echo $this->placeholder('website.under.maintenance'); // like this, maybe you need to echo in other place
    
endif;
?>
