<?php 
$patientMasterData = $this->{'patientMasterData'};
?>
<!-- start layout footer -->
<?php 
/**
 * TODO: the next divs MUST be removed altogether
 * edit  javascript/pms/usersession.js
 * add $('div', {'id': 'session_expired' }).append('body').dialog(...
 */
?>
<div id='session_expired'></div>
<div id='warning_expire'></div>
<div id='connection_lost'></div>
<div id='usersession_client_changed'></div>

<!-- end layout footer -->