<?php 
// Maria:: Migration ISPC to CISPC 08.08.2020 
?>
<div id="layout_result_messages" style="clear: both">
    <?php if (count($this->SuccessMessages)) : ?>
    <!--  SuccessMessages -->
        <ul id="messages" class="success">
        <?php foreach ($this->SuccessMessages as $message) : ?>
            <li><?php echo $this->escape($message); ?></li>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>
    <?php if (count($this->ErrorMessages)) : ?>
    <!--  ErrorMessages -->
        <ul id="messages" class="err">
        <?php foreach ($this->ErrorMessages as $message) : ?>
            <li><?php echo $this->escape($message); ?></li>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>
</div>

<?php
    //css append
    $this->headLink()->appendStylesheet(RES_FILE_PATH.'/css/page-css/versorger.css');
    
    //js append
    $this->headScript()->appendFile (RES_FILE_PATH . '/javascript/dateUtil.js');
    
    /*
    //add file uploader
    $this->headScript()->appendFile(APP_BASE.'javascript/fine-uploader/fine-uploader.min.js');
    $this->headLink()->appendStylesheet(APP_BASE.'javascript/fine-uploader/fine-uploader.css');
    //rendered-add the fine-uploader file-uploader template
    $qqtemplate = $this->render("templates/qq_fileupload_template_small_2017_09.html");
    //$qqtemplate = Pms_Template::createTemplate(array(), 'templates/qq_fileupload_template_2018_08.html');
    $this->headScript()->setAllowArbitraryAttributes(true)->appendScript($qqtemplate, 'text/template', array("id" => "qq-template", "noescape" => true));
    */
    
        $this->headScript()->appendFile( RES_FILE_PATH . '/javascript/livesearch/getzipcities.js' );
//         $this->headScript()->appendFile( RES_FILE_PATH . '/javascript/livesearch/gethealthinsurance.js' );
//         $this->headScript()->appendFile( RES_FILE_PATH . '/javascript/livesearch/getdiagnosisicd.js' );
//         $this->headScript()->appendFile( RES_FILE_PATH . '/javascript/livesearch/getfamilydoctor.js' );
//         $this->headScript()->appendFile( RES_FILE_PATH . '/javascript/livesearch/getspecialist.js' );
//         $this->headScript()->appendFile( RES_FILE_PATH . '/javascript/livesearch/getcareservice.js' );
//         $this->headScript()->appendFile( RES_FILE_PATH . '/javascript/livesearch/getsupplies.js' );
//         $this->headScript()->appendFile( RES_FILE_PATH . '/javascript/livesearch/getpharmacy.js' );
//         $this->headScript()->appendFile( RES_FILE_PATH . '/javascript/livesearch/getsuppliers.js' );
//         $this->headScript()->appendFile( RES_FILE_PATH . '/javascript/livesearch/gethomecare.js' );
//         $this->headScript()->appendFile( RES_FILE_PATH . '/javascript/livesearch/getphysiotherapists.js' );
//         $this->headScript()->appendFile( RES_FILE_PATH . '/javascript/livesearch/getvoluntaryworkers.js' );
//         $this->headScript()->appendFile( RES_FILE_PATH . '/javascript/livesearch/getchurches.js' );
//         $this->headScript()->appendFile( RES_FILE_PATH . '/javascript/livesearch/gethospiceassociation.js' );
//         $this->headScript()->appendFile( RES_FILE_PATH . '/javascript/livesearch/getremedysupplies.js' );
//         $this->headScript()->appendFile( RES_FILE_PATH . '/javascript/livesearch/getremedyaid.js' );
//         $this->headScript()->appendFile( RES_FILE_PATH . '/javascript/livesearch/getuservw.js' );
        $this->headScript()->appendFile( RES_FILE_PATH . '/javascript/livesearch/getsapvverordner.js' );
        
        $this->headScript()->appendFile( RES_FILE_PATH . '/javascript/pms/jquery.changeEventOrder.js' );
        
        
        // 		        $layout->getView()->headScript()->appendFile( APP_BASE . 'javascript/views/patient/patientdetails.js' );
    
        
        $this->headScript()->appendFile(RES_FILE_PATH.'/javascript/chosen_v1.6.2/chosen.jquery.min.js');
        $this->headLink()->appendStylesheet(RES_FILE_PATH.'/javascript/chosen_v1.6.2/chosen_2016.09.22.css');
        
        $this->headScript()->appendFile( RES_FILE_PATH . '/javascript/views/patientnew/patientdetails_box_patient_visits_settings.js' );
        
        
        //add file uploader
        $this->headScript()->appendFile(APP_BASE.'javascript/fine-uploader/fine-uploader.min.js');
        $this->headLink()->appendStylesheet(APP_BASE.'javascript/fine-uploader/fine-uploader.css');
        
        
        //rendered-add the fine-uploader file-uploader template
//         $qqtemplate = $this->render("templates/qq_fileupload_template_small_2018_08.html");
        $qqtemplate = Pms_Template::createTemplate(array(), 'templates/qq_fileupload_template_small_2018_08.html');
        $this->headScript()->setAllowArbitraryAttributes(true)->appendScript($qqtemplate, 'text/template', array("id" => "qq-template", "noescape" => true));
        
        
//modified by Carmen on 28.01.2020 for ISPC-2508     
//Ancuta added to Clinic ISPC (CISPC)  on 18.03.2020  
        
    
?>

<?php
$datas = $this->data;
$addresses = array();
$metaCategorys = array();

/*
 * addNew template for each box
 */

foreach ($datas['__meta-categorys'] as $cat => $data) {
    $this->headScript()->setAllowArbitraryAttributes(true)
    ->appendScript($data['addnewDialogHtml'] . PHP_EOL, 'text/template', array("id" => "{$cat}_addnewDialogHtml", "noescape" => true));
    
    unset($data['addnewDialogHtml']);
    
    if (isset($data['addnewDialogHtml_subForms'])) { 
        foreach ($data['addnewDialogHtml_subForms'] as $subcat => $subdata ) {
            $this->headScript()->setAllowArbitraryAttributes(true)
            ->appendScript($subdata . PHP_EOL, 'text/template', array("id" => "{$subcat}_addnewDialogHtml", "noescape" => true));
        }
        unset($data['addnewDialogHtml_subForms']);
    }
    
    unset($data['extract']);
    
    
    $metaCategorys[$cat] = $data;
}

/*
 * update template for each box entry
 */
foreach ($datas as $cat => $data) {
if($cat == 'PatientArtificialEntriesExits')
{ 
//print_r($data); exit;
}
    foreach ($data as $key=>$entry) {
        
        if (isset($entry['editDialogHtml'])){
            $this->headScript()->setAllowArbitraryAttributes(true)
            ->appendScript($entry['editDialogHtml'] . PHP_EOL, 'text/template', array("id" => "{$cat}_editDialogHtml_{$key}", "noescape" => true));            
        }
        
        if (isset($entry['editDialogHtml_extra'])){
        	$this->headScript()->setAllowArbitraryAttributes(true)
        	->appendScript($entry['editDialogHtml_extra'] . PHP_EOL, 'text/template', array("id" => "{$cat}_editDialogHtml_extra_{$key}", "noescape" => true));
        }
        //ISPC-2508 Carmen 20.05.2020 new design
        if (isset($entry['editDialogHtml_extra_remove'])){
        	$this->headScript()->setAllowArbitraryAttributes(true)
        	->appendScript($entry['editDialogHtml_extra_remove'] . PHP_EOL, 'text/template', array("id" => "{$cat}_editDialogHtml_extra_remove_{$key}", "noescape" => true));
        }
		//--
        if (isset($entry['editDialogHtml_subForms'])) {
            foreach ($entry['editDialogHtml_subForms'] as $subcat => $subdata ) {
                $this->headScript()->setAllowArbitraryAttributes(true)
                ->appendScript($subdata . PHP_EOL, 'text/template', array("id" => "{$subcat}_editDialogHtml", "noescape" => true));
            }
        }
        
        $addresses[$cat][$key] = $entry['address'];
    }    
}

?>


<script>
    var patientIsDischarged = <?=(int)$this->patientMasterData['isdischarged'];?>;
    var memos = <?=json_encode($this->memos);?>;
    var addresses = <?=json_encode($addresses);?>;
    var metaCategorys = <?=json_encode($metaCategorys);?>;

	var visits_settings_disabled_users = jQuery.parseJSON('<?php echo ($this->pat_visits_settings_disabled_users); ?>');
	var patientVisitsSettings = <?=json_encode($this->patientMasterData['PatientVisitsSettings']);?>;

    //ISPC-2539, elena, 29.10.2020
	var pat_id = '<?php echo $_GET['id'] ?>';

</script>

<!-- datapicker image -->
<div id="calImgs" style="display: none;">
    <img id="calImg" src="<?php echo RES_FILE_PATH; ?>/images/calendar.png" alt="Popup" class="trigger">
</div>


<!-- start  div#tab_container_provider -->
<div id="tab_container_provider" class="tab_container versorger">


<?php foreach ($this->boxesPlacement as $colid=>$colcats) :?>

    <!-- start  div#provider_<?=$colid?> -->
    <div id="provider_<?=$colid;?>" class="versorger-<?php echo $colid;?>">
        
    <?php foreach ($colcats as $cc) : ?>
    <?php $cat = $this->mappings[$cc]; $firstentry = 0;?>

        
        <?php 
            
            /*
             * set what boxes are opened and what closed
             */
            switch ($this->boxesOpened) {
                
                case "ALL_OPENED":
                
                    $disp='active';
                
                break;
                    
                case "ALL_CLOSED":
                    
                    $disp='inactive';
                    
                break;
                    
                case "ONLY_WITH_CONTENT":
                    
                    $with_data = array_filter($this->data[$cc], function ($item){
                        return ! empty($item['editDialogHtml']);
                    
                    });
                    //var_dump($this->data[$cc]);

                    if($this->data[$cc][0]['meta']['table'] == 'PatientMaster_Hospiz_Hospizverein_SAPV_AAPV' || ( ($cc == "Anamnese") &&  isset($data[$cc]['anamneseDataExists']))) //<!-- TODO-3848,Elena,11.02.2021 -->
                    {
                    	$disp="active";
                    }
                    elseif(count($with_data)>0 && $with_data[1]['editDialogHtml'] !="[") {
                        $disp="active"; 
                    } else {
                        $disp='inactive';
                    }
                    
                break;
                    
                default:
//                     dd("sssssssss", $cat['extra_form_ID'], $this->boxesOpened);
                    if (in_array($cat['extra_form_ID'], $this->boxesOpened)) {
                        $disp="active";
                    } else {
                        $disp='inactive';
                    }
                break;
            }
            
            
        ?>
            
            
    <!-- start box -->    
    <div id="box-<?php echo $cc;?>" class="catdetails">
        <!-- start box header -->  
        <div class="versorger-catheader <?php echo $disp;?>">
            <div class="headtitle"><?php echo $cat['label'];?></div>
            <div class="headtitle-img dontPrint">
                <?php if(isset($this->memos[$cc]) && $this->memos[$cc]['color']=="green"):?>
                <img src="<? echo RES_FILE_PATH;?>/images/circle_green24.png">
                <?php endif;?>
                <?php if(isset($this->memos[$cc]) && $this->memos[$cc]['color']=="red"):?>
                    <img src="<? echo RES_FILE_PATH;?>/images/circle_red24.png">
                <?php endif;?>
            </div>
        </div>
        <!-- end box header --> 
        <!-- start box body --> 
        <div class="entries" <?=($disp=='inactive') ? "style='display:none;'" : "";?>>
            <?php //ISPC-2694, elena, 07.01.2021 ?>
            <?php if($cc == 'Anamnese') : ?>
            <div class="entry_anamnese">

            <?php  echo($data[$cc]['addDataHTML']); ?>

            </div>
            <?php endif; ?>

            <input type="hidden" class="category" value="<?php echo $cc;?>">

            <?php foreach ($this->data[$cc] as $key => $entry): ?>
                
                <?php
                // ! this IF has a continue  
                if ($entry['meta']['inlineEdit'] == true):
                ?>
                <!-- inline edit -->
                <div class="entry">
                    <input type="hidden" class="hidden-json-data" value='<?=$key;?>'>
                    <?php
                    $first = reset($entry['extract']);
                    echo ($first[1]);
                    ?>
                </div>
                
                <div class="dontPrint">
                    <span class="ibutton memobutton"><img src="<? echo RES_FILE_PATH;?>/images/edit-icon.gif"> <?=$this->translate("Memo")?></span>
                    <?php if ($entry['meta']['hasHistory']) : ?>
                    <span class="ibutton historybutton"><img src="<? echo RES_FILE_PATH;?>/images/history.png"> <?=$this->translate("History")?></span>
                    <?php endif; ?>
                </div>
            
            </div>
            </div>
                <?php 
                continue 2;        
                endif;
                ?>
                
                <?php if (empty($entry['editDialogHtml'])) continue;?>

               	<?php if ( $cc == "PatientArtificialEntriesExits" && $entry['extract'][0][1] == 'justNotEmpty') {$firstentry = 1; continue;} ?>
               	
                <div class="entry">
                <?php if ( $cc == "PatientArtificialEntriesExits" && $entry['extract'][0][1] != 'justNotEmpty' && $firstentry == 0) echo '<div class="artificial_title">'. $this->translate('artificial_entries') . '</div>';?>
                <?php if ( $cc == "PatientArtificialEntriesExits" && $entry['extract'][0][1] != 'justNotEmpty' && $firstentry == 1) echo '<div class="artificial_title">'. $this->translate('artificial_exits') . '</div>'; ?>
                    <?php foreach($entry['extract'] as $row):?>
                        <div class="entryline">
                            <?php if ( ! empty($row[0])) : ?>
                            <label><?=$row[0]?></label> 
                            <?php endif; ?>
                            
                            <span class="entrydetail">
                                <?php if ($entry['meta']['extractEscape'] === false ): ?>
                                    	<?= $row[1];?>
                                <?php elseif($row[0] == 'Email Adresse' && strpos($row[1], '@') > 0) : ?>
                                    <?php //if not encrypted, otherwise has no sense // ISPC-2633: Clickable e-mail-link, elena, 14.08.2020 ?>
                                    <a href="mailto:<?php echo $row[1] ?>"><?php echo $row[1] ?></a>
                                <?php else :?>
                                    <?= nl2br($this->escape($row[1]));?>
                                <?php endif;?>
                            </span>
                        </div>
                    <?php endforeach; $firstentry = 1;?>
                   
                   <!-- ISPC-2400 --> 
                 <?php if ($entry['meta']['hideDetails'] != true ): ?> 	
                    <input type="hidden" class="hidden-json-data" value='<?=$key;?>'>
                     <div class="info-button"><img src="<? echo RES_FILE_PATH;?>/images/info_med.png"><span> Details</span></div><!-- //ISPC-2703, elena, 04.01.2021 -->
                 <?php endif;?>
                                
                  <!--    <input type="hidden" class="hidden-json-data" value='<?=$key;?>'>
                    <div class="info-button"><img src="<? echo RES_FILE_PATH;?>/images/info_med.png"> Details</div>
                  -->
                </div>
                
                
            <?php endforeach;?>

            <?php
            $style="";
            
            if ( ! $cat['multipleEntries'] && ! empty($this->data[$cc][0]['editDialogHtml'])) {
                $style='style="display:none;"';
            }
            
            ?>
                <div class="dontPrint">
                   <!-- ISPC-2400 --> 
                 <?php if ($entry['meta']['notaddnew'] != true ): ?> 	
                 
                    <!-- ISPC-2801 Ancuta 18.01.2021 -->
                 	<?php if ( $cc == "MePatientDevices") :?>
                    	<span <?php echo $style;?> class="ibutton addbutton"><img src="<? echo RES_FILE_PATH;?>/images/btttt_plus.png"><?php echo $this->translate('[mePatient add_edit devices]')?></span>
                 	<?php else:?>
                    	<span <?php echo $style;?> class="ibutton addbutton"><img src="<? echo RES_FILE_PATH;?>/images/btttt_plus.png"> <?php echo $cat['label'];?> hinzufügen</span>
                 	<?php endif;?>
                 
                 <?php endif;?>
                     
                
                   <!--  <span <?php echo $style;?> class="ibutton addbutton"><img src="<? echo RES_FILE_PATH;?>/images/btttt_plus.png"> <?php echo $cat['label'];?> hinzufügen</span>
                     -->
                     <span class="ibutton memobutton"><img src="<? echo RES_FILE_PATH;?>/images/edit-icon.gif"> <?=$this->translate("Memo")?></span>
                    <?php if ($entry['meta']['hasHistory']) : ?>
                    <span class="ibutton historybutton"><img src="<? echo RES_FILE_PATH;?>/images/history.png"> <?=$this->translate("History")?></span>
                    <?php endif; ?>
                    
                    <!-- ISPC-2432 Ancuta 12.03.2020 -->
					<?php if ( $cc == "MePatientDevicesNotifications" && !empty($this->data['MePatientDevices'][0]['editDialogHtml'])) :?>
	                    <span class="ibutton send_now_button"><img src="<? echo RES_FILE_PATH;?>/images/triangle_green-ipadd.png"> <?=$this->translate("send_push_notification")?></span>
                    <?php endif; ?>
                    <!--  // -->
                </div>
            
        </div>
        </div>
    
    
    <?php 
        endforeach;
        /*
         * end foreach ($colcats as $cc)
         */
    ?>
    </div>
    <!-- end  div#provider_<?=$colid?> -->
    
<?php 
endforeach;
/*
 * end foreach ($this->boxesPlacement as $colid=>$colcats)
 */
?>

</div>
<!-- end div#tab_container_provider-->


<div class="clearer"></div>

<a href="patientnew/patientdetails?id=<?=$this->encid?>&__action=patientdetailsToPrint" target="_blank" class="dontPrint"><img src="images/print.gif"></a> 
<a href="patientnew/patientdetails?id=<?=$this->encid?>&__action=patientdetailsToPDF" target="_blank" class="dontPrint"><img src="images/doc_pdf.png"></a>
<a class="dontPrint allhistorybutton" title="<?=$this->translate("History")?>"><img src="<? echo RES_FILE_PATH;?>/images/history.png"> </a>

<!-- start dialog versorger-entryeditor -->
<div id="versorger-entryeditor" style="display: none">
    <form class="wlassessment_form_class livesearchFormEvents">
        <div class="content"></div>
        <!-- 
        <div class="toolbar">
            <input type="button" class="clipboard-button" value="Adresse kopieren">
            <input style="padding:1px;" type="button" class="delbutton" value="Eintrag entfernen">
            <input style="float:right;" type="submit" class="savebutton" value="Übernehmen">
        </div>
         -->
    </form>
</div>
<!-- start dialog versorger-clipboardcopy -->
<div id="versorger-clipboardcopy" style="display: none">
    <textarea></textarea>
</div>
<!-- start dialog versorger-memo -->
<div id="versorger-memo" style="display: none">
    <form>
        <input type="hidden" name="__category" value="">
        <div style="width:200px;display:inline-block;margin-right:8px;">
            <textarea name="memo" style="height:80px;width:200px;"></textarea>
        </div>
        <div style="width:150px;display:inline-block;">
            <ul>
                <li><input name="color" value="none" type="radio"><?=$this->translate('no light');?></li>
                <li><input name="color" value="green" type="radio"><?=$this->translate('green light');?> (<img style="width:16px;vertical-align:bottom;" src="<? echo RES_FILE_PATH;?>/images/circle_green24.png">)</li>
                <li><input name="color" value="red" type="radio"><?=$this->translate('red light');?> (<img style="width:16px;vertical-align:bottom;" src="<? echo RES_FILE_PATH;?>/images/circle_red24.png">)</li>
            </ul>
        </div>
        <div style="margin-top:4px;padding:4px;text-align:center;">
            <input type="button" class="versorger-memo-button" value="<?=$this->translate('save changes')?>">
        </div>
    </form>
</div>
<!-- ISPC-2432 Ancuta 21.01.2020 START  -->
<div id="qr_device_modal" style="display: none">
	<form class="wlassessment_form_class livesearchFormEvents" id="form_activate_device">
    	<div class="content">
    		<div>
    			<fieldset class="label_same_size">
    				<legend><?php echo $this->translate('mePatient_activate_device')?></legend>
                    <table width="100%">
                    	<tr>
                    		<td>
                    			<label><?php echo $this->translate('mePatient_device_name')?></label>
                    		</td>
                    		<td >
                    		<h4 id="device_name"></h4>
                    		</td>
                    	</tr>
                    	<tr>
                    		<td colspan="2" align="center">
                    			<div class="qr_code" style="width:100%; text-align: center; ">
                    				<img id="QrcodeImg" src="<?php echo RES_FILE_PATH; ?>/images/loader_transparent.gif" >
                    			</div>
                    			<!-- ISPC-2432 Carmen 04.06.2020 <button id="refreshQr" date-device_id ="" style="display: none"><?php //echo $this->translate('refresh')?></button> -->
                    		</td>
                    	</tr>
                    	<tr>
                    		<td>
                    			<label><?php echo $this->translate('mePatient_activation_code')?></label>
                    		</td>
                    		<td colspan="2">
                    		<input type="hidden" name="device_id" value="" id="device_id" />
                    		<input type="hidden" name="device_internal_id" value="" id="device_internal_id" />
                    		<input type="text" name="activation_code" value="" id="activation_code" />
                    		</td>
                    	</tr>
                    	<tr>
                    		<td rowspan="2">
                    			<label><?php echo $this->translate('mePatient_device_password')?></label>
                    		</td>
                    		<td colspan="2">
                    			<input type="text" name="device_password" value=""  id="device_password" />
                    		</td>
                    	</tr>
                    	<tr>
                    		<td colspan="2">
                    		<span style="width:50%;" id="device_error"></span>
                    		</td>
                    	</tr>
                    	
                    </table>
    			</fieldset>
    		</div>
    	</div>
	</form>
</div>	
<div id="send_push_modal" style="display: none">
	<form class="wlassessment_form_class livesearchFormEvents" id="send_push_notifications">
    	<div class="content">
    		<div>
    			<fieldset class="label_same_size">
    				<legend><?php echo $this->translate('send_push_notifications')?></legend>
                    <table width="100%">
                    	<tr>
                    		<td width="20%">
                    			<label><?php echo $this->translate('push_comment')?></label>
                    		</td>
                    		<td width="80%">
                    		<textarea name="push_comment" id="push_comment" rows="" cols="" style="width:100%"></textarea>
                    		</td>
                    	</tr>
             
                    </table>
    			</fieldset>
    		</div>
    	</div>
	</form>
</div>