<?php 
//ISPC-2508 Carmen 20.01.2020
/* $this->headScript()->appendFile(RES_FILE_PATH.'/javascript/data_tables/jquery.dataTables.js?'.date('Ymd'));
$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/data_tables/dataTables.jqueryui.js?'.date('Ymd'));
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/data_tables/dataTables.jqueryui.css?' . date('Ymd')); */
?>

<style>
#table_exit th, #table_exitmodal th {
		color: #000 !important;
		background: #f2f2f2 !important;
		border-bottom-left-radius: 0px !important;
		border-bottom-right-radius: 0px !important;
		border: 1px solid #bbb;
}
#table_exit, #table_exitmodal {
	word-break: break-all;
	font-size: 11px;
}

.showalertage {
  visibility: visible;
}
.hidealertage {
  visibility: hidden;
}
</style>
<script>
	var langurl = appbase + 'javascript/data_tables/de_language.json';
	var tablesource_exits = <?php echo json_encode($this->patient_artificial_exits); ?>;
	var openfrom = '<?php echo $this->openfrom; ?>';
	$(function() {
	$('#table_exit'+openfrom).DataTable({
		// ADD language
		 "language": {
               "url": langurl
        },

		"sDom"://'<"fg-toolbar ui-toolbar ui-widget-header ui-helper-clearfix ui-corner-tl ui-corner-tr"lfr>'+
			't',//+
			//'<"fg-toolbar ui-toolbar ui-widget-header ui-helper-clearfix ui-corner-bl ui-corner-br"<"#bottom_export">lip>',
		// la sDom - este sa zic - declarat tablelu(t) - cu header - search, paginare(p)

			
		//"lengthMenu": [[5, 25, 50, 100], [5, 25, 50, 100]],
			
		"processing": true,

		"info": false,
		"filter": false,
		"paginate": false,
		"destroy": true,

		//"serverSide": true,
		"autoWidth": false,
		"stateSave": false,
		"scrollX": false,
		"scrollCollapse": true,
		
		//"sAjaxSource" : window.location.href,
		"data": tablesource_exits,
		
		/* "fnServerData" : function(sSource, aoData, fnCallback, oSettings) {

			if (oSettings.jqXHR) {
				oSettings.jqXHR.abort();
			}
			
			var _sorting = oSettings.aaSorting[0];		
			
			aoData.push({
				"name" : "length",
				"value" : oSettings._iDisplayLength
			});
			aoData.push({
				"name" : "start",
				"value" : oSettings._iDisplayStart
			});

			oSettings.jqXHR = $.ajax({
				"dataType" : 'json',
				"type" : "POST",
				"url" : sSource,
				"data" : aoData,
				"success" : fnCallback
			});
		}, */
		
		"columns": [
		          {
		        	  title: translate('artificial_option_name'),
		        	  data: "option_name",
		        	  className: "",
		        	  "width": "75px"
		          },
		          {
		        	  title: translate('artificial_option_date'),
		        	  data: "option_date",
		        	  className: "",
		        	  "width": "60px"
		          },
		          {
		        	  title: translate('artificial_option_localization'),
		        	  data: "option_localization",
		        	  className: "",
		        	  "width": "100px"
		          },
		          {
		        	  title: translate('artificial_option_age'),
		        	  data: "option_age",
		        	  className: "",
		        	  "width": "65px"
		          },
		          {
		        	  title: translate('actions'),
		        	  data: "actions",
		        	  className: "",
		        	  "width": "52px"
		          }
			],
			
		"columnDefs": [
		          { "targets": -1, "searchable": false, "orderable": false},
				],
		"order": [[0, "asc"]],
		
	});

	});	
	
</script>

<table id="table_exit<?php echo $this->openfrom; ?>"></table>

