<!--  Maria:: Migration CISPC to ISPC 22.07.2020 -->


<!-- ###########  BOX 101 Patient Case Status ############ -->
					<div  id="grow101" class="patientdragbox-content">
						<div class="curent_status_info">
							<b><?php echo $this->translate('current_status:'); ?></b>
							<?php if($this->isstandby):  ?>
								<span id="fdoc_message"> <?php echo $this->translate('standby'); ?></span>
							<?php elseif($this->isstandbydelete):  ?>
								<span id="fdoc_message"> <?php echo $this->translate('standby_deleted'); ?></span>
							<?php elseif($this->isdischarged == "1"):  ?>
								<span id="fdoc_message black"> <?php echo $this->translate('isdischarged'); ?></span>
							<?php else:  ?>
								<span id="fdoc_message black"> <?php echo $this->translate('isactive'); ?></span>
							<?php endif;  ?>
						</div>
                        <div id="PtDetails_first" class="dtbox">


                        <?php //Display only clinic cases for clinic clients?>
                            <style>
                                #clinic_cases_status_table td{
                                    padding:1px;
                                }
                            </style>
                            <h4>klinische Fälle</h4>
                            <table id="clinic_cases_status_table" style="width:340px;">
                                <tr>
                                    <th style="width:15%;font-weight:bold;">Art</th>
                                    <th style="width:25%;font-weight:bold;">Fall-Nr.</th>
                                    <th style="width:30%;font-weight:bold;">Start</th>
                                    <th style="width:30%;font-weight:bold;">Ende</th>
                                </tr>
                                <?php foreach ($this->clinic_cases as $case):?>
                                    <?php
                                    $open_case_class="";
                                    if (strtotime($case['disdate']) < 10) {
                                        $open_case_class="style='background-color:#a8e465;' ";
                                    }
                                    ?>
                                    <tr <?php echo $open_case_class;?>>
                                        <td><a href="patient/patientcasestatus?id=<?php echo $this->encid;?>"><?php echo $case['case_type'];?></a></td>
                                        <td><a href="patient/patientcasestatus?id=<?php echo $this->encid;?>"><?php echo $case['case_number'];?></a></td>
                                        <td><a href="patient/patientcasestatus?id=<?php echo $this->encid;?>"><?php if(strtotime($case['admdate'])<10){echo "-";}else{echo date("d.m.Y",strtotime($case['admdate']));}?></a></td>
                                        <td><a href="patient/patientcasestatus?id=<?php echo $this->encid;?>"><?php if(strtotime($case['disdate'])<10){echo "-";}else{echo date("d.m.Y",strtotime($case['disdate']));}?></a></td>
                                    </tr>
                                <?php endforeach;?>
                            </table>
                        <br>
                        <div class="dontPrint">
                            <a href="patient/patientops?id=<?php echo $this->encid;?>">
                                <span class="ibutton">
                                    <img style="width:16px;" src="<?php echo RES_FILE_PATH;  ?>/images/link.png">
                                    zum Zeitmanagement / OPS</span>
                            </a>
                        </div>

                        </div>
						<div class="clearer"></div>
					</div>
			
	
	
