	<!-- ###########  System Sync  ############ -->
<script type="text/javascript">
			$('document').ready(function(){
			$("#grow46 .dtbox").load('Systemssync/patientinfo?patid=<?php echo $this->patid2;?>&versorger_or_stammdaten=<?=$this->versorger_or_stammdaten?>');
		});
</script>
	<div id="grow46" class="patientdragbox-content dontPrint">
		<div id="PtDetails_second" class="dtbox">
		</div>
		<div class="clearer"></div>
	</div>
