<h1>THIS PAGE IS FOR TESTING PURPOSE ONLY, and will be removed</h1>
<fieldset>
<legend><?php echo $this->translate('Elvi User Login');?></legend>

<label><?php echo $this->translate('Please click the button to login into you Elvi account');?> </label>
<?php
    //login to user elvi room
    echo $this->formButton('elvi_user_login', 'elvi_user_login' , array('onclick' => 'elvi_login_user(event)'));
?>
</fieldset>



<fieldset>
<legend><?php echo $this->translate('Elvi Perform Action');?></legend>

<?php 
    $ea = "ElviTransactionsTable.action";
    echo $this->formSelect('action', '', array(), $this->$ea);

    echo $this->formButton("perform_action", "SUBMIT", array('id'=>'DEV_perform_action', 'onClick' => 'elviroom_user_login(this)'));

    echo "<br/><br/> RESULT: <br/>";
    echo $this->formTextarea("debug_elvi", "");
?>



</fieldset>



<!-- 
<fieldset>
<legend><?php echo $this->translate('Behandelt durch Patients');?></legend>

<?php
    //get list with patients, and with active tokens
    echo $this->formButton('elvi_user_login', 'elvi_user_login' , array('onclick' => 'elvi_login_user(event)'));
?>
</fieldset>
 -->

<div id='elvi_user_placeholder'>
Please wait to login ...
elvi_user_placeholder for the iframe
</div>
<?php //die('sss' . __METHOD__ . ' ' .__LINE__); ?>
