<?php 
//ISPC-2654 Lore 05.10.2020

$this->headLink()->appendStylesheet(RES_FILE_PATH.'/css/color_picker/colorpicker.css');
$this->headLink()->appendStylesheet(RES_FILE_PATH.'/css/color_picker/layout.css');
$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/colorpicker/colorpicker.js');
$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/colorpicker/eye.js');
$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/colorpicker/utils.js');

?>

<!-- inline script -->
<script type="text/javascript">
$(document).ready(function()
		{
			$('#colorSelector').ColorPicker({
				color: $('#color').val(),
				
				onShow: function (colpkr) {
					$(colpkr).fadeIn(500);
					return false;
				},
				onHide: function (colpkr) {
					$(colpkr).fadeOut(500);
					return false;
				},
				onChange: function (hsb, hex, rgb) {
					$('#color').val(hex);
					$('#colorSelector div').css('background-color:', '#' + hex);
			        var el = $(this).data('colorpicker').el;
			        $(el).css('backgroundColor', '#' + hex).val('#' + hex);
				}
			});

			//$('#colorSelector div').css('background-color:', '#00cdff');

		});
</script>


<div style="clear:both"></div>

<?php if (count($this->SuccessMessages)) : ?>
<!--  SuccessMessages -->
    <ul id="messages" class="success">
    <?php foreach ($this->SuccessMessages as $message) : ?>
        <li><?php echo $this->escape($message); ?></li>
    <?php endforeach; ?>
    </ul>
<?php endif; ?>


<?php if (count($this->ErrorMessages)) : ?>
<!--  ErrorMessages -->
    <ul id="messages" class="err">
    <?php foreach ($this->ErrorMessages as $message) : ?>
        <li><?php echo $this->escape($message); ?></li>
    <?php endforeach; ?>
    </ul>
<?php endif; ?>

<a href="<?php echo $this->url(array('controller'=>'clientlists' , 'action' => 'icdopsmresettingslist')) ;?>"><?php echo $this->translate("back")?></a>

<?php
    //echo the form

    $this->form
    ->setAction($this->url())
    ->setMethod(Zend_Form::METHOD_POST)
    ->setAttrib('novalidate', true) // this form is not html5 friendly.. it has closed accordions
    ->setAttrib('autocomplete', false) // this form is not html5 friendly.. it has closed accordions
    ->setAttrib("id", "icdopsmre")
    ->setAttrib("class", "form_class");
   // ->setAttrib("onsubmit", "return form_submit_validate();");
        


    echo $this->form;
?>

