<?php
//ISPC-2654 Lore 05.10.2020

$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/data_tables/jquery.dataTables.js?'.date('Ymd'));
$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/data_tables/dataTables.jqueryui.js?'.date('Ymd'));
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/data_tables/dataTables.jqueryui.css?' . date('Ymd'));
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/page-css/listscommon.css?' . date('Ymd'));

$this->headLink()->appendStylesheet(RES_FILE_PATH.'/css/color_picker/colorpicker.css');
$this->headLink()->appendStylesheet(RES_FILE_PATH.'/css/color_picker/layout.css');
$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/colorpicker/colorpicker.js');
$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/colorpicker/eye.js');
$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/colorpicker/utils.js');

$ioms_sort_arr = $this->ioms_sort_arr;
?>


<br/>
 <h1><? echo $this->translate('icd_ops_mre_settings_list') ?></h1>
<br/>
<div class="add_link">
<!-- 	<a href="<?php echo $this->url(array('controller'=>'clientlists' , 'action' => 'icdopsmresettingsadd' )); ?>"><? echo $this->translate('icd_ops_mre_settings_edit'); ?></a>
 -->
</div>
<div style="clear:both;"></div>
<div id="addfamilydoctor_Msgerror" class="err"><? echo urldecode($_GET['mes']); ?></div>	
<table id="table" class="table table-striped table-bordered table-hover table-condensed dataTable no-footer  left_menu_datatable">
 </table>	


<br/>
<br/>
<br/>
<br/>



 <h1><? echo $this->translate('icd_ops_mre_sorting_list') ?></h1>
<br/>
 
 <?php foreach($ioms_sort_arr as $k=>$vals_sort) :?>
	<?php echo "<span style='font-weight: bold;padding-right:57px;line-height: 1.6;'>".$this->translate('main_sort_col').": "."</span>".$vals_sort['main_sort_col'];?>
	<br/>
	<?php echo "<span style='font-weight: bold;padding-right:50px;line-height: 1.6;'>".$this->translate('secondary_sort_col').": "."</span>".$vals_sort['secondary_sort_col']."<span style='font-weight: bold;padding-right:120px;line-height: 1.6;'></span>".$vals_sort['actions'];?>
	<br/>
	<?php echo "<span style='font-weight: bold;padding-right:83px;line-height: 1.6;'>".$this->translate('sort_order').": "."</span>".$vals_sort['sort_order'];?>
	<br><br/>
 <?php endforeach;?>	
 
 <br/>
 <div class="add_link">
<!--	<a href="<?php echo $this->url(array('controller'=>'clientlists' , 'action' => 'icdopsmresortingadd' )); ?>"><? echo $this->translate('icd_ops_mre_sorting_add'); ?></a>
 -->
 </div>
<div style="clear:both;"></div>
<div id="addfamilydoctor_Msgerror" class="err"><? echo urldecode($_GET['mes']); ?></div>