<?php 
// Maria:: Migration ISPC to CISPC 08.08.2020 
//ISPC-2520 Lore 08.04.2020
?>

<!-- inline script -->
<script type="text/javascript" >

</script>


<div style="clear:both"></div>

<?php if (count($this->SuccessMessages)) : ?>
<!--  SuccessMessages -->
    <ul id="messages" class="success">
    <?php foreach ($this->SuccessMessages as $message) : ?>
        <li><?php echo $this->escape($message); ?></li>
    <?php endforeach; ?>
    </ul>
<?php endif; ?>


<?php if (count($this->ErrorMessages)) : ?>
<!--  ErrorMessages -->
    <ul id="messages" class="err">
    <?php foreach ($this->ErrorMessages as $message) : ?>
        <li><?php echo $this->escape($message); ?></li>
    <?php endforeach; ?>
    </ul>
<?php endif; ?>

<a href="<?php echo $this->url(array('controller'=>'clientlists' , 'action' => 'organicentriesexitslist')) ;?>"><?php echo $this->translate("back")?></a>

<?php
    //echo the form

    $this->form
    ->setAction($this->url())
    ->setMethod(Zend_Form::METHOD_POST)
    ->setAttrib('novalidate', true) // this form is not html5 friendly.. it has closed accordions
    ->setAttrib('autocomplete', false) // this form is not html5 friendly.. it has closed accordions
    ->setAttrib("id", "orgentext")
    ->setAttrib("class", "form_class");
   // ->setAttrib("onsubmit", "return form_submit_validate();");
        


    echo $this->form;
?>

