<!--  Maria:: Migration CISPC to ISPC 22.07.2020 -->
<?php 
// ISPC-2625, AOK Kurzassessment, 06.07.2020, elena
//css append
$this->headLink()
    ->appendStylesheet(RES_FILE_PATH . '/css/page-css/wlassessment.css')
    ->appendStylesheet(RES_FILE_PATH . '/css/page-css/mamboassessment.css')
    //qtip
    ->appendStylesheet(RES_FILE_PATH . '/css/qtip/jquery.qtip.min.css', ['media' => "screen"])
    //add file uploader
    ->appendStylesheet(APP_BASE.'javascript/fine-uploader/fine-uploader.css')
    
;

//js append
$this->headScript()
    ->appendFile(RES_FILE_PATH . '/javascript/dateUtil.js')
    ->appendFile(RES_FILE_PATH . '/javascript/qtip/jquery.qtip.min.js')
    ->appendFile(APP_BASE.'javascript/fine-uploader/fine-uploader.min.js')
    ->appendFile(APP_BASE.'javascript/number_format.js')
;


//rendered-add the fine-uploader file-uploader template
$qqtemplate = $this->render("templates/qq_fileupload_template_small_2018_08.html");
//$qqtemplate = Pms_Template::createTemplate(array(), 'templates/qq_fileupload_template_2018_08.html');
$this->headScript()->setAllowArbitraryAttributes(true)->appendScript($qqtemplate, 'text/template', array("id" => "qq-template", "noescape" => true));


    //medication-II
//TODO: add the syles
    $this->headScript()
        ->appendFile(RES_FILE_PATH.'/javascript/views/patientnew/medicationeditblocks.js')
        ->appendFile(RES_FILE_PATH.'/javascript/jquery.tablesorter.js')
		->appendFile(RES_FILE_PATH.'/javascript/pharmaindex/medi_pharmaindex.js');    
	$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/medicationnew_edit.css');
	$this->headLink()->appendStylesheet(RES_FILE_PATH.'/css/pharmaindex/medi_pharmaindex.css?'.date('Ymd'));


    //wounddocumentation
    $this->headScript()->appendFile(RES_FILE_PATH . '/javascript/human_body/multi.js');
//    $this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/page-css/wounddocumentation.css');

    //humanbody.js
    $this->headScript()
    ->appendFile(RES_FILE_PATH.'/javascript/views/patientformnew/humanbody.js')
    
    //add livesearch
    ->appendFile( RES_FILE_PATH . '/javascript/livesearch/getzipcities.js' )
    ->appendFile( RES_FILE_PATH . '/javascript/livesearch/gethealthinsurance.js' )
    ->appendFile( RES_FILE_PATH . '/javascript/livesearch/getdiagnosisicd.js' )
    ->appendFile( RES_FILE_PATH . '/javascript/livesearch/getfamilydoctor.js' )
    ->appendFile( RES_FILE_PATH . '/javascript/livesearch/getspecialist.js' )
    ->appendFile( RES_FILE_PATH . '/javascript/livesearch/getcareservice.js' )
//     ->appendFile( RES_FILE_PATH . '/javascript/livesearch/getsupplies.js' )
//     ->appendFile( RES_FILE_PATH . '/javascript/livesearch/getpharmacy.js' )
//     ->appendFile( RES_FILE_PATH . '/javascript/livesearch/getsuppliers.js' )
//     ->appendFile( RES_FILE_PATH . '/javascript/livesearch/gethomecare.js' )
//     ->appendFile( RES_FILE_PATH . '/javascript/livesearch/getphysiotherapists.js' )
//     ->appendFile( RES_FILE_PATH . '/javascript/livesearch/getvoluntaryworkers.js' )
//     ->appendFile( RES_FILE_PATH . '/javascript/livesearch/getchurches.js' )
//     ->appendFile( RES_FILE_PATH . '/javascript/livesearch/gethospiceassociation.js' )
//     ->appendFile( RES_FILE_PATH . '/javascript/livesearch/getremedysupplies.js' )
//     ->appendFile( RES_FILE_PATH . '/javascript/livesearch/getremedyaid.js' );
//     ->appendFile( RES_FILE_PATH . '/javascript/livesearch/getsapvverordner.js' )
    ->appendFile( RES_FILE_PATH . '/javascript/livesearch/getunifiedprovider.js' )
    ;   
?>



<?php
    //echo the form

    $this->form
    ->setAction($this->url() . "?id=" . $this->enc_id)
    ->setMethod(Zend_Form::METHOD_POST)
    ->setAttrib('novalidate', true) // this form is not html5 friendly.. it has closed accordions
    ->setAttrib('autocomplete', false) // this form is not html5 friendly.. it has closed accordions
    ->setAttrib("id", "wlassessment_form")
    ->setAttrib("class", "wlassessment_form_class livesearchFormEvents mambo_assessment_form_class")
    ->setAttrib("onsubmit", "return form_submit_validate();");
        


    echo $this->form;
?>

<!-- cloned to display inside a dialog  -->
<div style="display:none">
<?=$this->formSelect("usertodos", null, array(
    "id" => "todo_selectbox",
    "class" => "todo_selectbox",
	"multiple" => true,
	"size" => 1,
    'data-type' => 'userstodo',
	"disable" => array("0"),
	//"onchange" => "",
    ),
	$this->usersnewtodos
);
?>					
</div>



<!-- datapicker image -->
<div id="calImgs" style="display: none;">
    <img id="calImg" src="<?php echo RES_FILE_PATH; ?>/images/calendar.png" alt="Popup" class="trigger">
</div>
