<html>
    <head>
        <link href="<?=$this->app_path?>/../public/css/page-css/wlassessment_pdf.css" rel="stylesheet" type="text/css" />  
        <link href="<?=$this->app_path?>/../public/css/page-css/mambo_assessment_pdf.css" rel="stylesheet" type="text/css" />  
        <style>
            @page { margin: 20px 20px 60px 40px; }
        </style>                
    </head>
    
    <body class='wlassessment_form_class'>
       
        <div id="content">
        
        <?=$this->mambo_assessment_form;?>    

        </div>                                
    </body>
</html>
<?php if ( ! 1 ) : ?>
<!-- 
//Example: to user header and footer in html using counters
//example is not used in our fn
 $wlassessmentHead_with_counters = <<<EOT
<html>
    <head>
        <link href="%s/../public/css/page-css/wlassessment_pdf.css" rel="stylesheet" type="text/css" />  
        <style>
            @page { margin: 20px 20px 50px 20px; }
            #header { 
                position: fixed; 
                left: 0px; 
                top: -50px; 
                right: 0px; 
                height: 0px; 
                text-align: center;
            }
            #footer { 
                position: fixed; 
                left: 0px; 
                bottom: -50px; 
                right: 0px; 
                height: 40px; 
                text-align: center; 
                font-size:10px;
            }
            #footer .page:after { content: counter(page, decimal); }
        </style>                
    </head>
    <body class='wlassessment_form_class'>
        <div id="header">
        </div>
        <div id="footer"> 
            Seite: <span class="page"></span> | Datum: {$today_date} | {$nice_name_epid} 
        </div>
        <div id="content"> 
EOT;
 -->
 <?php endif; ?>