<?php
$patientMasterData = $this->{'patientMasterData'};
$enc_id = $this->enc_id;
$ControllerName = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$ActionName =  Zend_Controller_Front::getInstance()->getRequest()->getActionName();


//dd($this->{'patient.navigation.array'});

$this->placeholder('patient.navigation')->captureStart();

$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/views/templates/placeholderPatientNavigation.js');

?>
<!-- start  placeholder.patient.navigation -->

<div class="buttonbar smallbuttons" id="placeholder.patient.navigation">
    <a href="<?=APP_BASE?>patientcourse/patientcourse?id=<?=$enc_id;?>" class="btnBigBlue verlauf <?="{$ControllerName}/{$ActionName}" == "patientcourse/patientcourse" ? 'active' : ''?>">Verlauf</a>
    <a href="<?=APP_BASE?>patientform/contactform?id=<?=$enc_id;?>" class="btnBigBlue besuch <?="{$ControllerName}/{$ActionName}" == "patientform/contactform" ? 'active' : ''?>">Besuch</a>
    <!-- <a href="<?=APP_BASE?>patientnew/medication?id=<?=$enc_id;?>" class="btnBigBlue medikation <?="{$ControllerName}/{$ActionName}" == "patientnew/medication" ? 'active' : ''?>">Medikation</a> -->
    <a href="<?=APP_BASE?>patientmedication/overview?id=<?=$enc_id;?>" class="btnBigBlue medikation <?="{$ControllerName}/{$ActionName}" == "patientnew/medication" ? 'active' : ''?>">Medikation</a>
    <a href="<?=APP_BASE?>patient/patientfileupload?id=<?=$enc_id;?>" class="btnBigBlue datein <?="{$ControllerName}/{$ActionName}" == "patient/patientfileupload" ? 'active' : ''?>">Datein</a>
</div>

<!-- end  placeholder.patient.navigation -->
<?php $this->placeholder('patient.navigation')->captureEnd() ?>