<?php 
$patientMasterData = $this->{'patientMasterData'};
$system_icon_data = $patientMasterData['system_icon_data'];
$system_icon_details = $patientMasterData['system_icon_details'];

$patient_sys_icons = $patientMasterData['patient_sys_icons'];
$patient_icons_details = $patientMasterData['patient_icons_details'];
$custom_icon_details = $patientMasterData['custom_icon_details'];

$btm_perm = $patientMasterData['btm_perm'];
$has_btm_permission = $patientMasterData['has_btm_permission'];
$diagno_act_module = $patientMasterData['diagno_act_module'];
$death_date = $patientMasterData['death_date'];
$nr = $patientMasterData['nr'];
$show_debtor_number = $patientMasterData['show_debtor_number'];
$protected_patientMasterData = $patientMasterData['protected_patientMasterData'];

$this->placeholder('patient.icons.new')->captureStart();

$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/iconsexpand.css');

$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/views/templates/placeholderPatientIconsNew.js');

// $btm_perm = null;
// has_btm_permission


?>
<!-- start placeholder.patient.icons.new -->
<div class="iconbar iconbar_container" id="placeholder.patient.icons.new">

    <!-- start #new_icons .iconbar_icons_container -->
    <div id="new_icons" class="iconbar_icons_container table_column column_middle<?=$system_icon_details['24']['visible'] != '1' ? '_full' : ''?><?=($btm_perm == '1' && $has_btm_permission == '1') ? '_btm' : ''?> <?=($patient_sys_icons[0] != '24' && (count($patient_sys_icons) > '0' || count($patient_icons_details) > '0' || count($custom_icon_details) > '0')) ? ' ' : 'no_border' ?>">
    
    <?php 
    foreach ($system_icon_details as $k_icon_details => $v_icon_details) : 
    ?>
    
        <?php 
        // ICON must be VISIBILE in order to be displayed
        if( ! isset($v_icon_details['visible']) || $v_icon_details['visible'] != '1'): 
              continue;
        endif; 
        ?>
        
            <?php if($k_icon_details == "3"): ?>
                <div data-details_box="<?=$k_icon_details?>" class="patient_icon_cell iconitem" style="background:#<?php echo $system_icon_data[$k_icon_details]['last'][$this->ipid]['color']; ?>" id="sys_icon-<?php echo $k_icon_details; ?>">
                    <?php if(!empty($system_icon_data[$k_icon_details]['last'][$this->ipid]['image'])): ?>
                        <img src="<?php echo APP_BASE . 'icons_system/' . $system_icon_data[$k_icon_details]['last'][$this->ipid]['image']; ?>" title="<?php echo $this->translate($system_icon_data[$k_icon_details]['last'][$this->ipid]['name']); ?>" />
                    <?php else: ?>
                        <p> &nbsp; </p>
                    <?php endif; ?>
                </div>
            
            <?php elseif( $k_icon_details == '53'): ?>
                    <?php $germination_status = $system_icon_data[53]['germination_status'][$this->ipid]['status'];?>
                    <?php $germination_text = $system_icon_data[53]['germination_status'][$this->ipid]['germination_text'];
                    ?>
                    <div data-details_box="<?=$k_icon_details?>" class="patient_icon_cell tabs_table iconitem" style="background:#<?php echo $v_icon_details['color']; ?>" id="sys_icon-<?php echo $k_icon_details; ?>">
                        <?php if(!empty($v_icon_details['image'])): ?>
                            <img src="<?php echo APP_BASE . 'icons_system/' . $v_icon_details['image']; ?>" class="<?php echo $germination_status;?>" title="<?php echo $this->translate($v_icon_details['name']); ?>" />
                        <?php else: ?>
                            <p> &nbsp; </p>
                        <?php endif; ?>
                    </div>
            
                
            <?php elseif( $k_icon_details == '42'): ?>
            <?php /* ISPC-1775,ISPC-1678,ISPC-1994 */ ?>
                    <? $register_data = $system_icon_data[42]['register_status'][$this->ipid];?>
                    <div data-details_box="<?=$k_icon_details?>" class="patient_icon_cell iconitem" style="background:#<?php echo $v_icon_details['color']; ?>" id="sys_icon-<?php echo $k_icon_details; ?>">
                        <?php if(!empty($v_icon_details['image'])): ?>
                            <a href="<?php echo APP_BASE .'patientnew/hospizregisterv3?id=' . $_REQUEST['id']; ?>" >
                            <img src="<?php echo APP_BASE . 'icons_system/' . $v_icon_details['image']; ?>" class="<?php echo $register_data['status'];?>" title="<?php echo $this->translate($v_icon_details['name']); ?>" />
                            </a>
                        <?php else: ?>
                            <p> &nbsp; </p>
                        <?php endif; ?>
                    </div>
                    
                    
            <?php elseif($k_icon_details == '43' 
                && $diagno_act_module == "1"):
            ?>
                <div data-details_box="<?=$k_icon_details?>" class="patient_icon_cell iconitem" style="background:#<?php echo $system_icon_data[$k_icon_details]['last_diagno_act'][$this->ipid]['color']; ?>" id="sys_icon-<?php echo $k_icon_details; ?>">
                    <?php if(!empty($system_icon_data['43']['last_diagno_act'][$this->ipid]['image'])): ?>
                        <img src="<?php echo APP_BASE . 'icons_system/' . $system_icon_data[$k_icon_details]['last_diagno_act'][$this->ipid]['image']; ?>" title="<?php echo $this->translate($system_icon_data[$k_icon_details]['last_diagno_act'][$this->ipid]['name']); ?>" />
                    <?php else: ?>
                        <p> &nbsp; </p>
                    <?php endif; ?>
                </div>            
            <?php elseif($k_icon_details == '56' ):?>
                <div data-details_box="<?=$k_icon_details?>" class="patient_icon_cell tabs_table iconitem" style="background:#<?php echo $system_icon_data[$k_icon_details]['current_maintenancestage'][$this->ipid]['color']; ?>" id="sys_icon-<?php echo $k_icon_details; ?>">
                    <?php if(!empty($system_icon_data['56']['current_maintenancestage'][$this->ipid]['image'])): ?>
                        <img src="<?php echo APP_BASE . 'icons_system/' . $system_icon_data[$k_icon_details]['current_maintenancestage'][$this->ipid]['image']; ?>" title="<?php echo $this->translate($system_icon_data[$k_icon_details]['current_maintenancestage'][$this->ipid]['name']); ?>" />
                    <?php else: ?>
                        <p> &nbsp; </p>
                    <?php endif; ?>
                </div>
                
            
            <?php elseif($k_icon_details != '6' 
                && $v_icon_details['function'] != 'go_to_visitform'
                && $k_icon_details != '56'): 
            ?>
                <?php $homecare_icon = array_values($system_icon_data[$k_icon_details]['master_homes'][$this->ipid]); ?>
                <?php $physio_icon = array_values($system_icon_data[$k_icon_details]['master_physio'][$this->ipid]); ?>
                <div data-details_box="<?=$k_icon_details?>" class="patient_icon_cell<?php if($v_icon_details['function'] == 'go_to_visitform'): ?>_right<?php endif; ?> iconitem <?php if($k_icon_details != '5' && $k_icon_details != '33' && $v_icon_details['function'] != 'go_to_visitform' && $v_icon_details['function'] != 'sgbv_icon'): echo 'tabs_table'; endif; ?> <?php if($v_icon_details['function'] == 'get_patient_vital_signs'): ?> vital_signs_icon <?php endif; ?> " style="background:#<?php echo $v_icon_details['color']; ?>" id="sys_icon-<?php echo $k_icon_details; ?>">
                    <?php if(!empty($system_icon_data[$k_icon_details]['master_pflege'][$this->ipid]['logo'])): ?>
                        <img src="<?php echo APP_BASE . 'icons_system/' . $system_icon_data[$k_icon_details]['master_pflege'][$this->ipid]['logo']; ?>" title="<?php echo $this->translate($v_icon_details['name']); ?>" />
                    <?php elseif(!empty($system_icon_data[$k_icon_details]['patient_supplier_data'][$this->ipid]['logo'])): ?>    
                        <img src="<?php echo APP_BASE . 'icons_system/' . $system_icon_data[$k_icon_details]['patient_supplier_data'][$this->ipid]['logo']; ?>" title="<?php echo $this->translate($v_icon_details['name']); ?>" />        
                    <?php elseif(!empty($homecare_icon[0]['logo'])): ?>
                        <img src="<?php echo APP_BASE . 'icons_system/' . $homecare_icon[0]['logo']; ?>" title="<?php echo $this->translate($v_icon_details['name']); ?>" />
                    <?php elseif(!empty($physio_icon[0]['logo'])): ?>
                        <img src="<?php echo APP_BASE . 'icons_system/' . $physio_icon[0]['logo']; ?>" title="<?php echo $this->translate($v_icon_details['name']); ?>" />
                    <?php elseif(!empty($v_icon_details['image'])): ?>
                        <img src="<?php echo APP_BASE . 'icons_system/' . $v_icon_details['image']; ?>" title="<?php echo $this->translate($v_icon_details['name']); ?>" />
                    <?php else: ?>
                        <p> &nbsp; </p>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
    <?php endforeach; ?>
    
        
        <div style="clear: both;"></div>
    
        <!--display patient custom icons -->                        
        <?php foreach($patient_icons_details as $k_pat_icon => $v_pat_icon): ?>
        <div class="patient_icon_cell custom_icon_assigned" style="background:#<?php echo $v_pat_icon['color']; ?>" id="assigned_custom_icon-<?php echo $v_pat_icon['id']; ?>" title="<?php echo $v_pat_icon['name']; ?>">
            <?php if ( ! empty($v_pat_icon['image'])): ?>
            <img src="<?php echo APP_BASE . 'icons_system/' . $v_pat_icon['image']; ?>" title="<?php echo $this->translate($v_pat_icon['name']); ?>" />
            <?php else: ?>
            <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNgYAAAAAMAASsJTYQAAAAASUVORK5CYII="/><!-- blank 1px  -->
            <?php endif; ?>
        </div>
        <?php endforeach; ?>
    
        <!--green icon to toggle available custom icons -->
        <div id="assign_custom_icon"  class="patient_icon_cell assign_custom_icon"> 
            <a href="javascript:void(0);" ><img src="<?php echo APP_BASE . 'images/btttt_plus.png' ?>" title="<?php echo $this->translate('assign_custom_icon'); ?>" /></a>
        </div>
        
        <!-- display available custom icons -->
        <div id="available_custom_icons" style="display:none;">
        
            <?php foreach($custom_icon_details as $k_cust_icon_det => $v_cust_icon_det): ?>
            
            <div class="patient_icon_cell available" style="<?php if($v_cust_icon_det['visible'] == '0'): ?>display:none; <?php endif; ?>background:#<?php echo $v_cust_icon_det['color']; ?>" rel="<?php echo $v_cust_icon_det['id']; ?>" id="available_custom_icon-<?php echo $v_cust_icon_det['id']; ?>" title="<?php echo $v_cust_icon_det['name']; ?>">
                <?php if(!empty($v_cust_icon_det['image'])): ?>
                <img src="<?php echo APP_BASE . 'icons_system/' . $v_cust_icon_det['image']; ?>" />
                <?php else: ?>
                <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNgYAAAAAMAASsJTYQAAAAASUVORK5CYII="/><!-- blank 1px  -->
                <?php endif; ?>
            </div>
            <?php endforeach; ?>
        </div>
        
    </div><!-- end  #new_icons .iconbar_icons_container -->
    
    <div style="clear: both;"></div>
    
    <!-- start .iconbar_iconexpandbar_container -->
    <div class="tab-container selector_new_icons_details iconbar_iconexpandbar_container">
        <?php 
        /*
         * this are the details for each of the icon.. displayed on icon click
         */    
        foreach ($system_icon_details as $k_sys_det => $v_sys_det) :
         
            switch ($k_sys_det) :
                
                case "1":  //Ehrenamtliche
                case "2":  //VOLLVERSORGUNG VL
                case "3":  //sapv_verordnung
                case "4":  //Pflegedienst
                case "6":  //Dead
                    
                case "23":  //Hausnotruf - emergency nursing
                case "25":  //Family doctor icon
                case "27":  //Sanitätshaus
                case "29":  //Specialists
                    
                case "31":  //Diagnosis icon
                case "32":  //Medication icon
                case "34":  //Aphoteke
                case "35":  //Krankenkasse
                case "36":  //Versorger
                case "37":  //patient_assigned_users
                case "38":  //Physiotherapist
                case "39":  //Homecare
                    
                case "40":  //patient_location_users
                case "41":  //allergies_data
                case "48":  //Medication icon
                case "49":  //Vital signs icon
                    
                case "50":  //tourplan_settings
                case "51":  //todo_data
                case "52":  //scheduled_medication_data
                case "53":  //germination
                case "54":  //nutritionform
                case "55":  //form block ventilation
                case "56":  //pflegegrade
                    
                case "63":  //patient_contact_persons_custodians
                case "64":  //measure
                case "65":  //current situation
                case "66":  //sapv_appl
                    
                    $this->render("templates/iconexpanded/{$k_sys_det}.phtml");
                    echo $this->placeholder("patient.icons.new.expanded.{$k_sys_det}");
                    
                break;
             
            endswitch;
        endforeach; 
        ?>
    </div><!-- end .iconbar_iconexpandbar_container -->
              
</div><!-- end  placeholder.patient.icons.new-->
<?php $this->placeholder('patient.icons.new')->captureEnd() ?>