<?php
$patientMasterData = $this->{'patientMasterData'};
$view = $this;

$this->placeholder('patient.course.add.inline')->captureStart();

$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/views/templates/placeholderPatientCourseAddInline.js');

?>
<!-- start placeholder.patient.course.add.inline -->
<div class="verlauf addrecord"  id="placeholder.patient.course.add.inline">
<?php
/*
 * #cfileds is used as mains selector in js
 */
?>
<form action="<?php echo $this->act ?>" method="post" name="frmcourse" id="frmcourse" autocomplete="off">
    <?php
    /*
     * triggerformid .. what is used for?
     * if you are using this from the POST... then go to sleep 
     */
    ?>
    <input type="hidden" id="1" name="triggerformid" value="1" />

    <div id="cfileds">
    <h1 class="mobile"><?=$this->translate('patientcoursedocs')?></h1>

<?php 
$patient_hs_disabled = $view->disable_hs_insert;
$modulepriv = $view->modulepriv;
$modulepriv_bavaria = $view->modulepriv_bav;
$module_hb = $view->module_hb;
$module_le = $view->module_le;
$module_sd = $view->module_sd;
$module_al = $view->module_al;

$module_xs = $view->module_xs;
$module_xe = $view->module_xe;
$module_vo_ve = $view->module_vo_ve;
$pid = $view->pid;
$coursecnt = $view->coursecnt;

$current_date = date('d.m.Y');
$current_datetime = date('H:i');




foreach ($this->listcourseSessionArray as $courseSession) :

    $course_type = $courseSession['course_type'];
    $course_title = $courseSession['course_title'];
    
    $hide = '';
    
    $cntr++;
    $cntplus = $cntr + 1;
    $sel = "";

    if($cntr == $coursecnt)
    {
        $sel = "selectdignosis('" . trim($pid) . "'," . $cntplus . "," . $coursecnt . ")";
    }


    
    if($course_type == "M" || $course_type == "N" || $course_type == "I")
    {
    	$values = explode("|", $course_title);
    	array_walk($values, create_function('&$val', '$val = trim(rtrim($val));'));
    	
    	if(empty($values[0]))
    	{
    		$values[0] = "Name";
    	}
    	if(empty($values[1]))
    	{
    		$values[1] = "Dosierung";
    	}
    	if(empty($values[2]))
    	{
    		$values[2] = "Kommentar";
    	}
    	
    	$newfields = '<div id="hidd' . $cntr . '" class="hid-div">
    		<input type="text" id="name' . $cntr . '" class="course_med_name caret" name="name[]" value="'.$values[0].'" onfocus="if(this.value == \'Name\') { this.value=\'\'}" onblur="if(this.value == \'\'){ this.value=\'Name\' } else { appendto(\'' . $cntr . '\',this.value) }  insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');">
    		<input type="text" id="dosage' . $cntr . '" name="dosage[]" class="caret verlauf_medi_dosage" value="'.$values[1].'" onfocus="if(this.value == \'Dosierung\') { this.value=\'\'}" onblur="if(this.value == \'\'){ this.value=\'Dosierung\' } else { appendto(\'' . $cntr . '\',this.value) } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');">
    		<input type="text" id="komment' . $cntr . '" name="komment[]" class="caret verlauf_medi_komment" value="'.$values[2].'" onfocus="if(this.value == \'Kommentar\') { this.value=\'\'};" onblur="if(this.value == \'\'){ this.value=\'Kommentar\' } else { appendto(\'' . $cntr . '\',this.value) } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');">
    	</div>';
    	$hide = 'style="display:none;"';
    }
    else if($course_type == "BP")
    {
    	$values = explode("|", $course_title);
    	array_walk($values, create_function('&$val', '$val = trim(rtrim($val));'));
    	
    	if(empty($values[0]))
    	{
    		$values[0] = "Name";
    	}
    	if(empty($values[1]))
    	{
    		$values[1] = "Kommentar";
    	}
    	
    	$newfields = '<div id="hidd' . $cntr . '">
    		<input type="text" id="name' . $cntr . '" class="course_med_name_treatment_care caret" name="name[]" value="'.$values[0].'" onfocus="if(this.value == \'Name\') { this.value=\'\'}" onblur="if(this.value == \'\'){ this.value=\'Name\' } else { appendto(\'' . $cntr . '\',this.value) }  insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');">
    		<input type="text" id="komment' . $cntr . '" name="komment[]" class="caret verlauf_medi_komment" value="'.$values[2].'" onfocus="if(this.value == \'Kommentar\') { this.value=\'\'};" onblur="if(this.value == \'\'){ this.value=\'Kommentar\' } else { appendto(\'' . $cntr . '\',this.value) } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');">
    	</div>';
    	$hide = 'style="display:none;"';
    }
    else if((($course_type == 'XT') && ($modulepriv == "1" || $modulepriv_bavaria == "1" )) || ($course_type == 'SD' && $module_sd=="1"))
    {
    	$values = explode("|", $course_title);
    	array_walk($values, create_function('&$val', '$val = trim(rtrim($val));'));
    	if(empty($values[0]))
    	{
    		//default duration
    		$values[0] = "Zeit (in Minuten)";
    	}
    
    	if(empty($values[1]))
    	{
    		//default text
    		$values[1] = "Grund / Anlass";
    	}
    
    	if(empty($values[2]))
    	{
    		//default date/time
    		$values[3] = date('d.m.Y', time());
    		$values[4] = date('H:i', time());
    	}
    	else
    	{
    
    		$values[3] = date('d.m.Y', strtotime($values[2]));
    		$values[4] = date('H:i', strtotime($values[2]));
    	}
    
    	$newfields = '<div id="hidd' . $cntr . '" class="hid-div">
    					<input type="text" id="time' . $cntr . '" class="caret course_time" name="time[]" value="' . $values[0] . '" onfocus="if(this.value == \'Zeit (in Minuten)\') { this.value=\'\'}" onblur="if(this.value == \'\'){ this.value=\'Zeit (in Minuten)\' } else { appendto (\'' . $cntr . '\',this.value) } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" onkeydown="appendto(\'' . $cntr . '\',this.value);">
    					<textarea name="komment[]" id="komment' . $cntr . '" class="course_comment" onfocus="if(this.value == \'Grund / Anlass\') { this.value=\'\'}" onblur="if(this.value == \'\'){ this.value=\'Grund / Anlass\' } else { appendto(\'' . $cntr . '\',this.value) } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" style="overflow: hidden;">' . $values[1] . '</textarea>
    					<input type="text" id="date' . $cntr . '" name="date[]" class="caret course_date" value="' . $values[3] . '" onfocus="appendto(\'' . $cntr . '\',this.value);"   onblur="if(this.value == \'\'){ this.value=\'' .$current_date. '\' } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');"  onchange="if(this.value == \'\'){ this.value=\'' .$current_date. '\' } else { appendto(\'' . $cntr . '\',this.value) } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');">
    					<input type="text" id="hourtime' . $cntr . '" name="hourtime[]" class="course_timepicker" value="' . $values[4] . '"  onfocus="insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" onblur="if(this.value == \'\'){ this.value=\'' .$current_datetime. '\' } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" onchange="insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');">
    				</div>';
    	$hide = 'style="display:none;"';
    }
    else if(  ( $course_type == 'XS' && $module_xs == "1" ) || ( $course_type == 'XE' && $module_xe == "1" )         )
    {
    	$values = explode("|", $course_title);
    	array_walk($values, create_function('&$val', '$val = trim(rtrim($val));'));
    	if(empty($values[0]))
    	{
    		//default duration
    		$values[0] = "Zeit (in Minuten)";
    	}
    
    	if(empty($values[1]))
    	{
    		//default text
    		$values[1] = "Grund / Anlass";
    	}
    
    	if(empty($values[2]))
    	{
    		//default date/time
    		$values[3] = date('d.m.Y', time());
    		$values[4] = date('H:i', time());
    	}
    	else
    	{
    
    		$values[3] = date('d.m.Y', strtotime($values[2]));
    		$values[4] = date('H:i', strtotime($values[2]));
    	}
    
    	$newfields = '<div id="hidd' . $cntr . '" class="hid-div">
    					<input type="text" id="time' . $cntr . '" class="caret course_time" name="time[]" value="' . $values[0] . '" onfocus="if(this.value == \'Zeit (in Minuten)\') { this.value=\'\'}" onblur="if(this.value == \'\'){ this.value=\'Zeit (in Minuten)\' } else { appendto (\'' . $cntr . '\',this.value) } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" onkeydown="appendto(\'' . $cntr . '\',this.value);">
    					<textarea name="komment[]" id="komment' . $cntr . '" class="course_comment" onfocus="if(this.value == \'Grund / Anlass\') { this.value=\'\'}" onblur="if(this.value == \'\'){ this.value=\'Grund / Anlass\' } else { appendto(\'' . $cntr . '\',this.value) } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" style="overflow: hidden;">' . $values[1] . '</textarea>
    					<input type="text" id="date' . $cntr . '" name="date[]" class="caret course_date" value="' . $values[3] . '" onfocus="appendto(\'' . $cntr . '\',this.value);"   onblur="if(this.value == \'\'){ this.value=\'' .$current_date. '\' } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');"  onchange="if(this.value == \'\'){ this.value=\'' .$current_date. '\' } else { appendto(\'' . $cntr . '\',this.value) } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');">
    					<input type="text" id="hourtime' . $cntr . '" name="hourtime[]" class="course_timepicker" value="' . $values[4] . '"  onfocus="insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" onblur="if(this.value == \'\'){ this.value=\'' .$current_datetime. '\' } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" onchange="insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');">
    				</div>';
    	$hide = 'style="display:none;"';
    }
    else if($course_type == 'HB' && $module_hb == "1" )
    {
    	$values = explode("|", $course_title);
    	array_walk($values, create_function('&$val', '$val = trim(rtrim($val));'));
    	if(empty($values[0]))
    	{
    		//default duration
    		$values[0] = "Zeit (in Minuten)";
    	}
    
    	if(empty($values[1]))
    	{
    		//default text
    		$values[1] = "Grund / Anlass";
    	}
    
    	if(empty($values[2]))
    	{
    		//default date/time
    		$values[3] = date('d.m.Y', time());
    		$values[4] = date('H:i', time());
    	}
    	else
    	{
    
    		$values[3] = date('d.m.Y', strtotime($values[2]));
    		$values[4] = date('H:i', strtotime($values[2]));
    	}
    
    	$newfields = '<div id="hidd' . $cntr . '" class="hid-div">
    					<input type="text" id="time' . $cntr . '" class="caret course_time" name="time[]" value="' . $values[0] . '" onfocus="if(this.value == \'Zeit (in Minuten)\') { this.value=\'\'}" onblur="if(this.value == \'\'){ this.value=\'Zeit (in Minuten)\' } else { appendto (\'' . $cntr . '\',this.value) } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" onkeydown="appendto(\'' . $cntr . '\',this.value);">
    					<textarea name="komment[]" id="komment' . $cntr . '" class="course_comment" onfocus="if(this.value == \'Grund / Anlass\') { this.value=\'\'}" onblur="if(this.value == \'\'){ this.value=\'Grund / Anlass\' } else { appendto(\'' . $cntr . '\',this.value) } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" style="overflow: hidden;">' . $values[1] . '</textarea>
    					<input type="text" id="date' . $cntr . '" name="date[]" class="caret course_date" value="' . $values[3] . '" onfocus="appendto(\'' . $cntr . '\',this.value);"   onblur="if(this.value == \'\'){ this.value=\'' .$current_date. '\' } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');"  onchange="if(this.value == \'\'){ this.value=\'' .$current_date. '\' } else { appendto(\'' . $cntr . '\',this.value) } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');">
    					<input type="text" id="hourtime' . $cntr . '" name="hourtime[]" class="course_timepicker" value="' . $values[4] . '"  onfocus="insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" onblur="if(this.value == \'\'){ this.value=\'' .$current_datetime. '\' } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" onchange="insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');">
    				</div>';
    	$hide = 'style="display:none;"';
    }
    else if($course_type == 'PB')
    {
    
      $values = explode("|", $course_title);
    	array_walk($values, create_function('&$val', '$val = trim(rtrim($val));'));
    	if(empty($values[0]))
    	{
    		//default duration
    		$values[0] = "Inhalt";
    	}
    
    	if(empty($values[1]))
    	{
    		//default date/time
    		$values[3] = date('d.m.Y', time());
    		$values[4] = date('H:i', time());
    	}else{
    	   
    		$values[3] = date('d.m.Y', strtotime($values[1]));
    		$values[4] = date('H:i', strtotime($values[1]));
    	}
    
    
    	$newfields = '<div id="hidd' . $cntr . '" class="hid-div">
    					<textarea name="komment[]" id="komment' . $cntr . '" class="course_comment_pb" onfocus="if(this.value == \' Inhalt \') { this.value=\'\'}" onblur="if(this.value == \'\'){ this.value=\' Inhalt \' } else { appendto(\'' . $cntr . '\',this.value) } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" style="overflow: hidden;">' . $values[0] . '</textarea>
    					<input type="text" id="date' . $cntr . '" name="date[]" class="caret course_date" value="' . $values[3] . '" onfocus="appendto(\'' . $cntr . '\',this.value);"   onblur="if(this.value == \'\'){ this.value=\'' .$current_date. '\' }"  change="if(this.value == \'\'){ this.value=\'Date\' } else { appendto(\'' . $cntr . '\',this.value) } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');">
    					<input type="text" id="hourtime' . $cntr . '" name="hourtime[]" class="course_timepicker" value="' . $values[4] . '" onblur="if(this.value == \'\'){ this.value=\'' .$current_datetime. '\' } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" onchange="insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');">
    				</div>';
    	$hide = 'style="display:none;"';
      
      
      
    }
    else if($course_type == 'KX')
    {
    
      $values = explode("|", $course_title);
    	array_walk($values, create_function('&$val', '$val = trim(rtrim($val));'));
    	if(empty($values[0]))
    	{
    		//default duration
    		$values[0] = "";
    	}
    
    	if(empty($values[1]))
    	{
    		//default date/time
    		$values[3] = date('d.m.Y', time());
    		$values[4] = date('H:i', time());
    	}else{
    	   
    		$values[3] = date('d.m.Y', strtotime($values[1]));
    		$values[4] = date('H:i', strtotime($values[1]));
    	}
    
    
    	$newfields = '<div id="hidd' . $cntr . '" class="hid-div">
    					<textarea name="komment[]" id="komment' . $cntr . '" class="course_comment_pb" onfocus="if(this.value == \' Inhalt \') { this.value=\'\'}" onblur="if(this.value == \'\'){ this.value=\' \' } else { appendto(\'' . $cntr . '\',this.value) } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" style="overflow: hidden;">' . $values[0] . '</textarea>
    					<input type="text" id="date' . $cntr . '" name="date[]" class="caret course_date" value="' . $values[3] . '" onfocus="appendto(\'' . $cntr . '\',this.value);"   onblur="if(this.value == \'\'){ this.value=\'' .$current_date. '\' }"  change="if(this.value == \'\'){ this.value=\'Date\' } else { appendto(\'' . $cntr . '\',this.value) } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');">
    					<input type="text" id="hourtime' . $cntr . '" name="hourtime[]" class="course_timepicker" value="' . $values[4] . '" onblur="if(this.value == \'\'){ this.value=\'' .$current_datetime. '\' } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" onchange="insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');">
    				</div>';
    	$hide = 'style="display:none;"';
      
      
      
    }
    else if( $course_type == 'V'
    		 || ($module_vo_ve == "1" && ($course_type == 'VO' || $course_type == 'VE'))
    		) 
    {
    	$values = explode("|", $course_title);
    	array_walk($values, create_function('&$val', '$val = trim(rtrim($val));'));
    	
    	if(empty($values[0]))
    	{
    		//default duration
    		$values[0] = "Zeit (in Minuten)";
    	}
    	if(empty($values[1]))
    	{
    		//default text
    		$values[1] = "Grund / Anlass";
    	}
    	if(empty($values[2]))
    	{
    		//default date/time
    		$values[3] = date('d.m.Y', time());
    		$values[4] = date('H:i', time());
    	}
    	else
    	{
    
    		$values[3] = date('d.m.Y', strtotime($values[2]));
    		$values[4] = date('H:i', strtotime($values[2]));
    	}
    
    	$newfields = '<div id="hidd' . $cntr . '" class="hid-div">
    			<input type="text" id="time' . $cntr . '" class="caret course_time" name="time[]" value="' . $values[0] . '" onfocus="if(this.value == \'Zeit (in Minuten)\') { this.value=\'\'}" onblur="if(this.value == \'\'){ this.value=\'Zeit (in Minuten)\' } else { appendto (\'' . $cntr . '\',this.value) } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" onkeydown="appendto(\'' . $cntr . '\',this.value);">
    			<textarea name="komment[]" id="komment' . $cntr . '" class="course_comment" onfocus="if(this.value == \'Grund / Anlass\') { this.value=\'\'}" onblur="if(this.value == \'\'){ this.value=\'Grund / Anlass\' } else { appendto(\'' . $cntr . '\',this.value) } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" style="overflow: hidden;">' . $values[1] . '</textarea>
    			<input type="text" id="date' . $cntr . '" name="date[]" class="course_date caret" value="' . $values[3] . '" onfocus="appendto(\'' . $cntr . '\',this.value);"  onblur="if(this.value == \'\'){ this.value=\'' .$current_date. '\' }  insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');"  onchange="if(this.value == \'\'){ this.value=\'' .$current_date. '\' } else { appendto(\'' . $cntr . '\',this.value) } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');">
    			<input type="text" id="hourtime' . $cntr . '" name="hourtime[]" class="course_timepicker" value="' . $values[4] . '" onfocus="insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" onblur="if(this.value == \'\'){ this.value=\'' .$current_datetime. '\' }  insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');">
    		</div>';
    	$hide = 'style="display:none;"';
    }
    else if($course_type == 'AA')
    {
    	$values = explode("|", $course_title);
    	array_walk($values, create_function('&$val', '$val = trim(rtrim($val));'));
    	
    	if(empty($values[0]))
    	{
    		//default duration
    		$values[0] = "Zeit (in Minuten)";
    	}
    	if(empty($values[1]))
    	{
    		//default text
    		$values[1] = "Grund / Anlass";
    	}
    	if(empty($values[2]))
    	{
    		//default date/time
    		$values[3] = date('d.m.Y', time());
    		$values[4] = date('H:i', time());
    	}
    	else
    	{
    
    		$values[3] = date('d.m.Y', strtotime($values[2]));
    		$values[4] = date('H:i', strtotime($values[2]));
    	}
    
    	$newfields = '<div id="hidd' . $cntr . '" class="hid-div">
    			<input type="text" id="time' . $cntr . '" class="caret course_time" name="time[]" value="' . $values[0] . '" onfocus="if(this.value == \'Zeit (in Minuten)\') { this.value=\'\'}" onblur="if(this.value == \'\'){ this.value=\'Zeit (in Minuten)\' } else { appendto (\'' . $cntr . '\',this.value) } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" onkeydown="appendto(\'' . $cntr . '\',this.value);">
    			<textarea name="komment[]" id="komment' . $cntr . '" class="course_comment" onfocus="if(this.value == \'Grund / Anlass\') { this.value=\'\'}" onblur="if(this.value == \'\'){ this.value=\'Grund / Anlass\' } else { appendto(\'' . $cntr . '\',this.value) } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" style="overflow: hidden;">' . $values[1] . '</textarea>
    			<input type="text" id="date' . $cntr . '" name="date[]" class="course_date caret" value="' . $values[3] . '" onfocus="appendto(\'' . $cntr . '\',this.value);"  onblur="if(this.value == \'\'){ this.value=\'' .$current_date. '\' }  insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');"  onchange="if(this.value == \'\'){ this.value=\'' .$current_date. '\' } else { appendto(\'' . $cntr . '\',this.value) } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');">
    			<input type="text" id="hourtime' . $cntr . '" name="hourtime[]" class="course_timepicker" value="' . $values[4] . '" onfocus="insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" onblur="if(this.value == \'\'){ this.value=\'' .$current_datetime. '\' }  insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');">
    		</div>';
    	$hide = 'style="display:none;"';
    }
    else if($course_type == 'W')
    {
    
    	$values = explode('|---------|', $course_title);
    	array_walk($values, create_function('&$val', '$val = trim(rtrim($val));'));
    	
    	if(empty($values[0]))
    	{
    		//default todo text
    		$values[0] = "TODO";
    	}
    
    	if(empty($values[1]))
    	{
    		//default user selected
    		$values[1] = '0';
    	}
    	
    	$usersidstodo = explode(',', trim($values[1]));
    	
    	if(empty($values[2]))
    	{
    		//default date
    		$values[2] = date('d.m.Y', time());
    	}
    
    	if(!empty($values[3]) && $values[3] == '1')
    	{
    		$values['checked'] = 'checked="checked"';
    	}
    	else
    	{
    		$values['checked'] = '';
    	}
    	
    	$unames = array();
    	foreach($usersidstodo as $ud){
    		$unames[] = $view->usersnewtodos[$ud];
    	}
    	
    	/*
    	$attrs = array("onblur"=>"appendto(" . $cntr . ",this.value); insertsession('".$cntr."','".$pid."','".$cntr."');", "onchange"=>"insertsession('".$cntr."','".$pid."','".$cntr."');", "rel"=>$cntr  ,"style"=>" ", "class"=>"caret multiselect_style", "multiple"=>"multiple", "size"=>"1");
    	$select = $view->formSelect("user" . $cntr . "", $usersidstodo, $attrs, $view->usersnewtodos);
    	*/
     
     /* 
     	//this was the select before changing to $view->formSelect()
    	$sel_str ='<select name="user'.$cntr.'[]"  id="user'.$cntr.'" multiple="multiple" onblur="appendto(\'' . $cntr . '\',this.value); insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$cntr.'\');" onchange="insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$cntr.'\');"  rel="'.$cntr.'"  style=" "   class="caret multiselect_style" size="1" >';
    	foreach($view->usersnewtodos as $uid=>$uval){
    		if($uid == "u000000" || $uid == "g000000" || $uid =="pseudogroups_header"){
    			$dis_str = 'disabled="disabled"' ;
    		}else{
    			$dis_str ='';
    		}
    		if(in_array($uid,$usersidstodo)){
    			$tu_selected = 'selected="selected"';
    		} else{
    			$tu_selected = '';
    		}
    		$sel_str .= '<option value="'.$uid.'"  '.$dis_str.'  '.$tu_selected.' >'.$uval.'</option>';
    	}
    	$sel_str .= '</select>';
    */	
    	
    	  
    	
    	$sel_str = $view->formSelect(
    							"user{$cntr}[]", 
    							$usersidstodo, 
    							array(
    								"id" => "user{$cntr}",
    								"rel" => $cntr,
    								"class" => "todo_selectbox",
    								"multiple" => true,
    								"size" => 1,
    								"disable" => array("0"),
    								"onchange" => "appendto('{$cntr}', this.value); insertsession('{$cntr}','{$pid}','{$cntr}');",
    								"onchanges" => "insertsession('{$cntr}', '{$pid}', '{$cntr}');" 
    								 
    							),
    							$view->usersnewtodos
    						);
    
    	$newfields = '<div id="hidd' . $cntr . '" class="hid-div">
    		<textarea id="todo' . $cntr . '" class="course_todo caret" name="todo[]" onfocus="if(this.value == \'TODO\') { this.value=\'\'}" onblur="if(this.value == \'\'){ this.value=\'TODO\' } else { appendto(\'' . $cntr . '\',this.value) } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" style="overflow: hidden;">' . $values[0] . '</textarea><div class="sel_holder sel_holder_todos" >
    		'.$sel_str.'
    		</div>
    		<input type="text" style="width: 100px;" id="till' . $cntr . '" name="till[]" class="course_todo_date caret" value="' . $values[2] . '" onfocus="appendto(\'' . $cntr . '\',this.value);" onchange="if(this.value == \'\'){ this.value=\''.$current_date.'\' } else { appendto(\'' . $cntr . '\',this.value);} insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');">
    	</div>';
    	
    	/*
    	removed this textarea from $newfields
    	<textarea id="selected'.$cntr.'"  style="width:196px; height: 40px;" cols="" rows="3" class="todo_specialo_tezxtae">'.implode(";",$unames).'</textarea>
    	*/
    	
    	
    	$hide = 'style="display:none;"';
    }
    else if($course_type == 'U')
    {
    	$values = explode('|', $course_title);
    	array_walk($values, create_function('&$val', '$val = trim(rtrim($val));'));
    	
    	if(empty($values[1]))
    	{
    		$values[1] = 'Zeit (in Minuten)';
    	}
    	
    	if(empty($values[2]))
    	{
    		$values[2] = 'Grund / Anlass';
    	}
    	
    	if(empty($values[3]))
    	{
    		$values[4] = date('d.m.Y', time());
    		$values[5] = date('H:i', time());
    	}
    	else
    	{
    		$values[4] = date('d.m.Y', strtotime($values[3]));
    		$values[5] = date('H:i', strtotime($values[3]));
    	}
    	
    	$attrs = array("class"=>"course_uselect");
    	$u_values = array("mit Betroffenen"=>"mit Betroffenen","mit Leistungserbringer"=>"mit Leistungserbringer");
    	
    	$u_select = $view->formSelect("uSelect".$cntr, trim($values[0]), $attrs, $u_values);
    	
    	$newfields = '<div id="hidd' . $cntr . '"  class="hid-div">'.$u_select.'
    		<input type="text" id="time' . $cntr . '" class="caret course_time" name="time[]" value="'.$values[1].'" onfocus="if(this.value == \'Zeit (in Minuten)\') { this.value=\'\'}" onblur="if(this.value == \'\'){ this.value=\'Zeit (in Minuten)\' } else { appendto (\'' . $cntr . '\',this.value) } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" onkeydown="appendto(\'' . $cntr . '\',this.value);">
    		<textarea name="komment[]" id="komment' . $cntr . '" class="course_comment_small" onfocus="if(this.value == \'Grund / Anlass\') { this.value=\'\'}" onblur="if(this.value == \'\'){ this.value=\'Grund / Anlass\' } else { appendto(\'' . $cntr . '\',this.value) } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" style="overflow: hidden;">'.$values[2].'</textarea>
    		<input type="text" id="date' . $cntr . '" name="date[]" class="course_date caret" value="'.$values[4].'" onfocus="appendto(\'' . $cntr . '\',this.value);" onblur="if(this.value == \'\'){ this.value=\'' .$current_date. '\' }  insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" onchange="if(this.value == \'\'){ this.value=\'' .$current_date. '\' } else { appendto(\'' . $cntr . '\',this.value) } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');">
    		<input type="text" id="hourtime' . $cntr . '" name="hourtime[]" class="course_timepicker" value="'.$values[5].'"   onfocus="insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" onblur="if(this.value == \'\'){ this.value=\'' .$current_datetime. '\' }  insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');"  >
    	</div>';
    	$hide = 'style="display:none;"';
    }
    else if($course_type == 'D' || $course_type == 'H' || $course_type == 'HS')
    {
    	$values = explode('|', $course_title);
    	array_walk($values, create_function('&$val', '$val = trim(rtrim($val));'));
    	
    	if($course_type == 'HS')
    	{
    		if($patient_hs_disabled == '1')
    		{
    			$error_div = '<div id="error' . $cntr . '" class="verlauf_error_div" style="clear: both;">'.$view->translate('hs_limit_patient_reached').'</div>';
    		}
    		else
    		{
    			$error_div = '<div id="error' . $cntr . '" class="verlauf_error_div" style="display:none;clear: both;">'.$view->translate('hs_limit_patient_reached').'</div>';
    		}
    	}
    	else
    	{
    		$error_div = '';
    	}
    	
    	$newfields = '
    		<div id="hidd' . $cntr . '" class="hid-div">
    			<input name="icdnumber[' . $cntr . ']" id="icdnumber' . $cntr . '" class="livesearchicdinp caret" value="' . $values[1] . '" style="width:45px;" type="text" onfocus="if(this.value == \'ICD\') { this.value=\'\'}" onblur="if(this.value == \'\'){ this.value=\'ICD\' } else { appendto(\'' . $cntr . '\',this.value) }  insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" autocomplete="off">
    			<div id="icddiagnodropdown' . $cntr . '" class="icdlivesearchdropdown" style="position: absolute; display:none;"></div>
    			<input name="diagnosis[' . $cntr . ']" id="diagnosis' . $cntr . '" value="'.trim(rtrim($values[2])).'" size="33" class="livesearchinp caret course_diag_name" type="text" onfocus="if(this.value == \'Beschreibung\') { this.value=\'\'}" onblur="if(this.value == \'\'){ this.value=\'Beschreibung\' } else { appendto(\'' . $cntr . '\',this.value) } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" autocomplete="off">
    			<input name="hidd_icdnumber[' . $cntr . ']" value="'.$values[0].'" id="hidd_icdnumber' . $cntr . '" type="hidden">
    			<input name="hidd_diagnosis[' . $cntr . ']" value="'.$values[0].'" id="hidd_diagnosis' . $cntr . '" type="hidden">
    			<input name="hidd_tab[' . $cntr . ']" value="" id="hidd_tab" type="hidden">
    			<div id="diagnodropdown' . $cntr . '" class="samtablistDiognoDrp livesearchdropdown" style="position: absolute; display:none;"></div>
    			'.$error_div.'
    		</div>
    	 ';
    	 $hide = 'style="display:none;"';
    	
    }
    else if($course_type == 'SB')
    {
    
    	$values = explode('|__|', $course_title);
    	array_walk($values, create_function('&$val', '$val = trim(rtrim($val));'));
    
    	if(empty($values[0]))
    	{
    		//default user selected
    		$values[0] = '0';
    	}
    	if(empty($values[1]))
    	{
    		//default sh order text
    		$values[1] = "Sanitätshausbestellung";
    	}
    
    	$attrs = array("onblur"=>"appendto(" . $cntr . ",this.value); insertsession('".$cntr."','".$pid."','".$cntr."');", "onchange"=>"insertsession('".$cntr."','".$pid."','".$cntr."');", "style"=>"width:150px; text-align:left; float:left;", "class"=>"caret");
    	
    	$select = $view->formSelect("sb_user" . $cntr . "", trim($values[0]), $attrs, $view->sb_users);
    		
    	$newfields = '<div id="hidd' . $cntr . '" class="hid-div">
    		' . $select . '
    		<textarea id="sb_order' . $cntr . '" class="course_sb_order caret" name="sb_order[]" onfocus="if(this.value == \'Sanitätshausbestellung\') { this.value=\'\'}" onblur="if(this.value == \'\'){ this.value=\'Sanitätshausbestellung\' } else { appendto(\'' . $cntr . '\',this.value) } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" style="overflow: hidden;">' . $course_title . '</textarea>
    	</div>';
    	$hide = 'style="display:none;"';
    }
    else if($course_type == 'L')
    {
       $value=$course_title;
     
       $newfields = '<div id="hidd' . $cntr . '" class="hid-div">
    					 <textarea name="icdnumber['.$cntr.']" id="lrownumber'.$cntr.'" class="serviceslivesearvh caret" style="  margin: 3px 0; display: block;   height: 26px;   overflow: hidden;" onfocus="if(this.value == \'Leistungen\') { this.value=\'\'}" onblur="if(this.value == \'\'){ this.value=\'Leistungen\' } else { appendto(\'' . $cntr . '\',this.value) } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');">'.$value.'</textarea>
    				    <input name="hidd_icdnumber[' . $cntr . ']" value="'.$values[0].'" id="hidd_icdnumber' . $cntr . '" type="hidden">
    				</div>';
    	$hide = 'style="display:none;"';
    }
    else if($course_type == 'LE')
    {
    
    	$values = explode('|____|', $course_title);
    	array_walk($values, create_function('&$val', '$val = trim(rtrim($val));'));
    	 
    /* 
    print_r($values);
    print_r("id=> ".$values[0]);
    print_r("action_id=> ".$values[1]);
    print_r("action_name=> ".$values[2]);
    print_r("action_user=> ".$values[3]);
    print_r("action_datetime=> ".$values[4]); */
    
    	if(empty($values[0]))
    	{
    		$values[0] = ""; // action id from db
    	}
    	
    	if(empty($values[1]))
    	{
    		$values[1] = "ID";// action id
    	}
    	
    	if(empty($values[2]))
    	{
    		$values[2] = "Leistungen"; // action name
    	}
    	
    	
    
    	if(empty($values[4]))
    	{
    		$values[5] = date('d.m.Y', time());
    		$values[6] = date('H:i', time());
    	}
    	else
    	{
    		$values[5] = date('d.m.Y', strtotime($values[4]));
    		$values[6] = date('H:i', strtotime($values[4]));
    	}
    	
    
    
    	$attrs = array("onblur"=>"appendto(" . $cntr . ",this.value); insertsession('".$cntr."','".$pid."','".$cntr."');", "onchange"=>"insertsession('".$cntr."','".$pid."','".$cntr."');", "style"=>"width:120px; text-align:left; float:left;", "class"=>"caret","id"=>"actionuser".$cntr);
    	
    	$select_le_user = $view->formSelect("actionuser[" . $cntr . "]", trim($values[3]), $attrs, $view->users_le);
    		
    		$newfields = '
    		<div id="hidd' . $cntr . '" class="hid-div">
    			<input name="actionid[' . $cntr . ']" id="actionid' . $cntr . '" class="live_search_action_id caret" value="' . $values[1] . '" style="width:65px;" type="text" onfocus="if(this.value == \'ID\') { this.value=\'\'}" onblur="if(this.value == \'\'){ this.value=\'ID\' } else { appendto(\'' . $cntr . '\',this.value) }  insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" autocomplete="off">
    			<div id="icddiagnodropdown' . $cntr . '" class="icdlivesearchdropdown" style="position: absolute; display:none;"></div>
    			<input name="actionname[' . $cntr . ']" id="actionname' . $cntr . '" value="'.trim(rtrim($values[2])).'" size="10" class="live_search_action_name caret course_action_name" type="text" onfocus="if(this.value == \'Leistungen\') { this.value=\'\'}" onblur="if(this.value == \'\'){ this.value=\'Leistungen\' } else { appendto(\'' . $cntr . '\',this.value) } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" autocomplete="off">
    			<input name="hidd_actionid[' . $cntr . ']" value="'.$values[0].'" id="hidd_actionid' . $cntr . '" type="hidden">
    			<input name="hidd_actionname[' . $cntr . ']" value="'.$values[0].'" id="hidd_actionname' . $cntr . '" type="hidden">
    			<input name="hidd_tab[' . $cntr . ']" value="" id="hidd_tab" type="hidden">
    			' . $select_le_user . '
    			<input type="text" id="date' . $cntr . '" name="date[]" class="course_date caret" value="'.$values[5].'" onfocus="appendto(\'' . $cntr . '\',this.value);" onblur="if(this.value == \'\'){ this.value=\'' .$current_date. '\' }  insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" onchange="if(this.value == \'\'){ this.value=\'' .$current_date. '\' } else { appendto(\'' . $cntr . '\',this.value) } insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');">
    			<input type="text" id="hourtime' . $cntr . '" name="hourtime[]" class="course_timepicker" value="'.$values[6].'"   onfocus="insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');" onblur="if(this.value == \'\'){ this.value=\'' .$current_datetime. '\' }  insertsession(\''.$cntr.'\',\''.$pid.'\',\''.$coursecnt.'\');"  >
    		</div>
    	 ';
    	
    	
    	
    	
    	$hide = 'style="display:none;"';
    }
    elseif ($course_type == 'AL' && $module_al=="1")
    {
    		
    	$values = explode("|", $course_title);
    	array_walk($values, create_function('&$val', '$val = trim(rtrim($val));'));
    	//echo $course_title;
    	//print_r($values);die();
    	
    
    	
    	if(empty($values[0]))
    	{
    		$values[0] = "ID";// action id
    	}
    	
    	if(empty($values[1]))
    	{
    		$values[1] = "Beschreibung"; // action name
    	
    	}
    
    	if(empty($values[2]))
    	{
    		$values[3] = date('d.m.Y', time());
    	}
    	else
    	{
    		$values[3] = date('d.m.Y', strtotime($values[2]));
    	}
    	
    	$now = date("d.m.Y");
    $newfields = <<<EOT
    	<div id="hidd{$cntr}"  class="hid-div"> 
    
    	<input type="text" name="actionid{$cntr}" id="actionid{$cntr}"  value="{$values[0]}" style="width:45px" class="live_search_al_action_id caret" style="width:65px;" onfocus="if(this.value == 'ID') { this.value=''}" onblur="if(this.value == ''){ this.value='ID' } else { appendto('{$cntr}', this.value) }  trigger_insertsession('{$cntr}', '{$pid}' ,'{$coursecnt}');" autocomplete="off" />
    	<input type="text" name="description{$cntr}" id="description{$cntr}" value="{$values[1]}" style="width:450px!important"  class="live_search_al_description caret course_action_name"  style="width:65px;" onfocus="if(this.value == 'Beschreibung') { this.value=''}" onblur="if(this.value == ''){ this.value='Beschreibung' } else { appendto('{$cntr}', this.value) }  trigger_insertsession('{$cntr}', '{$pid}' ,'{$coursecnt}');" autocomplete="off" />
    	<input type="text" name="date[]" id="al_date{$cntr}"  value="{$values[3]}" style="height: 17px; width: 65px;" class="caret al_course_date"  onblur="if(this.value == ''){ this.value='{$now}' };"   onchange="if(this.value == ''){ this.value='{$now}'; } else { appendto('{$cntr}', this.value); } trigger_insertsession('{$cntr}', '{$pid}', '{$total_cnt}');"/>
    	
    	<input type="hidden" name="hidd_actionid{$cntr}" value="{$values[0]}" id="hidd_actionid{$cntr}" />
    	<input type="hidden" name="hidd_description{$cntr}" value="{$values[1]}" id="hidd_description{$cntr}" />
    	<input type="hidden" name="hidd_date{$cntr}" value="{$values[3]}" id="hidd_date{$cntr}" />
    
    	   
        
    	
    	</div>
EOT;
    
    	
    	$hide = 'style="display:none;"';
    	
    	
    }
    	
    	
    else
    {
    	$newfields = "";
    	$hide = 'style="display:block;"';
    }
    
    
    
    //create the selectbox for the patientcourse
    
    /*
    "data-choice_vsprintf"  : '<span class=\"choice\" style=\"%3%\">%1%</style>' ,
    "data-row_vsprintf"     : '<span class=\"colLeft\" style=\"%3%\">%1%</span><span class=\"colRight\" style=\"%3%\">%2%</span>' ,
    "data-search_vsprintf"  : '%1% %2%'
    */
    
    //add empty option so we can de-select
    $optionss = "<option value='' ". ($course_type ? ' selected ': ' ') ." data-1='' data-2='" . $view->translate("Please select action") . "' data-3='font-style: italic;color:#BBBBBB;'>" . $view->translate("Please select action") . "</option>"; 
    
    foreach ($this->shortcutsArray as $short) {
        $css = '';
        $css .= $short['isbold'] ? 'font-weight: bold;' : '';
        $css .= $short['isitalic'] ? 'font-style: italic;' : '';
        $css .= $short['isunderline'] ? 'text-decoration: underline;' : '';
        $css .= $short['font_color'] ? "color: #{$short['font_color']};" : '';
        
        $selected = $short['shortcut'] == $course_type ? ' selected ' : '';
        
        $short['course_fullname'] = trim($short['course_fullname']);
        
        $optionss .= "<option {$selected} value='{$short['shortcut']}' data-1='{$short['shortcut']}' data-2='{$short['course_fullname']}' data-3='{$css}'>{$short['course_fullname']}</option>";
    }
    $sel4select = str_replace("'", "\"", $sel);
    $course_type_as_select = "<select name='course_type[]' onchange='keyupdelay(this,{$cntr});' id='course_type{$cntr}' class='selectShortcut chosenShortcuts-container'>{$optionss}</select>";
    
    //default textarea  add default attributes 
    $textarea_disabled = $course_type ? '' : ' disabled ';
    $textarea_placeholder = $course_type ? '' : ' placeholder="'.$view->translate("Please select action first") . '"';
    
    /*
     * .shortcutRow, .LeftList01, .RightList01 are used as selectors in js
    */
?>

    <div class="shortcutRow addComment <?=$course_type?>">
    
        <div class="LeftList01 letter_box">
            <?=$course_type_as_select?>
		</div>
		
		<div id="listcoursesession_course_title<?=$cntr?>" class="RightList01 details_box" >
				<textarea name="course_title[]" 
    				id="course_title<?=$cntr?>" 
    				class="defaultTextarea" 
    				onfocus="<?=$sel?>" 
    				onblur="insertsession('<?=$cntr?>','<?=$pid?>','<?=$coursecnt?>');" 
    				onchange="insertsession('<?=$cntr?>','<?=$pid?>','<?=$coursecnt?>');" <?=$hide?> <?=$textarea_disabled?> 
    				<?=$textarea_placeholder?>
				><?=$course_title?></textarea>
			
			<?=$newfields?>
			
		</div>    
		
	</div>



<?php 
endforeach; //end foreach ($this->listcourseSessionArray;
?>
    </div><!-- //cfileds -->
    <button type="button" class="speichern" onclick="checkdischargednew('frmcourse')"><?=$this->translate('save')?></button>
    
</form>
</div>

<!-- end  placeholder.patient.course.add.inline -->	
<?php $this->placeholder('patient.course.add.inline')->captureEnd() ?>