<?php 
$patientMasterData = $this->{'patientMasterData'};
$system_icon_data = $patientMasterData['system_icon_data'];
$system_icon_details = $patientMasterData['system_icon_details'];

$this->placeholder('patient.icons.system')->captureStart();


$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/views/templates/placeholderPatientIconsSystem.js');

?>
<!-- start  placeholder.patient.icons.system -->
<div id="placeholder.patient.icons.system">
    <!--display system icons-->
    <div id="status_icon" >
        <?php //i don't know why you have a foreach if in theory you know it will be only one ... ?>
        <?php foreach($system_icon_details as $k_icon_det => $v_icon_det):?>
            
            <?php if ( empty($system_icon_data[$k_icon_det][$this->ipid]['show'])) continue; ?>
        
            <?php //else is a a status icon... ?>
            
                <?php $patient_image = $system_icon_data[$k_icon_det][$this->ipid]['show']['image'];?>
                <input type="hidden" value="<?php echo $system_icon_data[$k_icon_det][$this->ipid]['traffic_status']; ?>" name="current_status" id="current_traffic_status" />
                <?php if(in_array($system_icon_data[$k_icon_det][$this->ipid]['show']['id'], array("8","10"))): ?>
                    <!-- bg removed: style="background:#<?php echo $system_icon_data[$k_icon_det][$this->ipid]['show']['color']; ?>"--> 
                    <div data-details_box="<?=$k_icon_det?>" class="patient_icon_cell tabs_table <?php if($system_icon_data[$k_icon_det][$this->ipid]['condition'] == 'patient_status_icon'): echo 'traffic_light'; endif; ?>"  id="sys_icon-<?php echo $k_icon_det; ?>">
                        <?php if(!empty($system_icon_data[$k_icon_det][$this->ipid]['show']['image'])): ?>
                            <img src="<?php echo APP_BASE . 'icons_system/' . $system_icon_data[$k_icon_det][$this->ipid]['show']['image']; ?>"  title="<?php echo $this->translate($system_icon_data[$k_icon_det][$this->ipid]['show']['name']); ?>" />
                        <?php else: ?>
                            <p> &nbsp; </p>
                        <?php endif; ?>
                    </div>
                
                <?php else:?>
                <!-- bg removed:  style="background:#<?php echo $system_icon_data[$k_icon_det][$this->ipid]['show']['color']; ?>"-->
                <div data-details_box="<?=$k_icon_det?>" class="patient_icon_cell <?php if($system_icon_data[$k_icon_det][$this->ipid]['condition'] == 'patient_status_icon'): echo 'traffic_light'; endif; ?> <?php if($system_icon_data[$k_icon_det][$this->ipid]['show']['id'] == '7'): echo 'tabs_table'; endif;?>"  id="sys_icon-<?php echo $k_icon_det; ?>">
                    <?php if(!empty($system_icon_data[$k_icon_det][$this->ipid]['show']['image'])): ?>
                        <?php if($system_icon_data[$k_icon_det][$this->ipid]['show']['id'] == "7" || $system_icon_data[$k_icon_det][$this->ipid]['show']['id'] == "9"): ?>
                            <?php $readmit_pat_dialog = "readmit_patient"; ?>
                        <?php else: ?>
                            <?php $readmit_pat_dialog = ""; ?>
                        <?php endif; ?>
                        <img src="<?php echo APP_BASE . 'icons_system/' . $system_icon_data[$k_icon_det][$this->ipid]['show']['image']; ?>" class="<?php echo $readmit_pat_dialog; ?>" title="<?php echo $this->translate($system_icon_data[$k_icon_det][$this->ipid]['show']['name']); ?>" />
                    <?php else: ?>
                        <p> &nbsp; </p>
                    <?php endif; ?>
                    <div class='btnClose' style='display: none;'></div>
                </div>
                <?php endif; ?>
                            
                            
                            
                <!-- this is a dialog if pat is at home-->
                <div id="status_readmit_data" style="display: none;text-align: left;">
                        <label for="status_admission_date"><?php echo $this->translate('admissiondate'); ?>: </label>
                        <input type="text" name="status_admission_date" id="status_admission_date" value="<?php echo date('d.m.Y', time()); ?>" readonly="readonly" autofocus="false" />
                        <?php echo $this->formSelect('adm_time_h', date('H', time()), array('class'=>'time_sel'), $this->hours); ?>
                        <?php echo $this->formSelect('adm_time_m', date('i', time()), array('class'=>'time_sel'), $this->minutes); ?>
                    <?php if($this->isstandby == "0"):?>
                    <br/>
                        <label> Patienten-Status</label>
                        <select name="status_admission_transition" id="status_admission_transition" >
                            <option value="active">regulärer Patient</option>
                            <option value="standby">Standby / Anfrage</option>
                        </select>
                    <?php else:?>
                        <input type="hidden"  name="status_admission_transition" id="status_admission_transition" value="active" />
                    <?php endif; ?>
                </div>
                
                
                <!-- this is a change color if pat  not at home, andf not at a krakenhause and not in hospital -->
                <?php if($system_icon_data[$k_icon_det][$this->ipid]['condition'] == 'patient_status_icon'): ?>
                <div class="other_lights" id="other_lights" style="display:none">
                    <div class="patient_icon_cell" id="patient_icon_cell_red">
                        <img src="<?php echo APP_BASE . 'icons_system/' . IconsMaster::traffic_light_icons($patient_image, '3'); ?>" rel="3">
                    </div>
                    <div class="patient_icon_cell" id="patient_icon_cell_yellow">
                        <img src="<?php echo APP_BASE . 'icons_system/' . IconsMaster::traffic_light_icons($patient_image, '2'); ?>" rel="2">
                    </div>
                    <div class="patient_icon_cell" id="patient_icon_cell_green">
                        <img src="<?php echo APP_BASE . 'icons_system/' . IconsMaster::traffic_light_icons($patient_image, '1'); ?>" rel="1">
                    </div>
                </div>
                <?php endif; ?>
                
                
        <?php endforeach; ?>
    </div>
</div><!-- end  placeholder.patient.icons.system -->

<?php $this->placeholder('patient.icons.system')->captureEnd() ?>