<?php
$patientMasterData = $this->{'patientMasterData'};
$show_navigation = $patientMasterData['show_navigation'];
$nav = $patientMasterData['nav'];

$this->placeholder('patient.details.simple')->captureStart();

$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/views/templates/placeholderPatientDetailsSimple.js');
?>
<!-- start  placeholder.patient.details.simple -->
<div class="patientinfo"  id="placeholder.patient.details.simple">
   <a href="<?=APP_BASE?>patient/patientoveralllist" class="btnBack"></a>

    <h1 class="patient"><?=$patientMasterData['nice_name'];?>, <?=$patientMasterData['age'];?> - <?=$patientMasterData['epid'];?>
        <?php if ($show_navigation == "1") : ?>
        <select class="change_patient" onChange="window.location=appbase +  'patientcourse/patientcourse?id=' + this.value">
            <option value=""></option>
            <?php foreach ($nav['dropdown'] as $p_id => $p_name) : 
                    if ($p_id == $nav['current'])
                        continue;
            ?>
            <option value="<?=Pms_Uuid::encrypt($p_id);?>" <?=($p_id == $nav['current']) ? 'selected="selected"' : ''?> ><?=$p_name?></option>
            <?php endforeach; ?>
        </select>
        <?php endif; ?>
    </h1>
    <a href="routeplanning/index?id=<?=$this->enc_id?>" class="location" target="_blank"><?=$patientMasterData['nice_address'];?></a>
    <!-- 
    <a href="https://www.google.com/maps/search/?api=1&query=<?=rawurlencode($patientMasterData['nice_address'] . ", Germany")?>" class="location" target="_blank"><?=$patientMasterData['nice_address'];?></a>
     -->
    
    <div class="status">
      <?php echo $this->placeholder('patient.icons.system'); ?>
    </div>
        
</div><!-- end  placeholder.patient.details.simple -->

<?php $this->placeholder('patient.details.simple')->captureEnd(); ?>