<div class="qq-uploader-selector qq-uploader bigupload" qq-drop-area-text="Drop files here" >

    <div class="qq-upload-drop-area-selector qq-upload-drop-area" qq-hide-dropzone>
        <span class="qq-upload-drop-area-text-selector"></span>
    </div>

    <span class="qq-drop-processing-selector qq-drop-processing">
        <span>Processing dropped files...</span>
        <span class="qq-drop-processing-spinner-selector qq-drop-processing-spinner"></span>
    </span>

    <div class="qq-total-progress-bar-container-selector qq-total-progress-bar-container">
        <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-total-progress-bar-selector qq-progress-bar qq-total-progress-bar"></div>
    </div>


    <ul class="qq-upload-list-selector qq-upload-list qq-upload-list-visible" aria-live="polite" aria-relevant="additions removals">
        <li>
            <div class="qq-file-info">

                <div class="qq-file-name">
                    
                    <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-progress-bar-selector qq-progress-bar"></div>
                    
                    <input type="text" class="qquuid_file_title qq-edit-filename-selector" name="qquuid_title[]" tabindex="0"/>
                    <span class="qq-upload-size-selector qq-upload-size filesize"></span>
                    <input type="hidden" class="qquuid" name="qquuid[]" value="" />
                    
                </div>
                
                <span style="float:right;" class="qq-upload-delete-selector qq-upload-delete" href="#" title="<?php echo $this->translate('deleteafile'); ?>"></span>
                   
            </div>
        </li>

    </ul>
    
    <div class="qq-upload-button-selector qq-upload-button browse">
        <div><?php echo $this->translate('upload or drag file'); ?></div>
    </div>
</div>