<?php 

//css append
//$this->headLink()->appendStylesheet(RES_FILE_PATH.'/css/page-css/addorder.css');
//ISPC-2247
?>

<!-- inline script -->
<script type="text/javascript" >

</script>


<div style="clear:both"></div>

<?php if (count($this->SuccessMessages)) : ?>
<!--  SuccessMessages -->
    <ul id="messages" class="success">
    <?php foreach ($this->SuccessMessages as $message) : ?>
        <li><?php echo $this->escape($message); ?></li>
    <?php endforeach; ?>
    </ul>
<?php endif; ?>


<?php if (count($this->ErrorMessages)) : ?>
<!--  ErrorMessages -->
    <ul id="messages" class="err">
    <?php foreach ($this->ErrorMessages as $message) : ?>
        <li><?php echo $this->escape($message); ?></li>
    <?php endforeach; ?>
    </ul>
<?php endif; ?>

<a href="<?php echo $this->url(array('controller'=>'orders' , 'action' => $this->category.'list')) ;?>"><?php echo $this->translate("back")?></a>

<?php
    //echo the form

    $this->form
    ->setAction($this->url())
    ->setMethod(Zend_Form::METHOD_POST)
    ->setAttrib('novalidate', true) // this form is not html5 friendly.. it has closed accordions
    ->setAttrib('autocomplete', false) // this form is not html5 friendly.. it has closed accordions
    ->setAttrib("id", "ordermat")
    ->setAttrib("class", "form_class")
    ->setAttrib("onsubmit", "return form_submit_validate();");
        


    echo $this->form;
?>

