<?php
//TODO-2872 Ancuta 24.03.2020
$patient_enc_id = $this->patient_enc_id;
$lang = $this->translate('order_details');
$choose_lang = $this->translate('choose_order_details');
//dd($this->current_Date_orders);
?>
	<fieldset>
		<legend><?php echo $lang ['[Delivery For]'] ?> <b><?php echo $this->current_patient_name; ?></b></legend>
 

		<div class="po choose_order_cell"  style="width:200px;"
    						data-date="<?php echo  $this->current_Date; ?>"  
    						data-odmy="<?php echo date('d.m.Y',strtotime( $this->current_Date)); ?>"
    						data-patient="<?php echo $this->current_patient; ?>"
    						data-tab="all_active_orders"  
    						<?php if($ord_data['status'] != "canceled"):?>
        						data-order_id ="0"
        						data-current_order_id =""
        						data-order_parent_id =""
        						data-order_step_parent_id =""
        						data-is_parent =""
        						data-interval_type =""
        						data-interval_options =""        						
    						<?php endif;?>
    						>
    						      <button><?php echo $choose_lang ['[Add new order - for date:]'] ?> <?php echo date('d.m.Y',strtotime($this->current_Date));?></span>
    						 
    						</div>


	
	<?php if(!empty($this->current_Date_orders)): ?>
	<?php foreach($this->current_Date_orders as $order_id=>$ord_data):?>
    	<?php if( $ord_data['status'] != 'canceled'): ?>
	<?php $m_date = $this->current_Date?>
		
						<div class="po choose_order_cell" 
    						data-date="<?php echo $m_date; ?>"  
    						data-odmy="<?php echo date('d.m.Y',strtotime($m_date)); ?>"
    						data-patient="<?php echo $this->current_patient; ?>"
    						data-tab="all_active_orders"  
    						<?php if($ord_data['status'] != "canceled"):?>
        						data-order_id ="<?php echo $ord_data['order_id']; ?>"
        						data-current_order_id ="<?php echo $ord_data['current_order_id']; ?>"
        						data-order_parent_id ="<?php echo $ord_data['parent_id']; ?>"
        						data-order_step_parent_id ="<?php echo $ord_data['step_parent_id']; ?>"
        						data-is_parent ="<?php echo $ord_data['is_parent']; ?>"
        						data-interval_type ="<?php echo $ord_data['interval_type']; ?>"
        						data-interval_options ="<?php echo $ord_data['interval_options']; ?>"        						
    						<?php endif;?>
    						>
    						
    						      
    						      <?php
    						         $status_map = array(
    						             'active'=>"_yellow",
    						             'verified'=>"_green",
    						             'paused'=>"_pause_gray",
    						             'planned'=>"_planned_gray",
    						             'canceled'=>"",//_canceled_red
    						             'completed'=>"",
    						             'stopped'=>"_stopped",//      'stopped'=>"_stopped",
    						         );
    						         
    						         $order_Status_class [$m_date][ $ord_data['id'] ] = "";
    					              $order_Status_class [$m_date][ $ord_data['id'] ] = isset($status_map[$ord_data['status']]) ? $status_map[$ord_data['status']] : "";
    						      ?>
    						          
    						      <div style="display: none">
    						      <?php echo 'i '.$ord_data['order_id']; ?><br/>
    						      <?php echo 'p '.$ord_data['parent_id']; ?><br/>
    						      <?php echo 'sp '.$ord_data['step_parent_id']; ?><br/>
    						      </div>
    						       <button>
    						       <?php 
    						       $edit_text = $choose_lang['[Edit order: started on %start_order_date%  status :]'];
    						          $edit_button = str_replace('%start_order_date% ', date('d.m.Y',strtotime($ord_data['order_date'])), $edit_text);
    						       ?>
    						        <?php echo $edit_button;
    					 
    						        ?> <span class="order_status_cell <?php echo $order_Status_class [$m_date][ $ord_data['id'] ];?>" style="float: right; margin-top:-7px;"></span>
    						      </button>
    						</div>
		<?php endif;?>
		<?php endforeach;?>
		<?php endif;?>
</fieldset>