<?php

$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/data_tables/jquery.dataTables.js?'.date('Ymd'));
$this->headScript()->appendFile(RES_FILE_PATH.'/javascript/data_tables/dataTables.jqueryui.js?'.date('Ymd'));
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/data_tables/dataTables.jqueryui.css?' . date('Ymd'));
$this->headLink()->appendStylesheet(RES_FILE_PATH . '/css/page-css/listscommon.css?' . date('Ymd'));

?>

<script type="text/javascript">

</script>

<br/>

<div style="clear:both;"></div>

 <h1><? echo $this->translate('list_recipients'); ?></h1>
<br/>
<div style="clear:both;"></div>
	
<form  action="<?php echo APP_BASE.'orders/recipientslist?op=save_recipients'; ?>" method="post" >
<fieldset>
    <legend><?php echo $this->translate("userpseudo");?></legend>
    <table id="pseudo_table" class="pseudo_table table-striped table-bordered table-hover table-condensed dataTable no-footer  left_menu_datatable">
    </table>
</fieldset>

<fieldset>
    <legend><?php echo $this->translate("users");?></legend>
    <table id="table" class="table table-striped table-bordered table-hover table-condensed dataTable no-footer  left_menu_datatable">
    </table>	
</fieldset>

<input type="submit" value="<?php echo $this->translate('save')?>">

</form>